### PR TITLE
Fix globally valid parameters

### LINKED ISSUE #24838: The `"global": "parameters": {}` section in the JSON dump should not contain `control_tags`
## Reason
The `control_tags` parameter is not valid everywhere but gets added to the `"global": "parameters": {}` section in the JSON dump.

## Design
Refactor the valid parameters and add parameters that _belong_ to teh Parser directly. Only those should appear in that JSON section.

## Impact
Fix autocomplete. @brandonlangley

### PR DESCRIPTION
**Pull request by dschwen**
Closes #24838

### CODE REVIEW

**Review by lindsayad — COMMENTED** [review]
This looks fine to me but how does it fix the referenced issue? Is this something we can test?

File: framework/src/parser/Parser.C [hunk 1]
```diff
@@ -173,6 +173,27 @@ Parser::Parser(MooseApp & app, ActionWarehouse & action_wh)
...
 Parser::~Parser() {}
 
+InputParameters
+Parser::validParams()
+{
+  InputParameters params = emptyInputParameters();
+
+  /**
+   * Add the "active" and "inactive" parameters so that all blocks in the input file can selectively
+   * create white or black lists of active/inactive sub-blocks.
```
Comment (GiudGiud) [inline framework/src/parser/Parser.C:183]:
```suggestion
   * create lists of active/inactive sub-blocks.
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]

**Comment by dschwen** [comment]
> This looks fine to me but how does it fix the referenced issue? Is this something we can test?

It fixes it by not advertising `control_tags` as valid in our syntax dump in locations where it will lead to a parse error. Not sure how to test this.

**Review by GiudGiud — APPROVED** [review]

**Review by lindsayad — APPROVED** [review]
