### PR TITLE
Fix issues with output_q option in DomainIntegralAction

### LINKED ISSUE #9890: Problems with `output_q` option in DomainIntegralAction
### Description of the enhancement or error report
There are a couple of issues with the `output_q=false` option in the `DomainIntegral` Action, which make it unusable with interaction integrals.

### Rationale for the enhancement or information for reproducing the error
If this option is set to false with the InteractionIntegral, an error occurs because it incorrectly skips creation of some needed Materials. Also, if this option is true, it passes options to the Postprocessors that no longer exist.

### Identified impact
Minor changes to DomainIntegralAction.C

### PR DESCRIPTION
**Pull request by bwspenc**
closes #9890

### CODE REVIEW

**Comment by bwspenc** [comment]
Pinging @hoffwm

**Review by permcody — APPROVED** [review]

File: modules/solid_mechanics/src/actions/DomainIntegralAction.C [hunk 1]
```diff
@@ -402,14 +398,6 @@ DomainIntegralAction::act()
           av_name_stream << av_base_name << "_" << _ring_vec[ring_index];
           std::ostringstream pp_name_stream;
           pp_name_stream << pp_base_name << "_" << _ring_vec[ring_index];
```
Comment (dschwen) [inline modules/solid_mechanics/src/actions/DomainIntegralAction.C]: we're not using string streams for this purpose anymor (we have `MooseUtils::stringify()` now)
