### PR TITLE
FancyExtruderGenerator Extra Element ID Fix and Adding Test Cases

### LINKED ISSUE #18087: Enhancement of `FancyExtruderGenerator` Functionalities
## Reason
The current version of `FancyExtruderGenerator` does not retain element extra integers and subdomain/nodeset/sideset names during extrusion. Additionally, the useful "swap" functionality only works for subdomain IDs (not for element extra integers). 

## Design
The following new functionalities will be added to the FancyExtruderGenerator object.
1. Retain all existing element extra integers of the input mesh during extrusion;
2. Retain all existing subdomain, nodeset and sideset name maps of the input mesh during extrusion;
3. Enable element extra integer "swap", which is similar to the existing subdomain_swaps.

## Impact
This update will enable the implementation of a series of new features being developed as part of the `NEAMS MOOSE Meshing Improvements` project, including Reporting ID and Control Drum Meshing. It will also generally enhance the functionalities of `FancyExtruderGenerator` for other applications.

### PR DESCRIPTION
**Pull request by ScottRichards-ANL**
This commit resolves an issue when extruding a mesh, closes #18087.  Extra element ID are now preserved on the mesh when extruding.

### CODE REVIEW

**Comment by miaoyinb** [comment]
@friedmud This is the PR to update `FancyExtruderGenerator` that @eshemon discussed with you before. Thanks.

**Comment by loganharbour** [comment]
@ScottRichards-ANL: you've been added to an organization to enable automatic testing of your PRs. Once you join, your PRs will no longer require activation for testing.

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 1]
```diff
@@ -123,6 +136,35 @@ FancyExtruderGenerator::FancyExtruderGenerator(const InputParameters & parameter
     for (unsigned int j = 0; j < elevation_swaps.size(); j += 2)
       elevation_swap_pairs[elevation_swaps[j]] = elevation_swaps[j + 1];
   }
+
+  if (_elem_integers_swaps.size() &&
+      (_elem_integers_swaps.size() != num_elevations * _elem_integer_names_to_swap.size()))
+    paramError("elem_integers_swaps",
+               "If specified, 'elem_integers_swaps' must be the same length as the product of the "
+               "length of 'heights' and the length of 'elem_integer_names_to_swap' in ",
+               name());
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:145]:
```suggestion
               "length of 'heights' and the length of 'elem_integer_names_to_swap'");
```

`paramError()` provides context (either input line name, or object name and type if created via an action) so the additional context here is extraneous.

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 2]
```diff
@@ -135,6 +177,31 @@ FancyExtruderGenerator::generate()
...
+    if (_input->has_elem_integer(_elem_integer_names_to_swap[i]))
+      _elem_integer_indices_to_swap.push_back(
+          _input->get_elem_integer_index(_elem_integer_names_to_swap[i]));
+    else
+      paramError("elem_integer_names_to_swap",
+                 "Element ",
+                 i + 1,
+                 " of elem_integer_names_to_swap in ",
+                 name(),
+                 " is not a valid extra element integer of the input mesh.");
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:191]:
```suggestion
                 " of 'elem_integer_names_to_swap' is not a valid extra element integer of the input mesh.");
```

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 3]
```diff
@@ -135,6 +177,31 @@ FancyExtruderGenerator::generate()
...
+  const unsigned int num_extra_elem_integers = _input->n_elem_integers();
+  std::vector<std::string> id_names;
+
+  for (unsigned int i = 0; i < num_extra_elem_integers; i++)
+    id_names.push_back(_input->get_elem_integer_name(i));
+
+  // retreive subdomain/sideset/nodeset name maps
+  auto input_subdomain_map = _input->get_subdomain_name_map();
+  auto input_sideset_map = _input->boundary_info->get_sideset_name_map();
+  auto input_nodeset_map = _input->boundary_info->get_nodeset_name_map();
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:203]:
```suggestion
  const auto & input_subdomain_map = _input->get_subdomain_name_map();
  const auto & input_sideset_map = _input->get_boundary_info()->get_sideset_name_map();
  const auto & input_nodeset_map = _input->get_boundary_info()->get_nodeset_name_map();
```

We try to use the APIs (here, for boundary_info) as much as possible. The fact that boundary info is a public member variable is just something we're stuck with in libmesh due to deprecation

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 4]
```diff
@@ -510,6 +577,33 @@ FancyExtruderGenerator::generate()
...
         new_elem = mesh->add_elem(new_elem);
 
+        // maintain extra integers
+        if (num_extra_elem_integers > 0)
+        {
+          for (unsigned int i = 0; i < num_extra_elem_integers; i++)
+          {
+            // declare the "control_drum_id" when the first elem is added
+            if (!mesh->has_elem_integer(id_names[i]))
+              mesh->add_elem_integer(id_names[i]);
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:587]: Can you add all of the integers that don't exist up front instead of within the element loop? Also - remove the comment that's hanging around

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 5]
```diff
@@ -510,6 +577,33 @@ FancyExtruderGenerator::generate()
...
+          for (unsigned int i = 0; i < _elem_integer_indices_to_swap.size(); i++)
+          {
+            auto & elevation_extra_swap_pairs = _elem_integers_swap_pairs[i * _heights.size() + e];
+
+            auto new_extra_id_it = elevation_extra_swap_pairs.find(
+                elem->get_extra_integer(_elem_integer_indices_to_swap[i]));
+
+            if (new_extra_id_it != elevation_extra_swap_pairs.end())
+              new_elem->set_extra_integer(_elem_integer_indices_to_swap[i],
+                                          new_extra_id_it->second);
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:603]:
```suggestion
            const auto new_extra_id = elevation_extra_swap_pairs.at(
                elem->get_extra_integer(_elem_integer_indices_to_swap[i]));

            if (new_extra_id_it != elevation_extra_swap_pairs.end())
              new_elem->set_extra_integer(_elem_integer_indices_to_swap[i],
                                          new_extra_id);
```

In the off case that this doesn't exist, we'll get a more meaningful assertion from c++ (hopefully) vs trying to access the beyond-the-end iterator

File: framework/src/meshgenerators/FancyExtruderGenerator.C [hunk 6]
```diff
@@ -563,6 +657,23 @@ FancyExtruderGenerator::generate()
...
+  if (!input_sideset_map.empty())
+  {
+    auto & new_sideset_map = mesh->boundary_info->set_sideset_name_map();
+    new_sideset_map.insert(input_sideset_map.begin(), input_sideset_map.end());
+  }
+  if (!input_nodeset_map.empty())
+  {
+    auto & new_nodeset_map = mesh->boundary_info->set_nodeset_name_map();
+    new_nodeset_map.insert(input_nodeset_map.begin(), input_nodeset_map.end());
+  }
```
Comment (loganharbour) [inline framework/src/meshgenerators/FancyExtruderGenerator.C:675]:
```suggestion
  if (!input_subdomain_map.empty())
    mesh->set_subdomain_name_map().insert(input_subdomain_map.begin(), input_subdomain_map.end());
  if (!input_sideset_map.empty())
    mesh->get_boundary_info()->set_sideset_name_map().insert(input_sideset_map.begin(), input_sideset_map.end());
  if (!input_nodeset_map.empty())
    mesh->get_boundary_info()->set_nodeset_name_map().insert(input_nodeset_map.begin(), input_nodeset_map.end());
```

File: test/tests/meshgenerators/fancy_extruder_generator/tests [hunk 7]
```diff
@@ -28,4 +28,14 @@
     design = 'FancyExtruderGenerator.md'
     issues = '#16902'
   []
+  [extruder_with_element_extra_interger_swap]
+    type = 'Exodiff'
+    input = fancy_extruder_with_element_extra_integer_swap.i
+    exodiff = 'fancy_extruder_with_element_extra_integer_swap_out.e'
+    recover = false
```
Comment (loganharbour) [inline test/tests/meshgenerators/fancy_extruder_generator/tests:35]:
```suggestion
```

I believe that `recover = false` is only needed when we're doing `--mesh-only`. Because you're actually executing something here (even with `solve = false`), this shouldn't be needed

**Review by loganharbour — CHANGES_REQUESTED** [review]
All minor comments. In general, looks good to me.

File: framework/src/meshgenerators/FancyExtruderGenerator.C (hunk 5 above)
Comment (miaoyinb) [reply framework/src/meshgenerators/FancyExtruderGenerator.C:603]: Thanks, @loganharbour 
We have addressed all your comments except for this one on our local branch.
For this one,  I tried (I think that's what you suggested)
```
const auto new_extra_id = elevation_extra_swap_pairs[elem->get_extra_integer(_elem_integer_indices_to_swap[i])];
new_elem->set_extra_integer(_elem_integer_indices_to_swap[i], new_extra_id);
```
The code then just converts any elem extra integers that are not specified in `elem_integers_swaps` to 0 instead of retaining the original values.
I think the original approach works well as `if (new_extra_id_it != elevation_extra_swap_pairs.end())` prevents any access to beyond-the-end iterator. Any more suggestion?

Comment (loganharbour) [reply framework/src/meshgenerators/FancyExtruderGenerator.C:603]: Nope - that works for me. I failed to catch the original logic!

Go ahead and push and we should be good to approve. Just please click "resolve conversation" on the comments that you have resolved; it makes the review process easier.

**Comment by miaoyinb** [comment]
@loganharbour Any idea how to solve the three failed tests issue? Thanks in advance.

**Comment by loganharbour** [comment]
@miaoyinb - all of those failures are irrelevant. Once we get them fixed (separate from this PR), I'll invalidate, re-run, and get this in. Sorry for the delay.

**Comment by miaoyinb** [comment]
@loganharbour Let us know if any additional changes are needed before merging. Thanks.

**Review by loganharbour — APPROVED** [review]
Looks good. Sorry for the delay - we had a lot sitting around.

**Comment by miaoyinb** [comment]
> Looks good. Sorry for the delay - we had a lot sitting around.

Great, thanks. We appreciate your review. 👍
