### PR TITLE
Use of restartable data boolean to determine first step

### LINKED ISSUE #7457: Restart Fails with conditional Statements t_step==0 in Solid/Tensor Mechanics
### Description of the enhancement or error report
Conditional statements looking for t_step == 0 or 1 cause restart to fail, since restarts resets the time step to 0 and applies the condition incorrectly on restart.  This issue causes on restart stresses and thus displacements to increase on first time step beyond what is expected. MOOSE also needs tests to verify that restarts work correctly.

### Rationale for the enhancement or information for reproducing the error
Correct statement should also check to see if restart with _tstep == 0 && !_app.isRestarting().

### Identified impact
Affects restarts for MOOSE and BISON

@sapitts @permcody

### PR DESCRIPTION
**Pull request by sapitts**
### Relevant design information

 The use of the `_app.isRestarting()` flag is replaced by a boolean as suggested by @friedmud and @permcody in Solid and Tensor Mechanics.  The change to the boolean does not remove the need of the materials to query `_t_step`, but it does more gracefully allow for restarts.

@permcody  please review.
### Test Cases

No test cases modified or added.

Closes #7457

### CODE REVIEW

File: modules/solid_mechanics/src/materials/ConstitutiveModel.C [hunk 1]
```diff
@@ -93,13 +95,19 @@ ConstitutiveModel::applyThermalStrain(unsigned qp,
                                       SymmTensor & strain_increment,
                                       SymmTensor & d_strain_dT)
 {
-  if (_has_temp && _t_step != 0)
+  if (_t_step == 1)
```
Comment (permcody) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: This PR looks fine but in terms of defensible programming I would generally prefer to see `_t_step >= 1` instead of the current line in case the linear behavior of `_t_step` is changed in the future.

Comment (permcody) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: BTW - I don't think we have any intention of creating an execution that would do something different but you never know 😄

File: modules/heat_conduction/src/postprocessors/ThermalConductivity.C [hunk 2]
```diff
@@ -24,7 +24,8 @@ ThermalConductivity::ThermalConductivity(const InputParameters & parameters) :
     _flux(getPostprocessorValue("flux")),
     _T_hot(getPostprocessorValue("T_hot")),
     _length_scale(getParam<Real>("length_scale")),
-    _k0(getParam<Real>("k0"))
+    _k0(getParam<Real>("k0")),
+    _zeroth_step(declareRestartableData<bool>("zeroth_step", true))
```
Comment (dschwen) [inline modules/heat_conduction/src/postprocessors/ThermalConductivity.C]: I would have fewer problems pronouncing this if it was called `_step_zero`...

File: modules/solid_mechanics/src/materials/ConstitutiveModel.C [hunk 3]
```diff
@@ -93,13 +95,19 @@ ConstitutiveModel::applyThermalStrain(unsigned qp,
                                       SymmTensor & strain_increment,
                                       SymmTensor & d_strain_dT)
 {
-  if (_has_temp && _t_step != 0)
+  if (_t_step >= 1)
+    _zeroth_step = false;
+
+  if (_t_step >= 2)
+    _first_step = false;
+
```
Comment (dschwen) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: The above logic looks rather awkward. Rather than two bools why don't you store a copy of `_t_step`?

File: modules/heat_conduction/src/postprocessors/ThermalConductivity.C (hunk 2 above)
Comment (sapitts) [inline modules/heat_conduction/src/postprocessors/ThermalConductivity.C]: Well that's easy to fix: just don't read the code out loud.

File: modules/solid_mechanics/src/materials/ConstitutiveModel.C (hunk 3 above)
Comment (permcody) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: Well would you call that? Stored copy of _t_step? Then you have a line of code that looks like `_copy_t_step = _t_step`. That's just as awkward.

Comment (dschwen) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: Could be `_last_completed_step` or whatever makes sense here. At least that way we would only use _one_ variable to store that _one_ piece of information.

Comment (sapitts) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: I could do a restartable data unsigned int instead of a bool?  Also keep in mind this logic is in solid mechanics SolidModel and ConstitutiveModel, so the awkwardness will go away with solid mechanics; not that solid mechanics is a good excuse to avoid 'doing things right'

Comment (permcody) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: Two Booleans < one unsigned int

Either way, I'm not sure I really care, if you want to store a local copy of the time step, that's fine as long as you keep updating it so it actually makes sense. This implementation is also fine.

Comment (sapitts) [inline modules/solid_mechanics/src/materials/ConstitutiveModel.C]: In that case let's leave this as is with the two booleans:  it's a more transparent replacement for the `_t_step` in the materials for the Bison folks so that I can convince them to merge my bison PR.

**Comment by permcody** [comment]
👍
