### PR TITLE
fix swapped boundary ids during accmg stitching

### LINKED ISSUE #28955: Wrong Boundary IDs Used in Stitching in AdvancedConcentricCircleGenerator
### Bug Description

In `AdvancedConcentricCircleGenerator`, wrong boundary IDs are used when stitching the unit slices together. Although a later stitching seems magically to make this MG work fine. This bug needs to be fixed.

### Steps to Reproduce

```
[Mesh]
  [inner]
    type = AdvancedConcentricCircleGenerator
    ring_radii = '56.7519'
    ring_intervals = '1'
    ring_block_ids = '8000'
    num_sectors = 180
    preserve_volumes = false
    tri_element_type = TRI6
    quad_element_type = QUAD8
  []
[]
```
The screen printing when running this shows incorrect matching node numbers.

### Impact

Fixing this bug would eliminate the confusion and make debugging of other issues easier.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #28955

### CODE REVIEW

File: modules/reactor/src/meshgenerators/AdvancedConcentricCircleGenerator.C [hunk 1]
```diff
@@ -286,7 +286,7 @@ AdvancedConcentricCircleGenerator::generate()
     MeshTools::Modification::rotate(other_mesh, -_azimuthal_angles[i], 0, 0);
     mesh->prepare_for_use();
     other_mesh.prepare_for_use();
-    mesh->stitch_meshes(other_mesh, SLICE_BEGIN, SLICE_END, TOLERANCE, true);
```
Comment (GiudGiud) [inline modules/reactor/src/meshgenerators/AdvancedConcentricCircleGenerator.C:289]: add a comment for why it's that way and not the other way

**Review by GiudGiud — APPROVED** [review]

**Comment by roystgnr** [comment]
Thanks for this!
