### PR TITLE
Fixes problem with xda and xdr output enabled

### LINKED ISSUE #6525: Cannot output XDA and XDR simultaneously
### Description of the enhancement or error report
If you set `xda = true` and `xdr = true` in an `Outputs` block in an input file you get this:

```bash
*** ERROR ***
An output file with the name, out_0000, already exists.

[2] /Users/gastdr/projects/moose/framework/src/outputs/OutputWarehouse.C, line 140, compiled nodate at notime
```

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #6525)

### CODE REVIEW

File: framework/src/outputs/XDA.C [hunk 1]
```diff
@@ -44,15 +44,17 @@ XDA::XDA(const InputParameters & parameters) :
 void
 XDA::output(const ExecFlagType & /*type*/)
 {
+  std::string fname = filename();
+  std::string base = fname.substr(0, fname.size()-4);
```
Comment (permcody) [inline framework/src/outputs/XDA.C]: The second argument here could be negative. Since len is of type `size_t` this could be bad. I suggest a mooseError or some other sanity check just in case.

Comment (aeslaughter) [inline framework/src/outputs/XDA.C]: It can't be, the filename() method always adds ".xda" or ".xdr", so it has
a minimum of zero.

Comment (permcody) [inline framework/src/outputs/XDA.C]: I see, that's true until somebody changes that someday in the future :)

File: framework/src/outputs/XDA.C [hunk 2]
```diff
@@ -44,15 +44,17 @@ XDA::XDA(const InputParameters & parameters) :
...
   if (_binary)
   {
-    _mesh_ptr->getMesh().write(filename()+"_mesh.xdr");
-    _es_ptr->write (filename()+".xdr", ENCODE, EquationSystems::WRITE_DATA | EquationSystems::WRITE_ADDITIONAL_DATA);
+    _mesh_ptr->getMesh().write(base + "_mesh.xdr");
```
Comment (permcody) [inline framework/src/outputs/XDA.C]: You are effectively not using `filename()` at all now. Yes you call it to retrieve the filename with the suffix but then you immediately strip the suffix then manually add it back in here and just below? This seems clunky, I assume you need filename for an external interface but perhaps you should make use of the suffix you strip too?

Comment (aeslaughter) [inline framework/src/outputs/XDA.C]: @permcody The filename() method is used by the OutputWarehouse to check if multiple files exist with the same name. Hence, it really needs the extension to be accurate. Currently, for xda/xdr it doesn't.

The XDR/XDA object does use filename, it is the name used by the EquationSystems object write (`_es_ptr->write`). This object also needs to write a second file for the mesh, thus the "_mesh" suffix is inserted.

File: framework/src/outputs/XDA.C (hunk 1 above)
Comment (aeslaughter) [inline framework/src/outputs/XDA.C]: I will add a check.

File: framework/src/outputs/XDA.C (hunk 2 above)
Comment (permcody) [inline framework/src/outputs/XDA.C]: I'm just saying that you have duplicated logic in both methods
```
if (_binary)
    // Append ".xdr";
  else
    // Append ".xda";
```

I can merge as is, it just interesting that you throw the suffix away and then have it hardcoded to put it back on again.

Comment (aeslaughter) [inline framework/src/outputs/XDA.C]: @permcody I fixed this again to use a std::string insert, it is more better.

**Comment by permcody** [comment]
:+1:
