### PR TITLE
Fixed deprecated params output

### LINKED ISSUE #6780: Deprecated messages only output for one deprecated object per input file
### Description of the enhancement or error report

When multiple deprecated objects are present in an input file, a warning for only one of the objects is printed and the others ignored. This is especially unfortunate if the date of deprecation is past for one of the ignored kernels which usually throws an error
### Rationale for the enhancement or information for reproducing the error

This can be repeated by deprecating the kernels in examples/ex06_transient/src/base/ExampleApp.C by

```
registerDeprecatedObjectName(ExampleConvection, "ExampleConvection", "11/11/2010 00:00");
registerDeprecatedObjectName(ExampleDiffusion, "ExampleDiffusion", "11/11/2010 00:00");
registerDeprecatedObjectName(ExampleTimeDerivative, "ExampleTimeDerivative", "11/11/2016 00:00");
```

and observing that when ex06.i is run, only the warning for ExampleTimeDerivative prints.
### Identified impact

Animals with deprecated objects may see more warnings or errors as this is fixed.

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #6780

### CODE REVIEW

**Comment by friedmud** [comment]
I'm not sure this solves the problem.  Sure - it lets the deprecated message come out once - but it also makes it come out every time that deprecated object is used.

For instance: in your test, if you use that object twice in the same input file you would see the deprecation message twice.

This also makes the stack trace only come out once (even for multiple deprecated parameters).

The larger fix here is difficult.  You need to keep track of which deprecated parameters have had a warning printed about them... and make sure to only print them once.

**Review by friedmud — CHANGES_REQUESTED** [review]
Does not completely solve the problem - see above comment.

**Comment by friedmud** [comment]
Note: you can't use `mooseDoOnce()` in this solution because it is set with a static variable... which will be the same for many parameters.  It really does need something more sohpisticated here.

File: framework/include/parser/Parser.h [hunk 1]
```diff
@@ -243,6 +243,9 @@ class Parser : public ConsoleStreamInterface, public hit::Walker
   /// The current stream object used for capturing errors during extraction
   std::ostringstream * _current_error_stream;
 
+  /// Tracks whether a deprecated param has had its warning message printed already.
+  std::unordered_set<std::string> _deprec_param_tracker;
```
Comment (socratesgorilla) [inline framework/include/parser/Parser.h:247]: @permcody Here are the C++ changes at least -- Not 100% sure this is the best choice of container here or if there's a way to make this more elegant in general

Comment (socratesgorilla) [reply framework/include/parser/Parser.h:247]: I figured unordered_set because it doesn't need to be sorted, just iterated, and I believe average case complexity is faster than vector?

Comment (permcody) [reply framework/include/parser/Parser.h:247]: Your first priority is to get something that works and this does that. If it's in a time-sensitive area, then you can take a deeper look at optimizing something like container types. For what it's worth, vectors and arrays are by far the fastest containers for pretty much all but the most diabolical cases (like repeatedly inserting or removing in the middle). `unordered_set`s are surprisingly fast, almost always faster than just plain `set` even in cases where you'd expect `set`s underlying data structure to really fly.

File: framework/src/parser/Parser.C [hunk 2]
```diff
@@ -1206,6 +1206,13 @@ Parser::extractParams(const std::string & prefix, InputParameters & p)
     if (node && node->type() == hit::NodeType::Field)
     {
       p.set_attributes(it.first, false);
+
+      // Check if we have already printed the deprec param message.
+      // If we haven't, add it to the tracker, and print it.
+      if (!_deprec_param_tracker.count(it.first))
+        if (p.attemptPrintDeprecated(it.first))
```
Comment (friedmud) [inline framework/src/parser/Parser.C:1213]: Do we really need to know if it was printed or not?  If it wasn't... then it won't be in the future... right?

**Review by friedmud — DISMISSED** [review]
This is looking really good - just one question.  Thanks for working this out!

File: framework/src/parser/Parser.C (hunk 2 above)
Comment (socratesgorilla) [reply framework/src/parser/Parser.C:1213]: I'm confused what you mean here. All that happens here is that it checks if the message has been printed for that variable.

File: test/tests/misc/deprecation/tests [hunk 3]
```diff
@@ -62,4 +62,12 @@
     design = 'InputParameters.md'
     issues = '#15497'
   []
+  [deprec_param_duplicate_print]
+    type = RunApp
+    input = 'deprecated_param.i'
+    custom_evaluation_script = 'deprec_param_custom_eval.py'
+    issues = '#6780'
+    requirement = 'The system shall output one warning per deprecated parameter, regardless of how many deprecated params are in the system.'
```
Comment (GiudGiud) [inline test/tests/misc/deprecation/tests:70]:
```suggestion
    requirement = 'The system shall output one warning per deprecated parameter, regardless of how many deprecated parameters are in the system.'
```

File: test/tests/misc/deprecation/tests [hunk 4]
```diff
@@ -62,4 +62,12 @@
...
+  []
+
```
Comment (GiudGiud) [inline test/tests/misc/deprecation/tests:72]:
```suggestion
```

File: test/tests/misc/deprecation/deprecated_param.i [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+    D = 4
+  []
+
+  [diffusion2]
+    type = DeprecatedParamDiffusion
+    variable = u
+    D = 5
+    E = 2
+  []
+
```
Comment (GiudGiud) [inline test/tests/misc/deprecation/deprecated_param.i:23]:
```suggestion
```

File: test/tests/misc/deprecation/deprecated_param.i [hunk 6]
```diff
@@ -0,0 +1,32 @@
+[Mesh/gen]
+  type = GeneratedMeshGenerator
+  dim =1
+[]
+
+[Variables/u]
+
```
Comment (GiudGiud) [inline test/tests/misc/deprecation/deprecated_param.i:7]:
```suggestion
```

File: test/src/kernels/DeprecatedParamDiffusion.C [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "DeprecatedParamDiffusion.h"
+
+registerMooseObject("MooseTestApp", DeprecatedParamDiffusion);
+
+// MooseDocs::start
```
Comment (GiudGiud) [inline test/src/kernels/DeprecatedParamDiffusion.C:14]: what is this

File: test/src/kernels/DeprecatedParamDiffusion.C [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+InputParameters
+DeprecatedParamDiffusion::validParams()
+{
+  InputParameters params = Diffusion::validParams();
+  params.addDeprecatedParam<Real>("D", 1, "The diffusivity coefficient.", "This is deprecated");
+  params.addDeprecatedParam<Real>(
+      "E", 1, "The ediffusivity coefficient.", "This is also deprecated");
```
Comment (GiudGiud) [inline test/src/kernels/DeprecatedParamDiffusion.C:21]:
```suggestion
      "E", 1, "The E diffusivity coefficient.", "This is also deprecated");
```

File: test/src/kernels/DeprecatedParamDiffusion.C [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+  return params;
+}
+// MooseDocs::end
+
+DeprecatedParamDiffusion::DeprecatedParamDiffusion(const InputParameters & parameters)
+  : Diffusion(parameters),
+
```
Comment (GiudGiud) [inline test/src/kernels/DeprecatedParamDiffusion.C:28]:
```suggestion
```

File: framework/src/utils/InputParameters.C [hunk 10]
```diff
@@ -96,16 +96,23 @@ InputParameters::set_attributes(const std::string & name, bool inserted_only)
...
-      if (_params.count(name) && !_params[name]._deprecation_message.empty())
-        mooseDeprecated(
-            "The parameter '", name, "' is deprecated.\n", _params[name]._deprecation_message);
+      mooseDeprecated(
+          "The parameter '", name, "' is deprecated.\n", _params[name]._deprecation_message);
+      return true;
     }
   }
+  return false;
 }
```
Comment (GiudGiud) [inline framework/src/utils/InputParameters.C:115]:
```suggestion
}

```

File: framework/src/parser/Parser.C [hunk 11]
```diff
@@ -1206,6 +1206,13 @@ Parser::extractParams(const std::string & prefix, InputParameters & p)
     if (node && node->type() == hit::NodeType::Field)
     {
       p.set_attributes(it.first, false);
+
+      // Check if we have already printed the deprec param message.
```
Comment (GiudGiud) [inline framework/src/parser/Parser.C:1210]:
```suggestion
      // Check if we have already printed the deprecated param message.
```

File: framework/include/base/MooseError.h [hunk 12]
```diff
@@ -223,24 +223,26 @@ mooseDeprecatedStream(S & oss, bool expired, Args &&... args)
...
     mooseError("\n\nDeprecated code:\n", std::forward<Args>(args)...);
 
-  mooseDoOnce(std::ostringstream ss; mooseStreamAll(ss, args...);
-              std::string msg = mooseMsgFmt(
-                  ss.str(),
+  std::ostringstream ss;
+  mooseStreamAll(ss, args...);
+  std::string msg =
+      mooseMsgFmt(ss.str(),
                   "*** Warning, This code is deprecated and will be removed in future versions:",
```
Comment (GiudGiud) [inline framework/include/base/MooseError.h:230]: could we moose do once ONLY that line?
That way we have all the deprecated messages, and this shared message only once

**Review by GiudGiud — CHANGES_REQUESTED** [review]
this PR is actually quite time sensitive now that I've just deprecated 20 or so parameters in the parsed expressions. 

Would be great to merge asap

File: framework/include/base/MooseError.h (hunk 12 above)
Comment (socratesgorilla) [reply framework/include/base/MooseError.h:230]: Which message do you mean, the `warning this code is deprecated` one?

Comment (GiudGiud) [reply framework/include/base/MooseError.h:230]: Yes

**Review by GiudGiud — DISMISSED** [review]

**Comment by socratesgorilla** [comment]
@friedmud any chance on finishing review anytime soon on this? don't want to fix the merge conflicts until its ready to go

File: framework/include/base/MooseError.h [hunk 13]
```diff
@@ -238,28 +238,29 @@ mooseDeprecatedStream(S & oss, const bool expired, const bool print_title, Args
...
+  {
+    if (libMesh::global_n_processors() == 1)
+      print_trace(ss);
+    else
+      libMesh::write_traceout();
+    {
+      Threads::spin_mutex::scoped_lock lock(moose_stream_lock);
+      oss << ss.str() << std::endl;
+    };
+  };
```
Comment (GiudGiud) [inline framework/include/base/MooseError.h:263]: need to revert this, this doesnt work

**Review by GiudGiud — CHANGES_REQUESTED** [review]
This correctly fixes the deprecation of multiple parameters however it breaks the deprecation of objects, see my comment.

I m interested on improving that other thing, but I think it will be difficult. Let s keep this PR to parameter deprecation

Can you also please remove 2 line breaks from this?
```
/Users/giudgl/projects/moose_v4/test/tests/misc/deprecation/deprecated_param.i:13: (Kernels/diffusion/D):
The parameter 'D' is deprecated.
This is deprecated



/Users/giudgl/projects/moose_v4/test/tests/misc/deprecation/deprecated_param.i:20: (Kernels/diffusion2/E):
The parameter 'E' is deprecated.
This is also deprecated
```

File: framework/include/base/MooseError.h [hunk 14]
```diff
@@ -240,27 +240,37 @@ mooseDeprecatedStream(S & oss, const bool expired, const bool print_title, Args
...
-  if (Moose::show_trace)
+  size_t pos = ss.str().find('\n');
+  if (pos != std::string::npos)
   {
-    if (libMesh::global_n_processors() == 1)
-      print_trace(ss);
-    else
-      libMesh::write_traceout();
+    auto hash = std::hash<std::string>{}(ss.str().substr(pos + 1));
+    auto iter = Moose::_deprec_tracker.find(hash);
```
Comment (GiudGiud) [inline framework/include/base/MooseError.h:247]: system by system is the way to go, not a global attribute 

This is also relying on convoluted logic
"hash the part of the message before the line break" that works fine now but could be a pain to debug when it stops working

This commit should be reverted. What kind of issue are you having with the factory tracking?

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/include/base/MooseError.h (hunk 14 above)
Comment (socratesgorilla) [reply framework/include/base/MooseError.h:247]: There is no technical issue with implementing the object tracking in the factory system per se. 

My issue is more that we have to create two different systems in two different places that don't really interact with each other in order to keep track of their deprecation outputs. Instead of doing that, I figured it would be better to have all of them stored in one singular location that doesn't differentiate between what kind of deprecated output it is, just that `mooseDeprecatedStream` was called. Doing it this means that if we add new kinds of deprecation output, the system would still work with no modifications needed, and a universal tracker leaves a smaller footprint.

Design-wise, this does seem like a better solution. If the primary issue with the universal tracker is the line break check being too brittle, then that should be fixable.

Comment (GiudGiud) [reply framework/include/base/MooseError.h:247]: it s not a lot of code to duplicate here. Placing code in Moose.C is an easy solution but it s not sustainable. We need to distribute the codes between systems or concentrate it in utils if there's good redundancy.

in general we should shun global variables. There's threading issues you need to be wary of when you use global variables, it s not worth it

Comment (socratesgorilla) [reply framework/include/base/MooseError.h:247]: @loganharbour

Comment (GiudGiud) [reply framework/include/base/MooseError.h:247]: Let s have a look. Where is this triggered for creating objects?

**Comment by GiudGiud** [comment]
Down for a review @friedmud

**Review by GiudGiud — APPROVED** [review]
Approving the part that is not mine.

**Comment by GiudGiud** [comment]
Any volunteers among our 6 code owners?

**Review by permcody — APPROVED** [review]
