### PR TITLE
K epsilon mods

### LINKED ISSUE #27800: Error in the FindYPlus routine
### Bug Description

The findYPlus routine in Navier Stokes Methods computes the yplus iteratively.
However, the error of the current guess with respect to the old guess in the previous iteration is missing the absolute value, incurring in errors in the computation of the yplus.

### Steps to Reproduce

Currently, running the routine yields an error in the yplus value calculation.

### Impact

The impact is the miscalculation of the dimensionless wall distance, leading to a miscaracterization of the turbulence field. Impacts turbulence production kernels, turbulent viscosity wall functions and first cell wall distance determination in the meshing process.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by freiler**
Closes #27800 #27887 #27888

### CODE REVIEW

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+#include "NavierStokesMethods.h"
+#include "libmesh/nonlinear_solver.h"
+
+registerMooseObject("NavierStokesApp", RANSYPlusAux);
+
+InputParameters
+RANSYPlusAux::validParams()
+{
+  InputParameters params = AuxKernel::validParams();
+  params.addClassDescription("Calculates y+ value");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:22]:
```suggestion
  params.addClassDescription("Calculates non-dimensional wall distance (y+) value.");
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+  params.addRequiredCoupledVar("u", "The velocity in the x direction.");
+  params.addCoupledVar("v", "The velocity in the y direction.");
+  params.addCoupledVar("w", "The velocity in the z direction.");
+  params.addRequiredParam<MooseFunctorName>(NS::TKE, "Coupled turbulent kinetic energy.");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:26]:
```suggestion
  params.addRequiredParam<MooseFunctorName>(NS::TKE, "Turbulent kinetic energy functor.");
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+  params.addRequiredParam<MooseFunctorName>(NS::density, "fluid density");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:27]:
```suggestion
  params.addRequiredParam<MooseFunctorName>(NS::density, "Fluid density.");
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+  params.addRequiredParam<MooseFunctorName>(NS::mu, "Dynamic viscosity.");
+  params.addParam<std::vector<BoundaryName>>(
+      "walls", {}, "Boundaries that correspond to solid walls.");
+  MooseEnum wall_treatment("eq_newton eq_incremental eq_linearized neq", "eq_newton");
+  params.addParam<MooseEnum>("wall_treatment",
+                             wall_treatment,
+                             "The method used for computing the wall functions "
+                             "'eq_newton', 'eq_incremental', 'eq_linearized', 'neq'");
+  params.addParam<Real>("C_mu", 0.09, "Coupled turbulent kinetic energy closure.");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:36]:
```suggestion
  params.addParam<Real>("C_mu", 0.09, "Coupled turbulent kinetic energy closure coefficient.");
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+}
+
+Real
+RANSYPlusAux::computeValue()
+{
+  const auto state = determineState();
+  const auto elem_arg = makeElemArg(_current_elem);
+  const auto rho = _rho(elem_arg, state);
+  const auto mu = _mu(elem_arg, state);
+  const auto TKE = _k(elem_arg, state);
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:77]:
```suggestion
```

Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:77]: No need to define this parameter as it is used only one for the neq treatment

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+    for (unsigned int i = 0; i < distance_vec.size(); i++)
+    {
+      const auto parallel_speed = NS::computeSpeed(
+          velocity - velocity * face_info_vec[i]->normal() * face_info_vec[i]->normal());
+      const auto distance = distance_vec[i];
+
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(TKE) * rho / mu;
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:102]:
```suggestion
        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(_k(elem_arg, state)) * rho / mu;
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 7]
```diff
@@ -0,0 +1,117 @@
...
+        y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), distance);
+      }
+    }
+    // return *std::max_element(y_plus_vec.begin(), y_plus_vec.end());
+    return raw_value(y_plus);
+  }
+  else
+  {
+    return 0.;
+  }
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:116]:
```suggestion
     return 0.;
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 8]
```diff
@@ -32,15 +32,17 @@ kEpsilonViscosityAux::validParams()
...
-      "Boolean to indicate if yplus must be estimate locally for the blending functions.");
   params.addParam<bool>("bulk_wall_treatment", false, "Activate bulk wall treatment.");
-  params.addParam<bool>(
-      "non_equilibrium_treatment",
-      false,
-      "Use non-equilibrium wall treatement (faster than standard wall treatement)");
+  MooseEnum wall_treatment("eq_newton eq_incremental eq_linearized neq", "eq_newton");
+  params.addParam<MooseEnum>("wall_treatment",
+                             wall_treatment,
+                             "The method used for computing the wall functions "
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:39]:
```suggestion
                             "The method used for computing the wall functions."
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 9]
```diff
@@ -166,56 +124,83 @@ kEpsilonViscosityAux::computeValue()
     // Compute the velocity and direction of the velocity component that is parallel to the wall
     const ADReal parallel_speed = (velocity - velocity * loc_normal * loc_normal).norm();
 
-    ADReal y_plus, u_tau;
-    if (_non_equilibrium_treatment)
+    // Switch for determining the near wall quantities
+    // wall_treatment can be: "eq_newton eq_incremental eq_linearized neq"
+    ADReal u_tau;
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:129]:
```suggestion
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 10]
```diff
@@ -166,56 +124,83 @@ kEpsilonViscosityAux::computeValue()
...
-      // Computing non-equilibrium nondimensional wall distance and friction velocity
-      y_plus = _rho(current_argument, state) * std::pow(_C_mu, 0.25) *
-               std::pow(_k(current_argument, state), 0.5) * min_wall_dist /
-               _mu(current_argument, state);
-      const auto von_karman_value =
-          (1 / NS::von_karman_constant * std::log(NS::E_turb_constant * y_plus));
-      u_tau = std::sqrt(std::pow(_C_mu, 0.25) * std::pow(_k(current_argument, state), 0.5) *
-                        parallel_speed / von_karman_value);
+      // Full Newton-Raphson solve to find the wall quantities from the law of the wall
+      u_tau = NS::findUStar(mu, rho, parallel_speed, min_wall_dist);
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:137]:
```suggestion
      const ADReal u_tau = NS::findUStar(mu, rho, parallel_speed, min_wall_dist);
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 11]
```diff
@@ -166,56 +124,83 @@ kEpsilonViscosityAux::computeValue()
...
-    else if (y_plus >= 30.0) // log-layer
+    else if (_wall_treatment == "eq_linearized")
+    {
+      // Linearized approximation to the wall function to find the near-wall quantities faster
+      const ADReal a_c = 1 / NS::von_karman_constant;
+      const ADReal b_c = 1 / NS::von_karman_constant *
+                         (std::log(NS::E_turb_constant * std::max(min_wall_dist, 1.0) / mu) + 1.0);
+      const ADReal c_c = parallel_speed;
+
+      u_tau = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:158]:
```suggestion
      const ADReal u_tau = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 12]
```diff
@@ -166,56 +124,83 @@ kEpsilonViscosityAux::computeValue()
...
 
-    ADReal y_plus, u_tau;
-    if (_non_equilibrium_treatment)
+    // Switch for determining the near wall quantities
+    // wall_treatment can be: "eq_newton eq_incremental eq_linearized neq"
+    ADReal u_tau;
+    ADReal y_plus;
+    ADReal mut_log; // turbulent log-layer viscosity
+    ADReal mu_wall; // total wall viscosity to obtain the shear stress at the wall
+
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:133]: The whole method blow needs to be revised to optimize memory usage and efficiency. It should read as follows:

compute y_plus regarding the wall treatment method used;
if (y_plus <= 5.0)
  return 0.0
else if (y_plus >= 30.0)
  // do all the things that you are doing for the log-layer treatment
else
 // do the methd for the buffer layer

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 13]
```diff
@@ -69,13 +69,22 @@ findUStar(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
 
-  ADReal u_star = std::sqrt(nu * u / dist);
+  // Wall-function linearized guess
+  const Real a_c = 1 / NS::von_karman_constant;
+  const ADReal b_c =
+      1 / NS::von_karman_constant * (std::log(NS::E_turb_constant * dist / mu) + 1.0);
+  const ADReal c_c = u;
+
+  /// This is important to reduce the number of nonlinear iterations
+  ADReal u_star = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
```
Comment (tanoret) [inline modules/navier_stokes/src/base/NavierStokesMethods.C:79]: Nice initial guess!

File: modules/navier_stokes/src/executioners/SIMPLENonlinearAssembly.C [hunk 14]
```diff
@@ -478,6 +478,9 @@ SIMPLENonlinearAssembly::execute()
       // Resdiual index
       size_t residual_index = 0;
 
+      // Execute all objects tagged as nonlinear
+      _problem.execute(EXEC_NONLINEAR);
```
Comment (tanoret) [inline modules/navier_stokes/src/executioners/SIMPLENonlinearAssembly.C:482]: Please add a few comments for this. It is rather unconventional, but important for things to work!

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 15]
```diff
@@ -78,21 +79,23 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
   ADReal y_plus;
   const ADReal mut_visc = mu; // laminar sublayer viscosity
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:80]:
```suggestion
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 16]
```diff
@@ -101,29 +104,35 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
   }
-
   if (y_plus <= 5.0)
     // sub-laminar layer
-    return mut_visc;
+    return 0.0;
   else if (y_plus >= 30.0)
     // log-layer
-    return mut_log + mut_visc;
+    return std::max(mut_log, 1e-12);
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:127]: The 1e-12 appears often as a limiter. Considering making a coded parameter in NS Namespace

File: modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C [hunk 17]
```diff
@@ -117,11 +115,14 @@ INSFVTKEDSourceSink::computeQpResidual()
     {
       const auto distance = distance_vec[i];
 
-      ADReal y_plus;
-      if (_non_equilibrium_treatment)
-        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(TKE) / mu;
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(TKE) * rho / mu;
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C:121]:
```suggestion
        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * TKE) * rho / mu;
```

File: modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C [hunk 18]
```diff
@@ -144,12 +145,14 @@ INSFVTKEDSourceSink::computeQpResidual()
         const Elem * const loc_elem = defined_on_elem_side ? &fi->elem() : fi->neighborPtr();
         const Moose::FaceArg facearg = {
             fi, Moose::FV::LimiterType::CentralDifference, false, false, loc_elem};
-        const ADReal wall_mut = _mu_t(facearg, state);
-        destruction += 2.0 * TKE * wall_mut / Utility::pow<2>(distance_vec[i]) / tot_weight;
+        const ADReal wall_mu = _mu(facearg, state);
+        destruction += 2.0 * TKE * wall_mu / rho / Utility::pow<2>(distance_vec[i]) / tot_weight;
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C:149]:
```suggestion
        destruction += 2.0 * TKE * _mu(facearg, state) / rho / Utility::pow<2>(distance_vec[i]) / tot_weight;
```

File: modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C [hunk 19]
```diff
@@ -144,12 +145,14 @@ INSFVTKEDSourceSink::computeQpResidual()
...
       }
       else
+      {
         destruction += std::pow(_C_mu, 0.75) * rho * std::pow(TKE, 1.5) /
                        (NS::von_karman_constant * distance_vec[i]) / tot_weight;
+      }
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C:155]:
```suggestion
        destruction += std::pow(_C_mu, 0.75) * rho * std::pow(TKE, 1.5) /
                       (NS::von_karman_constant * distance_vec[i]) / tot_weight;
```

File: modules/navier_stokes/src/fvkernels/INSFVTKESourceSink.C [hunk 20]
```diff
@@ -116,8 +114,17 @@ INSFVTKESourceSink::computeQpResidual()
           velocity - velocity * face_info_vec[i]->normal() * face_info_vec[i]->normal());
       const auto distance = distance_vec[i];
 
-      const auto y_plus =
-          NS::findyPlus(_mu(elem_arg, state), rho, std::max(parallel_speed, 1e-10), distance);
+      ADReal y_plus;
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(_var(elem_arg, old_state)) * rho / mu;
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKESourceSink.C:121]:
```suggestion
        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * _var(elem_arg, old_state)) * rho / mu;
```

**Review by tanoret — CHANGES_REQUESTED** [review]
Initial round of reviews. Will add a few more comments in the second round, but there should be less. Nice work!

File: modules/navier_stokes/doc/content/source/auxkernels/RANSYPlusAux.md [hunk 21]
```diff
@@ -0,0 +1,13 @@
+# RANSYplusAux
+
+Computes the dimensionless wall distance $y^+$ for RANS models.
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/doc/content/source/auxkernels/RANSYPlusAux.md:3]: Seems like we will want to rename WallFunctionYPlusAux then

[the remark this answers is not in the document]
Comment (freiler) [reply modules/navier_stokes/doc/content/source/auxkernels/RANSYPlusAux.md:3]: Or maybe have a general YPlus kernel that checks if TKE is passed as a parameter. If it is not passed and the wall treatment is non-equilibrium. then throw an error. Or a warning and an automatic change to an equilibrium treatment.

File: modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h [hunk 22]
```diff
@@ -53,3 +51,57 @@ class INSFVTurbulentViscosityWallFunction : public FVDirichletBCBase
   /// Method used for wall treatment
   const MooseEnum _wall_treatment;
 };
+
+// //* This file is part of the MOOSE framework
```
[the remark this answers is not in the document]
Comment (freiler) [reply modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h:55]: Thank you!

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C
Comment (freiler) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:1]: Ideally, the y+ values should live at faces not cell centroids. For now we will return an average of y+ when the cells have multiple faces. In BC kernels for Turbulent viscosity this is not a problem, as mu_t is computed at each face, with its corresponding y+ value. Also in TKE and TKED source-sink kernels.

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C (hunk 12 above)
Comment (freiler) [reply modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:133]: The way I see this implemented is as follows:

if (wall_treatment = 'neq, eq_new, eq_incr, eq_lin')
     compute yplus 
     compute u_tau

if (yplus<5)
     0
else if (yplus>30)
     if (neq or eq_lin)
          mu_w = mu.(y+ kappa/log... - 1)
          mut_log=muw-mu
     else
          mu_w = utau^2 rho ....
          mut_log=muw-mu
else 

you save operations for the laminar case, but introduces a new if statement for the log layer cases that might make it more complicated to read. What do you think?

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C (hunk 10 above)
Comment (freiler) [reply modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:137]: u_tau is declared above the if statements as ADReal, and then computed, so I can't declare it as const

**Comment by GiudGiud** [comment]
what is the status of this? I am waiting for this to be merged before the Turbulence physics can be updated with K-Epsilon

**Comment by grmnptr** [comment]
As far as I remember @tanoret will take a look at this and if he approves I'll give it a quick look and approve.

**Comment by tanoret** [comment]
Yes, on it now

**Comment by tanoret** [comment]
Also, @GiudGiud the syntax of the TKE input will likely change when we merge kOmegaSST, which is currently ready (we are doing the flow test bed testing before merge). Do you maybe want to hold a little bit the merge to do it only once? Otherwise, I can always modify the physics

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped.i [hunk 23]
```diff
@@ -28,13 +28,11 @@ sigma_eps = 1.3
 C1_eps = 1.44
 C2_eps = 1.92
 C_mu = 0.09
+C_pl = 0.1
```
Comment (tanoret) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped.i:31]: Why 0.1 and not 10.0?

Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped.i:31]: If this is just a test to significantly cap the production, please disregard this comment

**Review by tanoret — CHANGES_REQUESTED** [review]
Nice work. I am good to merge after a few minor comments are addressed

**Comment by GiudGiud** [comment]
> Also, @GiudGiud the syntax of the TKE input will likely change when we merge kOmegaSST, which is currently ready (we are doing the flow test bed testing before merge). Do you maybe want to hold a little bit the merge to do it only once? Otherwise, I can always modify the physics

The k-epsilon Physics is ready but we can stagger the PRs either way.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped.i (hunk 23 above)
Comment (freiler) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped.i:31]: this is a test to cap the production

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 24]
```diff
@@ -101,29 +102,38 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
-                        std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)) -
-                    1.0);
+    y_plus =
+        std::pow(_C_mu, 0.25) * wall_dist * std::sqrt(_k(current_argument, old_state)) * rho / mu;
+    mu_wall = mu * (NS::von_karman_constant * y_plus /
+                    std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)));
+    mut_log = mu_wall - mu;
   }
+  else
+    mooseAssert(false, "Should not reach here");
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:121]: this is fine. the idea is that we currently cannot reach it, but if we add an option, this error will get triggered

it s the right thing to do to litter the code with asserts that prevent future mistakes (or current ones sometimes)

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 25]
```diff
@@ -101,29 +102,38 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
     const ADReal c_c = parallel_speed;
-    u_tau = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
+
+    const auto u_tau = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
     y_plus = wall_dist * u_tau * rho / mu;
-    mut_log = rho * Utility::pow<2>(u_tau) * wall_dist / parallel_speed;
+    mu_wall = rho * Utility::pow<2>(u_tau) * wall_dist / parallel_speed;
+    mut_log = mu_wall - mu;
   }
   else if (_wall_treatment == "neq")
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:111]: should use an enum instead of comparing strings

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 26]
```diff
@@ -101,29 +102,38 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
     // log-layer
-    return mut_log + mut_visc;
+    return std::max(mut_log, NS::mu_t_low_limit);
   else
   {
     // buffer layer
     const auto blending_function = (y_plus - 5.0) / 25.0;
-    return blending_function * mut_log + mut_visc;
+    // the blending depends on the mut_log at y+=30
+    const auto mut_log = mu * (NS::von_karman_constant * 30.0 /
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:134]: use static constexpr except for mu

Comment (GiudGiud) [reply modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:134]: static constexpr _mut_term = (NS::von_karman_constant * 30.0 / ...);

File: modules/navier_stokes/include/auxkernels/RANSYPlusAux.h [hunk 27]
```diff
@@ -0,0 +1,63 @@
...
+
+  /// x-velocity
+  const Moose::Functor<ADReal> & _u_var;
+  /// y-velocity
+  const Moose::Functor<ADReal> * _v_var;
+  /// z-velocity
+  const Moose::Functor<ADReal> * _w_var;
+
+  /// Turbulent kinetic energy
+  const Moose::Functor<ADReal> & _k;
```
Comment (tanoret) [inline modules/navier_stokes/include/auxkernels/RANSYPlusAux.h:40]: Technically `k` is only needed when `_wall_treatment == "neq"`. You could consider making this a pointer and then reading this parameter only when `neq` is selected for the wall treatment

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 28]
```diff
@@ -32,15 +32,17 @@ kEpsilonViscosityAux::validParams()
...
+  MooseEnum wall_treatment("eq_newton eq_incremental eq_linearized neq", "eq_newton");
+  params.addParam<MooseEnum>("wall_treatment",
+                             wall_treatment,
+                             "The method used for computing the wall functions."
+                             "'eq_newton', 'eq_incremental', 'eq_linearized', 'neq'");
+  MooseEnum scale_limiter("none standard", "standard");
+  params.addParam<MooseEnum>("scale_limiter",
+                             scale_limiter,
+                             "The method used to limit the k-epsilon time scale."
+                             "'none', 'standard'");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:45]: I thikn the `standard` limiting is not in the documentation. Please consider adding a more complete description here.

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 29]
```diff
@@ -166,60 +115,87 @@ kEpsilonViscosityAux::computeValue()
...
-      mu_t_wall = wall_val.value();
+      // Assign non-equilibrium wall function value
+      y_plus = min_wall_dist * std::sqrt(std::sqrt(_C_mu) * _k(current_argument, state)) * rho / mu;
+      mu_wall = mu * (NS::von_karman_constant * y_plus /
+                      std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)));
+      mut_log = mu_wall - mu;
     }
-    else // buffer layer
+    else
+      mooseAssert(false, "Should not reach here");
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:162]:
```suggestion
    else
      mooseAssert(false, "For `kEpsilonViscosityAux` , wall treatment should not reach here");
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 30]
```diff
@@ -166,60 +115,87 @@ kEpsilonViscosityAux::computeValue()
...
+    }
+
     const ADReal mu_t_nl =
         _rho(current_argument, state) * _C_mu * _k(current_argument, state) * time_scale;
     mu_t = mu_t_nl.value();
   }
-
-  return mu_t;
+  // Turbulent viscosity limiter
+  return std::min(mu_t, 1e5 * raw_value(mu));
```
Comment (tanoret) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:200]: Can we make the 1e5 limit a parameter that the user can change? I am good for defaulting this parameter to 1e5

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 31]
```diff
@@ -69,13 +69,22 @@ findUStar(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
 
   const ADReal nu = mu / rho;
 
-  ADReal u_star = std::sqrt(nu * u / dist);
+  // Wall-function linearized guess
+  const Real a_c = 1 / NS::von_karman_constant;
+  const ADReal b_c =
+      1 / NS::von_karman_constant * (std::log(NS::E_turb_constant * dist / mu) + 1.0);
```
Comment (tanoret) [inline modules/navier_stokes/src/base/NavierStokesMethods.C:75]:
```suggestion
      1.0 / NS::von_karman_constant * (std::log(NS::E_turb_constant * dist / mu) + 1.0);
```

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 32]
```diff
@@ -69,13 +69,22 @@ findUStar(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
 
   // Newton-Raphson method to solve for u_star (friction velocity).
   for (int i = 0; i < MAX_ITERS; ++i)
   {
-    ADReal residual = u_star / NS::von_karman_constant * std::log(u_star * dist / (0.111 * nu)) - u;
-    ADReal deriv = (1 + std::log(u_star * dist / (0.111 * nu))) / NS::von_karman_constant;
+    ADReal residual =
+        u_star / NS::von_karman_constant * std::log(NS::E_turb_constant * u_star * dist / nu) - u;
+    ADReal deriv =
+        (1 + std::log(NS::E_turb_constant * u_star * dist / nu)) / NS::von_karman_constant;
```
Comment (tanoret) [inline modules/navier_stokes/src/base/NavierStokesMethods.C:87]:
```suggestion
        (1.0 + std::log(NS::E_turb_constant * u_star * dist / nu)) / NS::von_karman_constant;
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C [hunk 33]
```diff
@@ -76,21 +82,40 @@ INSFVTurbulentTemperatureWallFunction::computeQpResidual()
...
+    // Full Newton-Raphson solve to find the wall quantities from the law of the wall
+    u_tau = NS::findUStar(mu, rho, parallel_speed, wall_dist);
+    y_plus = wall_dist * u_tau * rho / mu;
+  }
+  else if (_wall_treatment == "eq_incremental")
+  {
+    // Incremental solve on y_plus to get the near-wall quantities
+    y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), wall_dist);
+    u_tau = parallel_speed /
+            (std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)) / NS::von_karman_constant);
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C:99]:
```suggestion
            (std::log(std::max(NS::E_turb_constant * y_plus, 1.0 + 1e-4)) / NS::von_karman_constant);
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C [hunk 34]
```diff
@@ -76,21 +82,40 @@ INSFVTurbulentTemperatureWallFunction::computeQpResidual()
...
+  }
+  else if (_wall_treatment == "eq_linearized")
   {
+    // Linearized approximation to the wall function to find the near-wall quantities faster
     const ADReal a_c = 1 / NS::von_karman_constant;
-    const ADReal b_c =
-        1 / NS::von_karman_constant * (std::log(NS::E_turb_constant * wall_dist / mu) + 1.0);
+    const ADReal b_c = 1 / NS::von_karman_constant *
+                       (std::log(NS::E_turb_constant * std::max(wall_dist, 1.0) / mu) + 1.0);
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C:106]:
```suggestion
    const ADReal b_c = 1.0 / NS::von_karman_constant *
                       (std::log(NS::E_turb_constant * std::max(wall_dist, 1.0) / mu) + 1.0);
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C [hunk 35]
```diff
@@ -76,21 +82,40 @@ INSFVTurbulentTemperatureWallFunction::computeQpResidual()
...
+
     u_tau = (-b_c + std::sqrt(std::pow(b_c, 2) + 4.0 * a_c * c_c)) / (2.0 * a_c);
+    y_plus = wall_dist * u_tau * rho / mu;
+  }
+  else if (_wall_treatment == "neq")
+  {
+    // Assign non-equilibrium wall function value
+    y_plus = wall_dist * std::sqrt(std::sqrt(_C_mu) * _k(current_argument, old_state)) * rho / mu;
+    u_tau = parallel_speed /
+            (std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)) / NS::von_karman_constant);
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentTemperatureWallFunction.C:117]:
```suggestion
    u_tau = parallel_speed /
            (std::log(std::max(NS::E_turb_constant * y_plus, 1.0 + 1e-4)) / NS::von_karman_constant);
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 36]
```diff
@@ -58,72 +58,80 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
-  else if (_wall_treatment == "eq_incremental")
+  else if (_wall_treatment == INCREMENTAL)
   {
     // Incremental solve on y_plus to get the near-wall quantities
     y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), wall_dist);
-    mut_log = mu * (NS::von_karman_constant * y_plus /
-                        std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)) -
-                    1.0);
+    mu_wall = mu * (NS::von_karman_constant * y_plus /
+                    std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)));
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:95]:
```suggestion
    mu_wall = mu * (NS::von_karman_constant * y_plus /
                    std::log(std::max(NS::E_turb_constant * y_plus, 1.0 + 1e-4)));
```

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 37]
```diff
@@ -58,72 +58,80 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi) const
...
   {
     // Assign non-equilibrium wall function value
-    y_plus = std::pow(_C_mu, 0.25) * wall_dist * std::sqrt(_k(current_argument, state)) * rho / mu;
-    mut_log = mu * (NS::von_karman_constant * wall_dist /
-                        std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)) -
-                    1.0);
+    y_plus =
+        std::pow(_C_mu, 0.25) * wall_dist * std::sqrt(_k(current_argument, old_state)) * rho / mu;
+    mu_wall = mu * (NS::von_karman_constant * y_plus /
+                    std::log(std::max(NS::E_turb_constant * y_plus, 1 + 1e-4)));
```
Comment (tanoret) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C:117]:
```suggestion
    mu_wall = mu * (NS::von_karman_constant * y_plus /
                    std::log(std::max(NS::E_turb_constant * y_plus, 1 .0 + 1e-4)));
```

File: modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C [hunk 38]
```diff
@@ -117,11 +115,14 @@ INSFVTKEDSourceSink::computeQpResidual()
...
       const auto distance = distance_vec[i];
 
-      ADReal y_plus;
-      if (_non_equilibrium_treatment)
-        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(TKE) / mu;
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * TKE) * rho / mu;
+      }
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKEDSourceSink.C:122]:
```suggestion
      if (_wall_treatment == "neq") // Non-equilibrium / Non-iterative
        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * TKE) * rho / mu;
```

File: modules/navier_stokes/src/fvkernels/INSFVTKESourceSink.C [hunk 39]
```diff
@@ -116,8 +114,17 @@ INSFVTKESourceSink::computeQpResidual()
...
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * _var(elem_arg, old_state)) * rho / mu;
+      }
+      else
+      {
+        // Equilibrium / Iterative
+        y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), distance);
+      }
```
Comment (tanoret) [inline modules/navier_stokes/src/fvkernels/INSFVTKESourceSink.C:127]:
```suggestion
      if (_wall_treatment == "neq") // Non-equilibrium / Non-iterative
        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * _var(elem_arg, old_state)) * rho / mu;
      else // Equilibrium / Iterative
        y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), distance);
```

**Review by tanoret — APPROVED** [review]
Only minor changes. Good to go for me

**Review by GiudGiud — COMMENTED** [review]
dont tag Mauricio in commit messages he will get a slew of emails from that every time someone rebases

commit messages could be improved. "addressed reviews" does not tell me if there is something important in there or just typos / format

**Comment by grmnptr** [comment]
To save some git-related storage (MOOSE is growing a little too fast), could you please regold once and remove every additional regold in the git history? I can show you how to do it.

File: modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md [hunk 40]
```diff
@@ -12,8 +12,30 @@ boundary layer are identified as follows:
...
+
+\begin{equation}
+    \tau_w = \frac{ \mu_w u_p}{y_p} \,,
+\end{equation}
+
+where:
+
+- $\mu_w = \mu + \mu_t$  is the total viscosity evaluated at the wall face
+- $\mu_t$ is the turbulent viscosity, evaluated at the wall for the purpose of this boundary condition
+- $\mu$ is the kinematic viscosity, evaluated at the wall for the purpose of this boundary condition
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md:27]:
```suggestion
- $\mu$ is the dynamic viscosity, evaluated at the wall for the purpose of this boundary condition
```

File: modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md [hunk 41]
```diff
@@ -12,8 +12,30 @@ boundary layer are identified as follows:
...
+- $\tau_w$ is the wall-shear stress
+- $u_p$ is the wall-parallel velocity at the centroid
+- $y_p$ is the wall normal distance to the centroid
+
+To impose a correct boundary condition for $\mu_t$, as seen in the Equation above, we need to compute $\tau_w$ using analytical
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md:32]:
```suggestion
To impose a correct boundary condition for $\mu_t$, as seen in the equation above, we need to compute $\tau_w$ using analytical 
```

File: modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md [hunk 42]
```diff
@@ -12,8 +12,30 @@ boundary layer are identified as follows:
...
+- $\tau_w$ is the wall-shear stress
+- $u_p$ is the wall-parallel velocity at the centroid
+- $y_p$ is the wall normal distance to the centroid
+
+To impose a correct boundary condition for $\mu_t$, as seen in the Equation above, we need to compute $\tau_w$ using analytical 
+relationships between the wall shear stress and the dimensionless wall distance $y^+$. For this purpose, four different
+formulations are supported as defined by the [!param](/FVBCs/INSFVTurbulentViscosityWallFunction/wall_treatment) parameter.
+
+To set the grid spacing for the first cell near the wall in your mesh, we recommend using the Auxiliary Kernel
+[RANSYPlusAux.md]
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md:37]:
```suggestion
To set the grid spacing for the first cell near the wall in your mesh, we recommend using the [RANSYPlusAux.md] auxiliary kernel. 
```

File: modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md [hunk 43]
```diff
@@ -12,8 +12,30 @@ boundary layer are identified as follows:
 - Buffer region: $y^+ \in (5, 30)$
 - Logarithmic region: $y^+ \ge 30$
 
-Four different formulations are supported
-as defined by the [!param](/FVBCs/INSFVTurbulentViscosityWallFunction/wall_treatment) parameter.
+The wall function goal is to set the total viscosity at the wall $\mu_w$, decomposed as
+$\mu_w = \mu + \mu_t $ , such that the wall shear stress $\tau_w$ is accurately captured
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md:16]:
```suggestion
$\mu_w = \mu + \mu_t$, such that the wall shear stress $\tau_w$ is accurately captured 
```

Comment (grmnptr) [reply modules/navier_stokes/doc/content/source/fvbcs/INSFVTurbulentViscosityWallFunction.md:16]: This rendered weird on the website, maybe the white space is the culprit.

File: modules/navier_stokes/doc/content/source/fvkernels/INSFVTKEDSourceSink.md [hunk 44]
```diff
@@ -41,12 +39,12 @@ treatment in which the equilibrium value for the $\epsilon = \epsilon_{eq}$ is s
...
 is performed via the non-dimensional wall distance $y^+$.
-The non-dimensional wall distance can be as defined differently according to the
-[!param](/FVKernels/INSFVTKEDSourceSink/non_equilibrium_treatment) parameter.
+The non-dimensional wall distance can be defined differently according to the
+[!param](/FVKernels/INSFVTKEDSourceSink/wall_treatment) parameter. 
 
-If [!param](/FVKernels/INSFVTKEDSourceSink/non_equilibrium_treatment) is `false`, the
-standard wall function formulations is used in
-which $y^+$ is found by an incremental fixed point algorithm as follows:
+The four formulations are described in more detail in [INSFVTurbulentViscosityWallFunction](source/fvbcs/INSFVTurbulentViscosityWallFunction.md).
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvkernels/INSFVTKEDSourceSink.md:45]:
```suggestion
The four formulations are described in more detail in [INSFVTurbulentViscosityWallFunction.md]. 
```

File: modules/navier_stokes/doc/content/source/fvkernels/INSFVTKESourceSink.md [hunk 45]
```diff
@@ -24,6 +24,16 @@ transport equation for $\epsilon$.
 However, for canonical or measured cases, e.g., isotropic decaying turbulence,
 the user can utilize predefined fields through functors in MOOSE.
 
+To avoid the overproduction of turbulent kinetic energy in stagnation zones \cite{durbin1996k}, a production limiter is imposed in relation to the dissipation using the formulation in \cite{menter1994two}:
```
Comment (grmnptr) [inline modules/navier_stokes/doc/content/source/fvkernels/INSFVTKESourceSink.md:27]: Beautiful!

File: modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h [hunk 46]
```diff
@@ -52,4 +50,17 @@ class INSFVTurbulentViscosityWallFunction : public FVDirichletBCBase
...
   const MooseEnum _wall_treatment;
+
+  // Declare enum structure for wall treatment
+  enum wall_treatment_options
+  {
+    NEWTON,
+    INCREMENTAL,
+    LINEARIZED,
+    NEQ
+  };
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h:61]: Great idea!

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 47]
```diff
@@ -0,0 +1,116 @@
...
+      if (_wall_treatment == "neq")
+      {
+        // Non-equilibrium / Non-iterative
+        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(_k(elem_arg, state)) * rho / mu;
+      }
+      else
+      {
+        // Equilibrium / Iterative
+        y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), distance);
+      }
```
Comment (grmnptr) [inline modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:108]:
```suggestion
      if (_wall_treatment == "neq")
        // Non-equilibrium / Non-iterative
        y_plus = std::pow(_C_mu, 0.25) * distance * std::sqrt(_k(elem_arg, state)) * rho / mu;
      else
        // Equilibrium / Iterative
        y_plus = NS::findyPlus(mu, rho, std::max(parallel_speed, 1e-10), distance);
```

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C [hunk 48]
```diff
@@ -166,60 +115,87 @@ kEpsilonViscosityAux::computeValue()
...
+    if (_scale_limiter == "standard")
+    {
+      time_scale =
+          std::max(_k(current_argument, state) / (_epsilon(current_argument, state) + 1e-15),
+                   std::sqrt(nu / (_epsilon(current_argument, state) + 1e-15)));
+    }
+    else
+    {
+      time_scale = _k(current_argument, state) / (_epsilon(current_argument, state) + 1e-15);
+    }
```
Comment (grmnptr) [inline modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:193]:
```suggestion
    if (_scale_limiter == "standard")
      time_scale =
          std::max(_k(current_argument, state) / (_epsilon(current_argument, state) + 1e-15),
                   std::sqrt(nu / (_epsilon(current_argument, state) + 1e-15)));
    else
      time_scale = _k(current_argument, state) / (_epsilon(current_argument, state) + 1e-15);
```

File: modules/navier_stokes/src/executioners/SegregatedSolverBase.C [hunk 49]
```diff
@@ -412,6 +419,15 @@ SegregatedSolverBase::SegregatedSolverBase(const InputParameters & parameters)
       paramError("turbulence_absolute_tolerance",
                  "The number of absolute tolerances does not match the number of "
                  "turbulence equations!");
+    if (_turbulence_field_min_limit.empty())
+    {
+      // If no minimum bounds are given, initialize to default value 1e-8
+      _turbulence_field_min_limit.resize(_turbulence_system_names.size(), 1e-8);
+    }
```
Comment (grmnptr) [inline modules/navier_stokes/src/executioners/SegregatedSolverBase.C:426]:
```suggestion
    if (_turbulence_field_min_limit.empty())
      // If no minimum bounds are given, initialize to default value 1e-8
      _turbulence_field_min_limit.resize(_turbulence_system_names.size(), 1e-8);
```

**Review by grmnptr — CHANGES_REQUESTED** [review]
Very nice job! Just a few minor comments from my side as well.

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C (hunk 28 above)
Comment (freiler) [reply modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C:45]: Added to the documentation

File: modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h (hunk 46 above)
[the remark this answers is not in the document]
Comment (freiler) [reply modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h:61]: Not doing Enums for now

[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h:61]: what do you mean?

[the remark this answers is not in the document]
Comment (freiler) [reply modules/navier_stokes/include/fvbcs/INSFVTurbulentViscosityWallFunction.h]: Enums have been added to the NS namespace

File: modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C (hunk 30 above)
Comment (freiler) [reply modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C]: Added it

File: modules/navier_stokes/include/auxkernels/RANSYPlusAux.h (hunk 27 above)
Comment (freiler) [reply modules/navier_stokes/include/auxkernels/RANSYPlusAux.h:40]: Capability added.

File: modules/navier_stokes/doc/content/source/fvkernels/INSFVTKESourceSink.md (hunk 45 above)
Comment (freiler) [reply modules/navier_stokes/doc/content/source/fvkernels/INSFVTKESourceSink.md:27]: thank you

**Review by grmnptr — APPROVED** [review]
Great contribution!
