### PR TITLE
Fix Linear FV RZ, add coordinate transform factor to RC body force correction. 

### LINKED ISSUE #31862: Natural convection in linear FV missing coordinate transfer multiplier.
### Bug Description

The volume info here needs a coordinate transform factor multiplier.

```
force_kernel->setCurrentElemInfo(&elem_info);
              face_hbya(dim_i) -= force_kernel->computeRightHandSideContribution() *
                                  ainv_reader[dim_i](elem_dof) / elem_info.volume(); // zero-term expansion
```

### Steps to Reproduce

Run any r-z case with natural convection.

### Impact

Makes result unphysicial, showes numerical artifacts.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #31862 
Refs #31934

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Review by lindsayad — APPROVED** [review]
Would be good to test to make sure we don't regress

**Comment by grmnptr** [comment]
I'll add a test in a bit!

**Comment by grmnptr** [comment]
Oh wait, we will need this first for a test first:
https://github.com/idaholab/moose/pull/27757

**Comment by lindsayad** [comment]
That PR is in now (as you know 😄 )

**Comment by grmnptr** [comment]
Yeah I am working on an MMS case for this.

**Comment by grmnptr** [comment]
I will do the nonlinear FV tomorrow in a different PR.

File: modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+      const_cast<MooseLinearVariableFVReal *>(_velocity_vars[dir])->computeCellGradients();
+  }
+}
+
+Real
+LinearFVRZViscousSource::computeMatrixContribution()
+{
+  if (_coord_type != Moose::CoordinateSystemType::COORD_RZ)
+    return 0.0;
+
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C]:
```suggestion
```
theres an error in the constructor

File: modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+  const auto state = determineState();
+
+  const Real mu = _mu(elem_arg, state);
+  return mu * _stress_multiplier * _current_elem_volume / (r * r);
+}
+
+Real
+LinearFVRZViscousSource::computeRightHandSideContribution()
+{
+  if (_coord_type != Moose::CoordinateSystemType::COORD_RZ || !_use_deviatoric_terms)
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C]:
```suggestion
  if (!_use_deviatoric_terms)
```

File: modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+      paramError(param_name, "The supplied variable must be a MooseLinearVariableFVReal.");
+    return ptr;
+  };
+
+  if (isParamValid("u"))
+    _velocity_vars[0] = get_velocity_var("u");
+  if (isParamValid("v"))
+    _velocity_vars[1] = get_velocity_var("v");
+  if (isParamValid("w"))
+    _velocity_vars[2] = get_velocity_var("w");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C]:
```suggestion
```
there s no 3rd coordinate in RZ

File: modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVRZViscousSource.md [hunk 4]
```diff
@@ -0,0 +1,29 @@
+# LinearFVRZViscousSource
+
+!syntax description /LinearFVKernels/LinearFVRZViscousSource
+
+This kernel supplies the axisymmetric viscous source term $\mu u_r / r^2$ that appears in
+the cylindrical vector Laplacian.
```
Comment (GiudGiud) [inline modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVRZViscousSource.md:6]: did you check the entire laplacian?
there are also 2 cross terms in z we would have missed

**Comment by grmnptr** [comment]
Thanks for the quick review!
I'll double check, but I am fairly confident we have the stress tensor right here.

File: modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVRZViscousSource.md (hunk 4 above)
Comment (grmnptr) [reply modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVRZViscousSource.md:6]: Okay, I think we have all the terms.

**Comment by grmnptr** [comment]
Failures are unrelated.

File: modules/navier_stokes/doc/content/source/linearfvkernels/LinearWCNSFVMomentumFlux.md [hunk 5]
```diff
@@ -52,6 +52,45 @@ the first term so the user can elect to disable them using [!param](/LinearFVKer
...
+  remaining volumetric contribution $2 \mu u_r / r^2$ is supplied by
+  [LinearFVRZViscousSource.md]. When [!param](/LinearFVKernels/LinearWCNSFVMomentumFlux/use_deviatoric_terms)
+  is enabled (and likewise
+  [!param](/LinearFVKernels/LinearFVRZViscousSource/use_deviatoric_terms)), the source kernel also
+  injects the $-\tfrac{2}{3} \mu \nabla \cdot \vec{u} / r$ correction so the combination of the
+  two kernels reproduces the full cylindrical viscous operator.
+
+Therefore, for problems with space-dependent viscosities or densities in RZ, enable
+[!param](/LinearFVKernels/LinearWCNSFVMomentumFlux/use_deviatoric_terms) together with
+[!param](/LinearFVKernels/LinearFVRZViscousSource/use_deviatoric_terms) so the explicit hoop stress
```
Comment (lindsayad) [inline modules/navier_stokes/doc/content/source/linearfvkernels/LinearWCNSFVMomentumFlux.md]: these both just render as hyperlinks with the text `use_deviatoric_terms`. You might want to prefix with "this kernel's" and "LinearFVRZViscousSource's" respectively to make things more clear for the reader

File: modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+    if (isParamValid("v"))
+      _velocity_vars[1] = get_velocity_var("v");
+
+    if (!_velocity_vars[0])
+      paramError("u", "The x-velocity must be provided when using deviatoric terms.");
+    if (!_velocity_vars[1])
+      paramError("v", "The y-velocity must be provided when using deviatoric terms.");
+
+    for (const auto dir : make_range(_dim))
+      const_cast<MooseLinearVariableFVReal *>(_velocity_vars[dir])->computeCellGradients();
```
Comment (lindsayad) [inline modules/navier_stokes/src/linearfvkernels/LinearFVRZViscousSource.C]: Maybe just store them as non-const

File: modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex-rz/test.py [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=2, slope_precision=1)
+        fig.save('symmetric-vortex-rz.png')
+        for key, value in fig.label_to_slope.items():
+            print(f"{key}, {value}")
+            if key == "L2u":
+                self.assertTrue(fuzzyAbsoluteEqual(value, 2.0, 0.25))
+            elif key == "L2v":
+                self.assertTrue(fuzzyAbsoluteEqual(value, 3.0, 0.25))
```
Comment (lindsayad) [inline modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex-rz/test.py:29]: say whaaat?! Super-convergence?

Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex-rz/test.py:29]: Do you have an explanation for the super-convergence? There are certainly legitimate superconvergence cases but I've also had instances of superconvergence when I actually had a bug behind the scenes

Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-symmetric-vortex-rz/test.py:29]: The reason is that we are not entrely in the asymptotic range yet. We would need one more refinement which would prevent this to run in the regular test. I would prefer not adding it to heavy because we won't run those out of tree and can run into situations like the skewness correction.

**Comment by lindsayad** [comment]
Seems like this is ready for you to merge @grmnptr. Failures are unrelated

**Comment by grmnptr** [comment]
To merge this I would still need an approval :D
Other than that I am waiting from the green light from the CI lead.

**Comment by grmnptr** [comment]
I would also like for this go in first:
https://github.com/idaholab/moose/pull/31939

Considering it intriduces changes in the production computation which ould influence the linear PR as well.

**Comment by GiudGiud** [comment]
I would like the k-epsilon physics to go first, because it fixes the boundary conditions of those tests you fixed the production for. 

And because it's been there since August.

**Comment by grmnptr** [comment]
Sounds good to me!

**Comment by lindsayad** [comment]
> To merge this I would still need an approval :D

you have two approvals I believe? Anyway sounds good that this will take its place in a line

**Comment by grmnptr** [comment]
Ahhh you are right, I just glanced at the side bar seeing two pending reviews. But I forgot that I requested multiple rounds. Didn't even check the bottom of the PR.
