### PR TITLE
Fix multiple smaller things

### LINKED ISSUE #9714: Erroneous p-convergence for 3D DG diffusion test
### Description of the enhancement or error report
moose/test/tests/dgkernels/3d_diffusion_dg shows erroneous p convergence. 
I was increasing `Variables/u/order` from FIRST to FIFTH and get the following:
```
| time           | dofs           | h              | l2_err         |
|   1.000000e+00 |   5.000000e+02 |   3.464102e-01 |   5.895698e-02 |
|   1.000000e+00 |   1.250000e+03 |   3.464102e-01 |   6.322041e-02 |
|   1.000000e+00 |   2.500000e+03 |   3.464102e-01 |   6.363073e-02 |
|   1.000000e+00 |   4.375000e+03 |   3.464102e-01 |   6.364727e-02 |
|   1.000000e+00 |   7.000000e+03 |   3.464102e-01 |   6.364829e-02 |
```
Looks like the solution does converge to something very rapidly as expected but not converge to the expected manufactured solution.

### Rationale for the enhancement or information for reproducing the error
By just looking at the input, I cannot find anything wrong. Further investigation is needed.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Could be a bug or something we ignored.

### PR DESCRIPTION
**Pull request by YaqiWang**
Including:
1. do not assemble Jacobian for JFNK solve type;
2. requiring flags in MOOSE variable getters are not set;
3. add more buffer flushes so that messages can show up on screen quickly;
4. a small type in 3D DG diffusion test.

This will close #9714.

### CODE REVIEW

**Comment by YaqiWang** [comment]
@jwpeterson can you take a look? These are simple small fixes, should be just ready for merging.

File: framework/include/base/MooseVariable.h [hunk 1]
```diff
@@ -196,8 +196,16 @@ class MooseVariable : public MooseVariableBase
...
+  const VariableValue & nodalSln()
+  {
+    _need_nodal_u = true;
+    return _nodal_u;
+  }
+  const VariableValue & nodalSlnOld()
+  {
+    _need_nodal_u_old = true;
+    return _nodal_u_old;
+  }
```
Comment (andrsd) [inline framework/include/base/MooseVariable.h]: Do you have an input file that shows that not setting `_need_nodal_u` in `nodalSln` is a problem?

File: framework/src/outputs/Console.C [hunk 2]
```diff
@@ -366,7 +366,7 @@ Console::output(const ExecFlagType & type)
       _old_nonlinear_norm = std::numeric_limits<Real>::max();
 
     _console << std::setw(2) << _nonlinear_iter
-             << " Nonlinear |R| = " << outputNorm(_old_nonlinear_norm, _norm) << '\n';
+             << " Nonlinear |R| = " << outputNorm(_old_nonlinear_norm, _norm) << std::endl;
```
Comment (andrsd) [inline framework/src/outputs/Console.C]: I thought this was there on purpose, because we did not want to flush the buffers all the time during the solve. On clusters with slow file systems, where the output goes into a file, this might be a problem.  Did you do any testing/timings there?

File: framework/src/outputs/Console.C [hunk 3]
```diff
@@ -378,7 +378,7 @@ Console::output(const ExecFlagType & type)
       _old_linear_norm = std::numeric_limits<Real>::max();
 
     _console << std::setw(7) << _linear_iter
-             << " Linear |R| = " << outputNorm(_old_linear_norm, _norm) << '\n';
+             << " Linear |R| = " << outputNorm(_old_linear_norm, _norm) << std::endl;
```
Comment (andrsd) [inline framework/src/outputs/Console.C]: Same here.

File: framework/src/base/FEProblemBase.C [hunk 4]
```diff
@@ -3662,6 +3663,13 @@ FEProblemBase::init()
 
   ghostGhostedBoundaries(); // We do this again right here in case new boundaries have been added
 
+  // do not assemble system matrix for JFNK solve
+  if (solverParams()._type == Moose::ST_JFNK)
+  {
+    _nl->system().set_basic_system_only();
+    _nl->nonlinearSolver()->jacobian = NULL;
+  }
```
Comment (andrsd) [inline framework/src/base/FEProblemBase.C]: Should this be in `NonlinearSystemBase`?

File: framework/src/preconditioners/PhysicsBasedPreconditioner.C [hunk 5]
```diff
@@ -138,11 +138,14 @@ PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(const InputParameters & p
...
 
-  // We don't want to be computing the big Jacobian!
-  _nl.nonlinearSolver()->jacobian = NULL;
   _nl.nonlinearSolver()->attach_preconditioner(this);
 
-  _fe_problem.solverParams()._type = Moose::ST_JFNK;
+  if (_fe_problem.solverParams()._type != Moose::ST_JFNK)
+  {
+    mooseWarning(
+        "PBP should be used with JFNK solve type, thus Executioner/solve_type is set to JFNK");
```
Comment (andrsd) [inline framework/src/preconditioners/PhysicsBasedPreconditioner.C]: I think this should be an error. People should fix their input files. Say something like "PBP can be used only with JFNK. Please, change your solve_type."

File: framework/include/base/MooseVariable.h (hunk 1 above)
Comment (YaqiWang) [inline framework/include/base/MooseVariable.h]: I do, but it is a rattlesnake input. If you recall the ElementKernel stuff I proposed, you could remember that that one requires this as well.

File: framework/src/outputs/Console.C (hunk 2 above)
Comment (YaqiWang) [inline framework/src/outputs/Console.C]: No, I did not, but we can imagine that the number of this flush at most is hundreds, its impact on timing should be negligible. I'd rather to keep more flushes unless that flush is in places like a kernel computeresidual.

File: framework/src/base/FEProblemBase.C (hunk 4 above)
Comment (YaqiWang) [inline framework/src/base/FEProblemBase.C]: Nope, because _nl->init happens after _eq.init(), although we probably can move _nl->init above. That will require more changes which I am hesitating to do.

File: framework/src/preconditioners/PhysicsBasedPreconditioner.C (hunk 5 above)
Comment (YaqiWang) [inline framework/src/preconditioners/PhysicsBasedPreconditioner.C]: No problem to me, moose tests are erroring out on this anyway, ;-)

File: framework/src/base/FEProblemBase.C (hunk 4 above)
Comment (YaqiWang) [inline framework/src/base/FEProblemBase.C]: also seems to me FEProblem is the driver and owns this operation.

File: framework/include/base/MooseVariable.h (hunk 1 above)
Comment (andrsd) [inline framework/include/base/MooseVariable.h]: I remember `ElementKernel`, but AFAIK it is not in MOOSE right now. So if you implemented something like that in Rattlesnake, you are not fixing a bug, you are just using an incorrect API. Go look at `MooseVariable::nodalValue()` that will flip the flag and will give you the right memory back.

Or if you have a MOOSE input file that shows this is a problem, I would like to see that.

**Comment by YaqiWang** [comment]
@andrsd that warning is changed to error. Anything else you need me to answer?

File: framework/src/outputs/Console.C (hunk 2 above)
Comment (andrsd) [inline framework/src/outputs/Console.C]: I do not understand your argument about hundreds. You added a flush in each NL and linear iteration. Easily there can be hundreds iterations just within a single NL step.

File: framework/include/base/MooseVariable.h (hunk 1 above)
Comment (YaqiWang) [inline framework/include/base/MooseVariable.h]: Nope, I need this for elemental variables.

File: framework/src/outputs/Console.C (hunk 2 above)
Comment (permcody) [inline framework/src/outputs/Console.C]: I imagine there would be a huge impact to codes like Relap-7 while almost none to Rattlesnake. @YaqiWang, are you really losing output, or just don't like the buffering?

File: framework/src/base/FEProblemBase.C (hunk 4 above)
Comment (andrsd) [inline framework/src/base/FEProblemBase.C]: Well you could do something like:
```
if (solverParams()._type == Moose::ST_JFNK)
  _nl.turnOffPreconditioning();
```
And add your 2 lines into this new method.

File: framework/src/outputs/Console.C (hunk 2 above)
Comment (YaqiWang) [inline framework/src/outputs/Console.C]: Not losing the output. I guess I can remove the flush here, because we must have a flush already in iterations somewhere. The flush in action is more important to me. Also we are not flushing files but just screen. The impact should be very small.

File: framework/src/base/FEProblemBase.C (hunk 4 above)
Comment (YaqiWang) [inline framework/src/base/FEProblemBase.C]: This I agree. But we can have a better and more direct name `turnOffJacobian`.

**Comment by permcody** [comment]
You'd think, but screen I/O can slow you down just like file I/O. There's
not much of a difference, it's still a file and you are interrupting the
process to force the flush.

File: framework/include/base/MooseVariable.h (hunk 1 above)
Comment (YaqiWang) [inline framework/include/base/MooseVariable.h]: I think we should merge these two functions into one. But that will leave to the complete cleanup of MooseVariable.C later.

**Comment by YaqiWang** [comment]
This remind me that calling mooseError could terminate the run without flushing the buffer. @permcody did you fix that issue I created before?

**Comment by YaqiWang** [comment]
Took me a while to find the issue https://github.com/idaholab/moose/issues/6615, yes, it has been fixed.

**Comment by YaqiWang** [comment]
This is ready for merging. I need this to be merged in my MR in rattlesnake.

File: framework/src/outputs/Console.C (hunk 2 above)
Comment (andrsd) [inline framework/src/outputs/Console.C]: > The flush in action is more important to me.

I do not have a problem with that one.

> Also we are not flushing files but just screen. The impact should be very small.

1) On clusters where you are running a batch job, the screen output is redirected to a file. 2) Terminal emulators are not that fast as you would think. 3) Console can be easily redirected to a file via 2 parameters, so your assumption that we are flushing just screen is not correct.

File: framework/include/base/MooseVariable.h (hunk 1 above)
Comment (andrsd) [inline framework/include/base/MooseVariable.h]: I would still like to see the input file that shows the problem...

Comment (YaqiWang) [inline framework/include/base/MooseVariable.h]: You are wasting our time. Creating an input file probably with some source files is not worth especially for a bug this obvious. If you really care, go take a look at 3c06af725cfaf3fac05fb44c3fb064a2c01bed31.

Comment (andrsd) [inline framework/include/base/MooseVariable.h]: Yes, I do really care. Left you there a comment. You are using the wrong method there. You may want to re-read [my comment](https://github.com/idaholab/moose/issues/9690#issuecomment-323072876) on your #9690.

**Comment by YaqiWang** [comment]
Regardless my usage, 558ac2569a579c356bd7ecf2bfda1eb0c63aac1b by itself is a simple fix. I agree MooseVariable needs to be cleaned up. So can we merge this? I am waiting for this. Thanks.

**Comment by andrsd** [comment]
I am against merging 558ac25, because IMO is not fixing anything. If there is an input file + code that shows it is a bug, I would change my opinion. All I saw so far was an incorrect usage of the API.

At the end of our discussion yesterday, you wanted access to solution coefficients for elemental variables and I do not think this should the way how to get them. There should be an API for that.

The rest of this PR is fine with me.

**Comment by YaqiWang** [comment]
I disagree. That function returns `_nodal_u` and obviously it should set `_need_nodal_u` as all other functions. Maybe we should have a vote.

**Comment by andrsd** [comment]
And I explained why things are the way they are.

I am fine with the vote.

**Comment by YaqiWang** [comment]
@permcody, @andrsd and me had argument on 558ac25. I need that fix for my codes in Rattlesnake for pebble bed reactor analysis. Can you find a resolution? Thanks.

**Comment by permcody** [comment]
@YaqiWang - This is in the heart of David's contributions. He explained the design. Rather than providing a fix that seems to conflict with the design, can you be very specific about the interface you require? I'm not comfortable going in and changing it if David explains why it is the way it is. Do you just need to differentiate between these two different cases? Clearly MOOSE doesn't need this, but if you do, we can talk about adding that capability. Yeah, I can see your point about the confusing name, but it is part of the design. If David changed it to _need_nodal_u_for_case1_and_case2 then it wouldn't make sense to patch it your way.

Yes, we care. Yes, we want to support you.

**Comment by YaqiWang** [comment]
I basically need to call `nodalSln()` for getting all local solution dofs for elemental variables. But currently even I required `_nodal_u` with `nodalSln()`, `MooseVariable` is not setting `_need_nodal_u` and thus not evaluate it for me. Whether or not I should call `nodalSln()` is another story. @andrsd might have something in mind, but it is the only way for me currently. Even MooseVariable is refactored, I do not think fixing downstream application is hard. We do this all the time. I do not understand why this is an issue!

**Comment by andrsd** [comment]
The purpose of `nodalSln()` is _not_ to give back local solution DoFs. And it should not be used for that. If you need the local DOFs, create a special method for it. And by doing that you will avoid fixing the downstream applications when we actually do changes to `MooseVariable`.

**Comment by YaqiWang** [comment]
While, the contents of this new function will be exactly the same as `nodalSln()`.

**Comment by andrsd** [comment]
I am talking about a function like this:
```
void MooseVariable::getLocalSolution(const Elem * elem, std::vector<Real> & localSln)
{
  std::vector<dof_id_type> dof_indices;
  _dof_map.dof_indices(elem, dof_indices, _var_num);
  unsigned int num_dofs = _dof_indices.size();
  localSln.resize(num_dofs);
  for (unsigned int i = 0; i < num_dofs; i++)
    localSln[i] = (*_sys.currentSolution())(_dof_indices[i]);
}
```

File: framework/include/base/MooseVariable.h [hunk 6]
```diff
@@ -402,6 +402,27 @@ class MooseVariable : public MooseVariableBase
   Number getElementalValue(const Elem * elem, unsigned int idx = 0) const;
 
   /**
+   * Retrieve all the Elemental DOFs
+   * @param elem The element we are computing on
+   * @dofs The retrieved DOFs
```
Comment (andrsd) [inline framework/include/base/MooseVariable.h]: This should read: `@param dofs`. The same problem in the other methods.

**Review by andrsd — CHANGES_REQUESTED** [review]

**Comment by YaqiWang** [comment]
I changed my mind: these function makes my kernels really ugly. I will create a new PR. It will add a function `elementalValues()` to return a reference and add `coupledElementalValues` into `Coupleable`. I will also submit a test for it. The commit in this PR will be dropped.

**Comment by YaqiWang** [comment]
This should be ready.

**Review by andrsd — APPROVED** [review]

**Comment by brianmoose** [comment]
This broke the examples: https://www.moosebuild.org/job/112555/

**Comment by YaqiWang** [comment]
Will fix it shortly...
