### PR TITLE
Fixing moose_unit

### LINKED ISSUE #4986: MooseUnit is broken on devel
```text
-------------------------------------------------
/Users/slauae/projects/moose/unit/run_tests -j 24
-------------------------------------------------

##Failure Location unknown## : Error
Test name: EBSDMeshErrorTest::geometrySpecifiedError
setUp() failed
- uncaught exception of type St13runtime_error
- 



*** ERROR ***
A 'MarmotUnitApp' is not a registered object





##Failure Location unknown## : Error
Test name: EBSDMeshErrorTest::fileDoesNotExist
setUp() failed
- uncaught exception of type St13runtime_error
- 



*** ERROR ***
A 'MarmotUnitApp' is not a registered object





##Failure Location unknown## : Error
Test name: EBSDMeshErrorTest::headerError
setUp() failed
- uncaught exception of type St13runtime_error
- 



*** ERROR ***
A 'MarmotUnitApp' is not a registered object





##Failure Location unknown## : Error
Test name: ParsedFunctionTest::advancedConstructor
uncaught exception of type St13runtime_error
- 



*** ERROR ***
Number of vars must match the number of vals for a MooseParsedFunction!



##Failure Location unknown## : Error
Test name: ParsedFunctionTest::testVariables
uncaught exception of type St13runtime_error
- 



*** ERROR ***
Number of vars must match the number of vals for a MooseParsedFunction!



Failures !!!
Run: 131   Failure total: 5   Failures: 0   Errors: 5
Memory leak detected!
Compile in DEBUG mode with --enable-reference-counting
for more information
```

### PR DESCRIPTION
**Pull request by permcody**
closes #4986 

Adding an "if" statement to the end of the run_tests scripts in 101b743b broke the ability of the script to return the proper exit code on failure. As a result several regressions occured that went unnoticed. This patch fixes the script and repairs all of the regressions.

@dschwen - You have several unit tests for ParsedFunctions that allowed different numbers of var/value pairs. However you removed that ability in fdb2db2e. Please review my changes and let me know which way you'd rather have it.

### CODE REVIEW

File: unit/src/EBSDMeshErrorTest.C [hunk 1]
```diff
@@ -28,7 +28,7 @@ void
 EBSDMeshErrorTest::setUp()
 {
   const char *argv[2] = { "foo", "\0" };
-  _app = AppFactory::createApp("MarmotUnitApp", 1, (char**)argv);
+  _app = AppFactory::createApp("MooseUnitApp", 1, (char**)argv);
```
Comment (jwpeterson) [inline unit/src/EBSDMeshErrorTest.C]: Hahaha, oops

Comment (jwpeterson) [inline unit/src/EBSDMeshErrorTest.C]: If we change the unit tests, should we actually run them before committing the changes?

Comment (dschwen) [inline unit/src/EBSDMeshErrorTest.C]: Ugh, that was migrated recently. Why did this ever pass moosetest?!

**Comment by dschwen** [comment]
fdb2db2 did not remove any capability, it just made the input syntax testing more strict. Previously you could create silently broken parsed functions.

**Comment by permcody** [comment]
Ok, then this PR should be good. If you read my description, you'll see why moosebuild didn't catch these regressions.
