### PR TITLE
Make string references const 

### LINKED ISSUE #12045: Make string reference parameters const where possible
## Rationale

Some moose APIs take non-const string references, such as `AddVariableAction::addVariable`. This prevents the use of temporary strings when calling these methods.

```
error: non-const lvalue reference to type 'basic_string<...>' cannot bind to a temporary of type 'basic_string<...>'
``` 

## Description

Setting the parameter value to `const ` can be done without any change in functionality if the referenced parameter is not modified. This also improves code readability by making clear that no side effects occur.

## Impact

Make API more flexible (backwards compatible)

### PR DESCRIPTION
**Pull request by dschwen**
This allows code like

```
addVariable(name() + "i" + Moose::stringify(num));
```

which previously had to be written with a non-temporary variable

```
std::string var_name = name() + "i" + Moose::stringify(cur_num);
addVariable(var_name);
```

Closes #12045

### CODE REVIEW

File: modules/xfem/include/base/XFEM.h [hunk 1]
```diff
@@ -172,7 +172,7 @@ class XFEM : public XFEMInterface
    */
   std::vector<Real> & getXFEMCutData();
   void setXFEMCutData(std::vector<Real> & cut_data);
-  std::string & getXFEMCutType();
+  // std::string & getXFEMCutType();
```
Comment (permcody) [inline modules/xfem/include/base/XFEM.h]: What happened here?

Comment (permcody) [reply modules/xfem/include/base/XFEM.h]: OK - normally we'd just delete it then :)

Comment (dschwen) [reply modules/xfem/include/base/XFEM.h]: I just talked to @bwspenc and ended up removing a few more member declarations of methods that were factored away a while ago. The non-const string arguments of at least one of those puts this in the issue scope IMO.

**Review by permcody — APPROVED** [review]
