### PR TITLE
Zero material property fix

### LINKED ISSUE #6360: Still construction order dependence for DerivativeSumMaterial
The dependency system is not dealing correctly with `DerivativeSumMaterials` blocks preceding the material blocks that define the free energies used in the sum.

### PR DESCRIPTION
**Pull request by dschwen**
This changes the way zero material properties are handled internally and should make them correctly work with block and boundary restrictions.

Zero material properties are now simply exempt from the material property consistency check. This should get rid of the double declare @aeslaughter saw.

This should also take care of the construction order dependence issue with derivative material properties.

Closes #6360

### CODE REVIEW

**Comment by permcody** [comment]
Thanks. I'll take a look

**Comment by dschwen** [comment]
Hmm. Two failed tensor mechanics tests. I'll investigate.

**Comment by dschwen** [comment]
Ok, @permcody, there are two places where I have to override a missing material properties check.

1. `SubProblem::checkMatProps`, I've got this down, it works. The `_zero_block_material_props` and `_zero_boundary_material_props` are members of `SubProblem`. Everything is hunky dory.
2. `FEProblem::checkDependMaterialsHelper`. Arggh, what is going on. `_zero_block_material_props` and `_zero_boundary_material_props` look empty from this method? Why, god, why?! 

So the problem seems to be that FEProblem does not see the right `_zero_block_material_props`. Any ideas?

**Comment by permcody** [comment]
I'm not sure. I don't even know if that's my code. I'd have to dig in.

**Comment by dschwen** [comment]
@permcody I figured that one out. I needed to also exempt the properties on `Moose::ANY_BLOCK_ID` in that check!

File: framework/include/base/SubProblem.h [hunk 1]
```diff
@@ -310,6 +331,10 @@ class SubProblem : public Problem
   /// Map for boundary material properties (boundary_id -> list of properties)
   std::map<unsigned int, std::set<std::string> > _map_boundary_material_props;
 
+  /// Set of properties returned as zero properties
+  std::map<unsigned int, std::set<MaterialPropertyName> > _zero_block_material_props;
+  std::map<unsigned int, std::set<MaterialPropertyName> > _zero_boundary_material_props;
```
Comment (permcody) [inline framework/include/base/SubProblem.h]: You should use `SubdomainID` and `BoundaryID` in place of these `unsigned int`s

File: framework/include/base/SubProblem.h [hunk 2]
```diff
@@ -348,6 +373,7 @@ class SubProblem : public Problem
    */
   void checkMatProps(std::map<unsigned int, std::set<std::string> > & props,
                      std::map<unsigned int, std::multimap<std::string, std::string> > & check_props,
+                     std::map<unsigned int, std::set<MaterialPropertyName> > & zero_props,
```
Comment (permcody) [inline framework/include/base/SubProblem.h]: Same here. In general as you see these unsigned int types floating around, let's convert them to the correct types. I've been doing that in `MooseMesh`

**Comment by permcody** [comment]
Looks good once you fix up those types.

File: framework/include/base/SubProblem.h (hunk 2 above)
Comment (dschwen) [inline framework/include/base/SubProblem.h]: Well, this is a bit more involved than just changing types. Both, block and boundary, variants are passed into `checkMatProps`. To switch over to the correct types this function would need to get templated! We then could remove the type string parameter entirely and replace it with a template specialized helper function. Would be a bit more elegant but I thought it was beyond the scope of this PR. 
I've noticed the convolution of issues blowing up certain other PRs, which makes them rather cumbersome to review. I'd like to avoid this. I'd be happy to address this in another PR.

Comment (permcody) [inline framework/include/base/SubProblem.h]: OK - Agreed, let's take care of that later.

**Comment by permcody** [comment]
:+1:
