### PR TITLE
Catch exceptions from UserObject evaluation

### LINKED ISSUE #26685: Exception during UserObject evaluation not caught
## Bug Description
I have a problem from a BISON user that is throwing an exception from a material model during UserObject evaluation that is not being caught. This should be caught like other similar exceptions and result in retrying the solve.

## Steps to Reproduce
I have the BISON input file but can't post it here.

## Impact
This is preventing a needed simulation from running to completion.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #26685

### CODE REVIEW

File: framework/src/problems/FEProblemBase.C [hunk 1]
```diff
@@ -6758,6 +6763,8 @@ FEProblemBase::computeBounds(NonlinearImplicitSystem & libmesh_dbg_var(sys),
   _lower.swap(lower);
   _upper.swap(upper);
 
+  //BWS: In all other cases where this is called, it's within a try/catch to strip
```
Comment (bwspenc) [inline framework/src/problems/FEProblemBase.C:6766]: This is a note to self that I will remove when I have resolved this outstanding question.

File: framework/src/problems/FEProblemBase.C [hunk 2]
```diff
@@ -6758,6 +6779,8 @@ FEProblemBase::computeBounds(NonlinearImplicitSystem & libmesh_dbg_var(sys),
   _lower.swap(lower);
   _upper.swap(upper);
 
+  // BWS: In all other cases where this is called, it's within a try/catch to strip
+  // out the exception. Should that be done here too?
   checkExceptionAndStopSolve();
```
Comment (lindsayad) [inline framework/src/problems/FEProblemBase.C:6784]: Yes we should

Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:6784]: Actually no I don't think we should. I am not 100% confident that this function is called during a solve, in which case I would rather have an uncaught exception that leads to simulation termination than a silenced exception

File: framework/src/problems/FEProblemBase.C [hunk 3]
```diff
@@ -6297,10 +6332,6 @@ FEProblemBase::computeResidualAndJacobian(const NumericVector<Number> & soln,
     }
     catch (MooseException & e)
     {
-      _console << "\nA MooseException was raised during Auxiliary variable computation.\n"
-               << "The next solve will fail, the timestep will be reduced, and we will try again.\n"
-               << std::endl;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:6302]: It looks like we would...

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: framework/include/problems/FEProblemBase.h [hunk 4]
```diff
@@ -488,6 +501,13 @@ class FEProblemBase : public SubProblem, public Restartable
    */
   virtual void checkExceptionAndStopSolve(bool print_message = true);
 
+private:
+  /**
+   * Reset state of this object in preparation for the next evaluation.
+   */
+  virtual void resetState();
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/include/problems/FEProblemBase.h:508]: Happy to do that. I wasn't sure what the preference was.

File: framework/src/problems/FEProblemBase.C [hunk 5]
```diff
@@ -4304,216 +4304,218 @@ FEProblemBase::computeUserObjectsInternal(const ExecFlagType & type,
   for (const auto & uo : uos)
     execution_groups.insert(uo->getParam<int>("execution_order_group"));
 
-  // iterate over execution order groups
-  for (const auto execution_group : execution_groups)
+  try
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:4307]: Makes sense, will do.

File: framework/src/problems/FEProblemBase.C [hunk 6]
```diff
@@ -5852,6 +5854,21 @@ FEProblemBase::setException(const std::string & message)
   _exception_message = message;
 }
 
+void
+FEProblemBase::setException(const ExecFlagType & type, const std::string & message)
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:5858]: Good catch! I had meant to use it on lines 4496 and 4502 of this file in place of the now-removed `process_possibly_handleable_exception`. I'll switch those over to use this.

File: framework/src/problems/FEProblemBase.C (hunk 3 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:6302]: I agree that this is valuable information that we don't want to lose. I believe what I was thinking was that this would get printed out later, but in looking at the output from the test case that motivated this (which also triggered some of these), I'm not getting what I wanted. I'll look into this.

File: framework/src/problems/FEProblemBase.C [hunk 7]
```diff
@@ -6554,7 +6575,7 @@ FEProblemBase::computeResidualTags(const std::set<TagID> & tags)
   _safe_access_tagged_vectors = false;
   _current_nl_sys->computeResidualTags(tags);
   _safe_access_tagged_vectors = true;
-  reset_state();
+  resetState();
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:6578]: This line gets hit during normal execution with no exceptions, which led me to believe that we need to do that resetting stuff all the time.

File: framework/src/problems/FEProblemBase.C (hunk 2 above)
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:6784]: OK, I'll just remove that comment and consider that resolved.

I do wonder whether it's worthwhile to add a parameter to `checkExceptionAndStopSolve()` (or another variant of it) that makes it not throw an exception. There are an awful lot of try/catch blocks around calls to this just to strip out the exception.

Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:6784]: Ok I looked into this more. This is called during setup of the nonlinear solver, so not during the Newton iterations. So if we have an exception at this point, then it is like having an exception for execution flags `!EXEC_LINEAR && !EXEC_NONLINEAR`, in which case we should mooseError. So I think in this function we should wrap the `_aux->compute` in a `try` and then in the `catch` we should `mooseError`

File: framework/src/problems/FEProblemBase.C [hunk 8]
```diff
@@ -5852,6 +5854,21 @@ FEProblemBase::setException(const std::string & message)
   _exception_message = message;
 }
 
+void
+FEProblemBase::setException(const ExecFlagType & type, const std::string & message)
+{
+  if (type == EXEC_LINEAR || type == EXEC_NONLINEAR)
```
Comment (lindsayad) [inline framework/src/problems/FEProblemBase.C:5860]: So thinking again about this, I do think we should limit this to `EXEC_LINEAR`. This is because our stopping mechanism in `NonlinearSystem::stopSolve()` is `SNESSetFunctionDomainError(solver.snes());` which is not going to be checked by PETSc during a nonlinear/Jacobian evaluation

File: framework/src/problems/FEProblemBase.C [hunk 9]
```diff
@@ -4304,216 +4304,218 @@ FEProblemBase::computeUserObjectsInternal(const ExecFlagType & type,
...
+    moose::translateMetaPhysicLError(e);
+  }
+  try
+  {
+    // Propagate the exception to all processes if we had one
+    checkExceptionAndStopSolve();
+  }
+  catch (MooseException &)
+  {
+    // Just end now. We've inserted our NaN into the residual vector
```
Comment (lindsayad) [inline framework/src/problems/FEProblemBase.C:4517]: Paired with my comment above, can we `mooseAssert(type == EXEC_LINEAR, "We should only be continuing if this is a linear/residual evaluation and consequently we know we've inserted a NaN in the residual vector");` or some message like that right here? Then we are confident in this comment

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: framework/src/problems/FEProblemBase.C (hunk 6 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:5860]: I'm calling this version of `setException` in most cases now.

File: framework/src/problems/FEProblemBase.C [hunk 10]
```diff
@@ -5872,7 +5891,12 @@ FEProblemBase::checkExceptionAndStopSolve(bool print_message)
 
     // Print the message
     if (_communicator.rank() == 0 && print_message)
-      Moose::err << _exception_message << std::endl;
+    {
+      _console << "\nThe following exception was caught in FEProblemBase:\n";
```
Comment (bwspenc) [inline framework/src/problems/FEProblemBase.C:5895]: Note that this was going to `Moose::err` before, but that made the output weird. I think the standard console output is where we want this.

File: framework/src/problems/FEProblemBase.C (hunk 3 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:6302]: I'm pretty sure this is how we want this. The part about the solution failing and the step getting cut is printed out in `FEProblemBase::checkExceptionAndStopSolve()`

File: framework/src/problems/FEProblemBase.C [hunk 11]
```diff
@@ -6521,27 +6553,16 @@ FEProblemBase::computeResidualTags(const std::set<TagID> & tags)
...
-  };
   try
   {
     _aux->compute(EXEC_LINEAR);
   }
   catch (MooseException & e)
   {
-    _console << "\nA MooseException was raised during Auxiliary variable computation.\n"
-             << "The next solve will fail, the timestep will be reduced, and we will try again.\n"
-             << std::endl;
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:6538]: I think this is resolved per the discussion in the other comment.

**Comment by lindsayad** [comment]
@bwspenc just mention me here when this is ready for me to take over and investigate the automatic scaling issue

File: framework/include/problems/FEProblemBase.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/include/problems/FEProblemBase.h]: This is done

File: framework/src/problems/FEProblemBase.C (hunk 5 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C]: Done

File: framework/src/problems/FEProblemBase.C (hunk 6 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C]: I ended up just getting rid of this new version of setException() and moved the additional checking elsewhere, so this isn't relevant anymore.

File: framework/src/problems/FEProblemBase.C (hunk 7 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:6589]: of course, silly me

File: framework/src/systems/NonlinearSystem.C [hunk 12]
```diff
@@ -234,29 +212,27 @@ NonlinearSystem::solve()
...
-  _nl_implicit_sys.rhs->close();
-
-  // Clean up by getting other vectors into a valid state for a
-  // (possible) subsequent solve.  There may be more than just
-  // these...
-  if (_Re_time)
-    _Re_time->close();
-  _Re_non_time->close();
+
+  if (exec_flag == EXEC_LINEAR || exec_flag == EXEC_POSTCHECK)
```
Comment (bwspenc) [inline framework/src/systems/NonlinearSystem.C:220]: I assume these should match what is in `FEProblemBase::checkExceptionAndStopSolve()`, right? Is it intentional that `EXEC_NONLINEAR` is missing?

Comment (lindsayad) [reply framework/src/systems/NonlinearSystem.C:220]: No. That's handled a few lines later

**Comment by lindsayad** [comment]
Ok, I'm hoping after this most recent commit the only (real) failures are the two "high-Zr" tests in BISON. These tests throw exceptions on initial because the user supplies bad initial conditions. @bwspenc if you can decide what to do about those, that would be much appreciated

**Comment by lindsayad** [comment]
@loganharbour @milljm I think that at some point a wasp submodule update must have been supplied in this PR. Now I'm stuck with a wasp on conda that is from this PR I think and that's why I'm getting these continued conda recipe failures. Is there any way to fix that and force the recipes to use the regular conda channel?

**Comment by loganharbour** [comment]
> @loganharbour @milljm I think that at some point a wasp submodule update must have been supplied in this PR. Now I'm stuck with a wasp on conda that is from this PR I think and that's why I'm getting these continued conda recipe failures. Is there any way to fix that and force the recipes to use the regular conda channel?

Should be good now

**Comment by lindsayad** [comment]
awesome, thank you!

File: framework/src/systems/NonlinearSystem.C (hunk 12 above)
Comment (bwspenc) [reply framework/src/systems/NonlinearSystem.C:220]: Duhh... I see that now!

File: framework/src/problems/FEProblemBase.C [hunk 13]
```diff
@@ -5870,28 +5857,69 @@ FEProblemBase::checkExceptionAndStopSolve(bool print_message)
...
 
-    // Repropagate the exception, so it can be caught at a higher level, typically
-    // this is NonlinearSystem::computeResidual().
-    throw MooseException(_exception_message);
+      // Repropagate the exception, so it can be caught at a higher level, typically
+      // this is NonlinearSystem::computeResidual().
+      throw MooseException(_exception_message);
+    }
+    else
+      mooseError("The following parallel-communicated exception was detected during " +
```
Comment (bwspenc) [inline framework/src/problems/FEProblemBase.C:5894]: @lindsayad What do you think about this message? Would you rather just call it a "MooseException" like we did before? Maybe a "parallel-communicated MooseException"? I kind of like including the parallel bit because it clarifies the fact that it has been communicated in parallel already.

File: framework/src/systems/NonlinearSystemBase.C [hunk 14]
```diff
@@ -2816,11 +2816,20 @@ NonlinearSystemBase::computeJacobianInternal(const std::set<TagID> & tags)
       // they are almost always used in conjunction with Kernels
       ComputeJacobianForScalingThread cj(_fe_problem, tags);
       Threads::parallel_reduce(elem_range, cj);
+      // BWS TODO Add a call to FEProblemBase::checkExceptionAndStopSolve() here
```
Comment (bwspenc) [inline framework/src/systems/NonlinearSystemBase.C:2819]: @lindsayad I need to delete this before we merge this PR. You took care of that a few lines below. I want to see if the currently running tests pass before I go update this.

File: framework/src/problems/FEProblemBase.C (hunk 13 above)
Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:5894]: I like this message. Yes the parallel bit is good. But also I like that it *doesn't* say MooseException since we handle more exception types than just MooseExceptions

File: framework/src/systems/NonlinearSystemBase.C (hunk 14 above)
Comment (lindsayad) [reply framework/src/systems/NonlinearSystemBase.C]: K I removed it

**Review by lindsayad — APPROVED** [review]
approving Ben's work

**Comment by lindsayad** [comment]
@bwspenc if you approve of what I've done, I think we can get this in

File: framework/src/problems/FEProblemBase.C (hunk 13 above)
Comment (bwspenc) [reply framework/src/problems/FEProblemBase.C:5894]: OK, great -- let's leave it as is.

**Review by bwspenc — COMMENTED** [review]
Approving Alex's changes
