### PR TITLE
Fix threading bug in IC error checks

### LINKED ISSUE #6103: Error checks for ICs and threads not working

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #6103)

### CODE REVIEW

File: framework/src/ics/InitialConditionWarehouse.C [hunk 1]
```diff
@@ -33,40 +33,45 @@ InitialConditionWarehouse::initialSetup(THREAD_ID tid)
 void
 InitialConditionWarehouse::addObject(MooseSharedPointer<InitialCondition> object, THREAD_ID tid)
 {
-  // Check that when object is boundary restricted that the variable is nodal
-  const MooseVariable & var = object->variable();
 
-  // Boundary Restricted
-  if (object->boundaryRestricted())
+  // Perform IC error checking, there is no need to do this on each thread, since they are all the same
```
Comment (permcody) [inline framework/src/ics/InitialConditionWarehouse.C]: While this is true we don't don't restrict error checking anywhere else in the code even when they all threads have the same information. If this is truly failing in threaded mode _only_ then we should figure out why rather than simply skipping this check. If for some reason the threads don't have the same information then this will lead to a seg. fault or another much more difficult to find bug later.

Comment (friedmud) [inline framework/src/ics/InitialConditionWarehouse.C]: Agree with @permcody

Comment (aeslaughter) [inline framework/src/ics/InitialConditionWarehouse.C]: I know why, the error checking relies on lists of object names. So, when those lists are checked from multiple threads there are race conditions.

Comment (aeslaughter) [inline framework/src/ics/InitialConditionWarehouse.C]: I could store tid copies of the name lists and do the checks on each thread, but that seems un-necessary

Comment (permcody) [inline framework/src/ics/InitialConditionWarehouse.C]: You could use a thread-safe container if it's feasible or add a thread
lock. While that might seem extreme this code only runs once so it's worth
the wait to be assured that the system is sane before trying to use it.

**Comment by friedmud** [comment]
Why is any checking like this happening in a threaded region?  Error checking like this should only happen up front... and only on thread 0 (although it may check all of the TID's data).

**Comment by permcody** [comment]
Ah I see, it's not a threaded region. The problem was simply that the check was occuring during the addition of the threaded copies. Each time a new IC was added it was checked on the spot so when the second copy was added in a multi-threaded case it was thinking that another IC was already in place. 

This fix looks ok in that each threaded copy gets it's own spot in the names vector for the check.

**Comment by aeslaughter** [comment]
Cody, you explanation is correct. My race condition statement is wrong,
like you said this is not a threaded region.
