### PR TITLE
Add capability to use SIMPLE with fixed point iterations betweeen multiapps.

### LINKED ISSUE #28819: Add capabilities to use segregated fluid dynamics solvers together with other apps in a fixed point iteration.
### Motivation

Even though they are usable through multiapps, the segregated fluid dynamics solvers can't be used 
for Picard iteration with other physics. this means that tight coupling is not possible at the moment. 
Would be nice if we could do it.

### Design

Add a SIMPLESolveObject that replaces some parts in the executioners. Might require some more development to compute the residuals of multiple systems from the same problem within the fixed point algorithm.

### Impact

Better integration with other MOOSE simulations.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #28819

### CODE REVIEW

File: modules/navier_stokes/src/executioners/SIMPLE.C
Comment (lindsayad) [inline modules/navier_stokes/src/executioners/SIMPLE.C:1]: This executioner sure looks a lot like `Steady` now. Is there any chance for code reuse if you inherit from it?

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: modules/navier_stokes/src/executioners/SIMPLE.C
Comment (grmnptr) [reply modules/navier_stokes/src/executioners/SIMPLE.C:1]: Yeah this duplication is a bummer. The way I see is is that the only difference is that Steady uses `FEProblemSolve` whereas SIMPLE uses `SIMPLESolve`. However, there is some entanglement by adding the parameters of the SolveObject to the Executioner and then reading those parameters in the SolveObject `MooseObject(ex.parameters())`.

Ideally, it would be cool if I could just pass a SolveObject to Steady in the input file. And if I am not mistaken, something similar would be the purpose of the `Executor` system at some point in the future.

However, at the moment depending on which SolveObject Steady uses, all of the input parameters are different. I don't see an immediate way to just using SolveObjects for plug-and-play in the Steady executioner. I can try to open a new PR, and split the SolveObjects into their own MOOSE systems and then just pass those to the executioners. That might be the cleanest. At the same time, that might be a fairly big change in MOOSE, especially that we might get the Executor system soon (even though the same was said 3 years ago when I joined).

Do you see other ways to use plug-and-play SolveObjects in Steady besides splitting it into a new system?

Comment (lindsayad) [reply modules/navier_stokes/src/executioners/SIMPLE.C:1]: nope haha

File: modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+Real
+LinearFVVolumetricHeatTransfer::computeRightHandSideContribution()
+{
+  const auto elem = makeElemArg(_current_elem_info->elem());
+  const auto state = determineState();
+
+  const auto temp_value = _is_solid ? _temp_fluid.getElemValue(*_current_elem_info, state)
+                                    : _temp_solid.getElemValue(*_current_elem_info, state);
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C:68]: Well, the reason why these are not functors is that the functor argument takes `Elem*` whereas the linearFV loops are using `ElemInfo*`. There is a map between the two so these could be functor calls right now. However, the `ElemArg` based functor will add an `Elem->ElemInfo` lookup which can be expensive. At the same time `ElemInfo` actually has all the dof indices of the variables. So in this case this query is just fetching a value from the `NumericVector` directly. If we can change the `ElemArg` to have `ElemInfo` instead, we could use the variables in linearFV with all functors with just a little more of an overhead due to the virtuall call. I might do that in a different PR.

File: modules/navier_stokes/src/executioners/SIMPLE.C
Comment (lindsayad) [reply modules/navier_stokes/src/executioners/SIMPLE.C:1]: what about a static templated method on `Steady`? You'd have to friend the method in the downstream class

File: modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C (hunk 1 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvkernels/LinearFVVolumetricHeatTransfer.C:68]: The functor interfaces are there for the `MooseVariableLinearFV` but some might be a little expensive due to the additional lookups.

File: framework/src/utils/MooseUtils.C [hunk 2]
```diff
@@ -1272,6 +1272,26 @@ prettyCppType(const std::string & cpp_type)
   r.GlobalReplace("std::vector<\\1>", &s);
   return s;
 }
+
+bool
+converged(const std::vector<std::pair<unsigned int, Real>> & its_and_residuals,
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/src/utils/MooseUtils.C:1277]: Nice catch! In simple, they are used in the print. They should be something like this ideally:
```
Iteration 12 Residual norm: 1e-99 Number of linear iterations: 42
```
Or something similar. I am going to add it to the SolveObject responsible for the `LinearSystems`.

File: framework/include/problems/FEProblemBase.h [hunk 3]
```diff
@@ -1300,6 +1300,18 @@ class FEProblemBase : public SubProblem, public Restartable
...
+   * Computes the residual of a nonlinear system using whatever is sitting in the current
+   * solution vector then returns the L2 norm.
+   */
+  virtual Real computeResidualL2Norm(NonlinearSystemBase & sys);
+
+  /**
+   * Computes the residual of a linear system using whatever is sitting in the current
+   * solution vector then returns the L2 norm.
+   */
+  virtual Real computeResidualL2Norm(LinearSystem & sys);
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/include/problems/FEProblemBase.h:1313]: Yes, makes sense! Will change it in the next commit.

File: framework/include/executioners/LinearFixedPointSolve.h
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/include/executioners/LinearFixedPointSolve.h:1]: Yes, I will pull in the latest changes and check how much I can reuse from Guillaume's PR. I was not paying too close of an attention up until yesterday.

File: modules/navier_stokes/src/executioners/SIMPLE.C
Comment (grmnptr) [reply modules/navier_stokes/src/executioners/SIMPLE.C:1]: Aaa, that sounds interesting! I'll give it a shot!

Comment (grmnptr) [reply modules/navier_stokes/src/executioners/SIMPLE.C:1]: I didn't even have to do that, turns out `SegregatedSolverBase` is not used anymore. So I can just create a `SteadyBase` class that shares the member variables and the `execute` function. From this we have `Steady`, `SIMPLENonlinearassembly` and `SIMPLE` which override the other functions like `init()`.

File: framework/doc/content/source/executioners/LinearFixedPointSteady.md [hunk 4]
```diff
@@ -0,0 +1,24 @@
+# LinearFixedPointSteady
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/doc/content/source/executioners/LinearFixedPointSteady.md:1]: Yes it could be done! Pushing soon

**Review by GiudGiud — COMMENTED** [review]
is there a way, maybe using the Debug/show_execution_order, to check that all the expected execution phases (INITIAL, TIMEStEP_BEGIN, MULTIAPP_..., TIMESTEP_END, FINAL) are all present in the new executioners?

File: test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i [hunk 5]
```diff
@@ -91,9 +91,20 @@
...
+[]
+
 [Executioner]
-  type = LinearPicardSteady
-  linear_systems_to_solve = u_sys
+  type = Steady
+  system_names = u_sys
+  l_abs_tol = 1e-10
+  multi_system_fixed_point=true
+  multi_system_fixed_point_convergence=linear
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i:107]: Well, for some of them I can probably remove it. But others will have to solve the same linear system many times to resolve the nonorthogonal correctors, 2term expansions etc.
I also like the `converged_on_max_its` option of the used CV object.

File: framework/src/executioners/Steady.C [hunk 6]
```diff
@@ -50,80 +38,12 @@ Steady::init()
...
 void
 Steady::checkIntegrity()
 {
   // check to make sure that we don't have any time kernels in this simulation (Steady State)
-  if (_problem.getNonlinearSystemBase(/*nl_sys=*/0).containsTimeKernel())
-    mooseError("You have specified time kernels in your steady state simulation");
+  for (const auto & system : _feproblem_solve.systemsToSolve())
+    if (system->containsTimeKernel())
+      mooseError("You have specified time kernels in your Steady state simulation in system ",
+                 system->name());
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/src/executioners/Steady.C:48]: Added!

File: test/tests/transfers/multiapp_copy_transfer/linear_sys_to_aux/linear_sub.i [hunk 7]
```diff
@@ -55,13 +55,23 @@
...
+
 [Executioner]
-  type = LinearPicardSteady
-  linear_systems_to_solve = u_sys
+  type = Steady
+  system_names = u_sys
+  l_tol = 1e-10
   petsc_options_iname = '-pc_type -pc_hypre_type'
   petsc_options_value = 'hypre boomeramg'
+  multi_system_fixed_point=true
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply test/tests/transfers/multiapp_copy_transfer/linear_sys_to_aux/linear_sub.i:72]: I could remove it from this input, other input might need a picard iteration on the nonorthogonal correctors/two-term bcs etc which are all treated explicitly now.

File: test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i (hunk 5 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply test/tests/linearfvkernels/diffusion-reaction-advection/advection-diffusion-reaction-1d.i:107]: I did a screen for occasions where I can remove them, I had to keep them for the MMS cases though.

File: framework/src/executioners/FEProblemSolve.C [hunk 8]
```diff
@@ -404,7 +405,16 @@ FEProblemSolve::solve()
         if (is_nonlinear)
           _problem.solve(sys->number());
         else
-          _problem.solveLinearSystem(sys->number() - _problem.numNonlinearSystems());
+        {
+          const unsigned int linear_sys_number = sys->number() - _problem.numNonlinearSystems();
+          _problem.solveLinearSystem(linear_sys_number, &_problem.getPetscOptions());
+
+          // This is for postprocessing purposes in case none of the objects
```
Comment (GiudGiud) [inline framework/src/executioners/FEProblemSolve.C:412]: so if it s for postprcessing purpose, does it need to be performed on every multi-system iteration or could it be performed at the end of the loop ?

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Approving for once test failures are resolving

File: framework/include/executioners/SteadyBase.h [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+
+// System includes
+#include <string>
+
+// Forward declarations
+class InputParameters;
+class FEProblemBase;
+
+template <typename T>
+InputParameters validParams();
```
Comment (lindsayad) [inline framework/include/executioners/SteadyBase.h:22]: Can delete

File: framework/include/systems/SolverSystem.h [hunk 10]
```diff
@@ -39,6 +39,22 @@ class SolverSystem : public SystemBase
...
+   */
+  virtual bool converged() = 0;
+
+  /**
+   * If the system has a kernel that corresponds to a time derivative
+   */
+  virtual bool containsTimeKernel() = 0;
+
+  /**
+   * If the system has a kernel that corresponds to a time derivative
```
Comment (lindsayad) [inline framework/include/systems/SolverSystem.h:54]: This doxygen string could be a little better. The current one makes me expect a simple boolean as the return type

File: framework/src/executioners/FEProblemSolve.C [hunk 11]
```diff
@@ -404,7 +405,16 @@ FEProblemSolve::solve()
         if (is_nonlinear)
           _problem.solve(sys->number());
         else
-          _problem.solveLinearSystem(sys->number() - _problem.numNonlinearSystems());
+        {
+          const unsigned int linear_sys_number = sys->number() - _problem.numNonlinearSystems();
```
Comment (lindsayad) [inline framework/src/executioners/FEProblemSolve.C:409]:
```suggestion
          const auto linear_sys_number = cast_int<unsigned int>(sys->number() - _problem.numNonlinearSystems());
```

File: framework/src/systems/LinearSystem.C [hunk 12]
```diff
@@ -271,10 +276,18 @@ LinearSystem::solve()
 
   system().solve();
 
+  // store info about the solve
   _n_linear_iters = _linear_implicit_system.n_linear_iterations();
 
-  // store info about the solve
+  PetscLinearSolver<Real> & linear_solver =
```
Comment (lindsayad) [inline framework/src/systems/LinearSystem.C:282]:
```suggestion
  auto & linear_solver =
```

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Review by lindsayad — APPROVED** [review]

**Comment by grmnptr** [comment]
The update fr subchannel is here:
https://github.inl.gov/ncrc/subchannel/pull/346

**Comment by grmnptr** [comment]
Okay, the [timestep begin/end/multiapp] executes are hit in the FixedPointSolve. SIMPLE iteration hits Nonlinear for the problem. The nonlinear multiapp/transfer/control/UO execs are in the `computeLinearsystemTags`.
