### PR TITLE
Add CentroidMultiApp and fix brain damage in MultiApp  

### LINKED ISSUE #10483: CentroidMultiApp
## Rationale
It's really normal to want to run a sub-app at the center of every element in your master mesh for multiscale solves.  We should add this capability to MOOSE.

## Description
Will loop over elements and add the centroid of each element to `_positions`

## Impact
New capability.  Very little code.

### PR DESCRIPTION
**Pull request by friedmud**
This MultiApp creates sub-apps at the centroid of every element in the master app.  Very useful for multiscale solves.

Also fixes some small brain damage about calling virtual functions from base class constructors...

closes #10483

### CODE REVIEW

**Comment by permcody** [comment]
So invalidated the python test once but it failed again. Your new python test is timing out for real.

**Comment by friedmud** [comment]
Python test?  It's not a test... it's just there to view the results.  How do I tell it not to treat it as a test?

File: framework/src/multiapps/CentroidMultiapp.C [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+void
+CentroidMultiApp::fillPositions()
+{
+  MooseMesh & master_mesh = _fe_problem.mesh();
+
+  auto & bids = blockIDs();
+
+  // Detect if it can be on any block
+  bool any_bid = bids.find(Moose::ANY_BLOCK_ID) != bids.end();
```
Comment (permcody) [inline framework/src/multiapps/CentroidMultiapp.C]: I'm pretty sure you don't have to do this. We shouldn't need any special logic to deal with the any case. @aeslaughter, can you confirm?

File: framework/src/multiapps/CentroidMultiapp.C [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+  for (const auto & elem_ptr : master_mesh.getMesh().active_local_element_ptr_range())
+  {
+    if (any_bid || bids.find(elem_ptr->subdomain_id()) != bids.end())
+      _positions.push_back(elem_ptr->centroid());
+  }
+
+  libMesh::ParallelObject::comm().allgather(_positions);
+
+  // An attempt to try to make this parallel stable
+  std::sort(_positions.begin(), _positions.end());
```
Comment (permcody) [inline framework/src/multiapps/CentroidMultiapp.C]: possibly stable_sort? I'm not sure that would actually change anything in this case though.

**Review by permcody — COMMENTED** [review]
This looks ok with the exception of the explicit "ANY_BLOCK_ID" check. I don't think that's necessary with BlockRestrictable.

File: framework/src/multiapps/CentroidMultiapp.C (hunk 1 above)
Comment (aeslaughter) [reply framework/src/multiapps/CentroidMultiapp.C]: If I remember correct this should not be needed, when BlockRestrictable is created it replaces ANY_BLOCK_ID with all the subdomains from the mesh, so it shouldn't show up in the output of `blockIDs`. Unless it has changed.

Comment (aeslaughter) [reply framework/src/multiapps/CentroidMultiapp.C]: I just looked at BlockRestrictable and it looks like ANY_BLOCK_ID is used, but there is a function 'blockRestricted` that can be called instead of doing this manually.

Comment (aeslaughter) [reply framework/src/multiapps/CentroidMultiapp.C]: Also, you can just call [`hasBlocks`](https://github.com/idaholab/moose/blob/devel/framework/src/base/BlockRestrictable.C#L196) on line 54 and avoid all of this.

**Comment by friedmud** [comment]
This is ready to go

**Comment by friedmud** [comment]
This is ready to go...

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like when this PR was tested, Tiamat was broken by #10334 but this PR broke Tiamat tests in a different way and was overlooked. 
@lindsayad fixed the issues with Tiamat caused by #10334 and then this PR got merged and we are now seeing the failures caused by this PR. 
https://www.moosebuild.org/job/154145/

**Comment by brianmoose** [comment]
On Intel, `test:recover.recover_3` is exodiffing: https://www.moosebuild.org/job/154148/
It started when this PR was merged and happens reliably on PRs and devel tests, preventing any merges into the master branch.
Don't know if it is an integration issue or due to us installing a new moose environment package between when this was tested and when this was merged.

**Comment by friedmud** [comment]
It is possible it was this - I fix something in MultiApp. It’s possible
that test needs to be refilled if it uses MultiApps.
