### PR TITLE
Fix date/time macros, use std::abort 

### LINKED ISSUE #6930: MooseError contains a legacy workaround that hurts ccache performance
### Description of the enhancement or error report
Remove code that should have been remove with the merge of libmesh/libmesh#415

### Rationale for the enhancement or information for reproducing the error
The old code introduces `__TIME__` and `__DATE__` macros, even if they had been disabled at libmesh configure time.

### Identified impact
Should speed up compile times by improving ccache utilization.

### PR DESCRIPTION
**Pull request by dschwen**
Remove deprecated code, use `std::abort` instead of `exit`, wrap `MPI_Abort` call.

Closes #6930

### CODE REVIEW

File: framework/src/base/MooseError.C [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+#include "MooseError.h"
+
+namespace Moose {
+
+void MPIAbortWrapper()
+{
+#if defined(LIBMESH_HAVE_MPI)
+  MPI_Abort(libMesh::GLOBAL_COMM_WORLD, 1);
+#endif
```
Comment (permcody) [inline framework/src/base/MooseError.C]: If you go through the trouble making this abort wrapper why not just have it abort properly for both cases?

```
#else
  std::abort(...)
#endif
```

Comment (dschwen) [inline framework/src/base/MooseError.C]: Of course this occurred to me, too. :-/

Unfortunately clang then errors out because it thinks in a ton of functions the end of the body is reached without returning a value!

Comment (permcody) [inline framework/src/base/MooseError.C]: Why is this happening? Does the `exit(1)` logic work where `std::abort` does not?

Comment (dschwen) [inline framework/src/base/MooseError.C]: No, that is not the difference. Both exit and std::abort seem to be _magic_ (in C++11 they are tagged `noreturn` but prior to that I assume the compilers use a heuristic). They both disable the warning if they are in in the body of teh function, but not when they are wrapped in another function call.

Comment (permcody) [inline framework/src/base/MooseError.C]: Ah so the solution is to dump the wrapper and put the expanded macro in MooseError?

Comment (dschwen) [inline framework/src/base/MooseError.C]: Hm, well, I was under the impression that using ifdefs in a macro does not work. It'd be great if it did though.

Comment (permcody) [inline framework/src/base/MooseError.C]: I think you may be right, but you could ifdef the whole Macro (repeat most of the code). Is this a moot point if we move to C++11 soon?

Comment (dschwen) [inline framework/src/base/MooseError.C]: I could make the wrapper a macro that is wrapped in an ifdef. Yeah yeah, you need to go deeper.. Anyhow that would result in less code duplication and I could put the std:;abort in the proper place.

Comment (permcody) [inline framework/src/base/MooseError.C]: Perhaps we should just wait then. I haven't noticed this being slow with ccache. We are talking about going to C++11 in the next "few" weeks for various definitions of "few".

Comment (jwpeterson) [inline framework/src/base/MooseError.C]: If there's no function, you don't get the clang errors, right?  Would 

```
#if defined(LIBMESH_HAVE_MPI)
#define MOOSE_ABORT do {MPI_Abort(libMesh::GLOBAL_COMM_WORLD, 1); } while (0)
#else
#define MOOSE_ABORT do {std::abort(); } while (0)
#endif
```

work?  Then just say `MOOSE_ABORT;` where ever you need it?

Comment (dschwen) [inline framework/src/base/MooseError.C]: @jwpeterson that is exactly what I had in mind when I said "I could make the wrapper a macro that is wrapped in an ifdef". I'll make a commit to that effect.

Comment (jwpeterson) [inline framework/src/base/MooseError.C]: > that is exactly what I had in mind

Suuuuuure it is

Comment (dschwen) [inline framework/src/base/MooseError.C]: Except that the `MPI_Abort` branch needs an `std::abort` as well to appease the return error warning of the compiler...

File: framework/include/base/MooseError.h [hunk 2]
```diff
@@ -18,16 +18,21 @@
...
+#include "libmesh/libmesh_common.h"
+
+// C++ includes
+#include <cstdlib>
+
+/**
+ * Application abort macro. Uses MPI_Abort if available, std::abort otherwise
+ */
+#if defined(LIBMESH_HAVE_MPI)
+#define MOOSE_ABORT MPI_Abort(libMesh::GLOBAL_COMM_WORLD, 1); std::abort(); while (0)
```
Comment (jwpeterson) [inline framework/include/base/MooseError.h]: You have the `while (0)` part but not the do?  I wasn't aware this was valid C++...

Comment (dschwen) [inline framework/include/base/MooseError.h]: Yeah, it is valid C++ (it is a regular while loop), but it actually is a dumb idea...
