### PR TITLE
Fix VectorPostprocessor output in parallel

### LINKED ISSUE #7636: VectorPostprocessor Output Garbled On Many Processors
### Description of the enhancement or error report
VectorPostprocessor output is not properly guarded to only come out from `processor 0`... so it gets garbled if you're running MPI.  How we never saw this before I have no idea.

### Rationale for the enhancement or information for reproducing the error
It MUST be fixed.

### Identified impact
Bug will be fixed.

### PR DESCRIPTION
**Pull request by friedmud**
I lost ~10,000 processor hours to this last night.  How in the hell did we not see it before?

closes #7636

### CODE REVIEW

**Comment by permcody** [comment]
I recall fixing this bug on other outputters in the past. Yeah, I'm a little surprised it hasn't popped up before now.

File: framework/src/outputs/CSV.C [hunk 1]
```diff
@@ -101,7 +101,8 @@ CSV::output(const ExecFlagType & type)
     _all_data_table.printCSV(filename(), 1, _align);
```
Comment (permcody) [inline framework/src/outputs/CSV.C]: We really need to get in the habit of using MOOSE asserts as a team. This line here is currently only called on processor zero but the actual function being called is buried three classes down. We're just asking for this bug to pop up again.

**Comment by permcody** [comment]
👍
