### PR TITLE
Fixup and test solution serialization 

### LINKED ISSUE #4490: Aux System serialized solution not resized when mesh refined
Not sure how this has slipped through this long - but if you're using the serialized solution vector from the Aux system with mesh refinement (even uniform refinement) the serialized solution vector doesn't get resized leading to a segfault.

Working on a good test and fix for this now...

### PR DESCRIPTION
**Pull request by friedmud**
There were definitely problems here.  I can't claim that everything is fixed - but it is much better now and it's at least tested (including uniform refinement and adaptivity) and it works in parallel.

closes #4490

### CODE REVIEW

File: test/src/postprocessors/TestSerializedSolution.C [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+  if (_serialized_solution.size() != _test_sys.system().n_dofs())
+    mooseError("Serialized solution vector doesn't contain the correct number of entries!");
+
+  // Sum up all entries in the solution vector
+  for (unsigned int i=0; i<_serialized_solution.size(); i++)
+    _sum += _serialized_solution(i);
+
+  // Verify that every processor got the same value
+  // Note: the arguments to this "if" MUST be in this order!
+  if (!_communicator.verify(_sum) && processor_id() == 0)
```
Comment (permcody) [inline test/src/postprocessors/TestSerializedSolution.C]: Avoiding the short circuit... Yeah, I'd say that's important
