### PR TITLE
Compressible Navier-Stokes/Euler with finite volume

### LINKED ISSUE #16758: CNSFV
## Reason
Some TH tasks will require a finite volume implementation of the compressible Navier-Stokes equations (e.g varying density)

## Design
We already have Euler equation development in Pronghorn. We are going to migrate that work into `navier_stokes`, potentially with some design modifications to fit more naturally alongside INSFV.

## Impact
Allow modeling of CNS problems using the finite volume method

### LINKED ISSUE #17193: FVFluxBCs dont allow for 0 dofs, which happens for neighbor facetypes
## Bug Description
Hitting an assert in FVFluxBC before computing the Jacobians which wants the number of dofs to be 1. But the variable has 0 dofs on the neighbor when it's not defined there

## Steps to Reproduce
Block restricted finite volume calculation, with a flux BC such as free slip conditions

## Impact
Cant debug application without disabling or modifying the assert. The latter is in a PR coming soon

### PR DESCRIPTION
**Pull request by lindsayad**
Rebased version of #17538 

Highlights:
- Porous version of Kurganov-Tadmor (KT) scheme for discretizing convective term
- Both free-flow and porous implementation of HLLC
    - porous implementation seems to really struggle with discontinuous porosity, but as shown in testing of KT substitution of a discontinuous porosity field with a continuous approximation can really improve results, so maybe HLLC would look better there
- Slope limiters for face interpolation

Closes #17193 #16758

### CODE REVIEW

**Comment by lindsayad** [comment]
@snschune I have these three troublesome tests that fail in recover mode which are tests ported over from your initial work:
```
test:finite_volume/cns/implicit_bcs.fv_implicit_bcs ...................... [recover] FAILED (EXODIFF) [0.522s]
test:finite_volume/cns/pressure_outlet.fv_specified_pressure_out ......... [recover] FAILED (EXODIFF) [1.082s]
test:finite_volume/cns/benchmark_shock_tube_1D.hllc_sod_shocktube_1D_benchmark [...] FAILED (EXODIFF) [5.696s]
```
They are using the `ExplicitTVDRK2` time integrator but they are not setting `implicit = false` in the non-time kernels. I believe for fully correct functionality (perhaps proper order of accuracy?) you would need to do that. However, if you *did* you actually wouldn't be able to run the input file because we don't currently support getting old values from AD.

So... I would like to switch to `ExplictSSPRungeKutta` with `order = 2` which is derived from the `ExplicitTimeIntegrator` class which no longer requires setting of the `implicit` parameter and it just works with AD. I've verified that recover with the `ExplicitSSPRungeKutta` class works.

**Comment by aprilnovak** [comment]
How much of Pronghorn's classes should be adapted verbatim here? I noticed there's a few that reference `pebble_diameter` for instance, maybe that's too specific for the NS module? Now would be a good time to switch parameters like that to `characteristic_length` or something generic and non-pebble focused. 

And there's other files that I feel should stay in Pronghorn? Such as the `NavierStokesEnums` that has Pronghorn's MooseEnums for a bunch of PBR closure model settings that wouldn't make it into the NS module because they're so specifc to pebble beds (unless the plan is to move all of the content of Pronghorn into NS).

**Comment by lindsayad** [comment]
> @snschune I have these three troublesome tests that fail in recover mode which are tests ported over from your initial work:
> 
> ```
> test:finite_volume/cns/implicit_bcs.fv_implicit_bcs ...................... [recover] FAILED (EXODIFF) [0.522s]
> test:finite_volume/cns/pressure_outlet.fv_specified_pressure_out ......... [recover] FAILED (EXODIFF) [1.082s]
> test:finite_volume/cns/benchmark_shock_tube_1D.hllc_sod_shocktube_1D_benchmark [...] FAILED (EXODIFF) [5.696s]
> ```

I finally figured out *why* these fail in recover mode. It's because this time integrator only ever evaluates the Jacobian once per executable invocation. So if you run the full simulation the Jacobian is evaluated at timestep 1 and then never again. However, if you recover then the Jacobian is evaluated at whatever the first recovered time-step is. This is fine when the only "implicit" contribution is from the time derivative term because that Jacobian is indeed constant as long as the time-step is constant. However since we were not setting `implicit = false` for the non-time terms and they are nonlinear a Jacobian re-evaluation upon recover will yield a different matrix compared to one evaluated at timestep 1. So yea I think the right thing to do is to switch the inputs with `ExplicitTVDRK2` over to `ExplictSSPRungeKutta` which will automatically give us the right terms contributing to the matrix and RHS (and then for constant time step the matrix will indeed be constant)

**Comment by lindsayad** [comment]
> How much of Pronghorn's classes should be adapted verbatim here? I noticed there's a few that reference `pebble_diameter` for instance, maybe that's too specific for the NS module? Now would be a good time to switch parameters like that to `characteristic_length` or something generic and non-pebble focused.
> 
> And there's other files that I feel should stay in Pronghorn? Such as the `NavierStokesEnums` that has Pronghorn's MooseEnums for a bunch of PBR closure model settings that wouldn't make it into the NS module because they're so specifc to pebble beds (unless the plan is to move all of the content of Pronghorn into NS).

@aprilnovak you're right. As I get this cleaned up I will probably pull out all the pieces specific to pebble beds. For one thing I don't think any of the pebble specific code is even tested by my tests or the other initial FV tests crafted by @snschune. Initially we had @nemacdonald migrate over a lot more stuff that was needed to run some FE tests for comparison with CNSFV...but I already pulled out all those tests so the objects needed to run those tests can now be pulled back out too.

**Comment by lindsayad** [comment]
Alright 20/28 ... making progress!

File: modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumSpecifiedPressureBC.C [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  : CNSFVHLLCMomentumImplicitBC(parameters),
+    _pressure_function(getFunction("specified_pressure_function"))
+{
+}
+
+ADReal
+CNSFVHLLCMomentumSpecifiedPressureBC::fluxElem()
+{
+  return _normal_speed_elem * _rho_elem[_qp] * _vel_elem[_qp](_index) +
+         _normal(_index) * _pressure_function.value(_t, _face_info->faceCentroid());
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumSpecifiedPressureBC.C:36]: @snschune I don't know whether you or @nemacdonald wrote this object. I believe we should probably be using the internal value here for pressure and only use the function in `fluxBoundary` ... ?

File: framework/doc/content/source/fvbcs/FVFunctionNeumannBC.md [hunk 2]
```diff
@@ -0,0 +1,14 @@
+# FVFunctionNeumannBC
+
+!syntax description /FVBCs/FVFunctionNeumannBC
+
+## Overview
+
+This object is equivalent to [FVNeumannBC.md] with the exception that the
+constant `value` parameter is is replaced by the `function` parameter.
```
Comment (GiudGiud) [inline framework/doc/content/source/fvbcs/FVFunctionNeumannBC.md:8]:
```suggestion
constant `value` parameter is replaced by the `function` parameter.
```

File: modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+   * coeff: coefficient()
+   * coefficientBody: cbody
+   * Tinf: temperature of the body irhs
+   */
+  virtual Real coefficient() const = 0;
+
+  /// Stefan-Boltzmann constant
+  const Real _sigma_stefan_boltzmann;
+
+  /// Function describing the temperature of the body irhs
```
Comment (GiudGiud) [inline modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h:40]: irhs?

File: modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+      "thermal_conductivities",
+      "vector of thermal conductivity values used for the conduction layers");
+  params.addRequiredParam<std::vector<Real>>("conduction_thicknesses",
+                                             "vector of conduction layer thicknesses");
+
+  MooseEnum geometry("cartesian cylindrical", "cartesian");
+  params.addParam<MooseEnum>("geometry", geometry, "type of geometry");
+  params.addRangeCheckedParam<Real>("inner_radius",
+                                    "inner_radius > 0.0",
+                                    "coordiante corresponding to the first resistance layer");
```
Comment (GiudGiud) [inline modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C:37]:
```suggestion
                                    "coordinate corresponding to the first resistance layer");
```

File: modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+
+  // because the thermal conductivities are constant, we only need to compute
+  // the conduction resistance one time
+  computeConductionResistance();
+}
+
+void
+FVThermalResistanceBC::computeConductionResistance()
+{
+  ADReal r = _inner_radius;
```
Comment (GiudGiud) [inline modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C:86]:
```suggestion
  Real r = _inner_radius;
```

File: modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+
+  // other iteration requirements
+  Real iteration = 0;
+  ADReal norm = 2 * _tolerance;
+  ADReal T_surface_previous;
+
+  // iterate to find the approximate surface temperature needed for evaluating the
+  // radiation resistance. We only do this iteration if we have radiation transfer.
+  if (_emissivity > HeatConduction::DefaultValues::epsilon)
+    while (norm > _tolerance)
```
Comment (GiudGiud) [inline modules/heat_conduction/src/fvbcs/FVThermalResistanceBC.C:131]: I'd multiply tolerance by the relaxation factor to avoid reaching convergence just because of strong relaxation

File: modules/navier_stokes/doc/content/source/auxkernels/Courant.md [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+!syntax description /AuxKernels/Courant
+
+## Overview
+
+The `Courant` object computes the Courant number given coupled variables
+representing velocity components (`u`, `v`, and `w`) and using the current
+timestep size and element size. The Courant number formula is:
+
+\begin{equation}
+C = \frac{u\Delta t}{h}
```
Comment (GiudGiud) [inline modules/navier_stokes/doc/content/source/auxkernels/Courant.md:12]: I believe it's the sum u/h + v/hy + w/hz
but really it depends on the numerical scheme used.

did this one work well for cnsfv?

File: modules/navier_stokes/doc/content/source/auxkernels/MaterialMachAux.md [hunk 8]
```diff
@@ -0,0 +1,25 @@
+# MaterialMachAux
+
+!syntax description /AuxKernels/MaterialMachAux
+
+## Overview
+
+`MaterialMachAux` computes the Mach number, similar to [NSMachAux.md], but
+whereas `NSMachAux` computes the Mach number based on MOOSE variable objects,
+`MaterialMachAux` uses material properties (based on default Navier-Stokes
+naming (see
```
Comment (GiudGiud) [inline modules/navier_stokes/doc/content/source/auxkernels/MaterialMachAux.md:10]: why not just have a boolean _use_material_properties in NSMachAux

File: modules/navier_stokes/doc/content/source/fvbcs/CNSFVHLLCFluidEnergyBC.md [hunk 9]
```diff
@@ -0,0 +1,24 @@
+# CNSFVHLLCFluidEnergyBC
+
+The `CNSFVHLLCFluidEnergyBC` template class implements the fluid energy flux boundary condition for
+Harten-Lax-Van Leer-Contact (HLLC) given either specified boundary fluid energy and
+temperature functions or a
+boundary pressure function. Note that these are function corresponding to
```
Comment (GiudGiud) [inline modules/navier_stokes/doc/content/source/fvbcs/CNSFVHLLCFluidEnergyBC.md:6]:
```suggestion
boundary pressure function. Note that these are functions corresponding to
```

**Review by GiudGiud — COMMENTED** [review]
First 80 files
Super impressive so far!

File: framework/include/utils/FVUtils.h [hunk 10]
```diff
@@ -300,6 +352,60 @@ determineElemOneAndTwo(const FaceInfo & fi, const MooseVariableFV<OutputType> &
...
+ * This equation is clearly asymmetric considering the face between C and D because of the
+ * subscript on grad(phi). Hence this method can be thought of as constructing an r associated with
+ * the C side of the face
+ */
+template <typename Scalar, typename Vector>
+ADReal
+rF(const Scalar & phiC, const Scalar & phiD, const Vector & gradC, const RealVectorValue & dCD)
+{
+  if ((phiD - phiC) == 0)
+    return 1e6 * MathUtils::sign(gradC * dCD) + 0 * (gradC * dCD + phiD + phiC);
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/utils/FVUtils.h:382]: Yes I think so otherwise we will error out anytime a user sets a constant initial condition

File: framework/include/utils/FVUtils.h [hunk 11]
```diff
@@ -300,6 +352,60 @@ determineElemOneAndTwo(const FaceInfo & fi, const MooseVariableFV<OutputType> &
...
+            const Scalar & phiD,
+            const Vector & gradC,
+            const FaceInfo & fi,
+            const bool C_is_elem)
+{
+  // Using beta, w_f, g nomenclature from Greenshields
+  const auto r_f = rF(phiC, phiD, gradC, C_is_elem ? fi.dCF() : RealVectorValue(-fi.dCF()));
+  const auto beta = limiter(r_f);
+
+  const auto w_f = C_is_elem ? fi.gC() : (1. - fi.gC());
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/utils/FVUtils.h:403]: Hmm you are right. Obviously these reduce to the same thing for non-skewed meshes, but...

I like the way that we have defined `gC` and consequently `w_f` because if were to sum the `gC` taken from the element perspective, and then from the neighbor perspective, then we would get 1. But perhaps I should document our different definition of `w_f`...?

File: framework/src/executioners/Transient.C [hunk 12]
```diff
@@ -96,6 +96,12 @@ Transient::validParams()
       "steady_state_start_time",
       0.0,
       "Minimum amount of time to run before checking for steady state conditions.");
+  params.addParam<bool>(
+      "dt_in_solution_diff_norm",
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/executioners/Transient.C:100]: Yea I like that

File: framework/src/fvbcs/FVBoundaryCondition.C [hunk 13]
```diff
@@ -53,12 +65,12 @@ FVBoundaryCondition::FVBoundaryCondition(const InputParameters & parameters)
...
                                  false,
                                  "variable",
-                                 Moose::VarKindType::VAR_NONLINEAR,
+                                 Moose::VarKindType::VAR_ANY,
                                  Moose::VarFieldType::VAR_FIELD_STANDARD),
     _var(*mooseVariableFV()),
     _subproblem(*getCheckedPointerParam<SubProblem *>("_subproblem")),
     _fe_problem(*getCheckedPointerParam<FEProblemBase *>("_fe_problem_base")),
-    _sys(*getCheckedPointerParam<SystemBase *>("_sys")),
+    _sys(changeSystem(parameters, _var)),
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvbcs/FVBoundaryCondition.C:73]: My use case was: providing porosity through an auxiliary variable and wanting to be able to provide `FVDirichletBCs` in order to get the boundary values right and also to get the cell gradients at the centroids of elements on the boundary right as well.

File: framework/src/fvbcs/FVOrthogonalBoundaryDiffusion.C [hunk 14]
```diff
@@ -0,0 +1,57 @@
...
+FVOrthogonalBoundaryDiffusion::validParams()
+{
+  InputParameters params = FVFluxBC::validParams();
+  params.addClassDescription(
+      "Imposes an orthogonal diffusion boundary term with specified boundary function.");
+  params.addRequiredParam<FunctionName>("function",
+                                        "The value of the quantity of interest on the boundary.");
+  params.addRequiredParam<MaterialPropertyName>("coeff", "diffusion coefficient");
+  params.addParam<MaterialPropertyName>("diffusing_quantity",
+                                        "The quantity that is diffusing. If this is not valid, "
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvbcs/FVOrthogonalBoundaryDiffusion.C:25]: :+1:

File: framework/src/fvkernels/FVKernel.C [hunk 15]
```diff
@@ -60,8 +60,10 @@ FVKernel::FVKernel(const InputParameters & params)
     TransientInterface(this),
     BlockRestrictable(this),
     FunctionInterface(this),
+    UserObjectInterface(this),
     PostprocessorInterface(this),
     SetupInterface(this),
+    Restartable(this, "FVKernels"),
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvkernels/FVKernel.C:66]: old fluxes in the `PCNSFVKTDC` (`DC` for deferred-correction) object

File: framework/src/materials/FVPropValPerSubdomainMaterial.C [hunk 16]
```diff
@@ -0,0 +1,89 @@
...
+{
+  auto params = Material::validParams();
+  params.addClassDescription("Computes a property value on a per-subdomain basis");
+  params.addRequiredParam<MaterialPropertyName>("prop_name", "The name of the property to declare");
+  params.addRequiredParam<std::map<std::string, Real>>("subdomain_to_prop_value",
+                                                       "Map from subdomain to property value");
+  return params;
+}
+
+FVPropValPerSubdomainMaterial::FVPropValPerSubdomainMaterial(const InputParameters & params)
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/materials/FVPropValPerSubdomainMaterial.C:25]: Sigh. It is right haha. I'm realizing that the only place I've used it is in the HTR-PM input

File: framework/src/materials/FVPropValPerSubdomainMaterial.C [hunk 17]
```diff
@@ -0,0 +1,89 @@
...
+  : Material(params), _prop(declareProperty<Real>("prop_name"))
+{
+  for (const auto & map_pr : getParam<std::map<std::string, Real>>("subdomain_to_prop_value"))
+    _sub_id_to_prop.emplace(std::make_pair(_mesh.getSubdomainID(map_pr.first), map_pr.second));
+}
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/materials/FVPropValPerSubdomainMaterial.C:30]: Do you mean perform all the checks that I'm performing in `computeQpProperties`?

File: framework/src/problems/FEProblemBase.C [hunk 18]
```diff
@@ -4969,6 +4969,7 @@ FEProblemBase::init()
   }
 
   _nl->update();
+  _aux->update();
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C:4972]: Why is it not that? Haha. But to answer your question, `SystemBase::update` is where `FaceInfo::faceTypes` get setup for the different variables which I needed I think in things like auxiliary variable gradient reconstruction (mostly for assertion checking...?)

File: modules/fluid_properties/src/userobjects/HeliumFluidProperties.C [hunk 19]
```diff
@@ -30,6 +30,38 @@ HeliumFluidProperties::fluidName() const
...
+  const ADReal v = 1. / rho;
+
+  Real real_p_from_props, dp_dv, dp_de;
+  const unsigned int max_its = 10;
+  unsigned int it = 0;
+
+  do
+  {
+    p_from_v_e(v.value(), e.value(), real_p_from_props, dp_dv, dp_de);
+    ADReal p_from_props = real_p_from_props;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/HeliumFluidProperties.C:47]: `residual, Jacobian, etc.` are part of forming the Newton update `delta_e` which is used directly in computing `e` itself. So having everything be `ADReal` is necessary for getting the `derivatives` in `e` correct.

However, I'm wary of this method for another reason... this will not capture the fact that `dp_dv` and `dp_de` are themselves functions of the nonlinear degrees of freedom unless `p` is a linear function of `v` or `e`.

I may actually remove this override for that reason

File: modules/fluid_properties/src/userobjects/HeliumFluidProperties.C [hunk 20]
```diff
@@ -68,6 +100,48 @@ HeliumFluidProperties::p_from_v_e(
   dp_de = dp_dT * dT_de;
 }
 
+Real
+HeliumFluidProperties::p_from_T_v(const Real T, const Real v) const
+{
+  return T / (48.14 * v - 0.4446 / std::pow(T, 0.2)) * 1.0e5;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/HeliumFluidProperties.C:106]: Omg it seems like I added this out of thin air. I don't even have a reference for myself! Wtf

[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/HeliumFluidProperties.C:106]: Oh I see. I took this from the preexisting `p_from_v_e` method which itself doesn't have a reference.

File: modules/fluid_properties/src/userobjects/HeliumFluidProperties.C [hunk 21]
```diff
@@ -68,6 +100,48 @@ HeliumFluidProperties::p_from_v_e(
...
+}
+
+ADReal
+HeliumFluidProperties::p_from_T_v(const ADReal & T, const ADReal & v) const
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/HeliumFluidProperties.C:110]: I don't think that's necessarily true. There was a need for the non-AD versions before AD was around, and now there's a need for the AD versions. You could definitely call the AD versions and do `raw_value` but that would be unnecessarily expensive

File: modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C [hunk 22]
```diff
@@ -119,6 +137,19 @@ IdealGasFluidProperties::c_from_v_e(Real v, Real e) const
...
 }
 
+ADReal
+IdealGasFluidProperties::c_from_v_e(const ADReal & v, const ADReal & e) const
+{
+  const auto T = T_from_v_e(v, e);
+
+  const auto c2 = _gamma * _R_specific * T;
+  if (MetaPhysicL::raw_value(c2) < 0)
+    mooseException(name() + ": Sound speed squared (gamma * R * T) is negative: c2 = " +
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C:147]: Correct on all counts

File: modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md [hunk 23]
```diff
@@ -0,0 +1,93 @@
...
+
+\begin{equation}
+R_c=\sum_{i=1}^N\frac{\Delta x_i}{k_i}\ ,
+\end{equation}
+
+where $\Delta x_i$ is the thickness of each layer and $k_i$ is the thermal conductivity of
+each layer. For cylindrical annuli, the conduction thermal resistance is computed as
+
+\begin{equation}
+R_c=\sum_{i=1}^N\frac{\ln{\left(\frac{\Delta x_i+r_i}{r_i}\right)}}{k_i}\ ,
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md:46]: Sooo... I pretty much just copied the finite element version of this object from Pronghorn including its documentation. The multiplication by 2pi is not currently happening in the code. Should it be?

File: modules/heat_conduction/include/base/HeatConductionNames.h [hunk 24]
```diff
@@ -0,0 +1,28 @@
...
+#include <string>
+
+namespace HeatConduction
+{
+static const std::string emissivity = "emissivity";
+static const std::string T_ambient = "T_ambient";
+
+namespace DefaultValues
+{
+static const Real epsilon = 1e-8;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/heat_conduction/include/base/HeatConductionNames.h:21]: Haha this is another copy from Pronghorn. This is used in `FVThermalResistanceBC` but we could delete this and use 1e-8 directly in that object or make it a user-settable parameter and then delete this `static`

File: modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h (hunk 3 above)
Comment (lindsayad) [reply modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h:40]: Hahaha these abbreviations are copied over from the FE object. Whoever created them loved abbreviations. I think I figured out that `irht` means "in radiative heat transfer". I dunno about this "s" though...

Comment (lindsayad) [reply modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h:40]: It looks like the creator of these classes was... @snschune !

Comment (lindsayad) [reply modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h:40]: Perhaps he can shed some light on `irhs`. Infinite radiative heat surface? That wouldn't go well with the preceding "body" though...

File: modules/navier_stokes/doc/content/source/auxkernels/Courant.md (hunk 7 above)
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/auxkernels/Courant.md:12]: In general for explicit time integration I found that the time step size had to be significantly less than the Courant number, or even 0.5 times the Courant number in order to avoid oscillations. Significantly meaning at least an order of magnitude less

File: modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md (hunk 23 above)
[the remark this answers is not in the document]
Comment (aprilnovak) [reply modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md:46]: It's been a while since I wrote this, but I can say two things:

1. This class has been tested by comparing the temperature with a model that actually explicitly models the conduction heat transfer through 1-D layers. The tests show the correct behavior with the resistance BC.
2. The 2\pi shows up on traditional textbook definitions of thermal resistance, but IIRC, the reason it doesn't appear in the class or in this documentation is because it eventually would cancel with a 2\pi factor in the area somewhere else when computing the total heat flux.

So I suppose technically there should be a 2\pi in the documentation for the thermal resistance, but it's just not in the class implementation because it cancels anyways.

[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md:46]: Thanks for the clarification @aprilnovak. Given that, I will add it to the doc!

**Comment by GiudGiud** [comment]
Trying out this reply by email thing since I cant find the reply in thread
button.

Yeah I am not saying the class is wrong, which is why I did not add any
comments on the equations in the kernel.

If we are saying R as in the integral resistance of the system, we need 2
pi. If it's R of the local element contribution, then no 2 pi. Think of
each element as a separate conductor, then for 2 pi of them the inverse of
the resistances are supposed to be summed.
Agree with April on the conclusion.

Guillaume


Le lun. 7 juin 2021 à 15:17, April Novak ***@***.***> a
écrit :

File: framework/doc/content/source/materials/FVPropValPerSubdomainMaterial.md [hunk 25]
```diff
@@ -0,0 +1,17 @@
+# FVPropValPerSubdomainMaterial
+
+!syntax description /Materials/FVPropValPerSubdomainMaterial
+
+## Overview
+
+This object is useful for providing a material property value, for finite volume
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/doc/content/source/materials/FVPropValPerSubdomainMaterial.md:7]: I suppose that this is nice for FE too from a convenience standpoint; instead of having to specify multiple `GenericConstatMaterials` you can just create one object. But it's essential from a functional standpoint for finite volume calculations in order to circumvent the material property ghosting issue for one property name

File: modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md (hunk 23 above)
[the remark this answers is not in the document]
Comment (aprilnovak) [reply modules/heat_conduction/doc/content/source/fvbcs/FVThermalResistanceBC.md:46]: Thanks for the careful read @GiudGiud!

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCFluidEnergyStagnationInletBC.h [hunk 26]
```diff
@@ -0,0 +1,34 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCStagnationInletBC.h"
+
+/**
+ * HLLC stagnation inlet boundary conditions
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCFluidEnergyStagnationInletBC.h:15]:
```suggestion
 * HLLC stagnation inlet boundary conditions for the conservation of energy equation
```

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumBC.h [hunk 27]
```diff
@@ -0,0 +1,48 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h"
+#include "CNSFVHLLCSpecifiedPressureBC.h"
+
+template <typename T>
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumImplicitBC.h [hunk 28]
```diff
@@ -0,0 +1,31 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCImplicitBC.h"
+
+/**
+ * HLLC implicit boundary conditions
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumImplicitBC.h:15]:
```suggestion
 * HLLC implicit boundary conditions for the momentum conservation equation
```

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumStagnationInletBC.h [hunk 29]
```diff
@@ -0,0 +1,34 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCStagnationInletBC.h"
+
+/**
+ * HLLC stagnation inlet boundary conditions
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCMomentumStagnationInletBC.h:15]:
```suggestion
 * HLLC stagnation inlet boundary conditions for the momentum conservation equation
```

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCSpecifiedPressureBC.h [hunk 30]
```diff
@@ -0,0 +1,26 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCBC.h"
+
+class Function;
+
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCSpecifiedPressureBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/CNSFVHLLCStagnationInletBC.h [hunk 31]
```diff
@@ -0,0 +1,44 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "CNSFVHLLCBC.h"
+
+/**
+ * HLLC stagnation boundary conditions
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/CNSFVHLLCStagnationInletBC.h:15]:
```suggestion
 * Base class for the HLLC stagnation inlet boundary conditions
```

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCMassBC.h [hunk 32]
```diff
@@ -0,0 +1,45 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "PCNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h"
+#include "PCNSFVHLLCSpecifiedPressureBC.h"
+
+template <typename T>
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCMassBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCMomentumBC.h [hunk 33]
```diff
@@ -0,0 +1,48 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "PCNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h"
+#include "PCNSFVHLLCSpecifiedPressureBC.h"
+
+template <typename T>
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCMomentumBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h [hunk 34]
```diff
@@ -0,0 +1,29 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "PCNSFVHLLCBC.h"
+
+class Function;
+
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCSpecifiedPressureBC.h [hunk 35]
```diff
@@ -0,0 +1,26 @@
...
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "PCNSFVHLLCBC.h"
+
+class Function;
+
+class PCNSFVHLLCSpecifiedPressureBC : public PCNSFVHLLCBC
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCSpecifiedPressureBC.h:16]: docstring

File: modules/navier_stokes/include/fvbcs/PCNSFVImplicitMomentumPressureBC.h [hunk 36]
```diff
@@ -0,0 +1,26 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "FVFluxBC.h"
+
+class PCNSFVImplicitMomentumPressureBC : public FVFluxBC
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVImplicitMomentumPressureBC.h:14]: dcostring

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCFluidEnergyBC.h [hunk 37]
```diff
@@ -0,0 +1,46 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "PCNSFVHLLCSpecifiedMassFluxAndTemperatureBC.h"
+#include "PCNSFVHLLCSpecifiedPressureBC.h"
+
+template <typename T>
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCFluidEnergyBC.h:15]: docstring

File: modules/navier_stokes/include/fvbcs/PCNSFVHLLCBC.h [hunk 38]
```diff
@@ -0,0 +1,84 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "FVFluxBC.h"
+
+class SinglePhaseFluidProperties;
+
+/**
+ * Base clase for HLLC boundary condition for Euler equation
```
Comment (GiudGiud) [inline modules/navier_stokes/include/fvbcs/PCNSFVHLLCBC.h:17]:
```suggestion
 * Base clase for HLLC boundary conditions for the Euler equation
```

**Review by GiudGiud — COMMENTED** [review]
Mostly reviewed a good chunk of the headers, so not too many comments beyond 'docstring'

File: framework/doc/content/syntax/Limiters/index.md [hunk 39]
```diff
@@ -0,0 +1,34 @@
...
+TV(u^n) = TV(u(\centerdot,t^n)) = \sum_j \vert u_{j+1}^n - u_j^n \vert
+\end{equation}
+
+where $u$ is the discretized approximate solution, $n$ denotes the time index,
+and $u_j^n = u(x_j,t^n)$. A numerical method is TVD if
+
+\begin{equation}
+TV(u^{n+1}) \leq TV(u^n)
+\end{equation}
+
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/doc/content/syntax/Limiters/index.md:22]: What? I don't see a `gC` anywhere around here?

[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/doc/content/syntax/Limiters/index.md:22]: I was suggesting we document here the different gC we are using

File: modules/heat_conduction/include/base/HeatConductionNames.h (hunk 24 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/heat_conduction/include/base/HeatConductionNames.h:21]: This is used in this context as like a "minimum emissivity in order to care" kind of thing.
```c++
  // iterate to find the approximate surface temperature needed for evaluating the
  // radiation resistance. We only do this iteration if we have radiation transfer.
  if (_emissivity > HeatConduction::DefaultValues::epsilon)
    while (norm > (_tolerance * _alpha))
    {
      T_surface_previous = _T_surface;

      // compute the flux based on the conduction part of the circuit
      flux = (_u[_qp] - _T_surface) / _conduction_resistance;

      computeParallelResistance();

      // use the flux computed from the conduction half to update T_surface
      _T_surface = flux * _parallel_resistance + _T_ambient;
      _T_surface = _alpha * _T_surface + (1 - _alpha) * T_surface_previous;
      norm = std::abs(_T_surface - T_surface_previous) / std::abs(T_surface_previous);

      if (iteration == _max_iterations)
      {
        mooseWarning("Maximum number of iterations reached in 'FVThermalResistanceBC'!");
        break;
      }
      else
        iteration += 1;
    }
```
I think in that context, I'm just going to hard-code 1e-8 in the place of `HeatConduction::DefaultValues::epsilon`. I think it might be confusing to a user to have to supply a iteration tolerance and a minimum emissivity tolerance. If you disagree, I'm open to changing

File: modules/navier_stokes/doc/content/source/fvkernels/CNSFVHLLCBase.md [hunk 40]
```diff
@@ -0,0 +1,104 @@
...
+$v$, and $w$ represent the $x$, $y$, and $z$ components of the velocity $\bm{a}$
+respectively. $p$ is the static pressure and $e_t = e +
+\lparen\bm{v}\cdot\bm{v}\rparen/2$ where $e$ is the specific internal
+energy. $\rho$ is the density. $S_L$, $S_*$, and $S_R$ are the left, middle, and
+right wave speeds respectively. $S_*$ is given by [!citep](toro2009riemann):
+
+\begin{equation}
+S_* = \frac{p_R - p_L + \rho_L a_{n,L}\left(S_L - a_{n,L}\right) - \rho_R a_{n,R}
+\left(S_R - a_{n,R}\right)}{\rho_L \left(S_L - a_{n,L}\right) -
+\rho_R\left(S_R - a_{n,R}\right)}
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/fvkernels/CNSFVHLLCBase.md:45]: Screenshot from 2021-06-08 13-36-08

Double-checked with Toro and I think this looks good as-is.

File: modules/navier_stokes/doc/content/source/fvkernels/NSFVSolidFluidConvection.md [hunk 41]
```diff
@@ -0,0 +1,23 @@
+# NSFVSolidFluidConvection
+
+!syntax description /FVKernels/NSFVSolidFluidConvection
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/fvkernels/NSFVSolidFluidConvection.md:3]: I don't see that `boolean` parameter, but shouldn't need it anyway. If there's anything to be done, it's to allow `T_ambient` to be supplied via material property

File: modules/navier_stokes/doc/content/source/materials/PorousConservedVarMaterial.md [hunk 42]
```diff
@@ -0,0 +1,30 @@
...
+\begin{bmatrix}
+\rho\\
+\epsilon \rho u\\
+\epsilon \rho v\\
+\epsilon \rho w\\
+\rho e_t
+\end{bmatrix}
+\end{equation}
+
+where $\epsilon$ is the porosity, $\rho$ is the density, $u$, $v$, and $w$ are the component velocities, and
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/materials/PorousConservedVarMaterial.md:20]: Not superficial. The `bmatrix` above shows multiplication of each component velocity by `\epsilon`

File: modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md [hunk 43]
```diff
@@ -0,0 +1,18 @@
+# MfrPostprocessor
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md:1]: In theory this object could be used to aggregate just about any quantity computed in a `FVFluxBC` object. Maybe rename to `FVBoundaryQuantityPostprocessor` and rename the `setMfr` method to `setBoundaryQuantity`?

File: modules/navier_stokes/include/base/GeometryFunctions.h [hunk 44]
```diff
@@ -0,0 +1,63 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+/**
+ * Compute the radial coordinate
+ * @param p      point
+ * @param center center coordinate of the bed
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/base/GeometryFunctions.h:15]: Actually realized this code was only used by Pronghorn CFEM tests which I removed a few commits ago, so I deleted this file

File: modules/navier_stokes/include/base/InputErrorChecking.h [hunk 45]
```diff
@@ -0,0 +1,34 @@
...
+/**
+ * Checks whether the user has specified an input parameter that will go un-used, printing
+ * an error message to help in the debugging process.
+ * @param p input parameters object
+ * @param name name of the input parameter
+ * @param explanation short explanation of the reason why parameter is unused
+ */
+void checkUnusedInputParameter(const InputParameters & p,
+                               const std::string & name,
+                               const std::string & explanation);
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/base/InputErrorChecking.h:21]: Yes I will also remove this file (and its `.C` complement)

File: framework/doc/content/syntax/Limiters/index.md (hunk 39 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/doc/content/syntax/Limiters/index.md:22]: Ok cool, yes I've done just that

File: modules/navier_stokes/include/materials/SoundspeedMat.h [hunk 46]
```diff
@@ -0,0 +1,40 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "Material.h"
+
+class SinglePhaseFluidProperties;
+
+/**
+ * Computes the speed of sound from other Navier-Stokes materials
```
Comment (GiudGiud) [inline modules/navier_stokes/include/materials/SoundspeedMat.h:17]:
```suggestion
 * Computes the speed of sound from other Navier-Stokes material properties
```

File: modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h [hunk 47]
```diff
@@ -0,0 +1,51 @@
...
+
+#pragma once
+
+// MOOSE includes
+#include "ElementPostprocessor.h"
+
+/**
+ * Computes a time step size based on user-specified CFL number
+ */
+class ADCFLTimeStepSize : public ElementPostprocessor
```
Comment (GiudGiud) [inline modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h:18]: Why AD?

**Review by GiudGiud — COMMENTED** [review]
That's it for the headers.

I'm thinking we need to list somewhere the small specificities of each solver type. 
Like INSFV likes a constant rho, CNSFV wants a variable sometimes, and sometimes a matprop
PNSFV wants an aux variable porosity

Maybe kernel docs is already enough though

File: modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h (hunk 47 above)
Comment (lindsayad) [reply modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h:18]: I will rename to remove the AD

File: modules/navier_stokes/doc/content/source/fvkernels/PNSFVPGradEpsilon.md [hunk 48]
```diff
@@ -0,0 +1,21 @@
...
+This object adds a residual equivalent to
+
+\begin{equation}
+\int_{\Omega_C} -p \nabla \epsilon dV
+\end{equation}
+
+This object must be included in any simulations where the $\epsilon \nabla p$
+term has been integrated by parts as is done by the [PCNSFVKT.md] and
+[PCNSFVHLLC.md] objects.
+
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/fvkernels/PNSFVPGradEpsilon.md:16]: Does this work if the `SolutionUserObject` information is discontinuous? E.g. what happens if we request an evaluation on a face between two elements?

File: modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h (hunk 47 above)
Comment (lindsayad) [reply modules/navier_stokes/include/postprocessors/ADCFLTimeStepSize.h]: Oh I see there is a `CFLTimeStepSize` object already in THM

**Comment by lindsayad** [comment]
@GiudGiud I'm sure you're doing other things. Just wanted to let you know that this is ready for further review whenever

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C [hunk 49]
```diff
@@ -0,0 +1,119 @@
...
+const std::array<ADReal, 3> &
+CNSFVHLLCBase::waveSpeed(const THREAD_ID tid,
+                         const FaceInfo & fi,
+                         const HLLCData & hllc_data,
+                         const ADRealVectorValue & normal)
+{
+  mooseAssert(tid < libMesh::n_threads(), tid << " must be less than " << libMesh::n_threads());
+
+  auto it = _fi_to_wave_speeds[tid].find(&fi);
+  if (it != _fi_to_wave_speeds[tid].end())
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:72]: did you check that it is faster to cache ^^

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C [hunk 50]
```diff
@@ -0,0 +1,119 @@
...
+  const ADReal u2 = hllc_data.vel_neighbor.norm();
+  const ADReal q2 = normal * hllc_data.vel_neighbor;
+  const ADReal v2 = 1.0 / rho2;
+  const ADReal & e2 = hllc_data.e_neighbor;
+  const ADReal E2 = e2 + 0.5 * u2 * u2;
+  const ADReal p2 = hllc_data.fluid.p_from_v_e(v2, e2);
+  const ADReal H2 = E2 + p2 / rho2;
+  const ADReal c2 = hllc_data.fluid.c_from_v_e(v2, e2);
+
+  // compute Roe-averaged variables
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: well I m up for reading chapter 11 I guess

**Review by GiudGiud — COMMENTED** [review]
More reviewing, mostly HLLC
Should be almost done with HLLC, just have to read a little bit more on Roe Riemann solvers for the wave speeds.

I'd like to see a table summarizing our NS capabilities in the NS index of the documentation.

Something that points a user to which prefix they should be using based on:
compressible/not , viscous/not , turbulent/not , other relevant criteria (shock resolving? can do displaced mesh? )
Also says which variable set can be used

File: modules/navier_stokes/include/postprocessors/NSCFLTimeStepSize.h [hunk 51]
```diff
@@ -0,0 +1,55 @@
+//* This file is part of the MOOSE framework
+//* https://www.mooseframework.org
+//*
+//* All rights reserved, see COPYRIGHT for full restrictions
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/include/postprocessors/NSCFLTimeStepSize.h:8]: or object name?

File: modules/navier_stokes/src/fvkernels/PCNSFVMomentumPressureRZ.C [hunk 52]
```diff
@@ -0,0 +1,42 @@
...
+  InputParameters params = FVElementalKernel::validParams();
+  params.addClassDescription(
+      "Adds the porous $-p/r$ term into the radial component of the Navier-Stokes "
+      "momentum equation for the problems in the RZ coordinate system.");
+  return params;
+}
+
+PCNSFVMomentumPressureRZ::PCNSFVMomentumPressureRZ(const InputParameters & params)
+  : FVElementalKernel(params),
+    _p(getADMaterialProperty<Real>(NS::pressure)),
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVMomentumPressureRZ.C:28]: This is a material property though and in all the `VarMaterials` the property is declared as `NS::pressure`. In this PR I also added `prop_getter_suffix` as a parameter to `MaterialPropertyInterface` and `declare_suffix` to `MaterialBase` to allow more flexibility in property naming when there are hard-coded property names. 

When a material declares properties, do we want to add `MaterialPropertyName` parameters for every declared property (with defaults perhaps)? This could become overload. At least when using PCNSFV a user will always want to be using one of the `VarMaterials` and I think declaring and retrieving properties based on the NS namespace is a decent design.

I suppose that this would be more of an issue if we rename this to `PNSFVMomentumRZ` implying this can be used in incompressible cases where we will not be using the `VarMaterials`.

File: modules/navier_stokes/include/postprocessors/NSCFLTimeStepSize.h (hunk 51 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/postprocessors/NSCFLTimeStepSize.h:8]: I cannot do either right now because of compatibility with THM. After this is merged, we can delete the file/object in THM and then we will rename this file.

File: modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumStagnationInletBC.C [hunk 53]
```diff
@@ -0,0 +1,74 @@
...
+CNSFVHLLCMomentumStagnationInletBC::fluxBoundary()
+{
+  return _normal_speed_boundary * _rho_boundary * _vel_boundary(_index) +
+         _normal(_index) * _p_boundary;
+}
+
+ADReal
+CNSFVHLLCMomentumStagnationInletBC::hllcElem()
+{
+  Real f = std::sqrt(1 - MetaPhysicL::raw_value(_normal(_index)) *
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumStagnationInletBC.C:51]: Nice catch. This pre-dated me... I have no idea what the thought was there.

File: modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumSpecifiedPressureBC.C (hunk 1 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvbcs/CNSFVHLLCMomentumSpecifiedPressureBC.C:36]: I am just going to change this to `_pressure_elem[_qp]`

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C [hunk 54]
```diff
@@ -0,0 +1,119 @@
...
+    _vel_elem(getADMaterialProperty<RealVectorValue>(nms::velocity)),
+    _vel_neighbor(getNeighborADMaterialProperty<RealVectorValue>(nms::velocity)),
+    _speed_elem(getADMaterialProperty<Real>(nms::speed)),
+    _speed_neighbor(getNeighborADMaterialProperty<Real>(nms::speed)),
+    _rho_elem(getADMaterialProperty<Real>(nms::density)),
+    _rho_neighbor(getNeighborADMaterialProperty<Real>(nms::density)),
+    _pressure_elem(getADMaterialProperty<Real>(nms::pressure)),
+    _pressure_neighbor(getNeighborADMaterialProperty<Real>(nms::pressure))
+{
+  if (_tid == 0)
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:47]: `_fi_to_wave_speeds` is a static data member so every thread will share the same `_fi_to_wave_speeds` data structure. this is similar to RC coeffs (currently). Before I took up the compressible work the `waveSpeed` method was already static, but there was no caching so mass, all momentum components, and energy would trigger redundant wave speed computations on a per FaceInfo basis. I added this static data member to prevent that

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 49 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:72]: No 😆

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: I also believe I documented all of this in `CNSFVHLLCBase.md` ...

**Comment by lindsayad** [comment]
> I'd like to see a table summarizing our NS capabilities in the NS index of the documentation.

What do you think of a table like this?

class | works for compressible | incompressible | porous compressible | porous incompressible
--- | --- | --- | --- | ---
PNSFVMomentumFriction (links to its doc page) | no | no | yes | yes

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: (hopefully). A second pair of eyes is probably good

**Comment by GiudGiud** [comment]
Ah that would be another good way of doing it too!
I was thinking of having:
INSFE
CNSFE
HLLC CNSFV
INSFV
KT CNSFV
as major categories.
It s trivial to say that INS is for incompressible. But the breakdown for turbulence, friction and sources etc is not clear from just the capital letter names.

**Comment by lindsayad** [comment]
> But the breakdown for turbulence, friction and sources etc is not clear from just the capital letter names.

Isn't that what the rest of the name is for? And the doc pages? We shouldn't have to reproduce a description of every single class on the index page

**Comment by GiudGiud** [comment]
I was not thinking of breaking down by class. Just the 5 major categories:
INSFE, CNSFE, INSFV, HLLC, KT and what they can do.

**Comment by lindsayad** [comment]
That table is confusing to me. It makes me think that if I add an INSFV object somehow I instantly have mixing length turbulence modeling as well as friction and sources. Maybe changing "turbulence?" to "turbulence support" would make that column more clear. As to friction/sources ... maybe also changing to "friction/source support" would make that clearer, although you can slap a `FVBodyForce` object on any of the different free-flow/porous compressible/incompressible flow types and have sources

**Comment by lindsayad** [comment]
I think your categories and something similar to the table you presented is pretty close. I'll take a first stab and we can iterate if we need to

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: Ok chapter 11 wasnt the relevant one. It s in chapter 10. 
So there's tons of options here for determining SL and SR.

I dont see this one in the list (in my edition). It s essentially a mix between Davis' "exceedingly simple" ones and the recommended by Davis and Einfeldt Roe average. 

Toro seems to recommend a pressured based wave speed estimate. But his equations are written for ideal gases, and you have to choose between two different approximations, more choices..

So I m happy with this, and if we notice issues with wave speeds, we ll have to re-visit

File: modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C [hunk 55]
```diff
@@ -0,0 +1,139 @@
...
+
+  // compute wave speeds
+  // I may want to change the estimate of these wave speeds!
+  const auto SL = std::min(q1 - c1, q_roe - c_roe);
+  const auto SR = std::max(q2 + c2, q_roe + c_roe);
+  const auto SM =
+      (eps2 * rho2 * q2 * (SR - q2) - eps1 * rho1 * q1 * (SL - q1) + eps1 * p1 - eps2 * p2) /
+      (eps2 * rho2 * (SR - q2) - eps1 * rho1 * (SL - q1));
+
+  // store these results in _wave_speed
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:98]: you're not caching them for PCNSFV?

File: modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C [hunk 56]
```diff
@@ -0,0 +1,139 @@
...
+#include "NS.h"
+#include "SinglePhaseFluidProperties.h"
+
+using MetaPhysicL::raw_value;
+
+InputParameters
+PCNSFVHLLC::validParams()
+{
+  InputParameters params = FVFluxKernel::validParams();
+  params.addRequiredParam<UserObjectName>(NS::fluid, "Fluid userobject");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:20]:
```suggestion
  params.addRequiredParam<UserObjectName>(NS::fluid, "Fluid properties userobject");
```

File: modules/navier_stokes/src/materials/GeneralFluidProps.C [hunk 57]
```diff
@@ -0,0 +1,149 @@
...
+#include "NavierStokesMethods.h"
+#include "SinglePhaseFluidProperties.h"
+
+registerMooseObject("NavierStokesApp", GeneralFluidProps);
+
+InputParameters
+GeneralFluidProps::validParams()
+{
+  auto params = Material::validParams();
+  params.addRequiredParam<UserObjectName>(NS::fluid, "Fluid userobject");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/materials/GeneralFluidProps.C:22]:
```suggestion
  params.addRequiredParam<UserObjectName>(NS::fluid, "Fluid properties userobject");
```

File: modules/navier_stokes/src/materials/GeneralFluidProps.C [hunk 58]
```diff
@@ -0,0 +1,149 @@
...
+  params.addClassDescription("Computes fluid properties using (P, T) formulation");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/materials/GeneralFluidProps.C:23]:
```suggestion
  params.addClassDescription("Computes fluid properties using a (P, T) formulation");
```

File: modules/navier_stokes/src/userobjects/HLLCUserObject.C [hunk 59]
```diff
@@ -0,0 +1,147 @@
...
+namespace nms = NS;
+using MetaPhysicL::raw_value;
+
+registerMooseObject("NavierStokesApp", HLLCUserObject);
+
+InputParameters
+HLLCUserObject::validParams()
+{
+  InputParameters params = InternalSideUserObject::validParams();
+  params.addRequiredParam<UserObjectName>(nms::fluid, "Fluid userobject");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/userobjects/HLLCUserObject.C:23]:
```suggestion
  params.addRequiredParam<UserObjectName>(nms::fluid, "Fluid properties userobject");
```

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C [hunk 60]
```diff
@@ -0,0 +1,108 @@
...
+
+// MOOSE includes
+#include "libmesh/quadrature.h"
+#include "metaphysicl/raw_type.h"
+
+#include <algorithm>
+#include <limits>
+
+registerMooseObject("NavierStokesApp", CFLTimeStepSize);
+registerMooseObject("NavierStokesApp", ADCFLTimeStepSize);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:21]: why do we need an AD version of this?

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C [hunk 61]
```diff
@@ -0,0 +1,108 @@
...
+                                                             "Velocity material property name(s)");
+  params.addRequiredParam<std::vector<MaterialPropertyName>>(
+      "c_names", "Sound speed material property name(s)");
+
+  // Because this post-processor is meant to be used with PostprocessorDT, it
+  // should be executed on initial (not included by default) and timestep end.
+  params.set<ExecFlagEnum>("execute_on") = {EXEC_INITIAL, EXEC_TIMESTEP_END};
+  params.suppressParameter<ExecFlagEnum>("execute_on");
+
+  params.addClassDescription("Computes a time step size based on user-specified CFL number");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:40]:
```suggestion
  params.addClassDescription("Computes a time step size based on an user-specified CFL number");
```

File: modules/navier_stokes/src/userobjects/HLLCUserObject.C [hunk 62]
```diff
@@ -0,0 +1,147 @@
...
+  params.addClassDescription(
+      "Computes free-flow wave speeds on internal sides, useful in HLLC contexts");
+  return params;
+}
+
+HLLCUserObject::HLLCUserObject(const InputParameters & parameters)
```
Comment (GiudGiud) [inline modules/navier_stokes/src/userobjects/HLLCUserObject.C:29]: this wont have the right wave speeds for PCNSFV. Maybe just add porosity as an optional param so we can keep a single object?

Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/HLLCUserObject.C:29]: or text in the docs excluding CNSFV, your call

**Review by GiudGiud — COMMENTED** [review]
quick one

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: > I dont see this one in the list (in my edition). It s essentially a mix between Davis' "exceedingly simple" ones and the recommended by Davis and Einfeldt Roe average.

Yea...I noted the same thing when I took up this code. @snschune presumably wrote this so maybe he got it from another reference? It is slightly unsatisfactory to have a wave speed implementation without a corresponding reference.

File: modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C (hunk 55 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:98]: No. I suppose I should make them consistent, huh. Ugh I suppose I'll profile and see if it matters

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C (hunk 60 above)
Comment (lindsayad) [reply modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:21]: Because this retrieves material properties and has to retrieve either non-AD or AD properties

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C (hunk 61 above)
Comment (lindsayad) [reply modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:40]:
```suggestion
  params.addClassDescription("Computes a time step size based on a user-specified CFL number");
```

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: so you were saying you had to go with a smaller time step that you expected right. Maybe this is the problem? Like the "exceedingly simple" option is being more limiting for the faster wave speed

Because the averaging done by Roe is always 'in the middle' since it s an average, like q_roe is smaller than q_2 and c_roe is probably the same as c_2 roughly.

If you have time, could you please try to confirm my intuition that we just want to use Roe and not this. 
This is also just a wild intuition so you dont have to spend the time.

@snschune if you provide a reference on this, we dont need to do this

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C (hunk 60 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:21]: ugh this is true but also ugh. Is there a getNonADMaterialPropertyWhetherItsADorNot() routine?

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/rotated-2d-bkt-function-porosity.i [hunk 63]
```diff
@@ -0,0 +1,369 @@
...
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/rotated-2d-bkt-function-porosity.i:36]:
```suggestion
```
I dont get what s wrong with coverage check here I guess. 
each variable has a kernel right?

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i [hunk 64]
```diff
@@ -0,0 +1,303 @@
...
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i:86]:
```suggestion
```

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C [hunk 65]
```diff
@@ -0,0 +1,269 @@
...
+  const auto sup_vel_elem_normal = sup_vel_elem * _face_info->normal();
+  const auto sup_vel_neighbor_normal = sup_vel_neighbor * _face_info->normal();
+  const auto u_elem_normal = u_elem * _face_info->normal();
+  const auto u_neighbor_normal = u_neighbor * _face_info->normal();
+
+  const auto pr = computeAlphaAndOmega(u_elem_normal, u_neighbor_normal, c_elem, c_neighbor);
+  const auto & alpha = pr.first;
+  const auto & omega = pr.second;
+
+  if (_eqn == "mass")
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVKT.C:222]: so you're doing this selection on equation because everything before then is re-used. I think I like this better than having 3 different strong BC objects for each equation. I ll allow it lol. 

If you could specify a list of equations and a list of variables, would be even cooler. I think the latter is not possible right

Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:222]: especially with the momentum checks

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/dc.i [hunk 66]
```diff
@@ -0,0 +1,379 @@
...
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/dc.i:38]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 67]
```diff
@@ -0,0 +1,315 @@
+stagnation_pressure = 1
+stagnation_temperature = 1
+
+[GlobalParams]
+  fp = fp
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:10]:
```suggestion

```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 68]
```diff
@@ -0,0 +1,315 @@
...
+    type = FileMeshGenerator
+    file = supersonic_nozzle.e
+  []
+[]
+
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+      allow_imperfect_jacobians = true
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:27]: is that a thing for AD?

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 69]
```diff
@@ -0,0 +1,315 @@
...
+  # Mass conservation
+  [mass_time]
+    type = FVTimeKernel
+    variable = rho
+  []
+
+  [mass_advection]
+    type = CNSFVMassHLLC
+    variable = rho
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:73]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 70]
```diff
@@ -0,0 +1,315 @@
...
+  [momentum_x_time]
+    type = FVTimeKernel
+    variable = rho_u
+  []
+
+  [momentum_x_advection]
+    type = CNSFVMomentumHLLC
+    variable = rho_u
+    momentum_component = x
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:86]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 71]
```diff
@@ -0,0 +1,315 @@
...
+  # Fluid energy conservation
+  [fluid_energy_time]
+    type = FVTimeKernel
+    variable = rho_E
+  []
+
+  [fluid_energy_advection]
+    type = CNSFVFluidEnergyHLLC
+    variable = rho_E
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:110]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 72]
```diff
@@ -0,0 +1,315 @@
...
+  []
+[]
+
+[FVBCs]
+  ## inflow stagnation boundaries
+  [mass_stagnation_inflow]
+    type = CNSFVHLLCMassStagnationInletBC
+    variable = rho
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:119]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 73]
```diff
@@ -0,0 +1,315 @@
...
+    stagnation_pressure = ${stagnation_pressure}
+    stagnation_temperature = ${stagnation_temperature}
+    boundary = left
+  []
+
+  [momentum_x_stagnation_inflow]
+    type = CNSFVHLLCMomentumStagnationInletBC
+    variable = rho_u
+    momentum_component = x
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:129]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 74]
```diff
@@ -0,0 +1,315 @@
...
+    stagnation_pressure = ${stagnation_pressure}
+    stagnation_temperature = ${stagnation_temperature}
+    boundary = left
+  []
+
+  [momentum_y_stagnation_inflow]
+    type = CNSFVHLLCMomentumStagnationInletBC
+    variable = rho_v
+    momentum_component = y
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:139]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 75]
```diff
@@ -0,0 +1,315 @@
...
+    stagnation_pressure = ${stagnation_pressure}
+    stagnation_temperature = ${stagnation_temperature}
+    boundary = left
+  [../]
+
+  [fluid_energy_stagnation_inflow]
+    type = CNSFVHLLCFluidEnergyStagnationInletBC
+    variable = rho_E
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:148]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 76]
```diff
@@ -0,0 +1,315 @@
...
+    stagnation_pressure = ${stagnation_pressure}
+    stagnation_temperature = ${stagnation_temperature}
+    boundary = left
+  []
+
+  ## outflow implicit conditions
+  [mass_outflow]
+    type = CNSFVHLLCMassImplicitBC
+    variable = rho
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:158]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 77]
```diff
@@ -0,0 +1,315 @@
...
+    boundary = right
+  []
+
+  [momentum_x_outflow]
+    type = CNSFVHLLCMomentumImplicitBC
+    variable = rho_u
+    momentum_component = x
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:166]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 78]
```diff
@@ -0,0 +1,315 @@
...
+    boundary = right
+  []
+
+  [momentum_y_outflow]
+    type = CNSFVHLLCMomentumImplicitBC
+    variable = rho_v
+    momentum_component = y
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:174]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 79]
```diff
@@ -0,0 +1,315 @@
...
+    boundary = right
+  []
+
+  [fluid_energy_outflow]
+    type = CNSFVHLLCFluidEnergyImplicitBC
+    variable = rho_E
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:181]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/dc.i [hunk 80]
```diff
@@ -0,0 +1,379 @@
...
+[]
+
+[Materials]
+  [var_mat]
+    type = PorousMixedVarMaterial
+    p = pressure
+    T_fluid = T_fluid
+    superficial_rhou = sup_mom_x
+    superficial_rhov = sup_mom_y
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/dc.i:311]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i [hunk 81]
```diff
@@ -0,0 +1,303 @@
...
+  []
+[]
+
+[Materials]
+  [var_mat]
+    type = PorousPrimitiveVarMaterial
+    p = pressure
+    T_fluid = T_fluid
+    superficial_vel_x = sup_vel_x
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i:277]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 82]
```diff
@@ -0,0 +1,315 @@
...
+    sort_by = x
+  []
+[]
+
+[Outputs]
+  exodus = true
+  #[csv]
+  #  type = CSV
+  #  execute_on = 'FINAL'
+  #[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:314]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i [hunk 83]
```diff
@@ -0,0 +1,315 @@
...
+
+  [TimeStepper]
+    type = PostprocessorDT
+    postprocessor = cfl_dt
+  []
+[]
+
+[VectorPostprocessors]
+  [Ma_layered]
+    type = LineValueSampler
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:300]: ugh a LineValueSampler sampling on edges and nodes and my PR to fix that never went in

File: modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i [hunk 84]
```diff
@@ -0,0 +1,192 @@
...
+    xmax = ${fparse 2 * middle}
+    nx = 1000
+  []
+[]
+
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+      allow_imperfect_jacobians = true
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i:29]: for AD?

File: modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i [hunk 85]
```diff
@@ -0,0 +1,192 @@
...
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i:36]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i [hunk 86]
```diff
@@ -0,0 +1,192 @@
...
+
+[FVBCs]
+  #[./mom_pressure]
+  #  type = FVMomImplicitPressureBC
+  #  variable = rho_u
+  #  momentum_component = x
+  #  boundary = 'left right'
+  #[../]
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i:103]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i [hunk 87]
```diff
@@ -0,0 +1,192 @@
...
+  [TimeIntegrator]
+    type = ExplicitSSPRungeKutta
+    order = 2
+  []
+  l_tol = 1e-8
+
+  # run to t = 0.15
+  start_time = 0.0
+  dt = 1e-2
+  end_time = 20
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i:185]: test is running 10 steps of 0.01s, the end_time is 20s and the comment says 0.15s

could you please make those numbers more consistent

File: modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i [hunk 88]
```diff
@@ -0,0 +1,288 @@
...
+#  [./Markers]
+#    [./mach]
+#      type = ValueThresholdMarker
+#      coarsen = 0.3
+#      variable = Ma
+#      refine = 0.85
+#    [../]
+#  [../]
+#[]
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i:262]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i [hunk 89]
```diff
@@ -0,0 +1,288 @@
...
+    [./fp]
+      type = IdealGasFluidProperties
+      allow_imperfect_jacobians = true
+    [../]
+  [../]
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i:56]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i [hunk 90]
```diff
@@ -0,0 +1,288 @@
...
+
+[FVBCs]
+  #[./zero_vel]
+  #  type = FVDirichletBC
+  #  variable = 'rho_u'
+  #  value = 0
+  #  boundary = 'left right'
+  #[../]
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i:181]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i [hunk 91]
```diff
@@ -0,0 +1,315 @@
...
+  []
+
+  ## outflow implicit conditions
+  [mass_outflow]
+    type = CNSFVHLLCMassImplicitBC
+    variable = rho
+    fp = fp
+    boundary = right
+  []
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i:159]:
```suggestion

  # outflow explicit pressure boundary condition
```

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i [hunk 92]
```diff
@@ -0,0 +1,315 @@
...
+outlet_pressure = 0.9e5
+
+[GlobalParams]
+  fp = fp
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i:16]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i [hunk 93]
```diff
@@ -0,0 +1,315 @@
...
+
+mass_flux = ${fparse inlet_vel * rho_in}
+enthalpy_flux = ${fparse inlet_vel * rho_in * H_in}
+
+outlet_pressure = 0.9e5
+
+[GlobalParams]
+  fp = fp
+[]
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i:13]:
```suggestion
```
might be simpler at this point

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i [hunk 94]
```diff
@@ -0,0 +1,192 @@
...
+  nl_rel_tol = 1e-12
+[]
+
+[Outputs]
+  exodus = true
+  csv = true
+  [dof]
+    type = DOFMap
+    execute_on = 'initial'
+  []
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:162]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i [hunk 95]
```diff
@@ -0,0 +1,192 @@
...
+[]
+
+[Executioner]
+  type = Steady
+  solve_type = 'NEWTON'
+  petsc_options_iname = '-pc_type'
+  petsc_options_value = 'lu'
+  # petsc_options = '-pc_svd_monitor'
+  # petsc_options_iname = '-pc_type'
+  # petsc_options_value = 'svd'
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:152]:
```suggestion
```
anything on the dominance ratio you learned from these?

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i [hunk 96]
```diff
@@ -0,0 +1,192 @@
...
+  value = '4*sin(x)^3/cos(x)^2 + 7*sin(x)'
+[]
+[exact_rho_et]
+  type = ParsedFunction
+  value = '3*cos(x)'
+[]
+[forcing_rho_et]
+  type = ParsedFunction
+  value = '8*cos(x)'
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:142]:
```suggestion
  [exact_rho]
    type = ParsedFunction
    value = 'cos(x)'
  []
  [forcing_rho]
    type = ParsedFunction
    value = '2*cos(x)'
  []
  [exact_rho_u]
    type = ParsedFunction
    value = '2*sin(x)'
  []
  [forcing_rho_u]
    type = ParsedFunction
    value = '4*sin(x)^3/cos(x)^2 + 7*sin(x)'
  []
  [exact_rho_et]
    type = ParsedFunction
    value = '3*cos(x)'
  []
  [forcing_rho_et]
    type = ParsedFunction
    value = '8*cos(x)'
  []
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i [hunk 97]
```diff
@@ -0,0 +1,192 @@
...
+    dim = 1
+    xmin = .1
+    xmax = 1
+    nx = 2
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:17]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i [hunk 98]
```diff
@@ -0,0 +1,207 @@
...
+    xmin = .1
+    xmax = 1
+    nx = 2
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i:18]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i [hunk 99]
```diff
@@ -0,0 +1,207 @@
...
+  nl_rel_tol = 1e-12
+[]
+
+[Outputs]
+  exodus = true
+  csv = true
+  [dof]
+    type = DOFMap
+    execute_on = 'initial'
+  []
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i:177]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i [hunk 100]
```diff
@@ -0,0 +1,207 @@
...
+[]
+
+[Executioner]
+  type = Steady
+  solve_type = 'NEWTON'
+  petsc_options_iname = '-pc_type'
+  petsc_options_value = 'lu'
+  # petsc_options = '-pc_svd_monitor'
+  # petsc_options_iname = '-pc_type'
+  # petsc_options_value = 'svd'
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/hllc-mms.i:167]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py [hunk 101]
```diff
@@ -0,0 +1,28 @@
...
+import sympy
+
+rho = 'cos(x)'
+rho_u = '2*sin(x)'
+rho_et = '3*cos(x)'
+p = 'rho'
+vel = 'rho_u / rho * e_i'
+rho_ht = 'rho_et + p'
+
+# f_rho, e_rho = mms.evaluate('-div(grad(rho))', rho, variable='rho', rho=rho)
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py:13]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py [hunk 102]
```diff
@@ -0,0 +1,28 @@
...
+f_rho, e_rho = mms.evaluate('div(vel*rho) - div(grad(rho))', rho, variable='rho', rho=rho, rho_u=rho_u, vel=vel)
+# f_rho, e_rho = mms.evaluate('div(vel*rho)', rho, variable='rho', rho=rho, rho_u=rho_u, vel=vel)
+# f_rho_u, e_rho_u = mms.evaluate('div(vel*rho_u) - div(grad(rho_u))', rho_u, variable='rho_u', rho=rho, rho_u=rho_u, vel=vel)
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py:16]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py [hunk 103]
```diff
@@ -0,0 +1,28 @@
...
+f_rho_u, e_rho_u = mms.evaluate('div(vel*rho_u) - div(grad(rho_u)) + grad(p).dot(e_i)', rho_u, variable='rho_u', rho=rho, rho_u=rho_u, vel=vel, p=p)
+f_rho_et, e_rho_et = mms.evaluate('div(vel*rho_ht) - div(grad(rho_et))', rho_et, variable='rho_et', rho_et=rho_et, rho=rho, rho_u=rho_u,  vel=vel, p=p, rho_ht=rho_ht)
+# f_rho_et, e_rho_et = mms.evaluate('div(vel*rho_et)', rho_et, variable='rho_et', rho_et=rho_et, rho=rho, rho_u=rho_u,  vel=vel, p=p, rho_ht=rho_ht)
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/1d-compute-functions.py:19]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests [hunk 104]
```diff
@@ -0,0 +1,13 @@
+[Tests]
+  issues = '#16758'
+  design = 'CNSFVHLLCBase.md'
+  [1d-hllc]
+    type = PythonUnitTest
+    input = test.py
+    test_case = Test1DHLLC
+    requirement = 'The system shall be able to solve compressible fluid flow kernels for mass, momentum, and energy with the addition of diffusion and display first order convergence for all variables when using a HLLC scheme for the convection terms.'
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: so 2 questions:
- what happens when you just slap a diffusion kernel onto HLLC? Because the scheme is meant for Euler equations, it doesnt look at diffusion of the shockwave
- it seems the no-diffusion-hllc-mms.i is not used by any test? Or am I missing it

**Review by GiudGiud — COMMENTED** [review]
Mostly went over the HLLC tests. less than 50 files left now!
@idaholab/moose-ccb if anyone wants to have a look before we merge, I only need to review the KT schemes pretty much

**Comment by fdkong** [comment]
I will take a review within this week

File: modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C (hunk 60 above)
Comment (lindsayad) [reply modules/navier_stokes/src/postprocessors/NSCFLTimeStepSize.C:21]: No. We are using a statically typed language so there is no way around this. We used to allow inter-conversion between non-AD and AD material properties but it was disastrous

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: Note that CFL is a necessary but not necessarily sufficient condition for stability

Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: My hypothesis would be that the stability limitation is not due to the wave speed estimates, but it would be good to give it a whirl and verify. I will do this if you don't beat me to it @GiudGiud

File: modules/navier_stokes/src/userobjects/HLLCUserObject.C (hunk 62 above)
Comment (lindsayad) [reply modules/navier_stokes/src/userobjects/HLLCUserObject.C:32]: I elected for the former

File: test/src/fvkernels/FVLimitedAdvection.C [hunk 105]
```diff
@@ -0,0 +1,50 @@
...
+    _limiter(Limiter::build(LimiterType(int(getParam<MooseEnum>("limiter"))))),
+    _grad_u_elem(_var.adGradSln()),
+    _grad_u_neighbor(_var.adGradSlnNeighbor())
+{
+}
+
+ADReal
+FVLimitedAdvection::computeQpResidual()
+{
+  const bool elem_is_up = _velocity * _normal >= 0;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply test/src/fvkernels/FVLimitedAdvection.C:42]: So many more characters 😆

File: test/include/fvkernels/FVLimitedAdvection.h [hunk 106]
```diff
@@ -0,0 +1,39 @@
...
+
+namespace Moose
+{
+namespace FV
+{
+class Limiter;
+}
+}
+
+class FVLimitedAdvection : public FVFluxKernel
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply test/include/fvkernels/FVLimitedAdvection.h:24]: Test object stickler 😢

File: python/MooseDocs/test/extensions/test_appsyntax.py [hunk 107]
```diff
@@ -94,7 +94,8 @@ def testHTML(self):
         self.assertEqual(res(3)['data-details-open'], 'open')
         self.assertEqual(res(3).text(), 'Optional Parameters')
 
-        self.assertHTMLTag(res(4), 'ul', size=2)
+        # This size should match the number of optional parameters for Kernel
+        self.assertHTMLTag(res(4), 'ul', size=3)
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply python/MooseDocs/test/extensions/test_appsyntax.py:98]: `prop_getter_suffix`

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/rotated-2d-bkt-function-porosity.i (hunk 63 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/rotated-2d-bkt-function-porosity.i:36]: This branch has been in existence for a very long time ... well before you fixed up this integrity check

File: modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i (hunk 64 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/straight_channel_porosity_step/hllc.i:86]: I really wish that jump to conversation worked properly when github decides to not have every diff loaded. I have to have two windows open to know which file to navigate to in order to add the suggestion to the batch

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C (hunk 65 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:222]: Well definitely not with the momentum checks. You could circumvent this:

> a list of variables, would be even cooler. I think the latter is not possible right

by overriding `computeResidual` but you would need the logic to loop over an arbitrary number of `variable`-esque args

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i (hunk 68 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:27]: There's this in `FluidProperites::validParams`:
```
  params.addParam<bool>(
      "allow_imperfect_jacobians",
      false,
      "true to allow unimplemented property derivative terms to be set to zero for the AD API");
```
However, this doesn't actually appear to be necessary for this input (nor should it ever be for FV (which is always AD)) so I will remove this

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i (hunk 83 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:300]: Is it still languishing in an open state?

File: modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i (hunk 87 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/benchmark_shock_tube_1D/hllc_sod_shocktube.i:185]: I think a user should be able to run the whole sod shocktube test if they come to this directory and run this input without any `cli_args`. If they do so, they will see a very nice development of shock, contact, and rarefaction waves. However, running that whole test in the test harness takes a while hence the limiting the time in the `tests` spec. However, I will definitely update the comment

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i (hunk 93 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/subsonic_nozzle_fixed_inflow_hllc.i:13]: It was missing from the material so I actually kept this block and flushed all the other `fp =` lines

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i (hunk 96 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:142]: I'm impressed by the effort

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i (hunk 95 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/no-diffusion-hllc-mms.i:152]: I think this was just for debugging something wrong in the initial implementation where things were singular when they shouldn't have been

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: I just checked on the 1D shock tube. Pure Roe vs Roe blend shows little difference. The max time step I can take with pure Roe is 0.086 while with Roe blend it's 0.087. I ll do a little more testing but now that we have a reference for our wave speeds that's good with me.

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests (hunk 104 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: > what happens when you just slap a diffusion kernel onto HLLC? Because the scheme is meant for Euler equations, it doesnt look at diffusion of the shockwave

When running a real problem in which you actually have a shockwave, I myself do not know. I do know:

- there is quite a bit of literature about attempting to incorporate viscosity/conduction into characteristic/Riemann-style treatments of the Navier-Stokes equations. I also know that
- `rhoCentralFoam` does operator splitting for momentum advection/viscosity and energy advection/conduction. They do this because of time-step limitations imposed by the diffusion/conduction term for explicit schemes. They, however, do not do any special spatial discretization of viscosity/conduction nor do they do any modification of the Kurganov-Tadmor advective fluxes
- The approximation order as shown by this MMS test does not appear to be affected by the presence of `FVDiffusion`.


>     * it seems the no-diffusion-hllc-mms.i is not used by any test? Or am I missing it

You are correct. I will remove it. The `mms/1d-with-bcs` directory contains HLLC MMC tests with no `FVDiffusion`

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/varying-eps-hllc.i [hunk 108]
```diff
@@ -0,0 +1,262 @@
...
+[Modules]
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/varying-eps-hllc.i:24]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/varying-eps-hllc.i [hunk 109]
```diff
@@ -0,0 +1,262 @@
...
+  type = ParsedVectorFunction
+  value_x = '1.0*cos(1.1*x)*cos(1.3*x)/cos(x)'
+[]
+[]
+
+[Executioner]
+  solve_type = NEWTON
+  type = Transient
+  num_steps = 1
+  dtmin = 1
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/varying-eps-hllc.i:217]:
```suggestion
  type = Steady
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 110]
```diff
@@ -0,0 +1,263 @@
...
+def run_spatial(*args, **kwargs):
+    try:
+        kwargs['executable'] = "../../../../../../"
+        return mms.run_spatial(*args, **kwargs)
+    except:
+        kwargs['executable'] = "../../../../../../../combined/"
+        return mms.run_spatial(*args, **kwargs)
+
+class Test1DFreeFlowHLLC(unittest.TestCase):
+# class Test1DFreeFlowHLLC():
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:14]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 111]
```diff
@@ -0,0 +1,263 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('free-flow-hllc.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s, %f" % (key, value))
+            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))
+
+class Test1DPorousHLLC(unittest.TestCase):
+# class Test1DPorousHLLC():
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:27]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 112]
```diff
@@ -0,0 +1,263 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('porous-hllc.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s, %f" % (key, value))
+            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))
+
+class Test1DVaryingEpsPorousHLLC(unittest.TestCase):
+# class Test1DVaryingEpsPorousHLLC():
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:40]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 113]
```diff
@@ -0,0 +1,263 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('varying-eps-hllc.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s, %f" % (key, value))
+            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))
+
+class TestBasic1DPorousKTPrimitiveCD(unittest.TestCase):
+# class TestBasic1DPorousKTPrimitiveCD():
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:53]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 114]
```diff
@@ -0,0 +1,263 @@
...
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('varying-eps-basic-kt-mixed-cd.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s slope, %f" % (key, value))
+            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))
+        # for key,value in fig.label_to_intercept.items():
+        #     print("%s intercept, %f" % (key, value))
+
+class TestBasic1DVaryingPorousKTMixedUpwind(unittest.TestCase):
+# class TestBasic1DVaryingPorousKTMixedUpwind():
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:248]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py [hunk 115]
```diff
@@ -0,0 +1,263 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('varying-eps-basic-kt-mixed-upwind.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s slope, %f" % (key, value))
+            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))
+        # for key,value in fig.label_to_intercept.items():
+        #     print("%s intercept, %f" % (key, value))
+
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]:
```suggestion

class TestBasic1DPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', list(range(8,11)), "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', 4, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DPorousKTConservedCD(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DPorousKTConservedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 10, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .1))

class TestBasic1DPorousKTConservedVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 6, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DVaryingPorousKNPPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKNPPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "--error", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKNPPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTMixedCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTMixedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 9, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))


```

Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]:
```suggestion

class TestBasic1DPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', list(range(8,11)), "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', 4, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DPorousKTConservedCD(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DPorousKTConservedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 10, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .1))

class TestBasic1DPorousKTConservedVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 6, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DVaryingPorousKNPPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKNPPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "--error", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKNPPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTMixedCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTMixedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 9, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))


```

Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]:
```suggestion

class TestBasic1DPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', list(range(8,11)), "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('basic-primitive-pcnsfv-kt.i', 4, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-primitive-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DPorousKTConservedCD(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DPorousKTConservedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 10, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .1))

class TestBasic1DPorousKTConservedVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2rho', 'L2rho_ud', 'L2rho_et']
        df1 = run_spatial('basic-conserved-pcnsfv-kt.i', 6, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('basic-conserved-pcnsfv-kt-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 2.)

class TestBasic1DVaryingPorousKNPPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKNPPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "--error", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKNPPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-knp-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTPrimitiveCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 7, "GlobalParams/limiter='central_difference'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTPrimitiveUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 9, "GlobalParams/limiter='upwind'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))

class TestBasic1DVaryingPorousKTPrimitiveVanLeer(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_vel_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-primitive.i', 8, "GlobalParams/limiter='vanLeer'", "GlobalParams/knp_for_omega=false", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, slope_precision=1)
        fig.save('varying-eps-basic-kt-primitive-vanLeer.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertGreaterEqual(value, 1.95)

class TestBasic1DVaryingPorousKTMixedCD(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 5, "GlobalParams/limiter='central_difference'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-cd.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 2., .05))

class TestBasic1DVaryingPorousKTMixedUpwind(unittest.TestCase):
    def test(self):
        labels = ['L2pressure', 'L2sup_mom_x', 'L2T_fluid']
        df1 = run_spatial('varying-eps-basic-kt-mixed.i', 9, "GlobalParams/limiter='upwind'", "--error", y_pp=labels)

        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
        fig.save('varying-eps-basic-kt-mixed-upwind.png')
        for key,value in fig.label_to_slope.items():
            print("%s slope, %f" % (key, value))
            self.assertTrue(fuzzyAbsoluteEqual(value, 1., .05))


```

Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]: git wont let me fix them all in one go

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/straight-channel-hllc.i [hunk 116]
```diff
@@ -0,0 +1,139 @@
...
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/straight-channel-hllc.i:24]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/regular-straight-channel.i [hunk 117]
```diff
@@ -0,0 +1,139 @@
...
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/regular-straight-channel.i:24]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/porous-hllc.i [hunk 118]
```diff
@@ -0,0 +1,249 @@
...
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/porous-hllc.i:27]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/implicit_bcs/hllc_sod_shocktube.i [hunk 119]
```diff
@@ -0,0 +1,195 @@
...
+    [fp]
+      type = IdealGasFluidProperties
+      allow_imperfect_jacobians = true
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/implicit_bcs/hllc_sod_shocktube.i:39]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i [hunk 120]
```diff
@@ -0,0 +1,229 @@
...
+  [FluidProperties]
+    [fp]
+      type = IdealGasFluidProperties
+    []
+  []
+[]
+
+[Problem]
+  kernel_coverage_check = false
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i:25]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i [hunk 121]
```diff
@@ -0,0 +1,229 @@
...
+    variable = rho_et
+    function = 'exact_rho_et'
+  []
+[]
+
+[FVKernels]
+  [mass_advection]
+    type = CNSFVMassHLLC
+    variable = rho
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i:61]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i [hunk 122]
```diff
@@ -0,0 +1,229 @@
...
+    type = FVBodyForce
+    variable = rho
+    function = 'forcing_rho'
+  []
+
+  [momentum_x_advection]
+    type = CNSFVMomentumHLLC
+    variable = rho_u
+    momentum_component = x
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i:73]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i [hunk 123]
```diff
@@ -0,0 +1,229 @@
...
+  [momentum_fn]
+    type = FVBodyForce
+    variable = rho_u
+    function = 'forcing_rho_u'
+  []
+
+  [fluid_energy_advection]
+    type = CNSFVFluidEnergyHLLC
+    variable = rho_et
+    fp = fp
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i:84]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i [hunk 124]
```diff
@@ -0,0 +1,229 @@
...
+  value = '1.0*(3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x) + 26.7439413073546*cos(1.2*x))*sin(x)*cos(1.1*x)/cos(x)^2 - 1.1*(3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x) + 26.7439413073546*cos(1.2*x))*sin(1.1*x)/cos(x) + 1.0*(-(10.6975765229419*cos(1.2*x)/cos(x) - 0.697576522941849*cos(1.1*x)^2/cos(x)^2)*sin(x) + (10.6975765229419*sin(x)*cos(1.2*x)/cos(x)^2 - 1.3951530458837*sin(x)*cos(1.1*x)^2/cos(x)^3 + 1.53466835047207*sin(1.1*x)*cos(1.1*x)/cos(x)^2 - 12.8370918275302*sin(1.2*x)/cos(x))*cos(x) - 32.0927295688256*sin(1.2*x))*cos(1.1*x)/cos(x)'
+[]
+[exact_T]
+  type = ParsedFunction
+  value = '0.0106975765229418*cos(1.2*x)/cos(x) - 0.000697576522941848*cos(1.1*x)^2/cos(x)^2'
+[]
+[exact_p]
+  type = ParsedFunction
+  value = '3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x)'
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/free-flow-hllc.i:179]:
```suggestion
  [exact_rho]
    type = ParsedFunction
    value = '3.48788261470924*cos(x)'
  []
  [forcing_rho]
    type = ParsedFunction
    value = '-3.83667087618017*sin(1.1*x)'
  []
  [exact_rho_u]
    type = ParsedFunction
    value = '3.48788261470924*cos(1.1*x)'
  []
  [forcing_rho_u]
    type = ParsedFunction
    value = '-(10.6975765229419*cos(1.2*x)/cos(x) - 0.697576522941849*cos(1.1*x)^2/cos(x)^2)*sin(x) + (10.6975765229419*sin(x)*cos(1.2*x)/cos(x)^2 - 1.3951530458837*sin(x)*cos(1.1*x)^2/cos(x)^3 + 1.53466835047207*sin(1.1*x)*cos(1.1*x)/cos(x)^2 - 12.8370918275302*sin(1.2*x)/cos(x))*cos(x) + 3.48788261470924*sin(x)*cos(1.1*x)^2/cos(x)^2 - 7.67334175236034*sin(1.1*x)*cos(1.1*x)/cos(x)'
  []
  [exact_rho_et]
    type = ParsedFunction
    value = '26.7439413073546*cos(1.2*x)'
  []
  [forcing_rho_et]
    type = ParsedFunction
    value = '1.0*(3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x) + 26.7439413073546*cos(1.2*x))*sin(x)*cos(1.1*x)/cos(x)^2 - 1.1*(3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x) + 26.7439413073546*cos(1.2*x))*sin(1.1*x)/cos(x) + 1.0*(-(10.6975765229419*cos(1.2*x)/cos(x) - 0.697576522941849*cos(1.1*x)^2/cos(x)^2)*sin(x) + (10.6975765229419*sin(x)*cos(1.2*x)/cos(x)^2 - 1.3951530458837*sin(x)*cos(1.1*x)^2/cos(x)^3 + 1.53466835047207*sin(1.1*x)*cos(1.1*x)/cos(x)^2 - 12.8370918275302*sin(1.2*x)/cos(x))*cos(x) - 32.0927295688256*sin(1.2*x))*cos(1.1*x)/cos(x)'
  []
  [exact_T]
    type = ParsedFunction
    value = '0.0106975765229418*cos(1.2*x)/cos(x) - 0.000697576522941848*cos(1.1*x)^2/cos(x)^2'
  []
  [exact_p]
    type = ParsedFunction
    value = '3.48788261470924*(3.06706896551724*cos(1.2*x)/cos(x) - 0.2*cos(1.1*x)^2/cos(x)^2)*cos(x)'
  []
```

File: modules/navier_stokes/src/materials/PorousConservedVarMaterial.C [hunk 125]
```diff
@@ -0,0 +1,162 @@
...
+// FluidProperties includes
+#include "SinglePhaseFluidProperties.h"
+
+registerMooseObject("NavierStokesApp", PorousConservedVarMaterial);
+
+InputParameters
+PorousConservedVarMaterial::validParams()
+{
+  auto params = Material::validParams();
+  params.addRequiredParam<UserObjectName>(NS::fluid, "fluid userobject");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/materials/PorousConservedVarMaterial.C:23]:
```suggestion
  params.addRequiredParam<UserObjectName>(NS::fluid, "Fluid properties userobject");
```

**Review by GiudGiud — COMMENTED** [review]
test cosmetics.
Got to read up on KT now

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests [hunk 126]
```diff
@@ -0,0 +1,11 @@
+[Tests]
+  issues = '#16758'
+  design = 'CNSFVHLLCBase.md'
+  [./fv_specified_pressure_out]
+    type = Exodiff
+    input =  subsonic_nozzle_fixed_inflow_hllc.i
+    exodiff = subsonic_nozzle_fixed_inflow_hllc_out.e
+    abs_zero = 1e-9
+    requirement = "The system shall be able to model subsonic nozzle flow using an HLLC discretization with a specified outlet pressure."
+  [../]
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests:10]: I actually think the problem is probably inadequate BC specification. subsonic inlet needs dim + 1 specified properties, so 3 in this 2D case, and there are only 2. I know that @snschune has talked for a while about something wrong with specified pressure. Well we fixed one thing ... the elem information at the boundary should use the interior pressure as opposed to the boundary pressure function. But this may be a separate problem (e.g. the incorrect number of bcs)

[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests:10]: > this test does not converge beyond timestep 16 (stopped at 10 in this test).

Are you using a recent checkout of this branch that has the elem correction (removing the pressure function from the elem computations in the specified pressure BC)? I am able to run out to `num_steps = 20` without issue. The pressure profile with the current input does indeed look a bit weird

Screen Shot 2021-06-23 at 4 53 01 PM

and I do see the weird local maxima with `Ma_layered` 

Screen Shot 2021-06-23 at 4 54 50 PM

but at least it runs

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py (hunk 115 above)
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]: This is kind of you but the easiest thing for me is to just flush lines with `#` in my editor. I honestly trust it a bit more than manual github edits...

Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d-with-bcs/test.py:261]: And I will give you co-authorship on the commit either way 😄

File: modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C (hunk 50 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/CNSFVHLLCBase.C:95]: It's a bit funny that the Einfeldt paper was published before HLLC was even created and we use it as a reference for signal speeds. (Toro did HLLC in 1994). *But* Batten published in 1997 and he clearly discusses HLLC so I think that's a "solid" reference

File: modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests (hunk 126 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests:10]: Ah sorry I think I had bumped up the timesteps too. I was using the pre-review version of the cnfsv too. 
So with the current version it fails at like 6.5s with a 0.05s timestep.
With 0.01s timestep, I was able to reach to reach about the same time. 

The solution is hardly stabilized at this point, the specified pressure (9e4) is hardly obeyed from the beginning, as the top pictures show.
By the time it fails:
image

[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests:10]: Ok yea I think I'm going to see about how to fix the bad number of inlet bcs

[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/pressure_outlet/tests:10]: Ok yea I'm able to run to steady-state with sufficient BCs. And layered Mach issue was because of more layers than cells in the x-direction

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C (hunk 65 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:222]: Yeah so code wise it s cleaner that way. Performance wise, most likely not limiting

File: modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i (hunk 83 above)
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/cns/stagnation_inlet/supersonic_nozzle_hllc.i:284]: yup. Got to find what s up with bison on it

File: modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md (hunk 43 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md:1]: or setFlux?

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests (hunk 104 above)
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: MMS results with diffusion are encouraging. 
From Toro, it seems either operator splitting or some sort of upwinding of the source terms are what is being considered for dealing with source terms. Since we do neither of those things, I m a little worried that our approach will be an issue for someone doing a real problem, and they wont be too happy when we tell them after they've modeled it. 

How do you think we can document that we do not have a special treatment of diffusion or source terms and that it could be necessary even though we survived without so far ?

Comment (lindsayad) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: > From Toro, it seems either operator splitting or some sort of upwinding of the source terms are what is being considered for dealing with source terms.

Upwinding is a characteristic based concept. If you don't use a characteristic-based discretization of advection, e.g. if you use a centered scheme like Kurganov-Tadmor, then I think it makes total sense to have a centered discretization of source terms. As to how to discretize sources when using a characteristic-based approach to advection ... I honestly think by nature you're trying to fit a round peg in a square hole. To me you just shouldn't do a characteristic based approach with sources because the sources alter the equations. I've seen attempts to incorporate the sources into the eigendecomposition but I was never left feeling super-convinced. THM uses centered discretizations of sources in conjunction with HLLC. Maybe @joshuahansel or @andrsd has thoughts on it.

Comment (joshuahansel) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: In THM, we do not have a good solution for the source term discretization so far. We have not looked into the alternatives of the central source discretization. As far as the concern about users using it without knowing the consequences, I'd recommend you just have the code issue a warning when source terms are detected with an upwind discretization.

File: modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C (hunk 55 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:98]: Ok I profiled a PCNSFV simulation and with caching `PCNSFVHLLC::waveSpeed` comprises 6.44% of the simulation time. Without caching it comprises 6.68%. Comparatively speaking, `MooseVariableDataFV::computeAD` takes ~55% of the simulation time.

Given these results, I don't really care what we do. Maybe I'll do a heap profile and see whether the cache is noticeable

Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:98]: Oops I added the cache but didn't actually use it :rofl: Stand-by for actual caching CPU and heap profile results...

Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C:98]: `PCNSFVHLLC::waveSpeed`:

CPU:
- caching: 3.50%
- not caching: 6.68%

HEAP:
- cache takes anywhere between 10% and 25% of total memory depending on the snapshot

My thought would be that the increase in memory use is not worth the 3% drop in CPU. @GiudGiud what do you think?

**Comment by lindsayad** [comment]
Oh beautiful pass

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C [hunk 127]
```diff
@@ -0,0 +1,269 @@
...
+  const auto psi_elem =
+      std::max({c_elem + u_elem_normal, c_neighbor + u_neighbor_normal, ADReal(0)});
+  const auto psi_neighbor =
+      std::max({c_elem - u_elem_normal, c_neighbor - u_neighbor_normal, ADReal(0)});
+  auto alpha = _knp_for_omega ? psi_elem / (psi_elem + psi_neighbor) : ADReal(0.5);
+  auto omega = _knp_for_omega ? alpha * (1 - alpha) * (psi_elem + psi_neighbor)
+                              : alpha * std::max(psi_elem, psi_neighbor);
+
+  // Do this to avoid new nonzero mallocs
+  const auto dummy_quant = 0 * (c_elem + u_elem_normal + c_neighbor + u_neighbor_normal);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVKT.C:113]: never thought of this

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C [hunk 128]
```diff
@@ -0,0 +1,269 @@
...
+ADReal
+PCNSFVKT::computeFaceFlux(const ADReal & alpha,
+                          const ADReal & omega,
+                          const ADReal & sup_vel_elem_normal,
+                          const ADReal & sup_vel_neighbor_normal,
+                          const ADReal & adv_quant_elem,
+                          const ADReal & adv_quant_neighbor)
+{
+  return alpha * (sup_vel_elem_normal * adv_quant_elem) +
+         (1 - alpha) * sup_vel_neighbor_normal * adv_quant_neighbor -
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVKT.C:129]: says + in (7) of Greenshields?

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C [hunk 129]
```diff
@@ -0,0 +1,269 @@
...
+                                         _pressure_neighbor[_qp],
+                                         _grad_pressure_elem[_qp],
+                                         *_face_info,
+                                         /*elem_is_up=*/true);
+  const auto pressure_neighbor = interpolate(*_limiter,
+                                             _pressure_neighbor[_qp],
+                                             _pressure_elem[_qp],
+                                             _grad_pressure_neighbor[_qp],
+                                             *_face_info,
+                                             /*elem_is_up=*/false);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PCNSFVKT.C:148]: greenshields interpolates rho directly

File: modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i [hunk 130]
```diff
@@ -0,0 +1,263 @@
...
+    input = cartesian
+    primary_block = 1
+    paired_block = 0
+    new_boundary = 'wall'
+  [../]
+
+  [./delete]
+    type = BlockDeletionGenerator
+    input = wall
+    block_id = 0
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/cns/shock_tube_2D_cavity/hllc_sod_shocktube_2D.i:41]: deprecated I think
```suggestion
    block = 0
```

File: modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests (hunk 104 above)
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/cns/mms/1d/tests:8]: Yeah I was mentioning this for HLLC not for KT. I m perfectly happy with the treatment of sources for KT. 
Thanks for the insight!

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C (hunk 128 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:129]: I'm more used to minus (neighbor - elem) though
Thoughts?

**Review by GiudGiud — COMMENTED** [review]
Last review! Just a few comments.

**Comment by GiudGiud** [comment]
@fdkong

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C (hunk 128 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:129]: Since they're equivalent mathematically I like the way we have it because it looks more like a classic diffusive flux (which it is)

File: modules/navier_stokes/src/fvkernels/PCNSFVKT.C (hunk 129 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:148]: That's true. In the article, he interpolates a mixed variable set: density, momentum, and temperature. However, in their code `rhoCentralFoam` they actually interpolate density, momentum, specific internal energy, and 1/compressibility. It's somewhat interesting that a variable for which they express concerns about boundedness is a variable that they don't interpolate in the code.

I think we are free to choose the variables that we interpolate. With the current choice of interpolants I have not seen any variables that fall outside physical bounds.

Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVKT.C:148]: I like the primitive variable set because it fits best with what users typically specify boundary conditions for.

**Comment by lindsayad** [comment]
> I think unless you are planning to:
>
> make HLLC like 3x faster so caching becomes a 10% gain
> and not use a CNFSVHLLCCombinedAdvection kernel that would not need a cache because it advects everyone together
> we can drop the cache.
>
> Or we can wait for someone to call us out for our memory use in Discussions ^^

Becoming difficult to find thread beginnings haha. Removed the cache in the last push.

Beautiful green once again

File: test/src/fvkernels/FVKTLimitedAdvection.C [hunk 131]
```diff
@@ -0,0 +1,58 @@
...
+    _cd_limiter(Limiter::build(LimiterType::CentralDifference)),
+    _grad_u_elem(_var.adGradSln()),
+    _grad_u_neighbor(_var.adGradSlnNeighbor()),
+    _max_abs_eig(getADMaterialProperty<Real>("max_abs_eig")),
+    _add_artificial_diff(getParam<bool>("add_artificial_diff"))
+{
+}
+
+ADReal
+FVKTLimitedAdvection::computeQpResidual()
```
Comment (fdkong) [inline test/src/fvkernels/FVKTLimitedAdvection.C:45]: Why these kernels are in test folder? Are not general enough? It seems very  general for me

**Review by fdkong — COMMENTED** [review]
Looks nice for me

File: framework/src/fvbcs/FVBoundaryCondition.C [hunk 132]
```diff
@@ -12,6 +12,18 @@
 #include "SystemBase.h"
 #include "MooseVariableFV.h"
 
+namespace
+{
+SystemBase &
+changeSystem(const InputParameters & params_in, MooseVariableFV<Real> & fv_var)
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvbcs/FVBoundaryCondition.C:18]: This allows applying Dirichlet boundary conditions to auxiliary variables. Having the Dirichlet boundary condition available allows other objects to get accurate boundary face values for auxiliary variables as well as more accurate cell gradients near boundaries for auxiliary variables

File: framework/src/fvkernels/FVOrthogonalDiffusion.C [hunk 133]
```diff
@@ -0,0 +1,52 @@
...
+  ADReal coeff_interface;
+  Moose::FV::interpolate(Moose::FV::InterpMethod::Average,
+                         coeff_interface,
+                         _coeff_elem[_qp],
+                         _coeff_neighbor[_qp],
+                         *_face_info,
+                         true);
+
+  return -coeff_interface * (_diff_quant_neighbor[_qp] - _diff_quant_elem[_qp]) /
+         _face_info->dCFMag();
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvkernels/FVOrthogonalDiffusion.C:51]: What name would you like better? `dCFMagnitude`? `dCFNorm`?

File: modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C [hunk 134]
```diff
@@ -138,6 +169,21 @@ IdealGasFluidProperties::c_from_p_T(Real /*p*/, Real T) const
...
+
+void
+IdealGasFluidProperties::c_from_p_T(
+    const Real /*p*/, const Real T, Real & c, Real & dc_dp, Real & dc_dT) const
+{
+  c = std::sqrt(_cp * _R * T / (_cv * _molar_mass));
+  dc_dp = 0;
+  dc_dT = 0.5 / c * _cp * _R / (_cv * _molar_mass);
+}
+
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C:186]: It is not super-clean. Objects almost always hold the base `SinglePhaseFluidProperties` and we get the right property calculations by overriding virtual methods. So we have to define all these methods in the derived class in order to get the right property calculations. We could remove a couple lines of code duplication here and there potentially by making the derived non-templated virtual overrides explicitly call a (non-virtual) template defined in the derived class

File: test/src/fvkernels/FVKTLimitedAdvection.C (hunk 131 above)
Comment (lindsayad) [reply test/src/fvkernels/FVKTLimitedAdvection.C:45]: I think that in practice users are going to be solving problems in which the velocity is provided via variables. Moreover, determination of `max_abs_eig` will be a function of the velocity and the function will likely be defined in the kernel implementing the KT method, e.g. in `PCNSFVKT`, as opposed to provided through an arbitrary material property or simple user input. @aeslaughter was recently lamenting the explosion of objects in the framework. I think that until somebody asks for this to be available, I think this is best in test because I don't think it's generally useful.

File: modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md (hunk 43 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/doc/content/source/postprocessors/MfrPostprocessor.md:1]: Ok I ll see when I work on RC UO

**Comment by GiudGiud** [comment]
Yeah the conversations beta feature is broken. Out of the 45 unresolved ones, about 20 are unreachable now..
I've kept track of the critical stuff though so there is no large worry in those.

If you could resolve the 25 or so left, I would approve the PR.

File: framework/src/materials/FVPropValPerSubdomainMaterial.C (hunk 16 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/materials/FVPropValPerSubdomainMaterial.C]: Now tested

File: modules/fluid_properties/src/userobjects/HeliumFluidProperties.C (hunk 19 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/fluid_properties/src/userobjects/HeliumFluidProperties.C]: I did not remove this override but I added the correct nonlinear dof dependence of `dp_dv` and `dp_de`.

File: modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h (hunk 3 above)
Comment (lindsayad) [reply modules/heat_conduction/include/fvbcs/FVRadiativeHeatFluxBCBase.h:40]: Changed to
```c++
  /// Function describing the temperature of the body completely surrounding the surface, e.g. the
  /// temperature of the body we are in radiative heat transfer with
```
after next push

File: modules/navier_stokes/doc/content/source/fvkernels/NSFVSolidFluidConvection.md (hunk 41 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/doc/content/source/fvkernels/NSFVSolidFluidConvection.md]: We were able to reuse as suggested by @GiudGiud . This class consequently no longer exists

File: modules/navier_stokes/src/fvkernels/PCNSFVMomentumPressureRZ.C (hunk 52 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVMomentumPressureRZ.C:28]: I think in the future we can consider adding more flexibility here if needed

File: modules/navier_stokes/include/fvkernels/PNSFVMomentumGravity.h [hunk 135]
```diff
@@ -9,20 +9,20 @@
...
   static InputParameters validParams();
-  PINSFVMomentumGravity(const InputParameters & params);
+  PNSFVMomentumGravity(const InputParameters & params);
 
 protected:
   ADReal computeQpResidual() override;
 
   /// the porosity
-  const VariableValue & _eps;
+  const MooseArray<Real> & _eps;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/fvkernels/PNSFVMomentumGravity.h:27]: They are the same. But now I've updated this class to allow specifying epsilon through either a variable or a material property. Given this change, I like having the more generic-looking type name

File: modules/navier_stokes/include/fvkernels/PNSFVPGradEpsilon.h [hunk 136]
```diff
@@ -0,0 +1,31 @@
...
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "FVElementalKernel.h"
+
+class Function;
+
+class PNSFVPGradEpsilon : public FVElementalKernel
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/fvkernels/PNSFVPGradEpsilon.h:16]: It's as if I missed a whole review :confused:

File: modules/navier_stokes/include/materials/ConservedVarValuesMaterial.h [hunk 137]
```diff
@@ -0,0 +1,52 @@
...
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "Material.h"
+
+class SinglePhaseFluidProperties;
+
+class ConservedVarValuesMaterial : public Material
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/materials/ConservedVarValuesMaterial.h:16]: Otherwise it would conflict with the existing `ConservedVarMaterial` in Pronghorn. Don't make me deal with the name clash again :cry: I think that once this is in we can basically just make `ConservedVarMaterial` a shim of this

File: modules/navier_stokes/include/fvkernels/PNSFVPGradEpsilon.h (hunk 136 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/include/fvkernels/PNSFVPGradEpsilon.h:16]: it's the bonus round ^^

File: modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C (hunk 55 above)
Comment (lindsayad) [reply modules/navier_stokes/src/fvkernels/PCNSFVHLLC.C]: No more caching

File: modules/navier_stokes/include/materials/GeneralFluidProps.h [hunk 138]
```diff
@@ -0,0 +1,118 @@
...
+
+  const SinglePhaseFluidProperties & _fluid;
+
+  /// Porosity
+  const VariableValue & _eps;
+
+  /**
+   * Characteristic length $d$ used in computing the Reynolds number
+   * $Re=\rho_fVd/\mu_f$. If not provided, then a default is taken as
+   * the pebble diameter (if available).
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/include/materials/GeneralFluidProps.h]: :+1:

**Comment by lindsayad** [comment]
So annoying that refreshing contracts all the posts!

**Review by GiudGiud — DISMISSED** [review]

**Comment by GiudGiud** [comment]
@fdkong @snschune @aprilnovak please let us know if you want to comment more / review. Otherwise this is getting merged soon

**Comment by lindsayad** [comment]
the green button is so large. I hear it calling to me

File: framework/src/fvkernels/FVOrthogonalDiffusion.C (hunk 133 above)
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/src/fvkernels/FVOrthogonalDiffusion.C:51]: What dCF stands for? If you could add comments to the function, I would really appreciate it

File: modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C (hunk 134 above)
[the remark this answers is not in the document]
Comment (fdkong) [reply modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C:186]: It is pretty minor.

File: test/src/fvkernels/FVKTLimitedAdvection.C (hunk 131 above)
Comment (fdkong) [reply test/src/fvkernels/FVKTLimitedAdvection.C:45]: Got it.  Class name seem pretty general though, but we might not be worried about

**Comment by fdkong** [comment]
It looks good for me

File: framework/src/fvkernels/FVOrthogonalDiffusion.C (hunk 133 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/fvkernels/FVOrthogonalDiffusion.C:51]: Ok in my latest push I added doxygen to all `FaceInfo` methods

**Comment by aprilnovak** [comment]
Nothing else from me - looks great!

**Comment by lindsayad** [comment]
@GiudGiud could you re-approve?

**Review by GiudGiud — APPROVED** [review]

**Comment by lindsayad** [comment]
@GiudGiud thanks so much for your reviews. I had fun working on it together. And thanks for taking a glance @fdkong !!

**Comment by GiudGiud** [comment]
Congrats on merging this PR @lindsayad!!
This is a second absolutely major fluid flow capability you add to the framework this year and it was a pleasure supporting these major strides
