### PR TITLE
Fix effective strain 

### LINKED ISSUE #12386: Fix effective_plastic_strain output option from TensorMechanics/Master action
## Rationale

The TensorMechanics/Master action currently provides options for outputting `effective_plastic_strain` and `effective_creep_strain`. These incorrectly result in creating a `RankTwoScalarAux` object and using the option to compute `EffectiveStrain` on the plastic or creep strain tensor. That is not the same thing as the true effective plastic or creep strain, which is computed as a Real material property by material models that compute it.

## Description

We should either simply remove these options, or make it so that if the user asks for them, we output the `effective_plastic_strain` or `effective_creep_strain` scalar property from the material.

## Impact

This would change what users get if they ask for `effective_plastic_strain` or `effective_creep_strain`. The logic in the system that generates output in `TensorMechanicsActionBase` would need to be changed to support output of both Real and tensor materials. It may be best to phase in this change by first removing the option to ask for these properties to be output in the Master action, and then go back later and add them back in.

### PR DESCRIPTION
**Pull request by dschwen**
- Add proper computation of effective strains. While some return mapping models compute effective strain themselves this approach is more general, most likely more efficient (as the effective strain is _only_ computed at timestep end, and not during every single iteration), and definitely more modular. For example we had no way of computing the `effective_combined_inelastic_strain` (an output name that now is valid - see next point)

- Also adds the ability to generate scalar outputs of arbitrary tensors (e.g. tensors with base names). 

Closes #12386

### CODE REVIEW

File: modules/tensor_mechanics/src/actions/TensorMechanicsAction.C [hunk 1]
```diff
@@ -723,102 +723,80 @@ TensorMechanicsAction::actOutputMatProp()
...
-              type = ad_prepend + "RankTwoCartesianComponent";
-              params = _factory.getValidParams(type);
-              params.set<MaterialPropertyName>("rank_two_tensor") = _base_name + r2q.second;
-              params.set<unsigned int>("index_i") = a;
-              params.set<unsigned int>("index_j") = b;
-
-              params.applyParameters(parameters());
-              params.set<std::string>("property_name") = _base_name + out;
-            }
+      if ([&]() {
```
Comment (dschwen) [inline modules/tensor_mechanics/src/actions/TensorMechanicsAction.C:732]: the lambda here adds a closure that permits exiting out of the nested loop as soon as a match is found.

File: modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C [hunk 2]
```diff
@@ -230,7 +230,7 @@ TensorMechanicsActionBase::outputPropertiesType()
     for (auto & r : r2cc.second.second)
       options += " " + r2cc.first + "_" + r;
 
-  return MultiMooseEnum(options);
+  return MultiMooseEnum(options, "", true);
```
Comment (dschwen) [inline modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C:233]: permit _out of range_ options here so that users can supply arbitrary property names

File: modules/tensor_mechanics/test/tests/action/tests [hunk 3]
```diff
@@ -33,25 +33,23 @@
                   'subblocks requesting different strain formulations.'
   []
 
-  [error_unrestricted]
+  [two_block.error_unrestricted]
```
Comment (dschwen) [inline modules/tensor_mechanics/test/tests/action/tests:36]: We should _really_ be consistent about naming test blocks with the same names as our test inputs. Anything else is just confusing when looking for the inputs.

**Comment by dschwen** [comment]
This requires a Redback (@cpgr) and a BISON update (I'll do that). In Redback a call to `effectiveStrain` just has to be changed to `effectiveStrainIncrement` and in BISON a handful of test has to be regolded (the use the broken way of computing _effective strain_).

**Comment by dschwen** [comment]
@bwspenc maybe we want to retain the old measure as _equivalent strain_...

**Comment by dschwen** [comment]
I have a fix ready for BISON.

File: modules/tensor_mechanics/src/actions/TensorMechanicsAction.C (hunk 1 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/actions/TensorMechanicsAction.C:732]: I think it is confusing to set the parameters in the arguments to an if statement.  I think the loops should be kept outside of the if statement argument.  A bool could be set in the loop to use with the continue.

File: modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md [hunk 4]
```diff
@@ -40,24 +40,13 @@ where $D$ is the direction vector specified in the input file.
...
-This effective strain measure, `EffectiveStrain`, should not be confused with
-the effective plastic strain or effective creep strain, which are computed as
-integrals over the history of the inelastic strain; these effective inelastic
-strain measures are computed as scalar material properties (named
-`effective_plastic_strain` and `effective_creep_strain`) for applicable $J_2$
-models. The effective inelastic strains are computed as:
+Effective plastic strain or effective creep strain, which are computed as
+integrals over the history of the inelastic strain as
 \begin{equation}
 s = \int_t\sqrt{\frac{2}{3} \dot{\epsilon}^p_{ij} \dot{\epsilon}^p_{ij}} \mathrm{d}t
```
Comment (lynnmunday) [inline modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: was the EffectiveStrain only for the elastic strain component?  If this changes the effective strain to only be for the inelastic components, maybe this equation should be deleted too since it is no longer used for calculating the effective strain.  Or at least I don't think this is how we calculate the effective creep strain.

Comment (dschwen) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: This equation is how the effective inelastic strain is computed.

Comment (lynnmunday) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: Or is this equation used for computing the effective strain increment.

File: modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md [hunk 5]
```diff
@@ -40,24 +40,13 @@ where $D$ is the direction vector specified in the input file.
 
 ## Effective Strain
```
Comment (lynnmunday) [inline modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:41]: should this heading be effective strain Increment

File: modules/tensor_mechanics/include/utils/RankTwoScalarTools.h [hunk 6]
```diff
@@ -98,12 +97,12 @@ vonMisesStress(const RankTwoTensorTempl<T> & stress)
...
- * The effective strain is calculated as
+ * The effective strain increment (or equivalent von Mises strain) is calculated as
  * \epsilon_{eff} = \sqrt{\frac{2}{3}\epsilon_{ij} \epsilon_{ij}}
  */
 template <typename T>
 T
-effectiveStrain(const RankTwoTensorTempl<T> & strain)
+effectiveStrainIncrement(const RankTwoTensorTempl<T> & strain)
 {
   return std::sqrt(2.0 / 3.0 * strain.doubleContraction(strain));
```
Comment (lynnmunday) [inline modules/tensor_mechanics/include/utils/RankTwoScalarTools.h:107]: how do you know the strain is only the strain increment?  Is it the total strain increment or can it be elastic, plastic or creep components?   Summing this up over a simulation probably won't give the same value as the effective strain returned by the radial return method. Are we still going to return the effective strain from the radial return mapping if it is available.

File: modules/tensor_mechanics/include/materials/RankTwoInvariant.h [hunk 7]
```diff
@@ -26,15 +26,23 @@ class RankTwoInvariantTempl : public Material
...
+
+  /// Are stateful properties required?
+  const bool _stateful;
+
+  /// Tensor to extract the invariant from
   const GenericMaterialProperty<RankTwoTensor, is_ad> & _tensor;
 
-  /// Name of the stress/strain to be calculated
-  const std::string _property_name;
+  /// Old state of the tensor (required for sffective strain calculation)
```
Comment (lynnmunday) [inline modules/tensor_mechanics/include/materials/RankTwoInvariant.h:38]: spelling effective

File: modules/tensor_mechanics/include/utils/RankTwoScalarTools.h (hunk 6 above)
Comment (dschwen) [reply modules/tensor_mechanics/include/utils/RankTwoScalarTools.h:107]: You can pass in any strain increment tensor. I guess you could also pass in stress tensor increments (or total tensors), but I'm not sure how useful the output would be in those cases.

File: modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md (hunk 5 above)
Comment (dschwen) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:41]: Well, ultimately what we want to compute is the effective strain. The increment is just the means here. But you're right, in this tools namespace we only deal with the increment. The integration is performed in the material.

File: modules/tensor_mechanics/include/utils/RankTwoScalarTools.h (hunk 6 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/include/utils/RankTwoScalarTools.h:107]: Is the effective strain return by a creep material that uses the radial return mapping going to be the radial return mapping computed effective strain or is it going to be the effective strain computed using this equation

File: modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md (hunk 4 above)
Comment (dschwen) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: There is an integral in the equation, so, no, not the increment.

Comment (lynnmunday) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: I was wondering if we are going to be computing the effective strain increment using this formula 
sqrt{\frac{2}{3} \dot{\epsilon}^p_{ij} \dot{\epsilon}^p_{ij}}
or will we still use the increment computed from the radial return mapping when it is available?   Do we ever reference other theory manuals, like for ls-dyna?  They use the same definition for effective plastic strain

File: modules/tensor_mechanics/include/utils/RankTwoScalarTools.h (hunk 6 above)
Comment (dschwen) [reply modules/tensor_mechanics/include/utils/RankTwoScalarTools.h:107]: That's up to the user. For combined inelastic models and models that do not make the effective strain available it will have to be this equation.

File: modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md (hunk 4 above)
Comment (dschwen) [reply modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md:46]: If the effective inelastic strain is available from the radial return mapping you should probably use that value, however for stacked models and classes that do not use our radial return mapping you can use this approach.

File: modules/tensor_mechanics/src/materials/RankTwoInvariant.C [hunk 8]
```diff
@@ -60,31 +61,43 @@ RankTwoInvariantTempl<is_ad>::computeQpProperties()
...
           RankTwoScalarTools::getInvariant(MetaPhysicL::raw_value(_tensor[_qp]), _invariant);
       break;
     }
+
+    case RankTwoScalarTools::InvariantType::EffectiveStrain:
+    {
+      mooseAssert(_tensor_old, "The selected invariant requires the input material to be stateful");
+      mooseAssert(_property_old,
+                  "The selected invariant requires the output material to be stateful");
+      _property[_qp] = (*_property_old)[_qp] + RankTwoScalarTools::effectiveStrain(
```
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/RankTwoInvariant.C:95]: Do you think it's worth renaming `RankTwoScalarTools::effectiveStrain()` to `RankTwoScalarTools::effectiveStrainIncrement()` and having it take two arguments (the new and old tensors)? That would help reinforce the point that we can't directly compute that quantity from just the current state of the tensor.

Along the same lines, if we do that we should probably rename the enum entry for that from `RankTwoScalarTools::InvariantType::EffectiveStrain` to `RankTwoScalarTools::InvariantType::EffectiveStrainIncrement`.

**Review by bwspenc — CHANGES_REQUESTED** [review]
Super happy to see this change being made!  Overall looks good, just a few comments.

Regarding the broken apps, I think we need to go fix the tests in those apps first by manually requesting the scalar effective plastic strain with AuxKernels. That will probably require re-golding results files. Then we can merge this, and optionally go back and have those app tests use the Action.

File: modules/tensor_mechanics/include/actions/TensorMechanicsAction.h [hunk 9]
```diff
@@ -32,6 +32,9 @@ class TensorMechanicsAction : public TensorMechanicsActionBase
   virtual std::string getKernelType();
   virtual InputParameters getKernelParameters(std::string type);
 
+  template <typename T, typename T2>
```
Comment (bwspenc) [inline modules/tensor_mechanics/include/actions/TensorMechanicsAction.h:35]: A doxygen comment describing what the parameters are and what this function does would be helpful here.

File: modules/tensor_mechanics/src/actions/TensorMechanicsAction.C (hunk 1 above)
[the remark this answers is not in the document]
Comment (bwspenc) [reply modules/tensor_mechanics/src/actions/TensorMechanicsAction.C:732]: Thanks to your helpful explanation of lambdas, I think I'm finally wrapping my head around what's going on and relenting on my stance against them here.

File: modules/tensor_mechanics/src/materials/RankTwoInvariant.C (hunk 8 above)
Comment (dschwen) [reply modules/tensor_mechanics/src/materials/RankTwoInvariant.C:95]: There is no API for processing a pair of tensors in teh corresponding function that takes that enum.

**Comment by dschwen** [comment]
The only way to avoid breaking Bison is to _not_ calculate the bogus effective strain in those five tests (i.e. make a Bison MR first, regolding those tests)

**Comment by dschwen** [comment]
The Bison MR is up. Hopefully we can bring this to a conclusion soon.

**Review by bwspenc — APPROVED** [review]
