### PR TITLE
Fix EBSD mapping issue when using the getElementValue(s) methods

### LINKED ISSUE #5651: GrainTracker fix for multiple occurrences of same grain id
Grain Tracker needs to be able to handle multiple occurrences of the same grain id when these occurrences belong to the same grain (as in the case of kidney-shaped grains when dealing with serial sections). Otherwise there is a mismatch between the EBSD centers and the Grain Tracker Centers.
I believe @permcody will be handling this.

### PR DESCRIPTION
**Pull request by permcody**
closes #5651 

Here you go @jhbradley

### CODE REVIEW

**Comment by jhbradley** [comment]
Thanks a lot!

File: modules/phase_field/src/postprocessors/GrainTracker.C [hunk 1]
```diff
@@ -213,7 +221,10 @@ GrainTracker::finalize()
       {
         std::set<dof_id_type>::const_iterator elem_it_end = grain_it->second->entities_ptr->end();
         for (std::set<dof_id_type>::const_iterator elem_it = grain_it->second->entities_ptr->begin(); elem_it != elem_it_end; ++elem_it)
-          _elemental_data[*elem_it].push_back(std::make_pair(grain_it->first, grain_it->second->variable_idx));
+        {
+          mooseAssert(!_ebsd_reader || _unique_grain_to_ebsd_num.find(grain_it->first) != _unique_grain_to_ebsd_num.end(), "Bad mapping in unique_grain_to_ebsd_num");
+          _elemental_data[*elem_it].push_back(std::make_pair(_ebsd_reader ? _unique_grain_to_ebsd_num[grain_it->first] : grain_it->first, grain_it->second->variable_idx));
```
Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/GrainTracker.C]: Are you sure this doesn't do accidental insertion?

Comment (permcody) [inline modules/phase_field/src/postprocessors/GrainTracker.C]: Good question, if it does then something is very wrong. That map is a
lookup of the grain id to the ebsd number. I figured I'd be lazy and just
assert the lookup.
