### PR TITLE
Do not add IC for components if restarting

### LINKED ISSUE #26155: Component initialization of flow areas with ICs triggers the restart+IC check during restart simulations
## Bug Description
Flow channels use an IC, for example a constantIC, to initialize the area. However ICs are banned by default during restart simulations. 
This brings about an error message that can be bypassed by setting a boolean to the problem
This boolean `allow_initial_conditions_with_restart`

## Steps to Reproduce
Do a restart in a simulation with a THM component that has a flow area being initialized with an IC

```
  [core]

    [coolant_channel]
      type = FlowChannel1Phase
```

I m pretty worried that this has only been picked up now after 3 months of ICs being banned during restart simulations. 

## Impact
Inconvenience

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #26155

### CODE REVIEW

File: modules/thermal_hydraulics/src/components/HeatTransferBase.C [hunk 1]
```diff
@@ -139,7 +139,8 @@ HeatTransferBase::addHeatedPerimeter()
       makeFunctionControllableIfConstant(_P_hf_fn_name, "P_hf");
     }
 
-    getTHMProblem().addFunctionIC(_P_hf_name, _P_hf_fn_name, _flow_channel_subdomains);
+    if (!_app.isRestarting())
+      getTHMProblem().addFunctionIC(_P_hf_name, _P_hf_fn_name, _flow_channel_subdomains);
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/HeatTransferBase.C:143]: _P_hf_fn_name is a user parameter right?
I feel we should have a warning if restarting and keeping the IC in the input file

File: modules/thermal_hydraulics/src/components/HeatTransferFromSpecifiedTemperature1Phase.C [hunk 2]
```diff
@@ -33,7 +33,9 @@ HeatTransferFromSpecifiedTemperature1Phase::addVariables()
 {
   HeatTransferFromTemperature1Phase::addVariables();
 
-  getTHMProblem().addFunctionIC(_T_wall_name, _T_wall_fn_name, _flow_channel_subdomains);
+  if (!_app.isRestarting())
+    getTHMProblem().addFunctionIC(_T_wall_name, _T_wall_fn_name, _flow_channel_subdomains);
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/HeatTransferFromSpecifiedTemperature1Phase.C:37]: same for all the non-zero ICs being born from user-input

File: modules/thermal_hydraulics/src/components/HeatTransferBase.C (hunk 1 above)
Comment (joshuahansel) [reply modules/thermal_hydraulics/src/components/HeatTransferBase.C:143]: The function parameter is not just used for the IC but also the aux. Potentially a user could specify a time-dependent function.

File: modules/thermal_hydraulics/src/components/HeatTransferFromSpecifiedTemperature1Phase.C (hunk 2 above)
Comment (joshuahansel) [reply modules/thermal_hydraulics/src/components/HeatTransferFromSpecifiedTemperature1Phase.C:37]: Same comment for T_wall

File: modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i [hunk 3]
```diff
@@ -101,7 +101,6 @@
     n_part_elems = 1
     materials = 'mat1'
     widths = 0.1
-    initial_T = Ts_init
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: we could return warning on passing this during a restart

this is more in line with what you get in a regular MOOSE sim

Comment (joshuahansel) [reply modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: That's probably the right thing to do - maybe we add a parameter `override_restarted_ics` to these components that allow this behavior, `false` by default. And we could make it an error, not a warning.

Comment (joshuahansel) [reply modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: Or `allow_initial_conditions_with_restart` for consistency.

Comment (joshuahansel) [reply modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: Wait nevermind, the error message already occurs if you supply `initial_T`. We were just using `allow_initial_conditions_with_restart = true` in the test before. I'm not sure that anything needs to be done.

Comment (GiudGiud) [reply modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: but does it occur now? because you have an 'if' on isAppRestarting so I would suppose it does not occur anymore, even if we pass inital_T

Comment (joshuahansel) [reply modules/thermal_hydraulics/test/tests/misc/restart_1phase/test.i:104]: I don't know what you mean - if you supply `initial_T`, it attempts to add the IC, which triggers the error at the MOOSE level when you're restarting.

File: modules/thermal_hydraulics/src/components/ShaftConnectedTurbine1Phase.C [hunk 4]
```diff
@@ -145,22 +145,21 @@ ShaftConnectedTurbine1Phase::addVariables()
...
-  getTHMProblem().addConstantScalarIC(_moment_of_inertia_var_name, _inertia_const);
+
+  if (!_app.isRestarting())
+  {
+    getTHMProblem().addConstantScalarIC(_delta_p_var_name, 0);
+    getTHMProblem().addConstantScalarIC(_power_var_name, 0);
+    getTHMProblem().addConstantScalarIC(_driving_torque_var_name, 0);
+    getTHMProblem().addConstantScalarIC(_flow_coeff_var_name, 0);
+    getTHMProblem().addConstantScalarIC(_friction_torque_var_name, 0);
+    getTHMProblem().addConstantScalarIC(_moment_of_inertia_var_name, _inertia_const);
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/ShaftConnectedTurbine1Phase.C:161]: I still think this kind of think is problematic.
If the user passes a new inertia_const when doing their restart, it gets ignored

File: modules/thermal_hydraulics/src/components/HeatTransferFromHeatStructure3D1Phase.C [hunk 5]
```diff
@@ -237,7 +237,9 @@ HeatTransferFromHeatStructure3D1Phase::addVariables()
       false, _P_hf_name, getTHMProblem().getFlowFEType(), _flow_channel_subdomains);
 
   _P_hf_fn_name = getParam<FunctionName>("P_hf");
-  getTHMProblem().addFunctionIC(_P_hf_name, _P_hf_fn_name, _flow_channel_subdomains);
+
+  if (!_app.isRestarting())
+    getTHMProblem().addFunctionIC(_P_hf_name, _P_hf_fn_name, _flow_channel_subdomains);
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/HeatTransferFromHeatStructure3D1Phase.C:242]: I dont see an auxkernel to respect this parameter if it has changed during the restart

File: modules/thermal_hydraulics/src/components/FlowChannelBase.C [hunk 6]
```diff
@@ -228,7 +228,7 @@ FlowChannelBase::addVariables()
   _flow_model->addVariables();
 
   // total heat flux perimeter
-  if (_n_heat_transfer_connections > 1)
+  if (_n_heat_transfer_connections > 1 && !_app.isRestarting())
   {
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/FlowChannelBase.C:232]: ok there's an aux for that one too. all good here

File: modules/thermal_hydraulics/src/components/ShaftConnectedTurbine1Phase.C (hunk 4 above)
Comment (GiudGiud) [reply modules/thermal_hydraulics/src/components/ShaftConnectedTurbine1Phase.C:161]: ah that works

**Review by GiudGiud — APPROVED** [review]
