### PR TITLE
always use growth factor to increase timestep if it is provided

### LINKED ISSUE #17065: FunctionDT timestepper growth factor
## Reason
When the time step is cut in the functionDT timestepper due to a failed solve, the new dt is only multiplied by the growth factor for a single step and then it jumps back up to the timestep given by the function.  If this jump is big, the timestep then fails again and has be cut back a bunch of times until it passes.  It would make more sense to apply the growth factor to the timestep until it reaches the value given by the function.  This makes the function a max timestep size.  If no growth factor is given, the timestep should follow the function and if a timestep cutback occurs with no growth factor, the timestep should jump back up to the function value on the next timestep.

## Design
remove the member variable for cutback_occurred and always apply the growth factor whenever 
local_dt > (_dt * _growth_factor))
The default for growth factor is numeric max so if no growth factor is given, the timestep follows the function. 
This will cause the growth factor to be applied to any abrupt change in the function value if it is larger than the growth factor times the current timestep.  The growth factor will limit the rate that the timestep can grow by, even if the function specifies a higher rate. 
 
## Impact
This changes the behavior of the functionDT timestepper when a growth_factor is supplied.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #17065

### CODE REVIEW

File: framework/src/timesteppers/FunctionDT.C [hunk 1]
```diff
@@ -163,9 +161,8 @@ FunctionDT::computeDT()
   if (local_dt < _min_dt)
     local_dt = _min_dt;
 
-  if (_cutback_occurred && (local_dt > _dt * _growth_factor))
+  if ((local_dt > (_dt * _growth_factor)) && _dt > 0)
```
Comment (lynnmunday) [inline framework/src/timesteppers/FunctionDT.C:164]: If we want this to only effect cut time steps and not limit the rate timestep increase by functions
``` 
if (_cutback_occurred && (local_dt > _dt * _growth_factor))
  local_dt = _dt * _growth_factor;
else {
  _cutback_occurred = false;
}
```

**Comment by lynnmunday** [comment]
@dschwen  will you review this?

**Review by dschwen — APPROVED** [review]
Looks fine
