### PR TITLE
Check whether `_eigen_sys` was cast successfully

### LINKED ISSUE #27286: EigenKernel assumes without testing that it has a MooseEigenSystem available
### Bug Description

When an `EigenKernel` is initialized, it tries to dynamically cast its system to a `MooseEigenSystem`, but it doesn't check if the cast succeeds, and upon failure it ends up dereferencing a null pointer and segfaulting.

### Steps to Reproduce

@maxnezdyur provided this input file:

```
index = 0
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    xmax = 5
    nx = 25
    ny = 5
  []
[]

[Variables]
  [disp_x]
  []
  [disp_y]
  []
[]

[Kernels]
  [sdx]
    type = UpdatedLagrangianStressDivergence
    variable = disp_x
    displacements = 'disp_x disp_y'
    component = 0
  []
  [sdy]
    type = UpdatedLagrangianStressDivergence
    variable = disp_y
    displacements = 'disp_x disp_y'
    component = 1
  []
  [inertia_x]
    type = MassEigenKernel
    variable = disp_x
  []
  [inertia_y]
    type = MassEigenKernel
    variable = disp_y
  []
[]

[BCs]
  [dirichlet_x]
    type = DirichletBC
    variable = disp_x
    value = 0
    preset = false
    boundary = 'left'
  []
  [dirichlet_y]
    type = DirichletBC
    variable = disp_y
    value = 0
    preset = false
    boundary = 'left'
  []

[]

[Materials]
  [elastic_tensor]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 100000.0
    poissons_ratio = 0.25
  []
  [compute_stress]
    type = ComputeLagrangianLinearElasticStress
  []
  [compute_strain]
    type = ComputeLagrangianStrain
    displacements = 'disp_x disp_y'
  []

[]
[Executioner]
  type = Eigenvalue

  solve_type = KRYLOVSCHUR
  which_eigen_pairs = SMALLEST_MAGNITUDE
  eigen_problem_type = non_hermitian
  n_eigen_pairs = 1
  n_basis_vectors = 50
  petsc_options = '-eps_view'
[]

[VectorPostprocessors]
  [eigen]
    type = Eigenvalues
  []
[]

[Problem]
  type = EigenProblem
  active_eigen_index = ${index}
[]

[Outputs]
  console = true
  exodus = true
  csv = true
[] 
```

Which reproduces the problem for me with `combined-dbg -i foo.i`

### Impact

@YaqiWang managed to explain how to fix that input file, but we should be getting some kind of clue from MOOSE itself when something like this goes wrong, not just a segfault.  I'll add one.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by roystgnr**
Maybe @YaqiWang can suggest a better error message here, but this is at least a big step up from a segfault.

Fixes #27286

### CODE REVIEW

File: framework/src/kernels/EigenKernel.C [hunk 1]
```diff
@@ -38,6 +38,9 @@ EigenKernel::EigenKernel(const InputParameters & parameters)
         dynamic_cast<MooseEigenSystem *>(&_fe_problem.getNonlinearSystemBase(_sys.number()))),
     _eigenvalue(NULL)
 {
+  if (!_eigen_sys)
+    mooseError("EigenKernel System is not a MooseEigenSystem.");
```
Comment (YaqiWang) [inline framework/src/kernels/EigenKernel.C:42]:
```suggestion
    mooseError("Eigen kernel ", name(), " requires a MooseEigenSystem and was designed to work with old eigenvalue executioners such as 'NonlinearEigen'.  It is suggested to use the new eigenvalue executioner 'Eigenvalue' along with kernel tagging");
```

Comment (roystgnr) [reply framework/src/kernels/EigenKernel.C]: I had to move the error (didn't think about the case of an EigenKernel with eigen=false in a non-EigenSystem), but I replaced the message with yours.

**Review by lindsayad — APPROVED** [review]
