### PR TITLE
Ensure block-restricted save-in consistent for different proc counts

### LINKED ISSUE #12239: Residual save-in with block-restriction is buggy with MPI
## Rationale

While working on multi-scheme transport in Rattlesnake, I hit a bug and am able to reproduce it with a MOOSE input. The bug shows up with block restricted variables when using save-in.

## Description

I modified an input file like
```
diff --git a/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i b/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
index 4eb06fb2c7..e48883c631 100644
--- a/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
+++ b/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
@@ -41,6 +41,15 @@
   [../]
 []
 
+[AuxVariables]
+  [./ures]
+    block = 0
+  [../]
+  [./vres]
+    block = 1
+  [../]
+[]
+
 [Kernels]
   [./diff_u]
     type = CoeffParamDiffusion
@@ -68,6 +77,8 @@
     neighbor_var = v
     boundary = master0_interface
     penalty = 1e6
+#    save_in = 'ures vres'
+#    save_in_var_side = 'm s'
   [../]
 []
 
@@ -76,11 +87,15 @@
     type = VacuumBC
     variable = u
     boundary = 'left_to_0 bottom_to_0 right top'
+    # this should error out, but not
+    save_in = 'vres'
   [../]
   [./v]
     type = VacuumBC
     variable = v
     boundary = 'left_to_1 bottom_to_1'
+    # this results into behavior change with MPI
+    save_in = 'vres'
   [../]
 []
 
@@ -95,6 +110,16 @@
     variable = v
     block = 1
   [../]
+  [./ures_int]
+    type = ElementIntegralVariablePostprocessor
+    variable = ures
+    block = 0
+  [../]
+  [./vres_int]
+    type = ElementIntegralVariablePostprocessor
+    variable = vres
+    block = 1
+  [../]
 []
```
Initially I thought it is caused by `InterfaceKernel`, but later realized that it is probably related with node visiting with block restriction. I only left the save-in in the boundary condition of `v`, and the integral of the residual with one processor is
```
+----------------+----------------+----------------+----------------+----------------+
| time           | u_int          | ures_int       | v_int          | vres_int       |
+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.398597e+00 |   0.000000e+00 |   7.287195e-01 |   1.646896e-01 |
+----------------+----------------+----------------+----------------+----------------+
```
With two processors
```
+----------------+----------------+----------------+----------------+----------------+
| time           | u_int          | ures_int       | v_int          | vres_int       |
+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.398597e+00 |   0.000000e+00 |   7.287195e-01 |   2.078455e-01 |
+----------------+----------------+----------------+----------------+----------------+
```
You see `vres_int` value changed. Increasing number of processors will cause the value increased further. If you comment out the block restriction of `vres`, the bug will not show up. Another thing is not right is that save-in does not error out when saving into a variable not defined on the block a boundary condition is on.

## Impact
Impact Rattlesnake multi-scheme capability or anybody using the save-in with block restriction.

### PR DESCRIPTION
**Pull request by lindsayad**
This was a pretty interesting bug. One processor owned all the elements
for a subdomain that the save-in variable was restricted to. But we had
a node on a processor boundary that wasn't local to any of the subdomain
elements. Consequently when executing the `AllLocalDofIndicesThread`
with local elements, no process will try to zero that variable's degree
of freedom corresponding to the node on the processor boundary. If we
instead just add all dof indices that are semilocal to the local element
(e.g. all the dof indices attached to the local element) and zero, then
we ensure that we cover this corner case.

Closes #12239

@YaqiWang

### CODE REVIEW

**Review by rwcarlsen — COMMENTED** [review]
Good sleuthing!  My only comment would be that AllDofIndicesThread and AllLocalDofIndicesThread are nearly identical - couldn't their code be consolidated somehow?

**Comment by lindsayad** [comment]
> Good sleuthing! My only comment would be that AllDofIndicesThread and AllLocalDofIndicesThread are nearly identical - couldn't their code be consolidated somehow?

Good point. I just added a default parameter to the `AllLocalDofIndicesThread` for whether to include semilocal dofs

**Comment by aeslaughter** [comment]
This looks fine to me, but I am wondering if you could improve the design a bit while your in there. The purpose is to populate the public _all_dof_indices member in the loop. Can you add a method (e.g., getDofIndices) that provides const & access to the container?

In my quick search through the repo is seems like this container is just used in a few places for looping. It just seems wrong to rely on a public member variable.

**Review by rwcarlsen — DISMISSED** [review]

File: framework/include/loops/AllLocalDofIndicesThread.h [hunk 1]
```diff
@@ -20,28 +20,45 @@ namespace libMesh
...
+  const bool _include_semilocal;
+
   THREAD_ID _tid;
-};
 
+  std::set<dof_id_type> _all_dof_indices;
+
+  /// communicator for performing set unions
+  const TIMPI::Communicator & _communicator;
+};
```
Comment (fdkong) [inline framework/include/loops/AllLocalDofIndicesThread.h:64]: Can this guy derive from `ParallelObject`? It is a bit weird for me that we need a `_communicator` member

File: framework/src/loops/AllLocalDofIndicesThread.C [hunk 2]
```diff
@@ -66,3 +80,9 @@ AllLocalDofIndicesThread::join(const AllLocalDofIndicesThread & y)
 {
   _all_dof_indices.insert(y._all_dof_indices.begin(), y._all_dof_indices.end());
 }
+
+void
+AllLocalDofIndicesThread::dofIndicesSetUnion()
+{
+  _communicator.set_union(_all_dof_indices);
```
Comment (fdkong) [inline framework/src/loops/AllLocalDofIndicesThread.C:87]: Hold on, then we have the whole world?

File: framework/src/systems/NonlinearSystemBase.C [hunk 3]
```diff
@@ -2587,8 +2587,12 @@ NonlinearSystemBase::setVariableGlobalDoFs(const std::string & var_name)
   AllLocalDofIndicesThread aldit(_sys.system(), {var_name});
   ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();
   Threads::parallel_reduce(elem_range, aldit);
-  _communicator.set_union(aldit._all_dof_indices);
-  _var_all_dof_indices.assign(aldit._all_dof_indices.begin(), aldit._all_dof_indices.end());
+
+  // Gather the dof indices across procs to get all the dof indices for var_name
+  aldit.dofIndicesSetUnion();
```
Comment (fdkong) [inline framework/src/systems/NonlinearSystemBase.C:2592]: I am concerned  on this

File: framework/src/postprocessors/GreaterThanLessThanPostprocessor.C [hunk 4]
```diff
@@ -86,13 +86,13 @@ GreaterThanLessThanPostprocessor::execute()
...
   {
-    for (auto dof : aldit._all_dof_indices)
+    for (auto dof : aldit.getDofIndices())
       if (solution(dof) > _value)
         ++_count;
   }
   else if (_comparator == "less")
   {
-    for (auto dof : aldit._all_dof_indices)
+    for (auto dof : aldit.getDofIndices())
```
Comment (fdkong) [inline framework/src/postprocessors/GreaterThanLessThanPostprocessor.C:95]: If `aldit.getDofIndices` is the whole world, why we did not see seg-fault here.

`solution` is serialized?

**Review by fdkong — CHANGES_REQUESTED** [review]
Hopefull my understanding was wrong. I am concerned about that global communication union

File: framework/src/systems/NonlinearSystemBase.C (hunk 3 above)
Comment (lindsayad) [reply framework/src/systems/NonlinearSystemBase.C:2592]: The name of this method is `setVariableGlobalDoFs`. Sounds like a global operation to me. Look at the deleted lines. We were already doing a set union before. Now it's just encapsulated. This is the only place we do global communication. All the other `getDofIndices` calls are for local dofs only, e.g. we do not perform a global set union like we do here.

File: framework/src/postprocessors/GreaterThanLessThanPostprocessor.C (hunk 4 above)
Comment (lindsayad) [reply framework/src/postprocessors/GreaterThanLessThanPostprocessor.C:95]: It's not the whole world. It's only local dofs. We did not call `dofIndicesSetUnion`

File: framework/src/loops/AllLocalDofIndicesThread.C (hunk 2 above)
Comment (lindsayad) [reply framework/src/loops/AllLocalDofIndicesThread.C:87]: Yep, when we want to.

File: framework/include/loops/AllLocalDofIndicesThread.h (hunk 1 above)
Comment (lindsayad) [reply framework/include/loops/AllLocalDofIndicesThread.h:64]: Sure

File: framework/src/systems/NonlinearSystemBase.C (hunk 3 above)
Comment (fdkong) [reply framework/src/systems/NonlinearSystemBase.C:2592]: OK, the code is called from here:

```
  if (_requires_nonlocal_coupling)
    setVariableAllDoFMap(_uo_jacobian_moose_vars[0]);
```

It may be fine as long as `_requires_nonlocal_coupling=false`.

Comment (lindsayad) [reply framework/src/systems/NonlinearSystemBase.C:2592]: It is false almost all the time. I think virtually none of our users are using the non-local capability.

But this does beg the question of whether we could build up the global dof indices for a variable without doing communication.

**Comment by lindsayad** [comment]
@fdkong I inherit from ParallelObject now. Does it look good?

**Review by fdkong — APPROVED** [review]
