### PR TITLE
Change default values of three problem parameters

### LINKED ISSUE #22729: Adding [Problem] input block in STM main input can cause error
## Reason
I tried to add command-line argument `Problem/verbose_multiapps=true` for running a STM calculation and hit an error. Looks like adding this parameter makes MOOSE to add a `CreateProblemAction` but the action does not have `solve`, `kernel_coverage_check` and `skip_nl_system_check` parameters set required by the STM main input.

## Design
My suggestion is that when `_awh.hasActions("create_problem")` is true, `StochasticToolsAction` obtain the `CreateProblemAction` and its parameters and change the value of the three parameters, i.e. essentially change their default values.

## Impact
Avoid unexpected behavior.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #22729.

### CODE REVIEW

File: modules/stochastic_tools/src/actions/StochasticToolsAction.C [hunk 1]
```diff
@@ -65,24 +66,62 @@ StochasticToolsAction::act()
...
-    // Create the action
-    auto action = std::static_pointer_cast<MooseObjectAction>(
-        _action_factory.create("CreateProblemAction", "Problem", action_params));
+        if (params.isParamSetByUser("solve"))
+        {
+          if (params.get<bool>("solve"))
+            mooseError("Problem/solve parameter cannot be set to true for STM main input file.");
+        }
+        else
+          params.set<bool>("solve") = false;
```
Comment (zachmprince) [inline modules/stochastic_tools/src/actions/StochasticToolsAction.C:87]: Don't throw an error. The user most likely know exactly what they are doing if this is set.
```suggestion
        if (!params.isParamSetByUser("solve"))
          params.set<bool>("solve") = false;
```

File: modules/stochastic_tools/src/actions/StochasticToolsAction.C [hunk 2]
```diff
@@ -65,24 +66,62 @@ StochasticToolsAction::act()
...
-    params.set<bool>("kernel_coverage_check") = false;
-    params.set<bool>("skip_nl_system_check") = true;
+        if (params.isParamSetByUser("kernel_coverage_check"))
+        {
+          if (params.get<bool>("kernel_coverage_check"))
+            mooseError("Problem/kernel_coverage_check parameter cannot be set to true for STM main "
+                       "input file.");
+        }
+        else
+          params.set<bool>("kernel_coverage_check") = false;
```
Comment (zachmprince) [inline modules/stochastic_tools/src/actions/StochasticToolsAction.C:96]: Same here
```suggestion
        if (!params.isParamSetByUser("kernel_coverage_check"))
          params.set<bool>("kernel_coverage_check") = false;
```

File: modules/stochastic_tools/src/actions/StochasticToolsAction.C [hunk 3]
```diff
@@ -65,24 +66,62 @@ StochasticToolsAction::act()
...
 
-    // Add Action to the warehouse
-    _awh.addActionBlock(action);
+        if (params.isParamSetByUser("skip_nl_system_check"))
+        {
+          if (!params.get<bool>("skip_nl_system_check"))
+            mooseError("Problem/solve parameter cannot be set to false for STM main input file.");
+        }
+        else
+          params.set<bool>("skip_nl_system_check") = true;
```
Comment (zachmprince) [inline modules/stochastic_tools/src/actions/StochasticToolsAction.C:104]: And here
```suggestion
        if (!params.isParamSetByUser("skip_nl_system_check"))
          params.set<bool>("skip_nl_system_check") = true;
```

File: modules/stochastic_tools/src/actions/StochasticToolsAction.C [hunk 4]
```diff
@@ -65,24 +66,62 @@ StochasticToolsAction::act()
...
-    // Build the Action parameters
-    InputParameters action_params = _action_factory.getValidParams("CreateProblemAction");
+    if (_awh.hasActions("create_problem"))
+    {
+      const auto & actions = _awh.getActionListByName("create_problem");
+      for (const auto & act : actions)
+      {
+        CreateProblemAction * p = dynamic_cast<CreateProblemAction *>(act);
+        if (!p)
+          continue;
```
Comment (zachmprince) [inline modules/stochastic_tools/src/actions/StochasticToolsAction.C:78]: Pretty sure this can be done more simply:
```suggestion
      for (auto & act : _awh.getActions<CreateProblemAction>())
```

**Review by zachmprince — CHANGES_REQUESTED** [review]
Nice fix.

File: modules/stochastic_tools/src/actions/StochasticToolsAction.C (hunk 4 above)
Comment (YaqiWang) [reply modules/stochastic_tools/src/actions/StochasticToolsAction.C:78]: Yeah, the issue is that `getObjectParams()` is a non-const function and `act` here is a const pointer.

**Review by zachmprince — APPROVED** [review]
