### PR TITLE
Fixed Residual post-processor for nonlinear Eigenvalue problems

### LINKED ISSUE #32506: Residual postprocessor does not work with EigenProblem
### Motivation

`Residual` postprocessor is used to report the nonlinear residual of a problem, but currently it does not report the residual properly for an `EigenProblem`, which is created when the executioner type is `Eigenvalue`.

### Design

Residual is evaluated in `EigenProblem`, so we will just need to improve `Residual` to make it properly interface with `EigenProblem`.

### Impact

An improved functionality to make `Residual` postprocessor work with eigenvalue problems.

### PR DESCRIPTION
**Pull request by joshuahansel**
This PR makes `Residual` post-processor  work for `Eigenvalue` executioner with nonlinear solve types. For other types, an error is thrown if someone tries to get the nonlinear residual.

This is similar to the work in https://github.com/idaholab/moose/pull/32513, and note that a merge conflict will be present after that one is merged.

Closes #32506

### CODE REVIEW

File: test/tests/postprocessors/residual/tests [hunk 1]
```diff
@@ -14,4 +14,16 @@
...
   []
+  [eigen_problem]
+    type = CSVDiff
+    input = 'eigen_problem.i'
+    csvdiff = 'eigen_problem_out.csv'
+    # Since we test a nonlinear residual instead of a tightly converged solution, we
+    # restrict to 1 process for consistency and furthermore use a loose tolerance;
+    # this test does not care about the residual value itself but just that a nonzero
+    # value is returned.
+    max_parallel = 1
```
Comment (GiudGiud) [inline test/tests/postprocessors/residual/tests:25]: @lindsayad should not see this

**Review by GiudGiud — APPROVED** [review]

File: framework/src/systems/NonlinearEigenSystem.C [hunk 2]
```diff
@@ -296,6 +305,15 @@ NonlinearEigenSystem::solve()
     solution().restore_subvector(std::move(subvec), _eigen_sys.local_non_condensed_dofs_vector);
 }
 
+Real
+NonlinearEigenSystem::finalNonlinearResidual() const const
```
Comment (GiudGiud) [inline framework/src/systems/NonlinearEigenSystem.C]:
```suggestion
NonlinearEigenSystem::finalNonlinearResidual() const
```

File: test/tests/postprocessors/residual/tests (hunk 1 above)
Comment (GiudGiud) [reply test/tests/postprocessors/residual/tests:25]: (jk, we should be fine here with rel_err = 1, we d need the solve to be 2x as bad to start diffing)

Comment (joshuahansel) [reply test/tests/postprocessors/residual/tests:25]: It makes it hard when you tag him 😆 I don't know that it's actually needed, so I could try removing it. Alex please let me know if you prefer a different practice in this situation (testing a residual norm).

File: framework/src/systems/NonlinearEigenSystem.C (hunk 2 above)
Comment (joshuahansel) [reply framework/src/systems/NonlinearEigenSystem.C]: wow such const

**Comment by smpark7** [comment]
Thanks for tackling this issue! Would be it possible to extend this to other `residual_type`s supported by `Residual`, e.g. initial, current, compute? And/or perhaps add a warning or error for types that don't make sense in EigenProblems?

**Comment by joshuahansel** [comment]
> Thanks for tackling this issue! Would be it possible to extend this to other `residual_type`s supported by `Residual`, e.g. initial, current, compute? And/or perhaps add a warning or error for types that don't make sense in EigenProblems?

Yes, I can look into that. I did the quick-and-dirty for now to try and deliver some kind of option to you (wasn't sure what your urgency was). But I definitely should test the other options.

**Comment by smpark7** [comment]
It's not a critical blocker for my work so feel free to do as you see fit

**Review by GiudGiud — APPROVED** [review]

**Comment by joshuahansel** [comment]
Merged this but reopening https://github.com/idaholab/moose/issues/32506 with the suggested follow-up tasks.
