### PR TITLE
Properly prefix multiple systems

### LINKED ISSUE #29951: Preconditioner wrong for forward and adjoint multiple nonlinear systems
### Bug Description

The following PR introduced some changes to multiple nonlinear systems that don't work correctly with the SteadyAndAdjoint multiple nonlinear system that the optimization module uses:
[https://github.com/idaholab/moose/commit/08c5990288ae1f444af3ad534f41150629bb92d8#diff-345a4bacb5a625fa51738a7e1a[…]457e87b1f4620fd034900b01ad1a829b](https://github.com/idaholab/moose/commit/08c5990288ae1f444af3ad534f41150629bb92d8#diff-345a4bacb5a625fa51738a7e1a86636a457e87b1f4620fd034900b01ad1a829b)

The change in [AdjointSolve.C](https://github.com/idaholab/moose/commit/08c5990288ae1f444af3ad534f41150629bb92d8#diff-345a4bacb5a625fa51738a7e1a86636a457e87b1f4620fd034900b01ad1a829b) results in the adjoint nl system no longer copying the forward system preconditioner.  It is also not outputting the adjoint system options using the ```petsc_option -adjoint_ksp_view``` used in the test

It outputs the forward system options with ```petsc_option -nl0_ksp_view``` and this system uses an lu preconditioner as specified in the input file.  

The adjoint system does get output with ```petsc_option -ksp_view``` .  This system that it outputs does not have the name "adjoint", it has no name but I know its the adjoint system because it follows for the forward nl system.  The adjoitn system is also using an ilu preconditioner when it should be using the same lu preconditioner specified for the forward system.  It is also not using the LU preconditioner specified for the adjoint system from the input file.  

### Steps to Reproduce

You can reproduce this behavior in this directory:
moose/modules/optimization/test/tests/optimizationreporter/point_loads
With this:
../../../../optimization-opt -i main_auto_adjoint.i -nl0_ksp_view -ksp_view

There is a test in this directory to check that the adjoint system is not ILU but the adjoint preconditioner info is no longer being output with -adjoint_ksp_view so the test passes.

I can set the forward and adjoint preconditioner to LU if I use the command line option:
../../../../optimization-opt -i main_auto_adjoint.i -pc_type lu

### Impact

The adjoint system needs to use LU because it is sensitive to round off error.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #29951

### CODE REVIEW

**Comment by lindsayad** [comment]
Must wait on https://github.com/idaholab/moose/pull/29817

**Comment by lynnmunday** [comment]
I'll check this as soon as conda gets the libmesh update.

**Comment by lindsayad** [comment]
Sorry @lynnmunday, #29817 didn't end up including the prefix PR. But https://github.com/idaholab/moose/pull/30042 will

File: modules/contact/src/userobjects/WeightedGapUserObject.C [hunk 1]
```diff
@@ -126,8 +126,10 @@ WeightedGapUserObject::computeQpIProperties()
   // Get the _dof_to_weighted_gap map
   const auto * const dof = static_cast<const DofObject *>(_lower_secondary_elem->node_ptr(_i));
 
-  _dof_to_weighted_gap[dof].first += (*_test)[_i][_qp] * _qp_gap_nodal * _normals[_i];
-  _dof_to_weighted_gap[dof].second += (*_test)[_i][_qp] * _qp_factor;
+  auto & [weighted_gap, normalization] = _dof_to_weighted_gap[dof];
+
+  weighted_gap += (*_test)[_i][_qp] * _qp_gap_nodal * _normals[_i];
+  normalization += (*_test)[_i][_qp] * _qp_factor;
```
Comment (maxnezdyur) [inline modules/contact/src/userobjects/WeightedGapUserObject.C:132]: I'm assuming this shouldn't be in this PR?

File: modules/optimization/test/tests/optimizationreporter/point_loads/tests [hunk 2]
```diff
@@ -59,7 +59,7 @@
       type = CSVDiff
       input = main_auto_adjoint.i
       absent_out = 'type: ilu'
-      cli_args = 'Outputs/file_base=main_out -nl0_ksp_view -adjoint_ksp_view'
+      cli_args = 'Outputs/file_base=main_out -nl0_ksp_view -adjoint_ksp_view -ksp_view'
```
Comment (maxnezdyur) [inline modules/optimization/test/tests/optimizationreporter/point_loads/tests:62]: Can you add a comment above this making sure that -ksp_view is not removed. The reason this came undetected is that -ksp_view was taken out of the test during a PR.

**Review by maxnezdyur — APPROVED** [review]
Thanks for the fix. Looks good, just had a few minor comments.

File: modules/optimization/test/tests/optimizationreporter/point_loads/tests (hunk 2 above)
Comment (lynnmunday) [reply modules/optimization/test/tests/optimizationreporter/point_loads/tests:62]: I created this issue https://github.com/idaholab/moose/issues/30188 for us to add a test to verify that nondefault input file preconditioners are being used for each system.  So I approve of everything in the current PR.

File: modules/contact/src/userobjects/WeightedGapUserObject.C (hunk 1 above)
Comment (lindsayad) [reply modules/contact/src/userobjects/WeightedGapUserObject.C:132]: Can't I sneak in a rider commit especially with someone familiar with contact? 😄

Comment (maxnezdyur) [reply modules/contact/src/userobjects/WeightedGapUserObject.C:132]: Yup, this makes it so much more readable anyway!

**Review by lynnmunday — APPROVED** [review]
Max checked the output and it is correct

**Comment by GiudGiud** [comment]
I ll take a look tomorrow

**Review by GiudGiud — APPROVED** [review]

**Comment by grmnptr** [comment]
[b8db7e7](https://github.com/idaholab/moose/pull/29964/commits/b8db7e720ac322198d30781b3dfa4b98f727821a) broke the validation cases in the flow test bed. I assume due to the high numerical diffusivity in the regression test, this didn't show up on the PR. I will probably look into this.

**Comment by grmnptr** [comment]
The analysis is based on git bisect, I can't see immediately how this could break the segregated solvers which set the options directly in the executioner.

**Comment by maxnezdyur** [comment]
If you use -ksp_view you can make sure that before and after that there is no change is solver settings.

**Comment by grmnptr** [comment]
Yeah, the segregated solvers have a different logic for setting the parameters. They didn't rely on the prefix at all. I'll run the checks on ksp.

**Comment by lindsayad** [comment]
This is why we really need to get automated testing for the flow test bed

**Comment by grmnptr** [comment]
> This is why we really need to get automated testing for the flow test bed

I am on it, should be up by next week.

Before:
```
Execution Information:
  Executioner:             SIMPLENonlinearAssembly
  Solver Mode - system 0:  Preconditioned JFNK
  Solver Mode - system 1:  Preconditioned JFNK
  Solver Mode - system 2:  Preconditioned JFNK
  Solver Mode - system 3:  Preconditioned JFNK
  Solver Mode - system 4:  Preconditioned JFNK
KSP Object: 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=4.68319e-16, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=1e-26, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=3.16868e-17, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
Iteration 1 Initial residual norms:
 Momentum equation: Component 1 1
 Momentum equation: Component 2 1.7272e-11
 Pressure equation: 1
Turbulence Iteration 
TKED_system 0.999932
TKE_system 1
```

After:
```
Execution Information:
  Executioner:             SIMPLENonlinearAssembly
  Solver Mode - system 0:  Preconditioned JFNK
  Solver Mode - system 1:  Preconditioned JFNK
  Solver Mode - system 2:  Preconditioned JFNK
  Solver Mode - system 3:  Preconditioned JFNK
  Solver Mode - system 4:  Preconditioned JFNK

Iteration 1 Initial residual norms:
 Momentum equation: Component 1 1
 Momentum equation: Component 2 1.7272e-11
 Pressure equation: 1
Turbulence Iteration 
TKED_system 0.999932
TKE_system 1
```

After if I actually use the right prefix in the parameters for the `ksp_view`:
```
Execution Information:
  Executioner:             SIMPLENonlinearAssembly
  Solver Mode - system 0:  Preconditioned JFNK
  Solver Mode - system 1:  Preconditioned JFNK
  Solver Mode - system 2:  Preconditioned JFNK
  Solver Mode - system 3:  Preconditioned JFNK
  Solver Mode - system 4:  Preconditioned JFNK

KSP Object: (u_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=4.68319e-16, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (u_system_) 20 MPI processes
  type: bjacobi
    number of blocks = 20
    Local solver information for first block is in the following KSP and PC objects on rank 0:
    Use -u_system_ksp_view ::ascii_info_detail to display information for all blocks
    KSP Object: (u_system_sub_) 1 MPI process
      type: preonly
      maximum iterations=10000, initial guess is zero
      tolerances: relative=1e-05, absolute=1e-50, divergence=10000.
      left preconditioning
      using NONE norm type for convergence test
    PC Object: (u_system_sub_) 1 MPI process
      type: ilu
        out-of-place factorization
        0 levels of fill
        tolerance for zero pivot 2.22045e-14
        matrix ordering: natural
        factor fill ratio given 1., needed 1.
          Factored matrix follows:
            Mat Object: (u_system_sub_) 1 MPI process
              type: seqaij
              rows=925, cols=925
              package used to perform factorization: petsc
              total: nonzeros=11409, allocated nonzeros=11409
                not using I-node routines
      linear system matrix = precond matrix:
      Mat Object: (u_system_sub_) 1 MPI process
        type: seqaij
        rows=925, cols=925
        total: nonzeros=11409, allocated nonzeros=11409
        total number of mallocs used during MatSetValues calls=0
          not using I-node routines
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: (v_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=1e-26, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (v_system_) 20 MPI processes
  type: bjacobi
    number of blocks = 20
    Local solver information for first block is in the following KSP and PC objects on rank 0:
    Use -v_system_ksp_view ::ascii_info_detail to display information for all blocks
    KSP Object: (v_system_sub_) 1 MPI process
      type: preonly
      maximum iterations=10000, initial guess is zero
      tolerances: relative=1e-05, absolute=1e-50, divergence=10000.
      left preconditioning
      using NONE norm type for convergence test
    PC Object: (v_system_sub_) 1 MPI process
      type: ilu
        out-of-place factorization
        0 levels of fill
        tolerance for zero pivot 2.22045e-14
        matrix ordering: natural
        factor fill ratio given 1., needed 1.
          Factored matrix follows:
            Mat Object: (v_system_sub_) 1 MPI process
              type: seqaij
              rows=925, cols=925
              package used to perform factorization: petsc
              total: nonzeros=11409, allocated nonzeros=11409
                not using I-node routines
      linear system matrix = precond matrix:
      Mat Object: (v_system_sub_) 1 MPI process
        type: seqaij
        rows=925, cols=925
        total: nonzeros=11409, allocated nonzeros=11409
        total number of mallocs used during MatSetValues calls=0
          not using I-node routines
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: (pressure_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=3.16868e-17, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (pressure_system_) 20 MPI processes
  type: bjacobi
    number of blocks = 20
    Local solver information for first block is in the following KSP and PC objects on rank 0:
    Use -pressure_system_ksp_view ::ascii_info_detail to display information for all blocks
    KSP Object: (pressure_system_sub_) 1 MPI process
      type: preonly
      maximum iterations=10000, initial guess is zero
      tolerances: relative=1e-05, absolute=1e-50, divergence=10000.
      left preconditioning
      using NONE norm type for convergence test
    PC Object: (pressure_system_sub_) 1 MPI process
      type: ilu
        out-of-place factorization
        0 levels of fill
        tolerance for zero pivot 2.22045e-14
        matrix ordering: natural
        factor fill ratio given 1., needed 1.
          Factored matrix follows:
            Mat Object: (pressure_system_sub_) 1 MPI process
              type: seqaij
              rows=925, cols=925
              package used to perform factorization: petsc
              total: nonzeros=11409, allocated nonzeros=11409
                not using I-node routines
      linear system matrix = precond matrix:
      Mat Object: (pressure_system_sub_) 1 MPI process
        type: seqaij
        rows=925, cols=925
        total: nonzeros=11409, allocated nonzeros=11409
        total number of mallocs used during MatSetValues calls=0
          not using I-node routines
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
Iteration 1 Initial residual norms:
 Momentum equation: Component 1 1
 Momentum equation: Component 2 1.7272e-11
 Pressure equation: 1
Turbulence Iteration 
TKED_system 0.999932
TKE_system 1
```

After I use the correct prefix everywhere:
```
Execution Information:
  Executioner:             SIMPLENonlinearAssembly
  Solver Mode - system 0:  Preconditioned JFNK
  Solver Mode - system 1:  Preconditioned JFNK
  Solver Mode - system 2:  Preconditioned JFNK
  Solver Mode - system 3:  Preconditioned JFNK
  Solver Mode - system 4:  Preconditioned JFNK

KSP Object: (u_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=4.68319e-16, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (u_system_) 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: (v_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=1e-26, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (v_system_) 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
KSP Object: (pressure_system_) 20 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=30, nonzero initial guess
  tolerances: relative=0., absolute=3.16868e-17, divergence=10000.
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: (pressure_system_) 20 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type V
      Maximum number of levels 25
      Maximum number of iterations PER hypre call 1
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         1
      Sweeps up           1
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Maximum size of coarsest grid 9
      Minimum size of coarsest grid 1
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
      SpGEMM type         hypre
  linear system matrix = precond matrix:
  Mat Object: () 20 MPI processes
    type: mpiaij
    rows=18000, cols=18000
    total: nonzeros=230784, allocated nonzeros=230784
    total number of mallocs used during MatSetValues calls=0
      not using I-node (on process 0) routines
Iteration 1 Initial residual norms:
 Momentum equation: Component 1 1
 Momentum equation: Component 2 1.7272e-11
 Pressure equation: 1
Turbulence Iteration 
TKED_system 0.999932
TKE_system 1
```

**Comment by grmnptr** [comment]
If I switch the input parameters in our input from:
```
  momentum_petsc_options_iname = '-pc_type -pc_hypre_type'
  momentum_petsc_options_value = 'hypre boomeramg'
  pressure_petsc_options_iname = '-pc_type -pc_hypre_type'
  pressure_petsc_options_value = 'hypre boomeramg'
```
to this:
```
  momentum_petsc_options_iname = '-u_system_pc_type -u_system_pc_hypre_type -v_system_pc_type -v_system_pc_hypre_type'
  momentum_petsc_options_value = 'hypre boomeramg hypre boomeramg'
  pressure_petsc_options_iname = '-pressure_system_pc_type -pressure_system_pc_hypre_type'
  pressure_petsc_options_value = 'hypre boomeramg'
```
I suppose for the time being it works, I'll check a few options to get the old behavior back.

**Comment by lindsayad** [comment]
It was my intention to keep the existing behavior for the NS segregated solvers, but clearly that went amok somewhere. Sorry about this @grmnptr !
