### PR TITLE
Error out on invalid vals in ParsedFunction

### LINKED ISSUE #14169: ParsedFunction has difficult errors
## Reason
If a bad `vals` is used by `ParsedFunction` (e.g. incorrect scalar, function or postprocessor name), then a very difficult to understand error is thrown, with both `opt` and `dbg`.
```
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

## Design
There should be an error check to make sure the scalar/function/postprocessor exists.
This can be tested by running
```
../../../moose_test-opt -i combined.i Functions/fn/vals='sv cos_fn pp'
```
in `moose/test/tests/functions/parsed`

And changing `sv`, `cos_fn`, or `pp` to any other value.

## Impact
This will help debugging inputs a bit better.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #14169

### CODE REVIEW

File: framework/src/functions/MooseParsedFunctionWrapper.C [hunk 1]
```diff
@@ -121,7 +121,18 @@ MooseParsedFunctionWrapper::initialize()
     // Case when a Real is supplied
     else
     {
-      Real val = MooseUtils::convert<Real>(_vals_input[i], true);
+      Real val;
+      try
+      {
```
Comment (tophmatthews) [inline framework/src/functions/MooseParsedFunctionWrapper.C]: does it need {} with try/catch?

File: framework/src/functions/MooseParsedFunctionWrapper.C [hunk 2]
```diff
@@ -121,7 +121,18 @@ MooseParsedFunctionWrapper::initialize()
...
+        val = MooseUtils::convert<Real>(_vals_input[i], true);
+      }
+      catch (std::exception & e)
+      {
+        mooseError("No postprocessor, scalar variable, or function with the name '",
```
Comment (tophmatthews) [inline framework/src/functions/MooseParsedFunctionWrapper.C]: Can you add the function block name so its obvious?
```
mooseError("In ", _name, ": blah blah...")
```

File: framework/src/functions/MooseParsedFunctionWrapper.C (hunk 1 above)
Comment (dschwen) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: Yes!

File: test/tests/functions/parsed/vals_error.i [hunk 3]
```diff
@@ -0,0 +1,29 @@
+[Mesh]
+  type = GeneratedMesh
+  dim = 2
+  nx = 10
```
Comment (tophmatthews) [inline test/tests/functions/parsed/vals_error.i]: does it need nx = 10/ ny=10 at all? dim = 1?

File: framework/src/functions/MooseParsedFunctionWrapper.C (hunk 2 above)
Comment (dschwen) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: Actually in the wrapper class I don't have access to the name.

File: test/tests/functions/parsed/vals_error.i [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+[Problem]
+  kernel_coverage_check = false
+[]
+
+[Functions]
+  [./left_bc]
+    type = ParsedFunction
+    value = s
+    vals = invalid
+    vars = s
```
Comment (tophmatthews) [inline test/tests/functions/parsed/vals_error.i]: Obviously small...but `vars=dummy` or something like that might make more sense?

File: framework/src/functions/MooseParsedFunctionWrapper.C (hunk 2 above)
Comment (dschwen) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: Passing in the name would require an API change. Let me see how much that would break...

File: test/tests/functions/parsed/vals_error.i [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+  [../]
+[]
+
+[Executioner]
+  type = Transient
+  num_steps = 1
```
Comment (tophmatthews) [inline test/tests/functions/parsed/vals_error.i]: necessary?

**Review by tophmatthews — DISMISSED** [review]
nice! small questions only for trying to make a minimal input file.

File: framework/src/functions/MooseParsedFunctionWrapper.C (hunk 2 above)
Comment (tophmatthews) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: Well, at least it errors now...but sometimes it's a pain to find where it errors. It'd be nice to make it as easy as possible. Maybe you could just print the equation/value?

Comment (dschwen) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: I could catch the exception higher up, but then I don't have the vals item name...
Catch and rethrow with a modified message would work. But this is becoming ugly...

Comment (tophmatthews) [reply framework/src/functions/MooseParsedFunctionWrapper.C]: It's probably fine since you print out the offending name

**Review by tophmatthews — COMMENTED** [review]
🤘

File: test/tests/functions/parsed/tests [hunk 6]
```diff
@@ -52,4 +52,11 @@
     requirement = "The Function system shall support the creation of objects that execute a curl of a vector function defined within the input file."
     issues = '#13041'
   [../]
+
+  [./vals_error]
+    type = 'RunException'
+    input = 'vals_error.i'
+    expect_err = 'No postprocessor, scalar variable, or function with the name \'invalid\' found. Unable to convert \'invalid\' to type double'
+    requirement = "The ParsedFunction object shall fail with a human readable error if a vals entry is supplied that is neither a valid postprocessor, scalar variable, function, or real number."
```
Comment (tophmatthews) [inline test/tests/functions/parsed/tests]: `human readable` --> `topher readable, cause he makes too many damn input file mistakes,`

Comment (dschwen) [reply test/tests/functions/parsed/tests]: I'd hope `topher` counts as a subset of `human`...

Comment (tophmatthews) [reply test/tests/functions/parsed/tests]: 🤷‍♂

**Review by permcody — APPROVED** [review]
