### PR TITLE
Various mixture-related fluid properties improvements

### LINKED ISSUE #29656: Fluid properties interrogator does not report invalid properties combination for corner case
### Bug Description

When `FluidPropertiesInterrogator` is used with a `VaporMixtureFluidProperties` and a user provides `p` and `T` only, it does not report that this is an invalid combination, just gets to obscure error.

### Steps to Reproduce

See above.

### Impact

Time waste and confusion for users.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by joshuahansel**
This PR does the following, in support of the upcoming THM gas mixture flow channel:

- Added default implementations for `SinglePhaseFluidProperties::criticalDensity()` and `criticalInternalEnergy()` by evaluating respective methods with `criticalPressure()` and `criticalTemperature()`.
- Closes #29656
- Stopped outputting vapor mixture properties twice in `FluidPropertiesInterrogator`
- Added debug information to the solve-failed exception in `BrentsMethod` (iteration history)
- Added `REL_ABS_TEST` macro to `FluidPropertiesTestUtils`
- Added s(p,T) to `VaporMixtureFluidProperties` and interrogator
- Cleaned `IdealRealGasMixtureFluidProperties` and overhauled its testing

Note that I will not be using `IdealRealGasMixtureFluidProperties` in my upcoming gas mixture flow model - I'll have another PR with a simplified class: `IdealGasMixtureFluidProperties`, which assumes ideal gases. I'm sorry for the excessive cleanup commit.

### CODE REVIEW

File: modules/fluid_properties/src/utils/BrentsMethod.C [hunk 1]
```diff
@@ -34,8 +34,11 @@ bracket(std::function<Real(Real)> const & f, Real & x1, Real & x2)
   if (f1 * f2 > 0.0)
   {
     unsigned int iter = 0;
+    std::stringstream debug_ss;
     while (f1 * f2 > 0.0)
     {
+      debug_ss << "  iteration " << iter << ": (x1,x2) = (" << x1 << "," << x2 << "), (f1,f2) = ("
```
Comment (GiudGiud) [inline modules/fluid_properties/src/utils/BrentsMethod.C:40]: that's got to be slow.

maybe only do it in devel
```suggestion
#ifdef DEBUG
      debug_ss << "  iteration " << iter << ": (x1,x2) = (" << x1 << "," << x2 << "), (f1,f2) = ("
```

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 2]
```diff
@@ -14,8 +14,224 @@
...
+                                                           Real T,                                 \
+                                                           const std::vector<Real> & x,            \
+                                                           Real & y,                               \
+                                                           Real & dy_dp,                           \
+                                                           Real & dy_dT,                           \
+                                                           std::vector<Real> & dy_dx) const        \
+  {                                                                                                \
+    Real v, dv_dp, dv_dT;                                                                          \
+    std::vector<Real> dv_dx;                                                                       \
+    v_from_p_T(p, T, x, v, dv_dp, dv_dT, dv_dx);                                                   \
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:74]:
```suggestion
    v_from_p_T(p, T, x, v, dv_dp_T, dv_dT_p, dv_dx_pT);                                                   \
```

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 3]
```diff
@@ -14,8 +14,224 @@
...
+                                                           Real e,                                 \
+                                                           const std::vector<Real> & x,            \
+                                                           Real & y,                               \
+                                                           Real & dy_dv,                           \
+                                                           Real & dy_de,                           \
+                                                           std::vector<Real> & dy_dx) const        \
+  {                                                                                                \
+    Real T, dT_dv, dT_de;                                                                          \
+    std::vector<Real> dT_dx(_n_secondary_vapors);                                                  \
+    T_from_v_e(v, e, x, T, dT_dv, dT_de, dT_dx);                                                   \
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:39]: not sure we need that. it helps re-deriving it though

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 4]
```diff
@@ -14,8 +14,224 @@
...
+                                                                                                   \
+    dy_dv = dy_dv_T + dy_dT_v * dT_dv;                                                             \
+    dy_de = dy_dT_v * dT_de;                                                                       \
+    dy_dx.resize(_n_secondary_vapors);                                                             \
+    for (unsigned int i = 0; i < _n_secondary_vapors; i++)                                         \
+      dy_dx[i] = dy_dx_Tv[i] + dy_dT_v * dT_dx[i];                                                 \
+  }
+
+/**
+ * Defines the value and derivative methods from (p,T) for a property y
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:53]: this is pretty general. it does not have to be an IdealRealGas right? or is the lack of interaction between phase the definition of "IdealReal:" ?

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 5]
```diff
@@ -14,8 +14,224 @@
...
+    return y;                                                                                      \
+  }                                                                                                \
+                                                                                                   \
+  void IdealRealGasMixtureFluidProperties::prop##_from_T_v(Real T,                                 \
+                                                           Real v,                                 \
+                                                           const std::vector<Real> & x,            \
+                                                           Real & y,                               \
+                                                           Real & dy_dT,                           \
+                                                           Real & dy_dv,                           \
+                                                           std::vector<Real> & dy_dx) const        \
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:109]: do we ever care about dy_dxprimary?

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 6]
```diff
@@ -14,8 +14,224 @@
...
+  {                                                                                                \
+    const Real x_primary = primaryMassFraction(x);                                                 \
+                                                                                                   \
+    Real y_primary, dy_dT_primary, dy_dv_primary;                                                  \
+    _fp_primary->prop##_from_T_v(T, v / x_primary, y_primary, dy_dT_primary, dy_dv_primary);       \
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:114]: I dont have good insights on this. If x is tiny, v/x is huge which means very low pressure. wouldnt we bring fp_primary out of bounds easily that way?

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 7]
```diff
@@ -14,8 +14,224 @@
...
+                                                                                                   \
+    dy_dx.resize(_n_secondary_vapors);                                                             \
+    for (unsigned int i = 0; i < _n_secondary_vapors; i++)                                         \
+    {                                                                                              \
+      dy_dx[i] = y_sec[i] - x[i] * dy_dv_sec[i] * v / (x[i] * x[i]);                               \
+      for (unsigned int j = 0; j < _n_secondary_vapors; j++)                                       \
+      {                                                                                            \
+        if (j == i)                                                                                \
+          continue;                                                                                \
+        const Real dxj_dxi = -x[j] / (1. - x[i]);                                                  \
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:137]: so xj = 1 -xi - other things (roughly)
so dxj / dxi = -1 ?

how did you get that

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 8]
```diff
@@ -14,8 +14,224 @@
...
+    }                                                                                              \
+                                                                                                   \
+    for (unsigned int i = 0; i < _n_secondary_vapors; i++)                                         \
+    {                                                                                              \
+      const Real Mi = _fp_secondary[i]->molarMass();                                               \
+      dy_dx[i] += -M_star * M_star * (1 / Mi - 1 / M_primary) * sum_yj;                            \
+    }                                                                                              \
+  }
+
+define_mass_specific_prop_from_T_v(e) define_mass_specific_prop_from_T_v(s)
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:224]: use the clang format off flag to get this to look good

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C [hunk 9]
```diff
@@ -947,87 +619,99 @@ IdealRealGasMixtureFluidProperties::c_from_T_v(Real T,
...
+  const Real cp_primary = dh_dT - dh_dv * dp_dT / dp_dv;
+  cp = x_primary * cp_primary;
 
-  Real vp = v / x_primary;
-  Real ep = _fp_primary->e_from_T_v(T, vp);
-  Real mu = x_primary * M_star / M_primary * _fp_primary->mu_from_v_e(vp, ep);
+  // Neglect these for now. These require higher-order derivatives, so a finite
+  // difference should probably be used, as for sound speed.
+  dcp_dT = 0;
+  dcp_dv = 0;
```
[the remark this answers is not in the document]
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:667]: I originally had a warning for this in this PR. I have it on a commit on another branch. I took it off this PR because the warning triggers in RELAP-7, but I can add that commit back and just add the "allow_warnings" options for the affected tests in RELAP-7 while this is being reviewed.

[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:667]: works for me

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 4 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:53]: It could potentially be moved up into `VaporMixtureFluidProperties`

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 5 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:109]: It depends on the flow formulation, but in any case, adding it would be redundant due to sum-to-unity.

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 6 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:114]: This is something that should be guarded, since `x = 0` is a valid input. I have not addressed this in my changes, only refactored the existing formulation.

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 7 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:137]: I'm very confused/frustrated at this line. I vaguely remember figuring out this thing and even putting a comment, but then I couldn't figure out how to put a comment in the macro. But now the only answer I can come up with is that this should be 0 for `j != i`.

Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:137]: This is with `x_p + \sum_j^N x_j = 1`, where `N` is the number of secondary components. So the secondary mass fractions are independent; the primary mass fraction would take the change. I guess I need to test it.

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 4 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:53]: Actually nevermind, the (T,v) interfaces are not in `VaporMixtureFluidProperties`, so it belongs here only.

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 6 above)
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:114]: I'll put an assert that `x != 0`.

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 9 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:695]: I think if the "jacobian_imperfect_allowed" is set, we dont need to send a warning
not sure this is a mixture FP attribute though

File: modules/fluid_properties/src/fluidproperties/SinglePhaseFluidProperties.C [hunk 10]
```diff
@@ -309,13 +309,13 @@ SinglePhaseFluidProperties::criticalTemperature() const
...
-  mooseError(__PRETTY_FUNCTION__, " not implemented.");
+  return rho_from_p_T(criticalPressure(), criticalTemperature());
 }
 
 Real
 SinglePhaseFluidProperties::criticalInternalEnergy() const
 {
-  mooseError(__PRETTY_FUNCTION__, " not implemented.");
+  return e_from_p_rho(criticalPressure(), criticalDensity());
 }
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/SinglePhaseFluidProperties.C:319]: let's add these two to the unit tests pls

**Review by GiudGiud — COMMENTED** [review]
lgtm

File: modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C (hunk 9 above)
[the remark this answers is not in the document]
Comment (joshuahansel) [reply modules/fluid_properties/src/fluidproperties/IdealRealGasMixtureFluidProperties.C:695]: It does have that param, but I wasn't sure what to do here because in other places, it's used like: 
```
    if (_allow_imperfect_jacobians)
      mooseDoOnce(mooseWarning("blah"));
    else
      mooseError("blah");
```
Plus the description is "true to allow unimplemented property derivative terms to be set to zero for the AD API", which isn't quite the case here, but I could generalize that description.

I'll go ahead and make both of those changes.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
you have one remaining unit test failure btw
