### PR TITLE
Take more care of property derivatives in PorousFlowBrine

### LINKED ISSUE #30661: Bug in PorousFlowBrine derivatives
### Bug Description

As noted in #30621, when the salt mass fraction isn't a nonlinear variable and a tracer is included, the derivative of the fluid properties wrt tracer concentration is incorrectly set, which can make convergence poor

### Steps to Reproduce

See #30621 for examples

### Impact

Poor user experience

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by cpgr**
When salt mass fraction is not a nonlinear variable, then the fluid property derivative wrt mass fraction is set to zero to avoid incorrect Jacobian entries

Fixes #30661

### CODE REVIEW

File: modules/porous_flow/include/materials/PorousFlowBrine.h [hunk 1]
```diff
@@ -50,4 +50,7 @@ class PorousFlowBrine : public PorousFlowFluidPropertiesBase
 
   /// NaCl mass fraction at the qps or nodes
   const VariableValue & _xnacl;
+
+  /// Flag to denote whether NaCl mass fraction is a nonlinear variable
```
Comment (GiudGiud) [inline modules/porous_flow/include/materials/PorousFlowBrine.h:54]: should you add in docstring for the xnacl parameter that the xnacl needs to be listed in. the Dictator as a porous_flow_variable or is this explained somewhere else?

Comment (cpgr) [reply modules/porous_flow/include/materials/PorousFlowBrine.h:54]: Good question. I'll add something in the documentation (just looking and it looks like the documentation for this material is pretty sparse).

Comment (cpgr) [reply modules/porous_flow/include/materials/PorousFlowBrine.h:54]: OK. Updated the documentation for this material. Hope that addresses your suggestion.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Python test failures unrelated.
Are there other fluid properties for another component than NaCl that could have the same issue?

**Comment by cpgr** [comment]
> Python test failures unrelated. Are there other fluid properties for another component than NaCl that could have the same issue?

I believe this issue is particular to `PorousFlowBrine` only, but will double check. Thanks again for the quick review and prompt to update the documentation!
