### PR TITLE
Displace mesh consistently

### LINKED ISSUE #9626: Parallel-inconsistent Node locations on displaced meshes
### Description of the enhancement or error report

Displaced mesh objects in MOOSE can (and typically do?) become inconsistent between processors.

### Rationale for the enhancement or information for reproducing the error

```METHOD=dbg ./run_tests -p 2 --distributed-mesh --recover --re materials/output.block_displaced```
is the first way to trigger the problem that I found.

MOOSE is only calling UpdateDisplacedMeshThread on its internal _active_semilocal_node_range.  So we displace all the nodes on local and MOOSE-ghosted elements, but we don't displace all ghosted nodes.  This is arguably *good* in the ReplicatedMesh case, where every node is ghosted but you only care about a fraction of them and you can get away with not wasting time displacing the rest.  In the DistributedMesh case, though, we have parallel mesh modification code that depends on node locations being consistent across processors, and we have a ton of debug code that asserts such consistency. results.

In the test case above, what happens is that a MeshSerializer attempts to serialize the mesh to processor 0 for Exodus output, the assertions in parallel_node.C discover that a node is in two different places on two different processors, and libMesh screams and dies.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This came to my attention because it may be the last bug blocking #8410.

"Node locations are in sync between processors" is such a fundamental libMesh assumption that I can't imagine how many advanced features could be broken if that assumption isn't met.  As a start:  If we don't have correct node locations on neighboring elements then we will return the wrong results from flux based error estimators, as well as compute the wrong constraint equations on non-Lagrange elements.  If we don't have correct node locations on parent elements then we will compute the wrong constraint equations on Lagrange elements, and the wrong solution projection values on any elements.  If we don't have correct node locations on *arbitrarily distant layers* of elements then we will return the wrong results from patch recovery code.  If we don't have correct node locations on every ghosted element on a distributed mesh then we trigger assertions like the one above, and if we were to disable those assertions then several distributed mesh operations (including repartitioning and adaptive coarsening) would become race conditions for which failure could silently corrupt the mesh.

On the other hand, the obvious fix of "displace every node in the mesh" would turn an O(N_elem/N_proc) operation into an O(N_elem) operation in the ReplicatedMesh case.  I don't think this is significant (just creating a ReplicatedMesh in the first place is O(N_elem); if you don't like that then go DistributedMesh) but I'll wait for others to chime in before I go about pessimizing MOOSE code.

### PR DESCRIPTION
**Pull request by roystgnr**
This incorporates a necessary libMesh submodule update from #9633, and shouldn't be merged until/unless that is.

The rest of this PR changes the behavior of updateDisplacedMesh to fix the bugs reported (and the bugs speculated about, hopefully) in #9626.  The remote-vs-serialized status of reference mesh entities is now kept more closely in sync with displaced mesh entities, and the position of all displaced mesh nodes is now kept perfectly in sync between processors.  We create a custom send_list for displacement variables and use it to create temporary ghosted vectors, to avoid any overcommunication during the displacement update step.

This fixes #9626 in my materials/output.block_displaced recovery tests, on 1 through 24 processors.

### CODE REVIEW

**Comment by roystgnr** [comment]
Hmm... I'm now also getting successful --recovery runs of transfers/multiapp_mesh_function_transfer.fromsub_source_displaced, which test was failing for me (at least with recovery on 4 processors) last week.  I'm not *certain* this is the changeset which fixed it, but it's certainly the prime suspect.

File: framework/src/base/UpdateDisplacedMeshThread.C [hunk 1]
```diff
@@ -13,48 +13,56 @@
...
 
 UpdateDisplacedMeshThread::UpdateDisplacedMeshThread(FEProblemBase & fe_problem,
                                                      DisplacedProblem & displaced_problem)
-  : ThreadedNodeLoop<SemiLocalNodeRange, SemiLocalNodeRange::const_iterator>(fe_problem),
+  : ThreadedNodeLoop<NodeRange, NodeRange::const_iterator>(fe_problem),
     _displaced_problem(displaced_problem),
     _ref_mesh(_displaced_problem.refMesh()),
     _nl_soln(*_displaced_problem._nl_solution),
     _aux_soln(*_displaced_problem._aux_solution),
+    _nl_ghosted_soln(NumericVector<Number>::build(_nl_soln.comm()).release()),
```
Comment (permcody) [inline framework/src/base/UpdateDisplacedMeshThread.C]: Why release this only to capture it in a different smart pointer? Unless there's a compelling reason, I'd just keep the `unique_ptr` around from the build.

File: framework/src/base/UpdateDisplacedMeshThread.C [hunk 2]
```diff
@@ -13,48 +13,56 @@
...
     _aux_soln(x._aux_soln),
-    _var_nums(0),
-    _var_nums_directions(0),
-    _aux_var_nums(0),
-    _aux_var_nums_directions(0),
-    _num_var_nums(0),
-    _num_aux_var_nums(0),
-    _nonlinear_system_number(0),
-    _aux_system_number(0)
+    _nl_ghosted_soln(x._nl_ghosted_soln),
```
Comment (permcody) [inline framework/src/base/UpdateDisplacedMeshThread.C]: Oh, it's the splitting constructor...

File: framework/src/base/UpdateDisplacedMeshThread.C (hunk 1 above)
Comment (roystgnr) [inline framework/src/base/UpdateDisplacedMeshThread.C]: The first smart pointer is a UniquePtr, the second is a shared_ptr.

We can't make the shared_ptr into a unique_ptr, because we want to share these solutions between functors when the functors are split by multithreading.

Eventually we can directly construct the shared_ptr from unique_ptr, but that won't be guaranteed until after we euthanize pre-C++11 libMesh and get rid of the non-unique_ptr UniquePtr implementations.

**Comment by roystgnr** [comment]
Rebased, with merge conflicts fixed.  I'm hoping this can be merged soon; I've got another branch (the fix for #6799) which depends on it.

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like this broke on the 64bit dof id : https://www.moosebuild.org/job/109721/
