### PR TITLE
Correct computation of lower-d element volumes

### LINKED ISSUE #17938: Lower dimensional volume wrong for curvilinear coordinates
## Bug Description
We currently have this code in `Assembly::reinitLowerDElem`:
```c++
  mooseAssert(elem_dim == 1,
              "Lower-D Volume calculations are only accurate in 1D because we are not doing "
              "anything with the coordinate transformation. We currently only support 2D mortar, "
              "so if you hit this assertion there is a problem");
  _current_lower_d_elem_volume = _current_lower_d_elem->volume();
```
The assertion message is actually wrong even in 1D if using a coordinate system other than Cartesian (need to multiply by `_coord`)

## Steps to Reproduce
Look at the code. Run a 2DRZ problem and oggle at the bad lower-dimensional element volumes (areas strictly speaking).

## Impact
Gives users wrong results silently for 1D lower-dimensional elements in a RZ setting. And the assertion prevents valid use of `Assembly::reinitLowerDElem` for 3D HFEM. Issue reported by @YaqiWang

### PR DESCRIPTION
**Pull request by lindsayad**
And remove overzealous assertions

Closes #17938

### CODE REVIEW

**Review by YaqiWang — DISMISSED** [review]
This looks good to me. Thanks for the extra testing.

**Comment by lindsayad** [comment]
Oops just realized that the new booleans are a valgrind error waiting to happen

**Comment by lindsayad** [comment]
Ok should be valgrind clean now and also added 3D test case

File: framework/include/base/Assembly.h [hunk 1]
```diff
@@ -2257,6 +2257,8 @@ class Assembly
   mutable std::map<unsigned int, std::map<FEType, FEVectorBase *>> _vector_fe_lower;
   /// Vector FE objects for lower dimensional elements
   mutable std::map<unsigned int, std::map<FEType, const FEVectorBase *>> _const_vector_fe_lower;
+  /// helper object for transforming coordinates for lower dimensional element quadrature points
+  std::map<unsigned int, FEBase **> _holder_fe_lower_helper;
```
Comment (loganharbour) [inline framework/include/base/Assembly.h:2261]: Why not a vector or even `std::array<FEBase **, 2>` ? I think fixed size storage is pretty perfect here

**Review by loganharbour — APPROVED** [review]
LGTM. Minor comment that you can address if you so desire.

File: framework/include/base/Assembly.h (hunk 1 above)
Comment (lindsayad) [reply framework/include/base/Assembly.h:2261]: I think you could make an argument for the currently used container and both containers you proposed. The size this container *needs* to be is not fixed; it is equal to `_mesh_dimension`. So you could wind up with wasted space in your `std::array` (that no one would ever care about). A vector makes logical sense since you're index perfectly corresponds to dim. Maybe a follow-on PR could change all these `_holder_fe_*helper` objects to `std::vector`

Comment (loganharbour) [reply framework/include/base/Assembly.h:2261]: > Maybe a follow-on PR could change all these

In typical MOOSE fashion 😆

Comment (lindsayad) [reply framework/include/base/Assembly.h:2261]: It's not as if anything is broken or wrong here. And cosmetic changes would be more attractive if it didn't force re-triggering a few hour testing suite :smile:

Comment (loganharbour) [reply framework/include/base/Assembly.h:2261]: To be clear: I'm not disapproving and understand 😬
