### PR TITLE
Some NSFV updates

### LINKED ISSUE #22038: flux-mass with porous media treatment leads to bad BC for momentum
## Bug Description
It triggers addition of a `WCNSFVMomentumFluxBC` whose residual does not include the effects of porosity, e.g. if applying to porous treatment there should be a division by porosity in addition to a division by density.

## Steps to Reproduce
Use a `flux-mass` momentum inlet type in conjunction with `porous_medium_treatment = true` and a non-unity porosity

## Impact
Incorrect inlet momentum conditions

### PR DESCRIPTION
**Pull request by lindsayad**
- The resulting units in the `WCNSFVMomentumFluxBC` were incorrect before when using a mass flow rate input parameter.
- Add average velocity interpolation option to action
- Add TVD advection limiting schemes to action
- Added `PWCNSFVMomentumFluxBC`

Closes #22038

### CODE REVIEW

File: modules/navier_stokes/src/actions/NSFVAction.C [hunk 1]
```diff
@@ -388,6 +388,13 @@ NSFVAction::validParams()
       "The numerical scheme to interpolate the passive scalar field variables to the "
       "face (separate from the advected quantity interpolation).");
 
+  MooseEnum velocity_interpolation("average rc", "rc");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/actions/NSFVAction.C:391]: I thought we were trying to avoid giving that average option so we did not have to support users getting a checkerboard and complaining

Comment (lindsayad) [reply modules/navier_stokes/src/actions/NSFVAction.C:391]: The default is `rc`. If they try something other than the default, then presumably they are already having problems. I think it would be nice to be able to do anything with the action that you can do with the individual objects. Moreover, for buoyant flow for high Rayleigh numbers, I have seen that the only way you can get good results with FV matching FE (at least sans turbulence models) is to use a TVD limiter with average velocity interpolation. There is no checkerboard in this case (or at least I haven't seen it yet on Sinan's cask problems).

**Review by GiudGiud — DISMISSED** [review]
nice bug fixes. good catch
the FHR coupling leveraged the dirichlet BCs luckily

**Comment by GiudGiud** [comment]
seems there are some test failures in Pgh. These might have been similar to @snschune 's modeling. If you want to check Sebastian

**Comment by lindsayad** [comment]
I believe those were the tests I just fixed/changed in the Pronghorn MR so hoping invalidation shows green

**Review by GiudGiud — APPROVED** [review]
