### PR TITLE
Miscellaneous geometric stuff

### LINKED ISSUE #5234: quadrature-based locator breaks augmentSparsity calculation
If I use EqualValueBoundaryConstraint together with thermal contact with `quadrature=true` I get the following error:

```
We'll never get here!
Stack frames: 24
0: 0   libmesh_opt.0.dylib                 0x0000000111692ea5 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1237
1: 1   libmesh_opt.0.dylib                 0x0000000111691429 libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 329
2: 2   libmesh_opt.0.dylib                 0x000000011165b5f2 libMesh::DofObject::var_to_vg(unsigned int, unsigned int) const + 258
3: 3   libmesh_opt.0.dylib                 0x000000011164a3c2 libMesh::DofMap::_dof_indices(libMesh::Elem const*, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&, unsigned int, libMesh::Node const* const*, unsigned int) const + 370
4: 4   libmoose-opt.0.dylib                0x0000000110e0f943 MooseVariable::prepare() + 35
5: 5   libmoose-opt.0.dylib                0x0000000110e4d748 SystemBase::prepare(unsigned int) + 248
6: 6   libmoose-opt.0.dylib                0x0000000110d029cd FEProblem::prepare(libMesh::Elem const*, unsigned int) + 61
7: 7   libmoose-opt.0.dylib                0x0000000110ebce4d GeometricSearchData::generateQuadratureNodes(unsigned int, unsigned int) + 253
8: 8   libmoose-opt.0.dylib                0x0000000110ebcbbe GeometricSearchData::update(GeometricSearchData::GeometricSearchType) + 94
9: 9   libmoose-opt.0.dylib                0x0000000110e2d252 NonlinearSystem::augmentSparsity(libMesh::SparsityPattern::Graph&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&) + 66
10: 10  libmesh_opt.0.dylib                 0x00000001116412bc libMesh::DofMap::build_sparsity(libMesh::MeshBase const&) const + 748
11: 11  libmesh_opt.0.dylib                 0x0000000111649c54 libMesh::DofMap::compute_sparsity(libMesh::MeshBase const&) + 36
12: 12  libmesh_opt.0.dylib                 0x0000000111ac4ac0 libMesh::ImplicitSystem::init_matrices() + 192
13: 13  libmesh_opt.0.dylib                 0x0000000111b060a3 libMesh::TransientSystem<libMesh::NonlinearImplicitSystem>::init_data() + 19
14: 14  libmesh_opt.0.dylib                 0x0000000111ad1f48 libMesh::System::init() + 40
15: 15  libmesh_opt.0.dylib                 0x0000000111aa3072 libMesh::EquationSystems::init() + 818
16: 16  libmoose-opt.0.dylib                0x0000000110d1a7ec FEProblem::init() + 716
17: 17  libmoose-opt.0.dylib                0x0000000110c22c89 ActionWarehouse::executeActionsWithAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 313
18: 18  libmoose-opt.0.dylib                0x0000000110c22b02 ActionWarehouse::executeAllActions() + 274
19: 19  libmoose-opt.0.dylib                0x0000000110e00b25 MooseApp::runInputFile() + 213
20: 20  libmoose-opt.0.dylib                0x0000000110e01f98 MooseApp::run() + 24
21: 21  modules-opt                         0x000000010ffe1415 main + 133
22: 22  libdyld.dylib                       0x00007fff950665fd start + 1
23: 23  ???                                 0x0000000000000003 0x0 + 3
```

### PR DESCRIPTION
**Pull request by lindsayad**
- Make some static methods in `MooseMesh` that `MeshGenerators` can call
- Fix bug in `LowerDBlockFromSidesetGenerator`
- Fix #5234 by not preparing algebraic quantities when all we need is geometric

### CODE REVIEW

File: framework/include/mesh/MooseMesh.h [hunk 1]
```diff
@@ -739,6 +741,11 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
   void
   changeBoundaryId(const boundary_id_type old_id, const boundary_id_type new_id, bool delete_prev);
 
+  static void changeBoundaryId(MeshBase & mesh,
```
Comment (permcody) [inline framework/include/mesh/MooseMesh.h]: Are you calling any of these new methods anywhere, or are you planning on doing this in a follow up PR?
Can you put doc strings in for these new methods or use the "///@{ ///@}" syntax to group them with the existing member methods for Doxygen?

File: framework/include/mesh/MooseMesh.h [hunk 2]
```diff
@@ -607,6 +607,8 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
    */
   void setSubdomainName(SubdomainID subdomain_id, SubdomainName name);
 
+  static void setSubdomainName(MeshBase & mesh, SubdomainID subdomain_id, SubdomainName name);
```
Comment (permcody) [inline framework/include/mesh/MooseMesh.h]: A doc string would be helpful for this method. It's not exactly clear what to do with the arguments just based on the name. I can tell what it does when I look at the implementation. Also you can pass your string by const ref.

**Review by permcody — CHANGES_REQUESTED** [review]

File: framework/include/mesh/MooseMesh.h (hunk 1 above)
Comment (lindsayad) [reply framework/include/mesh/MooseMesh.h]: > Are you calling any of these new methods anywhere, or are you planning on doing this in a follow up PR?

I call this one from the original method 😄 But yea I wrote these for the `SmearedPelletMeshGenerator` that I'm writing for BISON. I could probably drum up a framework test.

File: test/tests/geomsearch/quadrature_locator_plus_constraint/tests [hunk 3]
```diff
@@ -0,0 +1,9 @@
+[Tests]
+  [quadrature_locator_plus_constraint]
+    type = RunApp
+    input = quadrature_locator_plus_constraint.i
+    issues = '#5234'
+    requirement = 'We shall be able to augment our sparsity based on constraints even when we have a quadrature nearest-node locator. The key is to not to try to access dof information when generating the purely geometric quadrature nodes (we may not have even initialized the DofMap at this point)'
```
Comment (permcody) [inline test/tests/geomsearch/quadrature_locator_plus_constraint/tests]: What the heck is going on with this requirement!? On one hand the detail for the programmer is great. However, it's not the best requirement following these definitions: https://www.mooseframework.org/sqa/what_is_a_requirement.html

Comment (permcody) [reply test/tests/geomsearch/quadrature_locator_plus_constraint/tests]: Since all I'm doing right now is cleanup up bad requirements. I'd like people to get better at not creating those in the first place. Use The system, not "we". Also try to avoid compound statements. This is like a mini-paragraph. I think the first sentence may be reasonable for the requirement here except I'd probably drop the word even. It's just a statement of what the system should do. The rest of this stuff could be put into the md, or even just a comment in the test spec or input file.

Comment (lindsayad) [reply test/tests/geomsearch/quadrature_locator_plus_constraint/tests]: >  https://www.mooseframework.org/sqa/what_is_a_requirement.html

The big blue note says that the requirement should be unambiguous. I would say that this is very unambiguous!

Comment (lindsayad) [reply test/tests/geomsearch/quadrature_locator_plus_constraint/tests]: But I'll change it

**Review by permcody — APPROVED** [review]
