### PR TITLE
Fix loading variables from file with multi-system

### LINKED ISSUE #26580: unrecognized variables when using output file to initialize variables
## Bug Description

I am currently working with the k-epsilon turbulence model. I have a solution for a case where the turbulence was very relaxed, but I wanted to use the output from that case as the new initial conditions for a case where turbulence is less relaxed. vel_x copied over just fine however, I get errors for every other variable saying "Unrecognized variable __ in variables to copy". If I initialize vel_y, vel_z, and pressure instead of copying them, it will then give me the same error for my TKE and TKED variables.

## Steps to Reproduce

I ran test_pipe.i, renamed the output file to test_pipe_input.e, and in the mesh block in test_pipe_read_in.i I set file = test_pipe_input.e
When I then run test_pipe_read_in.i I get the error mentioned above.
[test pipe files.zip](https://github.com/idaholab/moose/files/13969179/test.pipe.files.zip)

## Impact

I will likely need this feature to work in order for me to do tests with less turbulence relaxation.

### PR DESCRIPTION
**Pull request by DanielYankura**
-Fixes issue where initializing multiple variables from output file would fail 
-Nonlinear variables were not being properly copied to their corresponding system 
-A similar fix may be needed if the restart system is needed for multiple aux variables

closes #26580

### CODE REVIEW

File: framework/include/problems/FEProblemBase.h [hunk 1]
```diff
@@ -352,6 +352,12 @@ class FEProblemBase : public SubProblem, public Restartable
    */
   unsigned int getMaxQps() const;
 
+  /**
+   * @return The number of nonlinear systems
+   */
+
```
Comment (GiudGiud) [inline framework/include/problems/FEProblemBase.h:358]:
```suggestion
```

File: framework/src/actions/CopyNodalVarsAction.C [hunk 2]
```diff
@@ -57,11 +57,26 @@ CopyNodalVarsAction::act()
...
+          if (tempSys->hasVariable(name()))
+          {
+            system = tempSys;
+          }
+        }
+      }
       else
+      {
         system = &_problem->getAuxiliarySystem();
+      }
```
Comment (GiudGiud) [inline framework/src/actions/CopyNodalVarsAction.C:79]: let's not add those { }

File: framework/include/problems/FEProblemBase.h [hunk 3]
```diff
@@ -352,6 +352,12 @@ class FEProblemBase : public SubProblem, public Restartable
...
+  unsigned int getNonLinearSize() const { return _nl.size(); }
```
Comment (GiudGiud) [inline framework/include/problems/FEProblemBase.h:359]: we have this api already?
```
  virtual std::size_t numNonlinearSystems() const override { return _num_nl_sys; }
```

File: framework/src/actions/CopyNodalVarsAction.C [hunk 4]
```diff
@@ -57,11 +57,26 @@ CopyNodalVarsAction::act()
     else
     {
       SystemBase * system;
+      SystemBase * tempSys;
       // Is this a NonlinearSystem variable or an AuxiliarySystem variable?
       if (_current_task == "copy_nodal_vars")
+      {
+        // This iterates through each nonlinear system and finds which one the current variable
+        // needs to be copied to
         system = &_problem->getNonlinearSystemBase(/*nl_sys=*/0);
```
Comment (GiudGiud) [inline framework/src/actions/CopyNodalVarsAction.C:66]: no need to set this if you are going to loop after to find the real one

**Review by GiudGiud — CHANGES_REQUESTED** [review]
this looks like the right solution to this problem

we'll want to add a test for this

File: framework/src/actions/CopyNodalVarsAction.C (hunk 4 above)
Comment (DanielYankura) [reply framework/src/actions/CopyNodalVarsAction.C:66]: My thought with this was that it should be set to the first nonlinear system by default. That way if it is in fact a typo and can't be assigned to any of them, then when it tries to copy later it should throw an error instead of not trying to copy it. If it's better though I can have it throw an error right there it it isn't able to assign the variable to any of the nonlinear systems?

Comment (GiudGiud) [reply framework/src/actions/CopyNodalVarsAction.C:66]: that works

Comment (DanielYankura) [reply framework/src/actions/CopyNodalVarsAction.C]: I did some testing and it looks like assigning a variable by default to the first nonlinear system if unnecessary. If the user does have typos in their variable names will cause errors elsewhere so having a check there to make sure it was assigned doesn't do anything, so I made the changes you recommended.

File: framework/include/problems/FEProblemBase.h (hunk 3 above)
Comment (DanielYankura) [reply framework/include/problems/FEProblemBase.h]: I removed it from FEProblemBase.h and used the other function instead to get the number of nonlinear systems.

Comment (GiudGiud) [reply framework/include/problems/FEProblemBase.h:359]: seems to be back now?

Comment (DanielYankura) [reply framework/include/problems/FEProblemBase.h]: I think I made a mistake when pushing my changes because my branch didn't seem to have that function, so I recommitted and tried pushing again. Hopefully that fixes the issue.

File: test/tests/misc/multiple-nl-systems/restart_problem.i [hunk 5]
```diff
@@ -0,0 +1,77 @@
+[Mesh]
+  file = 'starting_problem_out.e'
+[]
+
+[Problem]
+  nl_sys_names = 'u v'
+  allow_initial_conditions_with_restart = true
+[]
```
Comment (GiudGiud) [inline test/tests/misc/multiple-nl-systems/restart_problem.i:8]:
```suggestion
  solve = false
[]
```
then you can use the same exodus

File: test/tests/misc/multiple-nl-systems/starting_problem.i [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+  petsc_options = '-snes_monitor'
+  petsc_options_iname = '-pc_type -pc_hypre_type'
+  petsc_options_value = 'hypre boomeramg'
+  first_nl_sys_to_solve = 'u'
+  second_nl_sys_to_solve = 'v'
+[]
+
+[Outputs]
+  exodus = true
+[]
```
Comment (GiudGiud) [inline test/tests/misc/multiple-nl-systems/starting_problem.i:75]:
```suggestion
  execute_on = FINAL
[]
```

File: test/tests/misc/multiple-nl-systems/restart_problem.i (hunk 5 above)
Comment (GiudGiud) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:8]: (with a symlink)

Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:8]: I had a thought. Right now the only real purpose of starting_problem.i is to create an output file that can be used as a starting point for restart_problem.i. What if instead I have only one test that starts from an output file in the gold folder, does the copying but doesn't run, and then I can just have a check to make sure nothing changed during the restart process?

Comment (GiudGiud) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:8]: this would work I agree

File: test/tests/misc/multiple-nl-systems/starting_problem.i (hunk 6 above)
Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/starting_problem.i]: This file was removed in the latest commit.

**Review by GiudGiud — COMMENTED** [review]
looks good.

let s squash some commits together to make the "check in this file, then delete this file" disappear from the commit history (it s wasted storage)

**Comment by DanielYankura** [comment]
I squashed together the three commits that added the test. The input file that was added, and then removed, shouldn't be in the commit history anymore.

File: test/tests/misc/multiple-nl-systems/restart_problem.i [hunk 7]
```diff
@@ -0,0 +1,78 @@
+[Mesh]
+  file = 'gold/starting_problem_out.e'
```
Comment (GiudGiud) [inline test/tests/misc/multiple-nl-systems/restart_problem.i:2]: cant you use restart_problem_out for the inital file?

Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:2]: The issue I found is that when restarting, even if no calculation is done, is that it will add a 2nd timestep that is the same as the first. So when you go to compare input and output files one has a time of 1 and the other 2 and exodiff fails. That's why I have it read in starting_problem_out.e, and compare its output to restart_problem_out.e.

Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:2]: I think start_time might only work for transient solvers? I tried using it but the test then errors because start_time is never used. I guess saying that it adds a 2nd timestep isn't accurate, but it adds a 2nd result. If there's a way to have a restart overwrite the previous output file instead of adding to it that might work. Otherwise the two output files might be necessary?

Comment (GiudGiud) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:2]: there is a `time` parameter for steady

it should not be appending, you are not outputting to gold/starting_problem.e

Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:2]: I tried messing around with the time parameter and I wasn't able to get it to quite work but I think I found a possible solution? I don't know if this is the right approach but adding execute_on = FINAL to the outputs block stops it from doing any execution after reading in the exodus file, so it should just read in the exodus file, copy over the solutions, and then output it right back out. Now when I compare its output against the file it reads in it matches. If that sounds like a reasonable solution then I can go ahead and push those changes.

Comment (GiudGiud) [reply test/tests/misc/multiple-nl-systems/restart_problem.i:2]: That sounds good
I suspect execute_on = initial is all you need to compare the old exodus with the just read then output exodus

Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/restart_problem.i]: When I used execute_on = initial the output file was different from the input. I ended up using execute_on = final and pushed that change.

**Review by GiudGiud — CHANGES_REQUESTED** [review]
the last but one commit still checks in two files. Let s squash them

you should also squash the meaningless format change commits into the one commit that introduced that code

we avoid squashing format commits only when they pertain to multiple commits (as it muddles the commit history instead of cleaning it)

File: test/tests/misc/multiple-nl-systems/tests [hunk 8]
```diff
@@ -70,4 +70,14 @@
     issues = '#28331'
     requirement = 'The system shall be able to output postprocessor data after solving multiple solver systems.'
   []
+  [restart]
+    requirement = 'The system shall be able to restart from an exodus file containing multiple nonlinear variables and multiple nonlinear systems'
```
Comment (GiudGiud) [inline test/tests/misc/multiple-nl-systems/tests:74]:
```suggestion
    requirement = 'The system shall be able to restart multiple nonlinear variables from different nonlinear systems  from an exodus file'
```
the exodus file does not have systems afaik (I dont know for sure but never seen it)

**Review by GiudGiud — COMMENTED** [review]
one tiny thing then good to go

File: test/tests/misc/multiple-nl-systems/tests (hunk 8 above)
Comment (DanielYankura) [reply test/tests/misc/multiple-nl-systems/tests]: Just updated the wording!

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Awesome. Multi-system is the next big step, I m glad to see you support this
