### PR TITLE
delete_remote_elements in Distributed MeshGen

### LINKED ISSUE #15088: Distributed mesh generators must ensure DistributedMesh::is_serial() reports false
## Bug Description
At the point of the ```Partitioner::set_node_processor_ids()``` call from ```DistributedRectilinearMeshGenerator::buildCube()```, ```mesh.is_serial()``` still returns true, despite the mesh having been constructed in parallel and never serialized.  This is tricking the new node partitioning code in https://github.com/libMesh/libmesh/pull/2479 into incorrectly thinking that it can skip communication steps.

## Steps to Reproduce
```METHOD=dbg ./run_tests --re distributed_rectilinear_mesh_generator_3D_hierarch``` using the above libMesh PR, or just assert ```!mesh.is_serial()``` in the buildCube code.

## Impact
No direct impact; ```is_serial()``` becomes correct after the first ```prepare_for_use()``` call.

But this is blocking https://github.com/libMesh/libmesh/pull/2479, which is in turn needed to fix other bugs with distributed node partitioning.  The fix should just be one line of code and two of comments.

### PR DESCRIPTION
**Pull request by roystgnr**
Doing this immediately doesn't actually delete anything or cost
anything, it simply lets a DistributedMesh know that it has been
constructed in a distributed fashion.

Fixes #15088 for me.

### CODE REVIEW

File: framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C [hunk 1]
```diff
@@ -1028,6 +1028,10 @@ DistributedRectilinearMeshGenerator::generate()
   mesh->set_mesh_dimension(_dim);
   mesh->set_spatial_dimension(_dim);
 
+  // Let the mesh know that it's not serialized; the libMesh idiom
+  // here "deletes" 0 elements.
+  mesh->delete_remote_elements();
+
```
Comment (fdkong) [inline framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C:1034]: `auto mesh = _mesh->buildMeshBaseObject(MooseMesh::ParallelType::DISTRIBUTED);`

Will libmesh figure out we are working on a distributed mesh?

**Review by fdkong — APPROVED** [review]

File: framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C (hunk 1 above)
Comment (roystgnr) [reply framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C:1034]: Well that's the trick.  libMesh definitely knows that you're trying to build a DistributedMesh, but not that you're trying to start with a *distributed* mesh, as opposed to a temporarily-serialized mesh which you merely want the capability to distribute later.  Only when you finally tell it to get rid of any remote elements does DistributedMesh decide "I'm definitely not serialized anymore".

I could be convinced to change the default behavior, I think, since it was originally sort of for backwards compatibility purposes that are now moot, but for now making the serialization status explicit in user code is the only fix (and even in the future it'll be the most robust thing to do).

Thanks for looking at this so promptly.

Comment (fdkong) [reply framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C:1034]: I see.

**Comment by fdkong** [comment]
Thanks @roystgnr

**Comment by fdkong** [comment]
@lindsayad

File: framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C:1034]: Since no nodes or elements have been added, wouldn't simply calling `mesh->set_distributed()` be sufficient here?

Comment (roystgnr) [reply framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C:1034]: It should be, I think.  Not sure why I used the old idiom other than force of habit.
