### PR TITLE
Fix segfault on using constants for variable parameters in various situations

### LINKED ISSUE #22597: Error occurs when CZM used no-AD TensorMechanics object with Eigenstrain
## Description
Seg fault on declaring the derivative material property name, retrieving the name of a variable which doesnt exist because a constant value was passed instead of variable

## How to reproduce
Run the input in discussions

## Impact
Seg faults look bad and require a debugger

### Discussed in https://github.com/idaholab/moose/discussions/22576

<div type='discussions-op-text'>

<sup>Originally posted by **echo1115** November  2, 2022</sup>
Hi everyone,
I run the case in https://github.com/idaholab/moose/blob/dfa17cdbb0/modules/tensor_mechanics/test/tests/cohesive_zone_model/bilinear_mixed.i , but I used no-AD TensorMechanics object, and applied a ThermalExpansionEigenstrain. However, the case failed with the following message :
```
*** Info ***
TensorMechanics Action: selecting 'incremental finite strain' formulation.[39m

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 42920 RUNNING AT ga0408
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
Here is the modified input:
```
[Mesh]
  [msh]
    type = GeneratedMeshGenerator
    dim = 2
    xmax = 1
    ymax = 2
    nx = 1
    ny = 2
  []
  [block1]
    type = SubdomainBoundingBoxGenerator
    input = 'msh'
    bottom_left = '0 0 0'
    top_right = '1 1 0'
    block_id = 1
    block_name = 'block1'
  []
  [block2]
    type = SubdomainBoundingBoxGenerator
    input = 'block1'
    bottom_left = '0 1 0'
    top_right = '1 2 0'
    block_id = 2
    block_name = 'block2'
  []
  [split]
    type = BreakMeshByBlockGenerator
    input = block2
  []
  [top_node]
    type = ExtraNodesetGenerator
    coord = '0 2 0'
    input = split
    new_boundary = top_node
  []
  [bottom_node]
    type = ExtraNodesetGenerator
    coord = '0 0 0'
    input = top_node
    new_boundary = bottom_node
  []
[]

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Modules]
  [TensorMechanics]
    [Master]
      generate_output = 'stress_yy'
      [all]
        strain = FINITE
        add_variables = true
        #use_automatic_differentiation = true
        decomposition_method = TaylorExpansion

        eigenstrain_names = 'thermal_eigen'
      []
    []
  []
[]

[BCs]
  [fix_x]
    type = DirichletBC
    preset = true
    value = 0.0
    boundary = bottom_node
    variable = disp_x
  []

  [fix_top]
    type = DirichletBC
    preset = true
    boundary = top
    variable = disp_x
    value = 0
  []

  [top]
    type = FunctionDirichletBC
    boundary = top
    variable = disp_y
    function = 'if(t<=0.3,t,if(t<=0.6,0.3-(t-0.3),0.6-t))'
    preset = true
  []

  [bottom]
    type = DirichletBC
    boundary = bottom
    variable = disp_y
    value = 0
    preset = true
  []
[]

[Modules/TensorMechanics/CohesiveZoneMaster]
  [czm_ik]
    boundary = 'interface'
  []
[]

[Materials]
  [stress]
    #type = ADComputeFiniteStrainElasticStress
    type = ComputeFiniteStrainElasticStress
  []
  [elasticity_tensor]
  #  type = ADComputeElasticityTensor
    type = ComputeElasticityTensor
    fill_method = symmetric9
    C_ijkl = '1.684e5 0.176e5 0.176e5 1.684e5 0.176e5 1.684e5 0.754e5 0.754e5 0.754e5'
  []
  [./thermal_expansion_strain]
    #type = ADComputeThermalExpansionEigenstrain
    type = ComputeThermalExpansionEigenstrain
    stress_free_temperature = 800
    thermal_expansion_coeff = 4.9e-6
    temperature = 800
    eigenstrain_name = 'thermal_eigen'
  [../]
  [czm]
    type = BiLinearMixedModeTraction
    boundary = 'interface'
    penalty_stiffness = 1e6
    GI_c = 1e3
    GII_c = 1e2
    normal_strength = 1e4
    shear_strength = 1e3
    displacements = 'disp_x disp_y'
    eta = 2.2
    viscosity = 1e-3
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  type = Transient

  solve_type = 'NEWTON'
  line_search = none

  petsc_options_iname = '-pc_type'
  petsc_options_value = 'lu'

  automatic_scaling = true

  l_max_its = 2
  l_tol = 1e-14
  nl_max_its = 30
  nl_rel_tol = 1e-50
  nl_abs_tol = 1e-15
  start_time = 0.0
  dt = 0.1
  end_time = 1.0
  dtmin = 0.1
[]

[Outputs]
  exodus = true
[]

```
Acturally the ThermalExpansionEigenstrain is zero because the temperature  equals to  the stress_free_temperature.

The error message is the same in debug mode. Could anyone give me some help? Maybe @hugary1995 @jiangwen84 can give me some suggestions. Thanks in advance.
</div>

### PR DESCRIPTION
**Pull request by GiudGiud**
…n, closes #22597

### CODE REVIEW

**Comment by hugary1995** [comment]
Yep, right fix.

**Comment by dschwen** [comment]
Oh, because of constant coupling... (should be required coupled anyways)

File: modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C [hunk 1]
```diff
@@ -34,9 +34,10 @@ ComputeThermalExpansionEigenstrainBaseTempl<is_ad>::ComputeThermalExpansionEigen
     _use_old_temperature(this->template getParam<bool>("use_old_temperature")),
     _temperature_old(this->_fe_problem.isTransient() ? this->coupledValueOld("temperature")
                                                      : this->_zero),
-    _deigenstrain_dT(is_ad ? nullptr
-                           : &this->template declarePropertyDerivative<RankTwoTensor>(
-                                 _eigenstrain_name, this->getVar("temperature", 0)->name())),
+    _deigenstrain_dT((is_ad || !(this->getVar("temperature", 0)))
+                         ? nullptr
+                         : &this->template declarePropertyDerivative<RankTwoTensor>(
+                               _eigenstrain_name, this->getVar("temperature", 0)->name())),
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C:40]: we should have a `isCoupledConstant` helper method in `Coupleable` to make such code more readable.

Comment (hugary1995) [reply modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C:40]: Yeah, we had a discussion in the referenced issue. Why don't you join the party there?

**Comment by GiudGiud** [comment]
Making it required wont stop people from passing constants. 

You prefer is coupledConstant over a coupledName() that doesnt seg fault?
At the end of the day we re trying to get devs to avoid getVar()->name() so it needs to be the most convenient

**Comment by dschwen** [comment]
> You prefer is coupledConstant over a coupledName() that doesnt seg fault?
No, we need both! What is a `coupledName` "that doesn't segfault" supposed to do? We still need some sort of check to deterimine if the derivative property should be created or not.

**Comment by GiudGiud** [comment]
I feel like it s pretty likely code downstream will expect the derivative to have been created, but that is caught nicer than a seg fault so I m fine with that. 

I agree there's a use for both routines. 
I ll amend this PR and the issue to reflect the broader problem

**Comment by dschwen** [comment]
> I feel like it s pretty likely code downstream will expect the derivative to have been created

No, it is not. Derivatives that do not exist are assumed to be zero. That's why this works at all with constant passed in in your fix.

**Comment by dschwen** [comment]
By the way, we cannot currently mix constants and variables names in vector coupling (multiple coupled components). We could capture this with a custom `CoupledVariableName` class if we add another field for coupled constant value.

**Comment by dschwen** [comment]
That would effectively be a `std::variant` ...

**Comment by GiudGiud** [comment]
I added the new APIs and propagated the coupledName() in moose and the modules. 

While tensor mechanics is good about using 0s for non-existent material properties, looking at the other modules affected, it s clear some expect the material properties to exist. So I did not add checks on isCoupledConstant everywhere, so some code will be declaring properties like dC_d800. This is not really an issue, it does not change the results or segfault like previously. 

I did not take care of the mix of constant and variables. This is a long standing request by others but outside the scope of this work (which is removing those seg faults with constants)

File: framework/src/interfaces/Coupleable.C [hunk 2]
```diff
@@ -2140,10 +2140,30 @@ Coupleable::coupledIndices(const std::string & var_name) const
...
+    return var_name;
+  else
+    mooseError("Variable '", var_name, "' does not exist, yet its coupled name is requested");
+}
+
 std::vector<VariableName>
 Coupleable::coupledNames(const std::string & var_name) const
 {
-  auto func = [this, &var_name](unsigned int comp) { return getVar(var_name, comp)->name(); };
+  auto func = [this, &var_name](unsigned int comp)
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C]: very true. Updated

File: framework/src/interfaces/Coupleable.C [hunk 3]
```diff
@@ -2140,10 +2140,22 @@ Coupleable::coupledIndices(const std::string & var_name) const
   return coupledVectorHelper<unsigned int>(var_name, func);
 }
 
+VariableName
+Coupleable::coupledName(const std::string & var_name, unsigned int comp) const
+{
+  if (getVar(var_name, comp))
+    return getVar(var_name, comp)->name();
+  // For constants, we ll just return the constant as the name
```
Comment (dschwen) [inline framework/src/interfaces/Coupleable.C:2148]:
```suggestion
  // For constants, we'll just return the constant as the name
```

File: framework/src/interfaces/Coupleable.C [hunk 4]
```diff
@@ -2140,10 +2140,22 @@ Coupleable::coupledIndices(const std::string & var_name) const
...
+  else if (MooseUtils::parsesToReal(var_name))
+    return var_name;
+  else
+    mooseError("Variable '", var_name, "' does not exist, yet its coupled name is requested");
```
Comment (dschwen) [inline framework/src/interfaces/Coupleable.C:2152]: You have access to the MooseObject pointer to the derived class that issues the failing call. Outputting its name could be helpful for the user.

File: framework/src/materials/PiecewiseLinearInterpolationMaterial.C [hunk 5]
```diff
@@ -47,7 +47,7 @@ PiecewiseLinearInterpolationMaterial::PiecewiseLinearInterpolationMaterial(
     _scale_factor(getParam<Real>("scale_factor")),
     _extrap(getParam<bool>("extrapolation")),
     _property(declareProperty<Real>(_prop_name)),
-    _dproperty(declarePropertyDerivative<Real>(_prop_name, getVar("variable", 0)->name()))
+    _dproperty(declarePropertyDerivative<Real>(_prop_name, coupledName("variable", 0)))
```
Comment (dschwen) [inline framework/src/materials/PiecewiseLinearInterpolationMaterial.C:50]: So for constant coupling this would declare something like `dprop/d45.7`?

Comment (dschwen) [reply framework/src/materials/PiecewiseLinearInterpolationMaterial.C:50]: the pattern should probalbly be 
```suggestion
    _dproperty(isCoupledConstant("variable") ? nullptr : &declarePropertyDerivative<Real>(_prop_name, coupledName("variable", 0)))
```

and changing `_dproperty` to a pointer

File: modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C [hunk 6]
```diff
@@ -36,7 +36,7 @@ SemiconductorLinearConductivity::SemiconductorLinearConductivity(const InputPara
     _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
     _electric_conductivity(declareProperty<Real>(_base_name + "electrical_conductivity")),
     _delectric_conductivity_dT(declarePropertyDerivative<Real>(
-        _base_name + "electrical_conductivity", getVar("temp", 0)->name()))
+        _base_name + "electrical_conductivity", coupledName("temp", 0)))
```
Comment (dschwen) [inline modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C:39]: same here

Comment (dschwen) [reply modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C:39]: and many other places

**Comment by GiudGiud** [comment]
ah I dont think I have access to Marmot but it should be a really easy fix, _dDdc is now a pointer inherited by PoreGBMrtx..Material

File: modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C (hunk 6 above)
Comment (GiudGiud) [reply modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C]: changed everywhere. Causes Marmot to break on one file. 
Can you make the patch or should I revert on file here?

Comment (GiudGiud) [reply modules/heat_conduction/src/materials/SemiconductorLinearConductivity.C]: *everywhere
Only on the declare*Derivatives. The get*Derivative should be fine querying dCd47.7

**Comment by dschwen** [comment]
Working on it now.

**Comment by dschwen** [comment]
Ok, I think I have the appropriate fix: (censored for export control reasons

```
-  MaterialProperty<RealTensorValue> & _dMdc;
+  MaterialProperty<RealTensorValue> * _dMdc;
```

```
-    _dMdc(declarePropertyDerivative<RealTensorValue>(_M_name, _c_name)),
+    _dMdc(isCoupledConstant(_c_name)
+              ? nullptr
+              : &declarePropertyDerivative<RealTensorValue>(_M_name, _c_name)),
```

```
-    _dMdc[_qp] = ########### * _dDdc[_qp];
+    if (_dMdc)
+      (*_dMdc)[_qp] = ########### * (*_dDdc)[_qp];
```

**Comment by dschwen** [comment]
Ok, I can update the MOOSE submodule on my marmot branch as soon as this get's merged.

**Comment by GiudGiud** [comment]
sounds good. So patch ready?

we need to break next
Once this is approved i ll seek permission

**Comment by dschwen** [comment]
patch ready

File: framework/src/interfaces/Coupleable.C [hunk 7]
```diff
@@ -2140,10 +2140,23 @@ Coupleable::coupledIndices(const std::string & var_name) const
...
+{
+  if (getVar(var_name, comp))
+    return getVar(var_name, comp)->name();
+  // For constants, we'll just return the constant as the name
+  else if (MooseUtils::parsesToReal(var_name))
+    return var_name;
+  else
+    mooseError(
+        _c_name, ": Variable '", var_name, "' does not exist, yet its coupled name is requested");
+}
```
Comment (dschwen) [inline framework/src/interfaces/Coupleable.C:2154]: I wonder if we should make `coupledName`  error out if a constant was coupled. I.e. remove line 2149 and 2150. This would force users to use `isCoupledConstant`. 

We could potentially add `coupledConstant` to recover the coupled constant value.

I just don;t see a usecase for working with a string representation of a coupled constant number literal.

File: framework/src/interfaces/Coupleable.C [hunk 8]
```diff
@@ -2140,10 +2140,23 @@ Coupleable::coupledIndices(const std::string & var_name) const
...
+
 std::vector<VariableName>
 Coupleable::coupledNames(const std::string & var_name) const
 {
-  auto func = [this, &var_name](unsigned int comp) { return getVar(var_name, comp)->name(); };
+  auto func = [this, &var_name](unsigned int comp) { return coupledName(var_name, comp); };
```
Comment (dschwen) [inline framework/src/interfaces/Coupleable.C:2159]: The behavior described above would not be an issue here, as we currently do not allow mixing of variable and constant coupling in one coupled variable vector.

File: framework/src/interfaces/Coupleable.C (hunk 7 above)
Comment (dschwen) [reply framework/src/interfaces/Coupleable.C:2154]: I can see new users wondering why material properties like `dF/d12.721` are created.

Comment (dschwen) [reply framework/src/interfaces/Coupleable.C:2154]: You could keep the lines but make 2150 emit a different `mooseError`. E.g. "The name of a coupled variable was requested, but the user provided a coupled constant value instead."

Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2154]: This is more general than material properties though. coupledName can be used in unrelated code. Do we want to ban constants as soon as the routine relies on the name (for an error message for example?) of the variable?

File: framework/src/interfaces/Coupleable.C (hunk 8 above)
Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2159]: this code would work even when we allow the mixing if we do not disallow coupledName on a constant

File: framework/src/interfaces/Coupleable.C (hunk 7 above)
Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2154]: do dF/d12.711 appear from the getMaterialDerivative calls? Do they get created by default instead of a 0 matprop?

Comment (dschwen) [reply framework/src/interfaces/Coupleable.C:2154]: you would have to suppress creation with a call to isCoupledConstant. Erroring would force the dev to do that. Also, are we using variable names in error messages? We could have a separate call for that which returns the constant string. In fact we already do, it is: `getParam<std::vector<VariableName>>("var_param_name")[component]`

Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2154]: There are 100 or so occurences of getVar->name(), which because they seg fault with constants have been changed to coupledName().

If we made them error instead, it's  definitely better than a seg fault, but it's lost capability. We could no longer use constants there for a while until the devs fix them all. 

Which is unlikely to happen, because the devs did not fix it when it was a seg fault, so when it s a benign error..

imo, the next improvement should not lie with coupledName() but with declareMatPropDerivative, that would avoid declaring a derivative if the variable is a constant.

Comment (dschwen) [reply framework/src/interfaces/Coupleable.C:2154]: How is this lost capable of it never worked?!

Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2154]: It works now :)

Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C:2154]: > Erroring would force the dev to do that.

The seg fault did not stop the devs from doing it.

I'll summarize my position on this:
- I want coupledName to be used because the getVar path is not working
- I dont want the spread of coupledName to limit our ability to pass constants as variables

**Comment by GiudGiud** [comment]
Let's go?

File: framework/src/interfaces/Coupleable.C (hunk 7 above)
Comment (GiudGiud) [reply framework/src/interfaces/Coupleable.C]: @dschwen I caved in
Can I please get an approval :)

Comment (dschwen) [reply framework/src/interfaces/Coupleable.C]: I agree with both of your bullets, but the spread of coupledName is not limiting our ability to pass constants as variables! In the cases where we used getVar instead of coupledName we didn't ever have that capability in the first place! We'd get a segfault instead of an error. Prior to this PR to have this capability the developer would have to explicitly check for a nullptr, after this PR the developer will have to use `isCoupledConstant`.

Overall the PR is an improvement because you are
1. turning a segfault into a proper mooseError
2. more readable functions will be used that convey intent

**Review by dschwen — APPROVED** [review]
