### PR TITLE
Mulitsystem Mulitapp keep_solution_during_restore

### LINKED ISSUE #31097: Multiple Nonlinear Systems in Multiapp not kept with keep_solutions_during_restore
### Bug Description

In /moose/framework/src/multiapps/MultiApp.C around line 770 to 830 there are a couple instances where the nonlinear system is hard coded to 0, rather than looping through all nonlinear systems, when multiple systems are necessary this causes the restore to only restore the first nonlinear system and reset the others. This is similar to issue https://github.com/idaholab/moose/issues/26580. I'm adding a pull request with my fix.

### Steps to Reproduce

Use a multiapp that has multiple non-linear systems (for instance navier stokes modules SIMPLENonlinearAssembly) and use the keep_solution_during_restore = true. I have a test case below that shows this behavior.

[nl_restore.zip](https://github.com/user-attachments/files/21370090/nl_restore.zip)

### Impact

This prevent multisystem coupling from working which I need for my project

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by wallnm**
Fixes the issue where only the first nonlinear system is restore when using keep_solution_during_restore.
 - Changes the current vector of solutions to a vector of vector
 - Adds a for loop to iterate through all nonlinear variables
 - Adds a unit test in the navier stokes module for /multiapps/keep_all_nl_solution

closes #31097

### CODE REVIEW

File: framework/include/multiapps/MultiApp.h [hunk 1]
```diff
@@ -604,7 +604,7 @@ class MultiApp : public MooseObject,
   const bool _no_restore;
 
   /// The solution from the end of the previous solve, this is cloned from the Nonlinear solution during restore
-  std::vector<std::unique_ptr<libMesh::NumericVector<Real>>> _end_solutions;
+  std::vector<std::vector<std::unique_ptr<libMesh::NumericVector<Real>>>> _end_solutions;
```
Comment (GiudGiud) [inline framework/include/multiapps/MultiApp.h:608]:
```suggestion
  /// Outer indexing by child application, inner indexing by solver system
  std::vector<std::vector<std::unique_ptr<libMesh::NumericVector<Real>>>> _end_solutions;
```

File: framework/src/multiapps/MultiApp.C [hunk 2]
```diff
@@ -778,12 +778,17 @@ MultiApp::restore(bool force)
...
-                                .solution()
-                                .clone();
+        _end_solutions[i].resize(_apps[i]->getExecutioner()->feProblem().numNonlinearSystems());
+        for (unsigned int j = 0; j < _apps[i]->getExecutioner()->feProblem().numNonlinearSystems();
+             j++)
+        {
+          _end_solutions[i][j] = _apps[i]
+                                     ->getExecutioner()
+                                     ->feProblem()
+                                     .getNonlinearSystemBase(/*nl_sys=*/j)
```
Comment (GiudGiud) [inline framework/src/multiapps/MultiApp.C]:
```suggestion
        _end_solutions[i].resize(_apps[i]->getExecutioner()->feProblem().numSolverSystems());
        for (unsigned int j = 0; j < _apps[i]->getExecutioner()->feProblem().numSolverSystems();
             j++)
        {
          _end_solutions[i][j] = _apps[i]
                                     ->getExecutioner()
                                     ->feProblem()
                                     .getSolverSystem(/*solver_sys=*/j)
```
this may be enough. Ideally we would make it work for solver systems (both linear & nonlinear)

File: framework/src/multiapps/MultiApp.C [hunk 3]
```diff
@@ -822,11 +827,15 @@ MultiApp::restore(bool force)
...
+        for (unsigned int j = 0; j < _apps[i]->getExecutioner()->feProblem().numNonlinearSystems();
+             j++)
+        {
+          _apps[i]->getExecutioner()->feProblem().getNonlinearSystemBase(/*nl_sys=*/j).solution() =
+              *_end_solutions[i][j];
 
-        // We need to synchronize solution so that local_solution has the right values
-        _apps[i]->getExecutioner()->feProblem().getNonlinearSystemBase(/*nl_sys=*/0).update();
+          // We need to synchronize solution so that local_solution has the right values
+          _apps[i]->getExecutioner()->feProblem().getNonlinearSystemBase(/*nl_sys=*/j).update();
```
Comment (GiudGiud) [inline framework/src/multiapps/MultiApp.C]: same changes

File: modules/navier_stokes/test/tests/multiapps/keep_all_nl_solution/exodiff.cmp
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/multiapps/keep_all_nl_solution/exodiff.cmp:1]: we can't test a change in the framework from a test in the module. 
please make a simple 2 variable - 2 system diffusion case in moose/test/tests/multi_system/multiapps_restore

File: modules/navier_stokes/test/tests/multiapps/keep_all_nl_solution/tests [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+	issues = '#31097'
+	design = 'syntax/MultiApps/index.md'
+	[nl_sol]
+		type = Exodiff
+		input = parent.i
+		exodiff = parent_out_sub0.e
+		custom_cmp = exodiff.cmp
+		exodiff_opts = '-show_all_diffs'
+	[]
+[]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/multiapps/keep_all_nl_solution/tests]:
```suggestion
[Tests]
  issues = '#31097'
  design = 'syntax/MultiApps/index.md'
  [nl_sol]
    type = Exodiff
    input = parent.i
    exodiff = parent_out_sub0.e
    custom_cmp = exodiff.cmp
    exodiff_opts = '-show_all_diffs'
    requirement = 'The system shall be able to restore solutions from multiple solver systems when performing multi-application iterations.'
  []
[]
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]
Thanks for the contribution! There are a few changes to make but the bulk is there

**Review by GiudGiud — COMMENTED** [review]
let's squash the "update" commitds and have a meaningful commit message please. Even if it's just "comments" or "typos" or something

**Comment by wallnm** [comment]
Ok, I think I have all the changes made now, let me know if there is anything else I need to do

**Comment by GiudGiud** [comment]
Dont worry about the threading failure, unrelated

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
VTB failure unrelated (subchannel change)

Thanks for the contribution!
