### PR TITLE
Depth-first search for dependency resolution

### LINKED ISSUE #19856: Dependency resolver issue when an input has many objects
Imported from [idaholab/thm#178](https://gitlab.software.inl.gov/idaholab/thm/-/issues/178) by Jack Cavaluzzi at Feb 22, 2021 04:15PM MST

------

# Bug Description
The problem hangs in the InitialConditionWarehouse due to an apparent dependency resolver issue, likely related to many objects in the problem.

# Steps to Reproduce Bug
run the attached input

[fullcore_redacted.txt](https://github.com/idaholab/moose/files/7764898/fullcore_redacted.txt)

Screen_Shot_2021-02-22_at_3 48 20_PM

### PR DESCRIPTION
**Pull request by lindsayad**
I will see about combining this with the code we added in #20778 so we don't have code/concept duplication.

Closes #19856

### CODE REVIEW

**Comment by cpgr** [comment]
Thanks @lindsayad, it looks like our hacky material resizing still works with this change. I hope it didn't cause you too many headaches.

**Comment by lindsayad** [comment]
No it wasn't too bad! I always enjoy getting some time in other folks' modules and getting some peripheral sense of what they're doing. It reminds me of how awesome of a community we have and how thankful I am for external contributors like yourself and @WilkAndy

**Comment by joshuahansel** [comment]
@lindsayad No new syntax tasks. I used `IterationAdaptiveDT`, so a different number of time steps would result if the number of nonlinear iterations was ever different.

**Comment by joshuahansel** [comment]
Looks like 108 instead of 99 time steps for the open Brayton test. Do you get 108 steps with the framework changes alone, or only when you apply THM changes?

**Comment by lindsayad** [comment]
The dependency resolver changes *do* result in different topological sorts. The old resolver, for instance, would put all "independent" items at the front of the sorted vector. However, with the new resolver, you may get an independent item way later in the sorted vector, after all the items that you traversed up from the first root you examined.

I noticed that for the shaft connected turbine/compressor tests that I re-golded, your energy conservation got much better. I'm still pursuing the question of whether the old dependency resolver didn't actually sort user objects correctly

**Comment by lindsayad** [comment]
For the shaft tests, I explicitly added the indirect dependencies of the `FunctionValuePostprocessor`. It just so happened that even without adding those, the new dependency resolver gave the same sorting. However, with the previous dependency resolver, I'm confident that the `FunctionValuePostprocessor` was executing before some of the other postprocessors and so then had old information, resulting in the bad energy conservation.

I didn't see something obvious like that in the Brayton inputs unfortunately ☹️

**Comment by joshuahansel** [comment]
> So with the new resolver, you are experiencing worse convergence?

I haven't looked at the new transient. It's possible that less iterations on one time step could cause a growth and lead to a failure, leading to a cutback and overall more time steps.

**Comment by joshuahansel** [comment]
I can't find anything that seems relevant. I think we'll need to compare the time step histories to see what's going on.

**Comment by lindsayad** [comment]
This should be ready for review

File: modules/thermal_hydraulics/src/components/FlowChannelBase.C [hunk 1]
```diff
@@ -299,6 +299,9 @@ FlowChannelBase::buildMesh()
     for (auto && id : _elem_ids)
       _mesh.elemPtr(id)->subdomain_id() = subdomain_id;
   }
+
+  // Update the mesh
+  _mesh.update();
```
Comment (joshuahansel) [inline modules/thermal_hydraulics/src/components/FlowChannelBase.C:304]: Just curious - what's this for?

File: modules/porous_flow/src/base/PorousFlowApp.C [hunk 2]
```diff
@@ -66,13 +66,15 @@ associateSyntaxInner(Syntax & syntax, ActionFactory & /*action_factory*/)
...
   addTaskDependency("add_porous_flow_bc", "add_bc");
+  addTaskDependency("resolve_optional_materials", "add_porous_flow_bc");
 
   // Task dependency and syntax for action to automatically add PorousFlow materials
   registerSyntax("PorousFlowAddMaterialAction", "Materials");
 
   // Task dependency and syntax for action to automatically add PorousFlowJoiner materials
   registerTask("add_joiners", /*is_required=*/false);
   addTaskDependency("add_joiners", "add_material");
+  addTaskDependency("add_master_action_material", "add_joiners");
```
Comment (GiudGiud) [inline modules/porous_flow/src/base/PorousFlowApp.C:77]: how did you determine this whole list of extra dependencies?
Was this just to make the test pass or do you have a list that you impose on each module?

File: test/tests/misc/check_error/tests [hunk 3]
```diff
@@ -737,7 +737,7 @@
   [./scalar_old_integrity_check]
     type = 'RunException'
     input = 'scalar_old_integrity_check.i'
-    expect_err = 'Vector tag \'TIME\' does not exist'
+    expect_err = 'Calling \'coupledScalarValueOld\' on variable \S+ when using a \"Steady\" executioner is not allowed. This value is available only in transient simulations.'
```
Comment (GiudGiud) [inline test/tests/misc/check_error/tests:740]: love the improved error messages!

**Review by GiudGiud — COMMENTED** [review]
should be good after this

File: modules/navier_stokes/src/base/NavierStokesApp.C [hunk 4]
```diff
@@ -53,34 +53,42 @@ associateSyntaxInner(Syntax & syntax, ActionFactory & /*action_factory*/)
   // add variables action
   registerTask("add_navier_stokes_variables", /*is_required=*/false);
   addTaskDependency("add_navier_stokes_variables", "add_variable");
+  addTaskDependency("add_mortar_variable", "add_navier_stokes_variables");
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/base/NavierStokesApp.C:56]: The old dependency resolver used to insert a new task immediately behind its prereq, and in front of other things that depend on the prereq ... but not always. In fact what it did was not very transparent at all. With the new dependency resolver you explicitly add every dependency edge; it's fully transparent and obvious what is happening. Now does `add_mortar_variable` truly depend on `add_navier_stokes_variables`? I would sure hope not! But where does the dependency appear? It is hard for me to say except through Monte Carlo. It should definitely happen before `add_user_object`; but should it happen before `add_fluid_properties` for example? I don't actually know unless I try and then maybe I get an error in the FP module. Maybe I don't, but then an error crops up in SAM. What I do know is that if I glance at the old sorting of tasks in the debugger, `add_navier_stokes_variables` occurred before `add_mortar_variable` and so I know this is a safe location for it in the graph.

File: modules/porous_flow/src/base/PorousFlowApp.C (hunk 2 above)
Comment (lindsayad) [reply modules/porous_flow/src/base/PorousFlowApp.C:77]: See previous comment. In general the new task would get inserted immediately behind the prereq task in the task list given in `Moose.C`. If you look in `Moose.C`, `add_master_action_material` is the task that occurs right after `add_material`

File: modules/navier_stokes/src/base/NavierStokesApp.C (hunk 4 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/base/NavierStokesApp.C:56]: Interesting. This seems like there should be convention when there is indetermination on the order. Like "alphabetical sorting"
adding dependencies makes the graph larger but since your algorithm is faster we dont notive it

[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/base/NavierStokesApp.C:56]: but adding dependencies also makes the graph more consistent across apps, which is good

**Review by GiudGiud — APPROVED** [review]
