### PR TITLE
Don't use never sized nonlocal coupling matrices from DisplacedProblem

### LINKED ISSUE #30859: Undefined behaviour in displacement tests
### Bug Description

After parallel debugging with @cmacmackin we've noticed undefined behaviour when running `test/tests/outputs/displacement/displacement_test.i`. Here is a backtrace:

```text
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fffdf0811e3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:89
#2  0x00007fffdf027afe in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fffdf00f6d0 in __GI_abort () at abort.c:73
#4  0x00007fffdf20b086 in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>)
    at ../../../../../libstdc++-v3/src/c++11/assert_fail.cc:41
#5  0x00007fffee5f558c in std::vector<libMesh::CouplingMatrix, std::allocator<libMesh::CouplingMatrix> >::operator[] (this=0xd53120, __n=0) at /usr/include/c++/15/bits/stl_vector.h:1282
#6  0x00007fffee5f0870 in SubProblem::nonlocalCouplingMatrix (this=0xd52f80, i=0) at /home/kcollie/code/inl-platypus/moose/framework/include/problems/SubProblem.h:674
#7  0x00007fffee5c385c in Assembly::Assembly (this=0xcddfe0, sys=..., tid=0) at /home/kcollie/code/inl-platypus/moose/framework/src/base/Assembly.C:84
#8  0x00007fffefb81798 in std::make_unique<Assembly, DisplacedSystem&, unsigned int&> () at /usr/include/c++/15/bits/unique_ptr.h:1085
#9  0x00007fffefb73e1f in DisplacedProblem::DisplacedProblem (this=0xd52f80, parameters=...) at /home/kcollie/code/inl-platypus/moose/framework/src/problems/DisplacedProblem.C:71
#10 0x00007fffefb8bac9 in std::make_unique<DisplacedProblem, InputParameters const&> () at /usr/include/c++/15/bits/unique_ptr.h:1085
#11 0x00007fffefb8ba03 in RegistryEntry<DisplacedProblem>::build (this=0x5f3040, parameters=...) at /home/kcollie/code/inl-platypus/moose/framework/include/base/Registry.h:337
#12 0x00007fffee50b2ea in Factory::createUnique (this=0xa1cd40, obj_name="DisplacedProblem", name="DisplacedProblem", parameters=..., tid=0, print_deprecated=false)
    at /home/kcollie/code/inl-platypus/moose/framework/src/base/Factory.C:102
#13 0x00007fffee22044e in Factory::createUnique<DisplacedProblem> (this=0xa1cd40, obj_name="DisplacedProblem", name="DisplacedProblem", parameters=..., tid=0)
    at /home/kcollie/code/inl-platypus/moose/framework/include/base/Factory.h:254
#14 0x00007fffee21ff55 in Factory::create<DisplacedProblem> (this=0xa1cd40, obj_name="DisplacedProblem", name="DisplacedProblem", parameters=..., tid=0)
    at /home/kcollie/code/inl-platypus/moose/framework/include/base/Factory.h:270
#15 0x00007fffee21da48 in CreateDisplacedProblemAction::act (this=0xa127d0) at /home/kcollie/code/inl-platypus/moose/framework/src/actions/CreateDisplacedProblemAction.C:121
#16 0x00007fffee0ed7d0 in Action::timedAct (this=0xa127d0) at /home/kcollie/code/inl-platypus/moose/framework/src/actions/Action.C:84
#17 0x00007fffee0fd3ea in ActionWarehouse::executeActionsWithAction (this=0xa1c468, task="init_displaced_problem")
    at /home/kcollie/code/inl-platypus/moose/framework/src/actions/ActionWarehouse.C:388
#18 0x00007fffee0fceb8 in ActionWarehouse::executeAllActions (this=0xa1c468) at /home/kcollie/code/inl-platypus/moose/framework/src/actions/ActionWarehouse.C:346
#19 0x00007fffee65eeef in MooseApp::runInputFile (this=0xa1bd70) at /home/kcollie/code/inl-platypus/moose/framework/src/base/MooseApp.C:1632
#20 0x00007fffee666cbc in MooseApp::run (this=0xa1bd70) at /home/kcollie/code/inl-platypus/moose/framework/src/base/MooseApp.C:2099
#21 0x0000000000402c26 in Moose::main<MooseTestApp> (argc=3, argv=0x7fffffffda68) at /home/kcollie/code/inl-platypus/moose/framework/include/base/MooseMain.h:41
#22 0x00000000004007e2 in main (argc=3, argv=0x7fffffffda68) at /home/kcollie/code/inl-platypus/moose/test/src/main.C:16
```

I think this occurs in a few of the tests which use `DisplacedSystem`. During the construction of `Assembly` with a `DisplacedProblem`, `SubProblem::nonlocalCouplingMatrix` is called, which attempts to access index 0 of a 0 size vector, which is obviously undefined behaviour.

I found this because I'm using gcc-15, which seems to now abort on out-of-bounds access of vectors when building in debug mode.

Here is a list of other tests that fail for me, I imagine a few are for the same reason:

```
misc/check_error.wrong_displacement_order ............................................................................................. FAILED (EXPECTED ERROR MISSING)
geomsearch/2d_moving_penetration.pl_test1 .............................................................................................................. FAILED (CRASH)
problems/eigen_problem/eigensolvers.test ............................................................................................................... FAILED (CRASH)
mfem/kernels.MFEMCurlCurl ............................................................................................................................. FAILED (ERRMSG)
geomsearch/3d_moving_penetration.pl_test1 .............................................................................................................. FAILED (CRASH)
geomsearch/3d_moving_penetration_smoothing.disjoint/pl_test3nns ........................................................................................ FAILED (CRASH)
transfers/multiapp_mesh_function_transfer.transfer/tosub ............................................................................................... FAILED (CRASH)
executioners/eigen_executioners.test_inverse_power_method .............................................................................................. FAILED (CRASH)
linearfvkernels/advection.mms-1d-upwind ................................................................................................................ FAILED (CRASH)
linearfvkernels/diffusion.mms-diffusion-1d-cd .......................................................................................................... FAILED (CRASH)
mesh/adapt.displaced_test .............................................................................................................................. FAILED (CRASH)
transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests.transfer/tosub .............................................................. FAILED (CRASH)
geomsearch/patch_update_strategy.never ................................................................................................................. FAILED (CRASH)
linearfvkernels/diffusion-reaction-advection.mms-adr-1d-dirichlet ...................................................................................... FAILED (CRASH)
mortar/displaced-gap-conductance-2d-non-conforming.dynamic_mortar_gap_conductance/separate ............................................................. FAILED (CRASH)
mfem/transfers/h1_mfem_parent_mfem_sub.FromSubToParent/run ............................................................................................ FAILED (ERRMSG)
meshgenerators/distributed_rectilinear/dmg_displaced_mesh.adaptivity ................................................................................... FAILED (CRASH)
adaptivity/displaced_mesh.linear_lagrange_source ....................................................................................................... FAILED (CRASH)
linearfvkernels/block-restriction.mms-diffusion ........................................................................................................ FAILED (CRASH)
mfem/submeshes.MFEMDomainSubMesh ...................................................................................................................... FAILED (ERRMSG)
outputs/displacement.test .............................................................................................................................. FAILED (CRASH)
outputs/displaced.use_displaced ........................................................................................................................ FAILED (CRASH)
transfers/multiapp_interpolation_transfer.tosub ........................................................................................................ FAILED (CRASH)
interfacekernels/ik_displaced.displaced ................................................................................................................ FAILED (CRASH)
linearfvkernels/anisotropic-diffusion.mms-anisotropic-diffusion-2d-orthogonal .......................................................................... FAILED (CRASH)
postprocessors/displaced_mesh.displaced_tests/elemental ................................................................................................ FAILED (CRASH)
vectorpostprocessors/sideset_info.sideset_info/regular ................................................................................................. FAILED (CRASH)
variables/linearfv.basic_pps ........................................................................................................................... FAILED (CRASH)
constraints/overwrite_variables.test_balance ........................................................................................................... FAILED (CRASH)
dgkernels/dg_displacement.test ......................................................................................................................... FAILED (CRASH)
geomsearch/quadrature_locator_plus_constraint.quadrature_locator_plus_constraint ....................................................................... FAILED (CRASH)
linearfvkernels/reaction.reaction-1d ................................................................................................................... FAILED (CRASH)
mfem/outputs.MFEMDataCollections ...................................................................................................................... FAILED (ERRMSG)
mfem/variables.MFEMVariableSetupFromMOOSEVariables .................................................................................................... FAILED (ERRMSG)
misc/block-restricted-disps.run ........................................................................................................................ FAILED (CRASH)
misc/no-renumber-disp-mesh-exodus.test ................................................................................................................. FAILED (CRASH)
misc/update-displaced-aux-local-soln.test .............................................................................................................. FAILED (CRASH)
multisystem/picard/linearfv_nonlinearfv.tightly_coupled ................................................................................................ FAILED (CRASH)
transfers/general_field/shape_evaluation/displaced.same_var_type ....................................................................................... FAILED (CRASH)
transfers/multiapp_copy_transfer/linear_sys_to_aux.test ................................................................................................ FAILED (CRASH)
hdgkernels/displaced.test .............................................................................................................................. FAILED (CRASH)
problems/eigen_problem/eigensolvers.gipm_test .......................................................................................................... FAILED (CRASH)
geomsearch/2d_moving_penetration.pl_test1q ............................................................................................................. FAILED (CRASH)
mfem/kernels.MFEMCurlCurlLOR .......................................................................................................................... FAILED (ERRMSG)
geomsearch/3d_moving_penetration.pl_test1q ............................................................................................................. FAILED (CRASH)
geomsearch/3d_moving_penetration_smoothing.disjoint/pl_test3nnstt ...................................................................................... FAILED (CRASH)
transfers/multiapp_mesh_function_transfer.transfer/fromsub ............................................................................................. FAILED (CRASH)
linearfvkernels/diffusion.mms-diffusion-1d-cd_neumann .................................................................................................. FAILED (CRASH)
linearfvkernels/advection.mms-1d-linear ................................................................................................................ FAILED (CRASH)
transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests.transfer/fromsub ............................................................ FAILED (CRASH)
outputs/variables.test_hidden_shown ................................................................................................... FAILED (EXPECTED ERROR MISSING)
```

I'm not exactly sure what the solution is but from what I can tell looking at the [class diagram](https://mooseframework.inl.gov/docs/doxygen/moose/classSubProblem.html) and grepping, `FEProblemBase` resizes `_nonlocal_cm`, but I can't see any place where `DisplacedProblem` resizes `_nonlocal_cm`.

### Steps to Reproduce

Run the test case in debugger with a breakpoint on `SubProblem:nonlocalCouplingMatrix`.
```bash
cd test
gdb --args ./moose_test-dbg -i tests/outputs/displacement/displacement_test.i
b SubProblem::nonlocalCouplingMatrix
```

Note for me this sets 2 breakpoints, I have to continue 3 times and then I print:

```
Thread 1 "moose_test-dbg" hit Breakpoint 1.2, SubProblem::nonlocalCouplingMatrix (this=0xd53380, i=0) at /home/kcollie/code/inl-platypus/moose/framework/include/problems/SubProblem.h:674
674	    return _nonlocal_cm[i];
(gdb) p _nonlocal_cm.size()
$1 = 0
(gdb) p i
$2 = 0
```

This is where the out-of-bounds access occurs, it might not cause a segfault or sigabrt but is UB nonetheless.

### Impact

Correct programs do not contain UB. I can't build debug with `gcc-15` and run tests.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #30859

### CODE REVIEW

**Comment by lindsayad** [comment]
trying to fix the phase field timeout in https://github.com/idaholab/moose/pull/30844

**Comment by lindsayad** [comment]
@cmacmackin @k-collie you guys want to test this out?

**Comment by k-collie** [comment]
> @cmacmackin @k-collie you guys want to test this out?

Tested and now runs without any aborts, thanks!

File: framework/include/problems/SubProblem.h [hunk 1]
```diff
@@ -88,7 +88,11 @@ class SubProblem : public Problem
   virtual const MooseMesh & mesh() const = 0;
   virtual const MooseMesh & mesh(bool use_displaced) const = 0;
 
-  virtual bool checkNonlocalCouplingRequirement() { return _requires_nonlocal_coupling; }
+  /**
+   * @returns whether there will be nonlocal coupling at any point in the simulation, e.g. whether
+   * there are any active \emph or inactive nonlocal kernels or boundary conditions
+   */
```
Comment (hugary1995) [inline framework/include/problems/SubProblem.h:94]: Here we say "active or inactive", but in the docstring for `hasNonlocalCoupling` we say "For this to return true, there must be at least one active nonlocal kernel or boundary condition". Is the consideration for "inactive" kernels or bcs the primary difference between the two methods, i.e., `checkNonlocalCouplingRequirement` vs `hasNonlocalCoupling`?

**Review by hugary1995 — APPROVED** [review]

File: framework/include/problems/SubProblem.h (hunk 1 above)
Comment (lindsayad) [reply framework/include/problems/SubProblem.h:94]: yes

**Comment by lindsayad** [comment]
failure unrelated
