### PR TITLE
Ghost RC coefficients near postprocessing boundaries

### LINKED ISSUE #21991: VolumetricFlowRate fails on internal boundaries that are cut by domain boundaries
## Bug Description
the a coefficients are local to elements, but they are being retrieved from the other side. The side that owns the face info doesnt own the a coefficient it seems. 

this is the backtrace. Sorry for screenshot, linux wasnt letting me paste from my xterm

image

## Steps to Reproduce
MSFR VTB input with 6 processes. I couldnt get it on my mac but on the linux box I saw it at 6 and 56 processes

## Impact
Died simulation bad bad.
Reduced flexibility in how distributed our flow simulations can be
Makes NS module look bad when we're trying to make it good
Lost analyst time

### PR DESCRIPTION
**Pull request by GiudGiud**
This could also turn in a general interface for this family of functors. 

Realistically, I do not have time to make it.

Closes https://github.com/idaholab/moose/issues/21991

### CODE REVIEW

**Comment by lindsayad** [comment]
Tag me when you want me to take a look at this

**Comment by GiudGiud** [comment]
Assuming it passes the new test in all configurations, I'd like a review

**Comment by GiudGiud** [comment]
should be good for realz
(only error was an unused variable)

**Comment by GiudGiud** [comment]
@lindsayad

File: framework/include/mesh/MooseMesh.h [hunk 1]
```diff
@@ -418,11 +418,34 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+  /**
+   * Returns a map of boundaries to ids of elements on the boundary.
+   */
+  const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
+  getBoundariesToActiveLocalElemIds() const;
+
+  /**
+   * Return all ids of elements which have a side which is part of a boundary/sideset.
+   * Note that boundaries are sided.
+   * @param bid the id of the boundary/sideset of interest
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:435]: As this is developer documentation, I think we can be 100% explicit that this is only about sidesets (nodesets be gone!)
```suggestion
   * Return all ids of elements which have a side which is part of a sideset.
   * @param bid the id of the sideset of interest
```

File: framework/include/mesh/MooseMesh.h [hunk 2]
```diff
@@ -418,11 +418,34 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+   */
+  const std::unordered_set<dof_id_type> getBoundaryActiveLocalElemIds(BoundaryID bid) const;
+
+  /**
+   * Return all ids of neighbors of elements which have a side which is part of a boundary/sideset.
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:440]:
```suggestion
   * Return all ids of neighbors of elements which have a side which is part of a sideset.
```

File: framework/include/mesh/MooseMesh.h [hunk 3]
```diff
@@ -418,11 +418,34 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+   * Note that boundaries are sided, this is on the neighbor side. For the sideset side, use
+   * getBoundariesActiveLocalElemIds.
+   * Note that while the element is local and active, the neighbor is not guaranteed to be local,
+   * it could be ghosted.
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:444]:
```suggestion
   * Note that while the element is local and active, the neighbor is not guaranteed to be local or active
```

Comment (lindsayad) [reply framework/include/mesh/MooseMesh.h:444]: what happens if you don't have any side neighbor layers ghosted like for CFEM and you call this method when there are non-local neighbors?

File: framework/include/mesh/MooseMesh.h [hunk 4]
```diff
@@ -418,11 +418,34 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+   */
+  const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
+  getBoundariesToActiveLocalElemIds() const;
+
+  /**
+   * Return all ids of elements which have a side which is part of a boundary/sideset.
+   * Note that boundaries are sided.
+   * @param bid the id of the boundary/sideset of interest
+   */
+  const std::unordered_set<dof_id_type> getBoundaryActiveLocalElemIds(BoundaryID bid) const;
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:437]:
```suggestion
  std::unordered_set<dof_id_type> getBoundaryActiveLocalElemIds(BoundaryID bid) const;
```

File: framework/include/mesh/MooseMesh.h [hunk 5]
```diff
@@ -418,11 +418,34 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+
+  /**
+   * Return all ids of neighbors of elements which have a side which is part of a boundary/sideset.
+   * Note that boundaries are sided, this is on the neighbor side. For the sideset side, use
+   * getBoundariesActiveLocalElemIds.
+   * Note that while the element is local and active, the neighbor is not guaranteed to be local,
+   * it could be ghosted.
+   * @param bid the id of the boundary/sideset of interest
+   */
+  const std::unordered_set<dof_id_type> getBoundaryActiveNeighborElemIds(BoundaryID bid) const;
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:447]:
```suggestion
  std::unordered_set<dof_id_type> getBoundaryActiveNeighborElemIds(BoundaryID bid) const;
```

File: framework/src/mesh/MooseMesh.C [hunk 6]
```diff
@@ -1000,10 +1000,57 @@ MooseMesh::getBoundaryElementRange()
...
+    return std::unordered_set<dof_id_type>{};
+  return it->second;
+}
+
+const std::unordered_set<dof_id_type>
+MooseMesh::getBoundaryActiveNeighborElemIds(BoundaryID bid) const
+{
+  // Vector of boundary elems is updated every mesh update
+  std::unordered_set<dof_id_type> neighbor_elems;
+  for (const auto & local_elem : _bnd_elems)
```
Comment (lindsayad) [inline framework/src/mesh/MooseMesh.C:1031]: I think we should be able to use a structured binding for the element, side, and boundary ID here. I believe this matches Case 3 here: https://en.cppreference.com/w/cpp/language/structured_binding

**Review by lindsayad — CHANGES_REQUESTED** [review]
partway through

File: framework/include/mesh/MooseMesh.h (hunk 3 above)
Comment (GiudGiud) [reply framework/include/mesh/MooseMesh.h:444]: you should not get them with this code, because you ll retrieve some remote_elems and we exclude them

Comment (lindsayad) [reply framework/include/mesh/MooseMesh.h:444]: :+1: Might want to mention that in the doxygen

File: modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C [hunk 7]
```diff
@@ -22,23 +22,28 @@ RhoFromPTFunctorMaterial::validParams()
...
+    _fluid(getUserObject<SinglePhaseFluidProperties>(NS::fluid)),
+    _density_name(getParam<MooseFunctorName>("density_name"))
 {
-  addFunctorProperty<ADReal>(NS::density,
+  addFunctorProperty<ADReal>(_density_name,
                              [this](const auto & r, const auto & t) -> ADReal
                              { return _fluid.rho_from_p_T(_pressure(r, t), _temperature(r, t)); });
   addFunctorProperty<ADReal>(
-      NS::time_deriv(NS::density),
+      NS::time_deriv(_density_name),
```
Comment (lindsayad) [inline modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C:46]: This works, but you could also do `"density_name"` and it would get worked out during the call to `addFunctorProperty`

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C [hunk 8]
```diff
@@ -439,6 +448,34 @@ INSFVRhieChowInterpolator::finalize()
...
+    return;
+
+  // Ghost a for the elements on the boundary
+  for (auto elem_id : _moose_mesh.getBoundaryActiveLocalElemIds(boundary_id))
+  {
+    const auto & elem = _moose_mesh.elemPtr(elem_id);
+    if (elem->processor_id() != this->processor_id())
+      for (const auto i : make_range(_dim))
+        // Adding to the a coefficient will make sure the final result gets communicated
+        addToA(elem, i, 0);
```
Comment (lindsayad) [inline modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:465]: You should just insert into `_elements_to_push_pull` directly; then you don't loop over every dim and it's more clear what we're doing here. Alternatively you could create a new protected/private method that both this method and `addToA` can call that does thread safe insertion into `_elements_to_push_pull`.

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 8 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:465]: you need to resize _a as well.
I ll check but I think I recall this is needed

Comment (lindsayad) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:465]: Yea thinking about this more, I know there are find assertions in `finalize` that would break if you didn't use `addToA` here. So let's keep the call to `addToA` but you only need to do it for component 0 to make sure we create the map entry

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C [hunk 9]
```diff
@@ -439,6 +448,34 @@ INSFVRhieChowInterpolator::finalize()
...
+{
+  if (_a_data_provided || this->n_processors() == 1 ||
+      _velocity_interp_method == Moose::FV::InterpMethod::Average)
+    return;
+
+  // Ghost a for the elements on the boundary
+  for (auto elem_id : _moose_mesh.getBoundaryActiveLocalElemIds(boundary_id))
+  {
+    const auto & elem = _moose_mesh.elemPtr(elem_id);
+    if (elem->processor_id() != this->processor_id())
```
Comment (lindsayad) [inline modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: You should assert that these processor IDs are equal

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C [hunk 10]
```diff
@@ -439,6 +448,34 @@ INSFVRhieChowInterpolator::finalize()
...
+  }
+
+  // Ghost a for the neighbors of the elements on the boundary
+  for (auto neighbor_id : _moose_mesh.getBoundaryActiveNeighborElemIds(boundary_id))
+  {
+    const auto & neighbor = _moose_mesh.queryElemPtr(neighbor_id);
+    if (neighbor->processor_id() != this->processor_id())
+      for (const auto i : make_range(_dim))
+        // Adding to the a coefficient will make sure the final result gets communicated
+        addToA(neighbor, i, 0);
```
Comment (lindsayad) [inline modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:475]: per above discussion, let's just do this for component 0

**Review by lindsayad — CHANGES_REQUESTED** [review]
Very nice API addition and use

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 9 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: but they are not?

File: framework/include/mesh/MooseMesh.h (hunk 3 above)
Comment (GiudGiud) [reply framework/include/mesh/MooseMesh.h:444]: done

File: framework/src/mesh/MooseMesh.C (hunk 6 above)
Comment (GiudGiud) [reply framework/src/mesh/MooseMesh.C]: ok I tried

File: modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C (hunk 7 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C]: yeah that s better

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 9 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: yeah this line was not doing anything, might as well delete

Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: well actually. getBoundaryActiveLocalElemIds actually gives you local + ghosted
so it can happen

I think we cant have the assert here

Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: We need a name for locally owned + ghosted. 
Or should we just say local = local owned + ghosted

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 10 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:475]: done

File: modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C [hunk 11]
```diff
@@ -22,23 +22,27 @@ RhoFromPTFunctorMaterial::validParams()
...
+    _temperature(getFunctor<ADReal>(NS::temperature)),
     _fluid(getUserObject<SinglePhaseFluidProperties>(NS::fluid))
 {
-  addFunctorProperty<ADReal>(NS::density,
+  addFunctorProperty<ADReal>("density_name",
                              [this](const auto & r, const auto & t) -> ADReal
                              { return _fluid.rho_from_p_T(_pressure(r, t), _temperature(r, t)); });
   addFunctorProperty<ADReal>(
-      NS::time_deriv(NS::density),
+      NS::time_deriv("density_name"),
```
Comment (GiudGiud) [inline modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C:45]: argh it doesnt get it right here

Comment (GiudGiud) [reply modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C]: reverted.
This is fine, I doubt we d want to guess the names from the derivatives too, as that is NS-specific code at this point

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 9 above)
Comment (lindsayad) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: The API name is totally wrong if it returns local + ghosted. Local is established to mean "owned by this processor" in libMesh and in almost all framework code. I would say all but clearly there is an aberration here

Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: it does.
The code works as expected though, the name is the problem imo

File: framework/include/mesh/MooseMesh.h [hunk 12]
```diff
@@ -418,11 +418,35 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+   * Returns a map of boundaries to ids of elements on the boundary.
    */
   const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
   getBoundariesToElems() const;
 
+  /**
+   * Returns a map of boundaries to ids of elements on the boundary.
+   */
+  const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
+  getBoundariesToActiveLocalElemIds() const;
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:430]: Per discussion today
```suggestion
  const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
  getBoundariesToActiveSemiLocalElemIds() const;
```

File: framework/include/mesh/MooseMesh.h [hunk 13]
```diff
@@ -418,11 +418,35 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
+
+  /**
+   * Return all ids of elements which have a side which is part of a boundary/sideset.
+   * Note that boundaries are sided.
+   * @param bid the id of the boundary/sideset of interest
+   */
+  std::unordered_set<dof_id_type> getBoundaryActiveLocalElemIds(BoundaryID bid) const;
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:437]:
```suggestion
  std::unordered_set<dof_id_type> getBoundaryActiveSemiLocalElemIds(BoundaryID bid) const;
```

File: framework/include/mesh/MooseMesh.h [hunk 14]
```diff
@@ -418,11 +418,35 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
...
   getBoundariesToElems() const;
 
+  /**
+   * Returns a map of boundaries to ids of elements on the boundary.
+   */
+  const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
+  getBoundariesToActiveLocalElemIds() const;
+
+  /**
+   * Return all ids of elements which have a side which is part of a boundary/sideset.
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:433]:
```suggestion
   * Return all ids of elements which have a side which is part of a sideset.
```

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: framework/src/mesh/MooseMesh.C [hunk 15]
```diff
@@ -1000,10 +1000,60 @@ MooseMesh::getBoundaryElementRange()
...
 const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
 MooseMesh::getBoundariesToElems() const
+{
+  mooseDeprecated("MooseMesh::getBoundariesToElems is deprecated, "
+                  "use MooseMesh::getBoundariesToActiveLocalElemIds");
+  return getBoundariesToActiveLocalElemIds();
+}
+
+const std::unordered_map<boundary_id_type, std::unordered_set<dof_id_type>> &
+MooseMesh::getBoundariesToActiveLocalElemIds() const
```
Comment (GiudGiud) [inline framework/src/mesh/MooseMesh.C:1010]:
```suggestion
MooseMesh::getBoundariesToActiveSemiLocalElemIds() const
```

File: framework/src/mesh/MooseMesh.C [hunk 16]
```diff
@@ -1000,10 +1000,60 @@ MooseMesh::getBoundaryElementRange()
...
 {
   return _bnd_elem_ids;
 }
 
+std::unordered_set<dof_id_type>
+MooseMesh::getBoundaryActiveLocalElemIds(BoundaryID bid) const
```
Comment (GiudGiud) [inline framework/src/mesh/MooseMesh.C:1016]:
```suggestion
MooseMesh::getBoundaryActiveSemiLocalElemIds(BoundaryID bid) const
```

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C [hunk 17]
```diff
@@ -439,6 +448,32 @@ INSFVRhieChowInterpolator::finalize()
...
 
+void
+INSFVRhieChowInterpolator::ghostADataOnBoundary(const BoundaryID boundary_id)
+{
+  if (_a_data_provided || this->n_processors() == 1 ||
+      _velocity_interp_method == Moose::FV::InterpMethod::Average)
+    return;
+
+  // Ghost a for the elements on the boundary
+  for (auto elem_id : _moose_mesh.getBoundaryActiveLocalElemIds(boundary_id))
```
Comment (GiudGiud) [inline modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:459]:
```suggestion
  for (auto elem_id : _moose_mesh.getBoundaryActiveSemiLocalElemIds(boundary_id))
```

File: framework/include/mesh/MooseMesh.h (hunk 1 above)
Comment (GiudGiud) [reply framework/include/mesh/MooseMesh.h]: forgot to click I ll fix it later

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C (hunk 9 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:462]: names changed

File: framework/include/mesh/MooseMesh.h (hunk 1 above)
Comment (GiudGiud) [reply framework/include/mesh/MooseMesh.h]: ok coaught it

**Comment by GiudGiud** [comment]
good now?

**Review by lindsayad — APPROVED** [review]
more beautiful code

**Comment by GiudGiud** [comment]
Nice thanks for the review!
