### PR TITLE
Minor fixes

### LINKED ISSUE #10475: An issue in CoupledForce?
## Rationale
`CoupledForce::computeQpJacobian()` is always returning 0. How if the coupled variable is the variable itself? At least the code does not stop us from doing that. Looks like the Jacobian will not be assembled correctly in this case if I am understanding correctly.

## Description
https://github.com/idaholab/moose/blob/devel/framework/src/kernels/CoupledForce.C

## Impact
Make implementation more robust.

### PR DESCRIPTION
**Pull request by YaqiWang**
Make sure CoupledForce is not coupling variable itself. Close #10475.
Also fix a small typo.

### CODE REVIEW

File: framework/src/kernels/CoupledForce.C [hunk 1]
```diff
@@ -32,6 +34,9 @@ validParams<CoupledForce>()
 CoupledForce::CoupledForce(const InputParameters & parameters)
   : Kernel(parameters), _v_var(coupled("v")), _v(coupledValue("v")), _coef(getParam<Real>("coef"))
 {
+  if (_var.number() == _v_var)
```
Comment (permcody) [inline framework/src/kernels/CoupledForce.C]: Wait, I though you actually wanted this. I would also accept a PR that properly implements the Jacobian when this case is true. Wouldn't that simplify some of the physics you setup?

Comment (YaqiWang) [reply framework/src/kernels/CoupledForce.C]: I do not. Do you?

Comment (YaqiWang) [reply framework/src/kernels/CoupledForce.C]: I noticed actually few kernels in test folder need to be fixed similarly. But since they are in tests, we do not have to hopefully...

Comment (YaqiWang) [reply framework/src/kernels/CoupledForce.C]: One more thing, let us wait the tests complete to see if anything is broken.

**Review by permcody — APPROVED** [review]
