### PR TITLE
Verify multiple contact pairs with shared secondary surface 

### LINKED ISSUE #23951: Multiple node-face constraints with shared secondary
## Bug Description

When multiple contact pairs are used and one secondary surface acts as secondary to multiple primary surfaces, results do not match to those obtained by splitting the sidesets and disallowing the usage of sidesets over the multiple contact pairs.

This behavior was reported by a user.

## Steps to Reproduce
Employ the `multiple_contact_pairs` test with split sidesets and compare to results obtained with one sideset encompassing multiple surfaces and serving more than one contact pairs.

## Impact
Correct behavior.

### PR DESCRIPTION
**Pull request by recuero**
Closes #23951.

### CODE REVIEW

File: framework/include/constraints/NodeFaceConstraint.h [hunk 1]
```diff
@@ -92,6 +92,16 @@ class NodeFaceConstraint : public Constraint,
    */
   virtual MooseVariable & primaryVariable() { return _primary_var; }
 
+  /**
+   * The primary boundary ID for this constraint.
+   */
+  virtual BoundaryID primaryBoundary() { return _primary; }
```
Comment (lindsayad) [inline framework/include/constraints/NodeFaceConstraint.h:98]:
```suggestion
  BoundaryID primaryBoundary() const { return _primary; }
```

File: framework/include/constraints/NodeFaceConstraint.h [hunk 2]
```diff
@@ -92,6 +92,16 @@ class NodeFaceConstraint : public Constraint,
...
+
+  /**
+   * The secondary boundary ID for this constraint.
+   */
+  virtual BoundaryID secondaryBoundary() { return _secondary; }
```
Comment (lindsayad) [inline framework/include/constraints/NodeFaceConstraint.h:103]:
```suggestion
  BoundaryID secondaryBoundary() const { return _secondary; }
```

File: modules/contact/test/tests/multiple_contact_pairs/tests [hunk 3]
```diff
@@ -31,4 +31,22 @@
...
     allow_warnings = true
   []
+  [split_sidesets]
+    type = 'Exodiff'
+    input = 'split_sidesets.i'
+    exodiff = 'split_sidesets_out.e'
+    requirement = 'The system shall compute mechanical contact with multiple pairs, which are defined with separate contact sidesets.'
+    abs_zero = 1.0e-4
+    rel_err = 1.0e-4
+    allow_warnings = true
```
Comment (lindsayad) [inline modules/contact/test/tests/multiple_contact_pairs/tests:41]: Why do you need to allow warnings?

File: modules/contact/test/tests/multiple_contact_pairs/three_hexagons_coarse.i [hunk 4]
```diff
@@ -52,7 +54,7 @@
     [hex1_pressure]
       boundary = '110'
       function = pressure
-      factor = 140
+      factor = 80
```
Comment (lindsayad) [inline modules/contact/test/tests/multiple_contact_pairs/three_hexagons_coarse.i:57]: Why this change?

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: modules/contact/test/tests/multiple_contact_pairs/tests (hunk 3 above)
Comment (recuero) [reply modules/contact/test/tests/multiple_contact_pairs/tests:41]: The penetration locator throws warnings if nodes don't project.

File: modules/contact/test/tests/multiple_contact_pairs/three_hexagons_coarse.i (hunk 4 above)
Comment (recuero) [reply modules/contact/test/tests/multiple_contact_pairs/three_hexagons_coarse.i:57]: The framework changes in this PR affect the results of this test. This particular change reduces the amount of deformation which speeds up the results. Since the purpose of these tests is to check for the action correctness, I think it's fine.

**Review by lindsayad — APPROVED** [review]
