### PR TITLE
Disable convergence reason printing when Outputs/console=false

### LINKED ISSUE #16030: linear/nonlinear converged reasons are output even when Outputs/console=false
## Bug Description

The title says it all.

## Steps to Reproduce

```
(base) lindad@pop-os:~/projects/moose/test/tests/kernels/simple_diffusion(scaling-and-global-indexing-15732)$ ../../../moose_test-dbg -i simple_diffusion.i Outputs/print_linear_converged_reason=false Outputs/print_nonlinear_converged_reason=false Outputs/console=false
  Linear solve converged due to CONVERGED_RTOL iterations 4
  Linear solve converged due to CONVERGED_RTOL iterations 3
Nonlinear solve converged due to CONVERGED_FNORM_RELATIVE iterations 2
 Solve Converged!
```

## Impact

It is an annoyance.

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #16030

@hugary1995

### CODE REVIEW

File: framework/src/actions/CommonOutputAction.C [hunk 1]
```diff
@@ -146,83 +147,101 @@ CommonOutputAction::CommonOutputAction(InputParameters params)
...
+  }
+  else if (_current_task == "add_output")
+  {
+    // More like remove output. This can't be done during the "common_output" task because the
+    // finite element problem is not yet constructed
 
-  if (!_app.getParam<bool>("no_timing") &&
-      (getParam<bool>("perf_graph") || getParam<bool>("print_perf_log") ||
-       _app.getParam<bool>("timing")))
-    create("PerfGraphOutput");
```
Comment (aeslaughter) [inline framework/src/actions/CommonOutputAction.C:222]: What about this little guy? This will break `perf_graph=true`, correct?

Comment (lindsayad) [reply framework/src/actions/CommonOutputAction.C:222]: That's till present above :smile: The diff is just kind of weird

Comment (aeslaughter) [reply framework/src/actions/CommonOutputAction.C:222]: Damn. I looked a few times. That was sneaky for me.

**Review by aeslaughter — APPROVED** [review]
