### PR TITLE
CSG surface transformations accounted for during half-space determination

### LINKED ISSUE #32730: CSG Transformations not accounted for in CSGSurface point evaluation
### Bug Description

Transformations for CSG objects were implemented such that information about the transformation is simply stored in a vector, not actually applied to manipulate the object (see #32403 #32308 ). However, this is problematic for CSGSurfaces which must implement `evaluateSurfaceEquationAtPoint()` for all surfaces types. The method will determine a value (pos/neg) to pass to `getHalfspaceFromPoint()` to determine if a point is in the negative or positive half-space for that surface. It's possible that a transformation would make it such that this result would be expected to change. However, the transformations are not currently accounted for in these methods which could yield incorrect results. 

### Steps to Reproduce

1. create a simple CSGSphere of radius 1.0 at origin.
2. call either `evaluateSurfaceEquationAtPoint()` or `getHalfspaceFromPoint()` using origin- should return the negative half space.
3. Apply translation to sphere to move it > 1.0 in any direction.
4. call either `evaluateSurfaceEquationAtPoint()` or `getHalfspaceFromPoint()` using origin again. This should return positive half-space in this case, but it actually still returns negative because it still believes the origin to be inside the sphere.

### Impact

Surface evaluation for CSG geometries may not be correct if transformations are used. Fixing this issue may not be straight forward and could add complex downstream developer burden.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by kkiesling**
closes #32730

### CODE REVIEW

**Comment by kkiesling** [comment]
@shikhar413

File: framework/src/csg/CSGTransformationHelper.C [hunk 1]
```diff
@@ -70,4 +70,41 @@ CSGTransformationHelper::getTransformationsAsStrings() const
   return result;
 }
 
+Point
+CSGTransformationHelper::applyReverseTransformsToPoint(const Point & p) const
+{
+  Point p_trans = p; // make a local copy to modify
```
Comment (shikhar413) [inline framework/src/csg/CSGTransformationHelper.C]: Can pass p by value instead of by reference to avoid having to make a copy

File: framework/src/csg/CSGTransformationHelper.C [hunk 2]
```diff
@@ -70,4 +70,41 @@ CSGTransformationHelper::getTransformationsAsStrings() const
...
+
+  // iterate in reverse
+  for (auto it = _transformations.rbegin(); it != _transformations.rend(); ++it)
```
Comment (shikhar413) [inline framework/src/csg/CSGTransformationHelper.C:77]: I think this can be simplified as for (const auto & [trans_type, val] : _transformations)

File: framework/src/csg/CSGTransformationHelper.C [hunk 3]
```diff
@@ -70,4 +70,41 @@ CSGTransformationHelper::getTransformationsAsStrings() const
...
+    {
+      Point offset(std::get<0>(val), std::get<1>(val), std::get<2>(val));
+      for (int i = 0; i < 3; ++i)
+        p_trans(i) -= offset(i);
+    }
+    else if (trans_type == TransformationType::SCALE)
+    {
+      Point scale(std::get<0>(val), std::get<1>(val), std::get<2>(val));
+      for (int i = 0; i < 3; ++i)
+        p_trans(i) /= scale(i);
```
Comment (shikhar413) [inline framework/src/csg/CSGTransformationHelper.C]: Can scale have a 0 value? If so this division will be undefined

File: framework/src/csg/CSGTransformationHelper.C [hunk 4]
```diff
@@ -70,4 +70,41 @@ CSGTransformationHelper::getTransformationsAsStrings() const
...
+
+  // iterate in reverse
+  for (auto it = _transformations.rbegin(); it != _transformations.rend(); ++it)
+  {
+    auto trans_type = it->first;
+    auto val = it->second;
+
+    if (trans_type == TransformationType::TRANSLATION)
+    {
+      Point offset(std::get<0>(val), std::get<1>(val), std::get<2>(val));
```
Comment (shikhar413) [inline framework/src/csg/CSGTransformationHelper.C:84]: You should be able to do p_trans -= offset

File: framework/src/csg/CSGTransformationHelper.C [hunk 5]
```diff
@@ -70,4 +70,41 @@ CSGTransformationHelper::getTransformationsAsStrings() const
...
+      for (int i = 0; i < 3; ++i)
+        p_trans(i) -= offset(i);
+    }
+    else if (trans_type == TransformationType::SCALE)
+    {
+      Point scale(std::get<0>(val), std::get<1>(val), std::get<2>(val));
+      for (int i = 0; i < 3; ++i)
```
Comment (shikhar413) [inline framework/src/csg/CSGTransformationHelper.C:90]: Same comment - p_trans /= scale as long as scale doesn’t have 0 values

File: unit/src/CSGSurfaceTest.C [hunk 6]
```diff
@@ -256,6 +256,72 @@ TEST(CSGSurfaceTest, testGetHalfspaceFromPoint)
...
+  // outside after performing these two transformations. If the transformations were to be
+  // considered in the wrong order during the half-space determination, the point would be
+  // incorrectly determined to be located inside the sphere.
+  {
+    // apply rotation 90 degrees around z-axis
+    std::tuple<Real, Real, Real> trans = {0.0, 0.0, 90};
+    sph3.addTransformation(TransformationType::ROTATION, trans);
+    // a sphere with the translation and then the rotation applied should have the point (1.5, 0, 0)
+    // be considered in the positive half-space (outside)
+    ASSERT_EQ(CSGSurface::Halfspace::POSITIVE, sph3.getHalfspaceFromPoint(p));
```
Comment (shikhar413) [inline unit/src/CSGSurfaceTest.C:321]: Do you think it’d be useful to have a test that shows that a transformation defined with 0 translation, scaling of 1, and rotation of 0 does not update the point in the inverse sense?

File: framework/src/csg/CSGTransformationHelper.C (hunk 3 above)
Comment (kkiesling) [reply framework/src/csg/CSGTransformationHelper.C]: no it has to be non-zero

File: framework/src/csg/CSGTransformationHelper.C (hunk 2 above)
Comment (kkiesling) [reply framework/src/csg/CSGTransformationHelper.C:77]: that doesn't go in reverse. The for-loop has to start at the last transformation and work it's way to the first.

File: framework/src/csg/CSGTransformationHelper.C (hunk 5 above)
Comment (kkiesling) [reply framework/src/csg/CSGTransformationHelper.C:90]: the `-=` operator is valid for this, but not the division operator. It doesn't allow scale to be a vector/point in this case (just a single real value). I updated the other operator though.

File: unit/src/CSGSurfaceTest.C (hunk 6 above)
Comment (kkiesling) [reply unit/src/CSGSurfaceTest.C:321]: I suppose it wouldn't hurt to add it

File: framework/src/csg/CSGTransformationHelper.C (hunk 2 above)
Comment (shikhar413) [reply framework/src/csg/CSGTransformationHelper.C:77]: I see I missed that in your implementation

**Comment by kkiesling** [comment]
@GiudGiud this is ready for review.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Test failures are unrelated
