### PR TITLE
Fix up several loose ends with FindValueOnLine

### LINKED ISSUE #7864: FindValueOnLine has a few corner cases not properly handled
### Description of the enhancement or error report

It looks like FindValueOnLine was written hastily. I saw several problems with that object kind of accidentally while I was working on another task. It doesn't handle out of bounds, it doesn't handle hitting max depth, etc.
### Rationale for the enhancement or information for reproducing the error

I'm not sure if all of these cases are actually errors. I thought it was weird that I couldn't get a very accurate answer for the default case until I realized that we just didn't have enough depth. I have a PR to fix up a lot of the loose ends.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Simulations using this object

### PR DESCRIPTION
**Pull request by permcody**
closes #7864

### CODE REVIEW

File: framework/src/postprocessors/FindValueOnLine.C [hunk 1]
```diff
@@ -24,7 +24,7 @@ InputParameters validParams<FindValueOnLine>()
   params.addParam<Point>("start_point", "Start point of the sampling line.");
   params.addParam<Point>("end_point", "End point of the sampling line.");
   params.addParam<Real>("target", "Target value to locate.");
-  params.addParam<unsigned int>("depth", 30, "Maximum number of bisections to perform.");
+  params.addParam<unsigned int>("depth", 36, "Maximum number of bisections to perform.");
```
Comment (dschwen) [inline framework/src/postprocessors/FindValueOnLine.C]: This is a clear improvement.

File: framework/src/postprocessors/FindValueOnLine.C [hunk 2]
```diff
@@ -62,35 +62,48 @@ FindValueOnLine::execute()
...
     else
-    {
       // to the right
       s_left = s;
-      left = value;
-    }
   }
 
+  if (!found_it)
+    mooseError("Target value \"" << std::setprecision(10) << _target << "\" not found on line within tolerance, last sample: " << value << ".");
```
Comment (dschwen) [inline framework/src/postprocessors/FindValueOnLine.C]: I'm not convinced this should error out hard.

Comment (permcody) [inline framework/src/postprocessors/FindValueOnLine.C]: Me neither, I just put this in because it's the reason your tolerance isn't being honored right now. This is your design, you tell me what you'd like.

We probably need to do something because if the underlying assumption of a monotonic function is violated then we may be really far off when we get down here and that's after the new initial bounds checks were added.

File: framework/src/postprocessors/FindValueOnLine.C (hunk 1 above)
Comment (permcody) [inline framework/src/postprocessors/FindValueOnLine.C]: I detect sarcasm. 

I was unable to get convergence to 1e-10 with 30 for most test cases (1e-10 is the default tolerance in this object). This new number seems like a better default if we want to keep the current tolerance level.

Comment (dschwen) [inline framework/src/postprocessors/FindValueOnLine.C]: Let's think about this a bot more. there is a clear maximum number of iterations after which cutting an interval of two double precision numbers just _cannot_ give you a value that is different from both of the interval bounds. We might be able to just drop this parameter.

**Comment by permcody** [comment]
Maybe. I'm already above what I calculated should be the required number. I
haven't dug in to figure out why. I'm on travel so feel free if you have
time. This isn't critical.

**Comment by permcody** [comment]
@dschwen are you taking this PR over? It's your object, I just noticed it when I was running the static analysis tool.

File: framework/src/postprocessors/FindValueOnLine.C (hunk 2 above)
Comment (dschwen) [inline framework/src/postprocessors/FindValueOnLine.C]: We could return an invalid value... like `-1`

Comment (permcody) [inline framework/src/postprocessors/FindValueOnLine.C]: Fine with me, this is your object. Do you want to finish it up?

**Comment by jwpeterson** [comment]
@dschwen I'd like to merge this (not touched for 12 days).  It seems like you've both washed your hands of it, but also that it's a clear improvement over the code that's currently there.  What do you say?

**Comment by dschwen** [comment]
Sure, go ahead and merge it.

**Review by jwpeterson — APPROVED** [review]
There were a couple of suggestions for improvement:
- Maximum number of bisections should be fixed based on floating point epsilon.
- We might not want to hard fail when the value is not found.

This should not prevent the current code from being merged, however.
