### PR TITLE
Add match/min/max, fix bug

### LINKED ISSUE #5472: Add discrete nucleation system to phase field
We need a system to force nucleation in phase field. I'm working on a probabilistic approach that can coerce nuclei to appear.

### PR DESCRIPTION
**Pull request by dschwen**
This adds the option to specify target order parameter values as min or max values (i.e. A concentration change is only enforced if the current concentration is below or above the target).
Furthermore I'm fixing a bug whereas a wong variable was used to index a vector.

Closes #5472

### CODE REVIEW

File: modules/phase_field/src/userobjects/DiscreteNucleationMap.C [hunk 1]
```diff
@@ -23,6 +23,7 @@ InputParameters validParams<DiscreteNucleationMap>()
 
 DiscreteNucleationMap::DiscreteNucleationMap(const InputParameters & parameters) :
     ElementUserObject(parameters),
+    _mesh_changed(false),
```
Comment (permcody) [inline modules/phase_field/src/userobjects/DiscreteNucleationMap.C]: Two missed initializations!

Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationMap.C]: Yeah, that sucks, but that was not the crash bug. Using ```i``` instead of ```qp``` to index a vector was. The missed initializations were fairly inconsequential (used in an if that only accessed initialized stuff either way and did the right thing either way).
