### PR TITLE
Pick-up user provided RC UO

### LINKED ISSUE #29911: WCNSFVFlowPhysics doesn't work with user-provided RC UO
### Bug Description

Objects will look for the hard-coded RC UO name no matter whether the user has specified an RC UO in their input or whether it's being created by the physics

### Steps to Reproduce

Put an RC UO block in the input file

### Impact

User gets an unexpected error

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #29911

### CODE REVIEW

File: modules/navier_stokes/include/physics/WCNSFVFlowPhysics.h [hunk 1]
```diff
@@ -80,4 +80,6 @@ class WCNSFVFlowPhysics final : public WCNSFVFlowPhysicsBase
   std::vector<std::vector<std::string>> _friction_types;
   /// The coefficients used for each item if friction type
   std::vector<std::vector<std::string>> _friction_coeffs;
+
+  UserObjectName _rc_uo_name;
```
Comment (GiudGiud) [inline modules/navier_stokes/include/physics/WCNSFVFlowPhysics.h:84]:
```suggestion
  /// Name of the user object in charge of computing the Rhie Chow coefficients
  UserObjectName _rc_uo_name;
```

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
BlueCrab test failure is unrelated (headers being more focused to files where they are needed now)
OpenMPI failures unrelated (timeout in an output, steffensen case)
