### PR TITLE
Fix a typo in DofCopyTransfer and address issue #30988 in MultiAppGeneralFieldTransfer

### LINKED ISSUE #30988: Transfers should check the existence of subdomains supplied
### Motivation

Transfers that receive subdomains (`GeneralFieldTransfer` and `DofCopyTransfer`) do not check the existence of the supplied subdomains in the sub-app or main-app mesh. This can lead to a failure of catching mistakes of users. For example, in the following input,

```
[temperature]
  type = MultiAppGeneralFieldNearestLocationTransfer
  from_multi_app = conduction
  source_variable = T
  variable = temperature
  from_blocks = 'FUEL_11 FUEL_12 FUEL_13 FUEL_21 FUEL_22 FUEL_23
                 FUEL_TRI_11 FUEL_TRI_12 FUEL_TRI_13 FUEL_TRI_21 FUEL_TRI_22 FUEL_TRI_23
                 MONOLITH MONOLITH_TRI REFLECTOR REFLECTOR_TRI ABSORBER'
  to_blocks = 'FUEL_11 FUEL_12 FUEL_13 FUEL_21 FUEL_22 FUEL_23
               FUEL_TRI_11 FUEL_TRI_12 FUEL_TRI_13 FUEL_TRI_21 FUEL_TRI_22 FUEL_TRI_23
               MONOLITH MONOLITH_TRI REFLECTOR REFLECTOR_TRI ABSORBER'
  execute_on = TIMESTEP_END
[]
```
the user renamed `ABSORBER` to something else forgot to change this part of input. MOOSE does not catch that `ABSORBER` doesn't exist and leaves the user unaware of his mistake.

### Design

Check the existence of subdomains supplied through `from_blocks` and `to_blocks` in the corresponding mesh.

### Impact

Higher robustness.

### PR DESCRIPTION
**Pull request by AyaHegazy22**
Closes #30988

### CODE REVIEW

File: framework/src/transfers/MultiAppDofCopyTransfer.C [hunk 1]
```diff
@@ -119,7 +119,7 @@ MultiAppDofCopyTransfer::initialSetup()
       }
       // We dont even own any of these subapps
       else
-        _from_blocks = {Moose::INVALID_BLOCK_ID};
+        _to_blocks = {Moose::INVALID_BLOCK_ID};
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppDofCopyTransfer.C:122]: good catch

File: test/tests/transfers/general_field/nearest_node/regular/tests [hunk 2]
```diff
@@ -87,4 +87,66 @@
...
+  
+  [block_boundaries_ids]
+  requirement = "The system shall report an error if a variable is required to be transferred"
+  
+    [bad_from_block_to_multiapp]
+      type = RunException
+      input = main.i
+      cli_args = "Transfers/to_sub/from_blocks=NOT_A_BLOCK"
+      expect_err = "The block 'NOT_A_BLOCK' was not found in the mesh"
+      detail = "with an invalid source block for the to_multiapp."
```
Comment (GiudGiud) [inline test/tests/transfers/general_field/nearest_node/regular/tests]:
```suggestion
      detail = "with an invalid source block for the source multiapp."
```
from_block is necessarily from the from_multiapp

File: test/tests/transfers/general_field/nearest_node/regular/tests [hunk 3]
```diff
@@ -87,4 +87,66 @@
...
+    []
+    [bad_to_block_to_multiapp]
+      type = RunException
+      input = main.i
+      cli_args = "Transfers/to_sub/to_blocks=NOT_A_BLOCK"
+      expect_err = "The block 'NOT_A_BLOCK' was not found in the mesh"
+      detail = "with an invalid target block for the to_multiapp."
```
Comment (GiudGiud) [inline test/tests/transfers/general_field/nearest_node/regular/tests]:
```suggestion
      detail = "with an invalid target block for the target multiapp."
```
same for the others. it s better to use English over parameter names / MOOSE-speak in SQA documentation

File: test/tests/transfers/general_field/nearest_node/regular/tests [hunk 4]
```diff
@@ -87,4 +87,66 @@
...
+    []
+    [bad_from_boundary_to_multiapp]
+      type = RunException
+      input = main.i
+      cli_args = "Transfers/to_sub/from_boundaries=NOT_A_BOUNDARY"
+      expect_err = "The boundary 'NOT_A_BOUNDARY' was not found in the mesh"
+      detail = "with an invalid source boundaries for the to_multiapp."
```
Comment (GiudGiud) [inline test/tests/transfers/general_field/nearest_node/regular/tests]:
```suggestion
      detail = "with an invalid source boundary for the  source multiapp."
```

File: test/tests/transfers/general_field/nearest_node/regular/tests [hunk 5]
```diff
@@ -87,4 +87,66 @@
...
+      expect_err = "The boundary 'NOT_A_BOUNDARY' was not found in the mesh"
+      detail = "with an invalid source boundaries for the from_multiapp."
+    []
+    [bad_to_boundary_from_multiapp]
+      type = RunException
+      input = main.i
+      cli_args = "Transfers/from_sub/to_boundaries=NOT_A_BOUNDARY"
+      expect_err = "The boundary 'NOT_A_BOUNDARY' was not found in the mesh"
+      detail = "with an invalid target boundary for the from_multiapp."
+    []
```
Comment (GiudGiud) [inline test/tests/transfers/general_field/nearest_node/regular/tests:121]: I think we only need 4 tests here, for each of the parameters having the wrong value. The to_/from_block/boundary get paired with the to_/from_ multiapp

File: framework/src/transfers/MultiAppGeneralFieldTransfer.C [hunk 6]
```diff
@@ -235,20 +235,32 @@ MultiAppGeneralFieldTransfer::initialSetup()
...
-      auto & blocks = getParam<std::vector<SubdomainName>>("from_blocks");
-      std::vector<SubdomainID> ids = from_moose_mesh.getSubdomainIDs(blocks);
-      _from_blocks.insert(ids.begin(), ids.end());
-      if (_from_blocks.size() != blocks.size())
-        paramError("from_blocks", "Some blocks were not found in the mesh");
+      const auto & block_names = getParam<std::vector<SubdomainName>>("from_blocks");
+
+      for (const auto & b : block_names)
+        if (!MooseMeshUtils::hasSubdomainName(const_cast<MeshBase &>(from_moose_mesh.getMesh()), b))
+
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppGeneralFieldTransfer.C]:
```suggestion
```

File: framework/src/transfers/MultiAppGeneralFieldTransfer.C [hunk 7]
```diff
@@ -235,20 +235,32 @@ MultiAppGeneralFieldTransfer::initialSetup()
...
     {
-      auto & blocks = getParam<std::vector<SubdomainName>>("from_blocks");
-      std::vector<SubdomainID> ids = from_moose_mesh.getSubdomainIDs(blocks);
-      _from_blocks.insert(ids.begin(), ids.end());
-      if (_from_blocks.size() != blocks.size())
-        paramError("from_blocks", "Some blocks were not found in the mesh");
+      const auto & block_names = getParam<std::vector<SubdomainName>>("from_blocks");
+
+      for (const auto & b : block_names)
+        if (!MooseMeshUtils::hasSubdomainName(const_cast<MeshBase &>(from_moose_mesh.getMesh()), b))
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppGeneralFieldTransfer.C]:
```suggestion
        if (!MooseMeshUtils::hasSubdomainName(from_moose_mesh.getMesh(), b))
```
you dont need the const cast because hasSubdomainName takes in a `const MeshBase &`, so it can accept both a const and a non-const `MeshBase &`

File: framework/src/transfers/MultiAppGeneralFieldTransfer.C [hunk 8]
```diff
@@ -235,20 +235,32 @@ MultiAppGeneralFieldTransfer::initialSetup()
...
     if (isParamValid("from_boundaries"))
     {
-      auto & boundary_names = getParam<std::vector<BoundaryName>>("from_boundaries");
-      std::vector<BoundaryID> boundary_ids = from_moose_mesh.getBoundaryIDs(boundary_names);
-      _from_boundaries.insert(boundary_ids.begin(), boundary_ids.end());
-      if (_from_boundaries.size() != boundary_names.size())
-        paramError("from_boundaries", "Some boundaries were not found in the mesh");
+      const auto & boundary_names = getParam<std::vector<BoundaryName>>("from_boundaries");
+      for (const auto & bn : boundary_names)
+        if (!MooseMeshUtils::hasBoundaryName(const_cast<MeshBase &>(from_moose_mesh.getMesh()), bn))
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppGeneralFieldTransfer.C]: same

**Review by GiudGiud — CHANGES_REQUESTED** [review]

**Review by GiudGiud — APPROVED** [review]
Thanks for the improved error & test coverage!
