### PR TITLE
CappedWeakPlane plasticity

### LINKED ISSUE #7784: Add CappedWeakPlane plasticity to TM
### Description of the enhancement or error report

This plasticity has 3 surfaces (s is the stress tensor in the formulae below).

1. tensile failure with yield function f0 = s_zz - T , with T being the tensile strength (which may be hardening)
2. compressive failure with yield function f1 = -(s_zz - C) , with C being the compressive strength (it is negative, and may be hardening)
3. shear failure with f2 = sqrt(s_zx^2 + s_zy^2) + s_zz * tan(phi) - Coh , with phi being the friction angle, and Coh being the cohesion.  This is non-associative: the flow potential is identical to the yield function, but with phi being replaced by psi, the dilation angle.  All these parameters may be hardening.

Currently this can be modelled in TensorMechanics using MultiSurfacePlasticity, except I want to add one feature that can't currently be handled.  The feature is that the internal parameter for (1) and (2) are linked.

I want to model the situation where a material fails in tension (by f0) has its compressive strength brought closer to zero, because the failure will have created voids in the material that cannot withstand any compressive stress.  Therefore, there will be only two internal parameters: a measure of the zz component of plastic strain; a measure of shear strain associated with f2.  The former will be increased by f0 yielding, and decreased by f1 decreasing.

This could be modelled using two plastic models: one with two surfaces f0 and f1, and the other with f2.  However, I also want to: create a custom and fast return-map algorithm; smooth the intersections of the yield surfaces in order to avoid "zero entries" in the consistent tangent operator when the stress returns to an intersection point, since these "zeros" create poor nonlinear convergence in MOOSE.

f2 will need to be smoothed via hyperbolic smoothing to handle the case of a large tensile strength that exceeds Coh * cot(phi).

I plan to create a new Material to TM, that accepts the current WeakPlane UserObjects, and does the return-map procedure utilising their functions.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #7784

I don't really want this merged at the moment, as the code needs more work.

HOWEVER, i wanted to alert you to a test that illustrates #7783, that I'm hoping one of the moose-devs can fix.  The test is:

tensor_mechanics/tests/capped_weak_plane/SEGFAULT

### CODE REVIEW

**Comment by WilkAndy** [comment]
This is ready for review, @permcody .   I plan to commit a number of similar plasticity models over the coming 6 months, so if you/someone has time for a pedantic and thorough inspection it'd probably pay off in the long term.

File: modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h [hunk 1]
```diff
@@ -0,0 +1,357 @@
...
+  const Real _smoothing_tol;
+
+  /// The yield-function tolerance
+  const Real _f_tol;
+
+  /// Square of the yield-function tolerance
+  const Real _f_tol2;
+
+  /// The type of tangent operator to return.  tangent operator = d(stress_rate)/d(strain_rate).
+  enum TangentOperatorEnum {
```
Comment (permcody) [inline modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h]: Minor: You might start switching to the new C++11 enum syntax. It's basically the same except for the keyword class. This creates a namespace when you use the enumeration items which I think looks a lot cleaner.

File: modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h [hunk 2]
```diff
@@ -0,0 +1,357 @@
...
+    f_and_derivs():
+      f(0.0),
+      df(0),
+      df_di(0),
+      dg(0),
+      d2g(0),
+      d2g_di(0)
+    {}
+
+    f_and_derivs(unsigned num_var, unsigned num_intnl):
```
Comment (permcody) [inline modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h]: Minor: Consider using the new delegating constructors available in C++11. This removes the need to duplicate your initialization lists. A very nice feature.

File: modules/tensor_mechanics/include/userobjects/TensorMechanicsPlasticWeakPlaneShear.h [hunk 3]
```diff
@@ -26,28 +26,12 @@ class TensorMechanicsPlasticWeakPlaneShear : public TensorMechanicsPlasticModel
...
-   * so currently it may not need to be super perfect.
-   * @param f values of the yield functions
-   * @param stress stress tensor
-   * @param intnl internal parameter
-   * @param Eijkl elasticity tensor (stress = Eijkl*strain)
-   * @param[out] act act[i] = true if the i_th yield function is active
-   * @param[out] returned_stress Approximate value of the returned stress
-   */
-  virtual void activeConstraints(const std::vector<Real> & f, const RankTwoTensor & stress, Real intnl, const RankFourTensor & Eijkl, std::vector<bool> & act, RankTwoTensor & returned_stress) const;
+  virtual void activeConstraints(const std::vector<Real> & f, const RankTwoTensor & stress, Real intnl, const RankFourTensor & Eijkl, std::vector<bool> & act, RankTwoTensor & returned_stress) const override;
```
Comment (permcody) [inline modules/tensor_mechanics/include/userobjects/TensorMechanicsPlasticWeakPlaneShear.h]: 👍

File: modules/tensor_mechanics/include/userobjects/TensorMechanicsPlasticWeakPlaneTensileN.h [hunk 4]
```diff
@@ -29,55 +29,17 @@ class TensorMechanicsPlasticWeakPlaneTensileN : public TensorMechanicsPlasticWea
...
-  RankTwoTensor dflowPotential_dintnl(const RankTwoTensor & stress, Real intnl) const;
+  RankTwoTensor dyieldFunction_dstress(const RankTwoTensor & stress, Real intnl) const override;
 
+  Real dyieldFunction_dintnl(const RankTwoTensor & stress, Real intnl) const override;
+
+  RankTwoTensor flowPotential(const RankTwoTensor & stress, Real intnl) const override;
+
+  RankFourTensor dflowPotential_dstress(const RankTwoTensor & stress, Real intnl) const override;
+
+  RankTwoTensor dflowPotential_dintnl(const RankTwoTensor & stress, Real intnl) const override;
```
Comment (permcody) [inline modules/tensor_mechanics/include/userobjects/TensorMechanicsPlasticWeakPlaneTensileN.h]: Nice! I appreciate that you didn't add documentation to these overridden methods.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 5]
```diff
@@ -0,0 +1,890 @@
...
+  if (_tan_phi.value(0) < 0 || _tan_psi.value(0) < 0)
+    mooseError("ComputeCappedWeakPlaneStress: Weak-plane friction and dilation angles must lie in [0, Pi/2]");
+  if (_tan_phi.value(0) < _tan_psi.value(0))
+    mooseError("ComputeCappedWeakPlaneStress: Weak-plane friction angle must not be less than dilation angle");
+  if (_cohesion.value(0) < 0)
+    mooseError("ComputeCappedWeakPlaneStress: Weak-plane cohesion must not be negative");
+  if (_tstrength.value(0) < - _cstrength.value(0))
+    mooseError("ComputeCappedWeakPlaneStress: Weak plane tensile strength must not be less than negative-compressive-strength");
+
+  for (unsigned i = 0; i < 3; ++i)
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: I don't like seeing bare constants like `3`. Can we use LIBMESH_DIM?

Minor: Since this vector is fixed at compile time you can consider using the new `std::array()` class. Basically this is the new C++11 wrapper around statically allocated C-arrays but with a C++ like feel. Why would you use them? They live on the stack instead of going through the memory allocator for storage on the free-store so they can potentially be a lot faster.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 6]
```diff
@@ -0,0 +1,890 @@
...
+}
+
+void
+ComputeCappedWeakPlaneStress::initQpStatefulProperties()
+{
+  ComputeStressBase::initQpStatefulProperties();
+
+  _plastic_strain[_qp].zero();
+  _intnl[_qp].assign(2, 0);
+  _yf[_qp].assign(3, 0);
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Minor: A few more fixed sized vectors. Consider using `std::array`

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 7]
```diff
@@ -0,0 +1,890 @@
...
+
+  const Real in_trial20 = _stress[_qp](2, 0);
+  const Real in_trial21 = _stress[_qp](2, 1);
+  const Real in_q_trial = q_trial;
+
+  // values of p, q  and intnl we know to be admissible
+  Real p_ok = _stress_old[_qp](2, 2);
+  Real q_ok = std::sqrt(Utility::pow<2>(_stress[_qp](2, 0)) + Utility::pow<2>(_stress[_qp](2, 1)));
+  // note that _intnl[_qp] is the "running" intnl variable that gets updated every NR iteration
+  std::vector<Real> intnl_ok(2);
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: std::array with initialization list here: Should be much faster (no allocation/deallocation) and looks nice:
```
std::array<Real, 2> initnl_ok = { _intnl_old[_qp][0], _intnl_old[_qp][1] };
```

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 8]
```diff
@@ -0,0 +1,890 @@
...
+  const Real Ezxzx = _elasticity_tensor[_qp](2, 0, 2, 0);
+  const Real tanpsi = _tan_psi.value(_intnl[_qp][0]);
+  const Real dintnl0_dq = -1.0 / Ezxzx;
+  const Real dintnl0_dqt = 1.0 / Ezxzx;
+  const Real dintnl1_dp = -1.0 / Ezzzz;
+  const Real dintnl1_dpt = 1.0 / Ezzzz;
+  const Real dintnl1_dq = tanpsi / Ezxzx - (q_trial - q) * _tan_psi.derivative(_intnl[_qp][0]) * dintnl0_dq / Ezxzx;
+  const Real dintnl1_dqt = - tanpsi / Ezxzx - (q_trial - q) * _tan_psi.derivative(_intnl[_qp][0]) * dintnl0_dqt / Ezxzx;
+
+  int system_size = 3;
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: const?

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 9]
```diff
@@ -0,0 +1,890 @@
...
+  jac[1] = smoothed_q.dg[0];
+  jac[2] = Ezxzx * smoothed_q.dg[1] / Ezzzz;
+  jac[3] = (smoothed_q.df[0] + smoothed_q.df_di[1] * dintnl1_dp);
+  jac[4] = 1.0 + gaE * (smoothed_q.d2g[0][0] + smoothed_q.d2g_di[0][1] * dintnl1_dp);
+  jac[5] = Ezxzx * gaE / Ezzzz * (smoothed_q.d2g[1][0] + smoothed_q.d2g_di[1][1] * dintnl1_dp);
+  jac[6] = (smoothed_q.df[1] + smoothed_q.df_di[0] * dintnl0_dq + smoothed_q.df_di[1] * dintnl1_dq);
+  jac[7] = gaE * (smoothed_q.d2g[0][1] + smoothed_q.d2g_di[0][0] * dintnl0_dq + smoothed_q.d2g_di[0][1] * dintnl1_dq);
+  jac[8] = 1.0 + Ezxzx * gaE / Ezzzz * (smoothed_q.d2g[1][1] + smoothed_q.d2g_di[1][0] * dintnl0_dq + smoothed_q.d2g_di[1][1] * dintnl1_dq);
+
+  int nrhs = 2;
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: const?

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 10]
```diff
@@ -0,0 +1,890 @@
...
+    _Jacobian_mult[_qp](0, 2, 1, 2) = _Jacobian_mult[_qp](2, 0, 1, 2) = _Jacobian_mult[_qp](0, 2, 2, 1) = _Jacobian_mult[_qp](2, 0, 2, 1) = trial20 * (_dq_dqt - q / q_trial) / q_trial * dqt_dep21;
+    _Jacobian_mult[_qp](1, 2, 1, 2) = _Jacobian_mult[_qp](2, 1, 1, 2) = _Jacobian_mult[_qp](1, 2, 2, 1) = _Jacobian_mult[_qp](2, 1, 2, 1) = _elasticity_tensor[_qp](2, 1, 2, 1) * q / q_trial + trial21 * (_dq_dqt - q / q_trial) / q_trial * dqt_dep21;
+  }
+}
+
+void
+ComputeCappedWeakPlaneStress::unsmoothedYieldFunctions(Real p, Real q, const std::vector<Real> & intnl, std::vector<Real> & yf) const
+{
+  mooseAssert(intnl.size() == 2, "ComputeCappedWeakPlaneStress: yieldFunctions called with intnl size " + Moose::stringify(intnl.size()));
+  mooseAssert(yf.size() == 3, "ComputeCappedWeakPlaneStress: yieldFunctions called with yf size " + Moose::stringify(yf.size()));
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: mooseAssert is a macro that directly passes all arguments to a streaming operator. That means you don't have to use the '+' operator or `stringify`.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 11]
```diff
@@ -0,0 +1,890 @@
...
+  else
+    _all_q[0].d2g[1][1] = _small_smoother2 / std::pow(Utility::pow<2>(q) + _small_smoother2, 1.5);
+  _all_q[1].d2g[1][1] = 0.0;
+  _all_q[2].d2g[1][1] = 0.0;
+}
+
+Real
+ComputeCappedWeakPlaneStress::yieldF(Real p, Real q, const std::vector<Real> & intnl) const
+{
+  std::vector<Real> yf(3);
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: You have lots of fixed size vectors!
`std::array`

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C [hunk 12]
```diff
@@ -0,0 +1,890 @@
...
+{
+  const Real Ezzzz = _elasticity_tensor[_qp](2, 2, 2, 2);
+  const Real Ezxzx = _elasticity_tensor[_qp](2, 0, 2, 0);
+
+  const Real dintnl0_dq = -1.0 / Ezxzx;
+  const Real dintnl1_dp = -1.0 / Ezzzz;
+  const Real tanpsi = _tan_psi.value(_intnl[_qp][0]);
+  const Real dintnl1_dq = tanpsi / Ezxzx - (q_trial - q) * _tan_psi.derivative(_intnl[_qp][0]) * dintnl0_dq / Ezxzx;
+
+  int system_size = 3;
```
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: const?

**Review by permcody — APPROVED** [review]
This looks mergable to me. I don't see any problems with it. I made several c++11 comments for you!

**Comment by WilkAndy** [comment]
Thanks for all those comment, @permcody.  I'll do the changes this wee: quite excited about learning a little bit more C++11.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 5 above)
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: We've had long discussions about this. LIBMESH_DIM is not the right thing here. @bwspenc may want to elaborate. But effectively our mechanics models always assume 3 dimensions internally.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 11 above)
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: I thought we had become pretty good about avoiding local `std::vectors` as they have proven to be horrible performance wise.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 5 above)
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: @dschwen is right. If we were to actually have `LIBMESH_DIM` set to something less than 3 for a lower dimensionality problem, we still have the full 3x3 stress and strain tensors. We are using `LIBMESH_DIM` like this all over the place, but it's wrong.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 11 above)
Comment (permcody) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Right, std::array

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 5 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 7 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 8 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 11 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Heheheh, i'm not sure who "we" is in @dschwen's comment: 

> I thought we had become pretty good about ...

but it certainly isn't ME !   I'd never heard of std::array.  Thanks for teaching me.

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 10 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 11 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: I've gone through the class trying to remove std::vector and replace by std::array.  This particular example i can't change as later i use pop_back on it

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 12 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C (hunk 9 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/src/materials/ComputeCappedWeakPlaneStress.C]: Fixed

File: modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h (hunk 2 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h]: Yea, this is nice, thanks.  Fixed.

File: modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h (hunk 1 above)
Comment (WilkAndy) [inline modules/tensor_mechanics/include/materials/ComputeCappedWeakPlaneStress.h]: OK, fixed.

**Comment by WilkAndy** [comment]
Thanks everyone for your help in making this rather complicated Class better.
