### PR TITLE
Linear kepsilon

### LINKED ISSUE #29846: Add k-epsilon model for new linear kernels
### Motivation

Currently, the $k-\epsilon$ model is supported by the nonlinear assembly method. The models should be extended to support the linear assembly one.

### Design

The design should follow the same one that the current one in the nonlinear assembly. 

### Impact

This enhancement will enable the usage of the $k-\epsilon$ model with linear kernels.

### LINKED ISSUE #31117: LinearFV objects with internal boundaries show wrong results due to normal flip.
### Bug Description

The direction of the normal in MOOSE-FV is fixed (points from the element to the neighbor) and is in the wrong direction when the variables live only on the neighbor and assign an internal boundary. This influences every kernel that directly utilizes the normal in the expression. We need extensive coverage on block-restricted cases.

### Steps to Reproduce

Run nonorthogonal problems with blockrestriction and nonorthogonal corrections turned on.

### Impact

Will yield wrong results for many block-restricted problems.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by tanoret**
Closes #29846
Closes #31117

### CODE REVIEW

**Comment by tanoret** [comment]
@grmnptr @GiudGiud - could you please do the code review?
@freiler - could you please do the technical review? I normally run the tests in the flow test bed and was getting the same results than the k-epsilon with the nonlinear assembly

Thanks!!

File: framework/src/linearfvbcs/LinearFVBoundaryCondition.C [hunk 1]
```diff
@@ -49,7 +49,7 @@ LinearFVBoundaryCondition::LinearFVBoundaryCondition(const InputParameters & par
     MooseVariableInterface(this,
                            false,
                            "variable",
-                           Moose::VarKindType::VAR_SOLVER,
+                           Moose::VarKindType::VAR_ANY,
```
Comment (lindsayad) [inline framework/src/linearfvbcs/LinearFVBoundaryCondition.C:52]: why this change?

File: framework/src/problems/FEProblemBase.C [hunk 2]
```diff
@@ -7420,22 +7425,26 @@ FEProblemBase::computeLinearSystemTags(const NumericVector<Number> & soln,
...
 
-  try
-  {
-    computeSystems(EXEC_NONLINEAR);
-  }
-  catch (MooseException & e)
-  {
-    _console << "\nA MooseException was raised during Auxiliary variable computation.\n"
-             << "The next solve will fail, the timestep will be reduced, and we will try again.\n"
-             << std::endl;
```
Comment (lindsayad) [inline framework/src/problems/FEProblemBase.C:7431]: we definitely want try-catch

**Review by lindsayad — COMMENTED** [review]
Need some communication about why we are changing the framework objects. Seems to be to allow BCs on aux variables?

File: framework/src/linearfvbcs/LinearFVBoundaryCondition.C (hunk 1 above)
Comment (GiudGiud) [reply framework/src/linearfvbcs/LinearFVBoundaryCondition.C:52]: this is allowing BCs on aux variables. Peter will do a separate PR

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+  {
+
+    // Useful variables
+    const Real mu = _mu(elem_arg, state);
+    const Real TKE = _var.getElemValue(*_current_elem_info, state);
+
+    // Assembly variables
+    Real destruction = 0.0;
+    Real tot_weight = 0.0;
+    std::vector<Real> y_plus_vec, velocity_grad_norm_vec;
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:107]: you should reserve a size for these two vectors for performance purposes rather than allocating dynamically later on

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+{
+  // Coumputing bounding map
+  const Elem * elem = _current_face_info->elemPtr();
+  const auto bounded_elem = _wall_bounded.find(elem) != _wall_bounded.end();
+  const Elem * neighbor = _current_face_info->neighborPtr();
+  const auto bounded_neigh = _wall_bounded.find(neighbor) != _wall_bounded.end();
+
+  // If we are on an internal face, we populate the four entries in the system matrix
+  // which touch the face
+  if (_current_face_type == FaceInfo::VarFaceNeighbors::BOTH)
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C:58]: let's discuss this tomorrow. this is a ton code duplication for something that block restriction should achieve naturally?

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/gold/channel_ERCOFTAC_out.e
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/gold/channel_ERCOFTAC_out.e:1]: well actually.

I dont think we need the short versions. The long versions run in 4 and 6s respectively in devel mode. this is plenty fast enough imo.

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C (hunk 4 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C:58]: if you dont think so, then let's create "addMatrixContrib/ETCInternal in the advection class.

then in the base class (regular advection) you do: addMatrixContrib() { addMatrixContribInternal() }

and in the derived class, you do 
if (on boundary)
  code code
else
 addMatrixContribInternal();

File: framework/src/linearfvbcs/LinearFVBoundaryCondition.C (hunk 1 above)
Comment (grmnptr) [reply framework/src/linearfvbcs/LinearFVBoundaryCondition.C:52]: Well, this is in this PR:
https://github.com/idaholab/moose/pull/29532

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 5]
```diff
@@ -0,0 +1,440 @@
...
+  [u_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_x
+    advected_interp_method = ${advected_interp_method}
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'x'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:125]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 6]
```diff
@@ -0,0 +1,440 @@
...
+    use_deviatoric_terms = yes
+  []
+  [u_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_x
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:132]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 7]
```diff
@@ -0,0 +1,440 @@
...
+  [v_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_y
+    advected_interp_method = ${advected_interp_method}
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'y'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:155]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 8]
```diff
@@ -0,0 +1,440 @@
...
+    use_deviatoric_terms = yes
+  []
+  [v_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_y
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:162]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 9]
```diff
@@ -0,0 +1,440 @@
...
+    variable = vel_y
+    pressure = pressure
+    momentum_component = 'y'
+  []
+
+  [p_diffusion]
+    type = LinearFVAnisotropicDiffusion
+    variable = pressure
+    diffusion_tensor = Ainv
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:175]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 10]
```diff
@@ -0,0 +1,440 @@
...
+  []
+  [TKE_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKE
+  []
+  [TKE_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKE
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:197]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 11]
```diff
@@ -0,0 +1,440 @@
...
+  []
+  [TKE_turb_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKE
+    diffusion_coeff = 'mu_t'
+    scaling_coeff = ${sigma_k}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:204]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 12]
```diff
@@ -0,0 +1,440 @@
...
+  [TKED_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKED
+    walls = ${walls}
+  []
+  [TKED_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:234]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 13]
```diff
@@ -0,0 +1,440 @@
...
+    walls = ${walls}
+  []
+  [TKED_turb_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = 'mu_t'
+    scaling_coeff = ${sigma_eps}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:242]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 14]
```diff
@@ -0,0 +1,440 @@
...
+    type = ParsedAux
+    variable = 'mu_eff'
+    coupled_variables = 'mu_t'
+    expression = 'mu_t + ${mu}'
+    execute_on = 'NONLINEAR'
+  []
+[]
+
+[Executioner]
+  type = PIMPLE
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:403]: I think we could put this and the steady version ot the same folder and reuse most of the input files. You can use the `!include mesh.i` syntax etc.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 15]
```diff
@@ -0,0 +1,417 @@
...
+  [u_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_x
+    advected_interp_method = ${advected_interp_method}
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'x'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:120]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 16]
```diff
@@ -0,0 +1,417 @@
...
+    use_deviatoric_terms = yes
+  []
+  [u_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_x
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:127]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 17]
```diff
@@ -0,0 +1,417 @@
...
+  [v_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_y
+    advected_interp_method = ${advected_interp_method}
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'y'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:144]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 18]
```diff
@@ -0,0 +1,417 @@
...
+    use_deviatoric_terms = yes
+  []
+  [v_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_y
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:151]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 19]
```diff
@@ -0,0 +1,417 @@
...
+    variable = vel_y
+    pressure = pressure
+    momentum_component = 'y'
+  []
+
+  [p_diffusion]
+    type = LinearFVAnisotropicDiffusion
+    variable = pressure
+    diffusion_tensor = Ainv
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:164]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 20]
```diff
@@ -0,0 +1,417 @@
...
+
+  [TKE_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKE
+  []
+  [TKE_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKE
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:181]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 21]
```diff
@@ -0,0 +1,417 @@
...
+  []
+  [TKE_turb_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKE
+    diffusion_coeff = 'mu_t'
+    scaling_coeff = ${sigma_k}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:188]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 22]
```diff
@@ -0,0 +1,417 @@
...
+  [TKED_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKED
+    walls = ${walls}
+  []
+  [TKED_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:213]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i [hunk 23]
```diff
@@ -0,0 +1,417 @@
...
+    walls = ${walls}
+  []
+  [TKED_turb_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = 'mu_t'
+    scaling_coeff = ${sigma_eps}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/channel_ERCOFTAC.i:221]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/tests [hunk 24]
```diff
@@ -0,0 +1,23 @@
+[Tests]
+  design = 'INSFVTurbulentAdvection.md INSFVTurbulentDiffusion.md INSFVTKESourceSink.md INSFVTKEDSourceSink.md INSFVTurbulentViscosityWallFunction.md kEpsilonViscosityAux.md'
+  issues = '#9007'
+  [channel_ERCOFTAC_linear]
+    requirement = 'The system shall be able to solve fluid flow problems with k-epsilon turbulence model for a standard channel, '
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/tests:5]:
```suggestion
    requirement = 'The system shall be able to solve fluid flow problems with k-epsilon turbulence model for a standard channel with linear FV discretization, and'
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i [hunk 25]
```diff
@@ -10,7 +10,7 @@
 ##########################################################
 
 H = 1 #halfwidth of the channel
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:12]: Part of the reason for regolds is the we fixed the deviatoric term for nonlinear assembly.

[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:12]: If we are already regolding, I think it is better to have the same conditions for linear and nonlinear. Linear can't do symmetry at the moment.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i [hunk 26]
```diff
@@ -123,7 +141,7 @@ wall_treatment = 'eq_newton' # Options: eq_newton, eq_incremental, eq_linearized
     variable = vel_x
     mu = 'mu_t'
     momentum_component = 'x'
-    complete_expansion = true
+    complete_expansion = no
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:144]: the deviatoric part should be fixed now, at least for laminar cases.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i [hunk 27]
```diff
@@ -272,24 +292,37 @@ wall_treatment = 'eq_newton' # Options: eq_newton, eq_incremental, eq_linearized
...
+  #   v = vel_y
+  #   intensity = ${intensity}
+  # []
+  # [inlet_TKED]
+  #   type = INSFVMixingLengthTKEDBC
+  #   boundary = 'left'
+  #   variable = TKED
+  #   k = TKE
+  #   characteristic_length = '${fparse 2*H}'
+  # []
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:322]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i [hunk 28]
```diff
@@ -299,39 +332,39 @@ wall_treatment = 'eq_newton' # Options: eq_newton, eq_incremental, eq_linearized
...
+  # [symmetry_TKE]
+  #   type = INSFVSymmetryScalarBC
+  #   boundary = 'bottom'
+  #   variable = TKE
+  # []
+  # [symmetry_TKED]
+  #   type = INSFVSymmetryScalarBC
+  #   boundary = 'bottom'
+  #   variable = TKED
+  # []
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:367]:
```suggestion
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 29]
```diff
@@ -0,0 +1,358 @@
...
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
+    walls = ${walls}
+  []
+  [TKED_turb_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = 'mu_t'
+    scaling_coeff = ${sigma_eps}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:198]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 30]
```diff
@@ -0,0 +1,358 @@
...
+  [TKED_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKED
+    walls = ${walls}
+  []
+  [TKED_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKED
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:190]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 31]
```diff
@@ -0,0 +1,358 @@
...
+
+  [TKE_advection]
+    type = LinearFVTurbulentLimitedAdvection
+    variable = TKE
+  []
+  [TKE_diffusion]
+    type = LinearFVTurbulentLimitedDiffusion
+    variable = TKE
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:158]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 32]
```diff
@@ -0,0 +1,358 @@
...
+    variable = vel_y
+    pressure = pressure
+    momentum_component = 'y'
+  []
+
+  [p_diffusion]
+    type = LinearFVAnisotropicDiffusion
+    variable = pressure
+    diffusion_tensor = Ainv
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:141]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 33]
```diff
@@ -0,0 +1,358 @@
...
+    momentum_component = 'y'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
+    use_deviatoric_terms = yes
+  []
+  [v_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_y
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:128]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 34]
```diff
@@ -0,0 +1,358 @@
...
+
+  [v_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_y
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'y'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:121]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 35]
```diff
@@ -0,0 +1,358 @@
...
+    momentum_component = 'x'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
+    use_deviatoric_terms = yes
+  []
+  [u_diffusion]
+    type = LinearFVDiffusion
+    variable = vel_x
+    diffusion_coeff = ${mu}
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:104]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i [hunk 36]
```diff
@@ -0,0 +1,358 @@
...
+[LinearFVKernels]
+  [u_advection_stress]
+    type = LinearWCNSFVMomentumFlux
+    variable = vel_x
+    mu = 'mu_t'
+    u = vel_x
+    v = vel_y
+    momentum_component = 'x'
+    rhie_chow_user_object = 'rc'
+    use_nonorthogonal_correction = true
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-non-eq-wall.i:97]:
```suggestion
    use_nonorthogonal_correction = false
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i [hunk 37]
```diff
@@ -0,0 +1,358 @@
+### Thermophysical Properties ###
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i:1]: We only have a few options different in this, we should either do the `inlude` syntax and split the input file or just the cli_args.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/tests [hunk 38]
```diff
@@ -0,0 +1,46 @@
+[Tests]
+  # Testing summary
+  # Input                        Wall function           Solver         Energy   Energy wall function
+  # lid-driven-turb-std-wall.i      std                  segregated     no
+  # lid-driven-turb-non-eq-wall.i   non-eq               segregated     no
+  design = 'INSFVTurbulentAdvection.md INSFVTurbulentDiffusion.md INSFVTKESourceSink.md INSFVTKEDSourceSink.md INSFVTurbulentViscosityWallFunction.md kEpsilonViscosityAux.md'
+  issues = '#9007'
+  [lid_driven_turb_std_wall_linear]
+    requirement = 'The system shall be able to run fluid flow with k-epsilon turbulence model in enclosures with standard wall functions, '
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/tests:9]:
```suggestion
    requirement = 'The system shall be able to run fluid flow with k-epsilon turbulence model in enclosures with standard wall functions and the linear finite volume discretization, '
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/tests [hunk 39]
```diff
@@ -0,0 +1,46 @@
...
+      type = 'Exodiff'
+      input = 'lid-driven-turb-std-wall.i'
+      exodiff = 'lid-driven-turb-std-wall_short.e'
+      detail = 'and pass debugging checks.'
+      cli_args = 'Executioner/num_iterations=10 Outputs/file_base=lid-driven-turb-std-wall_short'
+      abs_zero = 1e-6
+    []
+  []
+  [lid_driven_turb_non_eq_wall_linear]
+    requirement = 'The system shall be able to run fluid flow with k-epsilon turbulence model in enclosures with non-equilibrium wall functions, '
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/tests:28]:
```suggestion
    requirement = 'The system shall be able to run fluid flow with k-epsilon turbulence model in enclosures with non-equilibrium wall functions and the linear finite volume discretization, '
```

**Review by grmnptr — CHANGES_REQUESTED** [review]
Very nice, just a few suggestions!

File: framework/src/systems/LinearSystem.C [hunk 40]
```diff
@@ -91,6 +94,10 @@ LinearSystem::LinearSystem(FEProblemBase & fe_problem, const std::string & name)
   // We create a tag for the right hand side, the vector is already in the libmesh system
   _rhs_tag = _fe_problem.addVectorTag("RHS");
 
+  // We add other wector tags so that objects acting on the aux system inheriting
+  // from the tagging interface can still be used without any nonlinear systems
+  _rhs_non_time_tag = _fe_problem.addVectorTag("NONTIME");
```
[the remark this answers is not in the document]
Comment (tanoret) [reply framework/src/systems/LinearSystem.C:99]: Kept the first one.

File: modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVTKEDSourceSink.md [hunk 41]
```diff
@@ -0,0 +1,113 @@
+# LinearFVTKEDSourceSink
+
+This kernel implements a version of [`INSFVTKEDSourceSink`](INSFVTKEDSourceSink.md) for a linear kernel.
+The documentation is repeated down here for completeness.
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVTKEDSourceSink.md:4]: We will eventually be removing the one from the nonlinear assembly. This is why I copied it here. Thanks!

File: modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVTurbulentLimitedAdvection.md [hunk 42]
```diff
@@ -0,0 +1,19 @@
...
+$\phi$, where $\phi$ corresponds to the nonlinear variable that this kernel acts
+on. This kernel acts in a linear solve. 
+The linear `variable` can be of type `MooseLinearVariableFVReal`.
+
+The particularity of this kernel is that it allows us to skip computing advection
+for near-wall elements. The key for this skip are the boundaries identified in
+the [!param](/LinearFVKernels/LinearFVTurbulentLimitedAdvection/walls) list.
+For any element that is in contact with a boundary identified
+in the [!param](/LinearFVKernels/LinearFVTurbulentLimitedAdvection/walls) list,
+advection will be skipped for that element over all faces.
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/doc/content/source/linearfvkernels/LinearFVTurbulentLimitedAdvection.md:13]: Thanks. Yes. Keeping it this way for now. May be able to do this in the mesh later, but this is good for now.

File: modules/navier_stokes/include/base/NavierStokesMethods.h [hunk 43]
```diff
@@ -99,7 +99,8 @@ Real prandtlPropertyDerivative(const Real & mu,
  * @param dist the element centroid distance to the wall
  * @return the velocity at the wall
  */
-ADReal findUStar(const ADReal & mu, const ADReal & rho, const ADReal & u, Real dist);
+template <typename T>
+T findUStar(const T & mu, const T & rho, const T & u, Real dist);
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/include/base/NavierStokesMethods.h:103]: Thanks

File: modules/navier_stokes/include/linearfvkernels/LinearFVTKEDSourceSink.h [hunk 44]
```diff
@@ -0,0 +1,85 @@
...
+
+  // Production Limiter Constant
+  const Real _C_pl;
+
+  ///@{
+  /** Maps for wall treatment */
+  std::map<const Elem *, bool> _wall_bounded;
+  std::map<const Elem *, std::vector<Real>> _dist;
+  std::map<const Elem *, std::vector<const FaceInfo *>> _face_infos;
+  ///@}
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/include/linearfvkernels/LinearFVTKEDSourceSink.h:84]: Thanks. The problem is that INSFVTKED will eventually be going away from the linear methods when we remove the nonlinear assembly. I prefer to keep it this way for now. We can eventually optimize it in the future

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C [hunk 45]
```diff
@@ -95,16 +95,23 @@ RANSYPlusAux::computeValue()
 
     for (unsigned int i = 0; i < distance_vec.size(); i++)
     {
-      const auto parallel_speed = NS::computeSpeed(
+      const auto parallel_speed = NS::computeSpeed<ADReal>(
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/auxkernels/RANSYPlusAux.C:98]: Sometimes this wall will be called with ADReals when using the nonlinear methods. Real here will break a bunch of things

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 46]
```diff
@@ -127,32 +130,111 @@ findyPlus(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
   // avoid this failure mode.
   return isZero(velocity) ? 1e-42 : velocity.norm();
 }
+template Real computeSpeed<Real>(const libMesh::VectorValue<Real> & velocity);
+template ADReal computeSpeed<ADReal>(const libMesh::VectorValue<ADReal> & velocity);
+
+template <typename T>
+T
+computeShearStrainRateNormSquared(const Moose::Functor<T> & u,
+                                  const Moose::Functor<T> * v,
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/base/NavierStokesMethods.C:169]: Thanks!

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C (hunk 4 above)
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentLimitedAdvection.C:58]: I am tabling this for now since this is a bit unrelated to this PR. Let's keep this optimization for future efforts.

File: modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-vortex/spacedependent_mu/test.py [hunk 47]
```diff
@@ -0,0 +1,117 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('vortex-snl.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s, %f" % (key, value))
+            if key in velocity_labels:
+                self.assertTrue(fuzzyAbsoluteEqual(value, 2.0, .4))
+            else:
+                self.assertTrue(fuzzyAbsoluteEqual(value, 1.0, .5))
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-vortex/spacedependent_mu/test.py:62]: Yeah. We should really not expect 2nd order for any of them in the current formulations...

File: modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-vortex/spacedependent_mu/test.py [hunk 48]
```diff
@@ -0,0 +1,117 @@
...
+
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=1)
+        fig.save('vortex-snl-deviatoric.png')
+        for key,value in fig.label_to_slope.items():
+            print("%s, %f" % (key, value))
+            if key in velocity_labels:
+                self.assertTrue(fuzzyAbsoluteEqual(value, 2.0, .4))
+            else:
+                self.assertTrue(fuzzyAbsoluteEqual(value, 1.0, .5))
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/mms/linear-segregated/2d-vortex/spacedependent_mu/test.py:79]: Resolving this one.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests [hunk 49]
```diff
@@ -0,0 +1,25 @@
...
+    requirement = 'The system shall be able to solve fluid flow problems with k-epsilon turbulence model for a backward facing step, '
+    [result]
+      type = 'Exodiff'
+      input = 'BFS_ERCOFTAC.i'
+      exodiff = 'BFS_ERCOFTAC_exodus.e'
+      detail = 'and reach converged results with segregated solvers,'
+      abs_zero = 5e-6
+      rel_err = 5e-6
+      heavy = true
+    []
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests:14]: If we have drift in the wall function shear (for non-regression), we are unlikely to see this in the first iterations. We need this longer running tests unfortunately....

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i (hunk 25 above)
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:12]: Makes sense. Keeping them as is for now

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i (hunk 37 above)
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i:1]: We have it the same way in the nonlinear. I see the interest in spelling options clearly and fully in one test. Keeping it as is for now

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C [hunk 50]
```diff
@@ -0,0 +1,269 @@
...
+  params.addParam<bool>(
+      "linearized_model",
+      true,
+      "Boolean to determine if the problem should be use in a linear or nonlinear solve.");
+  MooseEnum wall_treatment("eq_newton eq_incremental eq_linearized neq", "neq");
+
+  params.addParam<MooseEnum>("wall_treatment",
+                             wall_treatment,
+                             "The method used for computing the wall functions "
+                             "'eq_newton', 'eq_incremental', 'eq_linearized', 'neq'");
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: Non-equilibrium uses one treatment here, all the rest use the others. We need to preserve all names for consistency with other kernels as mu_t will change regarding each of these methods

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C (hunk 3 above)
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:108]: Thanks. These vectors have one or two components. Reserving should make no difference or even slow down the process. Please advise

File: modules/navier_stokes/src/executioners/SIMPLESolveBase.C [hunk 51]
```diff
@@ -27,6 +27,8 @@ SIMPLESolveBase::validParams()
   params.addParam<SolverSystemName>("energy_system", "The solver system for the energy equation.");
   params.addParam<std::vector<SolverSystemName>>(
       "passive_scalar_systems", {}, "The solver system for each scalar advection equation.");
+  params.addParam<std::vector<SolverSystemName>>(
+      "turbulence_systems", {}, "The solver system for each surrogate turbulence equation.");
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/executioners/SIMPLESolveBase.C:31]: This will be deleted later on. Better to keep like this for now imo

File: modules/navier_stokes/src/executioners/SIMPLESolveBase.C [hunk 52]
```diff
@@ -380,6 +433,44 @@ SIMPLESolveBase::SIMPLESolveBase(Executioner & ex)
                                   "passive_scalar_equation_relaxation",
                                   "passive_scalar_absolute_tolerance"},
                                  false);
+
+  // We check for input errors with regards to the surrogate turbulence equations. At the same time,
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/executioners/SIMPLESolveBase.C:465]: Because they are surrogate variables (k-epsilon) that define the TKE and TKED

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i [hunk 53]
```diff
@@ -0,0 +1,437 @@
...
+    type = ParsedAux
+    variable = 'mu_eff'
+    coupled_variables = 'mu_t'
+    expression = 'mu_t + ${mu}'
+    execute_on = 'NONLINEAR'
+  []
+[]
+
+[Executioner]
+  type = PIMPLE
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i:397]: Yes, but I am already testing that. I want to test transients

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i [hunk 54]
```diff
@@ -0,0 +1,437 @@
+Re = 5100
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i:1]: This one is in the `linear-segreagated` folder one directory above

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i (hunk 26 above)
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/segregated/channel_ERCOFTAC.i:144]: Yes, but we don't need it for this a channel case. There is no need to test it here

**Review by grmnptr — CHANGES_REQUESTED** [review]
Thanks for pushing this large PR, I think it is getting really close! 
I have a few more things here though. If you are running short on time, I can help with it.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i (hunk 37 above)
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i:1]: I want complete test cases, because these are the cases from which people start from. I would prefer to keep this like it is. This is not a mistake, it is a conscious design decision based on feedback from users

File: framework/src/systems/LinearSystem.C [hunk 55]
```diff
@@ -107,6 +114,32 @@ LinearSystem::initialSetup()
...
+    std::vector<LinearFVFluxKernel *> fv_flux_kernels;
+    _fe_problem.theWarehouse()
+        .query()
+        .template condition<AttribSystem>("LinearFVFluxKernel")
+        .template condition<AttribThread>(tid)
+        .queryInto(fv_flux_kernels);
+
+    for (auto * fv_kernel : fv_flux_kernels)
+      fv_kernel->initialSetup();
+  }
```
[the remark this answers is not in the document]
Comment (tanoret) [reply framework/src/systems/LinearSystem.C:142]: I don't know why to do this or how this would improve the code. I can do the research in the code, but why is this effort worth it?

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C (hunk 50 above)
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: No. For `eq_newton` `eq_incremental` `eq_linearized` one uses the linear treatment to find `yPlus`, while they then defer in the way in which the turbulent viscosity is computed (kEpsilonViscosityAux). This allows us to have a universal selection of wall models for all kernels, which greatly simplify the code. This suggestion is not useful

[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: Also, this is already explained in the documentation

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentDiffusion.C [hunk 56]
```diff
@@ -0,0 +1,260 @@
...
+  NS::getWallBoundedElements(
+      _wall_boundary_names, _fe_problem, _subproblem, blockIDs(), _wall_bounded);
+}
+
+Real
+LinearFVTurbulentDiffusion::computeElemMatrixContribution()
+{
+  const auto face_arg = makeCDFace(*_current_face_info);
+  return computeFluxMatrixContribution() / _scaling_coeff(face_arg, determineState());
+}
```
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentDiffusion.C:57]: I cannot do this because the boundary conditions (near wall functions) do not propagate properly when defining the effective turbulent viscosity from the turbulent viscosity, which have the wall function. I am keeping this like this for now

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i (hunk 54 above)
[the remark this answers is not in the document]
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i:1]: I am not doing this. Both transient and steady cases test different phenomena and should not be merged. I will keep the folders as they are. Thank you for the suggestion

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i (hunk 14 above)
Comment (tanoret) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:403]: I would like to have complete working tests based on the feedback that I have received from our users. The include requires people accessing two files instead of one, which complicates the understanding. Thank you

**Comment by freiler** [comment]
Channel DNS Re_tau 590 comparison vs CFD benchmark code 
Velocity Profile:
image

TKE profile vs nonlinearSIMPLE and CFD benchmark (red):
image

**Comment by freiler** [comment]
Backward Facing Step comparison:

image

Skin friction coefficient:

image

**Comment by freiler** [comment]
There are two things to analyze which are 

1-Overdiffusion in TKE using non-equilibrium wall functions in the BFS case.
2-Velocity oscillations at the outlet of geometries (see picture below)

image

**Comment by GiudGiud** [comment]
> 2-Velocity oscillations at the outlet of geometries (see picture below) using the nonlinear model

the nonlinear FV? Are these oscillations in the new tests? If not we can create an issue for it.
I think we have some tests where we just use a dirichletBC on k/eps when outflow would be better

**Comment by grmnptr** [comment]
> > 2-Velocity oscillations at the outlet of geometries (see picture below) using the nonlinear model
> 
> the nonlinear FV? Are these oscillations in the new tests? If not we can create an issue for it. I think we have some tests where we just use a dirichletBC on k/eps when outflow would be better

Yeah it is the NL k-epsilon and this behavior got introduced in this PR, devel is fine. I think the main reason is that we added modifications to the full expansion of the stress tensor (should have been a fix).

File: framework/src/problems/FEProblemBase.C (hunk 2 above)
Comment (tanoret) [reply framework/src/problems/FEProblemBase.C]: Code removed

File: modules/navier_stokes/include/base/NavierStokesMethods.h [hunk 57]
```diff
@@ -184,4 +197,28 @@ wallHeatTransferCoefficient(const T1 & Nu, const T2 & k, const T3 & D_h)
...
+extern template Real computeShearStrainRateNormSquared<Real>(const Moose::Functor<Real> & u,
+                                                             const Moose::Functor<Real> * v,
+                                                             const Moose::Functor<Real> * w,
+                                                             const Moose::ElemArg & elem_arg,
+                                                             const Moose::StateArg & state);
+extern template ADReal computeShearStrainRateNormSquared<ADReal>(const Moose::Functor<ADReal> & u,
+                                                                 const Moose::Functor<ADReal> * v,
+                                                                 const Moose::Functor<ADReal> * w,
+                                                                 const Moose::ElemArg & elem_arg,
+                                                                 const Moose::StateArg & state);
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/include/base/NavierStokesMethods.h:223]: these are helpful if we are using these templates in multiple translation units. They are here to indicate that they are actually compiled in NavierStokesMethods.C and not to be compiled in every unit

File: modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C [hunk 58]
```diff
@@ -82,15 +83,26 @@ INSFVTurbulentViscosityWallFunction::boundaryValue(const FaceInfo & fi,
...
+    // if(fi.elem().vertex_average()(0) >= 0 && fi.elem().vertex_average()(1) > 0)
+    // {
+    //  _console << "wall_dist: " << wall_dist << std::endl;
+    //  _console << "parallel_speed: " << parallel_speed << std::endl;
+    //  _console << "u_tau: " << u_tau << std::endl;
+    //  _console << "rho: " << rho << std::endl;
+    //  _console << "mu: " << mu << std::endl;
+    //  _console << "mu_wall: " << mu_wall << std::endl;
+    //  _console << "------------------------" << std::endl;
+    // }
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C]:
```suggestion
```

File: modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C [hunk 59]
```diff
@@ -424,6 +422,7 @@ SIMPLESolveNonlinearAssembly::solveAdvectedSystem(const unsigned int system_num,
   {
     _console << system.name() << " system matrix" << std::endl;
     mmat.print();
+    rhs.print();
```
Comment (GiudGiud) [inline modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C:348]:
```suggestion
    _console << system.name() << " RHS vector" << std::endl;
    rhs.print();
```

Comment (GiudGiud) [reply modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C:348]: we should add some info that this is the "relaxed one"

File: modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C [hunk 60]
```diff
@@ -308,12 +308,10 @@ SIMPLESolveNonlinearAssembly::solveMomentumPredictor()
...
     }
-  }
 
-  for (const auto system_i : index_range(_momentum_systems))
-  {
-    NonlinearImplicitSystem & momentum_system =
-        libMesh::cast_ref<NonlinearImplicitSystem &>(_momentum_systems[system_i]->system());
+    // We clear the gradient caches of the velocity variables since the deviatoric terms will
+    // need the updated cell gradients. This will also help the turbulence routines which will
+    // need the latest cell gradients.
```
Comment (GiudGiud) [inline modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C]: which call does this gradient reset?

File: framework/src/systems/LinearSystem.C (hunk 55 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/src/systems/LinearSystem.C:137]: reminder. should be correct to just add suggestion

File: modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h [hunk 61]
```diff
@@ -57,12 +57,16 @@ class LinearAssemblySegregatedSolve : public SIMPLESolveBase
...
+  /// @param relax_fields (optional) A boolean flag to indicate whether to relax fields during the solve. Default value is false.
+  /// @param field_relaxation (optional) The relaxation factor for fields if relax_fields is true. Default value is 1.0.
   /// @return The normalized residual norm of the equation.
   std::pair<unsigned int, Real> solveAdvectedSystem(const unsigned int system_num,
                                                     LinearSystem & system,
                                                     const Real relaxation_factor,
                                                     libMesh::SolverConfiguration & solver_config,
-                                                    const Real abs_tol);
+                                                    const Real abs_tol,
+                                                    const bool relax_fields = false,
```
Comment (GiudGiud) [inline modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h]:
```suggestion
```
just test the relaxation factor in the beginning of the routine

File: modules/navier_stokes/include/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.h [hunk 62]
```diff
@@ -0,0 +1,74 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "LinearFVAdvectionDiffusionBC.h"
+#include "NS.h"
+
+/**
+ * Class implementing a Dirichlet boundary condition for linear finite
+ * volume variables. This is only applicable for advection-diffusion problems.
```
Comment (GiudGiud) [inline modules/navier_stokes/include/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.h]:
```suggestion
 * Class implementing a Dirichlet boundary condition for the turbulent viscosity wall function
 * in a RANS simulation
```

File: modules/navier_stokes/include/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.h [hunk 63]
```diff
@@ -0,0 +1,74 @@
...
+  const Moose::Functor<Real> & _k;
+
+  /// C_mu turbulent coefficient
+  const Real _C_mu;
+
+  /// Method used for wall treatment
+  NS::WallTreatmentEnum _wall_treatment;
+
+  // Mu_t evaluated at y+=30 for blending purposes
+  const Real _mut_30 =
```
Comment (GiudGiud) [inline modules/navier_stokes/include/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.h:72]:
```suggestion
  static constexpr Real _mut_30 =
```
might work?

File: modules/navier_stokes/include/linearfvkernels/LinearFVTKEDSourceSink.h [hunk 64]
```diff
@@ -0,0 +1,87 @@
...
+  /// Value of the first epsilon closure coefficient
+  const Real _C1_eps;
+
+  /// Value of the second epsilon closure coefficient
+  const Real _C2_eps;
+
+  /// C_mu constant
+  const Real _C_mu;
+
+  // Production Limiter Constant
```
Comment (GiudGiud) [inline modules/navier_stokes/include/linearfvkernels/LinearFVTKEDSourceSink.h]:
```suggestion
  /// Production Limiter Constant
```

File: modules/navier_stokes/include/linearfvkernels/LinearFVTKESourceSink.h [hunk 65]
```diff
@@ -0,0 +1,80 @@
...
+  /// Linearized model?
+  const bool _linearized_model;
+
+  /// Method used for wall treatment
+  NS::WallTreatmentEnum _wall_treatment;
+
+  /// C_mu constant
+  const Real _C_mu;
+
+  // Production Limiter Constant
```
Comment (GiudGiud) [inline modules/navier_stokes/include/linearfvkernels/LinearFVTKESourceSink.h]:
```suggestion
  /// Production Limiter Constant
```

File: modules/navier_stokes/src/auxkernels/RANSYPlusAux.C (hunk 45 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/auxkernels/RANSYPlusAux.C]: it s fine that way.

you would convert the arguments as well to make it work with Real. I m saying Real because auxkernels dont need derivatives

[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/auxkernels/RANSYPlusAux.C]: in fact we are messing up in the constructor... we should be retrieving all these functors as Real!

File: modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C [hunk 66]
```diff
@@ -354,7 +363,9 @@ LinearAssemblySegregatedSolve::solveAdvectedSystem(const unsigned int system_num
                                                    LinearSystem & system,
                                                    const Real relaxation_factor,
                                                    SolverConfiguration & solver_config,
-                                                   const Real absolute_tol)
+                                                   const Real absolute_tol,
+                                                   const bool relax_fields,
+                                                   const Real field_relaxation)
 {
```
Comment (GiudGiud) [inline modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C]:
```suggestion
                                                   const Real field_relaxation)
{
  const auto relax_fields = (field_relaxation != 1);
```

File: modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C [hunk 67]
```diff
@@ -496,6 +526,36 @@ LinearAssemblySegregatedSolve::solve()
...
+    // If we have turbulence equations, solve them here.
+    // The turbulent viscosity depends on the value of the turbulence surrogate variables
+    if (_has_turbulence_systems)
+    {
+      // We set the preconditioner/controllable parameters through petsc options. Linear
+      // tolerances will be overridden within the solver.
+      Moose::PetscSupport::petscSetOptions(_turbulence_petsc_options, solver_params);
+      for (const auto i : index_range(_turbulence_system_names))
+      {
+        ns_residuals[momentum_residual.size() + 1 + _has_energy_system + i] =
```
Comment (GiudGiud) [inline modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C]:
```suggestion
        ns_residuals[momentum_residual.size() + 1 + _has_energy_system + _has_solid_energy_system + i] =
```

File: modules/navier_stokes/src/executioners/SIMPLESolveBase.C (hunk 51 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/executioners/SIMPLESolveBase.C:33]: This line is good.
It s in the NonlinearSolve...Assembly that this parameter should be suppressed because it s ignored

File: modules/navier_stokes/src/executioners/SIMPLESolveBase.C [hunk 68]
```diff
@@ -472,6 +541,56 @@ SIMPLESolveBase::SIMPLESolveBase(Executioner & ex)
...
+                                                     *this,
+                                                     _turbulence_petsc_options);
+
+    _turbulence_linear_control.real_valued_data["rel_tol"] = getParam<Real>("turbulence_l_tol");
+    _turbulence_linear_control.real_valued_data["abs_tol"] = getParam<Real>("turbulence_l_abs_tol");
+    _turbulence_linear_control.int_valued_data["max_its"] =
+        getParam<unsigned int>("turbulence_l_max_its");
+  }
+  else
+    checkDependentParameterError("turbulence_systems",
```
Comment (GiudGiud) [inline modules/navier_stokes/src/executioners/SIMPLESolveBase.C:582]: thanks to this line, all you need to disable the whole group of turbulence parameters for the NL assembly is to suppress this one parameter

File: modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C [hunk 69]
```diff
@@ -0,0 +1,196 @@
...
+}
+
+Real
+LinearFVTurbulentViscosityWallFunctionBC::computeTurbulentViscosity() const
+{
+
+  // Utility functions
+  const Real wall_dist = computeCellToFaceDistance();
+  const auto re = makeElemArg(&_current_face_info->elem());
+  const auto t = Moose::StateArg(1, Moose::SolutionIterationType::Nonlinear); // determineState();
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C]:
```suggestion
  const auto t_prev = Moose::StateArg(1, Moose::SolutionIterationType::Nonlinear); // determineState();
```
or add a comment at least that we are lagging in terms of iterations

File: modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C [hunk 70]
```diff
@@ -0,0 +1,196 @@
...
+    // _current_face_info->elem().vertex_average()(1) > 0)
+    // {
+    //  _console << "wall_dist: " << wall_dist << std::endl;
+    //  _console << "parallel_speed: " << parallel_speed << std::endl;
+    //  _console << "u_tau: " << u_tau << std::endl;
+    //  _console << "rho: " << rho << std::endl;
+    //  _console << "mu: " << mu << std::endl;
+    //  _console << "mu_wall: " << mu_wall << std::endl;
+    //  _console << "------------------------" << std::endl;
+    // }
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C]:
```suggestion
```

File: modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C [hunk 71]
```diff
@@ -0,0 +1,196 @@
...
+  Real mut_log = 0.0; // turbulent log-layer viscosity
+  Real mu_wall = 0.0; // total wall viscosity to obtain the shear stress at the wall
+
+  if (_wall_treatment == NS::WallTreatmentEnum::EQ_NEWTON)
+  {
+    // Full Newton-Raphson solve to find the wall quantities from the law of the wall
+    const auto u_tau = NS::findUStar<Real>(mu, rho, parallel_speed, wall_dist);
+    y_plus = wall_dist * u_tau * rho / mu;
+    mu_wall = rho * Utility::pow<2>(u_tau) * wall_dist / parallel_speed;
+    mut_log = mu_wall - mu;
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C]: this last line is repeated 4 times, let's move it outside the if

File: modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C [hunk 72]
```diff
@@ -0,0 +1,196 @@
...
+  // Ths will not contribute to the matrix from the value considering that
+  // the value is independent of the solution.
+  return 0.0;
+}
+
+Real
+LinearFVTurbulentViscosityWallFunctionBC::computeBoundaryValueRHSContribution() const
+{
+  // Fetch the boundary value from the provided functor.
+  return this->computeTurbulentViscosity();
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C]: which equation is this contributing to?

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C [hunk 73]
```diff
@@ -0,0 +1,199 @@
...
+      mooseAssert(distance > 0, "Should be at a non-zero distance");
+
+      Real y_plus;
+      if (_wall_treatment == NS::WallTreatmentEnum::NEQ) // Non-equilibrium / Non-iterative
+        y_plus = distance * std::sqrt(std::sqrt(_C_mu) * TKE) * rho / mu;
+      else // Equilibrium / Iterative
+      {
+        const auto parallel_speed = NS::computeSpeed<Real>(
+            velocity - velocity * face_info_vec[i]->normal() * face_info_vec[i]->normal());
+        y_plus = NS::findyPlus<Real>(mu, rho, std::max(parallel_speed, 1e-10), distance);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C:161]: this is the fixed point approach. but the user could have asked for the newton or the linearized approach

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C [hunk 74]
```diff
@@ -0,0 +1,233 @@
...
+    // Convenient variables
+    Real production = 0.0;
+
+    // Compute production of TKE
+    const auto symmetric_strain_tensor_sq_norm =
+        NS::computeShearStrainRateNormSquared<Real>(_u_var, _v_var, _w_var, elem_arg, state);
+    Real production_k = _mu_t(elem_arg, state) * symmetric_strain_tensor_sq_norm;
+
+    // Limit TKE production (needed for flows with stagnation zones)
+    const Real production_limit = _C_pl * rho * _var.getElemValue(*_current_elem_info, state);
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C]: he's not wrong

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C (hunk 50 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: so y_plus in the turbulent viscosity calculation is different than in the kernels? Dont we risk some inconsistency?

with the 1e-8 jump at y+=5 that could cause trouble

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/segregated/tests [hunk 75]
```diff
@@ -236,20 +227,8 @@
       abs_zero = 1e-6
       cli_args = 'Executioner/num_iterations=10 Outputs/file_base=lid-driven-turb-energy-wall_short'
     []
-    [result_physics]
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/segregated/tests:239]: why are you removing this? We're losing coverage on the turbulence physics

Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/segregated/tests:239]: nevermind, moved to separate folder

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/physics/tests [hunk 76]
```diff
@@ -0,0 +1,61 @@
...
+    # lid-driven-turb-inc-wall.i      incremental          segregated     no
+    # lid-driven-turb-no-wall.i       none                 segregated     no
+    # lid-driven-turb-no-wall.i       none in log regime   segregated     no
+    # lid-driven-turb-non-eq-bulk.i   non-eq-bulk          segregated     no
+    # lid-driven-turb-energy.i        std                  segregated     yes      none
+    # lid-driven-turb-energy-wall.i   std                  segregated     yes      log-regime
+    # lid-driven-turb-energy-wall.i   linear               segregated     yes      linear
+    # lid-driven-turb-energy-wall.i   std in log region    segregated     yes      incremental
+    # lid-driven-turb-capped.i        std + capped mixing  segregated     no
+    # lid-driven-turb-std-wall-nonlinear.i std             fully-coupled  no
```
Comment (GiudGiud) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/physics/tests]:
```suggestion
```
we dont really need it with few tests

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C (hunk 50 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: aactually it s done this way for NL assembly

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentAdvection.C [hunk 77]
```diff
@@ -0,0 +1,179 @@
...
+#include "NS.h"
+
+registerMooseObject("NavierStokesApp", LinearFVTurbulentAdvection);
+
+InputParameters
+LinearFVTurbulentAdvection::validParams()
+{
+  InputParameters params = LinearFVScalarAdvection::validParams();
+  params.addClassDescription("Represents the matrix and right hand side contributions of an "
+                             "advection term for a turbulent variable.");
```
Comment (GiudGiud) [inline modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentAdvection.C]:
```suggestion
                             "advection term for a turbulence variable.");
```
or "for a turbulence equation"

File: modules/navier_stokes/include/linearfvkernels/LinearFVTurbulentAdvection.h [hunk 78]
```diff
@@ -0,0 +1,45 @@
...
+  std::pair<Real, Real> _advected_interp_coeffs;
+
+  /// The interpolation method to use for the advected quantity
+  Moose::FV::InterpMethod _advected_interp_method;
+
+  /// Wall boundaries
+  const std::vector<BoundaryName> & _wall_boundary_names;
+
+  /// Maps for wall bounded elements
+  std::map<const Elem *, bool> _wall_bounded;
```
Comment (GiudGiud) [inline modules/navier_stokes/include/linearfvkernels/LinearFVTurbulentAdvection.h]: remind me why the bool? we only check whether the element is in the map (means bounded), never the value of boolean

**Review by GiudGiud — DISMISSED** [review]
I think we may want to discuss taking care of these changes for you @tanoret

what's the reason behind re-golding all the entire nonlinear assembly turbulence cases?
is it the missing deviatoric term? Should we just set those cases to not use the deviatoric term then?

File: modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h (hunk 61 above)
Comment (GiudGiud) [reply modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h]: see comment in source for tentative implementation

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i (hunk 37 above)
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i:1]: Users should use the Physics syntax. I don't see the need for complete inputs using the old syntax.

I dont want to be debugging 400 line input files because someone was inconsistent between their interpolation method, wall function, or wrote v = u instead of v = v

**Comment by GiudGiud** [comment]
Looking at the code, it seems to me that if we put the wall-bounded element in a different block, we could avoid all these map lookups ? @grmnptr @tanoret is that your impression as well? 
We could keep the current treatment in this PR and re-factor using block restriction later. 

EDIT: I can investigate that using the NL k-epsilon. No need to ponder this here.

File: framework/src/systems/LinearSystem.C [hunk 79]
```diff
@@ -78,6 +79,9 @@ LinearSystem::LinearSystem(FEProblemBase & fe_problem, const std::string & name)
     _sys(fe_problem.es().add_system<LinearImplicitSystem>(name)),
     _rhs_time_tag(-1),
     _rhs_time(NULL),
+    // We add this vector tag so that objects acting on the aux system inheriting
+    // from the tagging interface can still be used without any nonlinear systems
+    // _rhs_non_time_tag(_fe_problem.addVectorTag("NONTIME")),
```
Comment (grmnptr) [inline framework/src/systems/LinearSystem.C]: Looks like this is not needed. I think we should remove it.

File: modules/navier_stokes/include/base/NavierStokesMethods.h (hunk 57 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/include/base/NavierStokesMethods.h:223]: Sounds good to me!

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 80]
```diff
@@ -127,32 +130,111 @@ findyPlus(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
+  T grad_xy = 0.0;
+  T grad_xz = 0.0;
+  T grad_yx = 0.0;
+  T grad_yy = 0.0;
+  T grad_yz = 0.0;
+  T grad_zx = 0.0;
+  T grad_zy = 0.0;
+  T grad_zz = 0.0;
+
+  T trace = 2.0 * Sij_xx / 3.0;
```
Comment (grmnptr) [inline modules/navier_stokes/src/base/NavierStokesMethods.C]:
```suggestion
  T trace = Sij_xx / 3.0;
```

Comment (grmnptr) [reply modules/navier_stokes/src/base/NavierStokesMethods.C]: Sorry, I was wrong, in the first round I didn't see the 2 multiplier here:
```
const T Sij_xx = 2.0 * grad_u(0);
```
The term is -2/3*div(u) which will be already satisfied with this. Sorry for the hassle.

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 81]
```diff
@@ -127,32 +130,111 @@ findyPlus(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
+  {
+    const auto & grad_v = (*v).gradient(elem_arg, state);
+    Sij_xy = grad_u(1) + grad_v(0);
+    Sij_yy = 2.0 * grad_v(1);
+
+    grad_xy = grad_u(1);
+    grad_yx = grad_v(0);
+    grad_yy = grad_v(1);
+
+    trace += 2.0 * Sij_yy / 3.0;
```
Comment (grmnptr) [inline modules/navier_stokes/src/base/NavierStokesMethods.C]:
```suggestion
    trace += Sij_yy / 3.0;
```

File: modules/navier_stokes/src/base/NavierStokesMethods.C [hunk 82]
```diff
@@ -127,32 +130,111 @@ findyPlus(const ADReal & mu, const ADReal & rho, const ADReal & u, const Real di
...
+      Sij_yz = grad_v(2) + grad_w(1);
+      Sij_zz = 2.0 * grad_w(2);
+
+      grad_xz = grad_u(2);
+      grad_yz = grad_v(2);
+      grad_zx = grad_w(0);
+      grad_zy = grad_w(1);
+      grad_zz = grad_w(2);
+
+      trace += 2.0 * Sij_zz / 3.0;
```
Comment (grmnptr) [inline modules/navier_stokes/src/base/NavierStokesMethods.C]:
```suggestion
      trace += Sij_zz / 3.0;
```

File: modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C (hunk 72 above)
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvbcs/LinearFVTurbulentViscosityWallFunctionBC.C]: This method will not contribute to any equation. I think these got added in case someone comes up with something that has mu_t as an advected quantity.

We could potentially disable these functions to warn the user not to meddle with mut in an equation.

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C (hunk 73 above)
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKEDSourceSink.C:161]: The way I understand it, for the source-sink it only matters if it is Uq/NonEq. The only place the iterative method makes a difference is the wall function for mut. I think thel ogic is correct here.

File: modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C (hunk 50 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTKESourceSink.C:43]: Yeah I am fine with this, makes it easier for the user to have just one parameter at the top of the input file.

File: modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentDiffusion.C (hunk 56 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/src/linearfvkernels/LinearFVTurbulentDiffusion.C:57]: Aaaaa okay, I understand. So for the laminar part, you want the original contribution without bounding. Sounds good to me!

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i (hunk 54 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/BFS_ERCOFTAC.i:1]: Fine.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated/tests [hunk 83]
```diff
@@ -0,0 +1,27 @@
+[Tests]
+  design = 'LinearFVTurbulentAdvection.md LinearFVTurbulentDiffusion.md LinearFVTKESourceSink.md LinearFVTKEDSourceSink.md kEpsilonViscosityAux.md INSFVTurbulentViscosityWallFunction.md'
+  issues = '#29846'
+  [BFS_ERCOFTAC_linear]
+    requirement = 'The system shall be able to solve fluid flow problems with the linear k-epsilon turbulence model for a backward facing step, '
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated/tests]:
```suggestion
    requirement = 'The system shall be able to solve steady-state fluid flow problems with the linear k-epsilon turbulence model for a backward facing step, '
```

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i (hunk 14 above)
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:398]: Fine.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/tests [hunk 84]
```diff
@@ -0,0 +1,29 @@
...
+      type = 'Exodiff'
+      input = 'channel_ERCOFTAC.i'
+      exodiff = 'channel_ERCOFTAC_out.e'
+      detail = 'and reach converged results with segregated solvers,'
+      abs_zero = 5e-6
+      rel_err = 5e-6
+      heavy = true
+      recover = false # we don't support recovery for PIMPLE yet
+      max_threads = 1 # see libmesh issue #3808
+    []
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/tests]: What do you think @GiudGiud ? I am fine both ways, just trying to offload some pressure from our testing system.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/tests [hunk 85]
```diff
@@ -0,0 +1,27 @@
+[Tests]
+  design = 'LinearFVTurbulentAdvection.md LinearFVTurbulentDiffusion.md LinearFVTKESourceSink.md LinearFVTKEDSourceSink.md kEpsilonViscosityAux.md INSFVTurbulentViscosityWallFunction.md'
+  issues = '#29846'
+  [channel_ERCOFTAC_linear]
+    requirement = 'The system shall be able to solve fluid flow problems with k-epsilon turbulence model for a standard channel with linear FV discretization, and'
```
Comment (grmnptr) [inline modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/tests]:
```suggestion
    requirement = 'The system shall be able to solve steady-state fluid flow problems with k-epsilon turbulence model for a standard channel with linear FV discretization, and'
```

**Review by grmnptr — CHANGES_REQUESTED** [review]
Okay, this is getting really close!
Based on yesterday's debugging sesssion I think we should add one more test case (I can add it this weekend) not physical, just regression:
A channel:
```
| fluid | solid  |
|   ^    |           |
|   ^    |           |
|   ^    |           |
|   ^    |           |
```
Solid can be blank. I expect this to work considering our default elemen/face info ordering. Then It would be nice to do the opposite:

```
| solid | fluid  |
|          |   ^    |
|          |   ^    |
|          |   ^    |
|          |   ^    |
```
In this case, the element-side of face info will not be on the fluid domain at the boundary.
This is just to test that the algorithms fetching the wall-bounded elements/sides etc work with block restriction.

**Comment by grmnptr** [comment]
Oh and one more thing. We should prevent users using the nonlinear machinery for computing nut. It will not give the correct results. It is not trivial because everything is going through functors now.

File: framework/src/systems/LinearSystem.C (hunk 55 above)
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/src/systems/LinearSystem.C:137]: Similarly to the regular `FVKernels`, we register the attribute a step higher, so the lookup with `LinearFVKernel` would not return anything.

File: modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C (hunk 60 above)
Comment (grmnptr) [reply modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C]: Dangling comment from a modified line. Well I added something here which got removed later.

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/gold/channel_ERCOFTAC_out.e
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated/gold/channel_ERCOFTAC_out.e:1]: Changed some of these tests to remove short version. I measured <3s on the ones I changed

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests (hunk 49 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests]: Addressed by running the longer one. Lienar FV is fast enough imo

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i (hunk 37 above)
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/linear-segregated/lid-driven-turb-std-wall.i:1]: I ll clean this up in a separate PR.

For what it's worth, the nonlinear FV tests are way worse on this aspect

File: modules/navier_stokes/src/auxkernels/ShearStressNormAux.C [hunk 86]
```diff
@@ -0,0 +1,42 @@
...
+#include "libmesh/nonlinear_solver.h"
+
+registerMooseObject("NavierStokesApp", ShearStressNormAux);
+
+InputParameters
+ShearStressNormAux::validParams()
+{
+  InputParameters params = AuxKernel::validParams();
+  params.addClassDescription(
+      "Calculates the turbulent viscosity according to the k-epsilon model.");
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/src/auxkernels/ShearStressNormAux.C]: that aux kernel got removed

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests [hunk 87]
```diff
@@ -0,0 +1,29 @@
...
+      type = 'Exodiff'
+      input = 'BFS_ERCOFTAC.i'
+      exodiff = 'BFS_ERCOFTAC_short.e'
+      detail = 'and pass debugging checks.'
+      abs_zero = 5e-6
+      rel_err = 5e-6
+      cli_args = 'Executioner/dt=1.0 Executioner/num_steps=1 Outputs/exodus/file_base=BFS_ERCOFTAC_short'
+      recover = false # we don't support recovery for PIMPLE yet
+      max_threads = 1 # see libmesh issue #3808
+    []
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests]: only have result, it's quite fast

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i [hunk 88]
```diff
@@ -0,0 +1,440 @@
+H = 1 #halfwidth of the channel
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/linear-segregated-transient/channel_ERCOFTAC.i:1]: it is the half-width in this case. leaving as is

File: modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/physics/tests (hunk 76 above)
[the remark this answers is not in the document]
Comment (GiudGiud) [reply modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/physics/tests]: removed

**Review by grmnptr — APPROVED** [review]
Looks good to me!

**Comment by GiudGiud** [comment]
🎉
