### PR TITLE
Retain multiplicity of coincident Dirac points

### LINKED ISSUE #7060: Need a way to track multiplicity of Dirac Points
### Description of the enhancement or error report
If a similar Point (within `libMesh::TOLERANCE`) is passed to `addPoint` in a DiracKernel it is silently dropped.

### Rationale for the enhancement or information for reproducing the error
A multiplicity field for each Point should be incremented if a similar point is passed in. The value should be available to `DiracKernel::computeQpResidual()`

Workarounds such as maps indexed by Points do _not_ work, as the Points being looked up are not necessarily _exactly_ the same (only within the tolerance). Reimplementing the tolerance check in user code is not a good solution either (any changes in the framework tolerance check would make the behaviors inconsistent and the residuals wrong).

### Identified impact
This will make implementing residuals easier.

### PR DESCRIPTION
**Pull request by dschwen**
I'm sure this needs discussion...
For now I'm abusing Civet to test this.

Closes #7060

### CODE REVIEW

**Comment by dschwen** [comment]
@bwspenc Bison fails with this PR. The alternative would be to make `_current_multiplicity` available to the QP residual and jacobian methods and have the developers multiply it on by themselves.

**Comment by friedmud** [comment]
Or have a flag for switching between the two ways of dealing with multiplicity....

File: framework/src/dirackernels/DiracKernelInfo.C [hunk 1]
```diff
@@ -33,11 +33,27 @@ DiracKernelInfo::addPoint(const Elem * elem, Point p)
 {
   _elements.insert(elem);
 
-  if (!hasPoint(elem, p))
+
+  auto & multi_point_list = _points[elem];
```
Comment (jwpeterson) [inline framework/src/dirackernels/DiracKernelInfo.C]: One line in your whole PR?  You trying to piss off @permcody here?

Comment (dschwen) [inline framework/src/dirackernels/DiracKernelInfo.C]: Just added another one to make it well rounded.

**Comment by dschwen** [comment]
Ugh, I'm not quite done. I cannot use `_qp` to index into the local dirac kernel info data!

File: framework/src/dirackernels/DiracKernelInfo.C [hunk 2]
```diff
@@ -33,11 +33,27 @@ DiracKernelInfo::addPoint(const Elem * elem, Point p)
...
+
+  const unsigned npoint = multi_point_list.first.size();
```
Comment (permcody) [inline framework/src/dirackernels/DiracKernelInfo.C]: Didn't you chew me out earlier for leaving off the `int`? Right back at you!

Comment (dschwen) [inline framework/src/dirackernels/DiracKernelInfo.C]: touché

File: framework/src/dirackernels/DiracKernelInfo.C (hunk 1 above)
Comment (dschwen) [inline framework/src/dirackernels/DiracKernelInfo.C]: So, should I remove those?

File: framework/include/dirackernels/DiracKernel.h [hunk 3]
```diff
@@ -216,6 +216,9 @@ class DiracKernel :
   /// Derivative of u_dot wrt u
   const VariableValue & _du_dot_du;
 
+  /// fully consider duplicate points
+  const bool _allow_duplicate_points;
```
Comment (friedmud) [inline framework/include/dirackernels/DiracKernel.h]: Which way does this go?  Basically, what does `allow` mean?  Does it mean that duplicates are ignored or that they're counted and then multiplied by the residuals?

How about: `_multiply_contribution_by_point_multiplicity` or something more descriptive?

**Comment by friedmud** [comment]
@dschwen Is it possible that people might want to deal with the multiplicity themselves?  i.e. maybe there are different contributions from each of the multiple points (that are at the same position)?

Maybe the thing to do here is just to count the multiplicity and make it available so people can do with it what they want.  You could use it to multiply your residual contribution.

**Comment by dschwen** [comment]
@friedmud, yeah, I thought about that (i.e. having  `_current_multiplicity` member). But I don't quite see the application for that TBH. IMO you either drop duplicates or you don't. If you keep duplicates the code now does the right thing automatically. The concept of _multiplicity_ is not even revealed to the user. For the user it looks like the duplicate points are never dropped.

File: framework/include/dirackernels/DiracKernel.h (hunk 3 above)
Comment (dschwen) [inline framework/include/dirackernels/DiracKernel.h]: I'd rather go for the opposite, `drop_duplicate_points`. Again, I don't really want to expose "multiplicity" to the user. For the user _not dropping duplicate points_ is the same thing as "multiplying contribution by point multiplicity". Only the latter sound much more complicated IMO.

**Comment by friedmud** [comment]
@dschwen I've thought about it a bit more and I agree.  There would be no way to differentiate the different "points" even if you wanted to.

How about my comment on changing the name of that flag?

File: framework/include/dirackernels/DiracKernel.h (hunk 3 above)
Comment (friedmud) [inline framework/include/dirackernels/DiracKernel.h]: Ok... drop `_drop_duplicate_points` sounds good.

File: framework/src/dirackernels/DiracKernelInfo.C [hunk 4]
```diff
@@ -33,11 +33,27 @@ DiracKernelInfo::addPoint(const Elem * elem, Point p)
...
+  const unsigned int npoint = multi_point_list.first.size();
+  mooseAssert(npoint == multi_point_list.second.size(), "Different sizes for location and multiplicity data");
+
+  for (unsigned int i = 0; i < npoint; ++i)
   {
-    std::vector<Point> & point_list = _points[elem];
-    point_list.push_back(p);
+    Real delta = (multi_point_list.first[i] - p).norm_sq();
+
+    if (delta < TOLERANCE*TOLERANCE)
```
Comment (friedmud) [inline framework/src/dirackernels/DiracKernelInfo.C]: This `TOLERANCE*TOLERANCE` is in a couple of places... can you codify this into one function so that these don't get out of sync?

**Comment by dschwen** [comment]
I've removed the two C++11lines in a separate commit so it can be easily reverted.

**Comment by bwspenc** [comment]
@dschwen Did you resolve the issue with BISON?  It looks like it's passing now.  It's not really clear to me what this commit does or why it would affect BISON.

**Comment by dschwen** [comment]
Everything I added needs to be activated by adding drop_duplicate_points =
false in the input file (for each dirackernel individually).
We should talk when you are back. I need a better understanding why the
Contact stuff adds duplicate points in the first place.

**Comment by dschwen** [comment]
Getting rid of the Dirac contact system would open the door to make this behavior the default. But let's discuss later.

**Comment by permcody** [comment]
👍
