### PR TITLE
Clear data in MooseMesh::cacheInfo to assure the correct reentering

### LINKED ISSUE #13799: MooseMesh::cacheInfo() reentering when using distributed mesh
## Bug Description
I have a test having a nodal postprocessor running with distributed mesh. It runs fine with replicated mesh but get an assertion error saying a coupled variable value on a node is size 0. After spending lots of time looking into it, it appears on that node, the connected subdomains is wrong, `1 2 3` instead of `1 2`. Adding some debug print-outs shows that the node-subdomain connection information is correct the first time we call that function in `SetupMeshCompleteAction::completeSetup` but not the second time. I am guessing the node IDs get renumbered and the left-over in the previous map was kept. If I add two lines like
```
  _subdomain_boundary_ids.clear();
  _block_node_list.clear();
```
my test can run fine.

## Steps to Reproduce
I will try to come up a test. But I think adding the two lines should be a right thing to do.

## Impact
My bad luck test triggering this bug.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #13799.

### CODE REVIEW

**Comment by YaqiWang** [comment]
The failing test can be found at https://moosebuild.inl.gov/job/196016/. I verified that with this fix, the crash can be fixed.

**Comment by YaqiWang** [comment]
We have a test accidentally covered this! The old expected screen output is wrong.

**Review by permcody — APPROVED** [review]

File: framework/src/outputs/ConsoleUtils.C [hunk 1]
```diff
@@ -96,8 +96,14 @@ outputMeshInformation(FEProblemBase & problem, bool verbose)
         << std::setw(console_field_width)
         << "  Num Partitions: " << static_cast<std::size_t>(mesh.n_partitions()) << '\n';
     if (problem.n_processors() > 1)
-      oss << std::setw(console_field_width) << "  Partitioner: " << moose_mesh.partitionerName()
-          << (moose_mesh.isPartitionerForced() ? " (forced) " : "") << '\n';
+    {
+      oss << std::setw(console_field_width) << "  Partitioner: ";
+      if (moose_mesh.isCustomPartitionerRequested())
+        oss << "custom";
```
Comment (permcody) [inline framework/src/outputs/ConsoleUtils.C]: I don't see the point of this. The source of the "partitionerName" is `MooseMesh::partitionerName` or arguably the _partitioner instance itself. Perhaps we can look into fixing it in the right spot?

**Review by permcody — CHANGES_REQUESTED** [review]

**Comment by permcody** [comment]
As far as your caching fix goes. That looks ok and is also interesting that we haven't run into that before. Perhaps because both of those data structures are maps so they usually don't change?

File: framework/src/outputs/ConsoleUtils.C (hunk 1 above)
Comment (YaqiWang) [reply framework/src/outputs/ConsoleUtils.C]: Problem is that _partitioner may not have a name and its name is not like the type we put in here for other cases.

**Comment by YaqiWang** [comment]
Possibly. In my case I hit an assertion in dbg mode but opt seems running ok.

File: framework/src/outputs/ConsoleUtils.C (hunk 1 above)
Comment (permcody) [reply framework/src/outputs/ConsoleUtils.C]: Well perhaps we should fix that... Too much scope for this PR? I could put @fdkong on this. The Partitioner base class has a name so we really should be pulling it from there (encapsulation). Even putting this logic into the other method would be a little better in case other methods access that method directly.

Comment (YaqiWang) [reply framework/src/outputs/ConsoleUtils.C]: `libMesh::Partitioner` does not have a name. I will drop this commit because I really want the other one merged.

**Comment by YaqiWang** [comment]
@permcody This is ready.

**Review by fdkong — APPROVED** [review]

**Review by permcody — APPROVED** [review]
