### PR TITLE
Enhance XFEM capabilities for moving interface problems

### LINKED ISSUE #11259: Enhance XFEM capability for moving interface problems
## Rationale
Current X-FEM implementation for material interface problems has several limitations
1. For stationary interfaces, X-FEM cannot selectively apply the constraint on a subset of interfaces which are generated by multiple mesh cutters. This makes X-FEM not be able to represent cracks and material interfaces in one problem.
2. X-FEM does not work with moving interfaces problem for which the entire cut locations will move. Since X-FEM doesn't store original uncut mesh, we need heal the cut mesh first and then apply cutter at new position. 

## Description
New capabilities:
1. The constraint ties with cutter and only apply it on specific interface.
2. Add healing capability for moving interface problems and the healing is managed by each mesh cutter.

## Impact
Some changes related to XFEM module and some very minor changes in framework(constraintWarehouse, ElemElemConstraint). X-FEM tests input syntax changes, but does not affect the results.

### PR DESCRIPTION
**Pull request by jiangwen84**
Some new capabilities are added to X-FEM

1. The constraint ties with cutter and only apply it on specific interface.
2. Add healing capability for moving interface problems and the healing is managed by each mesh cutter.

closes #11259

The codes have been tested on Rod to pass the valgrind tests:-)

### CODE REVIEW

File: framework/include/constraints/ElemElemConstraint.h [hunk 1]
```diff
@@ -59,10 +59,17 @@ class ElemElemConstraint : public Constraint,
    */
   virtual void computeJacobian();
 
+  /**
+   * Get the interface ID
+   */
+  virtual const unsigned int & getInterfaceID() const { return _interface_id; };
```
Comment (permcody) [inline framework/include/constraints/ElemElemConstraint.h]: Minor: const ref to an unsigned int is overkill. You might as well just return the unsigned int by value. Also, do you really want this to be virtual?

File: modules/xfem/src/base/XFEM.C [hunk 2]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+
+  std::set<Node *> nodes_to_delete;
+  std::set<Node *> nodes_to_delete_displaced;
+  std::set<unsigned int> cutelems_to_delete;
+
+  for (unsigned int i = 0; i < _geometric_cuts.size(); ++i)
+  {
+    if (_geometric_cuts[i]->healMesh())
+    {
+      for (ElementPairLocator::ElementPairList::iterator it =
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: A range-based for loop would really clean this up!

File: modules/xfem/src/base/XFEM.C [hunk 3]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+               _sibling_elems[_geometric_cuts[i]->getInterfaceID()].begin();
+           it != _sibling_elems[_geometric_cuts[i]->getInterfaceID()].end();
+           ++it)
+      {
+        Elem * elem1 = const_cast<Elem *>(it->first);
+        Elem * elem2 = const_cast<Elem *>(it->second);
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: A const_cast? Perhaps you shouldn't store these Elems as const if you are just going to cast it away. It might will cause confusion since developers might think you are actually not modifying those elements when they see the declarations.

File: modules/xfem/src/base/XFEM.C [hunk 4]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+        _mesh->boundary_info->remove(elem2);
+        unsigned int deleted_elem_id = elem2->id();
+        _mesh->delete_elem(elem2);
+        _console << "XFEM healing deleted element: " << deleted_elem_id << "\n";
+        mesh_changed = true;
+      }
+    }
+  }
+
+  for (std::set<Node *>::iterator sit = nodes_to_delete.begin(); sit != nodes_to_delete.end();
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: Range-based for?

File: modules/xfem/src/base/XFEM.C [hunk 5]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+       ++sit)
+  {
+    Node * node_to_delete = *sit;
+    unsigned int deleted_node_id = node_to_delete->id();
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: wrong type!

File: modules/xfem/src/base/XFEM.C [hunk 6]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+    _mesh->boundary_info->remove(node_to_delete);
+    _mesh->delete_node(node_to_delete);
+    _console << "XFEM healing deleted node: " << deleted_node_id << "\n";
+  }
+
+  if (_displaced_mesh)
+  {
+    for (std::set<Node *>::iterator sit = nodes_to_delete_displaced.begin();
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: range-based for

File: modules/xfem/src/base/XFEM.C [hunk 7]
```diff
@@ -882,6 +929,148 @@ XFEM::initCutIntersectionEdge(
...
+         sit != nodes_to_delete_displaced.end();
+         ++sit)
+    {
+      Node * node_to_delete = *sit;
+      _displaced_mesh->boundary_info->remove(node_to_delete);
+      _displaced_mesh->delete_node(node_to_delete);
+    }
+  }
+  _console << std::flush;
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: You didn't output to console in the loop above, why not move this flush up to the last place where you wrote to the console?

File: modules/xfem/src/base/XFEM.C [hunk 8]
```diff
@@ -959,19 +1148,23 @@ XFEM::cutMeshWithEFA(NonlinearSystemBase & nl, AuxiliarySystem & aux)
...
-    for (ElementPairLocator::ElementPairList::iterator it = _sibling_elems.begin();
-         it != _sibling_elems.end();
-         ++it)
+    for (unsigned int m = 0; m < _geometric_cuts.size(); ++m)
     {
-      if (parent_elem == it->first)
-        it->first = libmesh_elem;
-      else if (parent_elem == it->second)
-        it->second = libmesh_elem;
+      for (ElementPairLocator::ElementPairList::iterator it =
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: range-based for

File: modules/xfem/src/base/XFEM.C [hunk 9]
```diff
@@ -980,14 +1173,18 @@ XFEM::cutMeshWithEFA(NonlinearSystemBase & nl, AuxiliarySystem & aux)
...
-      for (ElementPairLocator::ElementPairList::iterator it = _sibling_displaced_elems.begin();
-           it != _sibling_displaced_elems.end();
-           ++it)
+      for (unsigned int m = 0; m < _geometric_cuts.size(); ++m)
       {
-        if (parent_elem2 == it->first)
-          it->first = libmesh_elem2;
-        else if (parent_elem2 == it->second)
-          it->second = libmesh_elem2;
+        for (ElementPairLocator::ElementPairList::iterator it =
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: range-based for

File: modules/xfem/src/constraints/XFEMSingleVariableConstraint.C [hunk 10]
```diff
@@ -40,6 +45,14 @@ XFEMSingleVariableConstraint::XFEMSingleVariableConstraint(const InputParameters
     _jump_flux(getParam<Real>("jump_flux")),
     _use_penalty(getParam<bool>("use_penalty"))
 {
+  _xfem = MooseSharedNamespace::dynamic_pointer_cast<XFEM>(_fe_problem.getXFEM());
+  if (_xfem == NULL)
```
Comment (permcody) [inline modules/xfem/src/constraints/XFEMSingleVariableConstraint.C]: nullptr

File: modules/xfem/src/constraints/XFEMSingleVariableConstraint.C [hunk 11]
```diff
@@ -40,6 +45,14 @@ XFEMSingleVariableConstraint::XFEMSingleVariableConstraint(const InputParameters
...
+    mooseError("Problem casting to XFEM in XFEMSingleVariableConstraint");
+
+  const UserObject * uo =
+      &(_fe_problem.getUserObjectBase(getParam<UserObjectName>("geometric_cut_userobject")));
+
+  _interface_id = _xfem->getGeometricCutID(dynamic_cast<const GeometricCutUserObject *>(uo));
```
Comment (permcody) [inline modules/xfem/src/constraints/XFEMSingleVariableConstraint.C]: What if this cast fails? If you know this type will always succeed then should just store it by reference and static_cast it. Otherwise, add the check or assertion.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C [hunk 12]
```diff
@@ -34,14 +37,25 @@ validParams<GeometricCutUserObject>()
...
-  _xfem = MooseSharedNamespace::dynamic_pointer_cast<XFEM>(fe_problem->getXFEM());
+  _xfem = MooseSharedNamespace::dynamic_pointer_cast<XFEM>(_fe_problem.getXFEM());
   if (_xfem == NULL)
-    mooseError("Problem casting to XFEM in XFEMMaterialStateMarkerBase");
+    mooseError("Problem casting to XFEM in GeometricCutUserObject");
+
+  _xfem->addGeometricCut(this);
+
+  MooseSharedPointer<XFEMElementPairLocator> new_xfem_epl(
+      new XFEMElementPairLocator(_xfem, _interface_id));
```
Comment (permcody) [inline modules/xfem/src/userobjects/GeometricCutUserObject.C]: Please don't use MooseSharedPointer, it's deprecated (use std::shared_pointer). Also, use `std::make_shared()` instead of calling `new`.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C [hunk 13]
```diff
@@ -34,14 +37,25 @@ validParams<GeometricCutUserObject>()
...
+  _fe_problem.geomSearchData().addElementPairLocator(_interface_id, new_xfem_epl);
+
+  if (_fe_problem.getDisplacedProblem() != NULL)
+  {
+    std::shared_ptr<XFEMElementPairLocator> new_xfem_epl2(
+        new XFEMElementPairLocator(_xfem, _interface_id, true));
```
Comment (permcody) [inline modules/xfem/src/userobjects/GeometricCutUserObject.C]: `std::make_shared()`

File: modules/xfem/src/userobjects/GeometricCutUserObject.C [hunk 14]
```diff
@@ -34,14 +37,25 @@ validParams<GeometricCutUserObject>()
...
 
 GeometricCutUserObject::GeometricCutUserObject(const InputParameters & parameters)
-  : CrackFrontPointsProvider(parameters)
+  : CrackFrontPointsProvider(parameters), _heal_mesh(getParam<bool>("heal_mesh"))
 {
-  FEProblemBase * fe_problem = dynamic_cast<FEProblemBase *>(&_subproblem);
-  if (fe_problem == NULL)
-    mooseError("Problem casting _subproblem to FEProblemBase in XFEMMaterialStateMarkerBase");
-  _xfem = MooseSharedNamespace::dynamic_pointer_cast<XFEM>(fe_problem->getXFEM());
+  _xfem = MooseSharedNamespace::dynamic_pointer_cast<XFEM>(_fe_problem.getXFEM());
```
Comment (permcody) [inline modules/xfem/src/userobjects/GeometricCutUserObject.C]: Don't use `MooseSharedNamespace` anymore, it's deprecated. Just use the C++11 smart pointer names directly.

File: framework/include/constraints/ElemElemConstraint.h (hunk 1 above)
Comment (jiangwen84) [reply framework/include/constraints/ElemElemConstraint.h]: I need to override this function for XFEM cases where the interface id will be obtained directly from the mesh cutters.

File: modules/xfem/src/base/XFEM.C (hunk 2 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: will do :-)

File: modules/xfem/src/base/XFEM.C (hunk 5 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: will change to dof_id_type

File: modules/xfem/src/userobjects/GeometricCutUserObject.C (hunk 12 above)
Comment (jiangwen84) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: I will make the changes to other files too.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C (hunk 14 above)
Comment (jiangwen84) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: I will make the changes to other files too.

File: framework/include/constraints/ElemElemConstraint.h (hunk 1 above)
Comment (jiangwen84) [reply framework/include/constraints/ElemElemConstraint.h]: I just realized that it could be  not virtual :-)

File: modules/xfem/src/base/XFEM.C (hunk 3 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: For most of other cases, we still want these elements to be const.

File: modules/xfem/src/constraints/XFEMSingleVariableConstraint.C (hunk 11 above)
Comment (jiangwen84) [reply modules/xfem/src/constraints/XFEMSingleVariableConstraint.C]: check is added

File: modules/xfem/src/userobjects/GeometricCutUserObject.C (hunk 13 above)
Comment (jiangwen84) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: Did!

File: modules/xfem/src/constraints/XFEMSingleVariableConstraint.C (hunk 10 above)
Comment (jiangwen84) [reply modules/xfem/src/constraints/XFEMSingleVariableConstraint.C]: got it

File: modules/xfem/src/base/XFEM.C (hunk 9 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: did

File: modules/xfem/src/base/XFEM.C (hunk 8 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: did

File: modules/xfem/src/base/XFEM.C (hunk 7 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: did

File: modules/xfem/src/base/XFEM.C (hunk 6 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: did

File: modules/xfem/src/base/XFEM.C (hunk 4 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: did

**Comment by permcody** [comment]
Thanks for all the fixups. I'm assigning to @bwspenc for merging.

File: modules/xfem/src/base/XFEM.C [hunk 15]
```diff
@@ -882,6 +929,143 @@ XFEM::initCutIntersectionEdge(
...
+  std::set<Node *> nodes_to_delete_displaced;
+  std::set<unsigned int> cutelems_to_delete;
+
+  for (unsigned int i = 0; i < _geometric_cuts.size(); ++i)
+  {
+    if (_geometric_cuts[i]->healMesh())
+    {
+      for (auto & it : _sibling_elems[_geometric_cuts[i]->getInterfaceID()])
+      {
+        Elem * elem1 = const_cast<Elem *>(it.first);
```
Comment (bwspenc) [inline modules/xfem/src/base/XFEM.C]: I guess this scheme will just keep the stateful material properties for elem1 in the combined element.  Maybe we could average the properties from the two elements or something, although that has its problems.
I wonder if we could check to see if there are stateful properties when we heal and warn that they might not be right if healing is used. That could be done in a follow-on commit.

File: modules/xfem/include/base/XFEM.h [hunk 16]
```diff
@@ -228,8 +245,9 @@ class XFEM : public XFEMInterface
 
   std::map<unique_id_type, XFEMCutElem *> _cut_elem_map;
   std::set<const Elem *> _crack_tip_elems;
-  ElementPairLocator::ElementPairList _sibling_elems;
-  ElementPairLocator::ElementPairList _sibling_displaced_elems;
+  std::set<const Elem *> _crack_tip_elems_need_heal;
```
Comment (bwspenc) [inline modules/xfem/include/base/XFEM.h]: I'd rename this to `_crack_tip_elems_to_be_healed`.  Also, add one-line doxygen comments for these variables.

File: modules/xfem/src/constraints/XFEMSingleVariableConstraint.C [hunk 17]
```diff
@@ -26,6 +28,9 @@ validParams<XFEMSingleVariableConstraint>()
   params.addParam<Real>("alpha", 100, "Stablization parameter in Nitsche's formulation.");
   params.addParam<Real>("jump", 0, "Jump at the interface.");
   params.addParam<Real>("jump_flux", 0, "Flux jump at the interface.");
+  params.addParam<UserObjectName>(
+      "geometric_cut_userobject",
+      "Names of GeometricCutUserObject associated with this constraint.");
```
Comment (bwspenc) [inline modules/xfem/src/constraints/XFEMSingleVariableConstraint.C]: Names -> Name

File: modules/xfem/src/userobjects/GeometricCutUserObject.C [hunk 18]
```diff
@@ -17,13 +17,16 @@
...
+#include "XFEMElementPairLocator.h"
+#include "DisplacedProblem.h"
 
 template <>
 InputParameters
 validParams<GeometricCutUserObject>()
 {
   InputParameters params = validParams<CrackFrontPointsProvider>();
   params.addClassDescription("Base UserObject class for XFEM Geometric Cuts");
+  params.addParam<bool>("heal_mesh", false, "Heal previous cuts at every time step");
```
Comment (bwspenc) [inline modules/xfem/src/userobjects/GeometricCutUserObject.C]: Maybe rename to `always_heal_mesh`. Rename the member variable as well.  The reason I suggest this is that derived classes may want to have their own more fine-grained control over healing, and the name `heal_mesh` might cause confusion with the options for that, which will be added in the future.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C [hunk 19]
```diff
@@ -262,11 +274,17 @@ GeometricCutUserObject::finalize()
 
   for (const auto & it : _marked_elems_2d)
     for (const auto & gmei : it.second)
+    {
       _xfem->addGeomMarkedElem2D(it.first, gmei);
+      _xfem->addGeomMarkerIDElem(_interface_id, it.first);
```
Comment (bwspenc) [inline modules/xfem/src/userobjects/GeometricCutUserObject.C]: Couldn't we just add these two additional parameters to `addGeomMarkedElem2D()` rather than having a second call?

File: modules/xfem/test/tests/bimaterials/glued_interface_2d.i [hunk 20]
```diff
@@ -0,0 +1,316 @@
+[GlobalParams]
+  order = FIRST
+  family = LAGRANGE
+  displacements = 'disp_x disp_y'
+[]
+
+[XFEM]
+  qrule = volfrac
+  output_cut_plane = true
+  heal_every_time = true
```
Comment (bwspenc) [inline modules/xfem/test/tests/bimaterials/glued_interface_2d.i]: I don't think this is a valid parameter.

File: modules/xfem/test/tests/diffusion_xfem/levelsetcut.i [hunk 21]
```diff
@@ -0,0 +1,126 @@
...
+  xmax = 1
+  ymin = 0
+  ymax = 1
+  elem_type = QUAD4
+[]
+
+[XFEM]
+  qrule = volfrac
+  output_cut_plane = true
+  heal_every_time = true
```
Comment (bwspenc) [inline modules/xfem/test/tests/diffusion_xfem/levelsetcut.i]: I don't think this is a valid parameter.

File: modules/xfem/test/tests/diffusion_xfem/diffusion_heal.i [hunk 22]
```diff
@@ -0,0 +1,98 @@
...
+  xmin = 0.0
+  xmax = 1.0
+  ymin = 0.0
+  ymax = 1.0
+  elem_type = QUAD4
+[]
+
+[XFEM]
+  geometric_cut_userobjects = 'line_seg_cut_uo'
+  heal_times = 2
```
Comment (bwspenc) [inline modules/xfem/test/tests/diffusion_xfem/diffusion_heal.i]: I don't think this is a valid parameter.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C (hunk 18 above)
Comment (bwspenc) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: `heal_every_time` would work too.

Comment (bwspenc) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: `heal_always`

**Review by bwspenc — CHANGES_REQUESTED** [review]

File: framework/include/interfaces/XFEMInterface.h [hunk 23]
```diff
@@ -25,7 +25,7 @@ namespace libMesh
 {
 class MeshBase;
 class QBase;
-}
+} // namespace libMesh
```
[the remark this answers is not in the document]
Comment (jiangwen84) [reply framework/include/interfaces/XFEMInterface.h]: I turned Atom auto clang save option on. When I saved it, it automatically adds this line. I am not sure if this is required or not.

File: modules/xfem/src/userobjects/GeometricCutUserObject.C (hunk 19 above)
Comment (jiangwen84) [reply modules/xfem/src/userobjects/GeometricCutUserObject.C]: Good point. I merged these two.

File: modules/xfem/src/base/XFEM.C (hunk 15 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C]: That is a good point. I would like to address it in a follow-on PR.

**Comment by jiangwen84** [comment]
@bwspenc I address all your comments except the stateful material one. I need to think about what is a better way to handle stateful material property for a moving interface problem.

File: modules/xfem/include/base/XFEM.h [hunk 24]
```diff
@@ -66,7 +66,7 @@ class XFEM : public XFEMInterface
 
   ~XFEM();
 
-  void addGeometricCut(const GeometricCutUserObject * geometric_cut);
+  void addGeometricCut(GeometricCutUserObject * geometric_cut);
```
[the remark this answers is not in the document]
Comment (bwspenc) [reply modules/xfem/include/base/XFEM.h]: It looks like you missed adding this one.

File: modules/xfem/test/tests/bimaterials/glued_interface_2d.i [hunk 25]
```diff
@@ -0,0 +1,315 @@
...
+[Constraints]
+  [./dispx_constraint]
+    type = XFEMSingleVariableConstraint
+    use_displaced_mesh = false
+    variable = disp_x
+    use_penalty = true
+    alpha = 1e5
+  [../]
+  [./dispy_constraint]
+    type = XFEMSingleVariableConstraint
```
Comment (bwspenc) [inline modules/xfem/test/tests/bimaterials/glued_interface_2d.i]: Do you need `geometric_cut_userobject = 'level_set_cut_uo'` in these Constraint blocks?

File: modules/xfem/test/tests/diffusion_xfem/levelsetcut.i [hunk 26]
```diff
@@ -0,0 +1,125 @@
...
+    y = '3   5'
+  [../]
+  [./ls_func]
+    type = ParsedFunction
+    #value = 'sqrt((x-0.)*(x-0.) + (y-0.)*(y-0.))-0.11*t'
+    value = 'x-0.5'
+  [../]
+[]
+
+# [Constraints]
```
Comment (bwspenc) [inline modules/xfem/test/tests/diffusion_xfem/levelsetcut.i]: Remove commented out commands.

**Review by bwspenc — CHANGES_REQUESTED** [review]
Really close. Just a couple little things.

File: modules/xfem/test/tests/bimaterials/glued_interface_2d.i (hunk 25 above)
Comment (jiangwen84) [reply modules/xfem/test/tests/bimaterials/glued_interface_2d.i]: this is the test that I forget to delete.

File: modules/xfem/include/base/XFEM.h (hunk 24 above)
[the remark this answers is not in the document]
Comment (jiangwen84) [reply modules/xfem/include/base/XFEM.h]: I removed it because I need to set an interface id in this function to geometric_cut and the set function is not a const function. Do you have a better way to do it?

[the remark this answers is not in the document]
Comment (bwspenc) [reply modules/xfem/include/base/XFEM.h]: I just meant that you didn't add the Doxygen comment. Since this method already existed, I'm not going to let that hold up the merging of this.

**Review by bwspenc — APPROVED** [review]
