### PR TITLE
Clear up _local2global_map (in MultiAppTransfer.C)  

### LINKED ISSUE #19375: _local2global_map in multiapp was not cleared up
## Bug Description

Clear up  `_local2global_map` since we built it from scratch every time
Otherwise, this will cause two issues: 1) increasing memory usage
for a simulation that requires many transfers, 2) producing wrong results
when we do collective communication on this vector. 

## Steps to Reproduce

Call transfer twice, and use debugger to check if the size of `_local2global_map` is doubled.

If you call transfer ten times, the size of `_local2global_map` will increased by a factor of ten.

## Impact
Waste  memory, and produce wrong results

### PR DESCRIPTION
**Pull request by fdkong**
Closes #19375

### CODE REVIEW

File: framework/src/transfers/MultiAppTransfer.C [hunk 1]
```diff
@@ -111,6 +111,11 @@ MultiAppTransfer::getAppInfo()
   _to_meshes.clear();
   _to_positions.clear();
   _from_positions.clear();
+  // Clear up this map since we built it from scratch every time
```
Comment (lindsayad) [inline framework/src/transfers/MultiAppTransfer.C:114]:
```suggestion
  // Clear this map since we build it from scratch every time we transfer
```

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Review by lindsayad — APPROVED** [review]
