### PR TITLE
Remove exit(1) calls, reduce unit test output for ElementFragmentAlgorithm

### LINKED ISSUE #15101: Clean up ElementFragmentAlgorithm[Test]
## Reason
The `ElementFragmentAlgorithm` unit test is unnecessarily chatty and spams the output with pages and pages of number tables. Let's do this only in debug mode! Also replace an `exit`  C call with throwing an exception. 

## Design
Wrap output calls in `#ifndef NDEBUG`

## Impact
Cleaner unit test output

### PR DESCRIPTION
**Pull request by dschwen**
Closes #15101

### CODE REVIEW

File: unit/src/ElementFragmentAlgorithmTest.C [hunk 1]
```diff
@@ -146,8 +146,6 @@ TEST(ElementFragmentAlgorithm, test1b)
 
   MyMesh.updateTopology();
 
-  //  MyMesh.printMesh();
```
Comment (bwspenc) [inline unit/src/ElementFragmentAlgorithmTest.C:149]: Would you mind converting these commented out versions to:
```
#ifndef NDEBUG
  MyMesh.printMesh();
#endif

**Review by bwspenc — CHANGES_REQUESTED** [review]

File: unit/src/ElementFragmentAlgorithmTest.C (hunk 1 above)
Comment (dschwen) [reply unit/src/ElementFragmentAlgorithmTest.C:149]: ?!

**Review by bwspenc — APPROVED** [review]
