### PR TITLE
MFEM mixed forms fix

### LINKED ISSUE #32096: MFEM mixed bilinear forms test and trial space ordering issues
### Bug Description

When using MFEM to solve a mixed system (i. e. different test and trial spaces), the `FormSystemMatrix` method in the `EquationSystem` class calls 

`mblf->FormRectangularLinearSystem(_ess_tdof_lists.at(j),
                                          _ess_tdof_lists.at(i),
                                          *(_var_ess_constraints.at(j)),
                                          aux_lf,
                                          *aux_a,
                                          aux_x,
                                          aux_rhs);`

where `i` represents the index of the test finite element space, and `j` represents the trial space. In particular, we wish to use the trial variable within the `j`th entry in `_var_ess_constraints`. However, as it currently stands, `_var_ess_constraints` has been created with the ordering of test spaces, not trial spaces. In square systems, with no mixed kernels, the `_test_var_names` and `_trial_var_names` are created with the same ordering of spaces, so this isn't an issue. However, in mixed systems, depending on how the `Kernels` block in the MOOSE script was arranged, the orderings might not be the same and the simulation will crash.

A secondary issue is that when `SetSize()` is called on `_h_blocks`, it only allocates space for the blocks but it doesn't clear what might be in that space, so in some cases it might cause segfaults if the blocks in `h_blocks` are not initialised as `nullptr`s.

### Steps to Reproduce

With the current version of MOOSE, run the following script:

```
[Mesh]
  type = MFEMMesh
  file = ../mesh/square.e
  dim = 2
[]

[Problem]
  type = MFEMProblem
[]

[FESpaces]
  [H1FESpace]
    type = MFEMScalarFESpace
    fec_type = H1
    fec_order = FIRST
  []
  [HCurlFESpace]
    type = MFEMVectorFESpace
    fec_type = ND
    fec_order = FIRST
  []
[]

[Variables]
  [E]
    type = MFEMVariable
    fespace = HCurlFESpace
  []
  [p]
    type = MFEMVariable
    fespace = H1FESpace
  []
[]

[Kernels]
  [scalarcurl_E]
    type = MFEMMixedScalarCurlKernel
    trial_variable = E
    variable = p
    coefficient = 1.0
  []
  [mass_p]
    type = MFEMMassKernel
    variable = p
    coefficient = 1.0
  []
  [mass_E]
    type = MFEMVectorFEMassKernel
    variable = E
    coefficient = 1.0
  []
[]

[Solver]
  type = MFEMSuperLU
[]

[Executioner]
  type = MFEMSteady
  assembly_level = legacy
[]
```

It will likely segfault, due to the secondary issue described above. The solution to the segfault is to initialise all blocks in `_h_blocks` as `nullptr`s before forming the linear system. This is done in the `ClearAllBlocks()` method in the PR that will be opened to fix this issue. However, even after fixing the segfault, the code will still crash due to the ordering of the FE spaces. Note, however, that if you change the order of the kernels in this script by putting the `scalarcurl_E` last in the `Kernels` block, the code should run normally. That is because in this case the `_test_var_names` and `_trial_var_names` end up with the same ordering.

### Impact

Depending on the particularities of the mixed system of equations being solved for, this issue might completely preclude the user from solving a perfectly valid and well-defined problem.

### PR DESCRIPTION
**Pull request by Heinrich-BR**
Closes #32096

### CODE REVIEW

File: framework/src/mfem/equation_systems/EquationSystem.C [hunk 1]
```diff
@@ -272,6 +313,8 @@ EquationSystem::FormSystemMatrix(mfem::OperatorHandle & op,
   // Allocate block operator
   DeleteAllBlocks();
   _h_blocks.SetSize(_test_var_names.size(), _test_var_names.size());
+  ClearAllBlocks();
+
```
Comment (nmnobre) [inline framework/src/mfem/equation_systems/EquationSystem.C]:
```suggestion
  _h_blocks = nullptr;
```

File: framework/src/mfem/equation_systems/EquationSystem.C [hunk 2]
```diff
@@ -142,14 +146,22 @@ EquationSystem::Init(Moose::MFEM::GridFunctions & gridfunctions,
...
     _test_pfespaces.push_back(gridfunctions.Get(test_var_name)->ParFESpace());
+  }
+
+  for (auto & trial_var_name : _trial_var_names)
+  {
+    if (!gridfunctions.Has(trial_var_name))
+    {
+      mooseError("MFEM variable ",
+                 trial_var_name,
+                 " requested by equation system during initialisation was "
```
Comment (nmnobre) [inline framework/src/mfem/equation_systems/EquationSystem.C]: initialisation -> initialization (change all three appearances)

File: framework/src/mfem/problem_operators/ComplexEquationSystemProblemOperator.C [hunk 3]
```diff
@@ -17,28 +17,42 @@ void
...
   }
-  _block_true_offsets.PartialSum();
+  _block_true_offsets_trial.PartialSum();
 
-  _true_x.Update(_block_true_offsets);
-  _true_rhs.Update(_block_true_offsets);
+  // Set operator size and block structure for test spaces
+  _block_true_offsets_test.SetSize(_cmplx_test_variables.size() + 1);
+  _block_true_offsets_test[0] = 0;
+  for (unsigned int ind = 0; ind < _cmplx_test_variables.size(); ++ind)
```
Comment (nmnobre) [inline framework/src/mfem/problem_operators/ComplexEquationSystemProblemOperator.C]: change all instances to use `index_range()` instead

**Review by nmnobre — CHANGES_REQUESTED** [review]
Thanks Henrique, I love the conceptual distinction between trial and test variables that this PR is pushing for :)

I've taken the liberty to push a commit that guarantees test and trial variables are in the same order. We probably don't want to place diagonal blocks (i.e. those with the same trial and test variable) outside the diagonal or off-diagonal blocks (i.e. different trial and test variables) on the diagonal; this would be a headache for conditioning, and preconditioning in particular - I don't doubt we could work out the algebra, but I fear the amount of technical debt we'd be buying into isn't justifiable.

So let's also assert that:
a) the no. of trial and test variables is the same (this will force future us to intentionally remove the assertion when we're ready to support rectangular, i.e. underconstrained, systems).
b) `i == j` when `test_var_name == trial_var_name` in `FormSystemMatrix()`

Inside that `if (test_var_name == trial_var_name)`, since we use `test_var_name`, let's also use `i` and not `j` (now we're asserting they're equal anyway).

**Comment by Heinrich-BR** [comment]
Thank you for the comments @nmnobre ! I've addressed them now. My only question is about this:

> Inside that `if (test_var_name == trial_var_name)`, since we use `test_var_name`, let's also use `i` and not `j` (now we're asserting they're equal anyway).

I understand that they're equal anyway, but isn't it cleaner if we keep the conceptually correct index?

File: framework/src/mfem/problem_operators/ComplexEquationSystemProblemOperator.C [hunk 4]
```diff
@@ -17,28 +17,42 @@ void
...
   }
-  _block_true_offsets.PartialSum();
+  _block_true_offsets_trial.PartialSum();
 
-  _true_x.Update(_block_true_offsets);
-  _true_rhs.Update(_block_true_offsets);
+  // Set operator size and block structure for test spaces
+  _block_true_offsets_test.SetSize(_cmplx_test_variables.size() + 1);
+  _block_true_offsets_test[0] = 0;
+  for (const auto ind : index_range(_cmplx_trial_variables))
```
Comment (nmnobre) [inline framework/src/mfem/problem_operators/ComplexEquationSystemProblemOperator.C]:
```suggestion
  for (const auto ind : index_range(_cmplx_test_variables))
```

File: framework/src/mfem/problem_operators/ProblemOperatorBase.C [hunk 5]
```diff
@@ -25,22 +25,30 @@ void
...
   _trial_variables = _problem_data.gridfunctions.Get(_trial_var_names);
+  _test_variables = _problem_data.gridfunctions.Get(_test_var_names);
 
-  // Set operator size and block structure
-  _block_true_offsets.SetSize(_trial_variables.size() + 1);
-  _block_true_offsets[0] = 0;
+  // Set operator size and block structure for trial spaces
+  _block_true_offsets_trial.SetSize(_trial_variables.size() + 1);
+  _block_true_offsets_trial[0] = 0;
   for (unsigned int ind = 0; ind < _trial_variables.size(); ++ind)
```
Comment (nmnobre) [inline framework/src/mfem/problem_operators/ProblemOperatorBase.C]:
```suggestion
  for (const auto ind : index_range(_trial_variables))
```

File: framework/src/mfem/problem_operators/ProblemOperatorBase.C [hunk 6]
```diff
@@ -25,22 +25,30 @@ void
...
-  _block_true_offsets.PartialSum();
+    _block_true_offsets_trial[ind + 1] = _trial_variables.at(ind)->ParFESpace()->TrueVSize();
+  _block_true_offsets_trial.PartialSum();
 
-  _true_x.Update(_block_true_offsets);
-  _true_rhs.Update(_block_true_offsets);
+  // Set operator size and block structure for test spaces
+  _block_true_offsets_test.SetSize(_test_variables.size() + 1);
+  _block_true_offsets_test[0] = 0;
+  for (unsigned int ind = 0; ind < _test_variables.size(); ++ind)
```
Comment (nmnobre) [inline framework/src/mfem/problem_operators/ProblemOperatorBase.C]:
```suggestion
  for (const auto ind : index_range(_test_variables))
```

File: framework/src/mfem/problem_operators/ProblemOperatorBase.C
Comment (nmnobre) [inline framework/src/mfem/problem_operators/ProblemOperatorBase.C]:
```suggestion
  for (const auto ind : index_range(_trial_variables))
```

**Review by nmnobre — CHANGES_REQUESTED** [review]

**Comment by nmnobre** [comment]
> but isn't it cleaner if we keep the conceptually correct index?

Fair, agreed.

**Review by nmnobre — APPROVED** [review]

**Comment by nmnobre** [comment]
Test failures unrelated.
