### PR TITLE
Remove the property storage of XFEM deleted element and side

### LINKED ISSUE #17063: Backup causes random failure for XFEM problems
## Bug Description

When backupMultiApp is called, a new backup will be created. The backup will store MaterialProprety from MaterialPropertyStorage. The storage uses element id, so it looks for element id. If an element has a pointer, but does not have a valid id, it will throw out an error.  For XFEM, some element will be deleted, but their points will still remain in the MaterialPropertyStoreage. Very randomly, their id could become invalid and trigger that error. 

## Steps to Reproduce

It fails randomly, and trigged by the backup. The bt is below

* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x000000012bfadbb0 libmpi.12.dylib`MPI_Abort
    frame #1: 0x0000000116285674 libmoose-dbg.0.dylib`moose::internal::mooseErrorRaw(msg="", prefix="") at MooseError.C:84:3
    frame #2: 0x00000001157979aa libmoose-dbg.0.dylib`void mooseError<char const (&) [37]>(args=<no value available>) [37]) at MooseError.h:240:3
    frame #3: 0x00000001157978e5 libmoose-dbg.0.dylib`void dataStore<libMesh::Elem const>(stream=0x00007ffee2e516d0, e=0x00007fbc0a69c170, context=0x00007fbceb0b7618) at DataIO.C:96:7
    frame #4: 0x00000001154b0e05 libmoose-dbg.0.dylib`void storeHelper<libMesh::Elem const*>(stream=0x00007ffee2e516d0, data=0x00007fbc0a69c170, context=0x00007fbceb0b7618) at DataIO.h:715:3
    frame #5: 0x00000001154b0cd2 libmoose-dbg.0.dylib`void dataStore<libMesh::Elem const*, HashMap<unsigned int, MaterialProperties> >(stream=0x00007ffee2e516d0, m=0x00007fbc78faaa40, context=0x00007fbceb0b7618) at DataIO.h:335:5
    frame #6: 0x00000001154b0bc8 libmoose-dbg.0.dylib`void dataStore<MaterialPropertyStorage>(stream=0x00007ffee2e516d0, storage=0x00007fbc78faaaa0, context=0x00007fbceb0b7618) at MaterialPropertyStorage.h:314:3
    frame #7: 0x00000001154b0b55 libmoose-dbg.0.dylib`void storeHelper<MaterialPropertyStorage>(stream=0x00007ffee2e516d0, data=0x00007fbc78faaaa0, context=0x00007fbceb0b7618) at DataIO.h:715:3
    frame #8: 0x00000001154b0623 libmoose-dbg.0.dylib`RestartableData<MaterialPropertyStorage>::store(this=0x00007fbc78faa9e0, stream=0x00007ffee2e516d0) at RestartableData.h:164:3
    frame #9: 0x000000011579ca78 libmoose-dbg.0.dylib`RestartableDataIO::serializeRestartableData(this=0x00007ffee2e51b80, restartable_data=size=78, stream=0x00007fbd490ce190) at RestartableDataIO.C:114:24
    frame #10: 0x000000011579f2c6 libmoose-dbg.0.dylib`RestartableDataIO::createBackup(this=0x00007ffee2e51b80) at RestartableDataIO.C:347:5
    frame #11: 0x0000000116224f58 libmoose-dbg.0.dylib`MooseApp::backup(this=0x00007fbd2881f818) at MooseApp.C:1089:15
    frame #12: 0x00000001157fa470 libmoose-dbg.0.dylib`MultiApp::backup(this=0x00007fbd1853a3c8) at MultiApp.C:430:29
    frame #13: 0x00000001157fa343 libmoose-dbg.0.dylib`FullSolveMultiApp::backup(this=0x00007fbd1853a3c8) at FullSolveMultiApp.C:54:15
    frame #14: 0x00000001153ddfb7 libmoose-dbg.0.dylib`FEProblemBase::backupMultiApps(this=0x00007fbcea808218, type=(_raw_name = "TIMESTEP_BEGIN", _name = "TIMESTEP_BEGIN", _id = 16)) at FEProblemBase.C:4406:18
    frame #15: 0x0000000114edbb7f libmoose-dbg.0.dylib`PicardSolve::solve(this=0x00007fbd4981d080) at PicardSolve.C:160:12
    frame #16: 0x0000000114ee7c26 libmoose-dbg.0.dylib`Steady::execute(this=0x00007fbd4981ce18) at Steady.C:88:45
    frame #17: 0x0000000116224768 libmoose-dbg.0.dylib`MooseApp::executeExecutioner(this=0x00007fbd2880c418) at MooseApp.C:1023:19
    frame #18: 0x00000001162256af libmoose-dbg.0.dylib`MooseApp::run(this=0x00007fbd2880c418) at MooseApp.C:1150:5
    frame #19: 0x000000010cdaec66 bison-dbg`main(argc=4, argv=0x00007ffee2e52968) at main.C:50:8
    frame #20: 0x00007fff67775cc9 libdyld.dylib`start + 1
    frame #21: 0x00007fff67775cc9 libdyld.dylib`start + 1

One way to fix this is to remove property storage of elements before they are deleted. 

## Impact

It will fix issues where backup is needed for XFEM, such as for multiapp application.

### PR DESCRIPTION
**Pull request by jiangwen84**
closes  #17063

### CODE REVIEW

**Comment by jiangwen84** [comment]
@rwcarlsen could you review this PR? Thanks.

File: modules/xfem/src/base/XFEM.C [hunk 1]
```diff
@@ -1430,6 +1430,11 @@ XFEM::cutMeshWithEFA(NonlinearSystemBase & nl, AuxiliarySystem & aux)
     }
 
     elem_to_delete->nullify_neighbors();
+
+    // remove the property storage of deleted element/side
+    (*_material_data)[0]->eraseProperty(elem_to_delete);
+    (*_bnd_material_data)[0]->eraseProperty(elem_to_delete);
+
```
Comment (rwcarlsen) [inline modules/xfem/src/base/XFEM.C:1437]: It looks like there are several places in the XFEM class/file that you delete elements.  And you remove boundary info, erase material properties, etc.  along with the actual element deletions.  Would it be better to have a special removeElem function that safely did all these things atomically? - That way you won't have to worry about forgetting to do any of these things whenever you are deleting elements.  Or are the situations for element deletion different enough that they all need different subsets of things done?

File: framework/include/materials/MaterialPropertyStorage.h [hunk 2]
```diff
@@ -255,13 +255,13 @@ class MaterialPropertyStorage
     return _prop_names.count(retrievePropertyId(prop_name)) > 0;
   }
 
+  /// Remove the property storage and element pointer from internal data structures
+  void eraseProperty(const Elem * elem);
```
Comment (rwcarlsen) [inline framework/include/materials/MaterialPropertyStorage.h:259]: Maybe add a sentence to the doc comment saying "Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g. stateful properties) hanging around in our data structures." - or something like that

File: framework/include/materials/MaterialData.h [hunk 3]
```diff
@@ -191,6 +191,11 @@ class MaterialData
    */
   bool isOnlyResizeIfSmaller() const { return _resize_only_if_smaller; };
 
+  /**
+   * Remove the property storage and element pointer from MaterialPropertyStorage data structures
+   */
+  void eraseProperty(const Elem * elem) { _storage.eraseProperty(elem); };
```
Comment (rwcarlsen) [inline framework/include/materials/MaterialData.h:197]: Maybe add a sentence to the doc comment saying "Use this when elements are deleted so we don't end up with invalid elem pointers (for e.g. stateful properties) hanging around in our data structures." - or something like that.

**Review by rwcarlsen — CHANGES_REQUESTED** [review]

File: modules/xfem/src/base/XFEM.C (hunk 1 above)
Comment (jiangwen84) [reply modules/xfem/src/base/XFEM.C:1437]: You are correct that there are other three places that call element deletion. However those deletion is for elements on the displaced mesh, and there is no need to remove their material properties because undisplaced and displaced mesh share same material properties.

File: framework/include/materials/MaterialPropertyStorage.h (hunk 2 above)
Comment (jiangwen84) [reply framework/include/materials/MaterialPropertyStorage.h:259]: I will add what you suggest. Thanks.

File: framework/include/materials/MaterialData.h (hunk 3 above)
Comment (jiangwen84) [reply framework/include/materials/MaterialData.h:197]: I will add what you suggest. Thanks.

**Review by rwcarlsen — APPROVED** [review]

**Comment by hugary1995** [comment]
@rwcarlsen Not sure if you remember this -- we actually depend on this "manual" erasing of material properties to copy some material properties from an old element to a new element. If the material property storage is actually cleaned up _on time_, that'll break something in xfem.

**Comment by hugary1995** [comment]
@rwcarlsen The related PR I was talking about is #16278 .
