### PR TITLE
Fixed nodal integration bug with NOSPD FormII model

### LINKED ISSUE #17724: Fix a bug with peridynamics form 2 bond-associated model
## Bug Description

The evaluation of the double integration to calculate the force density state is performed using nodal integrations. The outside integration use the nodal volume of the material point itself, and the inside integration use the nodal volume of the neighbor of the material point. Due to the form 2 reformulation, the inside integration should be carried out using the nodal volume of all neighbors within the bond-associated horizon rather a fixed neighbor who bond-associated quantities are calculated. For regular mesh, since all material points have the same volume, the integration is correct. Only for irregular mesh, the current implementation will yield inaccurate results, and this inaccuracy depends on the variation of the nodal volume.

### PR DESCRIPTION
**Pull request by hchen139**
closes #17724

### CODE REVIEW

**Comment by hchen139** [comment]
@bwspenc this PR fixed bug for the NOSPD Form II model.

File: modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C [hunk 1]
```diff
@@ -49,7 +49,7 @@ HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD::computeLocalResidual()
                       ((_dgrad[nd].det() * _stress[nd] * _dgrad[nd].inverse().transpose()) *
                        _shape2[nd].inverse())
                           .row(_component) *
-                      _origin_vec * _bond_status;
+                      _origin_vec * _node_vol[1 - nd] * _bond_status;
```
Comment (bwspenc) [inline modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C:52]: It might not be a bad idea to add something like this at the beginning of this function:
```
mooseAssert(_nnodes < 2, "Function only works with 2 or fewer nodes per element");
```
This would make sure you never end up with a negative index into `_node_vol`.

File: modules/peridynamics/src/kernels/HorizonStabilizedFormIISmallStrainMechanicsNOSPD.C [hunk 2]
```diff
@@ -46,7 +46,7 @@ HorizonStabilizedFormIISmallStrainMechanicsNOSPD::computeLocalResidual()
     for (unsigned int i = 0; i < _nnodes; ++i)
       _local_re(i) += (i == 0 ? -1 : 1) * _multi[nd] * _horizon_radius[nd] / _origin_vec.norm() *
                       (_stress[nd] * _shape2[nd].inverse()).row(_component) * _origin_vec *
-                      _bond_status;
+                      _node_vol[1 - nd] * _bond_status;
```
Comment (bwspenc) [inline modules/peridynamics/src/kernels/HorizonStabilizedFormIISmallStrainMechanicsNOSPD.C:49]: That assert on _nnodes would make sense at the beginning of this function too.

File: modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C (hunk 1 above)
Comment (hchen139) [reply modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C:52]: __nnodes_ is a protected parameter of the parent class. Its value is 2.

Comment (bwspenc) [reply modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C:52]: Sure, but the point of an assertion is to make sure that your assumptions of its value are actually true. The assertion only gets executed for the debug executable, so it doesn't hurt performance.

Comment (bwspenc) [reply modules/peridynamics/src/kernels/HorizonStabilizedFormIIFiniteStrainMechanicsNOSPD.C:52]: In looking at this again, I think my suggestion is a bad idea.

**Comment by bwspenc** [comment]
@hchen139 I think this is good to go, but it's been sitting here for a while. Could you please rebase and force push to this branch to trigger the tests to re-run?

**Comment by bwspenc** [comment]
I just did it for you, but then I see that you beat me to it!

**Review by bwspenc — APPROVED** [review]
