### PR TITLE
shell lint, better printf, colors

### LINKED ISSUE #28293: diagnostic.sh needs a little TLC
### Motivation

This script has some current failings I'd like to address

### Design

Correctly identify when the environment is failing due to missing compilers.
Adjust the print outs for easier reading.
Probably more things as I find them.

### Impact

A TLC'd diagnostic script

### PR DESCRIPTION
**Pull request by milljm**
Linted the scripts involved.

Added bold syntax highlighting for all `commands` printed.

A bit more intelligent printing of errors.

Print a final pass/fail message at the end (maybe now RED messages won't be ignored?)

Closes #28293

### CODE REVIEW

File: scripts/functions/diagnostic_environment.sh [hunk 1]
```diff
@@ -136,59 +184,80 @@ function conda_test()
...
         done
-        echo -e "${conda_list}"
-        if [ -n "${reminder}" ]; then print_orange "${reminder}\n"; fi
-        if [[ -n "${my_version}" ]] && [[ "${my_version}" != "${needs_version}" ]]; then
-            print_red "\nFAIL: "
-            printf "${prefix}${package}/repository version mismatch\n"
-            printf "\nYour MOOSE repository requires moose-${package}:\t$(print_green ${needs_version})
-while your Conda environment has moose-${package}:\t$(print_red ${my_version})
+        if [[ "${package}" == 'none' ]]; then
+            printf "\nConda MOOSE packages not applicative.
```
Comment (GiudGiud) [inline scripts/functions/diagnostic_environment.sh:219]: what do you mean by not applicative? I dont get it

**Review by GiudGiud — APPROVED** [review]

File: scripts/diagnostics.sh [hunk 2]
```diff
@@ -21,98 +27,151 @@ function print_failure_and_exit()
...
+        printf '\n--continue-on-fail enabled. Not exiting.\n\n'
         return
     fi
-    exit $1
+    exit "${1}"
 }
 
 function print_help()
 {
+    # shellcheck disable=SC2034
```
[the remark this answers is not in the document]
Comment (milljm) [reply scripts/diagnostics.sh:135]: These are shell lint controls (like pylint). It is the official way to document shell scripts.

File: scripts/functions/diagnostic_environment.sh (hunk 1 above)
Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: I think this `if` block was meant to reside outside of the parent `if` block. Looks like a mistake to me. I'll correct it (remove it, as I see I am doing what I want a little later with an `else`.).

File: scripts/diagnostics.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (milljm) [reply scripts/diagnostics.sh:135]: This is how they render an IDE with shellcheck enabled:

\# shellcheck disable=[SC2034](https://www.shellcheck.net/wiki/SC2034)

File: scripts/functions/diagnostic_environment.sh (hunk 1 above)
Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: Oh wait, no... it works like this:

```bash
moose_packages=(dev wasp libmesh petsc none)
for package in moose_packages; do
   do stuff for package
done
```
if we don't find anything and we reach a literal 'none', that means the user has moose-mpi installed. And it is up to them to build petsc, libmesh, wasp manually.

Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: example:
```bash
conda create -n testing moose-mpi packaging jinja2 pyaml
conda activate testing
./diagnostics
<trimmed>
###############################################################################################
Python Modules (TestHarness, run-ability)

OK
###############################################################################################
CONDA MOOSE Package Checks


Conda MOOSE packages not applicative.
User is required to manually build PETSc, libMesh, and WASP


checks PASSED
```

Comment (GiudGiud) [reply scripts/functions/diagnostic_environment.sh:219]: `Conda MOOSE packages not applicative.`
what do you mean by this? 
Maybe "conda installation path is not selected"

Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: But you are:

```bash
conda create -n testing moose-mpi
                        ^^^^^^^^^
```
This is basically supporting all you devs, that refuse to install `moose-petsc` or `moose-libmesh`, but you want the compiler stack.

Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: How about this: you tell me what you want it to say?

Like:
```pre
Conda MOOSE support library packages not installed.
```

Comment (GiudGiud) [reply scripts/functions/diagnostic_environment.sh:219]: yeah basically. That s how I understand it. 
If it s correct then works for me

Comment (milljm) [reply scripts/functions/diagnostic_environment.sh:219]: How about this, since if we hit 'none' we no we're missing all of them:

```pre
Conda MOOSE dependencies not avilable (moose-petsc, moose-libmesh,
moose-wasp, etc). User is required to manually build PETSc, libMesh,
and WASP.
```

File: scripts/functions/diagnostic_environment.sh [hunk 3]
```diff
@@ -216,8 +217,9 @@ function conda_test()
             fi
         done
         if [[ "${package}" == 'none' ]]; then
-            printf "\nConda MOOSE packages not applicative.
-User is required to manually build PETSc, libMesh, and WASP\n\n"
+            printf "\nConda MOOSE dependencies not avilable (moose-petsc, moose-libmesh,
```
Comment (GiudGiud) [inline scripts/functions/diagnostic_environment.sh:220]: available

File: scripts/functions/diagnostic_environment.sh [hunk 4]
```diff
@@ -216,8 +217,9 @@ function conda_test()
...
+moose-wasp, etc). User is required to manually build PETSc, libMesh,
+and WASP\n\n"
```
Comment (GiudGiud) [inline scripts/functions/diagnostic_environment.sh:222]: and WASP (see moose/scripts folder)

**Review by GiudGiud — APPROVED** [review]
some suggestions
works for me

**Comment by milljm** [comment]
After discussing, there is an issue I still need to address.

**Review by GiudGiud — APPROVED** [review]
