### PR TITLE
Fixes for RZ formulation for INS/INSAD

### LINKED ISSUE #25307: RZ viscous term wrong for INS and INSAD when r-coord = Y
## Bug Description
Looking at `INSMomentumLaplaceFormRZ` and `INSADMomentumViscous` both kernels are hard-coded to assume that u_r is the zeroth component

## Steps to Reproduce
Look at the code

## Impact
Gives wrong answers when r-coord = Y. This is rare but definitely happens

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #25307

### CODE REVIEW

File: modules/navier_stokes/include/materials/INSADTauMaterial.h [hunk 1]
```diff
@@ -308,28 +308,34 @@ INSADTauMaterialTempl<T>::viscousTermRZ()
...
+
+  {
+    // Do the "Laplace" form. This will be present in *both* Laplace and Traction forms
+    ADRealVectorValue rz_term;
+    for (const auto i : make_range((unsigned int)2))
+      rz_term(i) = -_mu[_qp] * _grad_velocity[_qp](i, _rz_radial_coord) / r;
+    rz_term(_rz_radial_coord) += _mu[_qp] * _velocity[_qp](_rz_radial_coord) / (r * r);
+    _viscous_strong_residual[_qp] += rz_term;
+  }
+  if (_viscous_form == NS::ViscousForm::Traction)
```
Comment (GiudGiud) [inline modules/navier_stokes/include/materials/INSADTauMaterial.h:329]: do we have docs about this traction form?
if so it d be nice to link to it from all the 'Traction' objects

File: modules/navier_stokes/src/kernels/INSADMomentumViscous.C [hunk 2]
```diff
@@ -57,15 +57,16 @@ INSADMomentumViscous::qpViscousTerm()
...
+
   // Add the u_r / r^2 term. There is an extra factor of 2 for the traction form
-  ADReal resid = _mu[_qp] * _u[_qp](_rz_radial_coord);
+  const auto & r = _ad_q_point[_qp](_rz_radial_coord);
+  extra_term = _mu[_qp] * _u[_qp](_rz_radial_coord) / (r * r);
   if (_form == "traction")
-    resid *= 2.;
+    extra_term *= 2.;
 
-  if (_use_displaced_mesh)
```
Comment (GiudGiud) [inline modules/navier_stokes/src/kernels/INSADMomentumViscous.C:65]: this was just an optimization right

File: modules/navier_stokes/src/kernels/INSBase.C [hunk 3]
```diff
@@ -326,3 +328,69 @@ INSBase::dTauDUComp(unsigned comp)
...
+  const auto r = _q_point[_qp](_rz_radial_coord);
+  RealVectorValue rz_term;
+  rz_term(0) = -_mu[_qp] * _grad_u_vel[_qp](_rz_radial_coord) / r;
+  rz_term(1) = -_mu[_qp] * _grad_v_vel[_qp](_rz_radial_coord) / r;
+  mooseAssert((_rz_radial_coord == 0) || (_rz_radial_coord == 1),
+              "We expect X or Y as the possible radial coordinate");
+  if (_rz_radial_coord == 0)
+    rz_term(0) += _mu[_qp] * _u_vel[_qp] / (r * r);
+  else
+    rz_term(1) += _mu[_qp] * _v_vel[_qp] / (r * r);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/kernels/INSBase.C:351]: can one line this?
with 
rz_term(_rz_radial_coord)

File: modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C [hunk 4]
```diff
@@ -98,9 +86,9 @@ INSMomentumTractionFormRZ::computeQpOffDiagJacobian(unsigned jvar)
   // If we're getting the pressure Jacobian contribution, and we
   // integrated the pressure term by parts, there is an extra term for
   // RZ.
-  if (jvar == _p_var_number && _component == 0 && _integrate_p_by_parts)
+  if (jvar == _p_var_number && _component == _rz_radial_coord && _integrate_p_by_parts)
   {
-    const Real r = _q_point[_qp](0);
+    const auto r = _q_point[_qp](_rz_radial_coord);
```
Comment (GiudGiud) [inline modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C:91]: want to use ad_q_point for displaced mesh Jacobian or not?

**Review by GiudGiud — COMMENTED** [review]
will look more later

File: modules/navier_stokes/src/kernels/INSBase.C (hunk 3 above)
Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSBase.C:351]: It uses different variables

Comment (GiudGiud) [reply modules/navier_stokes/src/kernels/INSBase.C:351]: ah good point.

File: modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C (hunk 4 above)
Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C:91]: Not really for the hand-coded objects. I've made no effort to support 100% accurate Jacobians for displaced meshes in the hand-coded objects to date. If wanting to add that support, I think it should happen in a larger sweep.

I'm still debating whether just to remove the INS objects in general. However, they have been very helpful in checking for bugs in the INSAD implementation. In an ideal world I would use the INSFE objects for that ... or remove the INSFE objects.

Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C:91]: Also in that same larger discussion, for non-displaced meshes the INS Jacobians are 100% accurate and so the INS objects have faster run-times than INSAD so that would be a good argument for keeping them around. Anyway this is not on-topic haha

Comment (GiudGiud) [reply modules/navier_stokes/src/kernels/INSMomentumTractionFormRZ.C:91]: ah ok that makes sense. 
INSAD will use ad_q_point and INS should consistently use _q_point and manually do the derivative later if it s ever needed

yeah INSFE vs INS will have to be decided some day

File: modules/navier_stokes/src/kernels/INSADMomentumViscous.C (hunk 2 above)
Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSADMomentumViscous.C:65]: Some unknown degree of optimization yes. My hope is that multiplying dual numbers without derivatives is not too expensive in the scheme of things

File: modules/navier_stokes/src/kernels/INSBase.C [hunk 5]
```diff
@@ -326,3 +328,69 @@ INSBase::dTauDUComp(unsigned comp)
...
+INSBase::strongViscousTermTractionRZ() const
+{
+  auto ret = strongViscousTermLaplaceRZ();
+
+  const auto r = _q_point[_qp](_rz_radial_coord);
+
+  const auto & grad_r_vel = (_rz_radial_coord == 0) ? _grad_u_vel[_qp] : _grad_v_vel[_qp];
+  const auto & r_vel = (_rz_radial_coord == 0) ? _u_vel[_qp] : _v_vel[_qp];
+  ret += -_mu[_qp] * grad_r_vel / r;
+  ret(_rz_radial_coord) += _mu[_qp] * r_vel / (r * r);
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSBase.C:378]: what you can be confident about now is that if something is wrong, then it's wrong in two places! 😄

File: modules/navier_stokes/src/kernels/INSBase.C [hunk 6]
```diff
@@ -143,7 +145,7 @@ INSBase::strongViscousTermLaplace()
 RealVectorValue
```
Comment (GiudGiud) [inline modules/navier_stokes/src/kernels/INSBase.C:145]: in the routine above, are we missing a grad_u * grad_mu term here?

from div(mu grad_u) = mu div grad u + grad_u . grad_mu

Comment (GiudGiud) [reply modules/navier_stokes/src/kernels/INSBase.C:145]: I guess this isnt specific to RZ. Porbably a common approximation considering mu doesnt move much. Could be worth documenting?

**Review by GiudGiud — APPROVED** [review]
all good

File: modules/navier_stokes/src/kernels/INSBase.C (hunk 6 above)
Comment (GiudGiud) [reply modules/navier_stokes/src/kernels/INSBase.C:145]: yes that is also true that we have not necessarily paid more attention to this term elsewhere

Comment (lindsayad) [reply modules/navier_stokes/src/kernels/INSBase.C:145]: I've opened https://github.com/idaholab/moose/issues/26217
