### PR TITLE
Fix memory errors, change reported IDs

### LINKED ISSUE #6445: Change reporting of node/element IDs in XFEM
### Description of the enhancement or error report
When XFEM creates/deletes nodes and elements, it is currently adding 1 to them (for consistency with Exodus output). Don't do that anymore.

### Rationale for the enhancement or information for reproducing the error
 Better to not do that for consistency with the rest of MOOSE.

### Identified impact
Minor change to XFEM.C, only console output is affected.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #6445
ref #6446

### CODE REVIEW

File: modules/xfem/src/base/XFEM.C [hunk 1]
```diff
@@ -893,7 +893,7 @@ XFEM::cutMeshWithEFA()
 
     new_node->set_n_systems(parent_node->n_systems());
     efa_id_to_new_node.insert(std::make_pair(new_node_id,new_node));
-    _console<<"XFEM added new node: "<<new_node->id()+1<<std::endl;
+    _console << "XFEM added new node: " << new_node->id() <<std::endl;
```
Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: Time to start getting rid of these overused `std::endls`. Generally you should do a bunch of output then a single flush. This is inside of a for loop so it's just unecessary and potentially slow.

**Comment by bwspenc** [comment]
@jwpeterson This might fix your issue.  If you could test it on your machine and let me know if it does, I'd appreciate it.

File: modules/xfem/src/base/XFEM.C (hunk 1 above)
Comment (bwspenc) [inline modules/xfem/src/base/XFEM.C]: OK.  I'll fix that.

Comment (permcody) [inline modules/xfem/src/base/XFEM.C]: Take a look at all the others in the file. We don't mind having them here
and there when you really need output for synchronization, just try to keep
them down as much as possible. It can be expensive on a cluster to flush an
output buffer.

**Comment by permcody** [comment]
:+1:
