### PR TITLE
Remove unnecessary code to improve performance

### LINKED ISSUE #13715: Remove a global communication from getBoundaryIDs
## Bug Description

In` MooseMesh.C, getBoundaryIDs`, we try to collect all boundary IDs together, which involves 
one global communication. It is expensive and unnecessary since `_mesh_bounary_ids` already has the same information.

## Steps to Reproduce

Remove unnecessary  code.

## Impact

Improve parallel performance

### PR DESCRIPTION
**Pull request by fdkong**
In MooseMesh.C, getBoundaryIDs, we try to collect all boundary IDs together, which involves
one global communication. It is expensive and unnecessary since _mesh_bounary_ids already has the same information.

Closes #13715

### CODE REVIEW

File: framework/src/mesh/MooseMesh.C [hunk 1]
```diff
@@ -1045,14 +1045,7 @@ MooseMesh::getBoundaryIDs(const std::vector<BoundaryName> & boundary_name,
...
 
-  std::set<BoundaryID> boundary_ids = boundary_info.get_boundary_ids();
-
-  // On a distributed mesh we may have boundary ids that only exist on
-  // other processors.
-  if (!this->getMesh().is_replicated())
-    _communicator.set_union(boundary_ids);
-
-  BoundaryID max_boundary_id = boundary_ids.empty() ? 0 : *(boundary_ids.rbegin());
+  BoundaryID max_boundary_id = _mesh_boundary_ids.empty() ? 0 : *(_mesh_boundary_ids.rbegin());
```
Comment (permcody) [inline framework/src/mesh/MooseMesh.C]: The comment says that only some processors might know about certain boundaries. "max" suggests that all processors agree on something, which this change will no longer accomplish. Perhaps that's fine?

Comment (fdkong) [reply framework/src/mesh/MooseMesh.C]: If the code is running right, `_mesh_boundary_ids` should be identical to `boundary_ids`.  Nothing should change. There are some bugs related to interface kernel I am working on a fix.

**Review by permcody — APPROVED** [review]
