### PR TITLE
Ensure duplicates are not added to list of checkpoint files.

### LINKED ISSUE #24777: Subapp of type FullSolveMultiapp does not output checkpoint when enabled in subapp input file
## Bug Description
When running a FullSolveMultiapp subapp after each time step of a transient parent app, subapp checkpoints are not written when Outputs/checkpoint = true is set in the subapp input file.

## Steps to Reproduce
Do not set Outputs/checkpoint in the main app input file. Set Outputs/checkpoint = true in the subapp input file. When running the main app input file, an empty folder is created for subapp checkpoints, but no checkpoints are written. When running the subapp file directly, checkpoints are written as expected. This undesired behavior can be remedied by adding the following block to the subapp input file:

[Outputs]
    [checkpoint]
        type = Checkpoint
        additional_execute_on = 'FINAL'
    []
[]

## Impact
Given the existence of the "additional_execute_on" workaround, this is an annoyance.

### PR DESCRIPTION
**Pull request by pbehne**
## Reason
Checkpoint objects keep a list of currently written checkpoint files in the _file_names attribute. When the number of checkpoints stored in this variable exceeds the _num_files variable, the oldest checkpoint is deleted from the hard drive. Sometimes, a checkpoint has the same file names as older checkpoints. For instance, this happens in a multiapp where the parent is a transient and the subapp is a FullSolveMultiApp, with a checkpoint executed on final, executed after every parent time step. When this occurs, the previously output checkpoint is overwritten by the new checkpoint that shares the same file names. This can be though of unintentionally "deleting" a checkpoint without checking the size of _file_names. The size check on _file_names doesn't know about this deletion and deletes the most recent checkpoint, not knowing that the old checkpoint was already overwritten. In this manner, all checkpoints can be deleted, leaving the user with nothing at the end of the simulation.

## Design
This PR adds a check to see if the most recent checkpoint file names are contained in _file_names before re-adding them, triggering the extra deletion.

## Impact
Users will get checkpoints from their subapps when they request them.

Closes #24777.

### CODE REVIEW

**Comment by pbehne** [comment]
@GiudGiud, check this out.

I probably need to add tests. I'm going to follow up by working on issues #20998 (this PR might resolve that one) and #18958.

File: framework/src/outputs/Checkpoint.C [hunk 1]
```diff
@@ -183,8 +183,12 @@ Checkpoint::output()
 void
 Checkpoint::updateCheckpointFiles(CheckpointFileNames file_struct)
 {
-  // Update the list of stored files
-  _file_names.push_back(file_struct);
+  // Update the list of stored files if it does not already contain file_struct
+  // This ensures that we don't store duplicates, which will cause issues when
```
Comment (GiudGiud) [inline framework/src/outputs/Checkpoint.C:187]: > This ensures that we don't store duplicates

maybe adapt the language for clarity. there could be a duplicate in the vector, but when we re-store a checkpoint with the same name, it could be a different state still (in which case we do want to overwrite the previous file)

**Review by GiudGiud — COMMENTED** [review]
I think we would want that, even where there is going to be a duplicate, the could-have-been-duplicated should now be on the last position in the vector (where push_back would have put that new name)

**Comment by pbehne** [comment]
> I think we would want that, even where there is going to be a duplicate, the could-have-been-duplicated should now be on the last position in the vector (where push_back would have put that new name)

Agreed. Can you think of a simulation where the could-have-been-duplicated is not already on the last position? I can't. I made the logic change to be safe, though.

File: test/tests/outputs/checkpoint/checkpoint_child.i [hunk 2]
```diff
@@ -40,7 +40,7 @@
 
 [Executioner]
   type = Transient
-  num_steps = 11
+  num_steps = 2
```
Comment (GiudGiud) [inline test/tests/outputs/checkpoint/checkpoint_child.i:43]: why that change?

Comment (GiudGiud) [reply test/tests/outputs/checkpoint/checkpoint_child.i:43]: I m fine with it, just curious

Comment (pbehne) [reply test/tests/outputs/checkpoint/checkpoint_child.i:43]: Basically so the test doesn't take as long. By changing the multiapp type from transient to full solve, we are running all time steps of the sub app after every master app time step. Not necessary or desirable.

**Review by GiudGiud — APPROVED** [review]
