### PR TITLE
Fixes and tests for coupling tagged solution vectors

### LINKED ISSUE #17586: Need to test more about coupling variables with tagged solution vectors
## Reason
Coupling variables in a tagged solution vector can be very useful for designing custom iterative solve objects. It is not fully tested yet. And some of my preliminary investigations revealed some missing pieces of the dependency on initializing variables from a tagged solution vector.

## Design
We need to add more tests and fix this loopholes for coupling variables with tagged solution vectors. I am planning to extend `FixedPoint` solve object in MOOSE test to test this capability and propose some fixes.

## Impact
New capability.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #17586.

### CODE REVIEW

**Comment by YaqiWang** [comment]
This is ready for review.

**Comment by YaqiWang** [comment]
@fdkong when will you be available for reviewing this? I will be needing this soon.

File: test/src/materials/VarCouplingMaterial.C [hunk 1]
```diff
@@ -20,12 +20,13 @@ VarCouplingMaterial::validParams()
...
   params.addParam<bool>(
       "declare_old", false, "When True the old value for the material property is declared.");
+  params.addParam<TagName>("tag", "The solution vector to be coupled in");
   return params;
 }
 
 VarCouplingMaterial::VarCouplingMaterial(const InputParameters & parameters)
   : Material(parameters),
-    _var(coupledValue("var")),
+    _var(coupledVectorTagValue("var", "tag")),
```
Comment (fdkong) [inline test/src/materials/VarCouplingMaterial.C:29]: We should check if tag does exist or not. If it exists, we should call `coupledValue`. 

It does not sound right for me that we let `coupledVectorTagValue` involve  `coupledValue` when tag does not exist.

File: test/src/problems/FixedPointProblem.C [hunk 2]
```diff
@@ -18,43 +18,65 @@ FixedPointProblem::validParams()
...
 FixedPointProblem::FixedPointProblem(const InputParameters & params)
   : FEProblem(params),
+    _tagged_vector_for_partial_residual(getParam<bool>("tagged_vector_for_partial_residual")),
     _tag_previous(getParam<TagName>("fp_tag_name")),
-    _tag_id(addVectorTag(_tag_previous)),
-    _residual_previous(_nl->addVector(_tag_id, false, GHOSTED))
+    _tag_id(addVectorTag(_tag_previous,
+                         _tagged_vector_for_partial_residual ? Moose::VECTOR_TAG_RESIDUAL
+                                                             : Moose::VECTOR_TAG_SOLUTION)),
+    _tagged_vector(_nl->addVector(_tag_id, false, GHOSTED))
```
Comment (fdkong) [inline test/src/problems/FixedPointProblem.C:35]: IIRC, you do not like ghosted vector:-) Could we use parallel vector to save memory ?

File: framework/src/interfaces/Coupleable.C [hunk 3]
```diff
@@ -522,6 +598,22 @@ Coupleable::coupledMatrixTagValue(const std::string & var_name, TagID tag, unsig
   return var->matrixTagValue(tag);
 }
 
+const VariableValue &
+Coupleable::coupledMatrixTagValue(const std::string & var_name,
+                                  const std::string & tag_name,
+                                  unsigned int comp) const
+{
+  if (!_c_parameters.isParamValid(tag_name))
+    return coupledValue(var_name, comp);
```
Comment (fdkong) [inline framework/src/interfaces/Coupleable.C:607]: This is totally wrong. We do not have a default couple for matrix

**Review by fdkong — CHANGES_REQUESTED** [review]
It looks good for me in general. But we might  improve APIs

```
Coupleable::coupledVectorTagValue(const std::string & var_name,
                                   const std::string & tag_name,
                                   unsigned int comp) const
 {
   if (!_c_parameters.isParamValid(tag_name))
     return coupledValue(var_name, comp);
```

It might mot be a good idea to  fall back to the default `coupledValue` when tag does not exist.

We should simply error out. The default solution often  is not tagged. 

We need to do the same thing for `Coupleable::coupledVectorTagGradient`, `Coupleable::coupledVectorTagDofValue`, ` coupledMatrixTagValue(const std::string & var_name,` ` Coupleable::coupledVectorTagValues(const std::string & var_name, const std::string & tag_name) const`, ` Coupleable::coupledVectorTagGradients`, `Coupleable::coupledVectorTagDofValues`, `Coupleable::coupledMatrixTagValues`

File: test/src/problems/FixedPointProblem.C (hunk 2 above)
Comment (YaqiWang) [reply test/src/problems/FixedPointProblem.C:35]: I did not try in MOOSE but did try in Griffin and failed. I will try and let you know.

File: framework/src/interfaces/Coupleable.C [hunk 4]
```diff
@@ -492,6 +498,60 @@ Coupleable::coupledVectorTagValue(const std::string & var_name, TagID tag, unsig
     return var->vectorTagValue(tag);
 }
 
+const VariableValue &
+Coupleable::coupledVectorTagValue(const std::string & var_name,
+                                  const std::string & tag_name,
+                                  unsigned int comp) const
+{
+  if (!_c_parameters.isParamValid(tag_name))
+    return coupledValue(var_name, comp);
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/interfaces/Coupleable.C:507]: Typically the parameter of tag name if for a particular iterative solver and the same kernel is also for our general solver which does not require the tag name parameter. We could move this out side of this function in kernel's constructor header, but my argument is that this will make the normal use case tedious. If a user want, they can always do this check on their own. `CoupledForceLagged` gives an example. This is kind of equivalent with having the default tag name for the current solution vector. If we have that tag, users can put that tag name in the parameter as the default value. If the tag name parameter is required, like in `TagVectorAux`, we will not hit this early return. Does this convince you?

File: test/src/materials/VarCouplingMaterial.C (hunk 1 above)
Comment (YaqiWang) [reply test/src/materials/VarCouplingMaterial.C:29]: If we have a tag name for the current solution vector, this will make sense. I can add that tag in `FEProblemBase` include `current_solution_tag`, `old_solutioner_tag`, `older_solution_tag` and associate them to the solution vectors. Then users can use them ad the default value of the `tag` parameter. What do you think?

File: test/src/problems/FixedPointProblem.C (hunk 2 above)
Comment (YaqiWang) [reply test/src/problems/FixedPointProblem.C:35]: Just tried, these two new tests using tagged solution vector:
```
executioners/fixed_point.tagged_solution_vector/var ........................................... FAILED (CRASH)
executioners/fixed_point.tagged_solution_vector/material ...................................... FAILED (CRASH)
```
crashed with four processors. I guess for nodal variables, we have to make it ghosted. For DG, DG kernels typically require ghosted solutions as well. If the tagged vector is for residual, it can be less restrictive unless the vector is used as solutions. Conclusion is that we have to make this ghosted.

File: framework/src/interfaces/Coupleable.C (hunk 4 above)
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/src/interfaces/Coupleable.C:507]: My concern is "return coupledValue(var_name, comp);" when users do not set tag name or the tag name does not exist.

In other words, I want to separate this API from `coupledValue`. I do not want this API call `coupledValue`. 

When users call this API and also want to use `coupledValue` when tag name does not exist,  users should do their `if ` logic .

[the remark this answers is not in the document]
Comment (fdkong) [reply framework/src/interfaces/Coupleable.C:507]: What I want to is 

```
if (!_c_parameters.isParamValid(tag_name) )
  MooseError("You have to specify tag name if you want to use  coupledVectorTagValue ")
  

  TagName tagname = _c_parameters.get<TagName>(tag_name);
  if (tagname.empty())
    MooseError("You can not use coupledVectorTagValue because tag name does not exist ")
```

File: test/src/materials/VarCouplingMaterial.C (hunk 1 above)
Comment (YaqiWang) [reply test/src/materials/VarCouplingMaterial.C:29]: I have a better design now along this line. It is working but I will need more time for polishing.

File: framework/src/base/Assembly.C [hunk 5]
```diff
@@ -2489,7 +2489,11 @@ Assembly::init(const CouplingMatrix * cm)
   if (_block_diagonal_matrix && scalar_vars.size() != 0)
     _block_diagonal_matrix = false;
 
-  auto num_vector_tags = _residual_vector_tags.size();
```
Comment (YaqiWang) [inline framework/src/base/Assembly.C:2492]: This line of code assumes the residual tags are ordered from 0 sequentially, which in general may not be true. The change at the following along the changes in `TimeIntegrator` can fix this temporarily but I believe that somewhere else in the code we have the same assumption. @fdkong can you think of any? I know because if I reset the changes in `TimeIntegrator` I got test failures.

File: framework/src/systems/SystemBase.C [hunk 6]
```diff
@@ -1433,7 +1451,11 @@ SystemBase::needSolutionState(const unsigned int state)
   // We will manually add all states past current
   for (unsigned int i = 1; i <= state; ++i)
     if (!_solution_states[i])
-      _solution_states[i] = &addVector(oldSolutionStateVectorName(i), true, GHOSTED);
+    {
+      auto tag =
+          _subproblem.addVectorTag(oldSolutionStateVectorName(i), Moose::VECTOR_TAG_SOLUTION);
```
Comment (YaqiWang) [inline framework/src/systems/SystemBase.C:1456]: I tagged old and older solutions because we are managing them but we cannot tag the solution `solution()` or `currentSolution()` because it is a vector passed in by the solver and could be changing. This causes the special treatment in `coupledVectorTagValue` when the tag name is `SOLUTION_TAG`.

File: test/tests/variables/previous_newton_iteration/test.i [hunk 7]
```diff
@@ -10,6 +10,10 @@
   elem_type = QUAD9
 []
 
+[Problem]
+  previous_nl_solution_required = true
```
Comment (YaqiWang) [inline test/tests/variables/previous_newton_iteration/test.i:14]: Because now I use tag to manage this solution vector, we have to add the vector earlier. This requires users to turn this flag to true when the vector is used. But I think this is the right design. Users can use their own actions to add the vector for better user interface if desired.

File: framework/src/base/Assembly.C (hunk 5 above)
Comment (fdkong) [reply framework/src/base/Assembly.C:2492]: We do not expect any order here. It does not need to start from zero.

Comment (fdkong) [reply framework/src/base/Assembly.C:2492]: If that caused issue, it should be a bug or something

File: test/tests/variables/previous_newton_iteration/test.i (hunk 7 above)
Comment (YaqiWang) [reply test/tests/variables/previous_newton_iteration/test.i:14]: Looks like no application is using this. Surprising.

File: framework/src/base/Assembly.C (hunk 5 above)
Comment (YaqiWang) [reply framework/src/base/Assembly.C:2492]: In `Assembly`, we are using `_type_id` for indexing, but in `TaggingInterface`, we use `_id`, which may mismatch `_type_id`. The fix should be in `TaggingInterface`. Just figured that out.

File: framework/src/interfaces/Coupleable.C (hunk 4 above)
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/interfaces/Coupleable.C]: I updated this part as you suggested. The only difference is that I added a new tag name for users to indicate that they want to use the same interface sometimes for coupling the current solution.

File: framework/src/interfaces/Coupleable.C (hunk 3 above)
Comment (YaqiWang) [reply framework/src/interfaces/Coupleable.C]: fixed.

**Comment by YaqiWang** [comment]
@fdkong Can I get a review again? All previous comments were addressed.

File: framework/src/systems/SystemBase.C (hunk 6 above)
Comment (fdkong) [reply framework/src/systems/SystemBase.C:1456]: We should stay with `currentSolution()` that is managed in libmesh not in solver side.  It does not change  within one one time step

File: framework/src/transfers/MultiAppFieldTransfer.C [hunk 8]
```diff
@@ -59,8 +67,8 @@ MultiAppFieldTransfer::transferDofObject(libMesh::DofObject * to_object,
         dof_id_type dof = to_object->dof_number(to_var.sys().number(), to_var.number() + vc, comp);
         dof_id_type from_dof =
             from_object->dof_number(from_var.sys().number(), from_var.number() + vc, comp);
-        Real from_value = from_var.sys().solution()(from_dof);
-        to_var.sys().solution().set(dof, from_value);
+        Real from_value = from_solution(from_dof);
+        to_solution.set(dof, from_value);
```
Comment (fdkong) [inline framework/src/transfers/MultiAppFieldTransfer.C:71]: We could transfer from an arbitrary solution to an arbitrary solution. But we have to check if the solution is compatible with the variables. 

I want to understand the use case. What use case you have?

File: framework/src/variables/MooseVariableData.C [hunk 9]
```diff
@@ -1291,6 +1322,63 @@ MooseVariableData<OutputType>::computeMonomialValues()
...
+        {
+          auto & mat = _sys.getMatrix(tag);
+          {
+            Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
+            _matrix_tags_dof_u[tag][0] = mat(_dof_indices[0], _dof_indices[0]);
+          }
+        }
+    }
+  }
+  for (auto tag : active_coupleable_matrix_tags)
```
Comment (fdkong) [inline framework/src/variables/MooseVariableData.C:1374]: We might need to move this into "if (_sys.subproblem().safeAccessTaggedMatrices())"

**Review by fdkong — CHANGES_REQUESTED** [review]
Can we actually tag solution as well?

File: framework/src/systems/SystemBase.C (hunk 6 above)
Comment (YaqiWang) [reply framework/src/systems/SystemBase.C:1456]: It is true on libmesh side, but moose manage it as a `const` solution pointer. So we cannot directly use that pointer for tagging because tagging assumes we want to change a vector. I believe that this pointer is not always pointing to libmesh current solution. I tried to directly tag that vector but failed. We possibly should tag during calling `setSolution` but in that function the solution is passed in as a const reference which we cannot tag unless we change our current design in `SystemBase.h`:
```
std::vector<NumericVector<Number> *> _tagged_vectors;
```

File: framework/src/transfers/MultiAppFieldTransfer.C (hunk 8 above)
Comment (YaqiWang) [reply framework/src/transfers/MultiAppFieldTransfer.C:71]: If the variables are on the same mesh with same FE family, they are compatible, right? The code does check those. My use case is to transfer main app solution to subapp tagged aux vector and the subapp uses it as the source for a steady-state calculation with `Steady`.

File: framework/src/variables/MooseVariableData.C (hunk 9 above)
Comment (YaqiWang) [reply framework/src/variables/MooseVariableData.C:1374]: I am not sure about this because this is aligned with the treatment for `safeAccessTaggedVectors`. The evaluation for vectors are not inside of `safeAccessTaggedVectors`.

**Review by fdkong — CHANGES_REQUESTED** [review]
We are very close to the point wan can merge.

Only concern for me right now is: do we have to change TaggingInterface.C/h? If so, we would to rename API otherwise it is confusing

File: framework/include/interfaces/TaggingInterface.h [hunk 10]
```diff
@@ -48,7 +48,7 @@ class TaggingInterface
 
   bool isMatrixTagged() { return _matrix_tags.size() > 0; }
 
-  const std::set<TagID> & getVectorTags() const { return _vector_tags; }
+  const std::set<TagID> & getVectorTags() const { return _vector_tag_ids; }
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/include/interfaces/TaggingInterface.h:51]: The difference of these two is that one is a set of `_id`s another is a set of `_type_id`s. The `_type_id` is used in Assembly for managing the local residual vectors. The `_id`s is used by MOOSE warehouse for things I did not look into much.

File: framework/include/interfaces/TaggingInterface.h [hunk 11]
```diff
@@ -132,6 +132,9 @@ class TaggingInterface
 
 protected:
   /// The vectors this Kernel will contribute to
+  std::set<TagID> _vector_tag_ids;
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/include/interfaces/TaggingInterface.h:135]: See above. We basically need to be careful on the difference on `_id` and `_type_id` of `VectorTag`. Previously the two do not have difference because `_type_id` is a subset and always match `_id`. Remember I mentioned on slack that there could be a bug somewhere in the code not differentiating the two properly, which I have really hard time to figure out, after I fix something obvious in `TaggingInterface`. My current design does not trigger that, so I will leave that as part of our future work of maintaining tagged solutions and residuals separately.

File: framework/src/variables/MooseVariableData.C [hunk 12]
```diff
@@ -1291,6 +1322,63 @@ MooseVariableData<OutputType>::computeMonomialValues()
         _u_older[qp] = _u_older[qp];
     }
   }
+
+  auto && active_coupleable_vector_tags =
+      _sys.subproblem().getActiveFEVariableCoupleableVectorTags(_tid);
+  auto && active_coupleable_matrix_tags =
+      _sys.subproblem().getActiveFEVariableCoupleableMatrixTags(_tid);
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/variables/MooseVariableData.C:1329]: I copied from another function, lol. I honestly do not know why do we need this. I can certainly make it a `&`.

File: framework/src/base/Assembly.C [hunk 13]
```diff
@@ -3334,12 +3334,11 @@ Assembly::cacheResidual()
...
   for (const auto & var : vars)
-    for (MooseIndex(_residual_vector_tags) tag_index = 0; tag_index < _residual_vector_tags.size();
-         tag_index++)
-      if (_sys.hasVector(_residual_vector_tags[tag_index]._id))
-        cacheResidualBlock(_cached_residual_values[tag_index],
-                           _cached_residual_rows[tag_index],
-                           _sub_Re[tag_index][var->number()],
+    for (const auto & vector_tag : _residual_vector_tags)
+      if (_sys.hasVector(vector_tag._id))
+        cacheResidualBlock(_cached_residual_values[vector_tag._type_id],
```
Comment (YaqiWang) [inline framework/src/base/Assembly.C:3339]: so `_residual_vector_tags` is not ordered based on `_type_id`?

File: framework/src/base/Assembly.C [hunk 14]
```diff
@@ -3348,8 +3347,10 @@ Assembly::cacheResidual()
 void
 Assembly::cacheResidual(dof_id_type dof, Real value, TagID tag_id)
 {
-  _cached_residual_values[tag_id].push_back(value);
-  _cached_residual_rows[tag_id].push_back(dof);
+  const VectorTag & tag = _subproblem.getVectorTag(tag_id);
```
Comment (YaqiWang) [inline framework/src/base/Assembly.C:3350]: You may want to add in the header explaining that the tag id passed in here is not the _type_id of a tag.

Comment (YaqiWang) [reply framework/src/base/Assembly.C:3350]: Or make this unchanged and change the other few places calling this function. I think this makes things cleaner in sense that all the TagID in assembly are _type_id.

File: framework/src/base/Assembly.C [hunk 15]
```diff
@@ -3384,10 +3385,11 @@ Assembly::cacheResidualNodes(const DenseVector<Number> & res,
   // respectively.
   // This is used by NodalConstraint.C to cache the residual calculated for primary and secondary
   // node.
+  const VectorTag & vector_tag = _subproblem.getVectorTag(tag);
```
Comment (YaqiWang) [inline framework/src/base/Assembly.C:3388]: We do not have to change this because it seems no code is passing `tag` in except using its default value 0.

File: framework/src/base/Assembly.C (hunk 13 above)
Comment (fdkong) [reply framework/src/base/Assembly.C:3339]: `_residual_vector_tags` is ordered by default. If I did not make this change, the code would still run fine.

But I do not want to make an unnecessary assumption. And so I made code more general

File: framework/src/base/Assembly.C (hunk 14 above)
Comment (fdkong) [reply framework/src/base/Assembly.C:3350]: API should always use  tag_id. We only index local vectors using _type_id.

File: framework/src/base/Assembly.C (hunk 15 above)
Comment (fdkong) [reply framework/src/base/Assembly.C:3388]: I do not want to make that assumption. More general better for me

**Comment by fdkong** [comment]
If you guys @loganharbour @lindsayad do not have suggestions, I would like to merge this PR in today

File: framework/src/variables/MooseVariableData.C (hunk 12 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/variables/MooseVariableData.C:1329]: It is a universal reference; it can bind to both l-value and r-value references

[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/variables/MooseVariableData.C:1329]: It is generally a good design if you don't know whether an API returns a reference or a new object

[the remark this answers is not in the document]
Comment (fdkong) [reply framework/src/variables/MooseVariableData.C:1329]: It is interesting. I learned. Possibly I should always use "&&" in the future. How about a pointer?

File: framework/include/utils/MooseTypes.h [hunk 16]
```diff
@@ -934,3 +934,11 @@ DerivativeStringClass(ExtraElementIDName);
 
 /// Name of a Reporter Value, second argument to ReporterName (see Reporter.h)
 DerivativeStringClass(ReporterValueName);
+
+namespace Moose
+{
+extern const TagName SOLUTION_TAG;
+extern const TagName OLD_SOLUTION_TAG;
+extern const TagName OLDER_SOLUTION_TAG;
+extern const TagName PREVIOUS_NL_SOLUTION_TAG;
```
Comment (lindsayad) [inline framework/include/utils/MooseTypes.h:943]: Are all these new names necessary? I thought were trying to move away from the old, older, olderer, oldererer design

Comment (YaqiWang) [reply framework/include/utils/MooseTypes.h:943]: What is the plan to move away from old, older, like stateful material props, old/older pps, etc.? The `Coupleable` interface can move away from `CoupledValueOld`, `implicit` etc. but it still requires the tag name to point which vector to be coupled in.

File: framework/src/variables/MooseVariableData.C (hunk 12 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/variables/MooseVariableData.C:1329]: You mean if you're catching a returned pointer? Note that if you are not going to modify an object, catching as `const auto &` is probably preferable (I haven't checked what you're doing here so I won't comment on whether this should be `const`)

File: framework/include/utils/MooseTypes.h (hunk 16 above)
Comment (lindsayad) [reply framework/include/utils/MooseTypes.h:943]: Can't get by with a `TagID`? I don't know these systems very well so this may be a dumb question

Comment (lindsayad) [reply framework/include/utils/MooseTypes.h:943]: But I suppose even with a `TagID` that's just the type and not a value/identifier. Ok yea I'm sure this is fine

**Review by lindsayad — APPROVED** [review]

File: framework/include/utils/MooseTypes.h (hunk 16 above)
Comment (YaqiWang) [reply framework/include/utils/MooseTypes.h:943]: These names can also be used by developers to provide the default tag name for calling `coupledVectorTagValue`. We can replace `implicit` parameter with `addParam<TagName>("tag", Moose::SOLUTION_TAG, "")`. Then we can replace `coupledValue("var")` with `coupledVectorTagValue("var", "tag")`. Thus we can keep only `coupledVectorTagValue` and users can use `tag = SOLUTION_1` to make a kernel implicit. The `tag` parameter can be a parameter for `Coupleable`, so we can simplify `coupledVectorTagValue("var", "tag")` back into `coupledValue("var")`. I think we are slowly moving to that direction. Does this make sense?

**Review by fdkong — APPROVED** [review]
