### PR TITLE
Resolve `DependencyResolver` issue with missing cyclic sub-graphs

### LINKED ISSUE #26575: `DependencyResolver` is missing a cyclic check
## Bug Description
In the event that we have any sub-graphs that are cyclic that do not have any roots (no adjacencies) and we have found one or more other sub-graphs with a root, we will have never visited the afformentioned cyclic sub-graphs. In this case, the `DependencyResolver` will actually only return the sorted ordering of the nodes that are in the non-cyclic sub graphs.

The simplest example is the following graph

```
0        1 <-> 2
```

where a cyclic dependency exists between 1 and 2. In this case, the `DependencyResolver` will return only node 0 in the depth first search sorted list.

## Steps to Reproduce

Sort with the following:

```
  DependencyResolver<int> resolver;
  resolver.addItem(0);
  resolver.addItem(1);
  resolver.addItem(2);
  resolver.addEdge(1, 2);
  resolver.addEdge(2, 1);
  const auto & sorted = resolver.dfs();
```

in which case `sorted` will be `[0]`.

## Impact

Could lead to missing execution of objects when there are cyclic dependencies.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #26575

### CODE REVIEW

**Comment by loganharbour** [comment]
I'm still going to add in the extra assertions to `TheWarehouse` that got me to this point

File: framework/include/interfaces/DependencyResolverInterface.h [hunk 1]
```diff
@@ -82,35 +82,33 @@ DependencyResolverInterface::sortDFS(typename std::vector<T> & vector)
   std::multimap<std::string, T> suppliers_map;
   for (auto & v : vector)
   {
+    // Whether or not this object supplies something, we will always
+    // add it as node because we want to make sure that it gets returned
```
Comment (lindsayad) [inline framework/include/interfaces/DependencyResolverInterface.h:86]:
```suggestion
    // add it as a node because we want to make sure that it gets returned
```

File: framework/include/utils/DependencyResolver.h [hunk 2]
```diff
@@ -278,7 +282,24 @@ DependencyResolver<T, Compare>::dfs()
       if (is_cyclic)
         break;
     }
-  if (!roots_found)
+
+  if (roots_found)
+  {
+    // At this point, if we have any sub-graphs that are cyclic that do not have any
+    // roots _and_ we have found one more or more separate sub-graphs with a root,
+    // we will have never visited the afformentioned cyclic sub-graphs. Therefore,
```
Comment (lindsayad) [inline framework/include/utils/DependencyResolver.h:290]:
```suggestion
    // we will have never visited the aforementioned cyclic sub-graphs. Therefore,
```

File: framework/include/utils/DependencyResolver.h [hunk 3]
```diff
@@ -405,7 +429,12 @@ bool
 DependencyResolver<T, Compare>::dfsFromNode(const T & root)
 {
   bool cyclic = false;
-  _visited[root] = true;
+  auto & visited = _visited.at(root);
```
Comment (lindsayad) [inline framework/include/utils/DependencyResolver.h:432]:
```suggestion
  auto & visited = libmesh_map_find(_visited, root);
```

**Review by lindsayad — APPROVED** [review]

**Comment by loganharbour** [comment]
@GiudGiud take a look at your failing positions test: https://civet.inl.gov/job/2005939/

In CLI args you end up adding a cyclic dependency that ends up expanding like this

```
[Positions]
  [input]
    type = InputPositions
    positions = '0 1 0
                 1 0 2'
    outputs = none
    initial_positions = file # cyclic
  []
  [file]
    type = FilePositions
    files = '../../multiapps/positions_from_file/positions.txt'
    outputs = none
    initial_positions = input # cyclic
  []
  ...
```

When I remove `initial_positions` from both, it still passes. Ideas?

File: framework/include/interfaces/DependencyResolverInterface.h [hunk 4]
```diff
@@ -122,7 +122,7 @@ DependencyResolverInterface::cyclicDependencyError(CyclicDependencyException<T2>
   const auto cycle = e.getCyclicDependencies();
   std::vector<std::string> names(cycle.size());
   for (const auto i : index_range(cycle))
-    names[i] = static_cast<T>(cycle[i])->name();
+    names[i] = static_cast<T>(cycle[i])->typeAndName();
```
Comment (lindsayad) [inline framework/include/interfaces/DependencyResolverInterface.h:125]: I kind of liked how concise the output was before. Seems like this could be a lot of text for a large cycle. I also don't know why there is a trailing slash after the name in `typeAndName()`

Comment (loganharbour) [reply framework/include/interfaces/DependencyResolverInterface.h:125]: There isn't a trailing slash? It's `ObjectType "name"`:

```
  /**
   * Get the class's combined type and name; useful in error handling.
   * @return The type and name of this class in the form '<type()> "<name()>"'.
   */
  std::string typeAndName() const
  {
    return type() + std::string(" \"") + name() + std::string("\"");
  }
```

It made it a lot easier for me to debug, but I'm not invested. Will remove

**Comment by GiudGiud** [comment]
I think this test was showing that when querying positions at initial, the initial_positions was not queried at initial. (so no infinite series of calls if the intiial position of the initial position was the first position). 
If that s leading to a cycle in the object creation dependency resolution, feel free to modify the test

File: framework/include/interfaces/DependencyResolverInterface.h (hunk 4 above)
Comment (lindsayad) [reply framework/include/interfaces/DependencyResolverInterface.h:125]: Lol, read the string wrong. If this was really helpful for you, then let's keep it

**Comment by loganharbour** [comment]
> I think this test was showing that when querying positions at initial, the initial_positions was not queried at initial. (so no infinite series of calls if the intiial position of the initial position was the first position). If that s leading to a cycle in the object creation dependency resolution, feel free to modify the test

Got it.

I removed the cyclic dependency, but the test is still able to test initial positions for a single object instead of both.
