### PR TITLE
Handle moving boundary inside a shared top parent of refined elements

### LINKED ISSUE #30275: Mesh modification: moving boundary does not seem to follow the subdomain changes when using boundary mesh refinement
## Issue
See title and related discussions post.

## How to reproduce
See input file in #30274 and apply the modification listed below

## Impact
External user simulation failures

I also tried to use the `BoundaryPreservedMarker', and it seems to work around the problems, but the `moving boundary` created was not correct. The simulation finally aborted at time step 241 (t=24.1, start of the 7th layer) with `YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)`.

```
[GlobalParams]
  displacements = 'disp_x disp_y'
  use_displaced_mesh = true
[]

[Mesh]
  displacements = 'disp_x disp_y'
[]

  [DirichletBC_top]
    type = DirichletBC
    variable = Temperature
    boundary = 'top_active'
    value = 330.0
    # use_displaced_mesh = false
  []
```
```
    [marker_boundary_preserve]
      block = 1
      type = BoundaryPreservedMarker
      preserved_boundary = 'top_active'
      marker = 'marker_error_frac_von_mises'
    []
```

The white horizontal lines are the moving border. As we can see, there are multiple lines rather than a single line.

**t = 4.1s (start of second layer)**
image

**t = 8.1s (start of third layer)**
image

**t = 12.1s (start of 4th layer)**
image

**t = 16.1s (start of 5th layer)**
image

_Originally posted by @keassyguang in https://github.com/idaholab/moose/discussions/29699#discussioncomment-12763944_

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #30275 

this does not work to find active neighbors of an element because of the possibility of being inside the top parent
```
auto neigh = elem->neighbor_ptr(side);
neigh->top_parent()->active_family_tree_by_neighbor(active_neighs, elem);
```

@roystgnr maybe you have seen this done differently?

alternatively we could have this routine on the element:
```
  std::vector<const Elem *> active_neighs;
  elem->active_neighbors(active_neighs);
```

### CODE REVIEW

File: framework/src/meshmodifiers/ElementSubdomainModifierBase.C [hunk 1]
```diff
@@ -314,8 +314,29 @@ ElementSubdomainModifierBase::gatherMovingBoundaryChanges(
           gatherMovingBoundaryChangesHelper(elem, side, neigh, neigh_side);
         else
         {
+          // Find the active neighbors of the element
           std::vector<const Elem *> active_neighs;
-          neigh->top_parent()->active_family_tree_by_neighbor(active_neighs, elem);
+          // Neighbor has active children, they are neighbors of the element along that side
```
Comment (roystgnr) [inline framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: A subactive() element is sub (below) active - it will have active ancestors, but never active children or other descendants.

So something's wrong here.  What is the goal precisely?

**Review by roystgnr — CHANGES_REQUESTED** [review]

File: framework/src/meshmodifiers/ElementSubdomainModifierBase.C (hunk 1 above)
Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: I think the ! makes the logic right.
it is not subactive (and it is not active, see right above), so it has active children

Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: the goal is to be able to follow the boundary as it enters an inactive top parent, and progresses through the refined elements

Comment (roystgnr) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: Well, missing the `!` was silly of me.  That simple case is correct, then.

The subactive case is still worrying me, though.

1.  How did we hit it?  This is getting called during mesh generation, right?  But we usually only have subactive elements when we're in the middle of some mesh coarsening (after elements are coarsened but before the systems finish projecting solutions) or geometric multigrid, and in either case we shouldn't be modifying the mesh.  Could we possibly just replace that whole branch with an assertion or error in the subactive case?

2.  "Active element we look for is coarser" isn't true in general.  Imagine a mesh with two quads, refined into 8 active quads with 2 ancestors, then half-coarsened into 5 active (4 fine, 1 coarse) quads but without yet removing the now-subactive 4.  Two of those 4 will have active neighbors at the same level as them, not coarser, and the other two will only have subactive neighbors.

Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: > How did we hit it? This is getting called during mesh generation, right?

nope during a solve. The user is moving a boundary and using AMR with a boundary marker at the same time. So we are refining elements, then moving the boundary within the refined element, and refining it more while inside as well. 

> Could we possibly just replace that whole branch with an assertion or error in the subactive case?

the subactive case is actually the one that matters here, see the coverage report. The others are harder to hit it seems!

> "Active element we look for is coarser" isn't true in general.

I understand what you are saying for the neighbor. 
But here, if an element is subactive, does it not mean that the active one is always a coarse parent of it?

Comment (roystgnr) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: This is really surprising.  The standard way to refine during a solve includes a call to `EquationSystems::reinit()` (because if you're refining your mesh mid-solve you'll need to be renumbering your DoFs and projecting your vectors and everything too), and unless we've specifically disabled it (which I don't see MOOSE doing) we do a `contract()` on the mesh and remove all the subactive elements before the `reinit()` returns.

This isn't just an academic worry - I don't recall that we go through much trouble to keep subactive elements' neighbor pointers valid, so seeing code relying on them is scary.

> But here, if an element is subactive, does it not mean that the active one is always a coarse parent of it?

Possibly a grandparent or higher if subactive elements have been retained through more than one coarsening step, but there should be some active ancestor at some point, yes.  I think I misunderstood your comment - I thought you were expecting to see coarser active neighbors, but you were talking about the coarser active parent.

What's the status of `elem` in this context?  If it's something we know, is it something we can assert?

Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: >  and remove all the subactive elements before the reinit() returns.

so I could just assert that we are not dealing with that, since I dont expect we would (and from coverage we are not)

> What's the status of elem in this context? If it's something we know, is it something we can assert?

elem is active and local afaik

Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: if you run the test locally and look at the exodus you ll see the context element-neighbor wise

Comment (roystgnr) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: Gah - I misunderstood you again, at "the subactive case is actually the one that matters here, see the coverage report" - you mean the `!subactive` case is the one that matters; now that I look at the report, we're not even hitting the subactive case.

> I could just assert that we are not dealing with that

Honestly I think that's the safest option.  I can't vouch for the subactive case's correctness here, and if it's not correct we'd basically just be leaving a red herring to confuse future users if there's some reason (e.g. preserving subactive elements during some kinds of transient AMR to reduce heap thrashing wouldn't be crazy) that code will ever be hit down the line.  My first impulse would be `else libmesh_not_implemented();` to make it clear that this isn't something we *can't* support, it's just not something we do support yet.  Maybe `libmesh_not_implemented_msg("Something about contacting developers");` to be nicer to whoever hits it.

Comment (GiudGiud) [reply framework/src/meshmodifiers/ElementSubdomainModifierBase.C:319]: ok I did that

**Review by roystgnr — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thanks!
