### PR TITLE
Error out on missing properties

### LINKED ISSUE #18917: Unknown material property in ParsedMaterial is not an error
## Bug Description
When using ParsedMaterial, if the material property listed in material_property_names is not defined, it becomes defined with a value of zero.  I think it would make more sense for this to be an error.  As it is now, input files will merrily run if someone mistypes a material property name.

## Steps to Reproduce
Use ParsedMaterial and supply a bogus material property in material_property_names.

## Impact
This behavior allows input file errors that are difficult to detect.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #18917

### CODE REVIEW

**Comment by dschwen** [comment]
Ping @jasondhales

File: framework/include/utils/FunctionMaterialPropertyDescriptor.h [hunk 1]
```diff
@@ -108,4 +108,7 @@ class FunctionMaterialPropertyDescriptor : public DerivativeMaterialPropertyName
 
   /// cache the final property name of the derivative
   std::string _property_name;
+
+  /// is this a property that was directly specified by the user? Then it _must_ exist.
+  bool _required;
```
Comment (loganharbour) [inline framework/include/utils/FunctionMaterialPropertyDescriptor.h:113]:
```suggestion
  const bool _required;
```
ya?

File: framework/src/utils/FunctionMaterialPropertyDescriptor.C [hunk 2]
```diff
@@ -68,7 +70,8 @@ FunctionMaterialPropertyDescriptor<is_ad>::FunctionMaterialPropertyDescriptor(
     _derivative_symbols(rhs._derivative_symbols),
     _value(nullptr),
     _parent(parent),
-    _property_name(rhs._property_name)
+    _property_name(rhs._property_name),
+    _required(false)
```
Comment (jasondhales) [inline framework/src/utils/FunctionMaterialPropertyDescriptor.C:74]: What's the purpose of having `_required` default to false?  In this case particularly, why is it not `rhs._required`?

File: framework/include/utils/FunctionMaterialPropertyDescriptor.h (hunk 1 above)
Comment (dschwen) [reply framework/include/utils/FunctionMaterialPropertyDescriptor.h:113]: nope

File: framework/src/utils/FunctionMaterialPropertyDescriptor.C (hunk 2 above)
Comment (dschwen) [reply framework/src/utils/FunctionMaterialPropertyDescriptor.C:74]: Because we copy existing descriptors to build the derivatives. We should only enforce properties to exist if they are explicitly coupled (in the `material_property_names` list).

File: framework/include/utils/FunctionMaterialPropertyDescriptor.h (hunk 1 above)
Comment (dschwen) [reply framework/include/utils/FunctionMaterialPropertyDescriptor.h:113]: To elaborate: It won't compile with `const` because the assignment operator will be implicitly deleted.

**Review by loganharbour — APPROVED** [review]

**Comment by tophmatthews** [comment]
Man alive I can't tell you how many times to screwed me , thanks for the fix @dschwen !
