### PR TITLE
Print an understandable message when a user-specified path/file does not exist

### LINKED ISSUE #15718: Misleading realpath petsc error
## Reason

When users have a not-exist  input file path, they possibly receive this error message:

```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Error in external library
[0]PETSC ERROR: realpath()
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.12.5, unknown 
```
We should replace this with a more-sense message such as:

`Failed to get real path for`

## Design

Override the petsc behavior in moose.

## Impact
None

### PR DESCRIPTION
**Pull request by fdkong**
Fixed this misleading petsc error message:

```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Error in external library
[0]PETSC ERROR: realpath()
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.12.5, unknown 
```

Closes #15718

### CODE REVIEW

**Comment by fdkong** [comment]
FYI @gambka

File: framework/src/utils/MooseUtils.C [hunk 1]
```diff
@@ -858,12 +858,24 @@ fileSize(const std::string & filename)
...
+#if defined(PETSC_HAVE_REALPATH)
+  // If "realpath" is adopted by PETSc and
+  // "path" does not exist, then PETSc will print a misleading message.
+  // [0]PETSC ERROR: Error in external library
+  // [0]PETSC ERROR: realpath()
+  // [0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
+  // [0]PETSC ERROR: Petsc Release Version 3.13.3, unknown
+  // We here override the misleading message with a better one.
+  if (!realpath(path.c_str(), dummy))
+    mooseError("Failed to get real path for ", path);
```
Comment (gambka) [inline framework/src/utils/MooseUtils.C:874]: Is this what we want to say? I guess it is still the path but even if you are in the correct directory and spell the input file incorrectly it will report the error. Would something as simple as "input_file_name" not found?

Comment (fdkong) [reply framework/src/utils/MooseUtils.C:874]: Yes, I was trying to make this consistent with the old behavior.

`mooseError("Failed to get real path for ", path);` is there for a while. 


`mooseRealpath` is used for beyond `input_file_name`

Comment (fdkong) [reply framework/src/utils/MooseUtils.C:874]: Or we could simply say:

` mooseError(path, "not found");` 

@dschwen @aeslaughter have any suggestions?

Comment (gambka) [reply framework/src/utils/MooseUtils.C:874]: That sounds good to me. By doing that it should give the full path to the file. I guess I'm just concerned why include real path? What purpose does real serve here? Is there a fake or imaginary path?

Comment (fdkong) [reply framework/src/utils/MooseUtils.C:874]: It is used to remove symbolic links  

https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Sys/PetscGetRealPath.html

File: framework/include/utils/MooseUtils.h [hunk 2]
```diff
@@ -756,7 +756,7 @@ linearPartitionChunk(dof_id_type num_items, dof_id_type num_chunks, dof_id_type
 /**
  * Wrapper around PetscGetRealPath, which is a cross-platform replacement for realpath
  */
-std::string realpath(const std::string & path);
+std::string mooseRealpath(const std::string & path);
```
Comment (lindsayad) [inline framework/include/utils/MooseUtils.h:759]: Is this not wrapped in a namespace?

Comment (lindsayad) [reply framework/include/utils/MooseUtils.h:759]: Looks like it is (`MooseUtils`)...so why we do we have to change the name?

File: framework/src/utils/MooseUtils.C [hunk 3]
```diff
@@ -858,12 +858,24 @@ fileSize(const std::string & filename)
...
   char dummy[PETSC_MAX_PATH_LEN];
+#if defined(PETSC_HAVE_REALPATH)
+  // If "realpath" is adopted by PETSc and
+  // "path" does not exist, then PETSc will print a misleading message.
+  // [0]PETSC ERROR: Error in external library
+  // [0]PETSC ERROR: realpath()
+  // [0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
+  // [0]PETSC ERROR: Petsc Release Version 3.13.3, unknown
+  // We here override the misleading message with a better one.
+  if (!realpath(path.c_str(), dummy))
```
Comment (lindsayad) [inline framework/src/utils/MooseUtils.C:873]: I'm guessing you changed the name so that there's not confusion here about where realpath is coming from? If you want it to be clear that it is not coming from the `MooseUtils` namespace, then you could do `::realpath` here to denote that this is coming from the global namespace.

**Review by lindsayad — CHANGES_REQUESTED** [review]
I would prefer to keep `MooseUtils::realpath` since one of the primary reasons of namespaces in C++ is to make it clear where a symbol is coming from.

File: framework/src/utils/MooseUtils.C (hunk 3 above)
Comment (fdkong) [reply framework/src/utils/MooseUtils.C:873]: Right.  `realpath` is a system function. Sometimes, compiler complains  about this. Let me change it to `::realpath`

File: framework/src/utils/MooseUtils.C (hunk 1 above)
Comment (fdkong) [reply framework/src/utils/MooseUtils.C:874]: OK, I see. the original message actually makes sense since `path` could be a symbolic link . 

I will have to keep as-is

**Comment by fdkong** [comment]
It is ready for review or merge @lindsayad

**Review by lindsayad — APPROVED** [review]
