### PR TITLE
Fixing doco string for --mesh-only command

### LINKED ISSUE #10268: Fix doco on --mesh-only command
## Rationale

The `--help` command to MOOSE fails to print out the fact that `--mesh-only` takes an optional filename. This can cause multiple issues. First, if you put command line arguments after that command, the argument parser will interpret the first one as a filename possibly causing an odd failure. If you happen to supply a filename override it could clobber the file or print odd "can't output to that file type" messages.

## Description

```
./moose_test-opt -i foo.i --mesh-only Mesh/file=some_abaqus_file.inp
```

## Impact

No impact on calculations, but may impact usability and helpful error messages.

### PR DESCRIPTION
**Pull request by permcody**
closes #10268

### CODE REVIEW

**Review by brianmoose — COMMENTED** [review]
Also, not related to this PR, but running
`./moose_test-opt --mesh-only` by itself
results in a core dump.

File: framework/src/base/MooseApp.C [hunk 1]
```diff
@@ -65,7 +65,9 @@ validParams<MooseApp>()
       "display_version", "-v --version", false, "Print application version");
   params.addCommandLineParam<std::string>("input_file", "-i <input_file>", "Specify an input file");
   params.addCommandLineParam<std::string>(
-      "mesh_only", "--mesh-only", "Setup and Output the input mesh only.");
+      "mesh_only",
+      "--mesh-only [mesh_file_name]",
+      "Setup and Output the input mesh only (Default: \"input_file_in.e\")");
```
Comment (brianmoose) [inline framework/src/base/MooseApp.C]: How about `<input_file_base>_in.e`?

Comment (permcody) [reply framework/src/base/MooseApp.C]: Hmm, ok my default isn't quite good enough, but "input_file_base" doesn't seem quite right. I might change it a little. Let me see if the core dump can be fixed easily.

**Review by brianmoose — APPROVED** [review]
