### PR TITLE
Remove null object call in ADComputeMultipleInelasticStress

### LINKED ISSUE #20722: Call on null object in ADComputeMultipleInelasticStress
## Bug Description
```c++
  if (isParamValid("damage_model") && !_damage_model)
    paramError("damage_model",
               "Damage Model " + _damage_model->name() +
                   " is not compatible with ADComputeMultipleInelasticStress");
```

## Steps to Reproduce
I'm not entirely sure because I'm a tensor mechanics noob

## Impact
Causes segmentation faults for users as opposed to what the writer of this code intended which was a nice, thoughtful parameter error.

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #20722

I could use some help getting a test for this error

### CODE REVIEW

File: modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C [hunk 1]
```diff
@@ -127,7 +127,7 @@ ADComputeMultipleInelasticStress::initialSetup()
 
   if (isParamValid("damage_model") && !_damage_model)
     paramError("damage_model",
-               "Damage Model " + _damage_model->name() +
```
Comment (hugary1995) [inline modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:130]: You mean _damage_model could be nullptr here?

Comment (hugary1995) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:130]: Oh no what am I saying...

Comment (hugary1995) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:130]: You can say `damage_model = some_material` in the input file and `some_material` cannot be cast to `DamageBase`.

Comment (hugary1995) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:130]: For example, change https://github.com/idaholab/moose/blob/2270e3210b1f7151cf7dde712331bbdf64baf868/modules/tensor_mechanics/test/tests/scalar_material_damage/ad_scalar_material_damage.i#L97
to `damage_model = damage_index`, and since damage_index cannot be cast to DamageBase, it should go down this branch.

Comment (lindsayad) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:130]: thanks @hugary1995 for the inspiration!

**Review by recuero — DISMISSED** [review]

**Review by recuero — APPROVED** [review]

**Comment by tophmatthews** [comment]
Shouldn't this be updated in the non-AD version too?

**Comment by lindsayad** [comment]
Definitely want to avoid making calls on null objects if that's happening elsewhere as well
