### PR TITLE
Always register thermochimica objects 

### LINKED ISSUE #23016: Register Thermochimica objects to avoid doc build failures
## Reason
Thermochimica docs fail the doc test if the corresponding objects are not registered (which they are only if the submodule is initialized).

## Design
Register the non-functioning objects anyways (yeah, it's not an ideal solution, but the only option right now). Throw an error in the constructor and indicate that the objects require the thermochimica submodule to be functioning in the object description.

## Impact
Unbreak app tests. @rpodgorney

### PR DESCRIPTION
**Pull request by dschwen**
Closes #23016

This PR is brought to you in part by ChatGPT:
image

### CODE REVIEW

**Comment by rpodgorney** [comment]
thanks @dschwen 

@loganharbour can you review when the checks complete?  I’d like to get Wencheng’s PR thru before everyone goes so I can do so doco updates over the break

**Comment by GiudGiud** [comment]
AI-informed coding wow

**Review by GiudGiud — APPROVED** [review]
I think this is good practice for external optional contribs.

Should we do the same for Saline?

**Review by loganharbour — CHANGES_REQUESTED** [review]
Not done with my review, @GiudGiud hijack

File: modules/chemical_reactions/include/utils/ThermochimicaUtils.h [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+#pragma once
+
+class InputParameters;
+class MooseObject;
+class Action;
+
+#include <string>
+
+namespace ThermochimicaUtils
```
Comment (GiudGiud) [inline modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: should this be a framework-wide thing to handle external contribs that may or may not be compiled in

**Review by rpodgorney — APPROVED** [review]
Approving only to keep things moving.  Relying on @loganharbour and @GiudGiud for detailed review.

I thought ChemicalReactions was depreciated.........didn't realize it was being used.

File: modules/chemical_reactions/include/utils/ThermochimicaUtils.h (hunk 1 above)
Comment (dschwen) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: Hm, I don't see how this could be generalized yet. And a central file in framework for optional contribs that are on modules seems more confusing than helpful to me.

Comment (GiudGiud) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: OptionalContribInterface base class for all objects tied to an external contrib
keeps these 3 routines. They would need to be re-implemented a bit to not rely on pre-processing. 

but you could keep track of the optional contrib name in the interface too

Comment (dschwen) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: "Not to rely on preprocessing"... gee, that would make things a lot more complicated, and we would have to rely on preprocessing anyways in the actual objects that depend on the optional contribs. Please keep in mind that the primary goal of this PR is to unbreak Falcon so that documentation can be merged in _before the holiday curtailment_.

Comment (loganharbour) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: > Please keep in mind that the primary goal of this PR is to unbreak Falcon so that documentation can be merged in before the holiday curtailment.

If that’s the goal… we just checkout the submodule…

Comment (dschwen) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: So what changes are requested?

Comment (GiudGiud) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: I m suggesting ideas if we dont want to have to replicate everything for Saline

Comment (GiudGiud) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: not really requesting anything right now, more like discussing

Comment (dschwen) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: > If that’s the goal… we just checkout the submodule…

I'd say this PR is superior to that approach as it fixes doc building for local users, too.

Comment (dschwen) [reply modules/chemical_reactions/include/utils/ThermochimicaUtils.h:18]: Anyways after some thinking I just don't see a way to do this without the preprocessor.

**Review by loganharbour — APPROVED** [review]
I have one another idea... maybe we could achieve this with a class that derives from `InputParameters` in order to generalize it. We would instantiate via copy constructor in `validParams()`.

I'm okay with this if you don't think the above is a good idea. Regardless, we can generalize later as needed. 

I think it would still be a good idea to figure out how to get documentation working without actually needing to _compile_ the objects... but that's another future task.

**Comment by GiudGiud** [comment]
More details on this, just my current understanding of the issue.
The registering of objects in the documentation is done with a regex on the register(MooseApp, object) routine. This certainly triggers here, we don't check for pre-processing flags in that regex. 

The object is registered for documentation, but the object and its parameters are not added to the dump because the object is (was after this) not registered. 

When the documentation page is parsed (this is always there, whether the submodule is checked out or not), the /Type/Objectname/parameters syntax requests the parameters

So alternative fixes:
- dont parse the .md thermochimica-related doco pages when the submodule is not checked out (needs a mechanism for that, I dont think we have anything yet, could be some sort of page tagging)
- add an `optional = true` to the /Type/Objectname/parameters syntax in the .md files

@rks171 I'm sorry we haven't communicated well on this, i m waiting on this being resolved before moving further with Saline

**Comment by dschwen** [comment]
> but that's another future task

Yeah, agree. The doc system does not have easy access to preprocessor symbols though.

I'd also caution against over-engineering this issue. This current solution is not "inelegant" in my opinion. Either way, this is not something we _need_ to commit to right now, and any change to this in the future will not break any API the users are relying on (in that light it would have been cool if this PR could have been merged before the break to at least give Rob some relief...).

**Comment by GiudGiud** [comment]
The apps were fixed before the break btw, by checking out the submodule, we can thank Logan for the emergency fix
