### PR TITLE
Don't apply ics when restarting unless explicitly requested

### LINKED ISSUE #24144: NavierStokesFV requires initialize_variables_from_mesh_file=true to properly restart from checkpoint
## Bug Description

NavierStokesFV requires `initialize_variables_from_mesh_file=true` to properly restart from checkpoint but the docstring for that parameter mentions that it is only for Exodus format.

In addition, the user may not be aware of that parameter so it would be best to set that parameter automatically to true when restart is detected.

## Steps to Reproduce

See [here](https://github.com/idaholab/moose/compare/next...vincentlaboure:moose:nv_cp_restart) to reproduce.

## Impact

At a minimum, this is not user friendly. 

Tag @lindsayad

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #24144 

@vincentlaboure

### CODE REVIEW

**Comment by vincentlaboure** [comment]
Looks good to me, thanks @lindsayad !

**Comment by lindsayad** [comment]
Thanks for preparing a branch with such a nice MWE!

File: modules/navier_stokes/src/actions/NSFVAction.C [hunk 1]
```diff
@@ -985,13 +985,13 @@ void
...
   // do not set initial conditions if we load from file
-  if (getParam<bool>("initialize_variables_from_mesh_file"))
+  if (_app.isRestarting() || getParam<bool>("initialize_variables_from_mesh_file"))
     return;
 
   InputParameters params = _factory.getValidParams("FunctionIC");
   auto vvalue = getParam<std::vector<FunctionName>>("initial_velocity");
 
-  if (_create_velocity)
+  if (_create_velocity && (!_app.isRestarting() || _pars.isParamSetByUser("initial_velocity")))
```
Comment (GiudGiud) [inline modules/navier_stokes/src/actions/NSFVAction.C:994]: we ve already returned if app.isRestarting

I dont think this is needed

Comment (GiudGiud) [reply modules/navier_stokes/src/actions/NSFVAction.C:994]: also if we create out own velocity, we need an IC, whether the user has specified one or not, because otherwise we get a divergence with any advected scalar

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: modules/navier_stokes/src/actions/NSFVAction.C (hunk 1 above)
Comment (lindsayad) [reply modules/navier_stokes/src/actions/NSFVAction.C:994]: > we ve already returned if app.isRestarting

Oops that is a mistake. I need to remove the early return. Did you look at this condition closely? It says add an IC if you're not restarting or if the user has specifically requested an initial condition. You seem concerned about the former case and we will indeed add an IC, regardless of user specification, if we are not restarting. If we *are* restarting, then just like we do for non-actions, this line allows the user to override the solution vectors in the restart with an initial condition.

Comment (GiudGiud) [reply modules/navier_stokes/src/actions/NSFVAction.C:994]: ok nevermind this second comment. I guess my brain is fried from Transfers all day

Comment (GiudGiud) [reply modules/navier_stokes/src/actions/NSFVAction.C:994]: or maybe I was conceptualizing a different fix that you did. anyhow

**Review by GiudGiud — DISMISSED** [review]

**Comment by lindsayad** [comment]
I had to re-push to re-trigger CIVET testing

**Review by GiudGiud — APPROVED** [review]
