### PR TITLE
Scalar scaling fix

### LINKED ISSUE #9450: Avoid redundant computation of scalar kernel residual components
### Description of the enhancement or error report

NonlinearSystemBase appears to call computeResidual() or computeJacobian() on all ScalarKernel objects on all processors, then accumulates the results with addResidualScalar() or addJacobianScalar() on all processors.  The redundant computation and assembly should be eliminated.

### Rationale for the enhancement or information for reproducing the error

Eliminating an assembly operation with O(N_procs) cost (because the processor which owns those residual entries + matrix rows will need to receive communication from every other processor) should improve scalability for problems with SCALAR variables.

Fixing this properly should simultaneously allow me to improve the dubious code at https://github.com/idaholab/moose/blob/devel/framework/src/base/MooseVariableScalar.C#L65-L76 which allows SCALAR dof values to end up uninitialized (well, 0).  The flaw there is unlikely to be a problem in most codes (where SCALAR dofs are semilocal and thus initialized on every single processor), but I've managed to trigger it in corner cases (where N_proc > N_elem + 1), and I can imagine real cases (where users have restricted coupling with SCALAR variables to only subdomains which are strict subsets of the whole mesh) where this could lead to incorrect results.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

My current plan is to examine each scalar kernel's variable dof_indices, then compute and assemble residual/jacobian values only on processors for which at least one DoF index is local.  I'm testing that now and should have a cleaned up PR tomorrow.

One design decision which will have to be made in the PR: when we reinit a MooseVariableScalar and we discover that it lacks semilocal data on the current processor, what do we do *instead* of letting the corresponding array values remain 0 or uninitialized?  We can't just throw an error right away, because user code may want to reinit() without expecting to test those values (for example, to test if their indices are local, as I'm doing).  If we truncate the arrays then future access screams and dies in dbg mode on libstdc++, but that seems too dangerous for other configurations.  I'm leaning toward "fill them with NaNs", which is a bit hard to debug but which at least prevents misusage from being mistaken for a correct result.  Alternatively I could test _GLIBCXX_DEBUG and truncate arrays if it's in use or fill with NaNs if not.

Copying @friedmud and @permcody since I'm moving my discussion with them from Gitter to here, and @andrsd at Cody's suggestion.

### PR DESCRIPTION
**Pull request by roystgnr**
I believe this should fix #9450 if my understanding of the problem is correct.

The second commit here trips _GLIBCXX_DEBUG assertion failures on the perverse N_proc > N_elem + 1 case, verifying an attempt to access uninitialized data, and the third commit fixes that failure, so there's at least a little justification for my belief.

We should change that second commit to be more robust (NaNs in opt mode?) before merging this, but I'll wait for a bit of discussion on exactly how we should do so; for now I just want to make sure that Civet doesn't think I've broken anything else.

### CODE REVIEW

**Comment by roystgnr** [comment]
1e-5 absolute error is kind of borderline; too small to be sure it's a bug, too big to ignore unless we can be sure it's not a solver tolerance issue.  I'll look into it.

**Comment by roystgnr** [comment]
Do we have an "App tests debug" test that we can manually run?  That _GLIBCXX_DEBUG trick caught a corner-case bug in the ScalarVariable postprocessor, and it would be nice to ensure that there aren't any similar problems in user code.

**Comment by roystgnr** [comment]
I can replicate the generalized_plane_strain_tm_contact.generalized_plane_strain_tm_contact bug, BTW, but I don't yet understand it.  I've ruled out "test is running with too low a solver tolerance", and I hope to soon confirm or deny "gold standard was generated with too low a solver tolerance", but if neither theory is correct I've got no leads.

**Comment by permcody** [comment]
I'm not entirely sure that your change is necessarily a bug. We've tripped these tests several times over the last few years with diffs that look like yours. Sometimes it's just the differences in the way we calculate things that cause these issues. Many of these tests are very sensitive. Rather than you continuing to look for the reason perhaps we could tackle it from the other end (i.e. involve one of the test builders to look at the new solutions to see if they still look reasonable). I'm happy to tag someone...

**Comment by roystgnr** [comment]
Yeah, I'd appreciate it.  I don't get any other regression test failures (after I rooted out a weird MKL red herring), but I'm not understanding this one.  The diffs are around 1e-5, in a field whose peak solution is around 2e3, so I'd normally laugh and chalk that up to solver tolerance, but futzing with tolerances hasn't fixed anything for me, and I'm loathe to just crank up a huge abs tolerance floor on a test case I'm unfamiliar with.

**Comment by permcody** [comment]
@bwspenc, or @hchen139 maybe one of you can shed some light on this test. Looking at the history it looks like it has given us fits before. The L2 norm of the residual of some of the timesteps is 1e-5-1e-6 so I'm surprised it doesn't diff more often. I really don't want Roy to try to figure out why his change is only breaking one or two of these very sensitive test when the rest of the suite passes.

**Comment by permcody** [comment]
@fdkong - previously skipped this test: https://github.com/idaholab/moose/commit/c88bc1a6ffeca97ae6785b5eb9463c98e5acbc47

**Comment by permcody** [comment]
@bwspenc and @hchen139 - Can one of you take a look at the test results here and see if you think these diffs are significant. You can read the comments above and the original issue but we are stuck trying to figure out if we've broken something here. Unless you are completely sure about the results in this test, it might actually be a fix. Any help would be appreciated, we'd like to get his patch in.

**Comment by bwspenc** [comment]
@hchen139 is looking into this.  I doubt this is a problem with the code.  It looks like the test is just a little too sensitive to small numerical issues.  We'll plan on just submitting a separate PR to improve the test, unless we hear otherwise.

**Comment by roystgnr** [comment]
We should kick those tests to see if they work now that #9531 is in.

I've got to handle those robustness issues, too, so I'll do that shortly and we can just wait for that push to trigger new tests.

**Comment by roystgnr** [comment]
Ah, hell.  I just rebased on master rather than devel, didn't I...

**Comment by roystgnr** [comment]
That should fix it.  If this passes tests now then IMHO it's good to go.

**Comment by roystgnr** [comment]
Oh, come on!  My formatting looks better before the demanded patch.

File: framework/src/postprocessors/ScalarVariable.C [hunk 1]
```diff
@@ -18,6 +18,9 @@
 #include "MooseVariableScalar.h"
 #include "SubProblem.h"
 
+// libMesh includes
```
Comment (andrsd) [inline framework/src/postprocessors/ScalarVariable.C]: cpt. Obvious.

File: framework/src/postprocessors/ScalarVariable.C [hunk 2]
```diff
@@ -49,5 +52,14 @@ Real
...
   _var.reinit();
-  return _var.sln()[_idx];
+
+  Real returnval = std::numeric_limits<Real>::max();
+  const DofMap & dof_map = _var.dofMap();
+  const dof_id_type dof = _var.dofIndices()[_idx];
+  if (dof >= dof_map.first_dof() && dof < dof_map.end_dof())
+    returnval = _var.sln()[_idx];
+
+  this->comm().min(returnval);
```
Comment (andrsd) [inline framework/src/postprocessors/ScalarVariable.C]: use `gatherMin(...)`

File: framework/src/base/MooseVariableScalar.C [hunk 3]
```diff
@@ -23,6 +23,9 @@
 #include "libmesh/numeric_vector.h"
 #include "libmesh/dof_map.h"
 
+// C++
```
Comment (andrsd) [inline framework/src/base/MooseVariableScalar.C]: Remove this line, it is cpt. Obvious.

**Review by andrsd — CHANGES_REQUESTED** [review]

File: framework/src/postprocessors/ScalarVariable.C (hunk 2 above)
Comment (roystgnr) [inline framework/src/postprocessors/ScalarVariable.C]: Will do.

File: framework/src/base/MooseVariableScalar.C (hunk 3 above)
Comment (roystgnr) [inline framework/src/base/MooseVariableScalar.C]:
```
roystgnr@leela:(roys_junk3) ~/git/moose-fresh
$ egrep -i '// (system|C\+\+)' framework/include/*/*.h | wc
     35     118    2112
roystgnr@leela:(roys_junk3) ~/git/moose-fresh
$ egrep -i '// libMesh includes' framework/include/*/*.h | wc
     70     210    4668
```

Should I get the other hundred instances while I'm at it?  That should probably be a separate PR.

I'd rather not remove any of them at all.  When I was removing unnecessary header dependencies, I discovered that dependency-tracking best practices (e.g. https://stackoverflow.com/a/2762596 ) were followed less often than not.  I'd like to have *some* comments that express "This isn't random order; someone put these headers below those headers for a reason, and here's what category they were sorted by".

**Comment by roystgnr** [comment]
Looks like we're still seeing exodiffs on the same test, even after #9531 cranked down the solver tolerance?  I'll see if I can still replicate.

**Comment by bwspenc** [comment]
@roystgnr Maybe we need to also loosen up the exodiff tolerances a bit on that test.  I'll look at the results after this round of tests runs.

File: framework/src/base/MooseVariableScalar.C (hunk 3 above)
Comment (andrsd) [inline framework/src/base/MooseVariableScalar.C]: I understand that grouping header files is a good thing, but I also think people already do that. That's why I think we do not need comments like "Put C++/libmesh headers here"...

Comment (roystgnr) [inline framework/src/base/MooseVariableScalar.C]: I still disagree, but I'd rather get this merged than argue, so I'll push one more commit stripping those two comments just as soon as these retests finish.

That said,
```
roystgnr@zappa:(scalar_scaling_fix) ~/git/moose/modules
$ git blame ../framework/src/base/MooseVariableScalar.C | tail -n +22 | head -n 5
e4501c55 (David Andrs       2012-02-06 08:48:49 +0000  22) // libMesh
ff8a0bdc (Cody Permann      2013-02-07 12:33:07 +0000  23) #include "libmesh/numeric_vector.h"
02f63040 (John W. Peterson  2015-11-03 10:18:43 -0700  24) #include "libmesh/dof_map.h"
e4501c55 (David Andrs       2012-02-06 08:48:49 +0000  25) 
b99fd8ac (Roy H. Stogner    2017-07-05 17:16:21 -0500  26) // C++
```

https://en.wikipedia.org/wiki/I_learned_it_by_watching_you!   ;-)

Comment (andrsd) [inline framework/src/base/MooseVariableScalar.C]: Well, originally the code looked like this:
```
// libMesh
#include "numeric_vector.h"
#include "dof_map.h"
```
Then, you guys in libmesh added "libmesh/", see `git show ff8a0bdc` for the change. At that point we should have dropped `// libMesh` comments, but they stayed. I really do think they are cpt. Obvious.  With the same logic, I do not think we need `// C++`

**Comment by roystgnr** [comment]
Tests passed, so this should be good to merge.  That last commit was just comment deletions.

**Review by andrsd — APPROVED** [review]
