### PR TITLE
Fixes in LinearViscoelasticityBase

### LINKED ISSUE #10078: Internal variables in LinearViscoelasticityBase have incorrect size in some cases
## Rationale
The size of _spring_elasticity_tensors in LinearViscoelasticityBase is too large when _has_longterm_dashpot is true (in that case, there is one more dashpot than springs, so the size of _spring_elasticity_tensors is off by 1). This costs unnecessary memory and may lead to errors in Materials deriving from LinearViscoelasticityBase. 

## Description
Two types of errors can be encountered:
- Mathematical errors: the solve succeeds, but the results are not the expected results. This error happens in the visco/burgers_creep.i test (the strain differs from the analytical solution).
- Inversion of zero fourth-order tensor when LinearViscoelasticityBase::computeQpViscoelasticPropertiesInv() is directly called. This error does not occur in the current tensor_mechanics version, but may happen for classes deriving from LinearViscoelasticityBase.

## Impact
Internal code change in LinearViscoelasticityBase.C. The test visco/burgers_creep.i needs to be regolded. No modification of input files.

### PR DESCRIPTION
**Pull request by agiorla**
Provide several fixes for LinearViscoelasticityBase class
- The size of _spring_elasticity_tensors is now correct when _has_longterm_dashpot is true.
- The default computation of _spring_elasticity_tensors_inv checks for the validity of the tensor before inverting it.
- The test burgers_creep.i has been regolded
- GeneralizedMaxwellModel and GeneralizedKelvinVoigtModel now issue the isotropic guarantee (this allows their use with SmearedCracking models)

Closes #10078

### CODE REVIEW

**Comment by agiorla** [comment]
Ping @bwspenc

**Comment by bwspenc** [comment]
@fdkong FYI, the three failures in the modules tests are all due to contact tests failing with the SuperLU bug with PETSc 3.7.6 on Intel.

File: modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C [hunk 1]
```diff
@@ -71,6 +71,8 @@ GeneralizedMaxwellModel::GeneralizedMaxwellModel(const InputParameters & paramet
 
   _components = _eta_i.size();
   _has_longterm_dashpot = (_eta_i.size() == _Ci.size() + 1);
+
+  issueGuarantee(_elasticity_tensor_name, Guarantee::ISOTROPIC);
```
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C]: Would it be better to do this in a base class?  I'm OK either way -- just asking.  Maybe in general it's possible to have an anisotropic version of one of these models, in which case it makes the most sense here.

**Review by bwspenc — APPROVED** [review]
We can't merge this until we resolve the problem with those failing tests (which are unrelated to this code), but this all looks good.

File: modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C (hunk 1 above)
Comment (agiorla) [reply modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C]: We can have, in theory, an anisotropic version of these models. I'm not sure anyone would use that in practice, so we could force the guarantee in the base class, and let derived classes revoke that guarantee on a case-by-case basis?

Comment (bwspenc) [reply modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C]: I'd say let's just keep it as you have it and guarantee that at the derived class level then.

Comment (agiorla) [reply modules/tensor_mechanics/src/materials/GeneralizedMaxwellModel.C]: Works for me! Actually, it's probably wiser to not guarantee something in the base class, to avoid guaranteeing something to be isotropic when it is not...
