### PR TITLE
Made ElementDeletionGeneratorBase delete elems that have already deleted elems as an interior parent

### LINKED ISSUE #21983: BlockDeletionGenerator produces segmentation fault with mixed-dimensional meshes
## Bug Description

BlockDeletionGenerator segfaults with mixed-dimensional meshes

## Steps to Reproduce

```
[Mesh]
  [twoquad]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 2
    xmax = 2
  []
  [subdomain]
    type = SubdomainBoundingBoxGenerator
    input = twoquad
    block_id = 1
    bottom_left = '1 0 0'
    top_right = '2 1 0'
  []
  [sideset]
    type = SideSetsBetweenSubdomainsGenerator
    input = subdomain
    primary_block = 0
    paired_block = 1
    new_boundary = bar
  []
  [edge_elem]
    type = LowerDBlockFromSidesetGenerator
    input = sideset
    sidesets = bar
    new_block_id = 2
  []
  [delete]
    type = BlockDeletionGenerator
    input = edge_elem
    block = 0
  []
[]
```

## Impact

I have a work-around, but would still like this bug to be fixed.  **I do not currently have time to fix this myself**

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #21983

### CODE REVIEW

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C [hunk 1]
```diff
@@ -226,6 +235,7 @@ ElementDeletionGeneratorBase::generate()
    * For now, we'll call contract and notify the SetupMeshComplete
    * Action that we need to re-prepare the mesh.
    */
+
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementDeletionGeneratorBase.C:238]:
```suggestion
```

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C [hunk 2]
```diff
@@ -52,6 +52,15 @@ ElementDeletionGeneratorBase::generate()
       deleteable_elems.insert(elem);
   }
 
+  // Set to be merged into deleteable elems, used to avoid derefencing a dangling pointer
+  std::set<Elem *> deleteable_parents;
+
+  // check for dangling interior parents
+  for (auto & elem : mesh->element_ptr_range())
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementDeletionGeneratorBase.C:59]: this is costing you another loop on all the mesh

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C [hunk 3]
```diff
@@ -52,6 +52,15 @@ ElementDeletionGeneratorBase::generate()
       deleteable_elems.insert(elem);
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementDeletionGeneratorBase.C:52]: when you could just loop over the child of the element here

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C (hunk 3 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/ElementDeletionGeneratorBase.C:52]: well it s not that simple

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C (hunk 2 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/ElementDeletionGeneratorBase.C:59]: ok so check the element dimension before doing a search. this will reduce the complexity from:
N_mesh * N_elem_deleted to
N_lower-d-mesh * N_elem_deleted

and that should be enough

File: test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i [hunk 4]
```diff
@@ -0,0 +1,72 @@
+[Mesh]
+  [twoquad]
+    type = GeneratedMeshGenerator
+    dim = 2
+    nx = 2
+    xmax = 2
```
Comment (GiudGiud) [inline test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:6]:
```suggestion
    dim = 2
    nx = 3
    ny = 4
    xmax = 2
```
to make sure we hit more cases

Comment (GiudGiud) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:6]: a 2x2 boundary does not have a fully interior element

File: test/tests/meshgenerators/block_deletion_generator/tests [hunk 5]
```diff
@@ -33,6 +33,13 @@
       recover = false
       detail = 'blocks and assigning the new boundary even if the input mesh is not prepared.'
     []
+    [delete_interior_parents]
+      type = 'RunApp'
```
Comment (GiudGiud) [inline test/tests/meshgenerators/block_deletion_generator/tests:37]: this should be an exodiff.
We need to make sure we get the right result out of this

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C [hunk 6]
```diff
@@ -52,6 +52,16 @@ ElementDeletionGeneratorBase::generate()
...
+  // Set to be merged into deleteable elems, used to avoid derefencing a dangling pointer
+  std::set<Elem *> deleteable_parents;
+
+  // check for dangling interior parents
+  for (auto & elem : mesh->element_ptr_range())
+    if (elem->dim() == mesh->mesh_dimension() - 1 &&
+        deleteable_elems.count(elem->interior_parent()) > 0)
+      deleteable_parents.insert(elem);
+
+  deleteable_elems.insert(deleteable_parents.begin(), deleteable_parents.end());
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementDeletionGeneratorBase.C:64]: why cant you insert in deleteable elements?

also isnt it deleteable_child rather than parents here?

File: test/tests/meshgenerators/block_deletion_generator/tests [hunk 7]
```diff
@@ -33,6 +33,13 @@
       recover = false
       detail = 'blocks and assigning the new boundary even if the input mesh is not prepared.'
     []
+    [delete_interior_parents]
+      type = 'Exodiff'
+      input = 'delete_interior_parents.i'
+      exodiff = 'delete_interior_parents_out.e'
+      recover = false
+      detail = 'blocks and properly removing elements with a deleted element as their interior parent.'
```
Comment (GiudGiud) [inline test/tests/meshgenerators/block_deletion_generator/tests:41]:
```suggestion
      detail = 'blocks and properly removing lower dimensional elements with a deleted element as their interior parent.'
```

File: test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+    primary_block = 0
+    paired_block = 1
+    new_boundary = bar
+  []
+  [edge_elem]
+    type = LowerDBlockFromSidesetGenerator
+    input = sideset
+    sidesets = bar
+    new_block_id = 2
+  []
```
Comment (GiudGiud) [inline test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: duplicate those please with foo for the sideset from 1 to 0 ((instead of 0 to 1)

I want to see if those lowerD elements survive as expected

**Review by GiudGiud — CHANGES_REQUESTED** [review]
Add a note in the documentation about this
For example

!alert note
Lower-dimensional elements created from the deleted elements will also be removed

**Comment by socratesgorilla** [comment]
Alert note is in there

File: framework/src/meshgenerators/ElementDeletionGeneratorBase.C [hunk 9]
```diff
@@ -52,10 +52,15 @@ ElementDeletionGeneratorBase::generate()
...
-   */
+  // check for dangling interior parents
+  for (auto & elem : mesh->element_ptr_range())
+    if (elem->dim() == mesh->mesh_dimension() - 1 &&
+        deleteable_elems.count(elem->interior_parent()) > 0)
+      deleteable_elems.insert(elem);
+      /**
+       * If we are in parallel we'd better have a consistent idea of what
+       * should be deleted.  This can't be checked cheaply.
+       */
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementDeletionGeneratorBase.C:63]:
```suggestion
  /**
   * If we are in parallel we'd better have a consistent idea of what
   * should be deleted.  This can't be checked cheaply.
   */
```

**Comment by GiudGiud** [comment]
clean up the commit history

we dont want a merge commit

**Comment by GiudGiud** [comment]
what you can do is an interactive rebase, remove the merge and squash the unimportant ones

File: test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+    type = LowerDBlockFromSidesetGenerator
+    input = sideset2
+    sidesets = bar
+    new_block_id = 2
+  []
+  [delete2]
+    type = BlockDeletionGenerator
+    input = edge_elem2
+    block = 0
+  []
```
Comment (socratesgorilla) [inline test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:34]:
```suggestion
```

**Comment by socratesgorilla** [comment]
I don't even know how that merge commit got in there, it shouldn't be. I don't remember merging.

**Review by GiudGiud — APPROVED** [review]

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i [hunk 11]
```diff
@@ -0,0 +1,90 @@
...
+    input = subdomain
+    primary_block = 1
+    paired_block = 0
+    new_boundary = bar
+  []
+  [edge_elem2]
+    type = LowerDBlockFromSidesetGenerator
+    input = sideset2
+    sidesets = bar
+    new_block_id = 2
```
[the remark this answers is not in the document]
Comment (socratesgorilla) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: Well, the lowerD block is, to the block_deletion_generator, just another block, the fact that someone made a new block with a new block id using the LowerDBlock generator shouldn't have any bearing. It doesn't make any sense that it wouldn't be able to delete the block, the selection of block is essentially arbitrary.

As long as it properly discerns between the right elements, there shouldn't be an issue, right? As far as I know that's what is happening.

[the remark this answers is not in the document]
Comment (GiudGiud) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: Let's say we have 
block 1, 2 higher D blocks
block 3 tied to elements in block 1, lower D, on sideset 1 between 1 & 2
block 4 tied to elements in block 2, lower D, on sideset 2 between 2 & 1

I d want the BlockDeletionGenerator to be able to:
- delete block 3 when deleting block 1 (this might be controversial actually)
- delete block 4 when deleting block 2 (same)
- delete block 3 or 4 only

[the remark this answers is not in the document]
Comment (socratesgorilla) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: Do you want me to test for that behavior?

[the remark this answers is not in the document]
Comment (GiudGiud) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: I d like the test that deletes block 1 & 3 also contain block 4 and does not delete it.

You are pretty much there, you just need to get the MGs set up properly and fix the block ids created I think

[the remark this answers is not in the document]
Comment (WilkAndy) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: As far as i'm concerned, the most important thing is to properly document this (eg, with examples, similar to @GiudGiud 's above).  BUT, if i had my choice, i would not want to always delete block 3 when deleting block 1.  I don't see why you'd always want to do that, and in my situation you'd almost always want to not delete block 3.  I'd prefer to specify block = '1 3' if i wanted to delete both blocks.   But, as i said, the documentation is more important than the final functionality.

[the remark this answers is not in the document]
Comment (GiudGiud) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:28]: The problem is that:
- if you specify '1 3' you already delete both blocks currently
- if you only specify 1, it seg faults because of elements missing their interior parent.
I agree documenting the behavior is important here

[the remark this answers is not in the document]
Comment (socratesgorilla) [reply test/tests/meshgenerators/block_deletion_generator/delete_interior_parents.i:27]: Newest push deletes block 1 and 3 and doesnt delete block 4.

**Review by GiudGiud — APPROVED** [review]
This looks good.
If users want to leave the lower-D elements in the future they ll just add a boolean and some more logic to fix the interior parents pointers.

Thanks for the fix!
