### PR TITLE
Only instantiate a single MFEM device

### LINKED ISSUE #31037: `HYPRE_Finalize` called multiple times in MFEM multiapp sim
### Bug Description

`HYPRE_Finalize` is called every time a `Device` is constructed and every `MFEMExecutioner` owns a `Device` instance. When an `MFEMExecutioner` is destructed before classes owning matrices, `HYPRE_Initialize` will actually be called again as shown in the backtrace below
```
#0  HYPRE_Initialize () at /data/lindad/projects/gpu-moose-dbg/petsc/arch-moose/externalpackages/git.hypre/src/utilities/general.c:409
#1  0x00007fffd08f0ba6 in hypre_handle () at /data/lindad/projects/gpu-moose-dbg/petsc/arch-moose/externalpackages/git.hypre/src/utilities/general.c:24
#2  0x00007fffd08f1724 in HYPRE_GetMemoryLocation (memory_location=0x7fffffffcce4) at /data/lindad/projects/gpu-moose-dbg/petsc/arch-moose/externalpackages/git.hypre/src/utilities/general.c:540
#3  0x00007ffff3f4b9f4 in mfem::GetHypreMemoryLocation () at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/installed/include/mfem/general/mem_manager.hpp:900
#4  0x00007ffff3f4ba1a in mfem::HypreUsingGPU () at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/installed/include/mfem/general/mem_manager.hpp:913
#5  0x00007fffe58b67b5 in mfem::HypreParMatrix::Destroy (this=0x555556bad120) at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/linalg/hypre.cpp:2848
#6  0x00007fffe57f1896 in mfem::HypreParMatrix::~HypreParMatrix (this=0x555556bad120, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/linalg/hypre.hpp:966
#7  0x00007fffe57f18c2 in mfem::HypreParMatrix::~HypreParMatrix (this=0x555556bad120, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/linalg/hypre.hpp:966
#8  0x00007fffe6bb6f87 in mfem::ParFiniteElementSpace::Destroy (this=0x555556b67fa0) at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/fem/pfespace.cpp:4751
#9  0x00007fffe57bc7d0 in mfem::ParFiniteElementSpace::~ParFiniteElementSpace (this=0x555556b67fa0, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/contrib/mfem/fem/pfespace.hpp:519
#10 0x00007ffff403f6ef in __gnu_cxx::new_allocator<mfem::ParFiniteElementSpace>::destroy<mfem::ParFiniteElementSpace> (this=0x555556b67fa0, __p=0x555556b67fa0) at /usr/include/c++/11/ext/new_allocator.h:168
#11 0x00007ffff403782b in std::allocator_traits<std::allocator<mfem::ParFiniteElementSpace> >::destroy<mfem::ParFiniteElementSpace> (__a=..., __p=0x555556b67fa0) at /usr/include/c++/11/bits/alloc_traits.h:535
#12 0x00007ffff402fe1d in std::_Sp_counted_ptr_inplace<mfem::ParFiniteElementSpace, std::allocator<mfem::ParFiniteElementSpace>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555556b67f90)
    at /usr/include/c++/11/bits/shared_ptr_base.h:528
#13 0x000055555556a354 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556b67f90) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#14 0x0000555555569e87 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x555556b49f50, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#15 0x00007ffff3f54896 in std::__shared_ptr<mfem::ParFiniteElementSpace, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555556b49f48, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#16 0x00007ffff3f548e0 in std::shared_ptr<mfem::ParFiniteElementSpace>::~shared_ptr (this=0x555556b49f48, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#17 0x00007ffff3f54d7b in MFEMFESpace::~MFEMFESpace (this=0x555556b49770, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/build/header_symlinks/MFEMFESpace.h:22
#18 0x00007ffff3f55065 in MFEMSimplifiedFESpace::~MFEMSimplifiedFESpace (this=0x555556b49770, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/build/header_symlinks/MFEMSimplifiedFESpace.h:17
#19 0x00007ffff4024add in MFEMScalarFESpace::~MFEMScalarFESpace (this=0x555556b49770, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/build/header_symlinks/MFEMScalarFESpace.h:15
#20 0x00007ffff4024b7a in MFEMScalarFESpace::~MFEMScalarFESpace (this=0x555556b49770, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/build/header_symlinks/MFEMScalarFESpace.h:15
#21 0x00007ffff5708824 in std::default_delete<UserObject>::operator() (this=0x555556b66a70, __ptr=0x555556b49770) at /usr/include/c++/11/bits/unique_ptr.h:85
#22 0x00007ffff5812010 in std::_Sp_counted_deleter<UserObject*, std::default_delete<UserObject>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555556b66a60) at /usr/include/c++/11/bits/shared_ptr_base.h:442
#23 0x000055555556a354 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556b66a60) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#24 0x0000555555569e87 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x555556bdad28, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#25 0x00007ffff3f573a6 in std::__shared_ptr<MooseObject, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555556bdad20, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#26 0x00007ffff3f573c6 in std::shared_ptr<MooseObject>::~shared_ptr (this=0x555556bdad20, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#27 0x00007ffff460a459 in std::_Destroy<std::shared_ptr<MooseObject> > (__pointer=0x555556bdad20) at /usr/include/c++/11/bits/stl_construct.h:151
#28 0x00007ffff45f4ca8 in std::_Destroy_aux<false>::__destroy<std::shared_ptr<MooseObject>*> (__first=0x555556bdad20, __last=0x555556bdad90) at /usr/include/c++/11/bits/stl_construct.h:163
#29 0x00007ffff45d1da0 in std::_Destroy<std::shared_ptr<MooseObject>*> (__first=0x555556bdad20, __last=0x555556bdad90) at /usr/include/c++/11/bits/stl_construct.h:196
#30 0x00007ffff45a6dbf in std::_Destroy<std::shared_ptr<MooseObject>*, std::shared_ptr<MooseObject> > (__first=0x555556bdad20, __last=0x555556bdad90) at /usr/include/c++/11/bits/alloc_traits.h:848
#31 0x00007ffff4573333 in std::vector<std::shared_ptr<MooseObject>, std::allocator<std::shared_ptr<MooseObject> > >::~vector (this=0x555556746938, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/stl_vector.h:680
#32 0x00007ffff452d558 in TheWarehouse::~TheWarehouse (this=0x555556746930, __in_chrg=<optimized out>) at /data/lindad/projects/gpu-moose-dbg/framework/src/base/TheWarehouse.C:111
```
After this new call to `HYPRE_Initialize` the memory location may not be set properly because the default hypre memory location is the device. And eventually we get seg faults in optimized modes I believe because of this. In debug mode we fail assertions about mismatches in memory locations

### Steps to Reproduce

Run the `h1_mfem_sub_mfem_sub` example with cuda configured

### Impact

Segmentation faults

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #31037

### CODE REVIEW

**Comment by lindsayad** [comment]
failure is unrelated

File: framework/include/base/MooseApp.h [hunk 1]
```diff
@@ -1124,6 +1092,24 @@ class MooseApp : public ConsoleStreamInterface,
...
+
+  /**
+   * Get the MFEM device object
+   */
+  std::shared_ptr<mfem::Device> getMFEMDevice(Moose::PassKey<MultiApp>) { return _mfem_device; }
+
+  /**
+   * Get the configured MFEM devices
+   */
+  const std::set<std::string> & getMFEMDevices(Moose::PassKey<MultiApp>) { return _mfem_devices; }
```
Comment (loganharbour) [inline framework/include/base/MooseApp.h]:
```suggestion
  const std::set<std::string> & getMFEMDevices(Moose::PassKey<MultiApp>) const { return _mfem_devices; }
```

**Review by loganharbour — CHANGES_REQUESTED** [review]
Good otherwise

**Comment by nmnobre** [comment]
With something like [this](https://github.com/libMesh/libmesh/compare/devel...nmnobre:libmesh:printset) we'd avoid some of the back-and-forth between set and vector containers, is it worth it?
Also, do we understand exactly why this was a problem(?), don't multi apps live in different processes and therefore different address spaces?

File: framework/include/base/MooseApp.h [hunk 2]
```diff
@@ -9,14 +9,22 @@
 
 #pragma once
 
-#ifdef LIBTORCH_ENABLED
+#include "MooseConfig.h"
+
```
Comment (nmnobre) [inline framework/include/base/MooseApp.h]:
```suggestion
```

File: framework/src/base/MooseApp.C [hunk 3]
```diff
@@ -55,6 +55,7 @@
 #include "StringInputStream.h"
 #include "MooseMain.h"
 #include "FEProblemBase.h"
+#include "MooseConfig.h"
```
Comment (nmnobre) [inline framework/src/base/MooseApp.C]:
```suggestion
```

**Review by nmnobre — CHANGES_REQUESTED** [review]
No need to include the config header explicitly anymore with #30916.

**Comment by lindsayad** [comment]
> With something like [this](https://github.com/libMesh/libmesh/compare/devel...nmnobre:libmesh:printset) we'd avoid some of the back-and-forth between set and vector containers, is it worth it?

Already did it in https://github.com/libMesh/libmesh/pull/4212. But the current code works without a libmesh submodule update

> Also, do we understand exactly why this was a problem(?), don't multi apps live in different processes and therefore different address spaces?

If you are running in serial, the parent app and child applications will all live on the same process

**Comment by nmnobre** [comment]
> Already did it in [libMesh/libmesh#4212](https://github.com/libMesh/libmesh/pull/4212)

Ace.

> If you are running in serial, the parent app and child applications will all live on the same process

That explains it.

**Review by nmnobre — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]
