### PR TITLE
LinearCombinationFunction now computes gradient and vectorValue

### LINKED ISSUE #9186: compute gradient and vectorValue in LinearCombinationFunction
### Description of the enhancement or error report

Currently LinearCombinationFunction only computes the "value".  Enhance it to combine the "gradient" and "vectorValue" too.

### Rationale for the enhancement or information for reproducing the error

Is there something wrong with this proposal?  I think i'm missing something!

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by WilkAndy**
Fixes #9186

### CODE REVIEW

File: framework/src/functions/LinearCombinationFunction.C [hunk 1]
```diff
@@ -61,3 +61,21 @@ LinearCombinationFunction::value(Real t, const Point & p)
...
+LinearCombinationFunction::gradient(Real t, const Point & p)
+{
+  RealGradient g;
+  for (unsigned i = 0; i < _f.size(); ++i)
+    g += _w[i] * _f[i]->gradient(t, p);
+  return g;
+}
+
+RealVectorValue
+LinearCombinationFunction::vectorValue(Real t, const Point & p)
```
Comment (permcody) [inline framework/src/functions/LinearCombinationFunction.C]: Do we really want a `vectorValue` method? Especially since it's a duplicate of the gradient? I think `value` and `gradient` are the normal types we want to support.

Comment (WilkAndy) [inline framework/src/functions/LinearCombinationFunction.C]: vectorValue vs gradient.   Why are there two methods in Function then?  I'm happy to remove one or the other from this PR, but i presume they're both useful for someone?

Comment (permcody) [inline framework/src/functions/LinearCombinationFunction.C]: I'll look into this, stay tuned.

Comment (permcody) [inline framework/src/functions/LinearCombinationFunction.C]: @aeslaughter - It looks like you added the `vectorValue()` method 4 years ago. Can you recall why this was needed and the `gradient()` method didn't suffice? I just want to make sure we don't have users duplicating implementations for these two methods.

Comment (aeslaughter) [inline framework/src/functions/LinearCombinationFunction.C]: I think I just didn't like the fact that if I had a function that returned a vector that I needed do use a method called "gradient", when I didn't want a gradient just a vector function.

That is, it was for code read ability, calling gradient when you don't want the gradient seemed wrong.

Comment (aeslaughter) [inline framework/src/functions/LinearCombinationFunction.C]: Generally, if you have a scalar and a gradient you use "value" and "gradient" and error on "vectorValue". If you have a vector function you use "vectorValue" and error on the others.

Comment (WilkAndy) [inline framework/src/functions/LinearCombinationFunction.C]: OK, so what's the conclusion here?  To me it seems that vectorValue is appropriate in certain situations.  In this PR if the basis Functions have to implement vectorValue then the LinearCombinationFunction will also calculate vectorValue.  Similar for gradient.

Comment (permcody) [inline framework/src/functions/LinearCombinationFunction.C]: So having both isn't a problem except it's code duplication 😛 . If you really want to fix that, you'd call a templated helper function:

```
template <typename T>
T vectorHelper(Real t, const Point & p)
{ 
  // One copy of logic here ...
}

RealVectorValue
LinearCombinationFunction::vectorValue(Real t, const Point & p)
{
    return vectorHelper<RealVectorValue>(t, P);
}

Gradient
LinearCombinationFunction::gradient(Real t, const Point & p)
{
    return vectorHelper<Gradient>(t, P);
}
```

Comment (WilkAndy) [inline framework/src/functions/LinearCombinationFunction.C]: OK, i'd quite like to try the template thing.  i haven't done templating before much so want to gain a tiny bit of experience.

**Comment by WilkAndy** [comment]
I'm on holidays for a while.  I doubt i'll be able to address these comments for another 2 weeks.

File: framework/src/functions/LinearCombinationFunction.C (hunk 1 above)
Comment (WilkAndy) [inline framework/src/functions/LinearCombinationFunction.C]: Hi @permcody .  I've just had a go at this templating of vectorValue and gradient in the LinearCombinationFunction.  I don't see how it's going to be advantageous.  The templated function will have to look something like:

```
template <typename T>
T
LinearCombinationFunction::vectorHelper(Real t, const Point & p)
{
  T g;
  for (unsigned i = 0; i < _f.size(); ++i)
    if (T == Gradient)
      g += _w[i] * _f[i]->gradient(t, p);
    else if (T == vectorValue)
      g += _w[i] * _f[i]->vectorValue(t, p);
  return g;
}
```
Obviously this is not real code, but hopefully you understand my point: i have to use the "gradient" or "vectorValue" functions in the body of the code.  I could now template those, in Function, but it seems excessive mucking around with the code just to save (maybe) one line of code duplication.

What do you think?  Have i misunderstood your suggestion?

Comment (WilkAndy) [inline framework/src/functions/LinearCombinationFunction.C]: Any thoughts here, @permcody ?

Comment (permcody) [inline framework/src/functions/LinearCombinationFunction.C]: Well that's a no go. I'm going to see if @friedmud or @andrsd has an opinion. I really don't like the fact that we have these two, "almost the same" interfaces hanging around in Function IC that people are starting to override. I'd really like to get rid of one of them, but I know there are people that think we should support both "Gradient" and "VectorValue" variants for type correctness.

**Comment by friedmud** [comment]
Yes: we need both.  A vector valued function also _has_ a gradient (which is a tensor/matrix).  The two things (vector value and gradient) are logically distinct.

This:

 - A gradient is a derivative
 - A vector value is not a derivative

Ideally we would have `Function` and `VectorFunction` or a templated `Function`... but none of that is really needed currently... so it's fine to have `vectorValue()` for the few cases where that's useful.

File: framework/src/functions/LinearCombinationFunction.C (hunk 1 above)
Comment (andrsd) [inline framework/src/functions/LinearCombinationFunction.C]: I agree with @friedmud's [comment](https://github.com/idaholab/moose/pull/9320#issuecomment-313145863)

**Comment by WilkAndy** [comment]
So i think this PR is ready to merge, right?

**Review by permcody — APPROVED** [review]
