### PR TITLE
Remove linear checker

### LINKED ISSUE #11970: l_abs_step_tol is completely broken
## Rationale
If the user supplies any positive number for `l_abs_step_tol` in `Executioner`, linear solves always converge in 1 iteration, even if the linear solve is nowhere even close to convergence.

Furthermore, the check in `FEProblemBase::checkLinearConvergence` is completely wrong anyway; it does
```
| ||r^{old}|| - ||r^{new}|| | < l_abs_step_tol
```
This is just wrong. For instance, the two residual vectors could be very different, yet have the same norms, so step convergence would be detected falsely.  The correct implementation is
```
||r^{old} - r^{new}|| < l_abs_step_tol
```

## Description
In `FEProblemBase::checkLinearConvergence`, print out `rnorm` and `system._last_rnorm`. You'll see that on the second call to this function in each linear solve, `rnorm` and `system._last_rnorm` are exactly equal, which seems to suggest that `system._last_rnorm` is updated with the new `rnorm` *before* calling this function.

There appears to be only 1 input file in MOOSE where `l_abs_step_tol` is even used: `modules/combined/examples/mortar/mortar_gradient.i`. You'll notice that those linear solves converge in 1 iteration.

## Impact
Fix broken linear convergence monitoring.

### PR DESCRIPTION
**Pull request by fdkong**
Closes #11970

### CODE REVIEW

**Comment by fdkong** [comment]
Curious about if or not we are actually using `checkLinearConvergence`.

**Comment by fdkong** [comment]
I remembered we were actually using this function.

**Comment by fdkong** [comment]
@idaholab/moose-team  Anyone happens to know why we introduced  `FEProblemBase::checkLinearConvergence` at the first place? I was asking because it looks like we do not call this function by default.

**Comment by friedmud** [comment]
I think it's used in some of the custom problems.  Check with the BISON
guys.

**Comment by fdkong** [comment]
> I think it's used in some of the custom problems. Check with the BISON guys

@bwspenc Are you using this function? `FEProblemBase::checkLinearConvergence`

**Comment by fdkong** [comment]
I did NOT see anything in bison.

**Comment by fdkong** [comment]
@lindsayad  I just deleted the linear checker without any issue. Do you know why we need a customized linear checker? Who is using it?

**Comment by lindsayad** [comment]
I don’t know. I agree that we should just delete it if we can

**Comment by fdkong** [comment]
> I don’t know. I agree that we should just delete it if we can

OK. I am going to delete it. I believe civet will tell us if we are able to do that.

**Comment by fdkong** [comment]
OK. We should just delete it.

File: framework/src/executioners/FEProblemSolve.C [hunk 1]
```diff
@@ -53,8 +53,6 @@ validParams<FEProblemSolve>()
   params += Moose::PetscSupport::getPetscValidParams();
 #endif // LIBMESH_HAVE_PETSC
   params.addParam<Real>("l_tol", 1.0e-5, "Linear Tolerance");
-  params.addDeprecatedParam<Real>(
```
Comment (lindsayad) [inline framework/src/executioners/FEProblemSolve.C]: Rattlesnake is failing because of this deletion

File: framework/src/problems/FEProblemBase.C [hunk 2]
```diff
@@ -5878,8 +5878,8 @@ FEProblemBase::checkNonlinearConvergence(std::string & msg,
                             : system._initial_residual_after_preset_bcs;
     if (fnorm <= the_residual * rtol)
     {
-      oss << "Converged due to function norm " << fnorm << " < "
-          << " (relative tolerance)\n";
+      // oss << "Converged due to function norm " << fnorm << " < "
```
Comment (lindsayad) [inline framework/src/problems/FEProblemBase.C]: Why did you comment this out? I don't think we want to do this...?

File: framework/src/utils/PetscSupport.C [hunk 3]
```diff
@@ -572,10 +476,10 @@ petscSetKSPDefaults(FEProblemBase & problem, KSP ksp)
   // routine for destroying said private data context.  In this case,
   // we use the default context provided by PETSc in addition to
   // a few other tests.
-  {
+  /*{
```
Comment (lindsayad) [inline framework/src/utils/PetscSupport.C]: Instead of commenting this out, we just want to remove it right?

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Comment by fdkong** [comment]
I do not see any user case right now. And PETSc does not call the linear checker from v3.10.

It is better to just remove it to avoid confusing.

**Comment by fdkong** [comment]
@lindsayad  It is ready for review

**Review by lindsayad — APPROVED** [review]
