### PR TITLE
Converting computeQpResidual to pass-by-reference for array kernels.

### LINKED ISSUE #16504: Pass-by-reference for ArrayKernel evaluation
## Bug Description
When doing some profiling of ArrayKernels, I found that despite my best efforts `computeQpResidual` was still unexpectedly allocating temporary memory. After much reading and headache I began to understand how Eigen does matrix-vector operations and learned when it creates temporary objects. From this, I learned how to better do in-place operations and realized that pass-by-reference was the best way to take advantage of this.

## Steps to Reproduce
At the end of this is an input with a simple diffusion problem with a bunch of components to an array variable.  Using instruments on my mac, I saw the allocation and deallocation sequences within `computeQpResidual`:
image

Changing the residual evaluation in `ArrayDiffusion` to pass-by-reference and using in-place operations:
```
void
ArrayDiffusion::computeQpResidual(RealEigenVector & vector)
{
  vector.noalias() = _grad_u[_qp] * _array_grad_test[_i][_qp];
  vector.array() *= (*_d_array)[_qp].array();
}
```
There is no more memory thrashing inside `computeQpResidual`. As a result `computeQpResidual` for this problem dropped by ~20%.

## Impact
Using the pass-by-reference would have significant impacts on derived objects of ArrayKernel, since this changes the API. Although I believe Griffin is the only app using array kernels, so this will be on me to make changes.

```
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 10
  ny = 10
  nz = 10
[]

[Variables]
  [u]
    order = FIRST
    family = LAGRANGE
    components = 500
  []
[]

[Kernels]
  [diff]
    type = ArrayDiffusion
    variable = u
    diffusion_coefficient = dc
  []
[]

[BCs]
  [right]
    type = ArrayDirichletBC
    variable = u
    boundary = '1 2'
    values = '1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1'
  []
[]

[Materials]
  [dc]
    type = GenericConstantArray
    prop_name = dc
    prop_value = '1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1'
  []
[]

[Executioner]
  type = Steady
  solve_type = JFNK
  l_max_its = 100
  nl_abs_tol = 1e-12
  nl_rel_tol = 1e-14
[]

[Outputs]
  [pg]
    type = PerfGraphOutput
    level = 10
  []
[]
```

### PR DESCRIPTION
**Pull request by zachmprince**
This PR converts the `computeQpResidual` API in array kernels to pass-by-reference. This allows for more flexibility in optimizing this function for large array variables. See the discussion in #16504 for more details. I've also added some documentation in ArrayMooseVariable.md for some of the things I've learned through the process of optimizing residual evaluations.

Closes #16504

### CODE REVIEW

**Review by loganharbour — COMMENTED** [review]
Just did a quick run-through. I'll leave most of it to Alex, but I think it's worthwhile adding comments _everywhere_ you use `noalias()`. Maybe not as much as you have in `ArrayDiffusion`, or you could have a link to the moosedocs with a description

**Comment by loganharbour** [comment]
Also - some performance comparisons may be nice if you have them around :-)

**Comment by zachmprince** [comment]
> Also - some performance comparisons may be nice if you have them around :-)

You can see some performance comparisons with ArrayDiffusion here:
[https://github.com/idaholab/moose/issues/16504#issue-768327122](https://github.com/idaholab/moose/issues/16504#issue-768327122)
[https://github.com/idaholab/moose/issues/16504#issuecomment-746756814](https://github.com/idaholab/moose/issues/16504#issuecomment-746756814)

For Griffin, a 2-D 274360 element DFEM benchmark, 11 variables with 512 components. About a 5% reduction in total time, and Kernel evaluation was about 17% faster.
Before:
```
|                              Section                              | Calls |   Self(s)  |   Avg(s)   |    %   | Children(s) |   Avg(s)   |    %   |  Total(s)  |   Avg(s)   |    %   |
| GriffinApp (main)                                                 |     1 |      0.078 |      0.078 |   0.00 |    6118.384 |   6118.384 | 100.00 |   6118.462 |   6118.462 | 100.00 |
|                 NonlinearSystemBase::Kernels                      |   380 |   2100.244 |      5.527 |  34.33 |       0.000 |      0.000 |   0.00 |   2100.244 |      5.527 |  34.33 |
```
After:
```
|                              Section                              | Calls |   Self(s)  |   Avg(s)   |    %   | Children(s) |   Avg(s)   |    %   |  Total(s)  |   Avg(s)   |    %   |
| GriffinApp (main)                                                 |     1 |      0.076 |      0.076 |   0.00 |    5837.104 |   5837.104 | 100.00 |   5837.180 |   5837.180 | 100.00 |
|                 NonlinearSystemBase::Kernels                      |   380 |   1753.731 |      4.615 |  30.04 |       0.000 |      0.000 |   0.00 |   1753.731 |      4.615 |  30.04 |
```

**Comment by zachmprince** [comment]
I have a Griffin patch ready to go [here](https://gitlab.software.inl.gov/idaholab/griffin/-/merge_requests/130).

File: framework/src/kernels/ArrayKernel.C [hunk 1]
```diff
@@ -102,9 +103,10 @@ ArrayKernel::computeResidual()
     initQpResidual();
     for (_i = 0; _i < _test.size(); _i++)
     {
-      _work_vector = computeQpResidual() * _JxW[_qp] * _coord[_qp];
+      computeQpResidual(_work_vector);
```
Comment (loganharbour) [inline framework/src/kernels/ArrayKernel.C:106]: You probably want to zero `_work_vector` before, no?

Comment (zachmprince) [reply framework/src/kernels/ArrayKernel.C:106]: Do you mean in this loop or in the constructor? Seems like unnecessary operation in this loop.

Comment (loganharbour) [reply framework/src/kernels/ArrayKernel.C:106]: Someone could easily add to the vector instead of setting it.

Comment (zachmprince) [reply framework/src/kernels/ArrayKernel.C:106]: You're right. I'll add a `setZero` then. Seems silly that someone would just add to it before knowing what is in the vector, but it is very possible.

Comment (loganharbour) [reply framework/src/kernels/ArrayKernel.C:106]: Yeah - I definitely agree. Very unlikely but could easily make one's day horrid 💩

**Comment by loganharbour** [comment]
> Job [Python 3.6 Tests](https://civet.inl.gov/job/651605/) on [1d6c7a8](https://github.com/idaholab/moose/commit/1d6c7a836513888a00a566138afc5a62a7c2f411) : invalidated by @lindsayad

@lindsayad won't pass until a re-push - @zachmprince knows about this.

**Comment by rwcarlsen** [comment]
We should look at some proper profiles to make sure this is resolving all the allocs/frees we expect it to address.

**Comment by loganharbour** [comment]
> We should look at some proper profiles to make sure this is resolving all the allocs/frees we expect it to address.

Is that you volunteering? :)

**Comment by rwcarlsen** [comment]
I could do it if @zachmprince could maybe direct me toward which sims are most useful to run/measure.

**Comment by zachmprince** [comment]
> I could do it if @zachmprince could maybe direct me toward which sims are most useful to run/measure.

I used instruments on a reduced version of one of our benchmarks to see the allocation/free calls are being avoided, and they are from my analysis. I am not great with gperf tools yet, so I didn't explicitly check for the big problem. You check out this PR and [this Griffin MR](https://gitlab.software.inl.gov/idaholab/griffin/-/merge_requests/130) to try it out. The one I suggest is `griffin/tests/performance/treat/19x19_het_mincrit_DFEM_11G.i`. I ran this problem with 24 nodes on sawtooth with 24 processes per node (`mpiexec -ppn 24`). @rwcarlsen you can use the reduced version of this we talked about previously as well.

**Comment by rwcarlsen** [comment]
I'll take a look tomorrow.

**Comment by rwcarlsen** [comment]
From

Screen Shot 2021-01-05 at 11 33 00 AM

to

Screen Shot 2021-01-05 at 11 33 08 AM

Looks good to me.

**Comment by zachmprince** [comment]
Woohoo! Thank you Robert!

File: framework/doc/content/source/variables/ArrayMooseVariable.md [hunk 2]
```diff
@@ -30,66 +32,134 @@ OutputType is the data type used for templating.
...
+  \vec{v} \texttt{ = } \vec{v}\texttt{.cwiseProduct(}\vec{w}\texttt{)} \rightarrow v_i = v_iw_i, i=1,...,n
+
+  !equation
+  \vec{v}\texttt{.array() /= } \vec{w}\texttt{.array()} \rightarrow v_i = v_i/w_i, i=1,...,n
+
+## Eigen Tips and Tricks (Advanced)
+
+Eigen has some unique features that, when used properly, can significantly impact performance. Here are some recommendations that can improve code performance.
+
+- [Aliasing](http://eigen.tuxfamily.org/dox/group__TopicAliasing.html) is a technique in Eigen that contructs temporary objects when performing matrix multiplications, this is to avoid overriding data that needs to be used later in the computation. For instance `vec = mat * vec` will create a temporary vector for `mat * vec` then assign it to `vec` at the end. However, `vec2 = mat * vec1` does not need this temporary object and assign the result to `vec2` directly, this aliasing can be avoided by doing `vec2.noalias()`. The `noalias()` function should be used with extreme caution since it can cause erroneous results.
```
Comment (loganharbour) [inline framework/doc/content/source/variables/ArrayMooseVariable.md:143]: 👍🏼

File: framework/include/bcs/ArrayIntegratedBC.h [hunk 3]
```diff
@@ -47,7 +47,7 @@ class ArrayIntegratedBC : public IntegratedBCBase, public MooseVariableInterface
   /**
    * Method for computing the residual at quadrature points
    */
-  virtual RealEigenVector computeQpResidual() = 0;
+  virtual void computeQpResidual(RealEigenVector & residual) = 0;
```
Comment (loganharbour) [inline framework/include/bcs/ArrayIntegratedBC.h:50]: Add something useful about the residual here in the docstring, something like

```
The residual is to be filled within \p residual.
```

File: framework/include/bcs/ArrayNodalBC.h [hunk 4]
```diff
@@ -46,7 +46,7 @@ class ArrayNodalBC : public NodalBCBase, public MooseVariableInterface<RealEigen
   /// Value of the unknown variable this BC is acting on
   const RealEigenVector & _u;
 
-  virtual RealEigenVector computeQpResidual() = 0;
+  virtual void computeQpResidual(RealEigenVector & residual) = 0;
```
Comment (loganharbour) [inline framework/include/bcs/ArrayNodalBC.h:49]: Add docstring

File: framework/include/dgkernels/ArrayDGKernel.h [hunk 5]
```diff
@@ -67,7 +67,7 @@ class ArrayDGKernel : public DGKernelBase, public NeighborMooseVariableInterface
    * This is the virtual that derived classes should override for computing the residual on
    * neighboring element.
    */
-  virtual RealEigenVector computeQpResidual(Moose::DGResidualType type) = 0;
+  virtual void computeQpResidual(Moose::DGResidualType type, RealEigenVector & residual) = 0;
```
Comment (loganharbour) [inline framework/include/dgkernels/ArrayDGKernel.h:70]: Add docstring about `\p residual`

File: framework/include/kernels/ArrayKernel.h [hunk 6]
```diff
@@ -46,7 +46,7 @@ class ArrayKernel : public KernelBase, public MooseVariableInterface<RealEigenVe
   /**
    * Compute this Kernel's contribution to the residual at the current quadrature point
    */
-  virtual RealEigenVector computeQpResidual() = 0;
+  virtual void computeQpResidual(RealEigenVector & residual) = 0;
```
Comment (loganharbour) [inline framework/include/kernels/ArrayKernel.h:49]: Add docstring about `\p residual`

File: framework/src/bcs/ArrayDirichletBC.C [hunk 7]
```diff
@@ -31,8 +31,8 @@ ArrayDirichletBC::ArrayDirichletBC(const InputParameters & parameters)
 {
 }
 
-RealEigenVector
-ArrayDirichletBC::computeQpResidual()
+void
+ArrayDirichletBC::computeQpResidual(RealEigenVector & residual)
 {
-  return _u - _values;
+  residual = _u - _values;
```
Comment (loganharbour) [inline framework/src/bcs/ArrayDirichletBC.C:37]: Can you add a check in the constructor on the size of `_values` vs `_var.count()`?

**Review by loganharbour — CHANGES_REQUESTED** [review]
Minor changes.

If possible, while you're here, it'd be nice to add as many checks as possible on `RealEigenVector` inputs matching `_var.count()`.

**Review by loganharbour — DISMISSED** [review]
Much wow. Very nice. Beautiful code.

**Review by loganharbour — DISMISSED** [review]
Much wow. Very nice. Beautiful code. (part 2)

**Comment by loganharbour** [comment]
Let's hold off on this until #16618 is in so that next can be green before having to also deal with updating Griffin.

**Comment by lindsayad** [comment]
We'll have to wait on libmesh/libmesh#2828 and then a libmesh update

**Comment by loganharbour** [comment]
@zachmprince we can probably get this in on the weekend once griffin master goes green again.

**Review by loganharbour — APPROVED** [review]
We're planning on the Griffin fix showing up overnight.
