### PR TITLE
Ensure there are always mass matrix contributors for explicit solves

### LINKED ISSUE #29834: Ensure there are always mass matrix contributors for explicit solves
### Motivation

Previously there were no sanity checks to see that we actually had objects contributing to the mass matrix for explicit solves meaning we could end up with an empty matrix as mostly happened in the PR addressing #28053

### Design

Search for objects that contribute to the mass matrix. If none are present, error.

### Impact

Avoid confusing simulation behavior such as segmentation faults in hypre

### PR DESCRIPTION
**Pull request by lindsayad**
Closes https://github.com/idaholab/moose/issues/29834

### CODE REVIEW

File: framework/src/timeintegrators/ExplicitTimeIntegrator.C [hunk 1]
```diff
@@ -63,6 +69,76 @@ void
...
+                  .hasVariableObjects(var_id))
+            continue;
+          if (_nl->getDGKernelWarehouse()
+                  .getMatrixTagObjectWarehouse(mass_matrix_tag_id, 0)
+                  .hasVariableObjects(var_id))
+            continue;
+          if (_nl->getNodalKernelWarehouse()
+                  .getMatrixTagObjectWarehouse(mass_matrix_tag_id, 0)
+                  .hasVariableObjects(var_id))
+            continue;
```
Comment (GiudGiud) [inline framework/src/timeintegrators/ExplicitTimeIntegrator.C:129]: HDG Kernels?

**Review by GiudGiud — COMMENTED** [review]
great cleanup

File: framework/src/timeintegrators/ExplicitTimeIntegrator.C [hunk 2]
```diff
@@ -63,6 +69,76 @@ void
...
+    std::unordered_set<unsigned int> vars_to_check;
+    if (!_vars.empty())
+      vars_to_check = _vars;
+    else
+      for (const auto i : make_range(_nl->nVariables()))
+        vars_to_check.insert(i);
+
+    const auto mass_matrix_tag_id = massMatrixTagID();
+    std::set<TagID> matrix_tags = {mass_matrix_tag_id};
+    auto fv_object_starting_query = _fe_problem.theWarehouse()
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/timeintegrators/ExplicitTimeIntegrator.C:84]: because it's only used for querying FV objects. FE objects are all from `MooseObjectWarehouses`, not `theWarehouse`

File: framework/src/timeintegrators/ExplicitTimeIntegrator.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/timeintegrators/ExplicitTimeIntegrator.C:129]: these inherit from `KernelBase` and are contained within the kernel warehouse

**Review by GiudGiud — APPROVED** [review]
