### PR TITLE
Do not recurse on semi-local elements

### LINKED ISSUE #7200: GrainTracker has issues with accessing DOFs on Semilocal elements
### Description of the enhancement or error report

I hit an `petsc_vector` assertion when trying to run a simple grain_growth problem in 3D with adaptivity. I then learned that semi-local != ghosted! The grain tracker assumes this is OK.

### Rationale for the enhancement or information for reproducing the error

Cannot access DOFs on some semi-local elements. This is tricky to reproduce but can be done with no physics on a 3D cube with refinement if you attempt to access all of each processors semi-local elements' DOFs. I cannot reproduce this error in 2D.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Limited I believe. We may need to investigate these literal edge or corner cases in libMesh to see if there are any unhandled cases in 3D. For now, I'm choosing an alternative method to handle stitching in the FeatureFloodCount and GrainTracker objects.

### PR DESCRIPTION
**Pull request by permcody**
Instead of recursing if elements (or nodes) that are semilocal, this patch
allows recursion on neighbors of active local elements but nothing
beyond that. I have verified that this at least removes the previous
assertion (seg fault) on the attached 3D input file. This is way
to large to turn into a regression test. More work to manufacture a
good test is needed.

closes #7200

Tagging @jwpeterson since this is his idea
@roystgnr and @dschwen.

### CODE REVIEW

File: modules/phase_field/src/postprocessors/FeatureFloodCount.C [hunk 1]
```diff
@@ -636,7 +610,7 @@ FeatureFloodCount::updateFieldInfo()
 
       // Loop over the ghosted ids to update cells with ghost information
       for (auto entity : feature._ghosted_ids)
-        _ghosted_entity_ids[entity] = feature_number;
+        _ghosted_entity_ids[entity] = 1;
```
Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Are you sure it's not "4"?

Comment (permcody) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Yeah, I'm sure...

I changed this line because I really don't want to see a "multi-colored" field when I look at ghosted ids. Using processor_id might be interesting but certainly not something related to the feature or grain. Just using a constant gives the "expected" looking field.

**Comment by permcody** [comment]
The halos don't look quite right.... I think the problem is that I need to always premark entries (like I was doing before) even when I don't do the recursion step. I'll experiment with that some more before we merge this.

**Comment by permcody** [comment]
Got a little carried away and spent about 8 hours rewriting everything again (on Saturday). I was able to create a few pretty good regression problems that run in several second and do advanced remapping so I'll even be able to create better regression tests from all of this. I need to polish up all the inputs and also I need to try this on the 3D adaptive problem before this is merged. I'll do all that on Monday.

File: framework/include/restart/DataIO.h [hunk 2]
```diff
@@ -374,7 +374,7 @@ dataLoad(std::istream & stream, std::list<T> & l, void * context)
   {
     T data;
     loadHelper(stream, data, context);
-    l.push_back(data);
+    l.push_back(std::move(data));
```
Comment (permcody) [inline framework/include/restart/DataIO.h]: I need to go through all the DataIO methods and mark many of them with `std::move`...

File: modules/phase_field/src/postprocessors/FeatureFloodCount.C [hunk 3]
```diff
@@ -727,56 +679,57 @@ FeatureFloodCount::visitElementalNeighbors(const Elem * elem, unsigned long curr
...
+          /**
+           * Premark neighboring entities with a halo mark. These
+           * entities may or may not end up being part of the feature.
+           * We will not update the _entities_visited data structure
+           * here.
+           */
+          feature->_halo_ids.insert(neighbor->id());
+
+          flood(neighbor, current_idx, feature);
+        }
```
Comment (permcody) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: @roystgnr - Take a look at this condition for recursing. It's actually quite simple now and much more elegant that looking at the semi-local set. Also seems to work just fine :)

**Comment by permcody** [comment]
This requires a one line change to BISON. I have that patch ready.

File: framework/include/restart/DataIO.h (hunk 2 above)
Comment (permcody) [inline framework/include/restart/DataIO.h]: Well I went through DataIO and we only needed one other `std::move()`

**Comment by permcody** [comment]
Sorry this ended up being huge @jwpeterson - It should be ready to review and merge. I have the BISON patch ready.

File: framework/src/restart/DataIO.C [hunk 4]
```diff
@@ -218,13 +218,11 @@ dataLoad(std::istream & stream, std::string & v, void * /*context*/)
...
-  char* s = new char[size+1];
-  stream.read(s, sizeof(char)*(size+1));
+  // Resize the string data
+  v.resize(size);
 
-  // Store the string and clean up
-  v = s;
-  delete[] s;
+  // Read the string
+  stream.read(&v[0], sizeof(char) * size);
```
Comment (jwpeterson) [inline framework/src/restart/DataIO.C]: Just found out today that this is now *guaranteed* to work in C++11.

File: modules/phase_field/include/postprocessors/FeatureFloodCount.h [hunk 5]
```diff
@@ -65,14 +66,14 @@ class FeatureFloodCount :
...
-  virtual Real getEntityValue(dof_id_type entity_id, FIELD_TYPE field_type, unsigned int var_idx=0) const;
+  virtual Real getEntityValue(dof_id_type entity_id, FieldType field_type, unsigned int var_idx=0) const;
 
   virtual const std::vector<std::pair<unsigned int, unsigned int> > & getElementalValues(dof_id_type elem_id) const;
 
   inline bool isElemental() const { return _is_elemental; }
 
   /// This enumeration is used to indicate status of the grains in the _unique_grains data structure
-  enum STATUS
+  enum class Status
```
Comment (jwpeterson) [inline modules/phase_field/include/postprocessors/FeatureFloodCount.h]: I hope all our minimum required compilers support `enum class`, this is another thing we never tested.

File: modules/phase_field/include/postprocessors/FeatureFloodCount.h [hunk 6]
```diff
@@ -220,20 +281,20 @@ class FeatureFloodCount :
    * any intersection is detected.
    */
   template<class InputIterator>
-  inline bool setsIntersect(InputIterator first1, InputIterator last1, InputIterator first2, InputIterator last2) const
+  static inline bool setsIntersect(InputIterator first1, InputIterator last1, InputIterator first2, InputIterator last2)
```
Comment (jwpeterson) [inline modules/phase_field/include/postprocessors/FeatureFloodCount.h]: Future note: we should eventually move this to MooseUtils.

File: framework/src/restart/DataIO.C (hunk 4 above)
Comment (roystgnr) [inline framework/src/restart/DataIO.C]: Wait, what changed in C++11?  I thought &v[0] is guaranteed to work iff the vector (in this case string?) is non-empty, regardless of standard.  C++11 added http://en.cppreference.com/w/cpp/container/vector/data to make handling the possibly-empty cases easier.

File: modules/phase_field/src/postprocessors/FauxGrainTracker.C [hunk 7]
```diff
@@ -34,16 +34,23 @@ FauxGrainTracker::~FauxGrainTracker()
 }
 
 Real
-FauxGrainTracker::getEntityValue(dof_id_type entity_id, FeatureFloodCount::FIELD_TYPE field_type, unsigned int var_idx) const
+FauxGrainTracker::getEntityValue(dof_id_type entity_id, FeatureFloodCount::FieldType field_type, unsigned int var_idx) const
 {
+  auto use_default = false;
```
Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FauxGrainTracker.C]: LOL, `auto` vs. `bool`.  OK bro

File: modules/phase_field/src/postprocessors/FeatureFloodCount.C [hunk 8]
```diff
@@ -467,129 +468,76 @@ FeatureFloodCount::mergeSets(bool use_periodic_boundary_info)
...
+  } // map loop
 
-      _partial_feature_sets[rank][map_num].clear();
+  /**
+   * All of the merges are complete and stored in a vector of lists. To make several
+   * of the sorting and tracking algorithms more straightforward, we will move these
+   * items into a vector of vectors instead.
+   */
+  _feature_count = 0;
+  for (auto map_num = decltype(_maps_size)(0); map_num < _maps_size; ++map_num)
```
Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]:
```
auto map_num = decltype(_maps_size)(0)
```
vs.
```
unsigned map_num = 0;
```
seems ridiculous to me.

**Comment by jwpeterson** [comment]
:+1:

File: framework/src/restart/DataIO.C (hunk 4 above)
Comment (jwpeterson) [inline framework/src/restart/DataIO.C]: I was referring to [this](http://stackoverflow.com/questions/16425338/is-it-safe-to-pass-stdstring-to-c-style-apis) which says that C++03 did not guarantee strings were contiguous in memory (although, how could they *not* be?) but can't vouch for its accuracy or my reading of it.

File: modules/phase_field/src/postprocessors/FeatureFloodCount.C (hunk 8 above)
Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: It's not ridiculous.  The type of `map_num` will now always stay in sync with the type of `_maps_size`... so you don't get into situations where `_maps_size` is changed to a `long unsigned int` but you forget to change `map_num` and your code is broken for large problems...

Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: The same problem is solved with a typedef.

Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: That's way worse.  You're promoting us to have millions of typedefs running around for each little thing?

I don't want to have to remember to use `some_other_index_type` for each line of code...

This code is explicit and self-explanatory.

Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: > I don't want to have to remember to use some_other_index_type for each line of code...

You're already doing that, it's just spelled "auto foo = decltype(bar)(0)" instead.

Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Nope - that line of code is the same regardless of what's on the right hand side.

vs having to remember "Oh yeah... this thing is a `dof_id_type`, this thing is a `element_id_type`, this thing is a `blah_id_type`"

Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: And the problem is... if you screw up and assign a `bar_id_type` to a `foo_id_type` they might be the same right now and not give any compiler warnings and work just fine so you would never know... and then later you change one of them and you have a bug.

_This_ line of code is foolproof.

Comment (jwpeterson) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: OK, I think I can see your point, but the syntax is so ugly... I just can't get behind it.

Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Yeah - I'm not the biggest fan of the syntax either.  We (me @permcody and @dschwen   ) already talked about this construction before.  I personally prefer:

`decltype(foo) bar = 0`

That is valid syntax and matches up better with what we're used to.  The problem is that sometimes `foo` is `const`... so this would actually make `bar` const as well and then you get a compile error on the `bar++`.

`auto bar = decltype(foo)(0)`

Doesn't have that issue.

You could do:

`decltype(std::remove_const(foo)) bar = 0` or somesuch... but that's deeply unsatisfying as well ;-)

`auto bar = decltype(foo)(0)` gets the job done and is simple (enough).

Comment (permcody) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: One of these days I'll figure out how to get rid of this whole "maps"
business so I can just use a range based for. Then I won't have this
problem. There are always going to be cases though were people need to
iterate over a range of integers and C++11 doesn't provide any clean ways
to just do that with an auto type...

Comment (friedmud) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Here's an interesting related read: https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

It's kind of where I'm headed...

Comment (roystgnr) [inline modules/phase_field/src/postprocessors/FeatureFloodCount.C]: Wait - Herb Sutter is still writing Guru of the Week?  I must have a decade of posts to catch up on...
