### PR TITLE
Fix piecewise linear derivatives

### LINKED ISSUE #15752: PiecewiseLinearBase::timeDerivative is incorrect if `axis` is specified
## Reason
If the `axis` parameter is set the function will be time independent and the derivative should return `0`.

## Design
Return `0` if `axis` is set. Implement `gradient`.

## Impact
Added capability.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #15752

### CODE REVIEW

File: framework/include/functions/PiecewiseLinearBase.h [hunk 1]
```diff
@@ -28,12 +28,13 @@ class PiecewiseLinearBase : public PiecewiseBase
...
-  virtual Real integral() const override;
-  virtual Real average() const override;
-  virtual void setData(const std::vector<Real> & x, const std::vector<Real> & y) override;
+  void initialSetup() override;
+  Real value(Real t, const Point & p) const override;
+  Real timeDerivative(Real t, const Point &) const override;
+  RealGradient gradient(Real, const Point & p) const override;
+  Real integral() const override;
+  Real average() const override;
+  void setData(const std::vector<Real> & x, const std::vector<Real> & y) override;
```
Comment (zachmprince) [inline framework/include/functions/PiecewiseLinearBase.h:37]: I think these should remain virtual for clarity. If you don't want derived classes to override, then use the `final` keyword.

**Review by zachmprince — DISMISSED** [review]

File: framework/include/functions/PiecewiseLinearBase.h (hunk 1 above)
Comment (dschwen) [reply framework/include/functions/PiecewiseLinearBase.h:37]: Virtual is implied when the override keyword is used.

Comment (dschwen) [reply framework/include/functions/PiecewiseLinearBase.h:37]: Sooo, you prefer the virtual keyword for clarity? My personal preference is to avoid redundant syntax consistently, but I can add it back in if you wan, @zachmprince

Comment (loganharbour) [inline framework/include/functions/PiecewiseLinearBase.h:37]:
```suggestion
  void initialSetup() final;
  Real value(Real t, const Point & p) const final;
  Real timeDerivative(Real t, const Point &) const final;
  RealGradient gradient(Real, const Point & p) const final;
  Real integral() const final;
  Real average() const final;
  void setData(const std::vector<Real> & x, const std::vector<Real> & y) final;
```

I suggest the best of both worlds per the previous discussion

**Review by loganharbour — CHANGES_REQUESTED** [review]

File: framework/include/functions/PiecewiseLinearBase.h (hunk 1 above)
Comment (dschwen) [reply framework/include/functions/PiecewiseLinearBase.h:37]: Huh?! Marking the methods final is a completely different issue. I'm not sure that's what we necessarily want. And I certainly don't want to incorporate such a design change into my PR. 

We can discuss whether we want to have a redundant `virtual` + `override` (per Zach) or go with the `override` only version (which I prefer).

Comment (loganharbour) [reply framework/include/functions/PiecewiseLinearBase.h:37]: Sorry - I didn't follow then. I thought you were trying to take them away. I prefer just `override` in this case.

Comment (dschwen) [reply framework/include/functions/PiecewiseLinearBase.h:37]: Ok, right now we're using `virtual` + `override` ~3800 times and `override` without `virtual` ~1000 times in moose. This is not the hill I want to die on, so I'll just put the virtual back.

Comment (dschwen) [reply framework/include/functions/PiecewiseLinearBase.h]: Didn't see you comment because I was stomping my feet and reluctantly put the `virtual` back :-D

It's nit a big deal, but for the sake of consistency we should probably come to a decision what to do in the moose codebase. But I suggest doing that in a separate issue. By default _not_ making this change in this PR, where it is not strictly necessary is the right thing IMO.

Comment (loganharbour) [reply framework/include/functions/PiecewiseLinearBase.h]: Hah - sounds good. Deferring to a later issue is the moose way, eh?

**Review by loganharbour — APPROVED** [review]
