### PR TITLE
Enhance element id interface

### LINKED ISSUE #15510: A subtle bug: when subapp uses cloned main mesh, it should not execute mesh modifiers
## Bug Description
When the main app asked the subapp to use its cloned mesh, the subapp should not execute any mesh modifiers but currently it still does.

## Steps to Reproduce
Use mesh modifiers in subapp and turn on cloned mesh in multiapp of the main app, we will see the mesh outputted by subapp is different from the main app. Considering mesh modifier is deprecated, we might just need to fix the code without adding tests.

## Impact
A subtle bug can be rarely triggered.

### LINKED ISSUE #15534: ElementIDInterface enhancements
## Reason
While converting our old element ID codes, some enhancements of `ElementIDInterface` are identified to be necessary. These enhancements include supporting element ID on sides and internal sides, element ID getters by name, gathering IDs on mesh blocks, etc.

## Design
`MooseMesh` will do some extra setups for managing element IDs. Element IDs need to be copied in `Assembly` at two more places for face and neighbor. `ElementIDInterface` will interact with `MooseMesh` and `Assembly` for the enhancement. Regression tests will be added. I will work on this issue and hopefully send in a PR very soon.

## Impact
Make element ID interface fully functioning.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #15534. A small commit included to close #15510 as well.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Anyone knows the quick solution of this doc error?
```
MooseDocs.commands.check (MainProcess): No documentation for /VectorPostprocessors/ElementCounterWithID.
    - The page should be located at /opt/civet/build_0/moose/test/doc/content/source/vectorpostprocessors/ElementCounterWithID.md.
    - It is possible to generate stub pages using './moosedocs.py check --generate'.
```
It is a test object and I guess we do not have to add a markdown file for it.

**Comment by zachmprince** [comment]
You need to register your test objects with `MooseTestApp` not `MooseApp`.

**Comment by YaqiWang** [comment]
Ahoh!

**Comment by YaqiWang** [comment]
I am expecting all tests will pass. This PR is ready for review. @permcody do you want to take a look?

File: framework/src/base/Assembly.C [hunk 1]
```diff
@@ -1622,6 +1630,11 @@ Assembly::reinitNeighbor(const Elem * neighbor, const std::vector<Point> & refer
     for (unsigned int qp = 0; qp < qrule->n_points(); qp++)
       _current_neighbor_volume += JxW[qp] * _coord_neighbor[qp];
   }
+
+  unsigned int n = _extra_elem_ids.size() - 1;
```
Comment (dschwen) [inline framework/src/base/Assembly.C:1634]: Why the `- 1`?

File: framework/src/base/Assembly.C [hunk 2]
```diff
@@ -1269,6 +1272,11 @@ Assembly::reinitFEFace(const Elem * elem, unsigned int side)
 
   if (_xfem != nullptr)
     modifyFaceWeightsDueToXFEM(elem, side);
+
+  unsigned int n = _extra_elem_ids.size() - 1;
+  for (unsigned int i = 0; i < n; ++i)
+    _extra_elem_ids[i] = _current_elem->get_extra_integer(i);
+  _extra_elem_ids[n] = _current_elem->subdomain_id();
```
Comment (dschwen) [inline framework/src/base/Assembly.C:1279]: Why do you copy the subdomain id into this `_extra_elem_ids` vector?

File: framework/src/base/Assembly.C [hunk 3]
```diff
@@ -763,8 +764,10 @@ Assembly::reinitFE(const Elem * elem)
     }
   }
 
-  for (unsigned int i = 0; i < _extra_elem_ids.size(); ++i)
+  unsigned int n = _extra_elem_ids.size() - 1;
+  for (unsigned int i = 0; i < n; ++i)
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/base/Assembly.C:768]: You could explicitly assign `n` type `std::size_t` if you want to make it clear that `n` is an unsigned type for indexing.

File: framework/src/base/Assembly.C [hunk 4]
```diff
@@ -1269,6 +1272,11 @@ Assembly::reinitFEFace(const Elem * elem, unsigned int side)
 
   if (_xfem != nullptr)
     modifyFaceWeightsDueToXFEM(elem, side);
+
+  unsigned int n = _extra_elem_ids.size() - 1;
+  for (unsigned int i = 0; i < n; ++i)
+    _extra_elem_ids[i] = _current_elem->get_extra_integer(i);
```
Comment (lindsayad) [inline framework/src/base/Assembly.C:1278]: Same recommended indexing idiom as above

File: framework/src/base/Assembly.C [hunk 5]
```diff
@@ -1622,6 +1630,11 @@ Assembly::reinitNeighbor(const Elem * neighbor, const std::vector<Point> & refer
     for (unsigned int qp = 0; qp < qrule->n_points(); qp++)
       _current_neighbor_volume += JxW[qp] * _coord_neighbor[qp];
   }
+
+  unsigned int n = _extra_elem_ids.size() - 1;
+  for (unsigned int i = 0; i < n; ++i)
+    _neighbor_extra_elem_ids[i] = _current_neighbor_elem->get_extra_integer(i);
```
Comment (lindsayad) [inline framework/src/base/Assembly.C:1636]: And one last time

File: framework/src/vectorpostprocessors/InterfaceVectorPostprocessor.C [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+//*
+//* All rights reserved, see COPYRIGHT for full restrictions
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "InterfaceVectorPostprocessor.h"
+
+defineLegacyParams(InterfaceVectorPostprocessor);
```
Comment (lindsayad) [inline framework/src/vectorpostprocessors/InterfaceVectorPostprocessor.C:12]: Please remove

File: test/include/vectorpostprocessors/ElementCounterWithID.h [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "ElementVectorPostprocessor.h"
+
+class ElementCounterWithID;
+
+template <>
+InputParameters validParams<ElementCounterWithID>();
```
Comment (lindsayad) [inline test/include/vectorpostprocessors/ElementCounterWithID.h:17]: Remove

File: test/include/vectorpostprocessors/InterfaceElementCounterWithID.h [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceVectorPostprocessor.h"
+
+class InterfaceElementCounterWithID;
+
+template <>
+InputParameters validParams<InterfaceElementCounterWithID>();
```
Comment (lindsayad) [inline test/include/vectorpostprocessors/InterfaceElementCounterWithID.h:17]: Remove

File: test/include/vectorpostprocessors/InternalSideElementCounterWithID.h [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InternalSideVectorPostprocessor.h"
+
+class InternalSideElementCounterWithID;
+
+template <>
+InputParameters validParams<InternalSideElementCounterWithID>();
```
Comment (lindsayad) [inline test/include/vectorpostprocessors/InternalSideElementCounterWithID.h:17]: remove

File: test/include/vectorpostprocessors/SideElementCounterWithID.h [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "SideVectorPostprocessor.h"
+
+class SideElementCounterWithID;
+
+template <>
+InputParameters validParams<SideElementCounterWithID>();
```
Comment (lindsayad) [inline test/include/vectorpostprocessors/SideElementCounterWithID.h:17]: remove

File: test/src/vectorpostprocessors/ElementCounterWithID.C [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "ElementCounterWithID.h"
+
+registerMooseObject("MooseTestApp", ElementCounterWithID);
+
+defineLegacyParams(ElementCounterWithID);
```
Comment (lindsayad) [inline test/src/vectorpostprocessors/ElementCounterWithID.C:14]: remove

File: test/src/vectorpostprocessors/InterfaceElementCounterWithID.C [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "InterfaceElementCounterWithID.h"
+
+registerMooseObject("MooseTestApp", InterfaceElementCounterWithID);
+
+defineLegacyParams(InterfaceElementCounterWithID);
```
Comment (lindsayad) [inline test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:14]: remove

File: test/src/vectorpostprocessors/InterfaceElementCounterWithID.C [hunk 13]
```diff
@@ -0,0 +1,87 @@
...
+void
+InterfaceElementCounterWithID::finalize()
+{
+  for (auto & pair : _counters)
+  {
+    gatherSum(pair.second.first);
+    gatherSum(pair.second.second);
+  }
+
+  unsigned int i = 0;
```
Comment (lindsayad) [inline test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:68]: The indexing argument for `std::vector::operator[]` is typically `std::size_t`. In general we should often be using `std::size_t` instead of `unsigned int` for type matching. I know that libmesh has a lot of APIs involving `unsigned int` so this is definitely not a hard and fast rule.

Comment (lindsayad) [reply test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:68]: Obviously `unsigned int` is straightforwardly converted to `std::size_t` so it's not required that you change this

Comment (lindsayad) [reply test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:68]: I guess the only concern would be if you ever had more unique ids than can be represented by `unsigned int`

File: test/tests/vectorpostprocessors/element_id_counters/tests [hunk 14]
```diff
@@ -0,0 +1,35 @@
...
+    type = 'CSVDiff'
+    input = 'interface_element_counter.i'
+    csvdiff = 'interface_element_counter_out_elem_counter_0001.csv'
+    requirement = 'The system shall have the ability to retrieve element integers of attached elements on both sides when visiting internal interfaces'
+  []
+  [element_counter_with_ids_on_internal_side]
+    type = 'CSVDiff'
+    input = 'internal_side_element_counter.i'
+    csvdiff = 'internal_side_element_counter_out_elem_counter_0001.csv'
+    requirement = 'The system shall have the ability to retrieve element integers of attached elements on both sides when visiting all internal sides'
```
Comment (lindsayad) [inline test/tests/vectorpostprocessors/element_id_counters/tests:33]: I think @permcody told me we're supposed to have periods at the end of our requirements. Otherwise I really like these requirements.

**Review by lindsayad — CHANGES_REQUESTED** [review]
Basically all just syntactic suggestions. Overall concepts look good to me

File: framework/src/base/Assembly.C (hunk 2 above)
Comment (YaqiWang) [reply framework/src/base/Assembly.C:1279]: Because we want to use the same postprocessing objects for handling either subdomain ID or something ID like material ID. With subdomain ID in this, we can simply switch the operation by using a different element ID index.

File: framework/include/interfaces/ElementIDInterface.h [hunk 15]
```diff
@@ -26,22 +28,107 @@ class ElementIDInterface
...
+   */
+  bool areElemIDsIdentical(const std::string & id_name1, const std::string & id_name2) const
+  {
+    return _mesh->areElemIDsIdentical(id_name1, id_name2);
+  }
+
+  /**
+   * Return all the unique element IDs for an element integer with its index on the entire domain
+   */
+  std::set<dof_id_type> getAllElemIDs(unsigned int elem_id_index) const
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/include/interfaces/ElementIDInterface.h:109]: Yep, plus this function is probably not called very often.

File: framework/include/base/Assembly.h [hunk 16]
```diff
@@ -299,6 +299,14 @@ class Assembly
    */
   const dof_id_type & extraElemID(unsigned int id) const { return _extra_elem_ids[id]; }
 
+  /**
+   * Returns an integer ID of the current element given the index associated with the integer
+   */
+  const dof_id_type & extraElemIDNeighbor(unsigned int id) const
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/include/base/Assembly.h:305]: Nope, this need to be returned by reference. It is like `_u`, objects use it but without modifying or setting it. It is set by `Assembly`.

File: framework/src/mesh/MooseMesh.C [hunk 17]
```diff
@@ -2832,7 +2915,7 @@ MooseMesh::getSubdomainInterfaceBoundaryIds(SubdomainID subdomain_id) const
 }
 
 std::set<SubdomainID>
-MooseMesh::getBoundaryConnectedBlocks(const BoundaryID bid) const
+MooseMesh::getBoundaryConnectedBlocks(BoundaryID bid) const
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/mesh/MooseMesh.C:2918]: The problem is that the argument is passed in by value, so const here does not make sense. `bid` is not going to be modified by the function anyway. I think this is actually a good argument for c++ developers. Removing this is also making it consistent with several other places.

File: test/src/vectorpostprocessors/ElementCounterWithID.C (hunk 11 above)
Comment (YaqiWang) [reply test/src/vectorpostprocessors/ElementCounterWithID.C:14]: Will do.

File: test/src/vectorpostprocessors/InterfaceElementCounterWithID.C (hunk 13 above)
Comment (YaqiWang) [reply test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:68]: That will requires the mesh contains 4G elements first, which will probably not happen in our life time, ;-)

Comment (YaqiWang) [reply test/src/vectorpostprocessors/InterfaceElementCounterWithID.C:68]: I can change it to size_t anyway.

File: test/src/vectorpostprocessors/InternalSideElementCounterWithID.C [hunk 18]
```diff
@@ -0,0 +1,79 @@
...
+    ++_counters[_neighbor_id];
+  }
+}
+
+void
+InternalSideElementCounterWithID::finalize()
+{
+  gatherSum(_counters);
+
+  unsigned int i = 0;
```
Comment (YaqiWang) [inline test/src/vectorpostprocessors/InternalSideElementCounterWithID.C:63]: Will use size_t here as well.

File: framework/src/base/Assembly.C [hunk 19]
```diff
@@ -145,7 +145,8 @@ Assembly::Assembly(SystemBase & sys, THREAD_ID tid)
   // _coord_msm
   _fe_msm->get_xyz();
 
-  _extra_elem_ids.resize(_mesh.getMesh().n_elem_integers());
+  _extra_elem_ids.resize(_mesh.getMesh().n_elem_integers() + 1);
+  _neighbor_extra_elem_ids.resize(_mesh.getMesh().n_elem_integers() + 1);
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/base/Assembly.C:149]: The last extra entry is for subdomain ID, which is technically an element ID. I want to push it into these vectors so that we can switch postprocessings from different element IDs including subdomain ID easily.

**Comment by YaqiWang** [comment]
@lindsayad your comments are addressed.

File: framework/include/base/Assembly.h (hunk 16 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/base/Assembly.h:305]: :+1:

File: framework/src/mesh/MooseMesh.C (hunk 17 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/mesh/MooseMesh.C:2913]: `const` absolutely still makes sense for pass-by-value. It's the same reason you write `const` for any constructed object in a code-block. It represents a contract that there's no reason to modify the object. I agree that it will have no affect on the caller of this method since it's pass-by-value, but this doesn't mean there isn't value. I refer you here: https://stackoverflow.com/a/117557/4493669

File: framework/src/base/Assembly.C (hunk 19 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/base/Assembly.C:149]: Sounds fine. Just make sure this is documented clearly somewhere

File: framework/src/mesh/MooseMesh.C (hunk 17 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/mesh/MooseMesh.C:2913]: > Removing this is also making it consistent with several other places.

If anything those other places should be updated to be `const` (in the .C file), instead of the other way around

[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/src/mesh/MooseMesh.C:2913]: This won't be the the hill that I die on; I'll accept an acknowledgement that there's value in the suggested changes :smile:

File: framework/src/base/Assembly.C (hunk 2 above)
Comment (dschwen) [reply framework/src/base/Assembly.C:1279]: But keep in mind that you are adding this copy operation to every element and face reinit, whether extra IDs are used or not. I'm not convinced that a minor convenience in postprocessing is worth that extra overhead.

File: framework/src/mesh/MooseMesh.C (hunk 17 above)
[the remark this answers is not in the document]
Comment (dschwen) [reply framework/src/mesh/MooseMesh.C:2913]: Just undo this change

[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/mesh/MooseMesh.C:2913]: Ok, I will revert this change.

File: framework/src/base/Assembly.C (hunk 2 above)
Comment (YaqiWang) [reply framework/src/base/Assembly.C:1279]: The only extra cost is one integer copy though. I initially did not have this and realized that my objects are super ugly. Another argument is that we copied the subdomain IDs anyway in `Assembly`. With the copying here, we can potentially remove the other copying. I do not want to introduce extra operations in the critical codes as well. But here I have to do this considering the significant simplifications in down-stream objects.

**Comment by YaqiWang** [comment]
@dschwen I hope you are convinced the copying of subdomain ID is useful. Think of a vector postprocessor integrating a variable over elements based on an element ID or the subdomain ID. If we do not have the copying, you can imagine how the code will look like. About the const argument passed by value, I only made the five functions (next to each other in a group) consistent. I agree it does have value to the callee.

File: framework/include/mesh/MooseMesh.h [hunk 20]
```diff
@@ -932,7 +932,7 @@ class MooseMesh : public MooseObject, public Restartable, public PerfGraphInterf
    * @param subdomain_id The subdomain ID you want to get the boundary ids for.
    * @return All boundary IDs connected to elements in the give
    */
-  const std::set<BoundaryID> & getSubdomainBoundaryIds(SubdomainID subdomain_id) const;
+  const std::set<BoundaryID> & getSubdomainBoundaryIds(const SubdomainID subdomain_id) const;
```
Comment (lindsayad) [inline framework/include/mesh/MooseMesh.h:935]: I probably didn't make it clear that I just wanted the `const` label on the parameter in the `.C` file as having it in the `.h` makes it harder to introduce some API changes (e.g. if we wanted to actually pass by non-const reference sometime in the future). But I don't imagine that we'll actually want to do that, and I'm not going to make you do more work if you don't want to when I motivated you to make the change

File: framework/src/base/Assembly.C [hunk 21]
```diff
@@ -763,8 +764,10 @@ Assembly::reinitFE(const Elem * elem)
     }
   }
 
-  for (unsigned int i = 0; i < _extra_elem_ids.size(); ++i)
+  auto n = _extra_elem_ids.size() - 1;
+  for (auto i : make_range(n))
     _extra_elem_ids[i] = _current_elem->get_extra_integer(i);
+  _extra_elem_ids[n] = _current_elem->subdomain_id();
```
Comment (lindsayad) [inline framework/src/base/Assembly.C:770]: :+1:

File: framework/src/mesh/MooseMesh.C [hunk 22]
```diff
@@ -897,6 +968,7 @@ MooseMesh::cacheInfo()
   TIME_SECTION(_cache_info_timer);
   CONSOLE_TIMED_PRINT("Caching mesh information");
 
+  _sub_to_neighbor_subs.clear();
```
Comment (lindsayad) [inline framework/src/mesh/MooseMesh.C:971]: Thanks for the rename!

**Review by lindsayad — APPROVED** [review]
This LGTM unless @YaqiWang wants to change the `const` parameter labels in the header or unless @dschwen still wants changes

File: framework/include/mesh/MooseMesh.h (hunk 20 above)
Comment (YaqiWang) [reply framework/include/mesh/MooseMesh.h:935]: Is it possible to have the function signature in C file different with the  one in the header? But I think keep it consistent is preferred. Even the argument is marked as non-const, I guess a const caller in a class can still call it with its member variables as the argument. So either way should be fine. But I think const indeed does not hurt. This is a big argument I do not want to get into though in this PR. This is good.

Comment (lindsayad) [reply framework/include/mesh/MooseMesh.h:935]: Yes you can: https://stackoverflow.com/q/117293/4493669
