### PR TITLE
Fixed iteration post-processors for Eigenvalue executioner

### LINKED ISSUE #32505: NumNonlinearIterations postprocessor does not work with Eigenvalue executioner
### Motivation

When solving an eigenvalue problem with `Eigenvalue` executioner, `NumNonlinearIterations` will not report the correct number of iterations.

### Design

`Eigenvalue` interfaces SLEPc for the eigenvalue calculation. When it uses PJFNK to solve the eigenvalue problem, it has Newton iterations, thus should report the number of Newton (nonlinear) iterations. This can be achieved by overriding `EigenProblem::nNonlinearIterations` function. It is noted that other solvers in SLEPc could be used by `Eigenvalue`, whether we should make `EigenProblem::nNonlinearIterations` return the number of iterations will be an open question.

### Impact

A new improved functionality.

### PR DESCRIPTION
**Pull request by joshuahansel**
This PR:
- improves doc for `NumNonlinearIterations`
- Makes `NumNonlinearIterations` and `NumLinearIterations` work for `Eigenvalue` executioner with nonlinear solve types. For other types, throw error if someone tries to get those iteration counts.

Closes #32505

### CODE REVIEW

File: framework/src/systems/NonlinearEigenSystem.C [hunk 1]
```diff
@@ -296,6 +310,28 @@ NonlinearEigenSystem::solve()
     solution().restore_subvector(std::move(subvec), _eigen_sys.local_non_condensed_dofs_vector);
 }
 
+unsigned int
+NonlinearEigenSystem::nNonlinearIterations() const
+{
+  if (!_time_integrators.empty())
+    mooseError("Not implemented for time integrators.");
+  if (!_eigen_problem.isNonlinearEigenvalueSolver(number()))
+    mooseError("Only implemented for nonlinear eigenvalue solvers.");
```
Comment (GiudGiud) [inline framework/src/systems/NonlinearEigenSystem.C:319]: what prompted these checks?

Comment (joshuahansel) [reply framework/src/systems/NonlinearEigenSystem.C:319]: The first one because time integrators would require some additional changes. This is what is done in `NonlinearSystem::solve()`, for reference:
```
  if (!_time_integrators.empty())
  {
    _n_iters = _time_integrators.front()->getNumNonlinearIterations();
    _n_linear_iters = _time_integrators.front()->getNumLinearIterations();
  }
  else
  {
    _n_iters = _nl_implicit_sys.n_nonlinear_iterations();
    _n_linear_iters = _nl_implicit_sys.nonlinear_solver->get_total_linear_iterations();
  }
```
but the time integrators assume the use of `NonlinearImplicitSystem`:
```
unsigned int
TimeIntegrator::getNumNonlinearIterationsLastSolve() const
{
  return _nonlinear_implicit_system->n_nonlinear_iterations();
}
```

The second one because we use `getSNES()` to get the iteration counts, which would give an error for that condition.

**Review by GiudGiud — APPROVED** [review]

**Comment by NamjaeChoi** [comment]
Is this related with the failure in https://civet.inl.gov/job/3676168/?

**Comment by GiudGiud** [comment]
Took care of it. Thanks for reporting!
