### PR TITLE
Throw MooseException when NaN sampled in LinearInterpolation

### LINKED ISSUE #20831: Return NaN instead of error when NaN sampled in LinearInterpolation
## Reason
In `LinearInterpolation`, when the sample point is a NaN value, an error is thrown that says "Unreachable". A simulation should be able to continue when a NaN value is sampled.

## Design
This would return a NaN value `LinearInterpolation` when the sample point is NaN, allowing the simulation to cut the time step size and continue.

## Impact
This should not affect existing results.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #20831

### CODE REVIEW

File: framework/src/utils/LinearInterpolation.C [hunk 1]
```diff
@@ -75,8 +75,8 @@ LinearInterpolation::sample(const T & x) const
     if (x >= _x[i] && x < _x[i + 1])
       return _y[i] + (_y[i + 1] - _y[i]) * (x - _x[i]) / (_x[i + 1] - _x[i]);
 
-  mooseError("Unreachable!");
-  throw std::out_of_range("Unreachable");
+  // If this point is reached, x must be a NaN.
+  throw MooseException("Sample point in LinearInterpolation is a NaN.");
```
Comment (dschwen) [inline framework/src/utils/LinearInterpolation.C:79]:
```suggestion
  tmooseException("Sample point in LinearInterpolation is a NaN.");
```

**Review by GiudGiud — APPROVED** [review]
