### PR TITLE
Only print convergence reason if failed

### LINKED ISSUE #16739: Only print PETSc convergence reason when failed by default
## Reason
Most pressing reason is that we have too verbose of output in multiapp settings.

## Design
Leverage new PETSc capability to only print convergence reasons when diverged.

## Impact
Cleaner output, especially for multi-apps

### PR DESCRIPTION
**Pull request by lindsayad**
Although this can be overridden by user specification in the input file
(and on the command line)

Closes #16739

### CODE REVIEW

**Comment by lindsayad** [comment]
@friedmud just alerting you to step 1 of the plan to reduce the convergence reason output

File: framework/src/utils/PetscSupport.C [hunk 1]
```diff
@@ -790,6 +795,18 @@ storePetscOptions(FEProblemBase & fe_problem, const InputParameters & params)
     }
   }
 
+#if !PETSC_VERSION_LESS_THAN(3, 14, 0)
+  for (const auto & reason_flag : reason_flags)
+    // Was the option already found in PetscOptions::flags? Or does it exist in PetscOptions::inames
```
Comment (fdkong) [inline framework/src/utils/PetscSupport.C:800]: You might not need this sentence anymore?

`Was the option already found in PetscOptions::flags?`

**Review by fdkong — CHANGES_REQUESTED** [review]
Minor query

File: framework/src/utils/PetscSupport.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/utils/PetscSupport.C:800]: I think I do. Because a user may put `-snes_converged_reason` or `-ksp_converged_reason` in `petsc_options` in which case I do not want to add `-snes_converged_reason ::failed` or `-ksp_converged_reason ::failed` because the user has indicated they want the convergence reason all the time (and in general we do not want duplicate options)

Comment (lindsayad) [reply framework/src/utils/PetscSupport.C:800]: Or am I misunderstanding your question?

Comment (fdkong) [reply framework/src/utils/PetscSupport.C:800]: What I meant was that: I did not see you touch `po.flags` within this loop. That indicates you did not touch `PetscOptions::flags?`. 

From my understanding, you already handled `po.flags` at line 669.

If you did not touch `po.flags`, then you do not need the comment 

`Was the option already found in PetscOptions::flags?`

Comment (lindsayad) [reply framework/src/utils/PetscSupport.C:800]: Oh I see your question. I think the comment is still relevant though: `!reason_flag.first` on line 802 is telling us whether the option was already found in `PetscOptions::flags`

Comment (fdkong) [reply framework/src/utils/PetscSupport.C:800]: Oh, I understood now. Thanks

**Review by fdkong — APPROVED** [review]

**Comment by fdkong** [comment]
I will work on the second  step
