### PR TITLE
Fix a bug in the calculation of stress_free_strain_increment at the first time step

### LINKED ISSUE #7795: fix a bug in ComputeThermalExpansionEigenStrain
### Description of the enhancement or error report
The old material class has a logic bug while using the incremental formulation, i.e., the stress_free_reference_temperature should be used only for the first step but was set to zero.

### Identified impact
Some tests based on this material class need to be regolded.

### PR DESCRIPTION
**Pull request by hchen139**
- Fixed the bug in calculation of stress_free_strain_increment for the first time step
- Loosen the tolerance and regolded the some affected test cases
- closes #7795

### CODE REVIEW

**Comment by hchen139** [comment]
@bwspenc @sapitts This is the fix to the calculation of stress_free_strain_increment at the first time step.

File: modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C [hunk 1]
```diff
@@ -40,8 +40,7 @@ ComputeThermalExpansionEigenStrain::computeQpStressFreeStrain()
 
   if (!_has_incremental_strain || _step_one)
     old_temp = _stress_free_reference_temperature;
-
```
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C]: This is heading the right way, but I think we should make more changes to this. I think this should behave the way the solid_mechanics version does, although others may disagree. `stress_free_reference_temperature` should be called `stress_free_temperature` to avoid confusion with the reference temperature, which is something else, and which I plan to add shortly. It also shouldn't have a default in my opinion.

Comment (hchen139) [inline modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C]: @dschwen Could you take a look at the failed test in MARMOT? Thanks.

File: modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C [hunk 2]
```diff
@@ -12,9 +12,10 @@ InputParameters validParams<ComputeThermalExpansionEigenStrain>()
 {
   InputParameters params = validParams<ComputeStressFreeStrainBase>();
   params.addClassDescription("Computes Eigenstrain due to thermal expansion");
-  params.addCoupledVar("temperature", 273, "Coupled temperature in units of Kelvin");
+  params.addCoupledVar("temperature", "Coupled temperature in K");
```
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C]: It shouldn't have the "in K" part. By removing the 273 default, it is now completely unit system independent.

**Review by bwspenc — APPROVED** [review]
Aside from the minor comment, I think this is good to go.

File: modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C (hunk 2 above)
Comment (hchen139) [inline modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenStrain.C]: @bwspenc Comment was addressed.

**Comment by bwspenc** [comment]
@hchen139 If you rebase your branch against devel, you'll see that the
modules/tensor_mechanics/tests/thermal_expansion/constant_expansion_coeff_restart.i test fails as I was just discussing with you.  You can fix it by changing the name of the `thermal_expansion` block to `thermal_expansion_strain` to be compatible with a change that was just made to the non-restart version of this test. That change must not have affected the test when it was still buggy without your fix.  Make that change and push your update.

The Marmot test is a minor change due to the parameter name change here. We have to merge this first.

**Comment by bwspenc** [comment]
@dschwen I think this is ready to go now. I can fix the Marmot test as soon as this is merged.

**Review by dschwen — APPROVED** [review]
