### PR TITLE
Report errors when capabilities are unknown by default

### LINKED ISSUE #32416: Fail tests when capabilities are not found
### Motivation

Currently, if unknown capabilities are found in `required_capabilities` the result will just be skipped. But in reality we want things to fail if we find capabilities that we don't know about (assuming they're not false).

### Design

Throw errors when checking capabilities when they do not exist (by default).

### Impact

New capability. Will reduce errors when producing test specs.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #32416

#### App patches

- [x] https://github.inl.gov/ncrc/blue_crab/pull/357
- [x] https://github.inl.gov/ncrc/grizzly/pull/821
- [x] https://github.com/idaholab/magpie/pull/513

### CODE REVIEW

File: framework/include/base/CapabilityRegistry.h [hunk 1]
```diff
@@ -125,8 +123,9 @@ class CapabilityRegistry
   /**
    * Checks if a set of requirements is satisified by the capabilities
    *
-   * @param capabilities The registry that contains the capabilities
    * @param requirements The requirement string
+   * @param certain Whether or not the capabilites must be certain, that is,
```
Comment (GiudGiud) [inline framework/include/base/CapabilityRegistry.h:127]:
```suggestion
   * @param all_known Whether or not the capabilites must be certain, that is,
```

File: framework/include/base/CapabilityRegistry.h [hunk 2]
```diff
@@ -149,7 +148,7 @@ class CapabilityRegistry
    * See the description for CheckState for more information on why a
    * certain state would be returned.
    */
-  CheckResult check(std::string requirements) const;
+  CheckResult check(std::string requirements, const bool certain = true) const;
```
Comment (GiudGiud) [inline framework/include/base/CapabilityRegistry.h:151]:
```suggestion
  CheckResult check(std::string requirements, const bool all_known = true) const;
```

File: framework/src/base/CapabilityRegistry.C [hunk 3]
```diff
@@ -82,7 +83,7 @@ checkException(const peg::SemanticValues & vs,
 }
 
 CapabilityRegistry::CheckResult
-CapabilityRegistry::check(std::string requirements) const
+CapabilityRegistry::check(std::string requirements, const bool certain /* = true */) const
```
Comment (GiudGiud) [inline framework/src/base/CapabilityRegistry.C:86]:
```suggestion
CapabilityRegistry::check(std::string requirements, const bool all_known /* = true */) const
```

File: framework/src/base/CapabilityRegistry.C [hunk 4]
```diff
@@ -115,6 +123,12 @@ CapabilityRegistry::check(std::string requirements) const
   if (!static_cast<bool>(parser))
     throw CapabilityException("Capabilities parser build failure.");
 
+  // Keep track of unknown capabilities in the event that
+  // the check must be certain
```
Comment (GiudGiud) [inline framework/src/base/CapabilityRegistry.C:127]:
```suggestion
  // the check must already know of all the capabilities
```

File: test/tests/test_harness/missing_capabilities [hunk 5]
```diff
@@ -0,0 +1,7 @@
+[Tests]
+  [test]
```
Comment (GiudGiud) [inline test/tests/test_harness/missing_capabilities:2]: missing test metadata?

File: unit/src/CapabilitiesTest.C [hunk 6]
```diff
@@ -174,16 +174,15 @@ TEST_F(CapabilitiesTest, mooseAppCheckRequiredCapabilities)
...
-    auto app = AppFactory::create("MooseUnitApp", {"--required-capabilities='foo!?'"});
-    EXPECT_MOOSEERROR_MSG_CONTAINS(
-        app->run(), "--required-capablities: Capability statement '!': unknown operator.");
-  }
+  EXPECT_MOOSEERROR_MSG_CONTAINS(
+      AppFactory::create("MooseUnitApp", {"--required-capabilities='foo!?'"})->run(),
+      "--required-capablities: Capability statement '!': unknown operator.");
 
-  // Unknown state
+  // Non-registered capabilities are allowed
```
Comment (GiudGiud) [inline unit/src/CapabilitiesTest.C:181]: why a non zero exit code if it's allowed

File: python/TestHarness/TestHarness.py [hunk 7]
```diff
@@ -510,6 +512,25 @@ def augment(*args, **kwargs):
         if options.minimal_capabilities:
             augment("platform", util.getPlatform(), "Operating system", None, True)
 
+        # Add extra capabilities that are known even though they might not
+        # exist (if they are not set by the app). This is needed in specific
+        # when testing against known applications. For example, in the
+        # fluid_properties module, we check against "airapp". We don't want
+        # to error when "airapp" doesn't exist in the app because we know
+        # that it could actually be false.
```
Comment (GiudGiud) [inline python/TestHarness/TestHarness.py:520]:
```suggestion
        # that it could be fine, e.g. air fluid properties are a legitimate object for FPapp
```

File: python/pycapabilities/_pycapabilities.C [hunk 8]
```diff
@@ -374,20 +482,26 @@ Capabilities_check(CapabilitiesObject * self, PyObject * args, PyObject * kwargs
 {
   // Parse arguments
   const char * requirement = nullptr;
+  PyObject * certain = Py_True;
   PyObject * add_capabilities = Py_None;
   PyObject * negate_capabilities = Py_None;
   static const char * kwlist[] = {
-      "requirement", "add_capabilities", "negate_capabilities", nullptr};
+      "requirement", "certain", "add_capabilities", "negate_capabilities", nullptr};
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.C:489]:
```suggestion
  PyObject * all_capabilities_known = Py_True;
PyObject * add_capabilities = Py_None;
PyObject * negate_capabilities = Py_None;
static const char * kwlist[] = {
      "requirement", "all_capabilities_known", "add_capabilities", "negate_capabilities", nullptr};
```

File: python/pycapabilities/_pycapabilities.C [hunk 9]
```diff
@@ -374,20 +482,26 @@ Capabilities_check(CapabilitiesObject * self, PyObject * args, PyObject * kwargs
...
   if (!PyArg_ParseTupleAndKeywords(args,
                                    kwargs,
-                                   "s|OO",
+                                   "s|OOO",
                                    const_cast<char **>(kwlist),
                                    &requirement,
+                                   &certain,
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.C:495]:
```suggestion
                                   &all_capabilities_known,
```

File: python/pycapabilities/_pycapabilities.C [hunk 10]
```diff
@@ -374,20 +482,26 @@ Capabilities_check(CapabilitiesObject * self, PyObject * args, PyObject * kwargs
...
                                    &add_capabilities,
                                    &negate_capabilities))
-    return returnPythonError(PyExc_ValueError,
-                             "Capabilities.check(requirement: str, add_capabilities: "
-                             "Optional[dict] = None, negate_capabilities: Iterable[str]] = None)");
+    return returnPythonError(
+        PyExc_ValueError,
+        "Capabilities.check(requirement: str, certain: bool = True, add_capabilities: "
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.C:500]:
```suggestion
        "Capabilities.check(requirement: str, all_capabilities_known: bool = True, add_capabilities: "
```

File: python/pycapabilities/_pycapabilities.C [hunk 11]
```diff
@@ -374,20 +482,26 @@ Capabilities_check(CapabilitiesObject * self, PyObject * args, PyObject * kwargs
...
+        "Optional[dict] = None, negate_capabilities: Iterable[str]] = None)");
+
+  if (certain != Py_True && certain != Py_False)
+    return returnPythonError(PyExc_TypeError, "certain must be a bool");
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.C:504]:
```suggestion
  if (all_capabilities_known != Py_True && all_capabilities_known != Py_False)
    return returnPythonError(PyExc_TypeError, "all_capabilities_known must be a bool");
```

File: python/pycapabilities/_pycapabilities.C [hunk 12]
```diff
@@ -478,34 +592,20 @@ Capabilities_check(CapabilitiesObject * self, PyObject * args, PyObject * kwargs
...
-      return nullptr;
-
-    PyObject * checkstate_obj = PyObject_CallFunction(checkstate, "l", result.state);
-    Py_DECREF(checkstate);
-
-    return Py_BuildValue("(NNN)",
-                         checkstate_obj,
-                         PyUnicode_FromString(result.reason.c_str()),
-                         PyUnicode_FromString(result.doc.c_str()));
+    const auto result = registry.check(requirement, certain == Py_True);
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.C:598]:
```suggestion
    const auto result = registry.check(requirement, all_capabilities_known == Py_True);
```

File: python/pycapabilities/_pycapabilities.pyi [hunk 13]
```diff
@@ -59,9 +65,10 @@ class Capabilities:
     def check(
         self,
         requirement: str,
+        certain: bool = True,
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.pyi:68]:
```suggestion
        all_capabilities_known: bool = True,
```

File: python/pycapabilities/_pycapabilities.pyi [hunk 14]
```diff
@@ -78,19 +85,17 @@ class Capabilities:
 
         Optional Parameters
         -------------------
+        certain : bool
```
Comment (GiudGiud) [inline python/pycapabilities/_pycapabilities.pyi:88]:
```suggestion
        all_capabilities_known : bool
```

File: unit/src/CapabilityRegistryTest.C [hunk 15]
```diff
@@ -280,6 +311,73 @@ TEST(CapabilityRegistryTest, checkParseFail)
 #undef CAP_CHECK_EXPECT_EQ
 #undef CAP_CHECK_EXPECT_ERROR
 
+/// Test CapabilityRegistry::check with certain capabilities
+TEST(CapabilityRegistryTest, checkCertain)
```
Comment (GiudGiud) [inline unit/src/CapabilityRegistryTest.C:315]:
```suggestion
/// Test CapabilityRegistry::check with known or unknown capabilities
TEST(CapabilityRegistryTest, checkKnown)
```

File: unit/src/CapabilityRegistryTest.C [hunk 16]
```diff
@@ -280,6 +311,73 @@ TEST(CapabilityRegistryTest, checkParseFail)
...
+{
+  CapabilityRegistry registry;
+
+  // Unknown bool capabilities
+  // No error with default certain=true
```
Comment (GiudGiud) [inline unit/src/CapabilityRegistryTest.C]:
```suggestion
  // No error with default all_capabilities_known=true
```

Comment (GiudGiud) [reply unit/src/CapabilityRegistryTest.C]: this test has an error though?

File: unit/src/CapabilityRegistryTest.C [hunk 17]
```diff
@@ -280,6 +311,73 @@ TEST(CapabilityRegistryTest, checkParseFail)
...
+    registry.check("noexist1 & !noexist2");
+    FAIL() << "UnknownCapabilitiesException not thrown";
+  }
+  catch (const Moose::UnknownCapabilitiesException & e)
+  {
+    EXPECT_EQ(std::string(e.what()), "The following capabilities are unknown: noexist1, noexist2");
+    const std::vector<std::string> unknown_capabilities{"noexist1", "noexist2"};
+    EXPECT_EQ(e.unknown_capabilities, unknown_capabilities);
+  }
+  // Possible state with certain=false
```
Comment (GiudGiud) [inline unit/src/CapabilityRegistryTest.C:332]: what do you mean by "possible" here? as in the opposite of certain?

File: framework/include/base/CapabilityRegistry.h (hunk 1 above)
Comment (loganharbour) [reply framework/include/base/CapabilityRegistry.h:127]: the "certain" verbiage aligns with the name of the resulting state:

```
  enum CheckState
  {
    CERTAIN_FAIL = 0,
    POSSIBLE_FAIL = 1,
    UNKNOWN = 2,
    POSSIBLE_PASS = 3,
    CERTAIN_PASS = 4
  };
```

I'd prefer to keep it

File: framework/include/base/CapabilityRegistry.h (hunk 2 above)
Comment (loganharbour) [reply framework/include/base/CapabilityRegistry.h:151]: Same as above

File: test/tests/test_harness/missing_capabilities (hunk 5 above)
Comment (loganharbour) [reply test/tests/test_harness/missing_capabilities:2]: This is a different test spec (not a file named `tests`) used for the test harness. The sqa component comes from the actual tests that under the hood run the test harness again. No metadata needed.

File: framework/src/base/CapabilityRegistry.C (hunk 3 above)
Comment (loganharbour) [reply framework/src/base/CapabilityRegistry.C:86]: Same as above

File: framework/src/base/CapabilityRegistry.C (hunk 4 above)
Comment (loganharbour) [reply framework/src/base/CapabilityRegistry.C:127]: Same as above

File: framework/include/base/CapabilityRegistry.h (hunk 1 above)
Comment (dschwen) [reply framework/include/base/CapabilityRegistry.h:127]: Yeah, please do not introduce inconsistent language here.

File: unit/src/CapabilitiesTest.C (hunk 6 above)
Comment (loganharbour) [reply unit/src/CapabilitiesTest.C:181]: `--required-capabilities` is used by the TestHarness. On first run (just once), the TestHarness collects the app capabilities so that it can do the internal checking for skipping checks without needing to run the executable as many times as tests you have. In the event that you have a dynamic application that you link in, those dynamic app capabilities aren't known on the first run through. Thus, if you have a dynamically linked application the test harness will check once up front. If things are not certain (missing capability names, etc), it will still run the app (the one that has dynamic linking) but with `--required-capabilities=<capabilities>`. Thus, the app (which has the extra dynamic capabilities) can either run successfully if it has it, or exit this non-zero code that the test harness can capture to consider it a skip.

File: python/pycapabilities/_pycapabilities.C (hunk 8 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.C:489]: Same comment on certain

File: python/pycapabilities/_pycapabilities.C (hunk 9 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.C:495]: Same comment on certain

File: python/pycapabilities/_pycapabilities.C (hunk 10 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.C:500]: Same comment on certain

File: python/pycapabilities/_pycapabilities.C (hunk 11 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.C:504]: Same comment on certain

File: python/pycapabilities/_pycapabilities.C (hunk 12 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.C:598]: Same comment on certain

File: python/pycapabilities/_pycapabilities.pyi (hunk 13 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.pyi:68]: Same comment on certain

File: python/pycapabilities/_pycapabilities.pyi (hunk 14 above)
Comment (loganharbour) [reply python/pycapabilities/_pycapabilities.pyi:88]: Same comment on certain

File: unit/src/CapabilityRegistryTest.C (hunk 15 above)
Comment (loganharbour) [reply unit/src/CapabilityRegistryTest.C:315]: Same comment on certain

File: unit/src/CapabilityRegistryTest.C (hunk 17 above)
Comment (loganharbour) [reply unit/src/CapabilityRegistryTest.C:332]: Correct. This is why the "certain" verbiage is used; it implies a "certain" state

**Review by GiudGiud — APPROVED** [review]

**Comment by loganharbour** [comment]
Error is unrelated and will be fixed on next (richards removal).
