### PR TITLE
Fix pprof recipes

### LINKED ISSUE #21446: go creates read-only cache areas
## Bug Description
`go install` creates read-only cache directories. We tried using their proper tool for clearing this directory. But it does not function in a way we (Civet) requires _in some way unknown to me_.

## Steps to Reproduce
Because this appears to be Civet oriented, you can't reproduce. Instead, to see the effects in actions;

open pprof step
Bad: https://civet.inl.gov/job/1027478/
Good: https://civet.inl.gov/job/1092172/

## Impact
Properly detect failures for one! Properly build/clean pprof when finished for the other.

### PR DESCRIPTION
**Pull request by milljm**
Use tried and true method to clean up go installs

Closes #21446

### CODE REVIEW

**Review by cticenhour — DISMISSED** [review]

File: conda/pprof/build.sh [hunk 1]
```diff
@@ -2,10 +2,14 @@
 set -ex
 export GOPATH="$PREFIX/pprof"
 # Build/Install pprof from google at specified hash
-go install github.com/google/pprof@c488b8fa1db3fa467bf30beb5a1d6f4f10bb1b87
+go install github.com/google/pprof@latest
+
+ls -latrh ${GOPATH}/pprof/bin
+ls -latrh ${GOPATH}/pprof/pkg
```
Comment (cticenhour) [inline conda/pprof/build.sh:8]:
```suggestion
ls -latrh ${GOPATH}/bin
ls -latrh ${GOPATH}/pkg
```

Looking at the linux output, I think you need to remove the pprof dir in these lines, as it should be under `GOPATH`

**Review by cticenhour — APPROVED** [review]
