### PR TITLE
To enable restart a crystal plasticity simulation from checkpoint

### LINKED ISSUE #26458: Crystal plasticity base classes aren't properly resizing state variables on restart
### Discussed in https://github.com/idaholab/moose/discussions/26449

<div type='discussions-op-text'>

<sup>Originally posted by **schakrabortygithub** January  2, 2024</sup>
Hi,

I was trying to use the checkpoint feature to restart a crystal plasticity simulation. But on restart, simulation throws segfault error. The error seems to originate from 'CrystalPlasticityStressUpdateBase::calculateSchmidTensor'. 

[Modified MNWE to use the bicrystal_test.i directly from the repository, with `checkpoint = true` added to the outputs block]

```
[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Mesh]
  file = bicrystal_test_out_cp/LATEST
[]

[Problem]
  restart_file_base = bicrystal_test_out_cp/LATEST
[]

[AuxVariables]
  [pk2]
    order = CONSTANT
    family = MONOMIAL
  []
  [fp_zz]
    order = CONSTANT
    family = MONOMIAL
  []
  [e_zz]
    order = CONSTANT
    family = MONOMIAL
  []
  [copper_gss]
    order = CONSTANT
    family = MONOMIAL
    block = 0
  []
  [copper_slip_increment]
    order = CONSTANT
    family = MONOMIAL
    block = 0
  []
  [brass_gss]
    order = CONSTANT
    family = MONOMIAL
    block = 1
  []
  [brass_slip_increment]
    order = CONSTANT
    family = MONOMIAL
    block = 1
  []
[]

[Modules/TensorMechanics/Master]
  [copper]
    strain = FINITE
    incremental = true
    add_variables = true
    generate_output = stress_zz
    block = 0
    base_name = copper
  []
  [brass]
    strain = FINITE
    incremental = true
    add_variables = true
    generate_output = stress_zz
    block = 1
    base_name = brass
  []
[]

[AuxKernels]
  [pk2]
    type = RankTwoAux
    variable = pk2
    rank_two_tensor = second_piola_kirchhoff_stress
    index_j = 2
    index_i = 2
    execute_on = timestep_end
  []
  [fp_zz]
    type = RankTwoAux
    variable = fp_zz
    rank_two_tensor = plastic_deformation_gradient
    index_j = 2
    index_i = 2
    execute_on = timestep_end
  []
  [e_zz]
    type = RankTwoAux
    variable = e_zz
    rank_two_tensor = total_lagrangian_strain
    index_j = 2
    index_i = 2
    execute_on = timestep_end
  []
  [gss_copper]
    type = MaterialStdVectorAux
    variable = copper_gss
    property = copper_slip_resistance
    index = 0
    block = 0
    execute_on = timestep_end
  []
  [slip_inc_copper]
    type = MaterialStdVectorAux
    variable = copper_slip_increment
    property = copper_slip_increment
    index = 0
    block = 0
    execute_on = timestep_end
  []
  [gss_brass]
    type = MaterialStdVectorAux
    variable = brass_gss
    property = brass_slip_resistance
    index = 0
    block = 1
    execute_on = timestep_end
  []
  [slip_inc_brass]
    type = MaterialStdVectorAux
    variable = brass_slip_increment
    property = brass_slip_increment
    index = 0
    block = 1
    execute_on = timestep_end
  []
[]

[BCs]
  [symmy]
    type = DirichletBC
    variable = disp_y
    boundary = bottom
    value = 0
  []
  [symmx]
    type = DirichletBC
    variable = disp_x
    boundary = left
    value = 0
  []
  [symmz]
    type = DirichletBC
    variable = disp_z
    boundary = back
    value = 0
  []
  [tdisp]
    type = FunctionDirichletBC
    variable = disp_z
    boundary = front
    function = '0.01*t'
  []
[]

[Materials]
  [elasticity_tensor_copper]
    type = ComputeElasticityTensorCP
    C_ijkl = '1.684e5 1.214e5 1.214e5 1.684e5 1.214e5 1.684e5 0.754e5 0.754e5 0.754e5'
    fill_method = symmetric9
    base_name = copper
    block = 0
  []
  [stress_copper]
    type = ComputeMultipleCrystalPlasticityStress
    crystal_plasticity_models = 'trial_xtalpl_copper'
    tan_mod_type = exact
    base_name = copper
    block = 0
  []
  [trial_xtalpl_copper]
    type = CrystalPlasticityKalidindiUpdate
    number_slip_systems = 12
    slip_sys_file_name = input_slip_sys.txt
    base_name = copper
    block = 0
  []
  [elasticity_tensor_brass]
    type = ComputeElasticityTensorCP
    C_ijkl = '1.684e5 1.214e5 1.214e5 1.684e5 1.214e5 1.684e5 0.754e5 0.754e5 0.754e5'
    fill_method = symmetric9
    euler_angle_1 = 0.0
    euler_angle_2 = 45.0
    euler_angle_3 = 0.9
    base_name = brass
    block = 1
  []
  [stress_brass]
    type = ComputeMultipleCrystalPlasticityStress
    crystal_plasticity_models = 'trial_xtalpl_brass'
    tan_mod_type = exact
    base_name = brass
    block = 1
  []
  [trial_xtalpl_brass]
    type = CrystalPlasticityKalidindiUpdate
    number_slip_systems = 12
    slip_sys_file_name = input_slip_sys.txt
    base_name = brass
    block = 1
  []
[]

[Postprocessors]
  [copper_stress_zz]
    type = ElementAverageValue
    variable = copper_stress_zz
    block = 0
  []
  [brass_stress_zz]
    type = ElementAverageValue
    variable = brass_stress_zz
    block = 1
  []
  [pk2]
    type = ElementAverageValue
    variable = pk2
  []
  [fp_zz]
    type = ElementAverageValue
    variable = fp_zz
  []
  [e_zz]
    type = ElementAverageValue
    variable = e_zz
  []
  [copper_gss]
    type = ElementAverageValue
    variable = copper_gss
    block = 0
  []
  [copper_slip_increment]
    type = ElementAverageValue
    variable = copper_slip_increment
    block = 0
  []
  [brass_gss]
    type = ElementAverageValue
    variable = brass_gss
    block = 1
  []
  [brass_slip_increment]
    type = ElementAverageValue
    variable = brass_slip_increment
    block = 1
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  type = Transient
  solve_type = 'PJFNK'

  petsc_options_iname = '-pc_type -pc_asm_overlap -sub_pc_type -ksp_type -ksp_gmres_restart'
  petsc_options_value = ' asm      2              lu            gmres     200'
  nl_abs_tol = 1e-10
  nl_rel_tol = 1e-10
  nl_abs_step_tol = 1e-10

  dt = 0.05
  dtmin = 0.01
  dtmax = 10.0
  num_steps = 10
[]

[Outputs]
  csv = true
  checkpoint = true
[]


```

Here is some useful information from the debugger:

```
Time Step 0, time = 0.01

Time Step 1, time = 0.012, dt = 0.002
Process 28121 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001041b6904 libtensor_mechanics-dbg.0.dylib`CrystalPlasticityStressUpdateBase::calculateSchmidTensor(this=0x0000000123856618, number_slip_systems=0x0000000123857320, plane_normal_vector=size=12, direction_vector=size=12, schmid_tensor=size=0, crysrot=0x0000000124a643c8) at CrystalPlasticityStressUpdateBase.C:414:32
   411 	    for (const auto j : make_range(LIBMESH_DIM))
   412 	      for (const auto k : make_range(LIBMESH_DIM))
   413 	      {
-> 414 	        schmid_tensor[i](j, k) = local_direction_vector[i](j) * local_plane_normal[i](k);
   415 	      }
   416 	  }
   417 	}
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001041b6904 libtensor_mechanics-dbg.0.dylib`CrystalPlasticityStressUpdateBase::calculateSchmidTensor(this=0x0000000123856618, number_slip_systems=0x0000000123857320, plane_normal_vector=size=12, direction_vector=size=12, schmid_tensor=size=0, crysrot=0x0000000124a643c8) at CrystalPlasticityStressUpdateBase.C:414:32
    frame #1: 0x00000001041a9540 libtensor_mechanics-dbg.0.dylib`CrystalPlasticityStressUpdateBase::calculateFlowDirection(this=0x0000000123856618, crysrot=0x0000000124a643c8) at CrystalPlasticityStressUpdateBase.C:378:3
    frame #2: 0x00000001041a8f7f libtensor_mechanics-dbg.0.dylib`ComputeMultipleCrystalPlasticityStress::updateStress(this=0x0000000123870e18, cauchy_stress=0x0000000124a7b9a8, jacobian_mult=0x000000012580cc00) at ComputeMultipleCrystalPlasticityStress.C:237:17
    frame #3: 0x00000001041d02cc libtensor_mechanics-dbg.0.dylib`ComputeMultipleCrystalPlasticityStress::computeQpStress(this=0x0000000123870e18) at ComputeMultipleCrystalPlasticityStress.C:205:3
    frame #4: 0x0000000103d82b3d libtensor_mechanics-dbg.0.dylib`ComputeGeneralStressBase::computeQpProperties(this=0x0000000123870e18) at ComputeGeneralStressBase.C:46:3
    frame #5: 0x00000001094e7a58 libmoose-dbg.0.dylib`Material::computeProperties(this=0x0000000123870e18) at Material.C:132:7
    frame #6: 0x000000010a1b1cd9 libmoose-dbg.0.dylib`void MaterialData::reinit<std::__1::vector<std::__1::shared_ptr<MaterialBase>, std::__1::allocator<std::__1::shared_ptr<MaterialBase> > > >(this=0x00000001249e45a0, mats=size=3) at MaterialData.h:313:10
    frame #7: 0x000000010a1b1c46 libmoose-dbg.0.dylib`FEProblemBase::reinitMaterials(this=0x000000012500d418, blk_id=0, tid=0, swap_stateful=true) at FEProblemBase.C:3392:21
    frame #8: 0x000000010ae186e6 libmoose-dbg.0.dylib`NonlinearThread::onElement(this=0x00007ffeefbf6e68, elem=0x0000000124a52010) at NonlinearThread.C:131:15
    frame #9: 0x0000000109cff166 libmoose-dbg.0.dylib`ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator(this=0x00007ffeefbf6e68, range=0x0000000124b6a5e0, bypass_threading=false)(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) at ThreadedElementLoopBase.h:248:9
    frame #10: 0x000000010ae20ef1 libmoose-dbg.0.dylib`NonlinearThread::operator(this=0x00007ffeefbf6e68, range=0x0000000124b6a5e0, bypass_threading=false)(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) at NonlinearThread.C:60:42
    frame #11: 0x000000010af406de libmoose-dbg.0.dylib`void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeResidualThread>(range=0x0000000124b6a5e0, body=0x00007ffeefbf6e68) at threads_pthread.h:380:5
    frame #12: 0x000000010af37c79 libmoose-dbg.0.dylib`NonlinearSystemBase::computeResidualInternal(this=0x000000012500fa18, tags=size=3) at NonlinearSystemBase.C:1569:5
    frame #13: 0x000000010af35569 libmoose-dbg.0.dylib`NonlinearSystemBase::computeResidualTags(this=0x000000012500fa18, tags=size=3) at NonlinearSystemBase.C:781:5
    frame #14: 0x000000010a09ed49 libmoose-dbg.0.dylib`FEProblemBase::computeResidualTags(this=0x000000012500d418, tags=size=3) at FEProblemBase.C:6395:20
    frame #15: 0x000000010a09cfc7 libmoose-dbg.0.dylib`FEProblemBase::computeResidualInternal(this=0x000000012500d418, soln=0x00000001249f8d20, residual=0x00000001249f9730, tags=size=3) at FEProblemBase.C:6241:5
    frame #16: 0x000000010a09b713 libmoose-dbg.0.dylib`FEProblemBase::computeResidual(this=0x000000012500d418, soln=0x00000001249f8d20, residual=0x00000001249f9730, nl_sys_num=0) at FEProblemBase.C:6012:3
    frame #17: 0x000000010a0e11bc libmoose-dbg.0.dylib`FEProblemBase::computeResidualSys(this=0x000000012500d418, sys=0x00000001249f9340, soln=0x00000001249f8d20, residual=0x00000001249f9730) at FEProblemBase.C:5979:3
    frame #18: 0x000000010af666b6 libmoose-dbg.0.dylib`NonlinearSystem::solve(this=0x000000012500fa18) at NonlinearSystem.C:147:17
    frame #19: 0x000000010a1033f7 libmoose-dbg.0.dylib`FEProblemBase::solve(this=0x000000012500d418, nl_sys_num=0) at FEProblemBase.C:5672:22
    frame #20: 0x000000010941af65 libmoose-dbg.0.dylib`FEProblemSolve::solve(this=0x000000012500c6a8) at FEProblemSolve.C:284:14
    frame #21: 0x0000000109414f65 libmoose-dbg.0.dylib`FixedPointSolve::solveStep(this=0x0000000124b2bcd0, begin_norm=0x0000000122cfc990, end_norm=0x0000000122efc290, transformed_dofs=size=0) at FixedPointSolve.C:426:22
    frame #22: 0x00000001094129be libmoose-dbg.0.dylib`FixedPointSolve::solve(this=0x0000000124b2bcd0) at FixedPointSolve.C:278:28
    frame #23: 0x000000010ac33bcd libmoose-dbg.0.dylib`TimeStepper::step(this=0x0000000122e16168) at TimeStepper.C:168:52
    frame #24: 0x0000000109418987 libmoose-dbg.0.dylib`Transient::takeStep(this=0x000000012500c418, input_dt=-1) at Transient.C:430:18
    frame #25: 0x0000000109425429 libmoose-dbg.0.dylib`Transient::execute(this=0x000000012500c418) at Transient.C:305:5
    frame #26: 0x000000010b4c3bc0 libmoose-dbg.0.dylib`MooseApp::executeExecutioner(this=0x0000000123854418) at MooseApp.C:1142:19
    frame #27: 0x000000010b4bba0a libmoose-dbg.0.dylib`MooseApp::run(this=0x0000000123854418) at MooseApp.C:1517:5
    frame #28: 0x0000000100011d75 moose_discoflux-dbg`main(argc=3, argv=0x00007ffeefbfd990) at main.C:33:8
    frame #29: 0x00007fff20519f3d libdyld.dylib`start + 1
(lldb) p schmid_tensor[i](j, k)
error: Couldn't apply expression side effects : Couldn't dematerialize a result variable: couldn't read its memory
(lldb) p local_direction_vector[i](j)
(double) $1 = 0
(lldb) p local_plane_normal[i](k)
(double) $2 = 0.57735026918962584
```

When simulation is run from the beginning, without any error, the arguments to the function call 'calculateSchmidTensor' is:

```
Time Step 1, time = 0.002, dt = 0.002
Process 28502 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001041b6830 libtensor_mechanics-dbg.0.dylib`CrystalPlasticityStressUpdateBase::calculateSchmidTensor(this=0x0000000127008618, number_slip_systems=0x0000000127009320, plane_normal_vector=size=12, direction_vector=size=12, schmid_tensor=size=12, crysrot=0x0000000122e2ec98) at CrystalPlasticityStressUpdateBase.C:414:57
   411 	    for (const auto j : make_range(LIBMESH_DIM))
   412 	      for (const auto k : make_range(LIBMESH_DIM))
   413 	      {
-> 414 	        schmid_tensor[i](j, k) = local_direction_vector[i](j) * local_plane_normal[i](k);
   415 	      }
   416 	  }
   417 	}
```

Not sure why during restart 'schmid_tensor=size=0'. The correct one is 'schmid_tensor=size=12'.

Best
Subhendu Chakraborty</div>

### PR DESCRIPTION
**Pull request by schakrabortygithub**
The non-statefull material properties were not getting resized properly during restart.

closes #26458 (changed to point directly to the issue that refers to the original discussion)

## Reason
The non-stateful material properties in crystal plasticity material models that were derived from the class "CrystalPlasticityStressUpdateBase" were not getting properly resized if the simulation is restated from a checkpoint.
This happened because the resizing operation are done within the function initQpStatefulProperties() of the corresponding class and during restart that function is not called for obvious reason.

## Design
A new virtual function setMaterialVectorSize() is added to separate the resizing operation for non-stateful material properties.

## Impact
Crystal plasticity simulation that updates the stress using the class 'ComputeMultipleCrystalPlasticityStress' and 'CrystalPlasticityStressUpdateBase' e.g., CrystalPlasticityKalidindiUpdate, CrystalPlasticityTwinningKalidindiUpdate should work without any problem while restarting the simulation from a checkpoint.
Also added input scripts to restart a simulation for regression test.

### CODE REVIEW

File: modules/tensor_mechanics/include/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.h [hunk 1]
```diff
@@ -38,6 +38,7 @@ class CrystalPlasticityStressUpdateBase : public Material
    * This class is often overwritten by inherting classes.
    */
   virtual void initQpStatefulProperties() override;
+  virtual void setMaterialVectorSize() ;
```
Comment (loganharbour) [inline modules/tensor_mechanics/include/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.h:41]:
```suggestion
  virtual void setMaterialVectorSize();
```

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C [hunk 2]
```diff
@@ -72,6 +72,13 @@ CrystalPlasticityKalidindiUpdate::initQpStatefulProperties()
   }
 }
 
+void
+CrystalPlasticityKalidindiUpdate::setMaterialVectorSize()
+{
+  CrystalPlasticityStressUpdateBase::setMaterialVectorSize();
+
```
Comment (loganharbour) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:79]:
```suggestion
  CrystalPlasticityStressUpdateBase::setMaterialVectorSize();
```

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityTwinningKalidindiUpdate.C [hunk 3]
```diff
@@ -126,6 +125,16 @@ CrystalPlasticityTwinningKalidindiUpdate::initQpStatefulProperties()
...
 }
 
+void
+CrystalPlasticityTwinningKalidindiUpdate::setMaterialVectorSize()
+{
+  CrystalPlasticityStressUpdateBase::setMaterialVectorSize();
+
+  //Resize non-statefull material properties
+  _twin_volume_fraction_increment[_qp].resize(_number_slip_systems);
+
```
Comment (loganharbour) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityTwinningKalidindiUpdate.C:135]:
```suggestion
  // Resize non-statefull material properties
  _twin_volume_fraction_increment[_qp].resize(_number_slip_systems);
```

**Review by loganharbour — CHANGES_REQUESTED** [review]

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C [hunk 4]
```diff
@@ -72,6 +72,13 @@ CrystalPlasticityKalidindiUpdate::initQpStatefulProperties()
...
+}
+
```
Comment (loganharbour) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:81]:
```suggestion
void
CrystalPlasticityKalidindiUpdate::setMaterialVectorSize()
{
  CrystalPlasticityStressUpdateBase::setMaterialVectorSize();
}

```

**Review by loganharbour — DISMISSED** [review]

**Review by loganharbour — COMMENTED** [review]
Thanks for looking into this @schakrabortygithub. 

I went ahead and applied the clang-format issues so that the tests will run.

I'll take a look at this soon.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C [hunk 5]
```diff
@@ -229,6 +232,8 @@ ComputeMultipleCrystalPlasticityStress::updateStress(RankTwoTensor & cauchy_stre
       _models[i]->setSubstepDt(_substep_dt);
 
     // calculate F^{eigen} only when we have eigenstrain
+    _inverse_eigenstrain_deformation_grad.zero();
+    _inverse_eigenstrain_deformation_grad.addIa(1.0);
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C:236]: Are you adding these two lines here?

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C [hunk 6]
```diff
@@ -72,6 +72,12 @@ CrystalPlasticityKalidindiUpdate::initQpStatefulProperties()
   }
 }
 
+void
+CrystalPlasticityKalidindiUpdate::setMaterialVectorSize()
+{
+  CrystalPlasticityStressUpdateBase::setMaterialVectorSize();
+}
+
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:80]: No need to override this function in this derived class if the same function is called by the base class. .

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C [hunk 7]
```diff
@@ -119,14 +119,21 @@ CrystalPlasticityStressUpdateBase::CrystalPlasticityStressUpdateBase(
...
 {
-  _tau[_qp].resize(_number_slip_systems);
-
-  _flow_direction[_qp].resize(_number_slip_systems);
+  setMaterialVectorSize();
   for (const auto i : make_range(_number_slip_systems))
   {
     _flow_direction[_qp][i].zero();
     _tau[_qp][i] = 0.0;
   }
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C:127]: resize and initialization should be done within the same function. Maybe consider moving the initialization to the new function too.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C [hunk 8]
```diff
@@ -119,14 +119,21 @@ CrystalPlasticityStressUpdateBase::CrystalPlasticityStressUpdateBase(
...
+void
+CrystalPlasticityStressUpdateBase::setMaterialVectorSize()
+{
+
+  _tau[_qp].resize(_number_slip_systems);
+
+  _flow_direction[_qp].resize(_number_slip_systems);
 
   _slip_resistance[_qp].resize(_number_slip_systems);
   _slip_increment[_qp].resize(_number_slip_systems);
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C:139]: why these two are not needed in the new function?

**Review by jiangwen84 — CHANGES_REQUESTED** [review]
Minor comments.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C (hunk 5 above)
Comment (sapitts) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C:236]: with just the `setMaterialVectorSize` method, a libmesh Assert is thrown because the elastic deformation gradient comes in as a zero tensor to the `postSolveQp` method. I suspect, and would appreciate it if @schakrabortygithub would confirm, that these lines are added to avoid that case

@schakrabortygithub would you add a regression test to restart one of the eigenstrain regression tests to make sure this change will handle those cases too please?

Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C:236]: @jiangwen84 Yes, those lines are due to the reason as explained by @sapitts.
I will test the restart capability and add the regression test for Eigen strain case.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C (hunk 6 above)
Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:80]: This one I did to keep the format general for any class that is derived from 'CrystalPlasticityStressUpdateBase' and has non-statefull material property whose size is not known during compile time but being resized during run time e.g, 'CrystalPlasticityTwinningKalidindiUpdate'. The material class 'CrystalPlasticityKalidindiUpdate' is a special case where there is no such resize operation. Let me know if I should remove that override from this one class. @jiangwen84

Comment (jiangwen84) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:80]: This is a C++ thing. In your case, ```CrystalPlasticityKalidindiUpdate``` will just call the function of ```setMaterialVectorSize``` from its base class. You do not need to add this function in ```CrystalPlasticityKalidindiUpdate``` header and source files.

Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityKalidindiUpdate.C:80]: Sure, that makes sense. I will remove that override from `CrystalPlasticityKalidindiUpdate `.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C (hunk 8 above)
Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C:139]: @jiangwen84 
Can you elaborate what you mean? I might be missing something.
Those two are part of the new function.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C (hunk 7 above)
Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/CrystalPlasticityStressUpdateBase.C]: @jiangwen84 
I have incorporated these changes in the new commit.

File: modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C (hunk 5 above)
Comment (schakrabortygithub) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C:236]: @sapitts 
I have tested the restart capability of CP-model with eigenstrain without any issue. Also added a regression test at:
modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/thermal_eigenstrain_test_restart.i

One thing, these restart files should run after their parent files, during the regression test, to make sure that corresponding checkpoint files are available during restart.

**Review by jiangwen84 — APPROVED** [review]

**Comment by GiudGiud** [comment]
Assigning you for the merge @jiangwen84

**Comment by sapitts** [comment]
@jiangwen84 I'd like to get this `setMaterialVector` change added into the remaining stress-update based crystal plasticity classes, and the modifications to all of the `tests` files made so that the new tests @schakrabortygithub added will be run in the test suite. I can do this as an additional commit on existing PR here.

Would you wait to merge this code until after I have added that commit please?

**Comment by GiudGiud** [comment]
@sapitts @jiangwen84 @loganharbour can we get an update on this please? Just making sure we're not stalling by accident

**Comment by sapitts** [comment]
Sorry folks, I lost github notifications and clearly forgot to check on this PR. @subhendu-LANL  thank you for repushing with the refactor to the new solid mechanics module name. I will pull early next week and get the required `tests` files added so that the new tests added are actually run. If you'd rather not wait for me (I completely understand, my track record with this pull request is pretty terrible), please take a look at the `tests` text file in any of the directories in which you have added a new test

File: framework/contrib/wasp
Comment (sapitts) [inline framework/contrib/wasp:1]: you'll need to reconcile this submodule with the `devel` branch version before the tests pass. I suggest updating your submodules after rebasing; @GiudGiud will know the best way to handle this case

Comment (schakrabortygithub) [reply framework/contrib/wasp:1]: @sapitts can you please check if the wasp submodule version of this PR branch is in sync with the moose/devel or not?

Comment (GiudGiud) [reply framework/contrib/wasp:1]: git fetch origin
Git rebase origin/devel

If any submodule change shows up in a commit you ll have to go to the commit and checkout the “old” version compared to your accidental change

Comment (schakrabortygithub) [reply framework/contrib/wasp:1]: @sapitts @GiudGiud , thanks for the suggestions! That helped.
Reverted the changes that I made by mistake in the sub-module `wasp`. Now, it does not show up in the `files changed`.

**Comment by schakrabortygithub** [comment]
@sapitts , sure, you can push the changes to the branch that I have created for this PR.

**Comment by sapitts** [comment]
@jiangwen84 or @loganharbour if one of you would be willing to review this PR once more, it's ready to go

**Review by loganharbour — COMMENTED** [review]
👍🏼 to the changes in code.

I would prefer that someone with more mechanics experience look at the tests.

**Review by dschwen — APPROVED** [review]
Looks good to me.
