### PR TITLE
Restoring reporter data when timestep fails

### LINKED ISSUE #30394: Should postprocessors be restored on failed timesteps?
### Motivation

As efforts to improve the robustness of the framework and modules to failed solves, i.e. repeated timesteps (see #30126), a recurring issue occurs regarding the state of postprocessors. Essentially, it is possible (and quite common) for objects to depend on old postprocessor values indirectly. For instance, an object executing on `timestep_begin` depending on a PP executing on `timestep_end`. Although this type of dependency is generally frowned upon, it is usually quite convenient in practice. However, if there is a timestep where `timestep_end` is called and afterward, the executioner decides to retry the timestep (e.g. a failed multiapp solve) the subsequent execution on `timestep_begin` will utilize different PP values than what was used before the first solve. This leads to a unintended discrepancy in the results than if the timestep didn't fail.

The thermal hydraulics module utilizes this dependency very frequently within it's `ControlLogic` functionality. Where `Controls` are exectuted on `timestep_begin`, which frequently depend on postprocessors executed on `timestep_end`.

Here is a simple, albeit contrived, example showing the issue. Here we have a PP the reports the time at `nonlinear`, and another PP that copies that value at `timestep_begin`, essentially lagging the time:

```
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 1
  []
[]

[Variables]
  [u]
  []
[]

[Kernels]
  [dt]
    type = TimeDerivative
    variable = u
  []
  [source]
    type = BodyForce
    variable = u
  []
[]

[Postprocessors]
  [time]
    type = TimePostprocessor
    execute_on = 'nonlinear'
  []
  [time_lag]
    type = ParsedPostprocessor
    expression = 'time'
    pp_names = 'time'
    execute_on = 'timestep_begin'
  []
[]

[Executioner]
  type = Transient
  end_time = 5
[]
```

```
Postprocessor Values:
+----------------+----------------+----------------+
| time           | time           | time_lag       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   2.000000e+00 |   1.000000e+00 |
|   3.000000e+00 |   3.000000e+00 |   2.000000e+00 |
|   4.000000e+00 |   4.000000e+00 |   3.000000e+00 |
|   5.000000e+00 |   5.000000e+00 |   4.000000e+00 |
+----------------+----------------+----------------+
```

Now if we "fail" the solve at timestep 5 using `FailingProblem`, we see the discrepancy:
```
Postprocessor Values:
+----------------+----------------+----------------+
| time           | time           | time_lag       |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   2.000000e+00 |   1.000000e+00 |
|   3.000000e+00 |   3.000000e+00 |   2.000000e+00 |
|   4.000000e+00 |   4.000000e+00 |   3.000000e+00 |
|   4.500000e+00 |   4.500000e+00 |   5.000000e+00 |
|   5.000000e+00 |   5.000000e+00 |   4.500000e+00 |
+----------------+----------------+----------------+
```

### Design

An idea to resolve this discrepancy involves "restoring" postprocessor values when a timestep is rejected. This would be identical to how solutions are restored in `FEProblemBase::restoreSolutions`, which is called when a timestep is being repeated. One caveat to this approach is that, in order to enable this, old postprocessor values would have to be stored, regardless of whether they are requested. I don't see this being a large issue since postprocessors are very light memory-wise. Extending this to VPPs and reporters would be natural, but the memory overhead would be more significant and dependency issues on these quantities is much less common.

Another solution that might warrant discussion is that we store all `RestartableData` for the main application and restore that when repeating a timestep. MultiApps do this, which is why we don't see the same issues when repeating multiapp timesteps. However, this could possibly be a huge memory or storage overhead for something that may or may not occur. 

### Impact

More robust app execution when timesteps fail, but potentially more memory overhead.

### PR DESCRIPTION
**Pull request by zachmprince**
## Reason

Closes #30394

## Design

The new member `restoreState` is added to `ReporterState`, which is called by `FEProblemBase::restoreSolutions` when a timestep is rejected and repeated. This method copies the old reporter value to its current one, if and only if an old value exists. Typically, an old value only exists if one is requested by another object; this remains true for `Reporters` and `VectorPostprocessors`. But now all `Postprocessors` states have an old value, regardless of whether it is requested. This is done by automatically declaring an old value when the value is declared.

In order to alleviate any confusion on whether a reporter value was restored or not, a verbosity mechanism was added: printing out a table of all reporter values and whether or not they were restored. Here is an example:

```
Restoring postprocessor, vector-postprocessor, and reporter data...


*** Info ***
Reporter Restoration Summary:
--------------------------------------
|    Name     |   Type   | Restored? |
--------------------------------------
| a/broadcast | Reporter | NO        |
| a/gather    | Reporter | NO        |
| a/int       | Reporter | YES       |
| a/real      | Reporter | NO        |
| a/scatter   | Reporter | NO        |
| a/string    | Reporter | NO        |
| a/vector    | Reporter | NO        |
--------------------------------------
```

Of course, postprocessors are always restored:
```
----------------------------------------------
|      Name      |     Type      | Restored? |
----------------------------------------------
| time/value     | Postprocessor | YES       |
| time_lag/value | Postprocessor | YES       |
----------------------------------------------
```

## Impact

See #30394

### CODE REVIEW

**Review by joshuahansel — CHANGES_REQUESTED** [review]
I didn't go deep into the technical, but the high level looks good. Is there a relevant place to mention restorability of reporters in documentation?

**Comment by zachmprince** [comment]
I can put it in the syntax documentation of each reporter type. What do you think @joshuahansel ?

**Review by joshuahansel — APPROVED** [review]

**Comment by GiudGiud** [comment]
> if and only if an old value exists.

this is a good idea, likely means state is involved already

File: framework/include/problems/FEProblemBase.h [hunk 1]
```diff
@@ -2778,6 +2778,9 @@ class FEProblemBase : public SubProblem, public Restartable
   /// Whether or not to be verbose with multiapps
   bool _verbose_multiapps;
 
+  /// Whether or not to be verbose on solution restoration
```
Comment (GiudGiud) [inline framework/include/problems/FEProblemBase.h:2781]:
```suggestion
  /// Whether or not to be verbose on solution restoration post a failed time step
```

File: modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_integration_error.i [hunk 2]
```diff
@@ -203,6 +194,8 @@
   growth_factor = 1.5
   cutback_factor = 0.5
   timestep_limiting_postprocessor = matl_ts_min
+  reject_large_step = true
+  reject_large_step_threshold = 0.999
```
Comment (GiudGiud) [inline modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_integration_error.i:198]: so this is just a friendlier setup for this step rejection?

**Review by GiudGiud — APPROVED** [review]

File: modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_integration_error.i (hunk 2 above)
Comment (zachmprince) [reply modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_integration_error.i:198]: I don't think that is the case. There is no way to execute a userobject between restoration and when it is used to constrain a timestep. This is an extremely unique usage of a PP value, so I think it's appropriate to implement the proper logic within the object requiring the uniqueness.
