### PR TITLE
Fixed ComputeJacobianThread so DGKernels are computed by subdomain

### LINKED ISSUE #6114: New Bugs added courtesy of the warehouse refactor - enjoy!
These are rather critical

`ComputeJacobianThread.C:89`
`ComputeJacobianThread.C:127`

### PR DESCRIPTION
**Pull request by aeslaughter**
(closes #6114)

### CODE REVIEW

**Comment by friedmud** [comment]
I'm ok with these changes (provided the tests pass at some point ;-)

File: framework/src/base/ComputeResidualThread.C [hunk 1]
```diff
@@ -101,7 +80,7 @@ ComputeResidualThread::onElement(const Elem *elem)
   _fe_problem.reinitMaterials(_subdomain, _tid);
 
 
-  const MooseObjectWarehouse<KernelBase> * storage;
+  MooseObjectWarehouse<KernelBase> const * storage;
```
Comment (permcody) [inline framework/src/base/ComputeResidualThread.C]: I'm not sure if this change was intentional or not, but it is fairly confusing. Usually when we see const **not** at the front of the declaration, we take that to mean that the pointer is constant, not the data (e.g. `Foo * const p`). However, in this case the const actually appears in-between the type and the pointer designation which means const data which is equivalent to the more normal declaration `const Foo * p`. So this change is equivalent and unecessary and just plain confusing.

Comment (aeslaughter) [inline framework/src/base/ComputeResidualThread.C]: I have been playing around with this sort of think recently, trying to get a better handle on what order things "should", from a readability standpoint, be coded.

To me the new way makes more sense when read from right to left (which is what I usually do): `storage` is a pointer to a `const` `MooseObjectWarehouse`. The pointer is not const, the thing pointed too is.

Having the `const` at the beginning, for me, leads me to believe the pointer is `const`, which is of course not true. Because, if I create something to be `const` I put it at the beginning in general.

I am happy to change it back, it is just something I am playing with.

What does @jwpeterson say?

Comment (permcody) [inline framework/src/base/ComputeResidualThread.C]: I'd be willing to bet that this is the only declaration in MOOSE using this order:

While your reasoning to change this makes sense, I think years of engrained practice go against this theory. Are you proposing that we declare none pointer types like this too (`int const i`)?

My specific problem with this order is that it's easy to confuse with the const pointer declaration:
These are not the same:
```
Foo * const p;   // const pointer
Foo const * p;   // const data (looks almost the same at first glance)

const Foo * p;  // more traditional const data (looks different from const pointer declaration)
```

**Comment by permcody** [comment]
:+1:
