### PR TITLE
Clear point locator after displacing the mesh

### LINKED ISSUE #22534: Incorrect transfer of data from displaced source
## Bug Description
Executing the inputs contained on my branch `debugging-22119`, which stems from discussion #22119 leads to the following undesirable behavior:

- libMesh node ID 89365 (exodus node ID 89366) is an example of a to-node getting a 0 value when it shouldn't
- This corresponds to the 4833 point that we want to query the from-mesh for (e.g. index 4832 in the incoming/outgoing points vector)
- When asking the mesh function to find the from-element containing that to-node we are getting back a null result, indicating that it thinks the point is out of the mesh
- When we get to the active nodes in `TreeNode`, we do get `bounds_point` but we do not get any elements that `contains_point`

I don't really know why this would be a hard case ... these are linear elements so I would expect inverse mapping from the physical space to the reference space to essentially be exact.

@roystgnr do you have any thoughts on what might be the issue here? Pasted below is a figure. The bottom is the sub-application field that we are transferring to the main application on top. You can see that we are getting these "teeth" in the transfer with the blue gaps in the teeth essentially indicating a failed transfer
Screen Shot 2022-10-28 at 12 35 44 AM

## Steps to Reproduce
Run the `parent.i` input in my branch

## Impact
Incorrect data transfers from displaced meshes. Erodes trust in the transfer system

### PR DESCRIPTION
**Pull request by lindsayad**
Displacing the mesh invalidates all the bounding boxes on the
point locator, so we need to make sure we clear the locator so
we don't use bad bounding box data

Closes #22534

### CODE REVIEW

**Comment by lindsayad** [comment]
@maxnezdyur would you be ok with me committing your example as a test with you as the commit author?

File: framework/src/transfers/MultiAppShapeEvaluationTransfer.C [hunk 1]
```diff
@@ -370,6 +370,7 @@ MultiAppShapeEvaluationTransfer::transferVariable(unsigned int i)
         if (node->n_dofs(sys_num, var_num) < 1)
           continue;
 
+        const auto node_id = node->id();
```
Comment (roystgnr) [inline framework/src/transfers/MultiAppShapeEvaluationTransfer.C:373]: What's going on here?  Is this an unused variable?

File: framework/src/loops/UpdateDisplacedMeshThread.C [hunk 2]
```diff
@@ -142,6 +143,12 @@ UpdateDisplacedMeshThread::onNode(NodeRange::const_iterator & nd)
   }
 }
 
+void
+UpdateDisplacedMeshThread::post()
+{
+  _displaced_problem.mesh().getMesh().clear_point_locator();
```
Comment (roystgnr) [inline framework/src/loops/UpdateDisplacedMeshThread.C:149]: This seems obviously correct ... which makes it somewhat concerning that it wasn't being done years ago.  Did we never run into a problem until we tried to do a transfer to/from a displaced mesh that relied on a PointLocator query?

**Review by roystgnr — DISMISSED** [review]

**Comment by maxnezdyur** [comment]
> @maxnezdyur would you be ok with me committing your example as a test with you as the commit author?

Yes, sounds good to me.

File: framework/src/transfers/MultiAppShapeEvaluationTransfer.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/transfers/MultiAppShapeEvaluationTransfer.C]: haha yea that's why CIVET was screaming. It was a temporary debugging line since gdb appears to choke on condition breakpoints involving a call through a range-based for iterator (pointing to a `Node *` in this case)

File: framework/src/loops/UpdateDisplacedMeshThread.C (hunk 2 above)
Comment (lindsayad) [reply framework/src/loops/UpdateDisplacedMeshThread.C:149]: It is frankly shocking that no one complained about this before

Comment (lindsayad) [reply framework/src/loops/UpdateDisplacedMeshThread.C:149]: many kudos to @maxnezdyur for finding it and reporting it

**Comment by GiudGiud** [comment]
These files are too big

**Comment by lindsayad** [comment]
😢

**Comment by lindsayad** [comment]
I tried coarsening the problem to see whether I could reproduce the bad behavior but wasn't successful. I'll try again

**Comment by maxnezdyur** [comment]
@lindsayad For a coarser mesh, the deformation needs to be larger for the problem to manifest. The input file below is a modified version of child.i. I changed it to a static mechanics problem and only prescribed displacements that would cause the whole structure to move. You may need need to mess with the timestep size, but I was able to see the problems on a parent mesh with `nx =100 ny=25`. 
```
 [GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    xmin = 0
    ymin = 0
    xmax = 0.2
    ymax = 0.5
    nx = 5
    ny = 15
    elem_type = QUAD4
  []
[]
[Variables]
  [disp_x]
    order = FIRST
  []
  [disp_y]
    order = FIRST
  []
[]

[AuxVariables] # variables that are calculated for output
  [solid_indicator]
    order = FIRST
    family = LAGRANGE
    [AuxKernel]
      type = ConstantAux
      variable = solid_indicator
      value = 0.0
      boundary = 'left right top'
      execute_on = 'INITIAL TIMESTEP_END'
    []
    initial_condition = 1.0
  []
[]

[Modules/TensorMechanics/Master]
  [all]
    # displacements = 'disp_x disp_y'
    add_variables = true
    # new_system = true
    incremental = true
    strain = SMALL
  []
[]

[Materials]
  [elastic_tensor]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 10000.0
    poissons_ratio = 0.3
    use_displaced_mesh = true
  []
  [stress]
    type = ComputeFiniteStrainElasticStress
  []
[]

[BCs]
  [move_bottom_x]
    type = FunctionDirichletBC
    boundary = bottom
    function = 't'
    variable = disp_x
  []
  [move_bottom_y]
    type = FunctionDirichletBC
    boundary = bottom
    function = 't'
    variable = disp_y
  []
[]

[Preconditioning]
  [SMP]
    type = SMP
    full = true
  []
[]
[Executioner]
  type = Transient
  end_time = 2
  dt = 1
  solve_type = 'NEWTON'
  petsc_options = '-snes_converged_reason -ksp_converged_reason -snes_ksp_ew'
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_type -pc_factor_shift_type -pc_factor_shift_amount'
  petsc_options_value = 'lu       superlu_dist                  NONZERO               1e-15'
  nl_max_its = 40
  l_max_its = 15
  line_search = 'none'
  nl_abs_tol = 1e-5
  nl_rel_tol = 1e-4
  automatic_scaling = true
[]

[Outputs]
  exodus = true
  print_linear_residuals = false
  print_linear_converged_reason = false
[]

```

**Comment by lindsayad** [comment]
Thanks @maxnezdyur! Before I saw your comment I switched to a CSVDiff. If that doesn't work out, I will definitely use your coarser child although the biggest file actually comes from the parent output

**Comment by maxnezdyur** [comment]
@lindsayad Sounds good. Also, the input file I provided, caused a problem on a parent mesh of nx=100 and ny=25. I didn't supply that input file because that and the time step size were all that I changed in the parent file.

**Comment by lindsayad** [comment]
Ah got ya. Ok I think I'm going to switch back to Exodiff with your suggestions as it is a much more reliable illustration of the original problem ... `NodalVariableValue` is a bit hacky as it relies on the fact that the mesh always be numbered the same way

**Review by GiudGiud — APPROVED** [review]
