### PR TITLE
Fix segfault for nonexistant variable in SolutionUserObject and test

### LINKED ISSUE #6694: Segmentation fault if invalid variable name is used in SolutionFunction or Axisymmetric2D3DSolutionFunction
### Description of the enhancement or error report
The user provides a variable or list of variables used to define the solution in `SolutionFunction` or `Axisymmetric2D3DSolutionFunction` using the `from_variable` or `from_variables` parameter, respectively. If an invalid variable name is supplied, a segmentation fault results in either case.

### Rationale for the enhancement or information for reproducing the error
Need a good error message rather than a segmentation fault

### Identified impact
Better error checking in `Axisymmetric2D3DSolutionFunction`, `SolutionFunction`, and `SolutionUserObject`.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #6694

### CODE REVIEW

File: framework/src/userobject/SolutionUserObject.C [hunk 1]
```diff
@@ -645,6 +645,8 @@ SolutionUserObject::evalMeshFunction(const Point & p, std::string var_name, unsi
 
   // Extract the variable index for the MeshFunction(s), must use iterator b/c of const
   std::map<std::string, unsigned int>::const_iterator it = _local_variable_index.find(var_name);
+  if (it == _local_variable_index.end())
```
Comment (permcody) [inline framework/src/userobject/SolutionUserObject.C]: This doesn't seem right. Why can't we detect this in the ctor? Maybe we just need to use the "variables" parameter to "VariableName"? I'd have to dig in bit more but this just looks way too late.

Comment (bwspenc) [inline framework/src/userobject/SolutionUserObject.C]: The SolutionFunction calls this method and passes in the name of the variable for which it's asking for a value. The SolutionUserObject doesn't know what the name of the variable that will be passed in is in its constructor. I agree that it's preferable to catch this earlier. Maybe the thing to do is to have a method on SolutionUserObject that returns an index to the variable. That would get called by SolutionFunction early on and get stashed away, and then we would pass in that index instead of the variable name in these methods that give the value. That would be more efficient as well.

**Comment by permcody** [comment]
Hmm... OK well this is still a good fix in the meantime. @YaqiWang identified a thread issue that needs to be fixed as well so maybe we'll give this object some TLC.
