### PR TITLE
Fix seg fault. 

### LINKED ISSUE #10194: Error in GeneralizedPlaneStrainOffDiag
## Rationale
An out-of-bounds memory access is possible in GeneralizedPlaneStrainOffDiag.

## Description
A vector is being accessed in the second position when only one position may exist.

## Impact
Prevent seg faults.

### PR DESCRIPTION
**Pull request by jasondhales**
Closes #10194.

### CODE REVIEW

File: modules/tensor_mechanics/src/kernels/GeneralizedPlaneStrainOffDiag.C [hunk 1]
```diff
@@ -56,15 +56,16 @@ GeneralizedPlaneStrainOffDiag::GeneralizedPlaneStrainOffDiag(const InputParamete
                        : 0),
     _temp_var(isParamValid("temperature")
                   ? &_subproblem.getVariable(_tid, getParam<NonlinearVariableName>("temperature"))
-                  : NULL)
+                  : NULL),
+    _num_disp_var(getParam<std::vector<NonlinearVariableName>>("displacements").size())
```
Comment (hchen139) [inline modules/tensor_mechanics/src/kernels/GeneralizedPlaneStrainOffDiag.C]: Maybe we should define _nl_vnames_ as member variable and assign its size to __num_disp_var_

**Review by hchen139 — CHANGES_REQUESTED** [review]

File: modules/tensor_mechanics/src/kernels/GeneralizedPlaneStrainOffDiag.C (hunk 1 above)
Comment (jasondhales) [reply modules/tensor_mechanics/src/kernels/GeneralizedPlaneStrainOffDiag.C]: We could do that, but I'm not sure it's better.

**Review by permcody — APPROVED** [review]
This looks reasonable.
