### PR TITLE
Dont let users run desynchronized unnoticed

### LINKED ISSUE #22338: Transient multiapp catch up does not properly catch up when one app has to run a longer time in first step
## Bug Description
A common simulation technique in multiphysics is to start solves at different times, so that at t=0s they are all synchronized and at steady state

However, if catch_up = true, the catching up only tries to match the main app dt, not catch up in time so that the apps synchornize. In this case we want to be using sub_cycling

But if we dont want that, then it still fails to realize it's caught up with its initial objective as this logic fails:
```
                  if (ex->getTime() + app_time_offset +
                          (ex->timestepTol() * std::abs(ex->getTime())) >=
                      target_time)
                    caught_up = true
```
target_time is based on main app time
there is no app_time_offset since we dont want the apps to remain disynchronized
ex->getTime() is in the subapp time

## Steps to Reproduce
Start subapp with start_time = -20
Set catch_up = true
Do not set a global time offset. If you set a global time offset, that means you want the app times not to synchronize, to stay offset

## Impact
Ugly initialization transient on MSFR coupled inputs happened and should not have

### PR DESCRIPTION
**Pull request by GiudGiud**
Closes #22338

let's see what breaks

### CODE REVIEW

File: framework/src/multiapps/TransientMultiApp.C [hunk 1]
```diff
@@ -217,6 +217,23 @@ TransientMultiApp::solveStep(Real dt, Real target_time, bool auto_advance)
...
         continue;
 
+      // Examine global time synchronization
+      if (!_sub_cycling && !_reset_happened)
+      {
+        // The multi-app general offset is substracted to go into local time.
+        if (std::abs(target_time - _app.getGlobalTimeOffset() - ex->getTime() - dt) >
+            ex->timestepTol())
+          mooseDoOnce(mooseWarning(
+              "The target time is desynchronized between this app and a subapp of a multi app.\n"
```
Comment (joshuahansel) [inline framework/src/multiapps/TransientMultiApp.C:227]: I (and probably other users) probably don't know what "target time" means. Either reword or at least use the vocabulary in documentation for `TransientMultiApp`.

File: framework/src/multiapps/TransientMultiApp.C [hunk 2]
```diff
@@ -418,21 +437,26 @@ TransientMultiApp::solveStep(Real dt, Real target_time, bool auto_advance)
                            << std::endl;
                 ex->incrementStepOrReject();
 
+                // Avoid numerical precision errors on target time
+                if (catch_up_time + catch_up_dt > dt)
+                  catch_up_dt = dt - catch_up_time;
```
Comment (joshuahansel) [inline framework/src/multiapps/TransientMultiApp.C:442]: This looks strange to me - `catch_up_time` is always equal to zero here, right? If so, why include it? This looks like it would just be replaceable with `catch_up_dt = min(catch_up_dt, dt);`, for example.

**Review by joshuahansel — CHANGES_REQUESTED** [review]

File: framework/src/multiapps/TransientMultiApp.C (hunk 2 above)
Comment (GiudGiud) [reply framework/src/multiapps/TransientMultiApp.C:442]: no it's not it builds up through the catch_up process. It could be for example:

catch_up_time = 0
catch_up_time = dt/4 (2 failures in a row)
catch_up_time = dt/2
and so on until we meet dt.

Comment (GiudGiud) [reply framework/src/multiapps/TransientMultiApp.C:442]: I ve done this because the previous time check criterion relied on the two time scales being synchronized

File: framework/src/multiapps/TransientMultiApp.C (hunk 1 above)
Comment (GiudGiud) [reply framework/src/multiapps/TransientMultiApp.C:227]: ok I just explained it.
target time is actually the terminology used for the steady state tol parameter and in the verbose logs for multiapps but I agree it doesnt jump to mind

Comment (joshuahansel) [reply framework/src/multiapps/TransientMultiApp.C]: Ok, thanks, you'll need to update your test accordingly with the new message.

**Comment by GiudGiud** [comment]
test failure is unrelated

**Review by joshuahansel — APPROVED** [review]

**Comment by GiudGiud** [comment]
thanks for the review
