### PR TITLE
fix eigen executioner on the displaced mesh

### LINKED ISSUE #6932: Eigen executioner does not work with displaced mesh properly
### Description of the enhancement or error report
The eigen executioners do not work properly with the displaced mesh currently. It appears that the solution on the displaced system is not implemented correctly.

### Rationale for the enhancement or information for reproducing the error
An existing eigen executioner test can be modified to reproduce the error, which will be included in the coming PR fixing the issue.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New capability.

### PR DESCRIPTION
**Pull request by YaqiWang**
Closes #6932. Also a non-used parameter `output_on_final` is removed.

### CODE REVIEW

**Comment by YaqiWang** [comment]
The fix is easy just adding few system updates. Can somebody explain to me what exactly `update()` is doing? The ugly part is that I have to save the old solution on the displaced system as I did for the nonlinear system.

**Comment by permcody** [comment]
You can see the doco and implementation here:
http://libmesh.github.io/doxygen/classlibMesh_1_1System.html#ab9d81ac9c1787c43fb87cf13d37741ee

**Comment by permcody** [comment]
Seems like a lot more code than I would have expected. Don't we already have several "save/restore" methods on displaced system? Also I see the test but where is the gold file and test spec file?

I think I'll have @andrsd or @friedmud take a look at this.

**Comment by YaqiWang** [comment]
Because the displacement is zero, I can reuse the old gold file. I also have to hide the two variables for displacement. I would like to have this save/restore in the base class.

**Comment by YaqiWang** [comment]
So the local solution is non-ghosted solution vector and current local solution is ghosted solution; `update()` does the communication and copy the local solution to current local solution. Is this correct? The naming in the system is confusing, I wish there is a better one on all of these solutions.

File: framework/src/executioners/EigenExecutionerBase.C [hunk 1]
```diff
@@ -120,6 +119,14 @@ EigenExecutionerBase::init()
   // normalize solution to make |Bx|=_eigenvalue, _eigenvalue at this point has the initialized value
   makeBXConsistent(_eigenvalue);
 
+  if ( _problem.getDisplacedProblem() != NULL )
+  {
+    _problem.getDisplacedProblem()->syncSolutions(*_problem.getNonlinearSystem().currentSolution(),
```
Comment (YaqiWang) [inline framework/src/executioners/EigenExecutionerBase.C]: so my understanding is that this function only copy the solutions of the undisplaced systems to the local solution (non-ghosted) of the displaced system, which explains why we need the following two lines.

File: framework/src/executioners/EigenExecutionerBase.C [hunk 2]
```diff
@@ -240,6 +249,8 @@ EigenExecutionerBase::inversePowerIteration(unsigned int min_iter,
     _problem.getAuxiliarySystem().copyOldSolutions();
     if ( _problem.getDisplacedProblem() != NULL )
     {
+      _problem.getDisplacedProblem()->nlSys().update();
```
Comment (YaqiWang) [inline framework/src/executioners/EigenExecutionerBase.C]: The reason we need these two lines is that in `FEProblem::solve()`, there is only `syncSolutions()`, but not the updates. I guess the more proper fix will be immediately performing update in `DisplaceProblem::syncSolutions()`. How does this sounds?

**Comment by andrsd** [comment]
So, the design of the displaced stuff is:
1. `DisplacedProblem` aggregates 2 `DisplacedSystem`s, one for nonlinear and one for aux variables.
2. `DisplacedSystem` inherits from `SystemTempl<>` which provides solution, solution old, solution older. If you need an extra vector to store stuff, add one to `DisplacedSystem`, and both NL and AUX versions will get the vector.  You seem to be storing 2 copies of NL and AUX (if this is on purpose, please, explain what is going on). Also `_sys_sol` seems like an incorrect name for a vector that stores flux.  Moreover, eigen solver may be used for something that is not flux, i.e. pick a better name.
3. Ideally, your executioner should work with DisplacedProblem and not exploit its internal structure, i.e. call displaced_problem->update(), and inside this function, do `nlSys().update; auxSys.update();`. Same for other functions like `saveOldSolutions()`.

**Comment by YaqiWang** [comment]
@andrsd I realized the relation between `DisplacedSystem` and `DisplacedProblem`. I have to create another copy of old and older solution vectors because they will be overwritten during the inverse power iteration. Basically before starting the power iteration, old and older solutions are backed up into these vectors. They will then be restored after the power iteration. I do not understand what you mean on `flux`. This is unnecessary if we are doing a stand-alone eigenvalue calculation but will be essential if the eigenvalue calculation is embedded at every time step of Transient, which is the case for depletion calculations. 

There is no `update()` in `FEProblem`. I think for fixing the eigen executioner, we possibly just need
```
_displaced_nl.update();
_displaced_aux.update();
```
at the end of `DisplacedProblem::syncSolutions()`.

File: framework/src/base/DisplacedSystem.C [hunk 3]
```diff
@@ -39,3 +44,39 @@ DisplacedSystem::getVector(std::string name)
...
+DisplacedSystem::saveOldSolutions()
+{
+  if (!_sys_sol_old)
+    _sys_sol_old= &addVector("save_flux_old", false, PARALLEL);
+  if (!_aux_sol_old)
+    _aux_sol_old = &_displaced_problem.auxSys().addVector("save_aux_old",  false, PARALLEL);
+  if (!_sys_sol_older)
+    _sys_sol_older = &addVector("save_flux_older", false, PARALLEL);
+  if (!_aux_sol_older)
+    _aux_sol_older = &_displaced_problem.auxSys().addVector("save_aux_older",  false, PARALLEL);
```
Comment (andrsd) [inline framework/src/base/DisplacedSystem.C]: In those 4 vectors, you use `flux`. That's what I meant....

**Comment by andrsd** [comment]
In regards to calling `DisplacedProblem`, maybe pseudo-code will make it more clear:
```
void DisplacedProblem::saveSolutions()
{
  nlSys().saveSolutions();
  auxSys().saveSolutions();
}
```

Then interaction with it, you do:
```
_fe_problem->getDisplacedProblem()->saveSolutions();
```
instead of:
```
_fe_problem->getDisplacedProblem()->nlSys().saveSolutions();
_fe_problem->getDisplacedProblem()->auxSys().saveSolutions();
```

File: framework/src/base/DisplacedSystem.C (hunk 3 above)
Comment (YaqiWang) [inline framework/src/base/DisplacedSystem.C]: ahoh... thanks.

I will need to ask your guys: can I move `saveSolutions()` into `SystemTempl<T>`? If so I can add them and remove those in `EigenSystem`.

Comment (andrsd) [inline framework/src/base/DisplacedSystem.C]: If you need to save the solutions both in non-displaced and displaced versions, then we could move it there, but we would want to allocate those vector only when we need them.

Comment (YaqiWang) [inline framework/src/base/DisplacedSystem.C]: Yes, they will be added when `saveSolutions()` is called like the current implementation and can be removed by `restoreSolutions()`.

Comment (andrsd) [inline framework/src/base/DisplacedSystem.C]: I thought `saveSolution()` would save the values of the vector, not that it would allocate it.  I think we need to allocate those vectors a bit earlier, right? Similarly, `restoreSolution()` would restore values, but would not deallocate the vector.

Comment (YaqiWang) [inline framework/src/base/DisplacedSystem.C]: Actually the old and older solution vectors need to be saved only for the inverse power iteration because the solution of previous iteration is using the old solution vector and the older solution vector. If the power iteration happens within a time step, we do not want the old solutions to be overwritten, so we save them and restore them after power iteration is done. The vector used for saving old solutions can be destroyed after power iteration is done to save memory. Does this make sense?

Comment (andrsd) [inline framework/src/base/DisplacedSystem.C]: All I am saying is that the names should be picked cautiously, so that for example `saveSolution()` will not add solution vector, which is how I understood your sentence: 

> Yes, they will be added when saveSolutions() is called

**Comment by YaqiWang** [comment]
I redid this PR, ready for your review. Thanks.

**Comment by YaqiWang** [comment]
Well, I am a little aggressive in this PR. It turns out I cannot simplify the interface of `syncSolutions()` and `updateMesh()` easily. But I believe it is the way to go. Fixing all depending codes is out of my scope, so I will stay with the old interface...

**Comment by permcody** [comment]
Well you can. You just have to deprecate the one and support the other for a little while. I really think I need to have a provision for allowing deprecated code in the test suite for things like this.

**Comment by YaqiWang** [comment]
I am not sure if it is proper for me to deprecate the code without other's agreement. But you give me a suggestion, I can let the two interface coexist. How this sounds?

File: framework/src/executioners/EigenExecutionerBase.C [hunk 4]
```diff
@@ -120,6 +119,9 @@ EigenExecutionerBase::init()
   // normalize solution to make |Bx|=_eigenvalue, _eigenvalue at this point has the initialized value
   makeBXConsistent(_eigenvalue);
 
+  if ( _problem.getDisplacedProblem() != NULL )
```
Comment (andrsd) [inline framework/src/executioners/EigenExecutionerBase.C]: No spaces inside `( )`

File: framework/src/executioners/EigenExecutionerBase.C [hunk 5]
```diff
@@ -197,7 +199,13 @@ EigenExecutionerBase::inversePowerIteration(unsigned int min_iter,
 
   // FIXME: currently power iteration use old and older solutions,
   // so save old and older solutions before they are changed by the power iteration
-  _eigen_sys.saveOldSolutions();
+  _problem.getNonlinearSystem().saveOldSolutions();
+  _problem.getAuxiliarySystem().saveOldSolutions();
```
Comment (andrsd) [inline framework/src/executioners/EigenExecutionerBase.C]: Nope, read [this comment](https://github.com/idaholab/moose/pull/6933#issuecomment-218308793) again.

File: framework/src/executioners/EigenExecutionerBase.C [hunk 6]
```diff
@@ -197,7 +199,13 @@ EigenExecutionerBase::inversePowerIteration(unsigned int min_iter,
...
+  if ( _problem.getDisplacedProblem() != NULL )
+  {
+    _problem.getDisplacedProblem()->nlSys().saveOldSolutions();
+    _problem.getDisplacedProblem()->auxSys().saveOldSolutions();
```
Comment (andrsd) [inline framework/src/executioners/EigenExecutionerBase.C]: Same here, see [this comment](https://github.com/idaholab/moose/pull/6933#issuecomment-218308793) again.

File: framework/src/executioners/EigenExecutionerBase.C [hunk 7]
```diff
@@ -344,7 +352,13 @@ EigenExecutionerBase::inversePowerIteration(unsigned int min_iter,
   _problem.es().parameters.set<Real> ("nonlinear solver relative residual tolerance") = tol2;
 
   //FIXME: currently power iteration use old and older solutions, so restore them
-  _eigen_sys.restoreOldSolutions();
+  _problem.getNonlinearSystem().restoreOldSolutions();
+  _problem.getAuxiliarySystem().restoreOldSolutions();
+  if ( _problem.getDisplacedProblem() != NULL )
+  {
+    _problem.getDisplacedProblem()->nlSys().restoreOldSolutions();
+    _problem.getDisplacedProblem()->auxSys().restoreOldSolutions();
```
Comment (andrsd) [inline framework/src/executioners/EigenExecutionerBase.C]: And same here...

File: framework/src/executioners/EigenExecutionerBase.C (hunk 5 above)
Comment (YaqiWang) [inline framework/src/executioners/EigenExecutionerBase.C]: yeah, i understand, but it requires creating a function in `FEProblem` and `DisplacedProblem`. I do not think it is necessary.

File: framework/include/base/SystemBase.h [hunk 8]
```diff
@@ -512,8 +514,71 @@ class SystemTempl : public SystemBase
...
+   * Adds a solution length vector to the system.
+   *
+   * @param vector_name The name of the vector.
+   * @param project Whether or not to project this vector when doing mesh refinement.
+   *                If the vector is just going to be recomputed then there is no need to project it.
+   * @param type What type of parallel vector.  This is usually either PARALLEL or GHOSTED.
+   *                                            GHOSTED is needed if you are going to be accessing off-processor entries.
+   *                                            The ghosting pattern is the same as the solution vector.
+   */
+  virtual NumericVector<Number>& addVector(const std::string & vector_name, const bool project, const ParallelType type)
```
Comment (andrsd) [inline framework/include/base/SystemBase.h]: What happened to `zero_for_residual` which worked in `NonlinearSystem`?

File: framework/src/executioners/EigenExecutionerBase.C (hunk 6 above)
Comment (YaqiWang) [inline framework/src/executioners/EigenExecutionerBase.C]: Same here. To me `FEProblem` is already too heavy.

File: framework/src/executioners/EigenExecutionerBase.C (hunk 7 above)
Comment (YaqiWang) [inline framework/src/executioners/EigenExecutionerBase.C]: Yes, same here. We will need to have others' opinion if we both insist, hehe.

File: framework/include/base/SystemBase.h (hunk 8 above)
Comment (YaqiWang) [inline framework/include/base/SystemBase.h]: Added a new function in `NonlinearSystem`. I realized that heat conduction module is using that capability.

File: framework/src/executioners/EigenExecutionerBase.C (hunk 5 above)
Comment (andrsd) [inline framework/src/executioners/EigenExecutionerBase.C]: In good OOP design, you call methods on class instances without knowing the inside of the class. The class itself knows the best what to do. Not the caller.

**Comment by YaqiWang** [comment]
Weird, I cannot reproduce the error in dbg mode on my mac.

**Comment by YaqiWang** [comment]
Turns out I have a misunderstanding on `currentSolution()` and `solution()` in moose system. I think it will be much better to add some doxygen comments in these functions in `SystemBase.h`.

**Comment by YaqiWang** [comment]
Ready for your review.

**Comment by YaqiWang** [comment]
@andrsd Can you review this?

**Comment by andrsd** [comment]
1. When we need an extra `NumericVector`, we add it at the beginning, use it, then deallocate it at the end. If I understand correctly, you are adding and removing those extra vectors, within a time step.

2. You are still doing:
```
_problem.nl()->something();
_problem.aux()->something();
```
I am against it. As I said before, it should be `_problem->something()`.

**Comment by YaqiWang** [comment]
1. Yes, if the inverse power iteration is embedded in Transient.
2. Since I really want this to be merged, I will make the change...

**Comment by YaqiWang** [comment]
@andrsd your comments are addressed.

File: framework/include/base/SystemBase.h [hunk 9]
```diff
@@ -512,8 +514,71 @@ class SystemTempl : public SystemBase
...
+    return *vec;
+  }
+
+  /**
+   * Save the old and older solutions.
+   */
+  virtual void saveOldSolutions()
+  {
+    if (!_saved_old)
+      _saved_old= &addVector("save_solution_old", false, PARALLEL);
```
Comment (andrsd) [inline framework/include/base/SystemBase.h]: Missing a space `_saved_old =`

File: framework/include/base/SystemBase.h (hunk 8 above)
Comment (andrsd) [inline framework/include/base/SystemBase.h]: Missing a space here between `>` and `&`.

**Comment by andrsd** [comment]
2 small formatting issues, otherwise good to go in.

**Comment by YaqiWang** [comment]
Should be ready for merge.

**Comment by andrsd** [comment]
👍
