### PR TITLE
Protect against zero size dof dependence before libMesh constraints

### LINKED ISSUE #17755: DGEMM error
## Bug Description

These are the minimal input files I can make. It uses a kernel from the phase-field module.

Here are the two input files:

This is the "bad" one that produces the error ` ** On entry to DGEMM parameter number  8 had an illegal value`
```
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 2
    ny = 2
  []
[]

[Variables]
  [d]
  []
[]

[Kernels]
  [time]
    type = ADTimeDerivative
    variable = d
  []
  [diff]
    type = ADDiffusion
    variable = d
  []
  [ac]
    type = ADAllenCahn
    variable = d
    f_name = F
    mob_name = L
  []
  [body]
    type = BodyForce
    variable = d
    function = 10
  []
[]

[Materials]
  [L]
    type = ADGenericConstantMaterial
    prop_names = 'L'
    prop_values = '1'
  []
  [F]
    type = ADDerivativeParsedMaterial
    f_name = F
    function = 'd'
    args = d
    derivative_order = 2
  []
[]

[BCs]
  [Periodic]
    [all]
      variable = d
      auto_direction = 'x y'
    []
  []
[]

[Executioner]
  type = Transient
  solve_type = 'NEWTON'
  petsc_options_iname = '-pc_type'
  petsc_options_value = 'lu      '
  num_steps = 1

  abort_on_solve_fail = true
[]
```

This is the "good" one that doesn't produce the error:
```
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 2
    ny = 2
  []
[]

[Variables]
  [d]
  []
[]

[Kernels]
  [time]
    type = TimeDerivative
    variable = d
  []
  [diff]
    type = Diffusion
    variable = d
  []
  [ac]
    type = AllenCahn
    variable = d
    f_name = F
    mob_name = L
  []
  [body]
    type = BodyForce
    variable = d
    function = 10
  []
[]

[Materials]
  [L]
    type = GenericConstantMaterial
    prop_names = 'L'
    prop_values = '1'
  []
  [F]
    type = DerivativeParsedMaterial
    f_name = F
    function = 'd'
    args = d
    derivative_order = 2
  []
[]

[BCs]
  [Periodic]
    [all]
      variable = d
      auto_direction = 'x y'
    []
  []
[]

[Executioner]
  type = Transient
  solve_type = 'NEWTON'
  petsc_options_iname = '-pc_type'
  petsc_options_value = 'lu      '
  num_steps = 1

  abort_on_solve_fail = true
[]
```

Notice that these two input files should be identical in terms of residual. The "bad" one uses AD, and the "good" one doesn't.
What's interesting is that if I remove the periodic BC in the "bad" one the error is gone.

## Steps to Reproduce

Run the "bad" input file with the default config.

## Impact

This breaks several models in my App.

### PR DESCRIPTION
**Pull request by lindsayad**
If we call `constrain_element_matrix` with zero size column indices then
we get errors out of BLAS. This was happening with global AD indexing
since global AD indexing in general only inserts nonzero degree of
freedom dependence.

Test to come. Necessary condition to trigger this error:
- using AD objects with global AD indexing when said objects may not
  have any nonlinear variable dependence (like `ADBodyForce`)
- Have some libmesh constraints like hanging nodes or periodic
  boundaries

Closes #17755

### CODE REVIEW

**Review by hugary1995 — APPROVED** [review]
Looks good to me, and I can confirm this patch fixes the bug in my app. But I'm not on CCB.

File: framework/include/base/Assembly.h [hunk 1]
```diff
@@ -2771,11 +2771,19 @@ Assembly::processDerivatives(const std::vector<ADReal> & residuals,
...
+                "dependence (as indicated by the dof index set held by the ADReal) has to be the "
+                "same for every residual passed to this method otherwise constrain_element_matrix "
+                "will not work.");
   }
 #endif
   auto column_indices = std::vector<dof_id_type>(compare_dofs.begin(), compare_dofs.end());
 
+  // If there's no derivatives then there is nothing to do. Moreover, if we pass zero size column
+  // indices to constrain_element_matrix then we will potentially get errors out of BLAS
+  if (!column_indices.size())
```
Comment (fdkong) [inline framework/include/base/Assembly.h:2784]: I would think this handle both mesh adaptivity and periodic boundary conditions?

Comment (fdkong) [reply framework/include/base/Assembly.h:2784]: Ideally, libmesh should be able to handle this since this is an empty matrix. But this fix is good anyway.

**Review by fdkong — APPROVED** [review]
