### PR TITLE
Fix threading bug with ConstitutiveModel creation

### LINKED ISSUE #5551: Solid mechanics models that use ConstitutiveModel are broken with multithreading
If any solid_mechanics model that calls createConstitutiveModel() to create a ConstitutiveModel based material model is used, it will fail if run multithreaded.  For example, the test:
moose/modules/solid_mechanics/tests/thermal_expansion_function/thermal_expansion_function_const_alpha_test.i
will fail with an error like this if run with --n_threads=2:
An object already exists with the name mean_alphaModel

This used to work.  I thought we automatically ran the tests with multithreading and parallelism, no?

I'm working on a fix for this.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #5551

### CODE REVIEW

**Comment by bwspenc** [comment]
That moose_PR_test seems to be a random failure.  This is a modules-only commit.

File: modules/solid_mechanics/src/materials/SolidModel.C [hunk 1]
```diff
@@ -1470,7 +1470,7 @@ SolidModel::createConstitutiveModel(const std::string & cm_name, const InputPara
 {
 
   Factory & factory = _app.getFactory();
-  MooseSharedPointer<ConstitutiveModel> cm = MooseSharedNamespace::dynamic_pointer_cast<ConstitutiveModel>(factory.create(cm_name, name()+"Model", params));
+  MooseSharedPointer<ConstitutiveModel> cm = MooseSharedNamespace::dynamic_pointer_cast<ConstitutiveModel>(factory.create(cm_name, name()+"Model", params, _tid));
```
Comment (jwpeterson) [inline modules/solid_mechanics/src/materials/SolidModel.C]: This line of code is quite a mouthful!

Comment (bwspenc) [inline modules/solid_mechanics/src/materials/SolidModel.C]: It's not my fault.  All I did is add 5 measly characters.
