### PR TITLE
expand InterfaceUO capabilities

### LINKED ISSUE #14680: InterfaceUserObject can NOT get MaterialProperty and NeighborMaterialProperty
## Bug Description
`InterfaceUserObject` can't properly get neighbor material property.
@lindsayad  The introduction of the interface material should have granted this to work automatically but apparently it doesn't and I can't figure out where the problem is.

## Steps to Reproduce
I prepared a branch here demonstrating the issue [interfaceUO_neighbor_material](https://github.com/arovinelli/moose/tree/interfaceUO_neighbor_material)
execute the `/moose/test/tests/userobjects/interface_user_object/interface_material_value_user_object_QP.i` test and see that _mp[qp] and _mp_neighbor[qp]  are always 0, when they should be 10 and 4, respectively, after one step 

## Impact
This does prevent user to compute interface average values material properties, and yes does prevent some of my work to be done

### PR DESCRIPTION
**Pull request by arovinelli**
The aim of this PR is to expand the `InterfaceUserObject` capabilities and to refactor the structure of the `InterfaceQPValue` to allow for more robust implementation and easier subclassing.

`feProblemBase` and `ComputeUserObjectsThread` has been updated to allow the `InterfaceUserObject` to properly collect material properties.
 Specific test materials and auxkernel were introduce to test the implementations.

A base class named `InterfaceQpUserObjectBase` was introduced to simplify override. 
This base class now allows to return `qp` and `sideaverage` values from other moose systems.
It also give options to not only compute interface values but also their rate and increment.
The `InterfaceValueUserObjectAux` was modified to work on `InterfaceQpUserObjectBase` derived classes.

The `InterfaceQpMaterialPropertyBaseUserObject` was added. This class is templated to facilitate the override process.
The `InterfaceQpMaterialPropertyRealUO` was also added.

closes #14680

### CODE REVIEW

**Comment by arovinelli** [comment]
@lindsayad and @permcody this is ready for review

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+  /**
+   * Class constructor
+   * @param parameters The input parameters for this object
+   */
+  InterfaceQpMaterialPropertyBaseUserObject(const InputParameters & parameters);
+  virtual ~InterfaceQpMaterialPropertyBaseUserObject(){};
+
+protected:
+  /* method computing the real value*/
+  virtual Real computeRealValue(const unsigned int qp) override final
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: I would prefer that the definition be outside the class body. Its best for developers trying to get a grasp of a class API to scroll through as few lines as possible. If (longer than one or two line) definitions are included in the class body, it takes much longer to scroll

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+  {
+    if (!_compute_rate && !_compute_increment)
+    {
+      return computeInterfaceValueType(computeScalarMaterialProperty(&_prop, qp),
+                                       computeScalarMaterialProperty(&_prop_neighbor, qp));
+    }
+    else
+    {
+
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: Unnecessary space

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        {
+          value_master /= _dt;
+          value_slave /= _dt;
+        }
+      }
+      return computeInterfaceValueType(value_master, value_slave);
+    }
+  };
+
+  /*template for computing a scalar material property value*/
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: doxygen comment please. Also try avoiding the word "template" since this is not a template method

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+#pragma once
+
+#include "InterfaceQpUserObjectBase.h"
+
+// Forward declarations
+template <typename T = Real>
+class InterfaceQpMaterialPropertyBaseUserObject;
+
+template <>
+InputParameters validParams<InterfaceQpMaterialPropertyBaseUserObject<>>();
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: @permcody can correct me, but since this way of doing `validParams` is "legacy" we probably shouldn't add it for new objects

File: framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+   */
+  InterfaceQpMaterialPropertyRealUO(const InputParameters & parameters);
+  virtual ~InterfaceQpMaterialPropertyRealUO(){};
+
+protected:
+  /// return the material property value at the give qp
+  virtual Real computeScalarMaterialProperty(const MaterialProperty<Real> * p,
+                                             const unsigned int qp) override final
+  {
+    return (*p)[qp];
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h]: 👍 A one-line method definition can stay inside the class definition.

File: framework/include/userobject/InterfaceQpUserObjectBase.h [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceValueUserObject.h"
+
+class InterfaceQpUserObjectBase;
+
+template <>
+InputParameters validParams<InterfaceQpUserObjectBase>();
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpUserObjectBase.h]: legacy

File: framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+//* All rights reserved, see COPYRIGHT for full restrictions
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+// MOOSE includes
+#include "InterfaceQpMaterialPropertyBaseUserObject.h"
+
+defineLegacyParams(InterfaceQpMaterialPropertyBaseUserObject<>);
```
Comment (lindsayad) [inline framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C]: Should be able to remove this entire file

File: framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+      "Computes the value, rate or increment of a Real Material property across an "
+      "interface. The value or rate is computed according to the provided "
+      "interface_value_type parameter");
+  return params;
+}
+
+InterfaceQpMaterialPropertyRealUO::InterfaceQpMaterialPropertyRealUO(
+    const InputParameters & parameters)
+  : InterfaceQpMaterialPropertyBaseUserObject<Real>(parameters)
+
```
Comment (lindsayad) [inline framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C]: Unnecessary space

File: test/include/materials/LinearNonLinearIterationInterfaceMaterial.h [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+
+#pragma once
+
+#include "InterfaceMaterial.h"
+
+// Forward Declarations
+class LinearNonLinearIterationInterfaceMaterial;
+
+template <>
+InputParameters validParams<LinearNonLinearIterationInterfaceMaterial>();
```
Comment (lindsayad) [inline test/include/materials/LinearNonLinearIterationInterfaceMaterial.h]: legacy

File: test/include/materials/LinearNonLinearIterationMaterial.h [hunk 10]
```diff
@@ -0,0 +1,33 @@
...
+
+#pragma once
+
+#include "Material.h"
+
+// Forward Declarations
+class LinearNonLinearIterationMaterial;
+
+template <>
+InputParameters validParams<LinearNonLinearIterationMaterial>();
```
Comment (lindsayad) [inline test/include/materials/LinearNonLinearIterationMaterial.h]: legacy

File: test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceUserObject.h"
+
+class InterfaceUserObjectTestGetMaterialProperty;
+
+template <>
+InputParameters validParams<InterfaceUserObjectTestGetMaterialProperty>();
```
Comment (lindsayad) [inline test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h]: legacy

File: test/src/materials/LinearNonLinearIterationInterfaceMaterial.C [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+    _mat_prop(declareProperty<Real>(getParam<MaterialPropertyName>("prop_name"))),
+    _prefactor(getParam<Real>("prefactor"))
+{
+}
+
+void
+LinearNonLinearIterationInterfaceMaterial::computeQpProperties()
+{
+  _mat_prop[_qp] =
+      (_t_step + _fe_problem.nNonlinearIterations() * _fe_problem.nLinearIterations()) * _prefactor;
```
Comment (lindsayad) [inline test/src/materials/LinearNonLinearIterationInterfaceMaterial.C]: This is a bit scary. Are you doing `Exodiff` or similar on a field related to this? If we try to update PETSc and somehow a solve takes a different number of iterations, then this would have to be regolded and/or we'd have to slap a specific petsc_version number on this test

File: test/src/materials/LinearNonLinearIterationMaterial.C [hunk 13]
```diff
@@ -0,0 +1,40 @@
...
+    _mat_prop(declareProperty<Real>(getParam<MaterialPropertyName>("prop_name"))),
+    _prefactor(getParam<Real>("prefactor"))
+{
+}
+
+void
+LinearNonLinearIterationMaterial::computeQpProperties()
+{
+  _mat_prop[_qp] =
+      (_t_step + _fe_problem.nNonlinearIterations() * _fe_problem.nLinearIterations()) * _prefactor;
```
Comment (lindsayad) [inline test/src/materials/LinearNonLinearIterationMaterial.C]: Same concern

File: test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+    // insert two vector value for each qp
+    auto & vec = _map_values[std::make_pair(_current_elem->id(), _current_side)];
+    vec.resize(_qrule->n_points());
+
+    // loop over qps and do stuff
+    for (unsigned int qp = 0; qp < _qrule->n_points(); ++qp)
+    {
+      // check material property values
+
+      mooseAssert(
```
Comment (lindsayad) [inline test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C]: Unnecessary space. If we're just doing equality asserts, and we're not doing any file testing, then you can ignore my concerns above

File: test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i [hunk 15]
```diff
@@ -0,0 +1,194 @@
...
+    full = TRUE
+  [../]
+[]
+
+[Executioner]
+  type = Transient
+  solve_type = 'NEWTON'
+
+  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package'
+  petsc_options_value = ' lu       superlu_dist                '
```
Comment (lindsayad) [inline test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i]: Are you doing LU in order to control the iteration count?

**Review by lindsayad — CHANGES_REQUESTED** [review]
Looking good!

File: test/src/materials/LinearNonLinearIterationInterfaceMaterial.C (hunk 12 above)
Comment (arovinelli) [reply test/src/materials/LinearNonLinearIterationInterfaceMaterial.C]: @lindsayad I see your point, however I thought about it. This material is. used in a test that only errors out if and when the material property is not equal to the theoretical material property compute inside the test user object. The test uses a `RunApp` spec and is completely independent from the obtained solution. As long as the test converges and no error are generated this is fine.

File: test/src/materials/LinearNonLinearIterationMaterial.C (hunk 13 above)
Comment (arovinelli) [reply test/src/materials/LinearNonLinearIterationMaterial.C]: as before

File: test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i (hunk 15 above)
Comment (arovinelli) [reply test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i]: no control on the number of linear and nonlinear iterations. The test doesn't care as long as it can go forward without warring out

File: test/include/materials/LinearNonLinearIterationInterfaceMaterial.h (hunk 9 above)
Comment (arovinelli) [reply test/include/materials/LinearNonLinearIterationInterfaceMaterial.h]: I tried removing the legacy line, it compiles but it errors out on execution complaining about undefined parameters

File: test/include/materials/LinearNonLinearIterationMaterial.h (hunk 10 above)
Comment (arovinelli) [reply test/include/materials/LinearNonLinearIterationMaterial.h]: as before

File: test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h (hunk 11 above)
Comment (arovinelli) [reply test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h]: as before

File: framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C (hunk 8 above)
Comment (arovinelli) [reply framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C]: removed

File: framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C (hunk 7 above)
Comment (arovinelli) [reply framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C]: ideally yes, but if I move everything to header then it sone't like it (compiles but complains about missing reference before execution)

File: framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h (hunk 5 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h]: I ty to keep the mind

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 4 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: As I explained below, I tried, but I wasn't able to remove the line. @permcody do you have any example of registered class without the incremented line

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 3 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: should be goof now

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 2 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: removed

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 1 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: I moved all definitions to the C files

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+  static InputParameters validParams();
+  /**
+   * Class constructor
+   * @param parameters The input parameters for this object
+   */
+  InterfaceQpMaterialPropertyBaseUserObject(const InputParameters & parameters);
+  virtual ~InterfaceQpMaterialPropertyBaseUserObject(){};
+
+protected:
+  /* method computing the real value*/
```
[the remark this answers is not in the document]
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: done

**Comment by arovinelli** [comment]
ok implicit fallthroug was sed on purpose but I get this error `InterfaceQpMaterialPropertyBaseUserObject.C:56:9: error: this statement may fall through [-Werror=implicit-fallthrough=]` from civet... I'll fix this now

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 4 above)
Comment (lindsayad) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: It's pretty lame if this is simultaneously legacy and we can't create new objects without it

File: framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C (hunk 7 above)
Comment (lindsayad) [reply framework/src/userobject/InterfaceQpMaterialPropertyBaseUserObject.C]: I meant that we didn't need any of the code in this file, e.g. you should delete the code...but if legacy really doesn't mean legacy then you're good

File: framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C (hunk 8 above)
Comment (lindsayad) [reply framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C]: Hmm, it looks like it's still here to me...it's not a huge deal

File: test/src/materials/LinearNonLinearIterationInterfaceMaterial.C (hunk 12 above)
Comment (lindsayad) [reply test/src/materials/LinearNonLinearIterationInterfaceMaterial.C]: Excellent!

File: test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i (hunk 15 above)
Comment (lindsayad) [reply test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i]: K, if you end up doing another commit, go ahead and remove these lines then. It's best if new users who come along and look at our test files as examples don't default to using LU

**Comment by lindsayad** [comment]
> ok implicit fallthroug was sed on purpose but I get this error `InterfaceQpMaterialPropertyBaseUserObject.C:56:9: error: this statement may fall through [-Werror=implicit-fallthrough=]` from civet... I'll fix this now

If you really want a fallthrough, you can use `libmesh_fallthrough()`

File: test/include/materials/LinearNonLinearIterationInterfaceMaterial.h (hunk 9 above)
Comment (lindsayad) [reply test/include/materials/LinearNonLinearIterationInterfaceMaterial.h]: Can you share the exact error?

**Comment by arovinelli** [comment]
> > ok implicit fallthroug was sed on purpose but I get this error `InterfaceQpMaterialPropertyBaseUserObject.C:56:9: error: this statement may fall through [-Werror=implicit-fallthrough=]` from civet... I'll fix this now
> 
> If you really want a fallthrough, you can use `libmesh_fallthrough()`

@ lindsayad thanks. I embrace your decision as I think the code is a more clear without the fallthrough. By the way, do you have any idea what the error in the documentation test means? To me the code seems correct

**Comment by lindsayad** [comment]
Yea, that's not your fault...

**Comment by arovinelli** [comment]
> Yea, that's not your fault...

@lindsayad @permcody wondering what's going on in the documentation test. Beside this issue, this  PR is ready for review.

File: test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i (hunk 15 above)
Comment (arovinelli) [reply test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i]: done

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 4 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: @lindsayad for some of the objects I can remove the valiParam 
for other I get this kid of error but I don't understand why
```
/home/arovinelli/projects/NEW_stuff/moose/framework/src/userobject/InterfaceValueUserObject.C:15:39: error: specialization of ‘InputParameters validParams() [with T = InterfaceValueUserObject]’ after instantiation
 validParams<InterfaceValueUserObject>()
```

the incriminated classes are `InterfaceValueUserObject` and `InterfaceQpUserObjectBase`

**Comment by arovinelli** [comment]
@lindsayad I finally figure out what was wrong. Now the code should all be nonLegacy and using the proper static validParams method.
Please give this another check when you have time but we should be close to merge. Also, let me know if you want to squash commits

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 17]
```diff
@@ -0,0 +1,120 @@
...
+#pragma once
+
+#include "InterfaceQpUserObjectBase.h"
+
+// Forward declarations
+template <typename T = Real>
+class InterfaceQpMaterialPropertyBaseUserObject;
+
+// template <>
+// InputParameters validParams<InterfaceQpMaterialPropertyBaseUserObject<>>();
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: Remove this entirely

**Review by lindsayad — CHANGES_REQUESTED** [review]
@permcody can correct me if I'm wrong but I believe that the general MOOSE style is to use
```
/**
 *
**/
```
style doxygen for methods and
```
///
```
style for data members. This is not something I really care about, but we should be consistent.

All the content looks good. I would like commits squashed within reason. Definitely commits with messages like "argh" probably shouldn't make it in 😆

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 17 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: ups I'm sorry about that
I tried so many different ways that  I confused myself.

I have one question though: all the interfaceUO use neighbors and should have relationship manger. What is need is a relationship manager with a layer of connected nodes, not element (think at tets or tri meshes ). This will ensure that when coupling variables we don't miss stuff. is there any example for this?

**Comment by lindsayad** [comment]
The current ghosting functor API only works for elements so you’ll just have to ghost the elements owning those interface nodes

**Comment by arovinelli** [comment]
> The current ghosting functor API only works for elements so you’ll just have to ghost the elements owning those interface nodes
> […](#)
> On Feb 13, 2020, at 6:18 PM, Andrea Rovinelli ***@***.***> wrote: ﻿ @arovinelli commented on this pull request. In framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h: > +// template <> +// InputParameters validParams<InterfaceQpMaterialPropertyBaseUserObject<>>(); ups I'm sorry about that I tried so many different ways that I confused myself. I have one question though: all the interfaceUO use neighbors and should have relationship manger. What is need is a relationship manager with a layer of connected nodes, not element (think at tets or tri meshes ). This will ensure that when coupling variables we don't miss stuff. is there any example for this? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

OK, I assume this is the same this is the same you added for the `InterfaceMaterial`, or maybe not?

**Comment by arovinelli** [comment]
> The current ghosting functor API only works for elements so you’ll just have to ghost the elements owning those interface nodes
> […](#)
> On Feb 13, 2020, at 6:18 PM, Andrea Rovinelli ***@***.***> wrote: ﻿ @arovinelli commented on this pull request. In framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h: > +// template <> +// InputParameters validParams<InterfaceQpMaterialPropertyBaseUserObject<>>(); ups I'm sorry about that I tried so many different ways that I confused myself. I have one question though: all the interfaceUO use neighbors and should have relationship manger. What is need is a relationship manager with a layer of connected nodes, not element (think at tets or tri meshes ). This will ensure that when coupling variables we don't miss stuff. is there any example for this? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I believe this is what you where referring to as point neighbor RM

```
  params.addRelationshipManager("MooseGhostPointNeighbors",
                                Moose::RelationshipManagerType::GEOMETRIC);
```

**Comment by arovinelli** [comment]
@lindsayad this ready for final review

**Comment by arovinelli** [comment]
ok this error has nothing to do with the userobject itself but it's related to the executioner type.
Apparently something awkward happens with MooseGhostPointNeighbors and steady executioner.
I'll change the test regold the file and submit the final PR. I will also open a ticket for this unless you already know about this behavior

**Comment by arovinelli** [comment]
@lindsay it seems that GhostPointNeighbors is not a good choice at the moment as it generate errors on recover. Actually we don't need GhostPointNeighbors (variable values at nodes sharing more elements should still be correct in case of ghosting). So I roll back at elementSideNeighbors ghosting. now finger crossed

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h [hunk 18]
```diff
@@ -0,0 +1,120 @@
...
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceQpUserObjectBase.h"
+
+// Forward declarations
+template <typename T = Real>
+class InterfaceQpMaterialPropertyBaseUserObject;
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: You can remove this; the forward declaration here is serving no purpose

File: test/src/auxkernels/StatefuleAux.C [hunk 19]
```diff
@@ -0,0 +1,33 @@
+//* This file is part of the MOOSE framework
```
Comment (lindsayad) [inline test/src/auxkernels/StatefuleAux.C]: Uh oh, this file should be named `StatefulAux.C`

File: test/include/materials/LinearNonLinearIterationInterfaceMaterial.h (hunk 9 above)
Comment (lindsayad) [reply test/include/materials/LinearNonLinearIterationInterfaceMaterial.h]: Do we still need this one?

File: test/include/auxkernels/StatefulAux.h [hunk 20]
```diff
@@ -0,0 +1,31 @@
...
+  static InputParameters validParams();
+
+  StatefulAux(const InputParameters & parameters);
+
+  virtual ~StatefulAux() {}
+
+protected:
+  virtual Real computeValue();
+
+  int _coupled;                           ///< The number of the coupled variable
```
Comment (lindsayad) [inline test/include/auxkernels/StatefulAux.h]: This should be an `unsigned int` instead of signed

File: test/include/materials/LinearNonLinearIterationMaterial.h (hunk 10 above)
Comment (lindsayad) [reply test/include/materials/LinearNonLinearIterationMaterial.h]: Do we still need this one?

File: test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h (hunk 11 above)
Comment (lindsayad) [reply test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h]: Do we still need this one? I don't consider these a roadblock to merging; I only ask because I thought you indicated you were able to rip all the legacy out

File: test/src/materials/LinearNonLinearIterationInterfaceMaterial.C [hunk 21]
```diff
@@ -0,0 +1,42 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "LinearNonLinearIterationInterfaceMaterial.h"
+
+registerMooseObject("MooseTestApp", LinearNonLinearIterationInterfaceMaterial);
+
+defineLegacyParams(LinearNonLinearIterationInterfaceMaterial);
```
Comment (lindsayad) [inline test/src/materials/LinearNonLinearIterationInterfaceMaterial.C]: ?

File: test/src/materials/LinearNonLinearIterationMaterial.C [hunk 22]
```diff
@@ -0,0 +1,42 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "LinearNonLinearIterationMaterial.h"
+
+registerMooseObject("MooseTestApp", LinearNonLinearIterationMaterial);
+
+defineLegacyParams(LinearNonLinearIterationMaterial);
```
Comment (lindsayad) [inline test/src/materials/LinearNonLinearIterationMaterial.C]: ?

File: test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C [hunk 23]
```diff
@@ -0,0 +1,113 @@
...
+//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#include "InterfaceUserObjectTestGetMaterialProperty.h"
+
+registerMooseObject("MooseTestApp", InterfaceUserObjectTestGetMaterialProperty);
+
+defineLegacyParams(InterfaceUserObjectTestGetMaterialProperty);
```
Comment (lindsayad) [inline test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C]: ?

File: framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h [hunk 24]
```diff
@@ -0,0 +1,40 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceQpMaterialPropertyBaseUserObject.h"
+
+// Forward declarations
+class InterfaceQpMaterialPropertyRealUO;
```
Comment (lindsayad) [inline framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h]: Can remove

File: test/include/materials/LinearNonLinearIterationInterfaceMaterial.h [hunk 25]
```diff
@@ -0,0 +1,36 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "InterfaceMaterial.h"
+
+// Forward Declarations
+class LinearNonLinearIterationInterfaceMaterial;
```
Comment (lindsayad) [inline test/include/materials/LinearNonLinearIterationInterfaceMaterial.h]: If we can remove the legacy validParams, then we can also remove this forward declaration

File: test/include/materials/LinearNonLinearIterationMaterial.h [hunk 26]
```diff
@@ -0,0 +1,36 @@
...
+//*
+//* Licensed under LGPL 2.1, please see LICENSE for details
+//* https://www.gnu.org/licenses/lgpl-2.1.html
+
+#pragma once
+
+#include "Material.h"
+
+// Forward Declarations
+class LinearNonLinearIterationMaterial;
```
Comment (lindsayad) [inline test/include/materials/LinearNonLinearIterationMaterial.h]: If we can remove the legacy validParams, we can remove this forward declaration

**Review by lindsayad — CHANGES_REQUESTED** [review]
If we can fixup the remaining legacy stuff, that would be great. No worries if not.

Also can remove those forward declares.

Main thing is to change to `unsigned int` for the coupled var and to rename that file. After that I promise I'll approve! 😄 sorry didn't catch these earlier

**Comment by arovinelli** [comment]
> If we can fixup the remaining legacy stuff, that would be great. No worries if not.
> 

@lindsayad I completely forgot about legacy stuff in the test dir. Now it's clean.

> Also can remove those forward declares.
> 

No more forward declaration, I should have removed all of them.

> Main thing is to change to `unsigned int` for the coupled var and to rename that file. After that I promise I'll approve! 😄 sorry didn't catch these earlier


File renamed and unsigned int fixed, so it should be ready!

File: test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C (hunk 23 above)
Comment (arovinelli) [reply test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C]: removed

File: test/src/materials/LinearNonLinearIterationInterfaceMaterial.C (hunk 21 above)
Comment (arovinelli) [reply test/src/materials/LinearNonLinearIterationInterfaceMaterial.C]: removed

File: test/include/auxkernels/StatefulAux.h (hunk 20 above)
Comment (arovinelli) [reply test/include/auxkernels/StatefulAux.h]: should be ok now

File: test/src/auxkernels/StatefuleAux.C (hunk 19 above)
Comment (arovinelli) [reply test/src/auxkernels/StatefuleAux.C]: fixed

File: framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h (hunk 4 above)
Comment (arovinelli) [reply framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h]: This was my fault, a template was missing a `T` in a templete

**Review by lindsayad — APPROVED** [review]
