### PR TITLE
Insert dependencies from discrete materials

### LINKED ISSUE #18726: `getMaterial` doesn't insert dependencies of the retrieved material into the retriever.
## Bug Description

As title suggests. This issue requires late binding of `getMaterial` #18725.

### PR DESCRIPTION
**Pull request by hugary1995**
Currently when we retrieve a discrete materials, we touch nothing about its dependencies. This leads to a weird situation where, when a discrete material is called by its hosting material, its dependencies may have not been evaluated. To avoid this situation, I propose to add the materials requested by the discrete material into the hosting material trying to retrieve the discrete material. I am now restricting the retrieval of discrete materials to the initial setup, so that we only need one more dependency resolution after the initial setup.

close #18726

### CODE REVIEW

**Comment by hugary1995** [comment]
Git blame tells me @permcody might be the right one to review this, but that was from 6 years ago... 

@loganharbour Could you please suggest other reviewers that are familiar with this part of the code. Thanks.

File: framework/include/materials/Material.h [hunk 1]
```diff
@@ -140,16 +140,29 @@ class Material : public MaterialBase, public Coupleable, public MaterialProperty
   }
 
   /**
-   * Retrieve the dicrete material named "name"
+   * Retrieve the dicrete material named "name".
+   *
+   * @param no_warn If true, suppress warning about retrieving the material potentially during its
+   * calculation. If you don't know what this is/means, then you don't need it.
+   * @param no_dep Use no_dep = true if no dependencies of the material is required. Using no_dep =
```
Comment (dschwen) [inline framework/include/materials/Material.h:147]:
```suggestion
   * @param no_dep Use no_dep = true if no dependency resolution for the material is required. Using no_dep =
```

**Review by dschwen — DISMISSED** [review]
Looks good to me. Small wording suggestion for the doco comment. Otherwise great.

File: framework/include/materials/Material.h [hunk 2]
```diff
@@ -131,6 +131,42 @@ class Material : public MaterialBase, public Coupleable, public MaterialProperty
...
+  /**
+   * Retrieve the dicrete material named "name".
+   *
+   * @param no_warn If true, suppress warning about retrieving the material potentially during its
+   * calculation. If you don't know what this is/means, then you don't need it.
+   * @param no_dep Use no_dep = true if no dependency resolution for the material is required. Using
+   * no_dep = false is useful for discrete materials.
+   */
+  MaterialBase &
+  getMaterialByName(const std::string & name, bool no_warn = false, bool no_dep = false)
```
Comment (loganharbour) [inline framework/include/materials/Material.h:151]: this should not be in the header

**Review by loganharbour — CHANGES_REQUESTED** [review]

File: framework/include/materials/Material.h (hunk 2 above)
Comment (dschwen) [reply framework/include/materials/Material.h]: what shouldn't? The default arguments? Those should _only_ be in the header.

Comment (loganharbour) [reply framework/include/materials/Material.h]: The whole method was in the header: https://github.com/idaholab/moose/pull/20106/commits/f91cdb5baf10a19637ef5fd92a43f567823caa4b

**Review by loganharbour — DISMISSED** [review]

File: framework/include/materials/Material.h [hunk 3]
```diff
@@ -131,6 +131,25 @@ class Material : public MaterialBase, public Coupleable, public MaterialProperty
   const MaterialProperty<T> & getMaterialPropertyOlderByName(const std::string & prop_name);
   ///@}
 
+  /**
+   * Retrieve the dicrete material with a given parameter key named "name"
```
Comment (dschwen) [inline framework/include/materials/Material.h:135]:
```suggestion
   * Retrieve the discrete material with a given parameter key named "name"
```

File: framework/include/materials/Material.h [hunk 4]
```diff
@@ -131,6 +131,25 @@ class Material : public MaterialBase, public Coupleable, public MaterialProperty
...
+   */
+  MaterialBase & getMaterial(const std::string & name)
+  {
+    return getMaterialByName(parameters().get<MaterialName>(name));
+  }
+
+  /**
+   * Retrieve the dicrete material named "name".
```
Comment (dschwen) [inline framework/include/materials/Material.h:143]:
```suggestion
   * Retrieve the discrete material named "name".
```

**Review by dschwen — COMMENTED** [review]
Ok, this looks fine. This puts the idea that materials have to bet gotten during the construction phase to ensure dependency resolution on its head. But the error check that checks if the material is gotten in initial setup will be helpful for developers.

**Comment by hugary1995** [comment]
One last comment: I think enabling `getMaterial` calls at construction time with late binding (#18725) is a better way of handling the dependency resolution. That way we can have a cleaner interface, plus we don't need to perform dependency resolution an additional time. But I don't know how to do that yet.

**Comment by hugary1995** [comment]
@dschwen @loganharbour Is this good to go now?

File: test/tests/materials/discrete/recompute_boundary_error.i [hunk 5]
```diff
@@ -5,74 +5,72 @@
...
+  []
 []
 
 [Kernels]
-  [./diff]
-    type = MatDiffusionTest
+  [diff]
+    type = Diffusion
     variable = u
-    prop_name = 'p'
```
Comment (dschwen) [inline test/tests/materials/discrete/recompute_boundary_error.i:28]: can you explain? I'm assuming coupling the recompute material doesn't work anymore (and it shouldn't). But this test does not seem to use `f` at all. Is it really testing the NewtonMaterial. Is the test testing an error message?

Comment (hugary1995) [reply test/tests/materials/discrete/recompute_boundary_error.i:28]: Yes, this test is testing an error message. The expected error message is something like
```
*** ERROR ***
Incompatible material and object boundaries:
    /home/gary/projects/moose/test/tests/materials/discrete/recompute_boundary_error.i:49: (Materials/recompute_props/boundary) material defined on boundaries 3, 
    /home/gary/projects/moose/test/tests/materials/discrete/recompute_boundary_error.i:59: (Materials/newton/boundary) object needs material on boundaries 1, 3, 
```
Because the `NewtonMaterial` is defined on boundaries `left` and `right`, while the `RecomputeMaterial` is only defined on `left`.

**Review by dschwen — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]

**Comment by lindsayad** [comment]
We should change the parameter doc-string for `compute` in `MaterialBase::validParams`.

**Comment by hugary1995** [comment]
The last sentence in the description 
> Non-computed MaterialBases are not sorted for dependencies.

might be confusing but it is actually pretty accurate as I see it. The discrete materials themselves do not participate in the sort, instead they modify the dependency graph if and only if they are retrieved by a regular material.

**Comment by hugary1995** [comment]
The rest of the description
> The user must call computeProperties() after retrieving the MaterialBase via MaterialBasePropertyInterface::getMaterialBase().

has never been true... and it doesn't seem to be related to this PR.

**Comment by lindsayad** [comment]
It sounds like the doc string is technically true. But it might be good to mention that the discrete materials will influence the sorting of the materials using them. Anyway i only stumbled upon this because Kyle Paaren messaged me about an input no longer working … and ultimately it was because of this PR (in a good way I think)

**Comment by lindsayad** [comment]
#21108 is revealing (although with the wrong error message) that there is a circular dependency within the `test/tests/materials/discrete/newton_no_calc` test in which the regular material is declaring the 'p' property and simultaneously retrieving the 'p' property in its discrete material. This makes sense given the names of the materials: `Newton` and `Recompute` respectively. So I don't know how to reconcile this new dependency check with a seeming desire to have Newton material iterations within regular-material/discrete-material pairs. Which do we want? Is this test "wrong"?

**Comment by hugary1995** [comment]
I just took a look at the test. If I am understanding it correctly, the error triggered in #21108 can be reproduced without any discrete material. For example, if a `compute = true` material does
```cpp
  _p_declared(declareProperty("p")),
  _p_retrieved(getMaterialProperty("p"))
```
then #21108 is going to complain. I think the decision of whether to allow this behavior should probably involve more people. But my vote is yes, for obvious reasons like discrete materials...

**Comment by dschwen** [comment]
What even is the point of 
```C++
  _p_declared(declareProperty("p")),
  _p_retrieved(getMaterialProperty("p"))
```
`_p_declared` id writable and readable already. The legitimate version of this is 

```C++
  _p_declared(declareProperty("p")),
  _p_declared_old(getMaterialPropertyOld("p"))
```

**Comment by hugary1995** [comment]
> What even is the point of
This was just mimicking the behavior of getting a discrete material that requests "p".

**Comment by hugary1995** [comment]
Also I suppose retrieving an old property doesn't mark the requested material object as requested.

**Comment by dschwen** [comment]
> Also I suppose retrieving an old property doesn't mark the requested material object as requested.

Correct, old properties do not participate in dependency resolution.

**Comment by lindsayad** [comment]
> But my vote is yes, for obvious reasons like discrete materials

This has been the implicit vote of the repository thus far. I'll let the repository be the voice of the people, and we'll continue with the current behavior 😄
