### PR TITLE
Fix automatic scaling for array variables

### LINKED ISSUE #26616: Executioner/automatic_scaling=true does not work with array variables
## Reason
Automatic scaling does not work for a nonlinear system with array variables. The code may still run but scaling factors other than the 0-th component will be ignored and no warning or error will be issued.

## Design
We need to check the number of components of all field variables and apply the scaling factors. The majority codes directly interacting with libMesh variables are not affected by this thus the effort of fixing this is not large. I will send in a patch.

## Impact
A potential unexpected behavior with automatic scaling for users using array variables.

### PR DESCRIPTION
**Pull request by YaqiWang**
Closes #26616.

### CODE REVIEW

File: framework/src/systems/NonlinearSystemBase.C [hunk 1]
```diff
@@ -3897,17 +3897,19 @@ NonlinearSystemBase::assembleScalingVector()
        as_range(lm_mesh.active_local_elements_begin(), lm_mesh.active_local_elements_end()))
     for (const auto * const field_var : field_variables)
     {
-      mooseAssert(field_var->count() == 1,
-                  "Contact Alex Lindsay and tell him to make this work for array variables.");
-      dof_map.dof_indices(elem, dof_indices, field_var->number());
-      for (const auto dof : dof_indices)
-        scaling_vector.set(dof, field_var->scalingFactor());
+      const auto & factors = field_var->arrayScalingFactor();
+      for (unsigned int i = 0; i < field_var->count(); ++i)
```
Comment (lindsayad) [inline framework/src/systems/NonlinearSystemBase.C:3901]:
```suggestion
      for (const auto i : make_range(field_var->count()))
```

File: framework/src/systems/SystemBase.C [hunk 2]
```diff
@@ -1426,9 +1426,14 @@ SystemBase::applyScalingFactors(const std::vector<Real> & inverse_scaling_factor
   for (MooseIndex(_vars) thread = 0; thread < _vars.size(); ++thread)
   {
     auto & field_variables = _vars[thread].fieldVariables();
-    for (MooseIndex(field_variables) i = 0; i < field_variables.size(); ++i)
-      field_variables[i]->scalingFactor(1. / inverse_scaling_factors[i] *
-                                        field_variables[i]->scalingFactor());
+    for (MooseIndex(field_variables) i = 0, p = 0; i < field_variables.size(); ++i)
+    {
+      auto factors = field_variables[i]->arrayScalingFactor();
```
Comment (lindsayad) [inline framework/src/systems/SystemBase.C:1431]:
```suggestion
      const auto & factors = field_variables[i]->arrayScalingFactor();
```

File: framework/src/systems/SystemBase.C [hunk 3]
```diff
@@ -1446,8 +1451,13 @@ SystemBase::applyScalingFactors(const std::vector<Real> & inverse_scaling_factor
       _console.precision(6);
 
       for (const auto & field_variable : field_variables)
-        _console << "  " << field_variable->name() << ": " << field_variable->scalingFactor()
-                 << "\n";
+      {
+        const auto & factors = field_variable->arrayScalingFactor();
+        _console << "  " << field_variable->name() << ":";
+        for (unsigned int i = 0; i < field_variable->count(); ++i)
```
Comment (lindsayad) [inline framework/src/systems/SystemBase.C:1457]:
```suggestion
        for (const auto i : make_range(field_variable->count()))
```

File: framework/src/variables/MooseVariableBase.C [hunk 4]
```diff
@@ -189,13 +190,16 @@ MooseVariableBase::componentDofIndices(const std::vector<dof_id_type> & dof_indi
 void
 MooseVariableBase::scalingFactor(Real factor)
 {
-  _scaling_factor.assign(_count, factor);
+  for (auto & v : _scaling_factor)
+    v = factor;
 }
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableBase.C:195]: The coverage report would tell us this but we didn't get it because of the THM threads failure. I'm wondering whether we can just remove this overload

File: framework/src/variables/MooseVariableBase.C [hunk 5]
```diff
@@ -189,13 +190,16 @@ MooseVariableBase::componentDofIndices(const std::vector<dof_id_type> & dof_indi
...
 
 void
 MooseVariableBase::scalingFactor(const std::vector<Real> & factor)
 {
-  _scaling_factor = factor;
+  mooseAssert(factor.size() == _count, "Inconsistent scaling factor size");
+  for (unsigned int i = 0; i < _count; ++i)
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableBase.C:201]:
```suggestion
  for (const auto i : make_range(_count))
```

**Review by lindsayad — CHANGES_REQUESTED** [review]
thank you for this nice improvement!

File: framework/src/systems/NonlinearSystemBase.C (hunk 1 above)
Comment (YaqiWang) [reply framework/src/systems/NonlinearSystemBase.C:3901]: `count()` is returning unsigned int, so this is consistent. But I can make the change if you insist.

File: framework/src/systems/SystemBase.C (hunk 2 above)
Comment (YaqiWang) [reply framework/src/systems/SystemBase.C:1431]: Intentionally making a copy here because we want to modify the factors with the auto generated factors and apply the modified factor.

File: framework/src/variables/MooseVariableBase.C (hunk 4 above)
Comment (YaqiWang) [reply framework/src/variables/MooseVariableBase.C:195]: Will try and report back. This is a legacy.

File: framework/src/systems/NonlinearSystemBase.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/systems/NonlinearSystemBase.C:3901]: I like the addition of being able to specify the index as `const`

File: framework/src/systems/SystemBase.C (hunk 2 above)
Comment (lindsayad) [reply framework/src/systems/SystemBase.C:1431]: sounds good

File: framework/src/variables/MooseVariableBase.C (hunk 4 above)
Comment (YaqiWang) [reply framework/src/variables/MooseVariableBase.C:195]: Looks like we can. The only place this function is used is in `SystemBase::applyScalingFactors` actually.

File: framework/src/systems/NonlinearSystemBase.C (hunk 1 above)
Comment (YaqiWang) [reply framework/src/systems/NonlinearSystemBase.C]: Fair enough. And also there is only one appearance of `i`.

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
failure is unrelated
