### PR TITLE
Array dgkernel Jacobian fixes

### LINKED ISSUE #20029: ArrayDGLowerDKernel::computeOffDiagJacobian is not exactly correct
## Reason
The function skips evaluations when the passed in variable is the variable on the lower-d mesh and calls `computeJacobian` when the passed in variable is the kernel variable. This code is probably copied from the non-array kernel `DGLowerDKernel`. The code is correct for `DGLowerDKernel` but not for `ArrayDGLowerDKernel` because in the array case, there could be couplings between components of the kernel variable and the kernel lower-d variable.

Similar issue exists for `ArrayDGKernel`. We did not hit any problem before because we do not have any test that has cross-component couplings.

## Design
Correct the potential bug and add a test. I will work on this.

## Impact
This bug will show up in a more complicated case in Griffin for HFEM with spherical harmonics expansion.

### PR DESCRIPTION
**Pull request by YaqiWang**
Close #20029.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Tag @yjung-anl

**Comment by YaqiWang** [comment]
This is ready for review. @lindsayad Please provide your comments if you have @yjung-anl.

File: framework/src/bcs/ArrayLowerDIntegratedBC.C [hunk 1]
```diff
@@ -159,7 +154,13 @@ ArrayLowerDIntegratedBC::computeLowerDOffDiagJacobian(Moose::ConstraintJacobianT
 
   const auto & jvar = getVariable(jvar_num);
 
-  prepareMatrixTagLower(_assembly, ivar, jvar_num, type);
+  // need to transform the type for assembling Jacobian on boundary to be consistent with
+  // Assembly::addJacobianLowerD() and Assembly::prepareLowerD().
+  Moose::ConstraintJacobianType type_tr =
```
Comment (lindsayad) [inline framework/src/bcs/ArrayLowerDIntegratedBC.C:159]: spell out `tr`. I assume it means transform, but I'm not 100% sure. Code should be self-documenting as much as possible

File: test/include/bcs/ArrayHFEMDirichletTestBC.h [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  static InputParameters validParams();
+
+  ArrayHFEMDirichletTestBC(const InputParameters & parameters);
+
+protected:
+  virtual void computeQpResidual(RealEigenVector & residual) override;
+  virtual void computeLowerDQpResidual(RealEigenVector & residual) override;
+  virtual RealEigenVector computeLowerDQpJacobian(Moose::ConstraintJacobianType type) override;
+  virtual RealEigenMatrix computeLowerDQpOffDiagJacobian(Moose::ConstraintJacobianType type,
+                                                         const MooseVariableFEBase & jvar) override;
```
Comment (lindsayad) [inline test/include/bcs/ArrayHFEMDirichletTestBC.h:26]: `virtual` is redundant in the presence of `override` but we have this all throughout MOOSE so I don't ask people to change it

**Review by lindsayad — CHANGES_REQUESTED** [review]
Overall this looks like an improvement to me. But we lost code coverage. Completely uncovered routines:
- [ ] ArrayLowerDIntegratedBC::computeJacobian()
- [ ] ArrayLowerDIntegratedBC::computeLowerDJacobian(Moose::ConstraintJacobianType type)
- [ ] LowerDIntegratedBC::computeJacobian()
- [ ] ArrayDGKernel::computeElemNeighJacobian(Moose::DGJacobianType type)
- [ ] ArrayDGLowerDKernel::computeJacobian()
- [ ] ArrayDGLowerDKernel::computeLowerDJacobian(Moose::ConstraintJacobianType type)
- [ ] DGLowerDKernel::computeJacobian()

I would like to see at least some of this decrease in coverage addressed

**Comment by YaqiWang** [comment]
> Overall this looks like an improvement to me. But we lost code coverage. Completely uncovered routines:
> 
> * [ ]  ArrayLowerDIntegratedBC::computeJacobian()
> * [ ]  ArrayLowerDIntegratedBC::computeLowerDJacobian(Moose::ConstraintJacobianType type)
> * [ ]  LowerDIntegratedBC::computeJacobian()
> * [ ]  ArrayDGKernel::computeElemNeighJacobian(Moose::DGJacobianType type)
> * [ ]  ArrayDGLowerDKernel::computeJacobian()
> * [ ]  ArrayDGLowerDKernel::computeLowerDJacobian(Moose::ConstraintJacobianType type)
> * [ ]  DGLowerDKernel::computeJacobian()
> 
> I would like to see at least some of this decrease in coverage addressed

The main reason we do not have tests for these functions is because the HFEM system is a saddle point problem and when we have PJFNK solve type, i.e. only assemble diagonal part of the Jacobian through calling these functions, we will get a singular matrix with zeros on diagonal. I can possible add a parameter in HFEM kernels to put identity matrix for the variables whose diagonal jacobians are zero. Any further comments?

File: framework/src/bcs/ArrayLowerDIntegratedBC.C (hunk 1 above)
Comment (YaqiWang) [reply framework/src/bcs/ArrayLowerDIntegratedBC.C:159]: yes, tr here means transformed. We had inline comment above, but I can rename it.

Comment (lindsayad) [reply framework/src/bcs/ArrayLowerDIntegratedBC.C:159]: Even though you have inline comments, it's still good practice to have meaningful variable names. I was able to guess that `tr` meant transform from your inline comments so I appreciate them, but I'd prefer not to guess. `tr` is a method name on tensors for example that signifies trace. I just don't want to have to guess

**Comment by lindsayad** [comment]
If the code in there is useless then I would prefer replacing it with a "not implemented" error or something like that. I am open to any solution that doesn't introduce blocks of untested code. I would prefer to hit an error than to march into a code routine that is untested and hence perhaps not trustworthy

**Comment by lindsayad** [comment]
Arguments related to HFEM are not going to resonate with me since none of the uncovered methods are from classes with HFEM in the name.

I do not have any further comments

**Comment by lindsayad** [comment]
Even though those classes do not have HFEM in the name, if the only use of them is currently HFEM, then I think an error in the methods actually makes sense. You could even say something like:
```c++
  mooseError("Not required for HFEM. When there are other uses for these classes, these methods should be implemented.");
```

**Comment by YaqiWang** [comment]
Working on adding a test for those computeJacobian functions.

**Comment by YaqiWang** [comment]
@lindsayad added three commits for addressing your comments.

File: test/tests/kernels/hfem/array_dirichlet_pjfnk.i [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+[]
+
+[Kernels]
+  [diff]
+    type = ArrayDiffusion
+    variable = u
+    block = 0
+    diffusion_coefficient = dc
+  []
+  [reaction]
```
Comment (YaqiWang) [inline test/tests/kernels/hfem/array_dirichlet_pjfnk.i:48]: Quite note: this kernel is added than the other input `array_dirichlet.i` is because otherwise the block diagonal matrix of `u` is only the stiffness matrix and we know stiffness matrix without any bc is singular. Adding reaction kernel (mass matrix) makes the block diagonal matrix of `u` non-singular. In `Executioner` we removed the `NEWTON` solve type.

**Comment by YaqiWang** [comment]
@lindsayad This should be ready for review again. I can add `for_pjfnk` parameter for `HFEMDiffusion` derived from `DGLowerDKernel` and a test to test the `computeJacobian` in `DGLowerDKernel`. I do not want to add an error message. I think `for_pjfnk` is a valid option that can go into framework. This function is actually not tested before, so it is arguably that we must add a test for it in this PR.

**Review by lindsayad — APPROVED** [review]
I'm curious how we lost coverage on `ArrayDGKernel` `save_in` code ... I didn't know we had testing on that before. Anyway this looks good enough to me. Thank you for adding the new tests

**Comment by lindsayad** [comment]
If you don't plan any more additions, I will merge

**Comment by YaqiWang** [comment]
Thanks @lindsayad !
