### PR TITLE
Fixed sync_times_object in Output

### LINKED ISSUE #25368: `sync_times_object` does not force solution to occur
## Bug Description
Using the `sync_times_object` in an output object does not actually force solution to occur at the times, just outputs the solution if the time happens to be in the list (when using `sync_only = true`). If `sync_only = false`, the parameter appears to have no effect.

## Steps to Reproduce
Run the following input file and look at the CSV output times: 
[sync_times.txt](https://github.com/idaholab/moose/files/12486383/sync_times.txt)

## Impact
This prevents users from getting much use from this option.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #25368

### CODE REVIEW

**Comment by joshuahansel** [comment]
@cticenhour This bug fix can go in newsletter, but I didn't want to conflict with https://github.com/idaholab/moose/pull/25310 - I can do it there.

**Comment by cticenhour** [comment]
Yeah, feel free to push directly to #25310 for the news entry if you want.

**Comment by joshuahansel** [comment]
Ok, if this PR needs another round of testing, I'll put it here; otherwise I'll put it in #25310.

File: framework/src/outputs/Output.C [hunk 1]
```diff
@@ -254,7 +258,12 @@ Output::onInterval()
 
   // Update sync times if a sync time object is in use
   if (_sync_times_object)
-    _sync_times = _sync_times_object->getUniqueTimes();
+  {
+    const auto & sync_times = _sync_times_object->getUniqueTimes();
+    if (sync_times != _sync_times)
+      mooseError("The provided sync times object has changing times values. Only static time "
+                 "values are supported at this time.");
```
[the remark this answers is not in the document]
Comment (joshuahansel) [reply framework/src/outputs/Output.C:265]: I'd say the object should be "times object" because the system is "Times", but the values should be "time values" as you suggested.

**Review by cticenhour — DISMISSED** [review]

File: framework/src/outputs/Output.C [hunk 2]
```diff
@@ -185,11 +185,15 @@ Output::Output(const InputParameters & parameters)
...
-    paramError("sync_times_object",
-               "Only one method of specifying sync times is supported at a time");
+  // Get sync times from Times object if using
+  if (_sync_times_object)
+  {
+    if (isParamValid("output_limiting_function") || isParamSetByUser("sync_times"))
+      paramError("sync_times_object",
+                 "Only one method of specifying sync times is supported at a time");
+    else
+      _sync_times = _sync_times_object->getUniqueTimes();
```
Comment (lindsayad) [inline framework/src/outputs/Output.C:195]:
```suggestion
      // Sync times for the time steppers are taken from the output warehouse. The output warehouse
      // takes sync times from the output objects immediately after the object is constructed. Hence we
      // must ensure that we set the `_sync_times` in the constructor
      _sync_times = _sync_times_object->getUniqueTimes();
```

File: framework/src/outputs/Output.C [hunk 3]
```diff
@@ -254,7 +258,12 @@ Output::onInterval()
 
   // Update sync times if a sync time object is in use
   if (_sync_times_object)
-    _sync_times = _sync_times_object->getUniqueTimes();
+  {
+    const auto & sync_times = _sync_times_object->getUniqueTimes();
+    if (sync_times != _sync_times)
+      mooseError("The provided sync times object has changing time values. Only static time "
+                 "values are supported at this time.");
```
Comment (lindsayad) [inline framework/src/outputs/Output.C:265]:
```suggestion
      mooseError("The provided sync times object has changing time values. Only static time "
                 "values are supported since time steppers take sync times from the output warehouse which determines its sync times at output construction time.");
```

File: framework/src/outputs/Output.C [hunk 4]
```diff
@@ -254,7 +258,12 @@ Output::onInterval()
 
   // Update sync times if a sync time object is in use
```
Comment (lindsayad) [inline framework/src/outputs/Output.C:259]:
```suggestion
```

**Review by lindsayad — CHANGES_REQUESTED** [review]
@GiudGiud maybe you have some thoughts on this

**Comment by GiudGiud** [comment]
looks fine to me

**Comment by GiudGiud** [comment]
it s just not fixing the main problem which is that we do not handle sync times dynamically. 
but this works for the current use

**Review by lindsayad — DISMISSED** [review]

**Review by GiudGiud — DISMISSED** [review]

**Review by lindsayad — APPROVED** [review]

**Comment by joshuahansel** [comment]
@loganharbour Know what's going on with the failing Conda MOOSE targets? I've invalidated already, but no change.

**Comment by milljm** [comment]
These are lock files still in play on conda.software.inl.gov. The only way to fix this, is for Logan or myself to remove them manually...

This can happen when there was some sort of network related hiccup closing the connection before the process ran to completion.

**Comment by milljm** [comment]
According to the PR history, the lock file was created (and not removed) on Aug 31st

```bash
-rw-r----- 1 moosetest moosetest  0 Aug 31 09:04 pr-25371.lock
```
That would explain why each push was failing. Invalidations are of no use, when you see:
```pre
BUILD_ROOT/moose/conda/moose/: Indexing Conda Channel
(Thu Aug 31 08:59:28 MDT 2023): Beginning Serial Process...
(Thu Aug 31 08:59:28 MDT 2023): Waiting for another process to complete...
```

**Comment by joshuahansel** [comment]
Thanks @milljm !

**Comment by milljm** [comment]
These locking issues seem to be a bit more rampant lately. So I've implemented a CRON to remove stale lock files. It is set to clean out locks older than 5 minutes. Conda indexing for PRs usually only takes 2 mins at the most.

So moving forwards if you run into this again... just wait about 5 minutes from when the serial process began:
```pre
BUILD_ROOT/moose/conda/moose/: Indexing Conda Channel
(Thu Aug 31 08:59:28 MDT 2023): Beginning Serial Process...
```
before hitting invalidate. ...basically, by the time you see your PR is stuck, its probably been long enough!
