### PR TITLE
Slight change to mortar segment generation

### LINKED ISSUE #17696: Handle invalid orientations when creating mortar segments
## Reason
We have noticed that the MOOSE exception "AutomaticMortarGeneration: Both orientations cannot simultaneously be invalid" appears in mechanical contact simulations at time steps where no special demands from the mortar segment generation seem to happen. For, at least, one case the message refers to very oblique projections between primary and secondary surface where, probably understandably, the selection of normal isn't clear. This could frequently correspond to the edge of the mortar segment mesh. The goal would be to avoid splitting mortar mesh segments if we find ourselves in such a case.  

## Design
Instead of splitting mortar mesh elements due to the incorporation of primary mesh elements and, then, check for both invalid orientations, let's wait on the creation until we know we are not in this case. Then, hopefully, we will only be giving up on mortar segments that are in unhealthy relative locations anyway.

## Impact
Make problems run to completion. @dewenyushu found this benchmarking mortar contact with an ironing problem.

### PR DESCRIPTION
**Pull request by recuero**
The purpose is to be more lenient when finding geometric inconsistencies in mortar segment generation. This PR should only enable new simulations and should not mess up with existing tests.

Closes #17696

### CODE REVIEW

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 1]
```diff
@@ -453,9 +374,97 @@ AutomaticMortarGeneration::buildMortarSegmentMesh()
...
+    // will not be considered in mortar thermomechanical contact.
     if (!orientation1_valid && !orientation2_valid)
-      throw MooseException(
-          "AutomaticMortarGeneration: Both orientations cannot simultaneously be invalid.");
+    {
+      mooseDoOnce(mooseWarning(
+          "AutomaticMortarGeneration: Both orientations cannot simultaneously be invalid. "
+          "This can indicate there are very oblique projections between primary (mortar) "
+          "and secondary (non-mortar) surfaces for a good problem set up. It can also mean your "
+          "time step is too large. This message is only printed once."));
```
Comment (lindsayad) [inline framework/src/constraints/AutomaticMortarGeneration.C:388]:
```suggestion
          "AutomaticMortarGeneration: Unable to determine valid secondary-primary orientation. "
          "Consequently we will consider projection of the primary node invalid and not split the mortar segment. "
          "This situation can indicate there are very oblique projections between primary (mortar) "
          "and secondary (non-mortar) surfaces for a good problem set up. It can also mean your "
          "time step is too large. This message is only printed once."));
```

**Review by lindsayad — CHANGES_REQUESTED** [review]
I think this is fine. Just the suggested change to the warning message (you may have to re-clang-format as a result)

**Review by lindsayad — APPROVED** [review]
