### PR TITLE
Fix inconsistent handling for optional input parameters 

### LINKED ISSUE #24455: Inconsistent handling for optional input parameters without a default value
## Reason

In MOOSE, an optional input parameter could be provided without default values, e.g.,

`params.addParam<Real>("dummy_real", "a dummy real number");`

When handling such an input parameter, it is typical to check if it is valid before accessing it, e.g., the following to avoid runtime error:

`_dummy_real(isParamValid("dummy_real")` <- Wrong, runtime error: The parameter "dummy_real" is being retrieved before being set.

The correct example is:
`_dummy_real(isParamValid("dummy_real") ? getParam<Real>("dummy_real") : 0.0)`

However, if the input parameter is a std::vector, e.g., 
```
params.addParam<std::vector<unsigned int>>("dummy_vec", "dummy_vec");
_dummy_vec(getParam<std::vector<unsigned int>>("dummy_vec"))
```
MOOSE won't send out a runtime error, but of course, `_dummy_vec` is an empty vector. This is inconsistent with the first case. This probably should not be categorized as a bug, would still be nice to make things consistent.

## Design

For the second case described above for std::vector input parameter, if no default value provided, should be handled the same way as other cases such as a real number.

## Impact

Inconsistent code design; causing confusion in module/application development.

### PR DESCRIPTION
**Pull request by MengnanLi91**
closes #24455 

## Design

Remove the template for std::vector<T> in getParamHelper

### CODE REVIEW

File: modules/richards/src/actions/Q2PAction.C [hunk 1]
```diff
@@ -100,8 +100,8 @@ Q2PAction::Q2PAction(const InputParameters & params)
     _gas_relperm(getParam<UserObjectName>("gas_relperm")),
     _gas_viscosity(getParam<Real>("gas_viscosity")),
     _diffusivity(getParam<Real>("diffusivity")),
-    _output_nodal_masses_to(getParam<std::vector<OutputName>>("output_nodal_masses_to")),
-    _output_total_masses_to(getParam<std::vector<OutputName>>("output_total_masses_to")),
+    _output_nodal_masses_to(isParamValid("output_nodal_masses_to")? getParam<std::vector<OutputName>>("output_nodal_masses_to"):std::vector<OutputName>{}),
+    _output_total_masses_to(isParamValid("output_total_masses_to")? getParam<std::vector<OutputName>>("output_total_masses_to"):std::vector<OutputName>{}),
```
Comment (dschwen) [inline modules/richards/src/actions/Q2PAction.C:104]: I disagree with this fix pattern. Please supply a default argument (empty vector) instead. This logic is reimplementing the default in a (for the documentation and autocomplete) intransparent way.

File: framework/src/actions/CommonOutputAction.C [hunk 2]
```diff
@@ -99,10 +99,12 @@ CommonOutputAction::validParams()
 
   params.addParam<std::vector<VariableName>>(
       "hide",
+      std::vector<VariableName>{},
```
Comment (dschwen) [inline framework/src/actions/CommonOutputAction.C:102]: it would be cool if we could support a `std::initializer_list<T>` here for parameter type `std::vector<T>`...

File: framework/src/actions/SetupMeshAction.C [hunk 3]
```diff
@@ -130,11 +130,9 @@ SetupMeshAction::SetupMeshAction(const InputParameters & params)
 void
 SetupMeshAction::setupMesh(MooseMesh * mesh)
 {
-  std::vector<BoundaryName> ghosted_boundaries =
-      getParam<std::vector<BoundaryName>>("ghosted_boundaries");
-
-  for (const auto & bnd_name : ghosted_boundaries)
-    mesh->addGhostedBoundary(mesh->getBoundaryID(bnd_name));
+  if (isParamValid("ghosted_boundaries"))
```
Comment (dschwen) [inline framework/src/actions/SetupMeshAction.C:133]: same here and everywhere. The right fix is to set an empty vector as a default rather than adding the logic down here

**Review by dschwen — CHANGES_REQUESTED** [review]
Please use default values instead of isParamValid logic

File: framework/src/actions/SetupMeshAction.C (hunk 3 above)
Comment (MengnanLi91) [reply framework/src/actions/SetupMeshAction.C:133]: The reason to use isParamValid logic is to be more consistent with other default value check. For other data type, we allow empty values in addParam and catch them later.

File: framework/src/actions/CommonOutputAction.C (hunk 2 above)
Comment (MengnanLi91) [reply framework/src/actions/CommonOutputAction.C:102]: `std::initializer_list<T>` could be a good idea. I fixed almost all cases in framework and modules, but the apps may be an issue here, especially I don't have access to many of them

File: framework/src/actions/SetupMeshAction.C (hunk 3 above)
Comment (dschwen) [reply framework/src/actions/SetupMeshAction.C:133]: That's not a good reason IMO. You are implementing the behavior that is obtained by supplying an empty vector as a default. This adds logic which we already have implemented. And the way that we have it implemented has additional functionality, namely signaling to the documentation system and language server/json dump that the parameter has a default behavior. There is no advantage to using `isParamValid` her, only drawbacks.

Comment (MengnanLi91) [reply framework/src/actions/SetupMeshAction.C:133]: The default value in addParam for me is more like a suggested value for users, therefore it also shows in the documentation. A empty vector value showing there doesn't provide much useful information

Comment (dschwen) [reply framework/src/actions/SetupMeshAction.C:133]: Sure, it shows that the code defaults to an empty list and not to some _unknown_ behavior that is hard coded in the specific object. I don't understand why this is even controversial for all other parameter types we supply a default value when we need one. This entire PR is about making things more consistent, so why are you using a different pattern to manually implement defaults just for std::vector parameters?

Comment (MengnanLi91) [reply framework/src/actions/SetupMeshAction.C:133]: These are two examples how other data type implemented(I can find more if needed). I don't know why vector parameter should all have empty default in addParam 

```
params.addParam<unsigned int>(
      "crack_front_point_index",
      "The index of the point on the crack front corresponding to this q function");
         _has_crack_front_point_index(isParamValid("crack_front_point_index")),

_crack_front_point_index(
    _has_crack_front_point_index ? getParam<unsigned int>("crack_front_point_index") : 0),
```

```
  params.addParam<std::string>("base_name", "Material property base name.");
  _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
```

Comment (MengnanLi91) [reply framework/src/actions/SetupMeshAction.C:133]: This is how it looks in documentation, not some _unknown_ behavior
Screenshot 2023-08-29 at 2 56 57 PM

**Comment by dschwen** [comment]
add 

```
   template <typename T>
   void addParam(const std::string & name,
                 const std::initializer_list<typename T::value_type> & value,
                 const std::string & doc_string)
   {
     addParam<T>(name, T{value}, doc_string);
   }
```

in InputParameters.h

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (dschwen) [inline modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: Why does this need to get regolded?

File: modules/heat_conduction/src/dirackernels/GapHeatPointSourceMaster.C [hunk 4]
```diff
@@ -22,8 +22,8 @@ GapHeatPointSourceMaster::validParams()
   MooseEnum orders("CONSTANT FIRST SECOND THIRD FOURTH", "FIRST");
 
   InputParameters params = DiracKernel::validParams();
-  params.addParam<BoundaryName>("boundary", "The primary boundary");
-  params.addParam<BoundaryName>("secondary", "The secondary boundary");
+  params.addParam<BoundaryName>("boundary", {}, "The primary boundary");
+  params.addParam<BoundaryName>("secondary", {}, "The secondary boundary");
```
Comment (dschwen) [inline modules/heat_conduction/src/dirackernels/GapHeatPointSourceMaster.C:26]: This is not a vector

File: modules/optimization/src/reporters/OptimizationData.C [hunk 5]
```diff
@@ -269,7 +269,7 @@ template <typename T>
 void
 OptimizationDataTempl<T>::readMeasurementsFromInput()
 {
-  if (this->isParamValid("file_variable_weights"))
+  if (this->template getParam<std::vector<std::string>>("file_variable_weights").size())
```
Comment (dschwen) [inline modules/optimization/src/reporters/OptimizationData.C:272]: I like to use `! .... .empty()` in these cases

File: modules/ray_tracing/src/raykernels/RayKernelBase.C [hunk 6]
```diff
@@ -49,7 +49,7 @@ RayKernelBase::RayKernelBase(const InputParameters & params)
     _need_segment_reinit(getParam<bool>("_need_segment_reinit"))
 {
   // Add dependencies
-  if (params.isParamSetByUser("depends_on"))
+  if (params.isParamSetByUser("depends_on") && isParamValid("depends_on"))
```
Comment (dschwen) [inline modules/ray_tracing/src/raykernels/RayKernelBase.C:52]: I think this can be just `isParamValid`

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: I checked the output, the difference is mainly some digital difference. The results looks the same in Paraview. I think the changes may come from the latest Petcs update like we've seen in other cases. What do you think?

File: modules/heat_conduction/src/dirackernels/GapHeatPointSourceMaster.C (hunk 4 above)
Comment (MengnanLi91) [reply modules/heat_conduction/src/dirackernels/GapHeatPointSourceMaster.C:26]: Good catch!

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (dschwen) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: Ok, let's make sure @recuero is aware of this.

Comment (recuero) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: Note that this file is not the in `/gold` folder! It should be removed from the repo.

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: I double check my re-gold files and run tests on my local machine. You are right. The re-gold may not be necessary. I'll push the changes and see how the tests go

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: > Note that this file is not in the `/gold` folder! It should be removed from the repo.

Have deleted those two files

Comment (recuero) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: Thanks! It was probably me (or Daniel) who mistakenly added it in the first place.

File: modules/ray_tracing/src/raybcs/RayBoundaryConditionBase.C [hunk 7]
```diff
@@ -42,7 +42,7 @@ RayBoundaryConditionBase::RayBoundaryConditionBase(const InputParameters & param
     _current_bnd_id(_trace_ray.currentBoundaryID())
 {
   // Add dependencies
-  if (params.isParamSetByUser("depends_on"))
+  if (params.isParamSetByUser("depends_on") && isParamValid("depends_on"))
```
Comment (GiudGiud) [inline modules/ray_tracing/src/raybcs/RayBoundaryConditionBase.C:45]:
```suggestion
  if (params.isParamSetByUser("depends_on"))
```

File: modules/misc/misc.yaml [hunk 8]
```diff
@@ -0,0 +1,9 @@
+DMETHOD: opt
```
Comment (GiudGiud) [inline modules/misc/misc.yaml:1]: delete this file
add to .gitignore in moose/

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (GiudGiud) [inline modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: why the change?

File: framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C [hunk 9]
```diff
@@ -31,6 +31,7 @@ MultiAppGeneralFieldUserObjectTransfer::validParams()
       "Transfers user object spatial evaluations from an origin app onto a variable in the target "
       "application.");
 
+  params.set<std::vector<VariableName>>("source_variable") = std::vector<VariableName>{};
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C:34]: cant you change the default in generalFieldTransfer instead?

File: framework/src/meshgenerators/RenameBlockGenerator.C [hunk 10]
```diff
@@ -23,39 +23,11 @@ RenameBlockGenerator::validParams()
...
-      "number.  If the old blocks are named, their names will be passed onto the "
-      "newly numbered blocks.",
-      "Use 'new_block' instead of 'new_block_id'.");
-  params.addDeprecatedParam<std::vector<SubdomainName>>(
-      "new_block_name",
-      "Elements with the old block number (or name) will be given this block "
-      "name.  No change of block ID is performed, unless multiple old blocks are "
-      "given the same name, in which case they are all given the first old block "
-      "number.",
-      "Use 'new_block' instead of 'new_block_name'.");
```
Comment (GiudGiud) [inline framework/src/meshgenerators/RenameBlockGenerator.C:52]: this change will have to go in another PR, I m pretty sure Kylee s mesh could not be done without selecting the id independently

File: framework/src/meshgenerators/ExtraNodesetGenerator.C [hunk 11]
```diff
@@ -52,18 +52,6 @@ std::unique_ptr<MeshBase>
 ExtraNodesetGenerator::generate()
 {
   std::unique_ptr<MeshBase> mesh = std::move(_input);
-  const auto coord = getParam<std::vector<std::vector<Real>>>("coord");
-  const auto nodes = getParam<std::vector<unsigned int>>("nodes");
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ExtraNodesetGenerator.C:56]: where did these checks go

File: framework/src/partitioner/LibmeshPartitioner.C [hunk 12]
```diff
@@ -149,17 +149,18 @@ LibmeshPartitioner::prepareBlocksForSubdomainPartitioner(
   subdomain_partitioner.chunks.clear();
 
   // Insert each chunk
-  for (const auto & group : _subdomain_blocks)
```
Comment (GiudGiud) [inline framework/src/partitioner/LibmeshPartitioner.C:152]: this should have been fine with the empty default?

File: framework/src/preconditioners/FieldSplitPreconditioner.C [hunk 13]
```diff
@@ -56,20 +56,23 @@ FieldSplitPreconditioner::FieldSplitPreconditioner(const InputParameters & param
   std::unique_ptr<CouplingMatrix> cm = std::make_unique<CouplingMatrix>(n_vars);
   if (!full)
   {
-    const auto off_diag_rows = getParam<std::vector<NonlinearVariableName>>("off_diag_row");
-    const auto off_diag_columns = getParam<std::vector<NonlinearVariableName>>("off_diag_column");
+    if (isParamValid("off_diag_row") && isParamValid("off_diag_column"))
+    {
+      const auto off_diag_rows = getParam<std::vector<NonlinearVariableName>>("off_diag_row");
+      const auto off_diag_columns = getParam<std::vector<NonlinearVariableName>>("off_diag_column");
```
Comment (GiudGiud) [inline framework/src/preconditioners/FieldSplitPreconditioner.C:62]: is there a check on the size of both somewhere?

File: framework/src/preconditioners/PhysicsBasedPreconditioner.C [hunk 14]
```diff
@@ -113,16 +113,20 @@ PhysicsBasedPreconditioner::PhysicsBasedPreconditioner(const InputParameters & p
...
+        getParam<std::vector<NonlinearVariableName>>("off_diag_column");
+
+    for (const auto i : index_range(odr))
+    {
+      unsigned int row = _nl.system().variable_number(odr[i]);
+      unsigned int column = _nl.system().variable_number(odc[i]);
+      off_diag[row].push_back(column);
+    }
   }
   // Add all of the preconditioning systems
```
Comment (GiudGiud) [inline framework/src/preconditioners/PhysicsBasedPreconditioner.C:131]: I think you can move this inside the isParamValid condition

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: This is not under /gold, just result exodus files

File: framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C (hunk 9 above)
Comment (MengnanLi91) [reply framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C:34]: "source_variable" is set in 'MultiAppConservativeTransfer' and used multiple places in the code. Most of them take "source_variable" as default parameters, a few not. I think it's better to fix a few places than changing all the rest

File: framework/src/meshgenerators/RenameBlockGenerator.C (hunk 10 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/RenameBlockGenerator.C:52]: yes she has to. The new ones wont let you set ids directly

Comment (MengnanLi91) [reply framework/src/meshgenerators/RenameBlockGenerator.C:52]: Okay, I'll put this back for this PR. I agree we need another PR. It's not good practice to rely on deprecatedParam. There should be better solution for it

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (MengnanLi91) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: I couldn't find it. Any hints?

Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: maybe add it then? seems like we would be accessing off-bounds

File: framework/src/preconditioners/PhysicsBasedPreconditioner.C (hunk 14 above)
Comment (MengnanLi91) [reply framework/src/preconditioners/PhysicsBasedPreconditioner.C:131]: It's already been inside the isParamValid condition. That's what the line 130 `}` for

Comment (MengnanLi91) [reply framework/src/preconditioners/PhysicsBasedPreconditioner.C:131]: 131 should stay with `addSystem(var, off_diag[var], _pre_type[var]);` Put `AddSystem` inside will cause three test cases to fail.
`problems/eigen_problem/preconditioners.newton_pbp ........................... FAILED (EXPECTED OUTPUT MISSING)
restart/restart_add_variable.add_variable_restart ............................................. FAILED (CRASH)
preconditioners/pbp.lots_of_variables ......................................................... FAILED (CRASH)
`

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: why are they checked in? can we generate them locally? 
I dont see what you changed that makes us have to change them

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: I think we can generate them locally. It doesn't break any test cases in CIVET. I though it just people forgot to delete it

Comment (GiudGiud) [inline modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: so you just found these files and dleeted them?

File: modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e
Comment (GiudGiud) [inline modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: why the regold?

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: Check this discussion https://github.com/idaholab/moose/pull/25245#discussion_r1340655402

File: modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e
Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty_out.e:1]: This is all related to a previous discussion with Daniel and Antonio

File: modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e
Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: this isnt a random exodus file sitting in the repo like this discussion mentions
This is a gold file, to this test
```
  [./frictionless_kinematic]
    type = 'Exodiff'
    input = 'frictionless_kinematic.i'
    exodiff = 'frictionless_kinematic_out.e'
    heavy = true
    min_parallel = 4
    abs_zero = 1e-6
    max_time = 800
    custom_cmp = 'frictionless_kinematic_out.cmp'
    issues = '#2816'
    design = 'MechanicalContactConstraint.md'
    requirement = 'We shall be able to solve the frictionless sliding block problem using a kinematic constraint formulation.'
  [../]
```

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: Yes,so what I did is to put it under /gold. Nothing more. I remembered before that there was a test failure. After re-gold, the test works fine. This file is not deleted but move from result folder to gold folder

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: Yes, this one just move from test folder to gold folder. Nothing else changes

Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: It says +6 kb. Do you mind trying again but with git mv ?

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (MengnanLi91) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: This review has been addressed

File: modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e
Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: either that or I need to learn to use exodiff to compare on my machine. Your call

File: framework/src/partitioner/LibmeshPartitioner.C (hunk 12 above)
Comment (MengnanLi91) [reply framework/src/partitioner/LibmeshPartitioner.C]: Review has been addressed

File: modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e
Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: Let me check

Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: I tested both my gold file and the one copy from latest moose. Both of them passed the test. I'll just update this gold file using the one from latest moose. So there won't be 6kb changes

Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: you ll need to squash this last commit into whichever commit did the change.
right now we are checking in the same file twice

Comment (GiudGiud) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: can you also please squash in all the clang commits?

File: framework/src/materials/DerivativeSumMaterial.C [hunk 15]
```diff
@@ -59,7 +59,9 @@ DerivativeSumMaterialTempl<is_ad>::DerivativeSumMaterialTempl(const InputParamet
     mooseError("Please supply at least one material to sum in DerivativeSumMaterial ", name());
 
   // get prefactor values if not 1.0
-  std::vector<Real> p = this->template getParam<std::vector<Real>>("prefactor");
+  std::vector<Real> p = this->isParamValid("prefactor")
```
Comment (GiudGiud) [inline framework/src/materials/DerivativeSumMaterial.C:62]: this is not needed, the param is always valid, it has a default

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: do you mind pointing me to the check?

Comment (MengnanLi91) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: New line 70

File: modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e
Comment (MengnanLi91) [reply modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_kinematic_out.e:1]: This has been addressed

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: ok this is not correct.

you ll silently ignore the user inputs if off_diag_row is size 3 and off_diag_col = 0
and you ll still seg fault if
off_diag_row is size 3 and off_diag_col = 1

Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: this goes beyond the PR but it d be good to fix. If you want to push this to another PR I m ok with it

File: framework/src/materials/DerivativeSumMaterial.C (hunk 15 above)
Comment (MengnanLi91) [reply framework/src/materials/DerivativeSumMaterial.C]: Review addressed

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (MengnanLi91) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: check the new condition

Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: you're ignoring the inputs in case they are not correct.
I think we should have an error if they are not correct.

this check should be right under if (!full)

Comment (MengnanLi91) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: Make an another PR for this then so that we can have proper error messages and tests for error check. I really need this one to merge quickly before any other apps make more changes and I need to patch them again. That's what happens for the Griffin test failure today.

File: framework/src/auxkernels/ParsedVectorAux.C [hunk 16]
```diff
@@ -98,11 +91,19 @@ ParsedVectorAux::ParsedVectorAux(const InputParameters & parameters)
...
+    auto constant_expressions =
+        isParamValid("constant_expressions")
+            ? getParam<std::vector<std::vector<std::string>>>("constant_expressions")
+            : std::vector<std::vector<std::string>>{};
+
+    if (constant_names.size() != constant_expressions.size())
+      paramError("constant_names", "Must be same length as constant_expressions");
+
+    if (isParamValid("constant_names") && isParamValid("constant_expressions"))
+      addFParserConstants(_func_F[i], constant_names[i], constant_expressions[i]);
```
Comment (GiudGiud) [inline framework/src/auxkernels/ParsedVectorAux.C:106]: why is anything changing in this file?
the previous code was fine, you could just try to use {} instead of the defaults they had

File: framework/src/actions/AdaptivityAction.C [hunk 17]
```diff
@@ -170,15 +170,15 @@ AdaptivityAction::act()
 
     adapt.setPrintMeshChanged(getParam<bool>("print_changed_info"));
 
-    const std::vector<std::string> & weight_names =
-        getParam<std::vector<std::string>>("weight_names");
-    const std::vector<Real> & weight_values = getParam<std::vector<Real>>("weight_values");
+    if (isParamValid("weight_names") && isParamValid("weight_values"))
```
Comment (GiudGiud) [inline framework/src/actions/AdaptivityAction.C:173]: can you use a default instead? for both params

File: framework/src/actions/SetupMeshAction.C (hunk 3 above)
Comment (GiudGiud) [reply framework/src/actions/SetupMeshAction.C:135]: Daniel is right here. It s better to have the default as it will show in the parameter as a default empty one. 
Here if base_name had a default you would see "" for the default or () or something, that would tell you more than what we have now (nothing)

File: framework/src/auxkernels/ArrayParsedAux.C [hunk 18]
```diff
@@ -84,9 +84,10 @@ ArrayParsedAux::ArrayParsedAux(const InputParameters & parameters)
   setParserFeatureFlags(_func_F);
 
   // add the constant expressions
-  addFParserConstants(_func_F,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
+  if (isParamValid("constant_names") && isParamValid("constant_expressions"))
```
Comment (GiudGiud) [inline framework/src/auxkernels/ArrayParsedAux.C:87]: try empty default instead

File: framework/src/auxkernels/ParsedAux.C [hunk 19]
```diff
@@ -67,9 +67,10 @@ ParsedAux::ParsedAux(const InputParameters & parameters)
   setParserFeatureFlags(_func_F);
 
   // add the constant expressions
-  addFParserConstants(_func_F,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
+  if (isParamValid("constant_names") && isParamValid("constant_expressions"))
```
Comment (GiudGiud) [inline framework/src/auxkernels/ParsedAux.C:70]: same

File: framework/src/meshgenerators/ExtraNodesetGenerator.C [hunk 20]
```diff
@@ -74,15 +62,16 @@ ExtraNodesetGenerator::generate()
   BoundaryInfo & boundary_info = mesh->get_boundary_info();
 
   // add nodes with their ids
-  for (const auto & node_id : nodes)
-  {
-    // Our mesh may be distributed and this node may not exist on this process
-    if (!mesh->query_node_ptr(node_id))
-      continue;
+  if (isParamValid("nodes"))
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ExtraNodesetGenerator.C:65]: this code would behave fine with a nodes {} default and you would not have such a large diff either

File: framework/src/meshgenerators/ParsedGenerateSideset.C [hunk 21]
```diff
@@ -103,25 +103,29 @@ ParsedGenerateSideset::ParsedGenerateSideset(const InputParameters & parameters)
...
   _func_F = std::make_shared<SymFunction>();
 
   // set FParser internal feature flags
   setParserFeatureFlags(_func_F);
 
   // add the constant expressions
-  addFParserConstants(_func_F,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
+  if (isParamValid("constant_names") && isParamValid("constant_expressions"))
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ParsedGenerateSideset.C:125]: same

File: framework/src/meshgenerators/ParsedCurveGenerator.C [hunk 22]
```diff
@@ -112,15 +112,18 @@ ParsedCurveGenerator::ParsedCurveGenerator(const InputParameters & parameters)
...
-  addFParserConstants(_func_Fx,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
-  addFParserConstants(_func_Fy,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
-  addFParserConstants(_func_Fz,
-                      getParam<std::vector<std::string>>("constant_names"),
-                      getParam<std::vector<std::string>>("constant_expressions"));
+  if (isParamValid("constant_names") && isParamValid("constant_expressions"))
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ParsedCurveGenerator.C:115]: same

File: framework/src/meshgenerators/ParsedElementDeletionGenerator.C [hunk 23]
```diff
@@ -24,10 +24,11 @@ ParsedElementDeletionGenerator::validParams()
       "(must be 'volume' in the expression) and the element id ('id' in the expression).");
   params.addRequiredParam<ParsedFunctionExpression>(
       "expression", "Expression to evaluate to decide whether an element should be deleted");
-  params.addParam<std::vector<std::string>>("constant_names",
-                                            "Vector of constants used in the parsed function");
+  params.addParam<std::vector<std::string>>(
+      "constant_names", {}, "Vector of constants used in the parsed function");
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ParsedElementDeletionGenerator.C:28]: done right here

File: framework/src/preconditioners/FieldSplitPreconditioner.C (hunk 13 above)
Comment (GiudGiud) [reply framework/src/preconditioners/FieldSplitPreconditioner.C:62]: other PR sounds good for this item

**Review by GiudGiud — CHANGES_REQUESTED** [review]
Daniel's review must be addressed. Most of the added isParamValid logic is unnecessary if we just reproduced the previous behavior (the empty vector default)

**Comment by MengnanLi91** [comment]
> Daniel's review must be addressed. Most of the added isParamValid logic is unnecessary if we just reproduced the previous behavior (the empty vector default)

That not works everywhere. It is really case-dependent. I started with add default value but found test cases failed so I dig into the test cases and find some isParamValid logic is necessary.

**Comment by GiudGiud** [comment]
imo the only thing that changed between before (default is silent {}) and after (actual {} in the addParam) is the behavior of isParamValid (used to be false with bad default, is true with default). Is there anything else?

File: framework/src/auxkernels/ParsedVectorAux.C (hunk 16 above)
Comment (MengnanLi91) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: This `isParamValid` is used to replace `getParam<std::vector<std::vector<std::string>>>("constant_names").size()`. It appears multiple times in the conditions which is not necessary. `IsParamValid` is cheaper than calling 'getParam.size()'.

Comment (GiudGiud) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: you can restore the default and then use isParamSetByUser instead of isParamValid. This lets you change a single line instead of rewriting the entire constuctor

File: framework/src/actions/AdaptivityAction.C (hunk 17 above)
Comment (MengnanLi91) [reply framework/src/actions/AdaptivityAction.C:173]: Here are test failed with default value.
`mesh/adapt.displaced_test ................................................................... FAILED (EXODIFF)
executioners/executioner.test_steady_adapt .................................................. FAILED (EXODIFF)
outputs/displaced.use_displaced ............................................................. FAILED (EXODIFF)
time_integrators/crank-nicolson.group/adapt ................................................. FAILED (EXODIFF)
mesh/adapt.test_time ........................................................................ FAILED (EXODIFF)
preconditioners/pbp.pbp/pbp_adapt_test ...................................................... FAILED (EXODIFF)
time_integrators/implicit-euler.group/adapt ................................................. FAILED (EXODIFF)
preconditioners/smp.smp/smp_adapt_test ...................................................... FAILED (EXODIFF)
time_integrators/dirk.group/dirk-2d-heat-adap ............................................... FAILED (EXODIFF)
time_integrators/bdf2.group/adapt ........................................................... FAILED (EXODIFF)
mesh/adapt.initial_adaptivity_test .......................................................... FAILED (EXODIFF)
preconditioners/reuse.mesh_refinement ....................................................... FAILED (CSVDIFF)
mesh/adapt.patch_test ....................................................................... FAILED (EXODIFF)
mesh/adapt.adapt_cycles_test ................................................................ FAILED (EXODIFF)
mesh/adapt.test ............................................................................. FAILED (EXODIFF)
bcs/periodic.testlevel1 ..................................................................... FAILED (EXODIFF)
mesh/adapt.interval ......................................................................... FAILED (EXODIFF)`

File: framework/src/auxkernels/ParsedVectorAux.C (hunk 16 above)
Comment (MengnanLi91) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: It doesn't do any harm to the constructor or failed any test cases. Just different ways of writing it. Why this can not be accepted?

**Comment by MengnanLi91** [comment]
> imo the only thing that changed between before (default is silent {}) and after (actual {} in the addParam) is the behavior of isParamValid (used to be false with bad default, is true with default). Is there anything else?

Check the ` AdaptivityAction` example. `IsParamValid` is a simple solution here

File: framework/src/auxkernels/ArrayParsedAux.C (hunk 18 above)
Comment (MengnanLi91) [reply framework/src/auxkernels/ArrayParsedAux.C:87]: Do we want to go through all the `isParamValid` conditions to see if it can be replaced by default value? I've tested most of them with default value and then went back to add conditions while working on this PR. There may be a few places that it can be replaced by default value but definitely not a lot.  Feel like we are repeating all that work now and it will be very time consuming to test each changes. The current change doesn't break any test cases or apps. Could we accept it as it is?

File: framework/src/actions/AdaptivityAction.C (hunk 17 above)
Comment (GiudGiud) [reply framework/src/actions/AdaptivityAction.C:173]: but why? they had a default value before.

File: framework/src/auxkernels/ArrayParsedAux.C (hunk 18 above)
Comment (GiudGiud) [reply framework/src/auxkernels/ArrayParsedAux.C:87]: It s not really a matter of seeing if you can, it s a matter that it should be possible. And if it's not we need to know why. It was certainly possible before since there was a default value. Something else must have changed

File: framework/src/actions/AdaptivityAction.C (hunk 17 above)
Comment (MengnanLi91) [reply framework/src/actions/AdaptivityAction.C:173]: > but why? they had a default value before. 

I think they may have 'isParamValid' check downstream. If we use default values, some of them may need change to ParamSetByUser or size check. I don't dig in because there will be a lot of tests and more(if you consider all the apps). For this PR, I just want to make sure this new changes won't break all the existing cases and code. I try not to change their logic if possible

File: framework/src/auxkernels/ArrayParsedAux.C (hunk 18 above)
Comment (MengnanLi91) [reply framework/src/auxkernels/ArrayParsedAux.C:87]: I think it is beyond the scope of this PR. There are definitely places to improve all the downstream logics but for this PR, I want to make sure all the existing cases works with this new patch. And for all the new codes there won't be any addParam with implicit default values. Otherwise I'll have to keep patching them

Comment (loganharbour) [reply framework/src/auxkernels/ArrayParsedAux.C:87]: is there not value in different logic for when a user provides a blank vs a user providing nothing and having a default blank?

File: framework/src/actions/AdaptivityAction.C (hunk 17 above)
Comment (GiudGiud) [reply framework/src/actions/AdaptivityAction.C:173]: They dont, I checked. 
I just did this with the {} default (e.g. reverted to what it was):
```
    // if (isParamValid("weight_names") && isParamValid("weight_values"))
    // {
    const std::vector<std::string> & weight_names =
        getParam<std::vector<std::string>>("weight_names");
    const std::vector<Real> & weight_values = getParam<std::vector<Real>>("weight_values");

    auto num_weight_names = weight_names.size();
    auto num_weight_values = weight_values.size();

    if (num_weight_names != num_weight_values)
      mooseError("Number of weight_names must be equal to number of weight_values in "
                 "Execution/Adaptivity");

    if (num_weight_names)
    {
```
and it worked fine, 0 test failures, with a default

Comment (MengnanLi91) [reply framework/src/actions/AdaptivityAction.C:173]: I see, the main difference here is use default and check size vs use empty value and check isParamValid. I think both logics work under this condition. Why it has to be size check instead of isParamValid() check?

Comment (GiudGiud) [reply framework/src/actions/AdaptivityAction.C:173]: Because passing {}, an empty vector that has true for isParamValid (and if the user specifies "" for the parameter, it also gets true for isParamSetByUser), is not valid for the code below the if

File: framework/src/auxkernels/ArrayParsedAux.C (hunk 18 above)
Comment (GiudGiud) [reply framework/src/auxkernels/ArrayParsedAux.C:87]: yeah if we care about users doing `some_vector_param = ""` then any previous (before this PR) isParamValid logic will have to rely on the size of the vector instead.
There still wont be a need for new isParamValid logic

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 20 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:65]: No, if you read the changing part, using 'IsValidParam' here is much better than has a bool variable flag and check.
```
 // make sure the input is not empty
  bool data_valid = false;
  if (isParamValid("nodes") && nodes.size() != 0)
    data_valid = true;
  if (_pars.isParamValid("coord") && coord.size() != 0)
    data_valid = true;
 ```

File: framework/src/actions/SetupMeshAction.C (hunk 3 above)
Comment (GiudGiud) [reply framework/src/actions/SetupMeshAction.C:135]: see here

File: framework/src/auxkernels/ParsedVectorAux.C (hunk 16 above)
Comment (GiudGiud) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: revert back

Comment (MengnanLi91) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: I don't think it is necessary to check size() multiple times

File: framework/src/preconditioners/VariableCondensationPreconditioner.C [hunk 24]
```diff
@@ -158,21 +158,21 @@ VariableCondensationPreconditioner::VariableCondensationPreconditioner(
...
-        {
-          const unsigned int row = _nl.getVariable(0, vars[j]).number();
-          const unsigned int column = _nl.getVariable(0, vars[k]).number();
-          (*cm)(row, column) = 1;
-          (*cm)(column, row) = 1;
-        }
-    }
+    if (isParamValid("coupled_groups"))
+      for (const auto & coupled_group :
+           getParam<std::vector<NonlinearVariableName>>("coupled_groups"))
```
Comment (GiudGiud) [inline framework/src/preconditioners/VariableCondensationPreconditioner.C:163]: should be default instead of added logic

File: framework/src/actions/SetupMeshAction.C (hunk 3 above)
Comment (MengnanLi91) [reply framework/src/actions/SetupMeshAction.C:135]: This is different from what Daniel said in my opinion.

Comment (GiudGiud) [reply framework/src/actions/SetupMeshAction.C:135]: @dschwen has your comment been addressed

Comment (dschwen) [reply framework/src/actions/SetupMeshAction.C:135]: yes

File: framework/src/auxkernels/ParsedVectorAux.C (hunk 16 above)
Comment (dschwen) [reply framework/src/auxkernels/ParsedVectorAux.C:106]: This could be made more elegant with `getParam<std::string, std::string>("constant_names", "constant_expressions")` which gets both parameters as a vector of pairs, checking that they have the same length. (with the proper change in `addFParserConstants`). Don't address this in this PR. I can make that change later.

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 20 above)
Comment (dschwen) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:65]: I don't get this either. Why is isParamValid necessary here? If nodes is empty the for loop is skipped automatically. I'm with Guillome. #istandwithguillaume

File: framework/src/meshgenerators/ExtraNodesetGenerator.C [hunk 25]
```diff
@@ -91,65 +80,67 @@ ExtraNodesetGenerator::generate()
...
-
-    for (unsigned int j = 0; j < c.size(); ++j)
-      p(j) = c[j];
-
-    // locate candidate element
-    bool on_node = false;
-    bool found_elem = false;
-    const Elem * elem = (*locator)(p);
-    if (elem)
+  if (_pars.isParamValid("coord"))
```
Comment (dschwen) [inline framework/src/meshgenerators/ExtraNodesetGenerator.C:83]: same here. Having an empty coord would also make the loop below do nothing.

File: framework/src/meshgenerators/RenameBlockGenerator.C [hunk 26]
```diff
@@ -69,29 +73,29 @@ RenameBlockGenerator::validParams()
 RenameBlockGenerator::RenameBlockGenerator(const InputParameters & parameters)
   : MeshGenerator(parameters), _input(getMesh("input"))
 {
-  if (isParamValid("old_block_id") && isParamValid("old_block_name"))
+  if (isParamSetByUser("old_block_id") && isParamSetByUser("old_block_name"))
```
Comment (dschwen) [inline framework/src/meshgenerators/RenameBlockGenerator.C:76]: I don't understand the need for this change. Looks to me as if this code could just stay completely unchanged (no default above and continuing to use isParamValid)

File: framework/src/nodalkernels/ADNodalKernel.C [hunk 27]
```diff
@@ -25,10 +25,10 @@ ADNodalKernel::validParams()
 ADNodalKernel::ADNodalKernel(const InputParameters & parameters)
   : NodalKernelBase(parameters), _u(_var.adDofValues())
 {
-  if (isParamValid("save_in"))
+  if (isParamSetByUser("save_in"))
```
Comment (dschwen) [inline framework/src/nodalkernels/ADNodalKernel.C:28]: I don't quite trust isParamSetByUser. What happens if the param is set by an action?

Comment (dschwen) [reply framework/src/nodalkernels/ADNodalKernel.C:28]: As above, why not keep this file unchanged? The semantics here are still the same. If no default is provided and the user didn't set the parameter we should use `isParamValid`. This code is not relying on an implict default, so let's not change it.

File: framework/src/preconditioners/FieldSplitPreconditioner.C [hunk 28]
```diff
@@ -65,12 +66,14 @@ FieldSplitPreconditioner::FieldSplitPreconditioner(const InputParameters & param
...
     // off-diagonal entries
     std::vector<std::vector<unsigned int>> off_diag(n_vars);
-    for (const auto i : index_range(off_diag_rows))
-    {
-      unsigned int row = _nl.getVariable(0, off_diag_rows[i]).number();
-      unsigned int column = _nl.getVariable(0, off_diag_columns[i]).number();
-      (*cm)(row, column) = 1;
-    }
+    if (off_diag_rows.size() * off_diag_columns.size() != 0 &&
+        off_diag_rows.size() == off_diag_columns.size())
```
Comment (dschwen) [inline framework/src/preconditioners/FieldSplitPreconditioner.C:70]: this should for sure be using the two parameter version of getParam instead!

File: framework/src/preconditioners/MoosePreconditioner.C [hunk 29]
```diff
@@ -67,15 +70,15 @@ MoosePreconditioner::MoosePreconditioner(const InputParameters & params)
   bool full = getParam<bool>("full");
 
   // We either have a full coupling or a custom coupling
-  if (full && isParamValid("off_diag_row"))
+  if (full && isParamSetByUser("off_diag_row"))
     paramError("off_diag_row", "Set full=false to specify the off-diagonal rows manually");
-  if (full && isParamValid("off_diag_column"))
+  if (full && isParamSetByUser("off_diag_column"))
```
Comment (dschwen) [inline framework/src/preconditioners/MoosePreconditioner.C:75]: I'll stop reviewing here and wait until we have discussed this (we can chat next week). I don't think this file should be modified either.

**Review by dschwen — CHANGES_REQUESTED** [review]
I don't think some of the changes in this PR should be made.

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 20 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:65]: In the previous code, it has a mooseError to remind people the "node can not be empty". `isParamValid` will give similar error. Whoever wrote it want to have the error, I just preserve that logic instead of being silence

File: framework/src/meshgenerators/RenameBlockGenerator.C (hunk 26 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/RenameBlockGenerator.C:76]: It failed tests if keep unchanged

File: framework/src/nodalkernels/ADNodalKernel.C (hunk 27 above)
Comment (MengnanLi91) [reply framework/src/nodalkernels/ADNodalKernel.C:28]: Is there a better way to do it along with providing default value? Check size?

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 25 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:83]: This I agree but the `isParamValid("nodes")` is needed

File: framework/src/preconditioners/MoosePreconditioner.C (hunk 29 above)
Comment (MengnanLi91) [reply framework/src/preconditioners/MoosePreconditioner.C:75]: Sure, I can show you how it affects the test cases. Maybe there is better solution for it but simply changing back to `isParamValid` won't work

Comment (GiudGiud) [reply framework/src/preconditioners/MoosePreconditioner.C:75]: Probably want to check the size instead. That ended up making the most sense in a lot of these changes

**Comment by MengnanLi91** [comment]
@dschwen I have remove all the isParamSetByUser in the PR, if you have time, could you take a look?

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 20 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:66]: you deleted those checks and there's no size checking now

File: framework/src/meshgenerators/RenameBlockGenerator.C [hunk 30]
```diff
@@ -99,7 +99,9 @@ RenameBlockGenerator::RenameBlockGenerator(const InputParameters & parameters)
   }
   else
   {
-    _old_block = getParam<std::vector<SubdomainName>>("old_block_name");
+    _old_block = isParamValid("old_block_name")
```
Comment (GiudGiud) [inline framework/src/meshgenerators/RenameBlockGenerator.C:102]: use default

File: framework/src/meshgenerators/ExtraNodesetGenerator.C (hunk 20 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/ExtraNodesetGenerator.C:66]: `isParamValid` gives the same thing, I don't use default value here, now if user don't provide default value, it will error out

File: framework/src/meshgenerators/RenameBlockGenerator.C (hunk 30 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/RenameBlockGenerator.C:102]: Can not use default here because it will break line 81 condition and @dschwen want to avoid use `isParamSetByUser`

Comment (GiudGiud) [reply framework/src/meshgenerators/RenameBlockGenerator.C:102]: nevermind it's because it s deprecated

File: framework/src/outputs/AdvancedOutput.C [hunk 31]
```diff
@@ -161,8 +161,9 @@ AdvancedOutput::init()
   initAvailableLists();
 
   // Separate the hide/show list into components
-  initShowHideLists(getParam<std::vector<VariableName>>("show"),
-                    getParam<std::vector<VariableName>>("hide"));
+  if (isParamValid("show") && isParamValid("hide"))
```
Comment (GiudGiud) [inline framework/src/outputs/AdvancedOutput.C:164]: should use default

File: framework/src/preconditioners/MoosePreconditioner.C [hunk 32]
```diff
@@ -35,7 +35,8 @@ MoosePreconditioner::validParams()
       "associated with an off-diagonal column from the same position in off_diag_column.");
   params.addParam<std::vector<NonlinearVariableName>>(
       "off_diag_column",
-      "The variable names for the off-diagonal columns you want to add into the matrix; they will "
+      "The variable names for the off-diagonal columns you want to add into the matrix; they "
+      "will "
       "be associated with an off-diagonal row from the same position in off_diag_row.");
```
Comment (GiudGiud) [inline framework/src/preconditioners/MoosePreconditioner.C:40]:
```suggestion
      "The variable names for the off-diagonal columns you want to add into the matrix; they "
      "will be associated with an off-diagonal row from the same position in off_diag_row.");
```

File: framework/src/scalarkernels/ParsedODEKernel.C [hunk 33]
```diff
@@ -69,6 +70,7 @@ ParsedODEKernel::ParsedODEKernel(const InputParameters & parameters)
   }
 
   // add postprocessors
+
```
Comment (GiudGiud) [inline framework/src/scalarkernels/ParsedODEKernel.C:73]:
```suggestion
```

File: framework/src/transfers/MultiAppConservativeTransfer.C [hunk 34]
```diff
@@ -51,7 +52,9 @@ MultiAppConservativeTransfer::MultiAppConservativeTransfer(const InputParameters
     _to_var_names(getParam<std::vector<AuxVariableName>>("variable")),
     _preserve_transfer(isParamValid("from_postprocessors_to_be_preserved")),
     _from_postprocessors_to_be_preserved(
-        getParam<std::vector<PostprocessorName>>("from_postprocessors_to_be_preserved")),
+        _preserve_transfer
+            ? getParam<std::vector<PostprocessorName>>("from_postprocessors_to_be_preserved")
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppConservativeTransfer.C:56]: use a default instead

File: modules/porous_flow/src/actions/PorousFlowActionBase.C [hunk 35]
```diff
@@ -99,9 +101,13 @@ PorousFlowActionBase::PorousFlowActionBase(const InputParameters & params)
     _num_aqueous_equilibrium(getParam<unsigned int>("number_aqueous_equilibrium")),
     _num_aqueous_kinetic(getParam<unsigned int>("number_aqueous_kinetic")),
     _gravity(getParam<RealVectorValue>("gravity")),
-    _mass_fraction_vars(getParam<std::vector<VariableName>>("mass_fraction_vars")),
+    _mass_fraction_vars(isParamValid("mass_fraction_vars")
+                            ? getParam<std::vector<VariableName>>("mass_fraction_vars")
+                            : std::vector<VariableName>{}),
```
Comment (GiudGiud) [inline modules/porous_flow/src/actions/PorousFlowActionBase.C:106]: use default in parameter

File: modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C [hunk 36]
```diff
@@ -100,7 +100,9 @@ GaussianProcessTrainer::GaussianProcessTrainer(const InputParameters & parameter
     if (_sampler.getNumberOfRows() < _optimization_opts.batch_size)
       paramError("batch_size", "Batch size cannot be greater than the training data set size.");
 
-  std::vector<std::string> tune_parameters(getParam<std::vector<std::string>>("tune_parameters"));
+  std::vector<std::string> tune_parameters(
+      _do_tuning ? getParam<std::vector<std::string>>("tune_parameters")
+                 : std::vector<std::string>{});
```
Comment (GiudGiud) [inline modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C:105]: use default in parameter

File: modules/thermal_hydraulics/src/components/HeatStructurePlate.C [hunk 37]
```diff
@@ -38,7 +38,8 @@ HeatStructurePlate::HeatStructurePlate(const InputParameters & params)
   for (unsigned int i = 0; i < _names.size(); i++)
     _name_index[_names[i]] = i;
 
-  _material_names = getParam<std::vector<std::string>>("materials");
+  _material_names = isParamValid("materials") ? getParam<std::vector<std::string>>("materials")
+                                              : std::vector<std::string>{};
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/HeatStructurePlate.C:42]: use default in parameter

File: modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C [hunk 38]
```diff
@@ -37,7 +37,8 @@ HeatStructureCylindrical::HeatStructureCylindrical(const InputParameters & param
   for (unsigned int i = 0; i < _names.size(); i++)
     _name_index[_names[i]] = i;
 
-  _material_names = getParam<std::vector<std::string>>("materials");
+  _material_names = isParamValid("materials") ? getParam<std::vector<std::string>>("materials")
+                                              : std::vector<std::string>{};
```
Comment (GiudGiud) [inline modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C:41]: same

File: modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C [hunk 39]
```diff
@@ -129,9 +129,11 @@ CrackFrontDefinition::CrackFrontDefinition(const InputParameters & parameters)
     _q_function_type(getParam<MooseEnum>("q_function_type")),
     _crack_front_points_provider(nullptr)
 {
+  auto boundary = isParamValid("boundary") ? getParam<std::vector<BoundaryName>>("boundary")
+                                           : std::vector<BoundaryName>{};
```
Comment (GiudGiud) [inline modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C:133]: default in boundary restrictable could work. It might bring a lot of code to adapt though

File: modules/porous_flow/include/actions/PorousFlowActionBase.h [hunk 40]
```diff
@@ -60,13 +60,13 @@ class PorousFlowActionBase : public Action, public PorousFlowDependencies
   const RealVectorValue _gravity;
 
   /// Name of the mass-fraction variables (if any)
-  const std::vector<VariableName> & _mass_fraction_vars;
+  const std::vector<VariableName> _mass_fraction_vars;
```
Comment (GiudGiud) [inline modules/porous_flow/include/actions/PorousFlowActionBase.h:63]: you can undo that once you have the default

File: framework/src/transfers/MultiAppDofCopyTransfer.C [hunk 41]
```diff
@@ -75,14 +75,14 @@ MultiAppDofCopyTransfer::initialSetup()
   // Convert block names to block IDs, fill with all blocks if unspecified
   if (_has_block_restrictions)
   {
-    const auto & from_block_names = getParam<std::vector<SubdomainName>>("from_blocks");
-    for (const auto & b : from_block_names)
-      if (!MooseMeshUtils::hasSubdomainName(const_cast<MeshBase &>(from_problem->mesh().getMesh()),
-                                            b))
-        paramError("from_blocks", "The block '", b, "' was not found in the mesh");
-
-    if (from_block_names.size())
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppDofCopyTransfer.C:84]: this was handling the `from_blocks = ''` user input better.

File: framework/src/transfers/MultiAppConservativeTransfer.C (hunk 34 above)
Comment (MengnanLi91) [reply framework/src/transfers/MultiAppConservativeTransfer.C:56]: Default value can not be used here. See the line above for `_preserve_transfer `. If default value is used, `_preserve_transfer` will always be true.

File: modules/porous_flow/src/actions/PorousFlowActionBase.C (hunk 35 above)
Comment (MengnanLi91) [reply modules/porous_flow/src/actions/PorousFlowActionBase.C:106]: Default can not be used here as well. See line 395, they want to error out when no value is set for "mass_fraction_vars". I don't think I should check that

File: modules/porous_flow/include/actions/PorousFlowActionBase.h (hunk 40 above)
Comment (MengnanLi91) [reply modules/porous_flow/include/actions/PorousFlowActionBase.h:63]: see the comment above

File: modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C (hunk 39 above)
Comment (MengnanLi91) [reply modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C:133]: I tried but default won't work. It failed the cases below: Mainly because "crack_front_points" and "crack_front_points_provider" uses "boundary" differently
`test:crack_tip_enrichment.crack_tip_enrichment_edge_2d ....................................... FAILED (ERRMSG)
test:solid_mechanics_basic.edge_crack_3d ..................................................... FAILED (ERRMSG)
test:solid_mechanics_basic.penny_crack ....................................................... FAILED (ERRMSG)


test:nucleation_uo.nucleateCrack ............................................................. FAILED (ERRMSG)
test:nucleation_uo.filterNucleation .......................................................... FAILED (ERRMSG)
test:solid_mechanics_basic.edge_crack_3d_fatigue ............................................. FAILED (ERRMSG)
test:solid_mechanics_basic.edge_crack_3d_mhs ................................................. FAILED (ERRMSG)
test:solid_mechanics_basic.edge_crack_2d_propagation_mhs ..................................... FAILED (ERRMSG)
test:solid_mechanics_basic.elliptical_crack .................................................. FAILED (ERRMSG)
test:solid_mechanics_basic.penny_crack_cfp ................................................... FAILED (ERRMSG)`

File: modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C (hunk 38 above)
Comment (MengnanLi91) [reply modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C:41]: Can not used default because `checkEqualSize` will fail. The reason for it to fail is "name" is a required param. It doesn't has default value. Then the size won't be equal

File: modules/thermal_hydraulics/src/components/HeatStructurePlate.C (hunk 37 above)
Comment (MengnanLi91) [reply modules/thermal_hydraulics/src/components/HeatStructurePlate.C:42]: same reason as HeatStructureCylindrical.C, can not use default here

File: modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C (hunk 36 above)
Comment (MengnanLi91) [reply modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C:105]: Can not use default because `_do_tuning(isParamValid("tune_parameters"))`

File: modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C (hunk 39 above)
Comment (GiudGiud) [reply modules/tensor_mechanics/src/userobjects/CrackFrontDefinition.C:133]: ok that was not unexpected. people have just been coding assuming no default downstream, and their code errors with 
`boundary = ""` already

File: modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C (hunk 36 above)
Comment (GiudGiud) [reply modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C:105]: ok that works

File: framework/src/transfers/MultiAppConservativeTransfer.C (hunk 34 above)
Comment (GiudGiud) [reply framework/src/transfers/MultiAppConservativeTransfer.C:56]: ok that works

File: framework/src/transfers/MultiAppDofCopyTransfer.C (hunk 41 above)
Comment (GiudGiud) [reply framework/src/transfers/MultiAppDofCopyTransfer.C:84]: that works

File: framework/src/outputs/AdvancedOutput.C (hunk 31 above)
Comment (MengnanLi91) [reply framework/src/outputs/AdvancedOutput.C]: Good catch! This has been addressed.

File: framework/src/meshgenerators/RenameBlockGenerator.C (hunk 26 above)
Comment (MengnanLi91) [reply framework/src/meshgenerators/RenameBlockGenerator.C]: The isParamSetByUser() is removed same as all the rest below

File: modules/porous_flow/src/actions/PorousFlowActionBase.C (hunk 35 above)
Comment (GiudGiud) [reply modules/porous_flow/src/actions/PorousFlowActionBase.C:106]: yeah it s not a clear winner here between your code and changing the check at line 395. So let s keep that

File: modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C (hunk 38 above)
Comment (GiudGiud) [reply modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C:41]: use the size check there instead of isParamValid

File: modules/thermal_hydraulics/src/components/HeatStructurePlate.C (hunk 37 above)
Comment (GiudGiud) [reply modules/thermal_hydraulics/src/components/HeatStructurePlate.C:42]: see other thread

File: modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C (hunk 38 above)
Comment (MengnanLi91) [reply modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C:41]: I prefer not to change it. Both way works in my opinion.

Comment (GiudGiud) [reply modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C:41]: I dont have a strong opinion there. They both work indeed and it s quite subjective

**Comment by GiudGiud** [comment]
I think we should squash into a few commits now, maybe just one (the easiest option). We should avoid capturing the back & forth in the commit history on the changes. 

otherwise this is good to go

**Comment by MengnanLi91** [comment]
> I think we should squash into a few commits now, maybe just one (the easiest option). We should avoid capturing the back & forth in the commit history on the changes.
> 
> otherwise this is good to go

Thanks so much for all the review efforts! Agree, I'll do the clean up after @dschwen reviewed it. He still has a change request out there.

**Review by dschwen — APPROVED** [review]
Looks fine!

**Review by loganharbour — APPROVED** [review]

**Review by GiudGiud — CHANGES_REQUESTED** [review]
as mentioned, this should be squashed to have either all commits contribute in the same direction or just one commit

**Review by GiudGiud — APPROVED** [review]
Looks good! Thanks for addressing that ticket, that was a nasty one.
