### PR TITLE
Get TimeIntegrators working with SCALAR variables.

### LINKED ISSUE #6289: Crank-Nicolson, RK2, and DIRK time integrators with scalar variables seem not working properly
With the following simple input
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  nx = 1
  ny = 1
  elem_type = QUAD4
[]

[Variables]
  [./n]
    family = SCALAR
    order = FIRST
    initial_condition = 1
  [../]
[]

[ScalarKernels]
  [./dn]
    type = ODETimeDerivative
    variable = n
  [../]
  [./ode1]
    type = ParsedODEKernel
    function = '-n'
    variable = n
  [../]
[]

[Executioner]
 type = Transient
 start_time = 0
 end_time = 1
 dt = 0.0001
 scheme = bdf2
 solve_type = 'PJFNK'
 timestep_tolerance = 1e-12
[]

[Outputs]
 csv = true
[]
```
The expected value at the end time is exp(1) = 2.718281828459045.

By changing the `Executioner/scheme`, we can obtain:
implicit-euler: 2.7184177551987
explicit-euler: 2.7184177551987
crank-nicolson: 1.6488243172143
bdf2: 2.7182818581953
rk-2: solve did not converge!
dirk: solve did not converge!

As you can see, those three integrators seem not working properly. Did I miss something?

Thanks.

### PR DESCRIPTION
**Pull request by jwpeterson**
There were a few different issues:
- ODETimeDerivative kernel residuals were being computed even when
  KT_NONTIME was requested.
- The ODETimeDerivative kernel was not assembling into the KT_TIME
  residual the way corresponding TimeKernels do.
- The implicit = false parameter was not respected by ParsedODEKernel,
  so the explicit time integration methods were getting the wrong
  answers.

The fixes for these things were pretty simple:
- Add new intermediate base class, ODETimeKernel.
  This class is responsible for overriding computeResidual() to make
  sure that ODE time derivative Kernels contribute to the proper
  residual, similarly to the way that TimeKernel works.
- Inherit the TransientInterface parameters in ScalarKernel, so that
  'implicit = false' is respected for ScalarKernels.
- Added a test verifying that Crank-Nicolson converges to the correct
  value.  Previously it was converging to a completely wrong value.

Closes #6289.

### CODE REVIEW

File: framework/src/base/NonlinearSystem.C [hunk 1]
```diff
@@ -1253,6 +1254,12 @@ NonlinearSystem::computeResidualInternal(Moose::KernelType type)
       const std::vector<MooseSharedPointer<ScalarKernel> > & scalars = _scalar_kernels.getActiveObjects();
       for (const auto & scalar_kernel : scalars)
       {
+        // Don't compute the residual if this is an ODETimeKernel and
+        // we've been asked for KT_NONTIME residuals.
+        ODETimeKernel * ode_time = dynamic_cast<ODETimeKernel *>(scalar_kernel.get());
+        if (type == Moose::KT_NONTIME && ode_time)
+          continue;
+
```
Comment (andrsd) [inline framework/src/base/NonlinearSystem.C]: Maybe we should consider doing the same deal with 3 warehouses i.e. one warehouse for each `ALL`, `TIME` and `NONTIME` scalar kernels like we do for normal kernels.

This implementation is not a big when people have just a few scalar kernels, but I am not sure what that will do in RELAP-7 where there is going to be possibly hundreds of them.

Comment (jwpeterson) [inline framework/src/base/NonlinearSystem.C]: OK, I can do this optimization, however this PR fixes the immediate serious bugs with TimeIntegrators for SCALAR variables if you think that would be worth getting merged sooner rather than later?

**Comment by andrsd** [comment]
👍
