### PR TITLE
Fix WCNSFVMomentumFlux condition to work with arbitrary velocity orientation

### LINKED ISSUE #23060: Flux BC for WCNSFV momentum equation gives wrong results if fluid flows in the negative (x,y,z) directions.
## Bug Description
The flux postprocessor assumes positive velocities and mass flow rates for inlets. The `WCNSFVMomentumFluxInlet` has the absolute value of the normal which yields weird results when the inlet velocity direction is negative in the chartesian coordinate system.  The user base (@snschune ), expressed that 

## Steps to Reproduce
Take a channel, use an inlet in the negative (x,y,z) direction and a positive number for massflow. 
It will give nonphysical results. Try running the input file below. 

```
bed_height = 10.0
bed_radius = 1.2
bed_porosity = 1
outlet_pressure = 5.5e6
T_fluid = 300
#density = 8.60161

#mass_flow_rate = 60.0
#flow_area = ${fparse pi * bed_radius * bed_radius * bed_porosity}
#flow_vel = ${fparse mass_flow_rate / flow_area / density}

[GlobalParams]
  fp = fluid_properties_obj
  porosity = 'porosity'
  rhie_chow_user_object = pins_rhie_chow_interpolator
[]

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    xmin = 0
    xmax = ${bed_radius}
    ymin = 0
    ymax = ${bed_height}
    nx = 6
    ny = 40
  []
  coord_type = RZ
[]

[Modules]
  [FluidProperties]
    [fluid_properties_obj]
      type = HeliumFluidProperties
    []
  []

  [NavierStokesFV]
    compressibility = 'weakly-compressible'
    porous_medium_treatment = true

    density = 'rho'
    dynamic_viscosity = 'mu'
    porosity = 'porosity'

    initial_velocity = '1e-6 0 0'
    initial_pressure = 5.4e6

    inlet_boundaries = top
    momentum_inlet_types = flux-mass
    flux_inlet_pps = mfr_pp
    #momentum_inlet_types = 'fixed-velocity'
    #momentum_inlet_function = '0 -${flow_vel}'
    wall_boundaries = 'left right'
    momentum_wall_types = 'slip slip'
    outlet_boundaries = bottom
    momentum_outlet_types = fixed-pressure
    pressure_function = ${outlet_pressure}

    pressure_face_interpolation = average
    momentum_advection_interpolation = upwind
    mass_advection_interpolation = upwind
  []
[]

[Materials]
  ## Fluid properties and non-dimensional numbers
  [fluid_props_to_mat_props]
    type = GeneralFunctorFluidProps
    pressure = 'pressure'
    T_fluid = ${T_fluid}
    speed = 'speed'
    characteristic_length = characteristic_length
  []

  [hydraulic_diameter]
    type = PiecewiseByBlockFunctorMaterial
    prop_name = 'characteristic_length'
    subdomain_to_prop_value = '0 1'
  []
[]

[AuxVariables]
  [porosity]
    family = MONOMIAL
    order = CONSTANT
    fv = true
    initial_condition = ${bed_porosity}
  []

  [density_var]
    family = MONOMIAL
    order = CONSTANT
    fv = true
  []
[]

[AuxKernels]
  [density_aux]
    type = ADFunctorElementalAux
    variable = density_var
    functor = rho
  []
[]

[Executioner]
  type = Transient
  end_time = 100
  [TimeStepper]
    type = IterationAdaptiveDT
    iteration_window = 2
    optimal_iterations = 8
    cutback_factor = 0.8
    growth_factor = 2
    dt = 1e-5
  []
  dtmax = 1
  line_search = l2
  solve_type = 'NEWTON'
  petsc_options_iname = '-pc_type -pc_factor_shift_type'
  petsc_options_value = 'lu NONZERO'
  nl_rel_tol = 1e-6
  nl_abs_tol = 1e-6
[]

[Postprocessors]
  [mfr_pp]
    type = Receiver
    default = 60
  []

  [inlet_mfr]
    type = VolumetricFlowRate
    advected_quantity = rho
    vel_x = 'superficial_vel_x'
    vel_y = 'superficial_vel_y'
    boundary = 'top'
  []

  [outlet_mfr]
    type = VolumetricFlowRate
    advected_quantity = rho
    vel_x = 'superficial_vel_x'
    vel_y = 'superficial_vel_y'
    boundary = 'bottom'
  []
[]

[Outputs]
  exodus = true
[]

```

The expected result is to get a uniform velocity field (considering the slip BCs). However it gives a spurious oscillation close to the inlet due to the wrong mass flow rate. 

## Impact
Users who assume that mass flow is always positive and don't factor in the surface normal when computing the inlet value might experience nonphysical results.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #23060

### CODE REVIEW

**Review by GiudGiud — DISMISSED** [review]

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C [hunk 1]
```diff
@@ -71,7 +71,12 @@ WCNSFVMomentumFluxBC::computeQpResidual()
     if (MooseUtils::absoluteFuzzyEqual(*_area_pp, 0))
       mooseError("Surface area is 0");
 
-  const Real contrib = std::abs(_face_info->normal()(_index));
+  // We assume that this boundary condition can only be specified on a boundary side.
+  // This means that the normal on the side points outwards and since the mass flow is
+  // defined as an absolute quantity, we need to use the negative of the normal here.
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:76]: What guarantee do we have that it is an absolute quantity?

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C [hunk 2]
```diff
@@ -71,7 +71,12 @@ WCNSFVMomentumFluxBC::computeQpResidual()
     if (MooseUtils::absoluteFuzzyEqual(*_area_pp, 0))
       mooseError("Surface area is 0");
 
-  const Real contrib = std::abs(_face_info->normal()(_index));
+  // We assume that this boundary condition can only be specified on a boundary side.
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:74]: If we are going to assume this, then you should assert that the `_face_info->neighborPtr()` is `nullptr`

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C (hunk 1 above)
Comment (grmnptr) [reply modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:76]: I'll rewrite this comment. I think the way I put it is wrong. We want to have a positive value for inflow and a negative value for outflow. so we need to use the negative of the normal if we are on a boundary. If we are not on a boundary then I have no idea on how to ensure that the inflow is really an inflow. Maybe we can ask for a direction parameter from the user. So I think for now we should restrict this.

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C (hunk 2 above)
Comment (grmnptr) [reply modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:74]: Right, thanks for the review!

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C (hunk 1 above)
Comment (grmnptr) [reply modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C]: Okay, I'll remove the boundary restriction and add another parameter which can be used to define the inlet direction. If it is specified, we use that, if not, we use the normal (whatever it is).

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C [hunk 3]
```diff
@@ -71,7 +71,16 @@ WCNSFVMomentumFluxBC::computeQpResidual()
     if (MooseUtils::absoluteFuzzyEqual(*_area_pp, 0))
       mooseError("Surface area is 0");
 
-  const Real contrib = std::abs(_face_info->normal()(_index));
+  // We restrict this BC for boundaries to be able to automatically determine the direction the
+  // flow is coming in from. In this case it is the negative of the surface normal (which points
+  // outwards). For internal faces, this would only be possible with additional parameters.
+  if (!_face_info->neighborPtr())
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:77]:
```suggestion
  if (_face_info->neighborPtr())
```

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Comment by grmnptr** [comment]
I added a little extra capability. Let me know if you think it is unnecessary.

File: modules/navier_stokes/src/fvbcs/WCNSFVEnergyFluxBC.C [hunk 4]
```diff
@@ -51,16 +52,28 @@ WCNSFVEnergyFluxBC::WCNSFVEnergyFluxBC(const InputParameters & params)
...
+    _cp(isParamValid(NS::cp) ? &getFunctor<ADReal>(NS::cp) : nullptr),
+    _direction(getParam<Point>("direction")),
+    _direction_specified_by_user(params.isParamSetByUser("direction"))
 {
+  if (_direction_specified_by_user)
+  {
+    if (_direction.is_zero())
+      paramError("direction",
+                 "The user should not define zero inlet/outlet advective flux values! Use noslip "
+                 "boundary conditions for that purpose!");
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/WCNSFVEnergyFluxBC.C:64]:
```suggestion
```

Comment (lindsayad) [reply modules/navier_stokes/src/fvbcs/WCNSFVEnergyFluxBC.C:64]: It seems like the more general error below covers this unique case

File: modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C [hunk 5]
```diff
@@ -71,21 +85,36 @@ WCNSFVMomentumFluxBC::computeQpResidual()
...
   else
-    return -_scaling_factor * std::pow((*_mdot_pp) / (*_area_pp), 2) * contrib /
-           (*_rho)(singleSidedFaceArg());
+  // In this case the cosine of the angle is already incorporated in mdot so we will
+  // have to correct back to get the right velocity magnitude
+  {
+    const auto velocity_magnitude =
+        (*_mdot_pp) / ((*_area_pp) * (*_rho)(singleSidedFaceArg()) * cos_angle);
+    return -_scaling_factor * (*_mdot_pp) / (*_area_pp) * incoming_vector(_index) *
+           velocity_magnitude;
```
Comment (lindsayad) [inline modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C:118]: Will want to see a test for this one for sure to make sure the math is good

**Review by lindsayad — CHANGES_REQUESTED** [review]
You may not want my review at this point as I suspect you are probably concocting some tests. Just give some indication of when I should re-review. I'm sorry that I've seemingly sent you down a bit of a rabbit hole for what was originally a very quick fix!

**Comment by lindsayad** [comment]
> I added a little extra capability. Let me know if you think it is unnecessary. I'll add coverage if you think it can stay.

I'll let you decide whether you want to move forward with the added capability :smile: I'm happy either way

**Comment by grmnptr** [comment]
I don’t thinks the failures are related

File: modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h [hunk 6]
```diff
@@ -47,4 +47,12 @@ class WCNSFVEnergyFluxBC : public FVFluxBC, public INSFVFlowBC
...
   /// Fluid specific heat capacity functor
   const Moose::Functor<ADReal> * const _cp;
+
+  /// The direction in which the flow is entering/leaving the domain. This is mainly used for cases
+  /// when the orientation of the face cannot be established (boundary on an internal face) or when the flow is
+  /// entering with an angle compared to the boundary surface.
+  const Point _direction;
+
+  /// Flag to store if the flow direction is specified by the user
+  const bool _direction_specified_by_user;
```
Comment (lindsayad) [inline modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h:57]: Maybe we should create a base class for these WCNSFV classes at some point, but you've already done a lot in this PR

Comment (lindsayad) [reply modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h:57]: Just mentioning that because of the apparent duplication between these three headers

File: modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i [hunk 7]
```diff
@@ -258,7 +258,7 @@ inlet_velocity = 0.001
     type = Receiver
     default = ${inlet_velocity}
   []
-  [surface_inlet]
+  [area_pp_left]
```
Comment (lindsayad) [inline modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i:261]: Why this change (and the one in the action input)? I assume these were the reasons for the re-gold?

**Review by lindsayad — DISMISSED** [review]

File: modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i (hunk 7 above)
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i:261]: This is actually a bug fix, in certain scenarios we didn't create area PPs in the action automatically for the flux BCs (scalar transport needs an area PP with the mass flux too to infer velocity). Now we create PPs every time a flux-bc is used. However the automatic name of the PP is `area_pp_${bd_name}` and I want to compare the action and non-action results to the same exodus file so I had to regold.

File: modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h (hunk 6 above)
Comment (grmnptr) [reply modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h:57]: I'll add the base class, wanna make this clean.

**Comment by grmnptr** [comment]
Okay, added base class, ready for a (hopefully) final round.

**Review by lindsayad — APPROVED** [review]
Nice work!
