### PR TITLE
Fix radial averaging system

### LINKED ISSUE #21786: Nonlocal Scalar Damage Models
## Reason
MOOSE has local damage models but they can exhibit mesh sensitivity. Nonlocal damage models allow for less mesh sensitivity while enabling the use of the same models. Damage averaging approach would be an easy first step that wouldn't require any change to existing damage models.
## Design
Create new damage model that would work with any existing damage model. It takes in a some form of averging user object and creates new damage_index for ComputeDamageStress.
## Impact
Would allow every current scalar local damage model to be used as a nonlocal version of itself.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #21786

### CODE REVIEW

File: framework/src/userobject/ThreadedRadialAverageLoop.C [hunk 1]
```diff
@@ -50,7 +50,7 @@ ThreadedRadialAverageLoop::operator()(const QPDataRange & qpdata_range)
 
     ret_matches.clear();
     std::size_t n_result =
-        kd_tree->radiusSearch(&(local_qp._q_point(0)), radius, ret_matches, search_params);
+        kd_tree->radiusSearch(&(local_qp._q_point(0)), radius * radius, ret_matches, search_params);
```
Comment (recuero) [inline framework/src/userobject/ThreadedRadialAverageLoop.C:53]: What's this fix about?

File: framework/src/userobject/RadialAverage.C [hunk 2]
```diff
@@ -37,6 +37,11 @@ RadialAverage::validParams()
   params.addClassDescription("Perform a radial equal weight average of a material property");
   params.addRequiredParam<std::string>("material_name", "Name of the material to average.");
   params.addRequiredParam<Real>("radius", "Cut-off radius for the averaging");
+  params.addParam<Real>(
+      "padding",
+      0.0,
+      "Padding for communication. This gets added to the radius when determining which QPs to send "
+      "to other processors. It should be of the order of the maximum element size.");
```
Comment (recuero) [inline framework/src/userobject/RadialAverage.C:44]: But `padding` is zero (default) in the tests?

File: framework/src/userobject/ThreadedRadialAverageLoop.C (hunk 1 above)
Comment (dschwen) [reply framework/src/userobject/ThreadedRadialAverageLoop.C:53]: That's how nanoflann expects the radius with the default L2 metric

File: framework/src/userobject/RadialAverage.C (hunk 2 above)
Comment (dschwen) [reply framework/src/userobject/RadialAverage.C:44]: Yeah, I think it will mostly be needed for inhomogeneous element sizes

File: framework/src/userobject/RadialAverage.C [hunk 3]
```diff
@@ -239,39 +204,31 @@ RadialAverage::meshChanged()
...
 
-  // iterate over active local elements
+  //
+  // iterate over active local elements and store all processor boundary node locations
+  //
   const auto end = mesh.active_local_elements_end();
   for (auto it = mesh.active_local_elements_begin(); it != end; ++it)
-    // find a face that faces either a boundary (nullptr) or a different processor
-    for (unsigned int s = 0; s < (*it)->n_sides(); ++s)
+    // find faces at a processor boundaries
```
Comment (bwspenc) [inline framework/src/userobject/RadialAverage.C:219]: at processor boundaries (get rid of the "a")

File: framework/include/userobject/RadialAverage.h [hunk 4]
```diff
@@ -100,17 +98,14 @@ class RadialAverage : public ElementUserObject
...
-
-  /// PointLocator for finding topological neighbors
-  std::unique_ptr<PointLocatorBase> _point_locator;
-
   /// The data structure used to find neighboring elements give a node ID
   std::vector<std::vector<const Elem *>> _nodes_to_elem_map;
 
-  // list of direct point neighbor elements of the current processor domain
-  std::set<const Elem *> _point_neighbors;
+  /// set of direct point neighbor elements of the current processor domain
```
Comment (bwspenc) [inline framework/include/userobject/RadialAverage.h:104]: /// Set of nodes on the boundary of the current processor domain

File: modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i [hunk 5]
```diff
@@ -63,7 +63,7 @@
     material_name = local_damage_reg
     execute_on = "INITIAL timestep_end"
     block = 0
-    radius = 0.3
+    radius = 0.55
```
Comment (bwspenc) [inline modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i:66]: Curious about why the radius was changed. Is this a more demanding test now?

File: framework/src/userobject/RadialAverage.C (hunk 2 above)
Comment (bwspenc) [reply framework/src/userobject/RadialAverage.C:44]: Are you sure we even need the padding? It seems like we're already going on the safe side by using the processor bounding boxes. Wouldn't that catch all possible needed communications? The way the comment is written, users will think they need to set this to something nonzero, which doesn't seem to be the case.

I'd say we should just remove this. If it is actually needed, it should be range checked to be >0, and the description should be revised to say that it's fine to be 0 for most cases.

**Review by bwspenc — COMMENTED** [review]
Thanks for fixing this! Seems like an elegant solution to the problem. Just a few minor things as noted.

File: framework/src/userobject/RadialAverage.C (hunk 2 above)
Comment (dschwen) [reply framework/src/userobject/RadialAverage.C:44]: Yeah, we might need it still. There is a radius search of qps around boundary nodes. That might need a wee bit of padding for some element geometries.

File: modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i (hunk 5 above)
Comment (dschwen) [reply modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i:66]: See above. Prior to this PR the value was the square root of the radius

**Review by bwspenc — APPROVED** [review]
