### PR TITLE
Commandline enhancements

### LINKED ISSUE #11168: CommandLine Enhancements
## Rationale

Tired of `--stuff=junk` not working.  Also need to support `std::string` arguments that have spaces in them(`--stuff='junk otherstuff'` and `--stuff 'junk otherstuff'`)

## Description

This stuff should work to make MOOSE apps more user friendly.

## Impact

Accept more command-line syntax

### PR DESCRIPTION
**Pull request by friedmud**
Two main enhancements: `std::string` params can now contain spaces and it's possible to use an `=` sign for assigning parameters like `--param=value`.

Also added some documentation on how to use the command-line and some unit tests for `CommandLine`.

Closes #11168

### CODE REVIEW

File: unit/src/CommandLine.C [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+        "string_param_without_default", "--string_param_without_default", "Doc");
+
+    params.addCommandLineParam<std::string>(
+        "compound_string_param", "--compound_string_param", "Doc");
+
+    params.addCommandLineParam<std::string>(
+        "compound_string_param_with_equals", "--compound_string_param_with_equals", "Doc");
+
+    int argc = 9;
+    const char * argv[9] = {"--bool_param_without_default",
```
Comment (permcody) [inline unit/src/CommandLine.C]: Magic numbers are unnecessary here. You can just initialize the array and pull out the number of entries so we don't have to keep them in sync. This is a unit test so it's no big deal, just a suggestion for better code. Also, the c-array could be a std::array.

**Review by permcody — APPROVED** [review]
