### PR TITLE
Fix TabulatedFluidProperties for multiphase class PorousFlowWaterVapor

### LINKED ISSUE #27457: Update TabulatedFluidProperties to work with Multiphase Classes
### Bug Description

Currently, TabulatedFluidProperties and TabulatedBicubicFluidProperties don't work with certain other classes which call functions like TriplePointPressure() which are implemented in other fluid properties such as Water97FluidProperties. 

Noted in https://github.com/idaholab/moose/discussions/27159#discussioncomment-9205632

### Steps to Reproduce

```
# MWE showing that PorousFlowWaterVapor does not work with TabulatedBicubicFluidProperties
# based on water_vapor_phase_change.i

[Mesh]
  type = GeneratedMesh
  dim = 3
  xmax = 10
  ymax = 10
  zmax = 10
[]

[GlobalParams]
  PorousFlowDictator = dictator
[]

[Variables]
  [pliq]
    initial_condition = 9e6
  []
  [h]
    scaling = 1e-3
  []
[]

[ICs]
  [hic]
    type = PorousFlowFluidPropertyIC
    variable = h
    porepressure = pliq
    property = enthalpy
    temperature = 300
    temperature_unit = Celsius
    fp = water_tab
  []
[]

[DiracKernels]
  [mass]
    type = ConstantPointSource
    point = '5 5 5'
    variable = pliq
    value = -1
  []
  [heat]
    type = ConstantPointSource
    point = '5 5 5'
    variable = h
    value = -1.344269e6
  []
[]

[Kernels]
  [mass]
    type = PorousFlowMassTimeDerivative
    variable = pliq
  []
  [heat]
    type = PorousFlowEnergyTimeDerivative
    variable = h
  []
[]

[UserObjects]
  [dictator]
    type = PorousFlowDictator
    porous_flow_vars = 'pliq h'
    number_fluid_phases = 2
    number_fluid_components = 1
  []
  [pc]
    type = PorousFlowCapillaryPressureBC
    pe = 1e5
    lambda = 2
    pc_max = 1e6
  []
  [fs]
    type = PorousFlowWaterVapor
    water_fp = water_tab
    capillary_pressure = pc
  []
[]

[FluidProperties]
  [water]
    type = Water97FluidProperties
  []
  [water_tab]
    type = TabulatedBicubicFluidProperties
    fp = water
    save_file = false

  []
[]

[Materials]
  [watervapor]
    type = PorousFlowFluidStateSingleComponent
    porepressure = pliq
    enthalpy = h
    temperature_unit = Celsius
    capillary_pressure = pc
    fluid_state = fs
  []
  [permeability]
    type = PorousFlowPermeabilityConst
    permeability = '1e-14 0 0 0 1e-14 0 0 0 1e-14'
  []
  [relperm0]
    type = PorousFlowRelativePermeabilityCorey
    n = 2
    phase = 0
  []
  [relperm1]
    type = PorousFlowRelativePermeabilityCorey
    n = 3
    phase = 1
  []
  [porosity]
    type = PorousFlowPorosityConst
    porosity = 0.2
  []
  [internal_energy]
    type = PorousFlowMatrixInternalEnergy
    density = 2650
    specific_heat_capacity = 1000
  []
[]


[AuxVariables]

    [temperature]
      order = CONSTANT
      family = MONOMIAL
    []

  []
  
  [AuxKernels]


    [temperature]
      type = PorousFlowPropertyAux
      variable = temperature
      property = temperature
      execute_on = 'initial timestep_end'
    []
  []
  

[Executioner]
  type = Transient
  solve_type = NEWTON
  end_time = 1e3
  nl_abs_tol = 1e-12
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 10
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]


[Outputs]
  csv = true
  perf_graph = false
[]
```

Which produces 
```
*** ERROR ***
/home/moose_projects/mwe_porousflowwatervapor_tab.i:87.3:
The following error occurred in the FluidProperties 'water_tab' of type TabulatedBicubicFluidProperties.

virtual libMesh::Real SinglePhaseFluidProperties::triplePointPressure() const not implemented.
```

### Impact

Currently this means you can't use TFP with PorousFlowWaterVapor and potentially other classes which call functions associated with multiphase behavior. 

It can be useful to use TFP to save time on calculations and for convergence issues.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by aikubo**
closes #27457

### CODE REVIEW

**Comment by aikubo** [comment]
This is my first moose pull request so I expect there to be some formatting or other errors. 
thanks for your patience

Also, I found that using the VScode git interface to try and push and pull causes errors. So I recommend other newbies do it all on terminal.

**Comment by GiudGiud** [comment]
so there's these two errors which should be fairly easy to fix

```
##########################################################################
ERROR: Your patch does not contain a valid ticket reference! (i.e. #1234)
Merge branch 'tfp_water_vapor' of https://github.com/aikubo/moose into test
style patch
remove debug statements
add tests in PorousFlow fluidstate
Add functions so TabulatedFluidProperties works with multiphase class PorousFlowWaterVapor

ERROR: The following files contain trailing whitespace after applying your patch:
	modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
##########################################################################
```

File: modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h [hunk 1]
```diff
@@ -110,6 +112,23 @@ class TabulatedFluidProperties : public SinglePhaseFluidProperties
 
   virtual void vaporPressure(Real temperature, Real & psat, Real & dpsat_dT) const override;
 
+  template <typename T>
+  void vaporPressureTemplate(const T & temperature, T & psat, T & dpsat_dT) const;
```
Comment (GiudGiud) [inline modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h:116]: is this defined?

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 2]
```diff
@@ -76,6 +76,10 @@ TabulatedFluidProperties::validParams()
       false,
       "Option to use a base-10 logarithmically-spaced grid for specific volume instead of a "
       "linearly-spaced grid.");
+  param.addParam<bool>("p_h_variables",
+                       false,
+                       "If using pressure enthalpy variables, interpolates from PT to h"
+                       "may be wrong especially in multiphase.");
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:82]: say what it does?

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 3]
```diff
@@ -609,6 +623,15 @@ TabulatedFluidProperties::h_from_p_T(Real pressure, Real temperature) const
   }
 }
 
+ADReal
+TabulatedFluidProperties::h_from_p_T(const ADReal & pressure, const ADReal & temperature) const
+{
+  if (_fp) // Assuming _fp can handle ADReal types
+    return _fp->h_from_p_T(pressure, temperature);
+  else
+    paramError("fp", "Fluid properties object does not support ADReal computations.");
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:632]: cant handle this specific one

maybe create a routine with a comprehensive error message, that says what is missing
TFP::fluidPropertyForwardError(std::string desired_routine, bool is_ad)

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 4]
```diff
@@ -895,6 +918,100 @@ TabulatedFluidProperties::vaporPressure(Real temperature, Real & psat, Real & dp
     mooseError("vaporPressure not specified.");
 }
 
+Real
+TabulatedFluidProperties::vaporTemperature(Real pressure) const
+{
+
+  const FPDualReal p = pressure;
+
+  return vaporTemperature_ad(p).value();
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:927]: use the same forward as the others instead?

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 5]
```diff
@@ -895,6 +918,100 @@ TabulatedFluidProperties::vaporPressure(Real temperature, Real & psat, Real & dp
...
+}
+
+void
+TabulatedFluidProperties::vaporTemperature(Real pressure, Real & Tsat, Real & dTsat_dp) const
+{
+
+  if (_fp)
+    _fp->vaporTemperature(pressure, Tsat, dTsat_dp);
+  else
+    mooseError("vaporTemperature not specified.");
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:937]: It's not really that it s not specified. It s more:

"Tabulation does not contain the vapor temperature. To use the TabulatedFluidProperties and compute the vaporTemperature, please provide another fluid property using the 'fp' parameter, which will be used to compute the vapor temperature"

and same, make it a standard error message in a TFP routine, which you can re-use for each of these routines

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 6]
```diff
@@ -1272,20 +1402,19 @@ TabulatedFluidProperties::checkInputVariables(T & pressure, T & temperature) con
   if (pressure < _pressure_min || pressure > _pressure_max)
   {
     if (_error_on_out_of_bounds)
-      throw MooseException("Pressure " + Moose::stringify(pressure) +
+      throw MooseException("Pressure " + 
                            " is outside the range of tabulated pressure (" +
-                           Moose::stringify(_pressure_min) + ", " +
-                           Moose::stringify(_pressure_max) + ").");
+                           
+
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:1408]: revert

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 7]
```diff
@@ -1272,20 +1402,19 @@ TabulatedFluidProperties::checkInputVariables(T & pressure, T & temperature) con
...
   }
 
   if (temperature < _temperature_min || temperature > _temperature_max)
   {
     if (_error_on_out_of_bounds)
-      mooseError("Temperature " + Moose::stringify(temperature) +
-                 " is outside the range of tabulated temperature (" +
-                 Moose::stringify(_temperature_min) + ", " + Moose::stringify(_temperature_max) +
+      mooseError("Temperature " + " is outside the range of tabulated temperature (" +
+
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:1417]: same

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 8]
```diff
@@ -1299,17 +1428,17 @@ TabulatedFluidProperties::checkInitialGuess() const
...
+                   
 
     if (_T_initial_guess < _temperature_min || _T_initial_guess > _temperature_max)
       mooseWarning("Temperature initial guess for (p,T), (v,e) conversions " +
-                   Moose::stringify(_T_initial_guess) +
+                   
                    " is outside the range of tabulated "
                    "temperature (" +
-                   Moose::stringify(_temperature_min) + ", " + Moose::stringify(_temperature_max) +
+
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:1441]: same

File: modules/porous_flow/test/tests/fluidstate/tests [hunk 9]
```diff
@@ -181,6 +181,15 @@
     design = 'PorousFlowWaterVapor.md'
     issues = '#13108'
   []
+  [water_vapor_tabulated]
+    type = 'CSVDiff'
+    input = 'water_vapor_tab.i'
+    csvdiff = 'water_vapor_twophase.csv'
+    threading = '!pthreads'
+    requirement = 'The system shall be able to use tabulate fluid properties.'
```
Comment (GiudGiud) [inline modules/porous_flow/test/tests/fluidstate/tests:189]:
```suggestion
    requirement = 'The system shall be able to use tabulated fluid properties in conjunction with another fluid properties object to provide non-tabulated properties.'
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]
if it becomes too complicated we will want to use a tabulation for all these things instead

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C (hunk 2 above)
Comment (aikubo) [reply modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C]: addressed in [a6a0e70](https://github.com/idaholab/moose/pull/27506/commits/a6a0e70fd320f10a2453e722ddc0c69452dc09be)

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C (hunk 3 above)
Comment (aikubo) [reply modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C]: added in [a6a0e70](https://github.com/idaholab/moose/pull/27506/commits/a6a0e70fd320f10a2453e722ddc0c69452dc09be)

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C (hunk 4 above)
Comment (aikubo) [reply modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C]: addressed in [a6a0e70](https://github.com/idaholab/moose/pull/27506/commits/a6a0e70fd320f10a2453e722ddc0c69452dc09be)

File: modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h [hunk 10]
```diff
@@ -311,8 +311,20 @@ class SinglePhaseFluidProperties : public FluidProperties
    */
   virtual Real vaporTemperature(Real p) const;
   virtual void vaporTemperature(Real p, Real & Tsat, Real & dTsat_dp) const;
-  DualReal vaporTemperature(const DualReal & p) const;
+  virtual DualReal vaporTemperature(const DualReal & p) const;
+  virtual FPDualReal vaporTemperature_ad(const FPDualReal & p) const;
```
[the remark this answers is not in the document]
Comment (aikubo) [reply modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h:315]: `virtual FPDualReal vaporTemperature_ad(const FPDualReal & p) const;`
is there to match the declaration in Water97FluidProperties

https://github.com/idaholab/moose/blob/1145d861a4cf31c9a159563694bd7d5619353a09/modules/fluid_properties/include/fluidproperties/Water97FluidProperties.h#L813

Maybe it's not necessary but I was trying to keep it consistent. There are some inconsistencies between AD versions and non-AD versions throughout Water97 and other fluid properties, some use template functions which I think is the prefered implementation and others use the `_ad` implementation.

File: modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h (hunk 1 above)
Comment (aikubo) [reply modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h:116]: Again, I was trying to keep it consistent with Water97 but I did forget to define it so I can just take it out.

Comment (GiudGiud) [reply modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h:116]: Sounds good. Let s remove that one

**Comment by GiudGiud** [comment]
let's remove the merge commit. We prefer rebase. You can remove it by:
```
git reset --hard a6a0e70
git fetch upstream
git rebase upstream/devel
git push origin HEAD:tfp_water_vapor -f
```

you have more formatting issues
```
##########################################################################
ERROR: The following files contain trailing whitespace after applying your patch:
	modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
##########################################################################
```

if you are using VSCode you need to use our user settings, and it wont be a problem ever again
https://mooseframework.inl.gov/help/development/VSCode.html

File: modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h (hunk 1 above)
Comment (aikubo) [reply modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h]: removed.

File: modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h (hunk 10 above)
[the remark this answers is not in the document]
Comment (aikubo) [reply modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h:315]: In Water97:

The general format is that there is a Real version, an ADReal version, and then a void version which takes the derivatives and then another void version which is AD. All of these reference two template functions one with the derivatives and one without.

https://github.com/idaholab/moose/blob/1145d861a4cf31c9a159563694bd7d5619353a09/modules/fluid_properties/src/fluidproperties/Water97FluidProperties.C#L80C1-L107C2

However, for some of the functions (vaporTemperature and T_from_p_h) there's no template function just a `_ad` version which is used for each of the functions. 
https://github.com/idaholab/moose/blob/1145d861a4cf31c9a159563694bd7d5619353a09/modules/fluid_properties/src/fluidproperties/Water97FluidProperties.C#L511C1-L549C2

I think both implementations have the same behavior so I'm not totally sure what the difference is. Also, I'm still not clear on the void versions with the derivatives but they are necessary for the functioning of things like PorousFlowWaterVapor. When I looked into what PFWaterVapor calls it calls `void Water97FluidProperties::vaporTemperature` then  `Water97FluidProperties::vaporTemperature_ad` in 

https://github.com/idaholab/moose/blob/087d66eb2aace3e6b0fe1db7b316749254c301d2/modules/porous_flow/src/userobjects/PorousFlowWaterVapor.C#L105C1-L109C49

[the remark this answers is not in the document]
Comment (cpgr) [reply modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h:315]: From memory (it was a long time ago!) those `foo_ad` methods are really just used internally to avoid hand-coding the derivatives. I think the `FPDualReal` ones use a smaller derivative container for speed. None of these are exposed in the public `SinglePhaseFluidProperties` API, so you probably don't want them in TabulatedFluidProperties.

I did have an idea which I'll add in a comment below

[the remark this answers is not in the document]
Comment (aikubo) [reply modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h:315]: Removed in d2f638c

File: modules/porous_flow/test/tests/fluidstate/tests (hunk 9 above)
Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/tests:189]: let s have the requirement be a little more specific

File: modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C [hunk 11]
```diff
@@ -892,7 +917,88 @@ TabulatedFluidProperties::vaporPressure(Real temperature, Real & psat, Real & dp
...
+}
+
+Real
+TabulatedFluidProperties::T_from_p_h(Real pressure, Real enthalpy) const
+{
+
+  if (_fp)
+  {
+    return _fp->T_from_p_h(pressure, enthalpy);
+  }
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C:999]:
```suggestion
    return _fp->T_from_p_h(pressure, enthalpy);
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]
minor things

**Comment by GiudGiud** [comment]
cleaned up the commit history a little. let's see if tests pass

**Comment by aikubo** [comment]
@cpgr @GiudGiud 

I went back to my original input file from #27159. And I get a different error using tabulated fluid properties than from the test input file I made `water_vapor_tab.i`

```
*** ERROR ***
/home/akh/myprojects/moose_projects/dikes/sims/multi/MVE_s_from_h_p_error.i:186.5:
The following error occurred in the FluidProperties 'water97' of type Water97FluidProperties.

The fluid properties class 'Water97FluidProperties' has not implemented the method below, which computes derivatives of fluid properties with regards to the flow variables. If your application requires this method, you must either implement it or use a different fluid properties  class.

virtual void SinglePhaseFluidProperties::s_from_h_p(libMesh::Real, libMesh::Real, libMesh::Real&, libMesh::Real&, libMesh::Real&) const

You can avoid this error by neglecting the unimplemented derivatives of fluid properties by setting the 'allow_imperfect_jacobians' parameter

Stack frames: 25
0: libMesh::print_trace(std::ostream&)
1: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
2: MooseBase::callMooseError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) const
3: /home/akh/myprojects/moose_projects/moose/modules/fluid_properties/lib/libfluid_properties-opt.so.0(+0xbbd84) [0x7f0b716bbd84]
4: /home/akh/myprojects/moose_projects/moose/modules/fluid_properties/lib/libfluid_properties-opt.so.0(+0x13fce4) [0x7f0b7173fce4]
5: /home/akh/myprojects/moose_projects/moose/modules/fluid_properties/lib/libfluid_properties-opt.so.0(+0x143574) [0x7f0b71743574]
6: SinglePhaseFluidProperties::T_from_p_h(double, double, double&, double&, double&) const
7: /home/akh/myprojects/moose_projects/moose/modules/fluid_properties/lib/libfluid_properties-opt.so.0(+0x126f35) [0x7f0b71726f35]
8: PorousFlowWaterVapor::thermophysicalProperties(MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<64ul> >, true> const&, MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<64ul> >, true> const&, unsigned int, FluidStatePhaseEnum&, std::vector<FluidStateProperties, std::allocator<FluidStateProperties> >&) const
9: PorousFlowWaterVapor::thermophysicalProperties(double, double, unsigned int, std::vector<FluidStateProperties, std::allocator<FluidStateProperties> >&) const
10: PorousFlowFluidStateBaseMaterialTempl<false>::initQpStatefulProperties()
11: PorousFlowFluidStateSingleComponentTempl<false>::initQpStatefulProperties()
12: MaterialBase::initStatefulProperties(unsigned int)
13: MaterialPropertyStorage::initStatefulProps(unsigned int, std::vector<std::shared_ptr<MaterialBase>, std::allocator<std::shared_ptr<MaterialBase> > > const&, unsigned int, libMesh::Elem const&, unsigned int)
14: ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool)
15: /home/akh/myprojects/moose_projects/moose/framework/libmoose-opt.so.0(+0x20e16d0) [0x7f0b74ee16d0]
16: FEProblemBase::initElementStatefulProps(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool)
17: FEProblemBase::initialSetup()
18: Transient::init()
19: MooseApp::executeExecutioner()
20: MooseApp::run()
21: main
22: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f0b68c29d90]
23: __libc_start_main
24: ../../dikes-opt(+0x33ef) [0x557abb8ce3ef]
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

```

This is an issue with the initial condition for enthalpy. Basically if you're not in the two phase zone, it gives this error. But I don't know why because I don't think any of these objects ever call `s_from_h_p` and it ONLY happens when use Tabulated Fluid Properties. 

Here's a MVE:

```
[Mesh]
    [gen]
      type = GeneratedMeshGenerator
      dim = 2

    []
  []

  [GlobalParams]
    PorousFlowDictator = dictator
  []

  [AuxVariables]
    [pressure_gas]
      order = CONSTANT
      family = MONOMIAL
    []
    [pressure_water]
      order = CONSTANT
      family = MONOMIAL
    []
    [enthalpy_gas]
      order = CONSTANT
      family = MONOMIAL
    []
    [enthalpy_water]
      order = CONSTANT
      family = MONOMIAL
    []
    [saturation_gas]
      order = CONSTANT
      family = MONOMIAL
    []
    [saturation_water]
      order = CONSTANT
      family = MONOMIAL
    []
    [density_water]
      order = CONSTANT
      family = MONOMIAL
    []
    [density_gas]
      order = CONSTANT
      family = MONOMIAL
    []
    [viscosity_water]
      order = CONSTANT
      family = MONOMIAL
    []
    [viscosity_gas]
      order = CONSTANT
      family = MONOMIAL
    []
    # [temperature]
    #   order = CONSTANT
    #   family = MONOMIAL
    # []
  []

  [AuxKernels]
    [enthalpy_water]
      type = PorousFlowPropertyAux
      variable = enthalpy_water
      property = enthalpy
      phase = 0
      execute_on = 'initial timestep_end'
    []
    [enthalpy_gas]
      type = PorousFlowPropertyAux
      variable = enthalpy_gas
      property = enthalpy
      phase = 1
      execute_on = 'initial timestep_end'
    []
    [pressure_water]
      type = PorousFlowPropertyAux
      variable = pressure_water
      property = pressure
      phase = 0
      execute_on = 'initial timestep_end'
    []
    [pressure_gas]
      type = PorousFlowPropertyAux
      variable = pressure_gas
      property = pressure
      phase = 1
      execute_on = 'initial timestep_end'
    []
    [saturation_water]
      type = PorousFlowPropertyAux
      variable = saturation_water
      property = saturation
      phase = 0
      execute_on = 'initial timestep_end'
    []
    [saturation_gas]
      type = PorousFlowPropertyAux
      variable = saturation_gas
      property = saturation
      phase = 1
      execute_on = 'initial timestep_end'
    []
    [density_water]
      type = PorousFlowPropertyAux
      variable = density_water
      property = density
      phase = 0
      execute_on = 'initial timestep_end'
    []
    [density_gas]
      type = PorousFlowPropertyAux
      variable = density_gas
      property = density
      phase = 1
      execute_on = 'initial timestep_end'
    []
    [viscosity_water]
      type = PorousFlowPropertyAux
      variable = viscosity_water
      property = viscosity
      phase = 0
      execute_on = 'initial timestep_end'
    []
    [viscosity_gas]
      type = PorousFlowPropertyAux
      variable = viscosity_gas
      property = viscosity
      phase = 1
      execute_on = 'initial timestep_end'
    []
  []

  [UserObjects]
    [dictator]
      type = PorousFlowDictator
      porous_flow_vars = 'pliquid h'
      number_fluid_phases = 2
      number_fluid_components = 1
    []
    [pc] #from porousflow/test/tests/fluidstate/watervapor.i
      type = PorousFlowCapillaryPressureBC
      pe = 1e5
      lambda = 2
      pc_max = 1e6
    []
    [fs]
      type = PorousFlowWaterVapor
      water_fp = water_tab
      capillary_pressure = pc
    []
  []


  [Variables]
    [pliquid]
      initial_condition = 1e6
    []
    [h]
      initial_condition = 8e4 # if you change it to 8e5 like in water_vapor_tab.i it works fine
    []
  []


  [Kernels]
    [mass]
      type = PorousFlowMassTimeDerivative
      variable = pliquid
    []
    [heat]
      type = PorousFlowEnergyTimeDerivative
      variable = h

    []
  []


  [FluidProperties]
    [water97]
      type = Water97FluidProperties    # IAPWS-IF97
    []
    [water_tab]
      type = TabulatedBicubicFluidProperties
      fp = water97
      fluid_property_file = 'water_extended.csv'
      p_h_variables = true
    []

  []

  [Materials]
      [watervapor]
        type = PorousFlowFluidStateSingleComponent
        porepressure = pliquid
        enthalpy = h
        capillary_pressure = pc
        fluid_state = fs
        temperature_unit = Kelvin
      []

      [porosity_wallrock]
        type = PorousFlowPorosityConst
        porosity = 0.1
      []
      [permeability]
        type = PorousFlowPermeabilityConst
        permeability = '1E-13 0 0   0 1E-13 0   0 0 1E-13'
      []
      [relperm_water] # from watervapor.i
        type = PorousFlowRelativePermeabilityCorey
        n = 2
        phase = 0
      []
      [relperm_gas]  # from watervapor.i
        type = PorousFlowRelativePermeabilityCorey
        n = 3
        phase = 1
      []
      [internal_energy]
        type = PorousFlowMatrixInternalEnergy
        density = 2500 # kg/m^3
        specific_heat_capacity = 1200 # J/kg/K
      []

  []

  [Preconditioning]
    [smp]
      type = SMP
      full = true
      petsc_options_iname = '-pc_type -pc_factor_mat_solver_package'
      petsc_options_value = ' lu       mumps'
    []
  []

  [Executioner]
    type = Transient
    solve_type = NEWTON
    end_time = 100
  []

```

**Comment by GiudGiud** [comment]
so you forwarded s_from_h_p to Water97, but is it defined there?
Is it defined as s_from_p_h by any chance?

**Comment by aikubo** [comment]
> so you forwarded s_from_h_p to Water97, but is it defined there?
It isn't defined in Water97 and I can add it but I find it odd because I'm not sure why this error occurs. 

> Is it defined as s_from_p_h by any chance?
no it is not but it would good to check that

**Comment by GiudGiud** [comment]
the backtrace explains the story:
-something in porousflow water calls T_from_p_h
- it s not implemented in TFP, so it goes to the implementation in SinglePhaseFP
- this implementation uses s_from_p_h which is not implemented anywhere

so two solutions:
- implement s_from_p_h (hard imo)
- implement T_from_p_h (easier? you may need to roll out the Newton inversion routine on h_from_p_T)

**Comment by aikubo** [comment]
Could you just implement it as basically a copy of `s_from_p_T`? Or is more complexity necessary?

```
template <typename T>
T
Water97FluidProperties::s_from_h_p_template(const T & enthalpy, const T & pressure) const
{
  T temperature = T_from_h_p(enthalpy, pressure);
  return s_from_p_T_template(pressure, temperature);
}

template <typename T>
void
Water97FluidProperties::s_from_h_p_template(
    const T & enthalpy, const T & pressure, T & s, T & ds_dh, T & ds_dp) const
{
  auto functor = [this](const auto & enthalpy, const auto & pressure)
  { return this->s_from_p_T_template(enthalpy, pressure); };

  xyDerivatives(enthalpy, pressure, s, ds_dh, ds_dp, functor);
}

```

And another question, looking closely there's `T_from_p_h` and `T_from_h_p` in Water97FluidProperties (one of which I added)  
And in SinglePhaseFluidProperties there's both. But only `T_from_h_p` in Tabulated Fluid Properties. Aren't these the same? Which should it be?

**Comment by GiudGiud** [comment]
but if T_from_h_p is implemented, T_from_p_h is definitely the faster and easier to implement

**Comment by aikubo** [comment]
I've added `s_from_h_p` and it works fine but I kept getting issues with 

```
*** ERROR ***
/home/akh/myprojects/moose_projects/dikes/MVE_s_from_h_p_error.i:183.5:
The following error occurred in the FluidProperties 'water_tab' of type TabulatedBicubicFluidProperties.

You must construct pT from vh tables when calling e_from_v_h.
```

When you turn both `construct_pT_from_ve=true` and `construct_pT_from_vh=true` everything works fine. This only occurs in certain regions of the phase diagram for p,h variables in porousflow. I think it might make sense to turn on those flags automatically as part of `p_h_variables` flag in TabulatedFluidProperties. Or if not to note it somewhere.

**Comment by GiudGiud** [comment]
> . I think it might make sense to turn on those flags automatically as part of p_h_variables flag in TabulatedFluidProperties. 

When does this flag get set? By the user? If so then sure. 

> Or if not to note it somewhere.

That's fine too.
I'm guessing that you are hitting these 'new' calls because:
- the TFP isnt implementing something, calls Water97, which uses routines that _from_h_p back from the TFP, which are implemented in the TFP but only if the flag is on

**Comment by aikubo** [comment]
I was having a hard time tracking down some of the issues I was having and I'll do my best to summarize 

I tried a input file in the Liquid state and it wasn't running at all (MVE below). I added the `s_from_h_p` to Water97FluidProperties and accordingly to TabulatedFluidProperties. 
After that the input file ran but the temperature was wrong. It gave a temperature of 299 K when it should be 377 K. I tracked this to PorousFlowWaterVapor calling `T_from_p_h` but the AD version which wasn't implemented in TabulatedFluidProperties, only the `Real` version. 

I also had to add a `ADReal T_from_p_h` version to WaterFluidProperties because the current version is `FPADReal T_from_p_h_ad`.  

The way I implemented `ADReal T_from_p_h` is imho terrible but I had a hard time compiling between the `FPADReal` and `ADReal` types. It's unclear to me when to use `FPADReal`, it seems to be used mostly for internal FP code. And as far as I can tell the `T_from_p_h` function is only directly called outside the FluidProperties module in `PorousFlowWaterVapor` .  What is the correct usage and correct way to convert between types? 

Finally, I cleaned up the commit history. 

Thanks for your patience bearing with a MOOSE and C++ novice. 

Here's the liquid state MVE which works now:
```
# at 1MPa (1e6 Pa) and 440 kJ/kg (440000) T should be 377 K

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
  []
[]

[GlobalParams]
  PorousFlowDictator = dictator
[]

[AuxVariables]
  [pressure_gas]
    order = CONSTANT
    family = MONOMIAL
  []
  [pressure_water]
    order = CONSTANT
    family = MONOMIAL
  []
  [enthalpy_gas]
    order = CONSTANT
    family = MONOMIAL
  []
  [enthalpy_water]
    order = CONSTANT
    family = MONOMIAL
  []
  [saturation_gas]
    order = CONSTANT
    family = MONOMIAL
  []
  [saturation_water]
    order = CONSTANT
    family = MONOMIAL
  []
  [density_water]
    order = CONSTANT
    family = MONOMIAL
  []
  [density_gas]
    order = CONSTANT
    family = MONOMIAL
  []
  [viscosity_water]
    order = CONSTANT
    family = MONOMIAL
  []
  [viscosity_gas]
    order = CONSTANT
    family = MONOMIAL
  []
  [temperature]
    order = CONSTANT
    family = MONOMIAL
  []
[]

[AuxKernels]
  [enthalpy_water]
    type = PorousFlowPropertyAux
    variable = enthalpy_water
    property = enthalpy
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [enthalpy_gas]
    type = PorousFlowPropertyAux
    variable = enthalpy_gas
    property = enthalpy
    phase = 1
    execute_on = 'initial timestep_end'
  []
  [pressure_water]
    type = PorousFlowPropertyAux
    variable = pressure_water
    property = pressure
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [pressure_gas]
    type = PorousFlowPropertyAux
    variable = pressure_gas
    property = pressure
    phase = 1
    execute_on = 'initial timestep_end'
  []
  [saturation_water]
    type = PorousFlowPropertyAux
    variable = saturation_water
    property = saturation
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [saturation_gas]
    type = PorousFlowPropertyAux
    variable = saturation_gas
    property = saturation
    phase = 1
    execute_on = 'initial timestep_end'
  []
  [density_water]
    type = PorousFlowPropertyAux
    variable = density_water
    property = density
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [density_gas]
    type = PorousFlowPropertyAux
    variable = density_gas
    property = density
    phase = 1
    execute_on = 'initial timestep_end'
  []
  [viscosity_water]
    type = PorousFlowPropertyAux
    variable = viscosity_water
    property = viscosity
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [viscosity_gas]
    type = PorousFlowPropertyAux
    variable = viscosity_gas
    property = viscosity
    phase = 1
    execute_on = 'initial timestep_end'
  []
  [temperature]
    type = PorousFlowPropertyAux
    variable = temperature
    property = temperature
    execute_on = 'initial timestep_end'
  []
[]

[UserObjects]
  [dictator]
    type = PorousFlowDictator
    porous_flow_vars = 'pliquid h'
    number_fluid_phases = 2
    number_fluid_components = 1
  []
  [pc] #from porousflow/test/tests/fluidstate/watervapor.i
    type = PorousFlowCapillaryPressureBC
    pe = 1e5
    lambda = 2
    pc_max = 1e6
  []
  [fs]
    type = PorousFlowWaterVapor
    water_fp = water_tab
    capillary_pressure = pc
  []
[]

[Variables]
  [pliquid]
    initial_condition = 1e6
  []
  [h]
    initial_condition = 440e3
  []
[]

[Kernels]
  [mass]
    type = PorousFlowMassTimeDerivative
    variable = pliquid
  []
  [heat]
    type = PorousFlowEnergyTimeDerivative
    variable = h
  []
[]

[FluidProperties]
  [water97]
    type = Water97FluidProperties # IAPWS-IF97
  []
  [water_tab]
    type = TabulatedBicubicFluidProperties
    fp = water97
    p_h_variables = true
  []
[]

[Materials]
  [watervapor]
    type = PorousFlowFluidStateSingleComponent
    porepressure = pliquid
    enthalpy = h
    capillary_pressure = pc
    fluid_state = fs
    temperature_unit = Kelvin
  []

  [porosity_wallrock]
    type = PorousFlowPorosityConst
    porosity = 0.1
  []
  [permeability]
    type = PorousFlowPermeabilityConst
    permeability = '1E-13 0 0   0 1E-13 0   0 0 1E-13'
  []
  [relperm_water] # from watervapor.i
    type = PorousFlowRelativePermeabilityCorey
    n = 2
    phase = 0
  []
  [relperm_gas] # from watervapor.i
    type = PorousFlowRelativePermeabilityCorey
    n = 3
    phase = 1
  []
  [internal_energy]
    type = PorousFlowMatrixInternalEnergy
    density = 2500 # kg/m^3
    specific_heat_capacity = 1200 # J/kg/K
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  end_time = 1
  nl_abs_tol = 1e-12
[]

[Postprocessors]
  [density_water]
    type = ElementAverageValue
    variable = density_water
    execute_on = 'initial timestep_end'
  []
  [density_gas]
    type = ElementAverageValue
    variable = density_gas
    execute_on = 'initial timestep_end'
  []
  [viscosity_water]
    type = ElementAverageValue
    variable = viscosity_water
    execute_on = 'initial timestep_end'
  []
  [viscosity_gas]
    type = ElementAverageValue
    variable = viscosity_gas
    execute_on = 'initial timestep_end'
  []
  [enthalpy_water]
    type = ElementAverageValue
    variable = enthalpy_water
    execute_on = 'initial timestep_end'
  []
  [enthalpy_gas]
    type = ElementAverageValue
    variable = enthalpy_gas
    execute_on = 'initial timestep_end'
  []
  [sg]
    type = ElementAverageValue
    variable = saturation_gas
    execute_on = 'initial timestep_end'
  []
  [sw]
    type = ElementAverageValue
    variable = saturation_water
    execute_on = 'initial timestep_end'
  []
  [pwater]
    type = ElementAverageValue
    variable = pressure_water
    execute_on = 'initial timestep_end'
  []
  [pgas]
    type = ElementAverageValue
    variable = pressure_gas
    execute_on = 'initial timestep_end'
  []
  [temperature]
    type = ElementAverageValue
    variable = temperature
    execute_on = 'initial timestep_end'
  []
  [enthalpy]
    type = ElementAverageValue
    variable = h
    execute_on = 'initial timestep_end'
  []
  [liquid_mass]
    type = PorousFlowFluidMass
    phase = 0
    execute_on = 'initial timestep_end'
  []
  [vapor_mass]
    type = PorousFlowFluidMass
    phase = 1
    execute_on = 'initial timestep_end'
  []
[]

[Outputs]
  file_base = water_vapor_twophase_tab
  csv = true
[]
```

**Comment by GiudGiud** [comment]
Sounds good. I ll check this out next week. Then I will be on travel so I may not be able to help this through. If you mind the delay we will have to bring in another reviewer. 

I don't think we need to use the FP version of the ADReal. I get by with using ADReal everywhere

**Comment by GiudGiud** [comment]
Looks like this flew under my radar post honeymoon. 

@aikubo do you still need this?

**Comment by aikubo** [comment]
Hi @GiudGiud 

Yes I think this would still me useful to me and a few others, perhaps https://github.com/idaholab/moose/discussions/28066 as well.

**Comment by GiudGiud** [comment]
https://github.com/idaholab/moose/discussions/28066 was just a convergence issue.

Ok once my own TFP PR is merged (it will conflict) I ll take over this one to get it past the finishing line. Thanks for getting back in touch

**Comment by GiudGiud** [comment]
ok I rebased and added tests. Machine is borked so I cant run them locally, let's see how civet fares.
@aikubo I did remove the restriction to p_h variables. If you still want that you'll need to make a separate PR

**Comment by GiudGiud** [comment]
@aikubo can I please get some guidance on that test?
The pressures in the CSV file are between 1.9 and 2.3e7 but the IC is at 1e6. 
Should I just raise the pressures? Or do you have an extended tabulation file I can use?

**Comment by aikubo** [comment]
Hi @GiudGiud, thanks for working on this. 

Raising the pressures will not show the same behavior since it will change to a different phase region. 

I have been using this script to generate tabulated ranges based on https://github.com/idaholab/moose/discussions/21038#discussioncomment-2779971


```
import CoolProp.CoolProp as cp
import pandas as pd
import numpy as np

# Range of pressure and temperature
minPressure = 1e4
maxPressure = 1.8e9
minTemperature = 275
maxTemperature = 1300

pressure = np.concatenate( (np.linspace(minPressure, 1e5, 5), np.linspace(1.1e5, 1e8, 100), np.linspace(1.1e8, 1e10, 5)))
temperature = np.concatenate( (np.linspace(minTemperature-100, minTemperature, 5), np.arange(minTemperature+5, maxTemperature, 100), np.linspace(maxTemperature+100, maxTemperature+500, 5)))

data = np.zeros((pressure.size * temperature.size, 6))

for i in np.arange(pressure.size):
    for j in np.arange(temperature.size):
        data[i * temperature.size + j, 0] = pressure[i]
        data[i * temperature.size + j, 1] = temperature[j]

        if pressure[i] < minPressure or temperature[j] < minTemperature:
            data[i * temperature.size + j, 0] = pressure[i]
            data[i * temperature.size + j, 1] = temperature[j]
            data[i * temperature.size + j, 2] = cp.PropsSI('D', 'P', minPressure, 'T', minTemperature, 'Water')
            data[i * temperature.size + j, 3] = cp.PropsSI('V', 'P', minPressure, 'T', minTemperature, 'Water')
            data[i * temperature.size + j, 4] = cp.PropsSI('H', 'P', minPressure, 'T', minTemperature, 'Water')
            data[i * temperature.size + j, 5] = cp.PropsSI('U', 'P', minPressure, 'T', minTemperature, 'Water')
            continue
        elif pressure[i] > maxPressure or temperature[j] > maxTemperature:
            data[i * temperature.size + j, 0] = pressure[i]
            data[i * temperature.size + j, 1] = temperature[j]
            data[i * temperature.size + j, 2] = cp.PropsSI('D', 'P', maxPressure, 'T', maxTemperature, 'Water')
            data[i * temperature.size + j, 3] = cp.PropsSI('V', 'P', maxPressure, 'T', maxTemperature, 'Water')
            data[i * temperature.size + j, 4] = cp.PropsSI('H', 'P', maxPressure, 'T', maxTemperature, 'Water')
            data[i * temperature.size + j, 5] = cp.PropsSI('U', 'P', maxPressure, 'T', maxTemperature, 'Water')
            continue
        elif pressure[i] > minPressure and pressure[i] < maxPressure and temperature[j] > minTemperature and temperature[j] < maxTemperature:
            data[i * temperature.size + j, 2] = cp.PropsSI('D', 'P', pressure[i], 'T', temperature[j], 'Water')
            data[i * temperature.size + j, 3] = cp.PropsSI('V', 'P', pressure[i], 'T', temperature[j], 'Water')
            data[i * temperature.size + j, 4] = cp.PropsSI('H', 'P', pressure[i], 'T', temperature[j], 'Water')
            data[i * temperature.size + j, 5] = cp.PropsSI('U', 'P', pressure[i], 'T', temperature[j], 'Water')

# Write out fluid_properties_extended.csv
df = pd.DataFrame(data, columns = ['pressure', 'temperature', 'density', 'viscosity', 'enthalpy', 'internal_energy'])
df.to_csv('water_extended.csv', index=False)
```

I'll push the extended tabulation file.

**Comment by GiudGiud** [comment]
@joshuahansel for the independent review please

File: modules/porous_flow/test/tests/fluidstate/tests [hunk 12]
```diff
@@ -181,6 +181,15 @@
     design = 'PorousFlowWaterVapor.md'
     issues = '#13108'
   []
+  [water_vapor_tabulated]
+    type = 'CSVDiff'
+    input = 'water_vapor_tab.i'
+    csvdiff = 'water_vapor_twophase_tab.csv'
+    threading = '!pthreads'
```
Comment (joshuahansel) [inline modules/porous_flow/test/tests/fluidstate/tests:188]: Why/when do we skip pthreads? I see a lot of "!pthreads" in the test suite but no reason ever listed. We'd like to note reasons as a comment on the line.

File: modules/porous_flow/test/tests/fluidstate/fluid_properties_extended.csv [hunk 13]
```diff
@@ -0,0 +1,2311 @@
+pressure,temperature,density,viscosity,enthalpy,internal_energy
+10000.0,175.0,999.8920764856763,0.0016821184304554088,7769.115321732408,7759.114242437768
+10000.0,200.0,999.8920764856763,0.0016821184304554088,7769.115321732408,7759.114242437768
+10000.0,225.0,999.8920764856763,0.0016821184304554088,7769.115321732408,7759.114242437768
+10000.0,250.0,999.8920764856763,0.0016821184304554088,7769.115321732408,7759.114242437768
+10000.0,275.0,0.0,0.0,0.0,0.0
```
Comment (joshuahansel) [inline modules/porous_flow/test/tests/fluidstate/fluid_properties_extended.csv:6]: Are these 0 lines expected?

File: modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i [hunk 14]
```diff
@@ -0,0 +1,316 @@
...
+    type = ElementAverageValue
+    variable = pressure_water
+    execute_on = 'initial timestep_end'
+  []
+  [pgas]
+    type = ElementAverageValue
+    variable = pressure_gas
+    execute_on = 'initial timestep_end'
+  []
+  # [temperature]
```
Comment (joshuahansel) [inline modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i:291]: Why is temperature commented out?

File: modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i [hunk 15]
```diff
@@ -0,0 +1,316 @@
...
+    specific_heat_capacity = 1200
+  []
+[]
+
+[Executioner]
+  type = Transient
+  solve_type = NEWTON
+  end_time = 1
+  nl_abs_tol = 1e-12
+[]
```
Comment (joshuahansel) [inline modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i:231]:
```suggestion
[Problem]
  solve = false
[]

[Executioner]
  type = Steady
[]
```

Comment (joshuahansel) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i:231]: And then update your gold file: it should have only one line instead of two now.

**Review by joshuahansel — CHANGES_REQUESTED** [review]
Side note: I never noticed that there was a `vaporPressure` method in `SinglePhaseFluidProperties`. It would have been preferable to use a `TwoPhaseFluidProperties` to meet this need, but maybe this was done because someone didn't have the other (liquid/vapor) properties.

File: modules/porous_flow/test/tests/fluidstate/tests (hunk 12 above)
Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/tests:188]: it's tradition for porous_flow module
I ll address that in a follow up

File: modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i (hunk 14 above)
Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i]: uncommented now

File: modules/porous_flow/test/tests/fluidstate/fluid_properties_extended.csv (hunk 13 above)
Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/fluid_properties_extended.csv:6]: @aikubo 

TFP handles them without complaint :D

File: modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i (hunk 15 above)
Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i]: still has two
I think we'd need to pass some execute_on to the csv to prevent any other execution?

Comment (joshuahansel) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i]: Yeah, I think it'll need `execute_on = INITIAL` in the `Outputs` block.

Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i]: ok i ll add it

Comment (GiudGiud) [reply modules/porous_flow/test/tests/fluidstate/water_vapor_tab.i]: done

**Review by joshuahansel — APPROVED** [review]

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thank you for the contribution @aikubo !
I m happy TFP can support porous flow needs as well. And this made me understand a lot more the fluid property needs of porous flow. I think we want to support a whole (p, h) variable set for this module, which we are far from

File: modules/fluid_properties/src/fluidproperties/Water97FluidProperties.C [hunk 16]
```diff
@@ -446,6 +446,38 @@ Water97FluidProperties::s_from_p_T(
...
+  Moose::derivInsert(p.derivatives(), 0, 1.0);
+
+  ADReal h = enthalpy;
+  Moose::derivInsert(h.derivatives(), 1, 1.0);
+
+  ADReal T = T_from_p_h_ad(p, h);
+  ADReal entropy = s_from_p_T_template(p, T);
+
+  ds_dh = entropy.derivatives()[1];
+  ds_dp = entropy.derivatives()[0];
```
Comment (GiudGiud) [inline modules/fluid_properties/src/fluidproperties/Water97FluidProperties.C:477]: @aikubo notice I flipped those. if you were getting convergence issues in your model this might have been it
