### PR TITLE
Fixing parser bugs

### LINKED ISSUE #10691: Command line argument syntax check is not complete
## Rationale
I made a mistake on command line, while I intended to have 
```
Executioner/end_time=0.10 Executioner/num_param_updates=4
```
but accidentally deleted the space between two arguments like
```
Executioner/end_time=0.10Executioner/num_param_updates=4
```
However, the code runs fine.

## Description
When the code parses the command line arguments, it should check the validity of the argument. I think right now it takes `0.10Executioner/num_param_updates=4` as the value of the first argument and uses `0.10`. The second argument is thus completely ignored.

## Impact
Better user experience.

### PR DESCRIPTION
**Pull request by permcody**
1) Merging two trees doesn't throw an error if field kinds don't match
2) Fixing unprotected raw calls to std::stod and std::stoi to verify all characters are used.

closes #10691

### CODE REVIEW

**Comment by rwcarlsen** [comment]
This fails tests.

File: framework/contrib/hit/parse.cc [hunk 1]
```diff
@@ -94,6 +94,25 @@ nodeTypeName(NodeType t)
   // clang-format on
 }
 
+std::string
+stringify(const Field::Kind & k)
```
Comment (rwcarlsen) [inline framework/contrib/hit/parse.cc]: This doesn't appear to be used anywhere anymore.

**Review by rwcarlsen — CHANGES_REQUESTED** [review]
Could we have a quick unit test that checks the kind is overridden to prevent any sort of regressions in merge behavior?

**Review by rwcarlsen — APPROVED** [review]
