### PR TITLE
Get correct coord system in GapHeatTransfer

### LINKED ISSUE #15967: GapConductance and GapHeatTransfer does not get correct coordinate system
## Bug Description

GapConductance tries to get `_coord_sys` from Assembly, but `coord_sys` will not be initialized by Assembly during initialSetup at recover mode. So GapConductance will get a wrong `cood_sys` and throw a MOOSE error for some cases. 

Another similar issue for GapHeatTransfer when running in parallel when using a large number of MPI processes. 

## Steps to Reproduce

In moose/modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_rspherical.i, set `gap_geometry_type = sphere` in `GapHeatTransfer` and run it in recover. A Moose Error will occur because the  `coord_sys` type does not match `gap_geometry_type`. 

In moose/modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_rspherical.i,  run it using 40 MPI processes. A Moose Error will occur because the  `coord_sys` type does not match `gap_geometry_type`. 

## Impact

Some thermal contact  tests will fail in recover mode.

### PR DESCRIPTION
**Pull request by jiangwen84**
closes #15967

### CODE REVIEW

File: modules/heat_conduction/src/bcs/GapHeatTransfer.C [hunk 1]
```diff
@@ -139,13 +139,21 @@ GapHeatTransfer::GapHeatTransfer(const InputParameters & parameters)
...
+      boundaryRestricted() && !boundaryIDs().empty() ? boundaryIDs() : meshBoundaryIDs();
+  if (check_boundaries.empty())
+    mooseError("No boundaries found");
+
+  // make sure all boundaries are using the same coordinate system
+  Moose::CoordinateSystemType coord_system = _fe_problem.getCoordSystem(*check_boundaries.begin());
+  for (auto boundary : check_boundaries)
+    if (_fe_problem.getCoordSystem(boundary) != coord_system)
+      mooseError(
+          "The GapConductance model requires all boundaires to have the same coordinate system.");
```
Comment (gambka) [inline modules/heat_conduction/src/bcs/GapHeatTransfer.C:153]: boundaires -> boundaries

Comment (jiangwen84) [reply modules/heat_conduction/src/bcs/GapHeatTransfer.C]: thanks.

**Review by jasondhales — APPROVED** [review]

**Comment by loganharbour** [comment]
Ping @dschwen
