### PR TITLE
Construct custom material container for mortar

### LINKED ISSUE #20070: Dependency-based reiniting of material properties for mortar constraints
## Reason
There is a limitation in the way we are reiniting the material properties within the mortar functor. We skip all stateful material properties and reinit all non-stateful material properties. This strategy doesn't consider the case where a non-stateful material relies on a stateful material, which then yields a bad access/segmentation fault. This prevents some simulations from running and also highlights that we are reiniting all materials in the functor regardless of whether mortar constraints are going to consume them. 

## Design
@lindsayad's input: Keep track of mortar's material property dependencies for each domain.  Then loop over materials to find out if a particular material provides any of the properties required by mortar constraints. Then, add logic to only reinit the required materials from the mortar functor.

## Impact
Expand the use of mortar to more cases. No impact on accuracy.

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #20070

### CODE REVIEW

File: framework/include/loops/ComputeMortarFunctor.h [hunk 1]
```diff
@@ -66,4 +70,8 @@ class ComputeMortarFunctor
 
   /// A reference to the assembly object
   Assembly & _assembly;
+
+  std::map<SubdomainID, std::deque<MaterialBase *>> _secondary_ip_sub_to_mats;
+  std::map<SubdomainID, std::deque<MaterialBase *>> _primary_ip_sub_to_mats;
+  std::deque<MaterialBase *> _secondary_boundary_mats;
```
Comment (recuero) [inline framework/include/loops/ComputeMortarFunctor.h:76]: If I understand this correctly, for everything object relying on mortar (i.e. constraints, mortar aux kernel), we require that there is an object that holds a map with the material properties that we are going to need, computed via `buildRequiredMaterials`.

File: framework/include/utils/MortarUtils.h [hunk 2]
```diff
@@ -274,14 +283,62 @@ loopOverMortarSegments(const Iterators & secondary_elems_to_mortar_segments,
...
       fe_problem.reinitMaterialsBoundary(
-          secondary_boundary_id, /*tid=*/0, /*swap_stateful=*/false, /*execute_stateful=*/false);
+          secondary_boundary_id, /*tid=*/0, /*swap_stateful=*/false, &secondary_boundary_mats);
 
       act();
 
     } // End loop over msm segments on secondary face elem
   }   // End loop over (active) secondary elems
 }
+
```
Comment (recuero) [inline framework/include/utils/MortarUtils.h:295]: If you touch the code again, maybe adding some comments for this method would be helpful in the future.

File: framework/src/utils/MooseUtils.C [hunk 3]
```diff
@@ -1194,6 +1197,72 @@ prettyCppType(const std::string & cpp_type)
...
+  {
+    const auto & mp_deps = consumer->getMatPropDependencies();
+    needed_mat_props.insert(mp_deps.begin(), mp_deps.end());
+  }
+
+  // A predicate of calling this function is that these materials come in already sorted by
+  // dependency with the front of the container having no other material dependencies and following
+  // materials potentially depending on the ones in front of them. So we can start at the back and
+  // iterate forward checking whether the current material supplies anything that is needed, and if
+  // not we discard it
```
Comment (recuero) [inline framework/src/utils/MooseUtils.C:1219]: Is this design feature taking of care of mortar properties provided by a material that uses data from another material? Would we error out if the second material happens to be stateful?

File: framework/include/constraints/AutomaticMortarGeneration.h [hunk 4]
```diff
@@ -261,12 +262,16 @@ class AutomaticMortarGeneration : public ConsoleStreamInterface
...
    */
-  const std::vector<std::pair<boundary_id_type, boundary_id_type>> &
-  primarySecondaryBoundaryIDPairs() const
+  const std::vector<std::pair<BoundaryID, BoundaryID>> & primarySecondaryBoundaryIDPairs() const
   {
     return _primary_secondary_boundary_id_pairs;
   }
 
+  // const std::pair<SubdomainID, SubdomainID> & primarySecondarySubdomainIDPair()
+  // const;
```
Comment (recuero) [inline framework/include/constraints/AutomaticMortarGeneration.h:271]: Remove?

File: framework/src/utils/MooseUtils.C (hunk 3 above)
Comment (recuero) [reply framework/src/utils/MooseUtils.C:1219]: Never mind the second question. Clearly spelled out below: https://github.com/idaholab/moose/blob/4a5d53f1ed5db3667a3358c55ba933359fada36d/framework/src/utils/MooseUtils.C#L1241.

Comment (recuero) [reply framework/src/utils/MooseUtils.C:1219]: And the magic for the first question appears to take place here:
https://github.com/idaholab/moose/blob/4a5d53f1ed5db3667a3358c55ba933359fada36d/framework/src/utils/MooseUtils.C#L1246-L1248

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 5]
```diff
@@ -1860,8 +1879,8 @@ AutomaticMortarGeneration::projectPrimaryNodes()
 
 void
 AutomaticMortarGeneration::projectPrimaryNodesSinglePair(
-    subdomain_id_type lower_dimensional_primary_subdomain_id,
-    subdomain_id_type lower_dimensional_secondary_subdomain_id)
+    SubdomainID lower_dimensional_primary_subdomain_id,
```
Comment (recuero) [inline framework/src/constraints/AutomaticMortarGeneration.C:1882]: what's the gist between `subdomain_id_type` and `SubdomainID`?

**Review by recuero — COMMENTED** [review]
This is great.

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 5 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C:1882]: they are the exact same, but the former is "libMesh" style while the latter is "MOOSE" style

File: framework/include/constraints/AutomaticMortarGeneration.h (hunk 4 above)
Comment (lindsayad) [reply framework/include/constraints/AutomaticMortarGeneration.h:271]: yessir

**Comment by lindsayad** [comment]
@recuero this is in a more polished state, e.g. ready for review

File: framework/src/interfaces/MortarExecutorInterface.C [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+{
+  _mortar_data.notifyWhenMortarSetup(this);
+}
+
+MortarExecutorInterface::MortarExecutorInterface(MortarExecutorInterface && other)
+  : _mortar_data(other._mortar_data)
+{
+  _mortar_data.dontNotifyWhenMortarSetup(&other);
+  _mortar_data.notifyWhenMortarSetup(this);
+}
```
Comment (recuero) [inline framework/src/interfaces/MortarExecutorInterface.C:25]: This part I don't fully grasp. How is it `MortarExecutorInterface` deciding what to notify and what to denotify? If I understand well, notification implies that a `MortarExecutorInterface` needs to run `mortarSetup()` to find out dependencies.

File: framework/include/auxkernels/MortarNodalAuxKernel.h [hunk 7]
```diff
@@ -10,14 +10,16 @@
...
 
 /**
  * Base class for creating new nodally-based mortar auxiliary kernels
- *
  */
 template <typename ComputeValueType>
-class MortarNodalAuxKernelTempl : public AuxKernelTempl<ComputeValueType>, protected MortarInterface
+class MortarNodalAuxKernelTempl : public AuxKernelTempl<ComputeValueType>,
+                                  public MortarExecutorInterface,
+                                  protected MortarConsumerInterface
```
Comment (recuero) [inline framework/include/auxkernels/MortarNodalAuxKernel.h:22]: The aux kernel gets to be consumer and executor. But the mortar constraint is only consumer because those duties are split with other classes?

**Review by recuero — COMMENTED** [review]
Neat design!

File: framework/src/interfaces/MortarExecutorInterface.C (hunk 6 above)
Comment (lindsayad) [reply framework/src/interfaces/MortarExecutorInterface.C:25]: If a move constructor gets called, that means the constructor argument (`other` in is case) is going to get destroyed after move construction of the new object. So if you don't remove the `other` `MortarExecutorInterface` from the container of objects that `MortarData` will iterate over and call `mortarSetup` on after the mortar mesh has been created, then you will get a segmentation fault because you will calling `mortarSetup` through a pointer to an object that has been destroyed.

File: framework/include/auxkernels/MortarNodalAuxKernel.h (hunk 7 above)
Comment (lindsayad) [reply framework/include/auxkernels/MortarNodalAuxKernel.h:22]: Correct. `ComputeMortarFunctor` is the object that executes the loop through the mortar mesh

**Review by recuero — APPROVED** [review]
We will be exercising these enhanced capabilities in the apps.
