### PR TITLE
Change access qualifier, fix header

### LINKED ISSUE #6869: Change members from private to protected in CoupledTimeDerivative
### Description of the enhancement or error report
Some members are needlessly private. This prevents us from inheriting from this class.

### Rationale for the enhancement or information for reproducing the error
Need to derive a new coupled time kernel with a derivative function prefactor,

### Identified impact
Avoid code duplication

### PR DESCRIPTION
**Pull request by dschwen**
Closes #6869

### CODE REVIEW

File: framework/include/kernels/CoupledTimeDerivative.h [hunk 1]
```diff
@@ -36,7 +36,6 @@ class CoupledTimeDerivative : public Kernel
   virtual Real computeQpJacobian();
   virtual Real computeQpOffDiagJacobian(unsigned int jvar);
 
-private:
   const VariableValue & _v_dot;
   const VariableValue & _dv_dot;
   unsigned int _v_var;
```
Comment (permcody) [inline framework/include/kernels/CoupledTimeDerivative.h]: Maybe this should be const if you are removing protection? Probably should have been before.
