### PR TITLE
Make aux kernel work properly for high-order boundary restriction

### LINKED ISSUE #16895: High-order boundary restricted AuxKernel has a bug
## Bug Description
When an aux kernel is boundary restricted, the assembled mass matrix on element with quadrature points on one of its side with high-order shape functions is rank deficient, thus we cannot use Cholesky decomposition for the local solve.

## Steps to Reproduce
Run this test `test/tests/auxkernels/element_aux_boundary/element_aux_boundary.i` with `AuxVariables/real_property/order=SECOND`. Tag @aprilnovak @fdkong . I will fix this along with the other issue related with boundary related aux kernels.

## Impact
Fix high order boundary restricted aux kernels that is not widely used.

### PR DESCRIPTION
**Pull request by YaqiWang**
And issue an error when multiple sides on boundary touching the same elements.

Close #16895.  And refer to #5061.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Tag @bwspenc

File: framework/src/auxkernels/AuxKernel.C [hunk 1]
```diff
@@ -138,6 +140,30 @@ AuxKernelTempl<ComputeValueType>::AuxKernelTempl(const InputParameters & paramet
...
+    auto boundaries = _mesh.getMesh().get_boundary_info().build_side_list();
+    std::set<dof_id_type> elements;
+    for (const auto & t : boundaries)
+    {
+      if (hasBoundary(std::get<2>(t)))
+      {
+        auto eid = std::get<0>(t);
+        std::pair<std::set<dof_id_type>::iterator, bool> stat = elements.insert(eid);
+        if (!stat.second)
+          mooseError("Boundary restricted auxiliary kernel ",
```
Comment (loganharbour) [inline framework/src/auxkernels/AuxKernel.C:158]:
```suggestion
          mooseError("Boundary restricted auxiliary kernel '",
```

File: framework/src/auxkernels/AuxKernel.C [hunk 2]
```diff
@@ -138,6 +140,30 @@ AuxKernelTempl<ComputeValueType>::AuxKernelTempl(const InputParameters & paramet
...
+                     name(),
+                     " has element (ID=",
```
Comment (loganharbour) [inline framework/src/auxkernels/AuxKernel.C:160]:
```suggestion
                     "' has element (id = ",
```

File: framework/src/auxkernels/AuxKernel.C [hunk 3]
```diff
@@ -138,6 +140,30 @@ AuxKernelTempl<ComputeValueType>::AuxKernelTempl(const InputParameters & paramet
...
+                     eid,
+                     ") connected with more than one boundary sides.\nYou can consider using "
+                     "multiple auxilary variables/kernels each on a part of the boundaries.");
```
Comment (loganharbour) [inline framework/src/auxkernels/AuxKernel.C:163]:
```suggestion
                     ") that has multiple boundary sides.\nSee the AuxKernel documentation on boundary restricted aux kernels for understanding this error.");
```

File: test/tests/auxkernels/element_aux_boundary/tests [hunk 4]
```diff
@@ -1,10 +1,27 @@
...
     exodiff = 'element_aux_boundary_out.e'
     requirement = "The variable data created by a MaterialRealAux object shall support being limited to boundaries."
+    issues = '#3114'
+    design = 'source/auxkernels/MaterialRealAux.md'
+  [../]
+  [./ho_boundary_restricted_test]
+    type = 'Exodiff'
+    input = 'high_order_boundary_aux.i'
+    exodiff = 'high_order_boundary_aux_out.e'
+    requirement = "MOOSE shall support boundary restricted auxilary elemental variables with high order shape functions."
```
Comment (loganharbour) [inline test/tests/auxkernels/element_aux_boundary/tests:14]:
```suggestion
    requirement = "MOOSE shall support boundary restricted auxiliary elemental variables with high order shape functions."
```

File: test/tests/auxkernels/element_aux_boundary/tests [hunk 5]
```diff
@@ -1,10 +1,27 @@
...
+    issues = '#16895'
+    design = 'syntax/AuxKernels/index.md'
+  [../]
+  [./boundary_restricted_error_test]
+    type = RunException
+    input = 'high_order_boundary_aux.i'
+    cli_args = "AuxKernels/real_property/boundary='0 1' --color off"
+    expect_err = "Boundary restricted auxiliary kernel real_property has element \(ID=[0-9]+\) connected with more than one boundary sides."
+    requirement = "MOOSE shall error if a boundary restricted elemental auxilary kernel evaluates on multple sides touching the same elements."
```
Comment (loganharbour) [inline test/tests/auxkernels/element_aux_boundary/tests:23]:
```suggestion
    requirement = "MOOSE shall error if a boundary restricted elemental auxiliary kernel is evaluated on an element with multiple boundary sides."
```

File: framework/src/auxkernels/AuxKernel.C (hunk 3 above)
Comment (loganharbour) [reply framework/src/auxkernels/AuxKernel.C:163]: We're looking into being able to link to documentation from within source... would be nice

**Review by loganharbour — CHANGES_REQUESTED** [review]

File: framework/doc/content/syntax/AuxKernels/index.md [hunk 6]
```diff
@@ -47,6 +47,16 @@ The same AuxKernel object can be designed work both as elemental or nodal, for e
 `computeValue` method for the [FunctionAux.md] object properly handles using the correct spatial
 location based on if the object is nodal or elemental with the `isNodal` method.
 
+## Block vs Boundary Restricted AuxKernel Objects
+
+While auxiliary variables are always defined on mesh subdomains, MOOSE allows auxiliary kernels to be either block (mesh subdomain) or boundary restricted.
+When an auxiliary kernel is boundary restricted, it evaluates an auxiliary variable only on the designated boundaries.
+Because of this, the auxiliary variable will only have meaningful values on the boundaries even though it is defined on mesh subdomains.
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/doc/content/syntax/AuxKernels/index.md:54]: Not for this change because aux variable is not boundary restricted.

File: framework/src/auxkernels/AuxKernel.C [hunk 7]
```diff
@@ -138,6 +140,30 @@ AuxKernelTempl<ComputeValueType>::AuxKernelTempl(const InputParameters & paramet
...
+    // all the sides on the boundaries
+    auto boundaries = _mesh.getMesh().get_boundary_info().build_side_list();
+    std::set<dof_id_type> elements;
+    for (const auto & t : boundaries)
+    {
+      if (hasBoundary(std::get<2>(t)))
+      {
+        auto eid = std::get<0>(t);
+        std::pair<std::set<dof_id_type>::iterator, bool> stat = elements.insert(eid);
+        if (!stat.second)
```
[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/auxkernels/AuxKernel.C:157]: There multiple versions of `std::set::insert` with different returned values, so I am not sure if `auto` here can work.

[the remark this answers is not in the document]
Comment (YaqiWang) [reply framework/src/auxkernels/AuxKernel.C:157]: Surprisingly `auto` works here. I will make the change.

**Comment by YaqiWang** [comment]
Comments are addressed. We will need to wait for @bwspenc 's answer on how to patch BISON.

**Comment by YaqiWang** [comment]
@loganharbour I want this to get in first. Looks like fixing Bison will take some time so I replaced that error with a warning. Because of this I did not close that old issue. We can revert the second commit after Bison is fixed in the future.

**Comment by loganharbour** [comment]
A warning won't work. It'll still fail tests.

**Comment by YaqiWang** [comment]
Nope, it passed.

**Comment by YaqiWang** [comment]
@loganharbour can this be merged?

**Comment by YaqiWang** [comment]
Ok, remove the second commit since we will see app patched soon.

**Review by loganharbour — APPROVED** [review]
Once the bison fix makes its way into master, we'll get this in.

**Comment by YaqiWang** [comment]
This closed #5061 as well.
