### PR TITLE
Output at FORWARD for optimization

### LINKED ISSUE #27193: Allow output on forward for optimization problems
### Motivation

Add output option right before `FORWARD` sub apps are run. This is allow for debugging of parameters when a solve fails.

### Design

Add ` _problem.outputStep(OptimizationAppTypes::EXEC_FORWARD)`

### Impact

Help users debug optimization problems.

### PR DESCRIPTION
**Pull request by maxnezdyur**
closes #27193

### CODE REVIEW

**Comment by maxnezdyur** [comment]
@lynnmunday Output at forward. The json file shows the parameters at every iteration and the final `Forward` is the same as the `TIMESTEP_END`.

**Comment by maxnezdyur** [comment]
@ke7kto 
This should help you in the future.

**Review by loganharbour — APPROVED** [review]

File: modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/tests [hunk 1]
```diff
@@ -3,12 +3,12 @@
...
     input = main.i
-    jsondiff = main_json.json
+    jsondiff = "main_json.json main_json_forward.json"
     recover = false
     abs_zero = 1.0e-6
     max_threads = 1
 
-    issues = '#24930'
-    requirement = "The system shall be able to minimize an objective function that is reporter transfer using TAO."
+    issues = '#24930 27193'
```
Comment (loganharbour) [inline modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/tests:11]:
```suggestion
    issues = '#24930 #27193'
```

**Review by loganharbour — CHANGES_REQUESTED** [review]

**Comment by ke7kto** [comment]
This looks really good! Am I right in understanding that outputting on FORWARD means that we won't have access to the solution value? Would we still be able to get most of the objective function values if we did "execute_on = FORWARD TIMESTEP_END" ?

**Comment by maxnezdyur** [comment]
> This looks really good! Am I right in understanding that outputting on FORWARD means that we won't have access to the solution value? Would we still be able to get most of the objective function values if we did "execute_on = FORWARD TIMESTEP_END" ?

Yes that would get you the parameters and values at every forward iteration and the final result.

File: modules/optimization/src/executioners/OptimizeSolve.C [hunk 2]
```diff
@@ -287,6 +295,8 @@ OptimizeSolve::setTaoSolutionStatus(double f, int its, double gnorm, double cnor
       steady->setIterationNumberOutput((unsigned int)its);
   }
 
+  if (_time_step_as_iteration)
+    _problem.timeStep() = its;
```
Comment (maxnezdyur) [inline modules/optimization/src/executioners/OptimizeSolve.C:299]: This would allow for outputting at each iteration. I couldn't find a better way to set this.

Comment (loganharbour) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: Hmm... I don't think we want to do this. This set would be frustrating to track down in the future

Comment (maxnezdyur) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: Any idea how we can do this. This would be a really useful debugging option because it would keep track of the current iteration, when the sub app doesn't solve. For exodus files when executing on `LINEAR` it increments the time by a very small number. But I can't find where it does that.

Comment (GiudGiud) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: there were talks of having a naming convention for outputs like
```
...._t<timestep number>_nl<nl ite number_l<linear it number>
```
we could do the same here for forward
@lindsayad was involved iirc

Comment (lynnmunday) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: What Max has also allows us to output exodus files on the main app and they will be incremented by the timestep so we can then view them in paraview.  I think we need the time to change because exodus does have a "time_step" but it doesn't have an "iteration" for saving different model states.   This PR is provides a really important debugging capability for optimization problems.

Comment (GiudGiud) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: the time is already changing, with the tiny increments (0.0...01 depending on the nesting)

Comment (maxnezdyur) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: So update nonlinear iterations instead of the timestep and good to go?

Comment (lindsayad) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: https://github.com/idaholab/moose/issues/25416 is the issue I believe. I think I'm the new Derek over-promising what I can do ... I said I would work on this many months ago but have not done so and likely will not be able to this fiscal year so if someone else wants to take that over or circumvent it if there's another good solution then I'm not opposed

Comment (GiudGiud) [reply modules/optimization/src/executioners/OptimizeSolve.C:299]: I'll sign off on abusing nonlinear iteration counts. Someone debugging nonlinear iterations within an optimization solve will just have to get wrekt or change the code

Comment (maxnezdyur) [reply modules/optimization/src/executioners/OptimizeSolve.C]: So a few things. 
1) These things go into the main app for an optimization problem which never solves the physics. It would be really hard to solve the physics and opt problem together with the way it is setup.   
2) So the only Optimize executioner is a steady executioner so if I can change the _t_step which is what I have currently all the outputting works really nice. 

Looking at Output.C, the way we get the time is based off the _t_step. 
``` 
Real
Output::time()
{
  if (_transient)
    return _time;
  else
    return _t_step;
}
``` 
If we did it any other way we would have to add a lot more hacky code.
For example in `JsonOutput.C` to output the nonlinear iteration as the tilmestep I would need to add a `contains(OptimizationAppTypes::EXEC_FORWARD)` if statement to make it work for Json fils, then something for csv files, the exodus files, etc.
```
   if (_execute_enum.contains(EXEC_LINEAR) && !_on_nonlinear_residual)
      current_node["linear_iteration"] = _linear_iter;
    if (_execute_enum.contains(EXEC_NONLINEAR))
      current_node["nonlinear_iteration"] = _nonlinear_iter;
```

Comment (loganharbour) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Is anything done with this executioner using transient at the moment?

Comment (maxnezdyur) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Even for transient optimizations we use this executioner for the main app. The "transient" part lives on the sub apps only.

Comment (loganharbour) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Part of me wants to say just kick this down the road to get it in and not let it work with transient?

Comment (GiudGiud) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Alright seems fair to me. I dont think we have the resource to look at this

Comment (loganharbour) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Yeah, I'm on board with it as long as @maxnezdyur isn't interrupted by it and doesn't see it as a near-future need.

Comment (maxnezdyur) [reply modules/optimization/src/executioners/OptimizeSolve.C]: Added an error check so it can't work with transient executioners. I agree getting this in sooner will provide a lot of value.

**Review by loganharbour — CHANGES_REQUESTED** [review]
We actually have a new way to deal with these sorts of errors. Rebase on next, because this feature is currently stuck on next...

Please create an issue that describes the reason why transient isn't supported. Reference this pull request and then reference https://github.com/idaholab/moose/issues/25416 as a likely solution.

Then, make your error:

```
mooseDocumentedError("moose", <issue number>, "Outputting for transient executioners has not been implemented.");
```

I know that it's a bit of a pain, but is a lot better for tracking and if we never implement it but https://github.com/idaholab/moose/issues/25416 becomes resolved, it will be much easier to track how to enable it.

**Comment by maxnezdyur** [comment]
> We actually have a new way to deal with these sorts of errors. Rebase on next, because this feature is currently stuck on next...
> 
> Please create an issue that describes the reason why transient isn't supported. Reference this pull request and then reference #25416 as a likely solution.
> 
> Then, make your error:
> 
> ```
> mooseDocumentedError("moose", <issue number>, "Outputting for transient executioners has not been implemented.");
> ```
> 
> I know that it's a bit of a pain, but is a lot better for tracking and if we never implement it but #25416 becomes resolved, it will be much easier to track how to enable it.

Will do. I like the idea, helps me in not having to always go through the issues trying to find if a problem has already been reported.

**Comment by loganharbour** [comment]
> helps me in not having to always go through the issues trying to find if a problem has already been reported.

That's the hope 😬

**Comment by lynnmunday** [comment]
@loganharbour will you take another look at this PR and merge?

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
Unfortunately looks like this broke next: https://civet.inl.gov/job/2166156/
