### PR TITLE
parser: more robust handling of number syntax errors

### LINKED ISSUE #10310: Parser should probably error when scientific notation is entered incorrectly
## Rationale

Scientific notation can sometimes be entered as a typo and the Parser will not complain. 

## Description

For example, if you accidentally add "1.0ee-5" or "1.0-5"  in an input file instead of 1.0e-5, then the Parser won't complain and you have to find the problem yourself. 

## Impact

Easier to use. LEss error prone input files.

### PR DESCRIPTION
**Pull request by rwcarlsen**
stoi and stod functions are quite permissive and can ignore part of the
input string leaving it not entirely parsed.  Sometimes this could
result in invalid number strings being parsed as valid.  For example
"3ee10" is parsed as the value "3".  This change fixes that and requires
sto[i/d] to parse the entire string.  Any corresponding errors are not
added to the _errmsg collection variable and printed together with
other errors all at once instead of one at a time.

fixes #10310

### CODE REVIEW

File: framework/src/parser/Parser.C [hunk 1]
```diff
@@ -1252,34 +1256,40 @@ Parser::setScalarParameter(const std::string & full_name,
...
     }
     else if (t == typeid(double))
     {
       try
       {
-        auto v = std::stod(_root->param<std::string>(full_name));
+        auto v = std::stod(strval, &pos);
         param->set() = *reinterpret_cast<T *>(&v);
+        if (pos != strval.size())
+          throw "foo"; // catch below and print error
```
Comment (permcody) [inline framework/src/parser/Parser.C]: Did you really intend to slip "foo" into the production code? Also, I'd really prefer that you catch specific exceptions. I really don't like seeing global exception catchers as the first line of defense when you actually know the specific types that are thrown in the try block. This is worth cleaning up. I can see that some of this has already slipped through, will you revisit and clean it up?

**Review by permcody — CHANGES_REQUESTED** [review]
Looks good with the exception of the one comment I made.

File: framework/src/parser/Parser.C (hunk 1 above)
Comment (rwcarlsen) [reply framework/src/parser/Parser.C]: The ``...`` was because there were some exceptions that weren't being caught properly despite being std::exception subclasses.  I can change this from ``foo`` but it doesn't matter what it is because it is caught (and not rethrown) on the next line in order to avoid duplicating the error message construction/emission.

Comment (permcody) [reply framework/src/parser/Parser.C]: I wonder if this problem is isolated to your machine. If you catch the right type and push it up for CIVET does it work? We really need to figure out what is going on with your system. There's no better time to go to High Sierra! 😉

Comment (rwcarlsen) [reply framework/src/parser/Parser.C]: It is harder than that to deal with - all the errors that triggered that issue were removed from input files.  I can't remember what syntax triggered the missed catch (nor what exception was slipping through).  I agree it's not the best, but it seems a bit tangential to this PR (dealing with the ``...``).  Would you prefer I change the throw to something like ``std::runtime_error("dummy")``?

Comment (permcody) [reply framework/src/parser/Parser.C]: Yes, I'd prefer something standard looking, but why not go even further and illustrate your intent rather than use dummy? What does it mean to have a mismatch like this? Use that definition as your string?

We can deal with `...` in another PR.

Comment (rwcarlsen) [reply framework/src/parser/Parser.C]: It really does not need a different message than the one given below.  They both mean invalid number syntax.  The atoi conversion sometimes throws an exception if the syntax is super invalid or just parses only part of the string into an int if the syntax stops being an int after some point.  i.e. ``asdf`` triggers atoi to throw and ``1.3`` would trigger the manual throw.  Both are invalid integer syntax and the current message says that in addition to printing the actual value that was invalid for both cases.  I could also alternatively use ``goto`` :-)

**Review by permcody — APPROVED** [review]

**Comment by brianmoose** [comment]
Looks like this broke the heavy tests: https://www.moosebuild.org/job/138041/
And possibly the examples: https://www.moosebuild.org/job/138012/

**Comment by brianmoose** [comment]
Also, looks like it broke bison heavy tests: https://moosebuild.inl.gov/job/93671/

**Comment by rwcarlsen** [comment]
I'll get PRs in.
