### PR TITLE
Avoid allocating large dense matrix in EBSDReader

### LINKED ISSUE #15418: Quaternion Algorithm in EBSDReader Does Not Scale
## Bug Description
A quaternion based method to average grain orientations in `EBSDReader` was added to MOOSE in  PR #13893 based on issue #13869.  The algorithm runs fine for small test problems but does not scale well as the problem size increases.  As the quaternion matrix size grows, the memory usage also increases until all the system memory is used.  On my mac, the program continues to run until the virtual memory runs out (~450GB) at which point the simulation exits with an "out of memory" error.  A stack trace for a 2D simulation with mesh size of 1376x1376 follows:  [stack_trace.txt](https://github.com/idaholab/moose/files/4747967/stack_trace.txt)

The memory issue seems to originate from [line 260](https://github.com/idaholab/moose/blob/060931b612a0532c3acc9449e4621a18cee5239a/modules/phase_field/src/userobjects/EBSDReader.C#L260).  By adding print statements to `EBSDReader`, it is clear the simulation crashed when averaging a large feature in the dataset. console_1

Here is the `memory_logger` plot:
figure_1

@rayaprolu143 & @dschwen, can the algorithm be made more robust or optional?  

For my use case, the angles output from DREAM.3D were already averaged using quaternions so it does not make sense to average them again...especially if it causes large memory spikes or extra CPU time to perform.  

Note: DREAM.3D performs the same quaternion averaging with very little memory usage.  Perhaps we should look at their method? 

## Steps to Reproduce
The mesh size of the current tests are too small to crash.  Need to find a larger problem to test against or I can upload my dataset if needed.

## Impact
Currently, not able to run moderate to large EBSD problems.

### PR DESCRIPTION
**Pull request by dschwen**
This should address the scalability issues reported by @frombs 
The algorithm now constructs `Q*w*Q^T` directly without constructing the `Q` and `w` matrices.

Closes #15418

### CODE REVIEW

**Comment by dschwen** [comment]
Again a difference in formatting of the clang-format version 12 we get auto-installed though conda and the version 10 installed on the Civet boxes. 😠

File: modules/phase_field/src/userobjects/EBSDReader.C [hunk 1]
```diff
@@ -244,123 +246,85 @@ EBSDReader::readFile()
...
     EulerAngles & b = _avg_angles[i];
 
     if (a._n == 0)
       continue;
 
-    Real w_index, x_index, y_index, z_index;
-    Real w, x, y, z;
-    std::vector<std::tuple<double, Eigen::VectorXd>> eigen_vectors_and_values;
+    // creating a map to store the quaternion count for each bin index
+    std::map<std::tuple<int, int, int, int>, unsigned int> feature_weights;
```
Comment (recuero) [inline modules/phase_field/src/userobjects/EBSDReader.C:259]: Cannot follow _exactly_ what this map is holding

File: modules/phase_field/src/userobjects/EBSDReader.C [hunk 2]
```diff
@@ -244,123 +246,85 @@ EBSDReader::readFile()
...
 
-    // creating an empty map
-    feature_weights.push_back(
-        std::map<std::tuple<unsigned int, unsigned int, unsigned int, unsigned int>,
-                 unsigned int>());
-
-    // looping through quaternions of each grain
-    for (unsigned int k = 0; k < quat[i].size(); k++)
+    // looping through all quaternions of the current grain
```
Comment (recuero) [inline modules/phase_field/src/userobjects/EBSDReader.C:261]: ~~How does a single grain have more than one quaternion vector associated? (for my own edification)~~

Comment (recuero) [reply modules/phase_field/src/userobjects/EBSDReader.C:261]: If this is just looping over all vector components of the quaternion: Does it make sense to hard code a "4" somehow instead of interrogating its `size`?

File: modules/phase_field/src/userobjects/EBSDReader.C (hunk 1 above)
Comment (recuero) [reply modules/phase_field/src/userobjects/EBSDReader.C:259]: Maybe an expanded comment would help.

File: modules/phase_field/src/userobjects/EBSDReader.C [hunk 3]
```diff
@@ -244,123 +246,85 @@ EBSDReader::readFile()
...
-     * maximum eigen value of Q*W*Q' is the weighted average quaternion
-     **/
+     * A weight matrix (W) is created. The eigenvector corresponding to the
+     * maximum eigenvalue of Q*W*Q' is the weighted average quaternion
+     */
 
-    // creating a quaternion matrix
-    Eigen::MatrixXd quat_mat(4, quat[i].size());
-    // creating the weight matrix
-    Eigen::MatrixXd weight = Eigen::MatrixXd::Identity(quat[i].size(), quat[i].size());
```
Comment (recuero) [inline modules/phase_field/src/userobjects/EBSDReader.C:306]: I can't see how the previous method was creating a 4xN matrix per your comment:

https://github.com/idaholab/moose/issues/15418#issuecomment-1014750495

**Review by recuero — CHANGES_REQUESTED** [review]

File: modules/phase_field/src/userobjects/EBSDReader.C (hunk 2 above)
Comment (dschwen) [reply modules/phase_field/src/userobjects/EBSDReader.C:261]: Not vector components, but all quaternions on sample point in the EBSD file which belong to a specific grain.

File: modules/phase_field/src/userobjects/EBSDReader.C (hunk 3 above)
Comment (dschwen) [reply modules/phase_field/src/userobjects/EBSDReader.C:306]: in line 304 `quat[i].size()` would be the number of datapoints for a given grain in the EBSD file. Those could be thousands.

**Comment by dschwen** [comment]
```
[2.214s]     DIFF test:truss_heat_conduction.w_and_wo_embedded_case/block_with_line FAILED (EXODIFF)
test:truss_heat_conduction.w_and_wo_embedded_case/block_with_line:   Num Processors:          2
test:truss_heat_conduction.w_and_wo_embedded_case/block_with_line:   Num Threads:             2
```
and

```
[0.922s]     DIFF test:finite_volume/wcns/boundary_conditions.dirichlet/using_velocity FAILED (EXODIFF)
test:finite_volume/wcns/boundary_conditions.dirichlet/using_velocity:   Num Processors:          1
test:finite_volume/wcns/boundary_conditions.dirichlet/using_velocity:   Num Threads:             2
```

seem unrelated. FYI @lindsayad , @jain651

**Comment by lindsayad** [comment]
I saw that `using_velocity` test Exodiff the other day, also with two threads. It came back helgrind clean, at least with my https://github.com/libMesh/libmesh/pull/3128 changes

**Review by recuero — APPROVED** [review]

**Comment by recuero** [comment]
Tests don't catch that behavior?
