### PR TITLE
change rom error to exception 

### LINKED ISSUE #17080: Laromance window exception
## Reason
The Laromance model should throw an exception instead of a mooseError when a parameter is outside the rom range.  This will give MOOSE a chance to cut the timestep and hopefully the reduced timestep and strain increment will produce rom input within the valid range.  This let simulations run longer and get past these points without ignoring these invalid parameters.  If the strain increment is always producing invalid rom input, the timestep will be cut enough times that the simulation will eventually error out, just like the old behavior.

## Design
Change the MooseError to  MooseException

## Impact
none

### PR DESCRIPTION
**Pull request by lynnmunday**
In hopes of getting past bad values with a smaller timestep.  closes #17080

### CODE REVIEW

**Comment by lynnmunday** [comment]
@tophmatthews    Is this ok to do?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 1]
```diff
@@ -472,7 +472,10 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
     if (behavior == WindowFailure::WARN)
       mooseWarning(msg.str());
     else if (behavior == WindowFailure::ERROR)
-      mooseError(msg.str());
+    {
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:475]: You should add an enum `WindowFailure::EXCEPTION`, so the user can specify.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 2]
```diff
@@ -472,7 +472,10 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
...
+      msg << " \n   Cutting timestep.";
+      throw MooseException(msg.str());
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:477]: Also, this can just be `mooseException(mst.str())`. You may have to do some string handling here, but I think it should just work.

**Review by tophmatthews — CHANGES_REQUESTED** [review]
An enum for an exception should be used instead of replacing the error behavior.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 1 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: I think these should only be exceptions and not errors.  Exceptions will eventually turn into errors after they force the timestep down to dtmin.  The SamplerFullSolveMultiapp is able to catch the errors when they reach dtmin with ignore_solve_not_converge = true and will let that subapp fail without killing the entire mutliapp.  A mooseError will kill the entire multiapp.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 2 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: I checked and the string is getting output.  Is that what you meant?

Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: Yeah that looks good.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 1 above)
Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: That is fine, but I still think you need to add the option to throw a hard error. Make another enum for exception, and leave the error as is. Change the default to exception even. It's an easy fix to retain the ability to throw an error

**Comment by lynnmunday** [comment]
@tophmatthews @dschwen Could you review again and merge?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 1 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: A hard error isn't useful, the exception will error out.   All these extra options just get confusing when people copy and paste input files.

Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: No, I don't agree, an error may be important to ensure you're passing fair values. This will be important for model development beyond just the roms you are developing.

**Review by tophmatthews — CHANGES_REQUESTED** [review]

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h [hunk 3]
```diff
@@ -58,12 +58,13 @@ class LAROMANCEStressUpdateBaseTempl : public RadialReturnCreepStressUpdateBaseT
   virtual Real computeTimeStepLimit() override;
 
   /// Enum to error, warn, ignore, or extrapolate if input is outside of window of applicability
-  enum class WindowFailure
```
Comment (tophmatthews) [inline modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:61]: Why all the changes?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 4]
```diff
@@ -25,7 +25,7 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::validParams()
   params.addParam<MaterialPropertyName>("environmental_factor",
                                         "Optional coupled environmental factor");
 
-  MooseEnum error_limit_behavior("ERROR WARN IGNORE", "ERROR");
+  MooseEnum error_limit_behavior("ERROR=0 EXCEPTION=1 WARN=2 IGNORE=3", "EXCEPTION");
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:28]: why numbers? 👍  to default change.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 5]
```diff
@@ -473,6 +474,8 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
       mooseWarning(msg.str());
     else if (behavior == WindowFailure::ERROR)
       mooseError(msg.str());
+    else
+      mooseException(msg.str());
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:478]: 👍

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 6]
```diff
@@ -839,11 +842,22 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::computeStressFinalize(
...
     _wall_dislocations[_qp] = _old_input_values[_wall_output_index];
-    mooseException("The negative values of the cell dislocation density, ",
-                   negative_cell_dislocations,
-                   ", and/or wall dislocation density, ",
-                   negative_wall_dislocations,
-                   ". Cutting timestep.");
+    if (_window_failure[_cell_input_index] == WindowFailure::ERROR ||
+        _window_failure[_wall_input_index] == WindowFailure::ERROR)
+    {
+      mooseError("The negative values of the cell dislocation density, ",
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:848]: This is new, do you think it's important to error here, or is exception good enough? This is not checking input windows, its just checking if its negative. The error I am pushing for is important for the _inputs_ going into the ROM, the _outputs_ here are more about being sane. `WindowFailure` does not really describe the output value checks does it?.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 7]
```diff
@@ -839,11 +842,22 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::computeStressFinalize(
...
     _cell_dislocations[_qp] = _old_input_values[_cell_output_index];
     _wall_dislocations[_qp] = _old_input_values[_wall_output_index];
-    mooseException("The negative values of the cell dislocation density, ",
-                   negative_cell_dislocations,
-                   ", and/or wall dislocation density, ",
-                   negative_wall_dislocations,
-                   ". Cutting timestep.");
+    if (_window_failure[_cell_input_index] == WindowFailure::ERROR ||
+        _window_failure[_wall_input_index] == WindowFailure::ERROR)
+    {
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:847]: extra {}

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 4 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:28]: Its because we are using the same windowFailure enum for error_limit and extrapolated_limit but error_limit has different valid enums than extrapolated_limit.  So to make extroplated_limit and error_limit correspond to the correct windowFailure enum, I needed the numbers.

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h (hunk 3 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:61]: Look at the answer below, but it is to get the indexing right.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 6 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: You're right, this should only be an exception and not an error.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 4 above)
Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:28]: Oh interesting, did that really screw things up beforehand?

Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:28]: They were fine until I added extrapolate.  That messed up the indexing in the extrapolatedLimitBehavior,  so instead of getting a warning, it would give an exception because that is the second entry in the window failure enum that is corresponding to the 2nd entry in the extrapolated limit behavior.  For how we are using it, the string doesn't matter.

**Comment by lynnmunday** [comment]
@dschwen can you merge this.  @tophmatthews is fine with the changes

**Comment by tophmatthews** [comment]
I'm not sure I'm fine with the changes yet, but I suppose I need to give you a better answer. I don't think you need it for the outputs still, and I'm not sure you need all the complications with the enum...but let me do some legwork first...

**Review by tophmatthews — CHANGES_REQUESTED** [review]
Okay, I understand a bit more now of what is going on. I like that you took out the output checks. I don't think it's a bad idea to add checks there, but you need to use a different inputparam. As for the different enum, the WindowFailure is used for both `error_limit_behavior` and `extrapolated_limit_behavior` on purpose. All inputs are checked via `checkInputWindow`. If a select few are allowed to extrapolate, the the check is bypassed, and extrapolation happens later. What that means is that all the extra pieces here with numbers is unnecessary, and you need to add an exception to `extrapolated_limit_behavior` as well.

**Comment by lynnmunday** [comment]
@tophmatthews I added the exception to the extrapolated limit behavior and left the numbers in there too.  They make it easier to figure out how the enums maps to each other.

**Comment by tophmatthews** [comment]
This just seems way more complicated then you are trying to do I think? Apologies for being unclear. I'll put up a dummy pr to show what I think you can simply do...

**Comment by lynnmunday** [comment]
@tophmatthews I know I can get rid of the numbers but since I was putting in a new enum I decided to clean up the code to make it easier for someone other than me to maintain.  If you don't want these changes, I'm fine with that.  I really only care about getting an exception merged.  So if you want your pr instead, close this one and ask Daniel to merge yours.

**Comment by tophmatthews** [comment]
I'm not trying to scoop your PR, I just don't think adding statics and other complications here cleans it up, does it? I'm willing to learn.

**Comment by lynnmunday** [comment]
@tophmatthews I know you're not and I'm fine with your pr since you're the one who has to deal with this material class the most.  I like the static getters because they put the MooseEnums next to the enum class in the header. I don't like how mooseEnums and the enum class are so disjointed.  In this case, the strings in each enum don't really correspond to each other and only the order matters.  So you could switch the order of the strings in one enum and now they would no longer correspond to the same string from the enum class.   At least by putting them together in the header, you can see this ordering.  I like the numbers because it makes it clear which enum is corresponding to which and the ordering no longers matters.  I think this makes it easier to correlate the two sets of enums since they have to be separate data.

**Comment by lynnmunday** [comment]
@tophmatthews @dschwen   Daniel, will you merge this unless Topher has any comments about it?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 5 above)
Comment (dschwen) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:478]: Calling this with `WindowFailure::EXTRAPOLATE` will throw an exception. Wut?

Comment (dschwen) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:478]: no it won't

**Comment by tophmatthews** [comment]
So I think I get your points on the static, with only having the definition once. The problem is that you are still retaining `enum class WindowFailure` since `checkInputWindow` takes `WindowFailure` to check both `error_limit_behavior` and `extrapolated_limit_behavior` right?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 8]
```diff
@@ -460,7 +460,8 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
                                                         const WindowFailure behavior,
                                                         const std::vector<Real> & global_limits)
 {
-  if (behavior != WindowFailure::WARN && behavior != WindowFailure::ERROR)
+  if (behavior != WindowFailure::WARN && behavior != WindowFailure::ERROR &&
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:463]: This is fine by me if @dschwen buys in. The only thing is this line should probably be `if if (behavior != WindowFailure::IGNORE && behavior != WindowFailure::EXTRAPOLATION)`,  and ...

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 9]
```diff
@@ -473,6 +474,8 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
       mooseWarning(msg.str());
     else if (behavior == WindowFailure::ERROR)
       mooseError(msg.str());
+    else
```
Comment (tophmatthews) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:477]: ...this turned into an else if, with an `else mooseError("internal error...blah blah)`

**Review by tophmatthews — CHANGES_REQUESTED** [review]

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 9 above)
Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C]: I changed this over to your commit with a switch statement here.

**Review by tophmatthews — APPROVED** [review]
👍

**Comment by lynnmunday** [comment]
@dschwen Will you merge this?  I am in agreement with @tophmatthews about simplifying the enums.

**Review by dschwen — APPROVED** [review]
