### PR TITLE
CNSFV block restriction

### LINKED ISSUE #8851: Block restriction causes segfault in CNSFV
### Error report
I am working with the CNSFV code in the Navier-Stokes module.  I am trying to restrict a fluid flow to a subdomain of the problem.  However, this appears to be causing a segmentation fault.  Running the same input deck without block restrictions doesn't produce an error, just wrong answers.  Both input files are included below.

<details><summary>The gdb stack trace</summary>
<pre>
/opt/moose/gcc-6.2.0/include/c++/6.2.0/debug/vector:415:
Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fffffffc130 {
      type = std::__debug::vector<unsigned int, std::allocator<unsigned int> >;
    }

Program received signal SIGABRT, Aborted.
0x00007fffe7714428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007fffe7714428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffe771602a in __GI_abort () at abort.c:89
#2  0x00007fffe7e671e3 in __gnu_debug::_Error_formatter::_M_error (this=0x62a140 <__gnu_debug::_Error_formatter::_M_at(char const*, unsigned int)::__formatter>)
    at ../../../../../gcc-6.2.0/libstdc++-v3/src/c++11/debug.cc:1061
#3  0x00007ffff6eb60b2 in std::__debug::vector<unsigned int, std::allocator<unsigned int> >::operator[] (this=0x7fffffffc130, __n=0) at /opt/moose/gcc-6.2.0/include/c++/6.2.0/debug/vector:415
#4  0x00007ffff12534cb in MooseVariable::getElementalValue (this=0xb82330, elem=0xa25280, idx=0) at /home/moose-user/Projects/moose/framework/src/base/MooseVariable.C:1716
#5  0x00007ffff3525a65 in CNSFVLeastSquaresSlopeReconstruction::reconstructElementSlope (this=0xba0a60)
    at /home/moose-user/Projects/moose/modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C:157
#6  0x00007ffff5285819 in SlopeReconstructionBase::computeElement (this=0xba0a60) at /home/moose-user/Projects/moose/modules/rdg/src/userobjects/SlopeReconstructionBase.C:217
#7  0x00007ffff5261a7e in ElementLoopUserObject::onElement (this=0xba0a60, elem=0xa22140) at /home/moose-user/Projects/moose/modules/rdg/src/userobjects/ElementLoopUserObject.C:147
#8  0x00007ffff5261664 in ElementLoopUserObject::execute (this=0xba0a60) at /home/moose-user/Projects/moose/modules/rdg/src/userobjects/ElementLoopUserObject.C:97
#9  0x00007ffff127b42d in FEProblemBase::computeUserObjects (this=0xaf5380, type=@0x7fffffffcd60: EXEC_LINEAR, group=@0x7fffffffcd5c: Moose::POST_AUX)
    at /home/moose-user/Projects/moose/framework/src/base/FEProblemBase.C:2591
#10 0x00007ffff128225d in FEProblemBase::computeResidualType (this=0xaf5380, soln=..., residual=..., type=Moose::KT_ALL) at /home/moose-user/Projects/moose/framework/src/base/FEProblemBase.C:3618
#11 0x00007ffff1281e53 in FEProblemBase::computeResidual (this=0xaf5380, soln=..., residual=...) at /home/moose-user/Projects/moose/framework/src/base/FEProblemBase.C:3542
#12 0x00007ffff1281e13 in FEProblemBase::computeResidual (this=0xaf5380, soln=..., residual=...) at /home/moose-user/Projects/moose/framework/src/base/FEProblemBase.C:3534
#13 0x00007ffff15300c3 in NonlinearSystem::solve (this=0xb1e230) at /home/moose-user/Projects/moose/framework/src/base/NonlinearSystem.C:121
#14 0x00007ffff12810e9 in FEProblemBase::solve (this=0xaf5380) at /home/moose-user/Projects/moose/framework/src/base/FEProblemBase.C:3313
#15 0x00007ffff0b11faf in TimeStepper::step (this=0xaeed10) at /home/moose-user/Projects/moose/framework/src/timesteppers/TimeStepper.C:188
#16 0x00007ffff0cb5194 in Transient::solveStep (this=0xb713e0, input_dt=-1) at /home/moose-user/Projects/moose/framework/src/executioners/Transient.C:392
#17 0x00007ffff0cb4d68 in Transient::takeStep (this=0xb713e0, input_dt=-1) at /home/moose-user/Projects/moose/framework/src/executioners/Transient.C:327
#18 0x00007ffff0cb49aa in Transient::execute (this=0xb713e0) at /home/moose-user/Projects/moose/framework/src/executioners/Transient.C:251
#19 0x00007ffff14d8995 in MooseApp::executeExecutioner (this=0x6cf240) at /home/moose-user/Projects/moose/framework/src/base/MooseApp.C:468
#20 0x00007ffff14d9598 in MooseApp::run (this=0x6cf240) at /home/moose-user/Projects/moose/framework/src/base/MooseApp.C:619
#21 0x000000000041adaf in main (argc=3, argv=0x7fffffffd178) at /home/moose-user/Projects/phoenix/src/main.C:23
</pre>
</details>

It looks like the error involves an empty array in MooseVariable::getElementalValue(), but I'm having trouble tracing the problem further.  Any help would be appreciated.

### PR DESCRIPTION
**Pull request by Chuban**
Let's try this again.

A change to CNSFVLeastSquaresSlopeReconstruction.C redefines an internal side to be a boundary for which a neighboring element exists and is a member of the subdomain. Internal boundaries between subdomains are now handled in the same manner as external boundaries. This permits CNSFV variables to be restricted to specific subdomains of the problem.

closes #8851

### CODE REVIEW

File: modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C [hunk 1]
```diff
@@ -128,7 +128,7 @@ CNSFVLeastSquaresSlopeReconstruction::reconstructElementSlope()
 
     /// for internal side
 
-    if (elem->neighbor(is) != NULL)
+    if (elem->neighbor(is) != NULL && hasBlocks(elem->neighbor(is)->subdomain_id()))
```
Comment (andrsd) [inline modules/navier_stokes/src/userobjects/CNSFVLeastSquaresSlopeReconstruction.C]: Notice that `elem->neighbor(is)` is obtained on the first line in the body of this if-statement. So let's do:
```
    if (elem->neighbor(is) != NULL)
    {
      const Elem * neig = elem->neighbor(is);
      if (this->hasBlocks(neig->subdomain_id()))
      {
        <original body>
      }
```

**Review by andrsd — CHANGES_REQUESTED** [review]

**Comment by Chuban** [comment]
I made this change rather blindly as I thought it was only stylistic, but that's not so.  We have three cases to handle: (1) the neighbor is defined and in the subdomain, (2) the neighbor is defined and out of the subdomain, and (3) the neighbor is not defined.  We need the outer else statement (line 202) to run for cases 2 and 3.  The proposed change only allows it to run for cases 3 and completely skips over a large section of code in case 2.  I think we need to revert back to the original construction.

Please block this PR until this has been resolved.

**Comment by Chuban** [comment]
This should be ready to go now.

**Review by andrsd — APPROVED** [review]
