### PR TITLE
fix ElementLoopUserObject along interfaces

### LINKED ISSUE #9591: CNSFV failure while varying the number of processes
### Description of the error
When using the CNSFV portion of the NS module, varying the number of processes can cause MOOSE errors.  These seem to originate in the `ElementLoopUserObject` class.  The simulation in which the errors have been observed contains two blocks separated by an interface.  User objects that inherit from `ElementLoopUserObject` are restricted to one of those blocks and the errors occur for elements on the interface.  The error is triggered by not finding an expected cached value.

### Proposed corrective action
As the error only appears for some numbers of processes, it is suspected it be related to the partitioning of the mesh and the communication between the processes.  Currently, `ElementLoopUserObject::onInterface()` is an empty function.  `ElementLoopUserObject::onInternalSide()`, in contrast, performs a check on the processor ids of the current and neighbor elements and initiates communication by editing `_interface_elem_ids`.  Defining `onInterface()` in a manner similar to `onInternalSide()` appears to resolve the problem.

### Identified impact
none

### PR DESCRIPTION
**Pull request by Chuban**
ElementLoopUserObject has been modified to work along mesh interfaces in a parallel environment.  An additional callback, `computeInterface()`, has been added for future use.

### CODE REVIEW

File: modules/rdg/src/userobjects/ElementLoopUserObject.C [hunk 1]
```diff
@@ -185,10 +185,32 @@ ElementLoopUserObject::onInternalSide(const Elem * elem, unsigned int side)
...
+  {
+    computeInterface();
+  }
+
+  if (!_have_interface_elems &&
+      (_current_elem->processor_id() != _current_neighbor->processor_id()))
+  {
+    // if my current neighbor is on another processor store the current element
+    // ID for later
+    // communication
```
Comment (andrsd) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: reflow the comment here, so it is just 2 lines

**Review by andrsd — CHANGES_REQUESTED** [review]

File: modules/rdg/src/userobjects/ElementLoopUserObject.C [hunk 2]
```diff
@@ -185,10 +185,31 @@ ElementLoopUserObject::onInternalSide(const Elem * elem, unsigned int side)
...
+  _current_neighbor = elem->neighbor(side);
+
+  // Get the global id of the element and the neighbor
+  const dof_id_type elem_id = elem->id();
+  const dof_id_type neighbor_id = _current_neighbor->id();
+
+  // TODO: add if-statement to check if this needs to be executed
+  if ((_current_neighbor->active() && (_current_neighbor->level() == elem->level()) &&
+       (elem_id < neighbor_id)) ||
+      (_current_neighbor->level() < elem->level()))
```
Comment (permcody) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: I don't understand the logic here: In the first half of the expression (separated by the OR expression) you are checking (among other things for a lower ID), is that so that you only execute on the interface once? If so, what about the the second case, in this scenario the current_neighbor may not be active since you are just using the `neighbor` method of the current element which returns an element at the same level. I'm fairly certain this won't handle all adaptivity cases. Also, `neighbor` is deprecated.

**Comment by Chuban** [comment]
This should be ready for merging now.

File: modules/rdg/src/userobjects/ElementLoopUserObject.C (hunk 2 above)
Comment (Chuban) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: Since the operation at the interface should closely resemble that of an internal side, this bit of code was taken from `onInternalSide()`.  We should get input from the original author (@yidongxiainl), but that is how I understand the logic.  I don't see in the documentation that `neighbor()` only returns an element at the same level.  Switching to use `neighbor_ptr()` seems a simple fix.

Comment (permcody) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: Agreed, I'll chat with @yidongxiainl then. He may not be using this with adaptivity yet but I fully suspect that there are issues.

Comment (andrsd) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: Internal sides are by definition hit twice. Once from an element and second time form a neighbor.  However, we want to compute things on them just once, therefore `elem_id<neighbor_id`. And this is only valid when element and its neighbor are at the same level of refinement.  

This should be fine, we have this at other places in MOOSE.

Comment (permcody) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: Well it might be fine for most meshes (that start from a single level of elements so all children will be at a higher number) but this assumption could break down with a sufficiently screwy mesh. You're right though that it's not really Adam's job to fix this.

Comment (andrsd) [inline modules/rdg/src/userobjects/ElementLoopUserObject.C]: The level comparison (after `||`) should take care of that. We developed this boolean expression over time, so it should be pretty robust. If there is a corner case, we did not seem to hit it yet.

**Review by andrsd — APPROVED** [review]
