### PR TITLE
Parallel sync fix

### LINKED ISSUE #23796: Parallel computing hung when using Mortar Constraint
## Bug Description

When using Mortar method in `Constraints` of type `ModularGapConductanceConstraint` to model gap heat transfer, calculation hung at `Computing Residual`. The discussion about this issue is at https://github.com/idaholab/moose/discussions/23629#discussion-4934340.  When running on 2 nodes with 4 cpus on each node with the input file and msh mesh provided, the output of Unique Stack Traces from `find_hung_process.sh` began to diverged from `-s 35`. Here is the console output:
```
Unique Stack Traces
********************************************************************************
Count: 7

Host: dcc-core-01 PID: 1161914
Host: dcc-core-01 PID: 1161912
Host: dcc-core-01 PID: 1161915
Host: dcc-core-02 PID: 3391780
Host: dcc-core-01 PID: 1161913
Host: dcc-core-02 PID: 3391778
Host: dcc-core-02 PID: 3391777

#0  0x00007f87f10c12c8 in poll () from /lib64/libc.so.6
#1  0x00007f87f19745b3 in MPID_nem_tcp_connpoll () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#2  0x00007f87f19648b8 in MPIDI_CH3I_Progress () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#3  0x00007f87f1954772 in MPID_Iprobe () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#4  0x00007f87f17fe1e9 in PMPI_Iprobe () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#5  0x00007f87fb95a16d in Moose::Mortar::Contact::communicateGaps(std::unordered_map<libMesh::DofObject const*, std::pair<MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<900ul> >, true>, double>, std::hash<libMesh::DofObject const*>, std::equal_to<libMesh::DofObject const*>, std::allocator<std::pair<libMesh::DofObject const* const, std::pair<MetaPhysicL::DualNumber<double, MetaPhysicL::SemiDynamicSparseNumberArray<double, unsigned long, MetaPhysicL::NWrapper<900ul> >, true>, double> > > >&, unsigned int, MooseMesh const&, bool, bool, libMesh::Parallel::Communicator const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/modules/contact/lib/libcontact-opt.so.0
#6  0x00007f87fb95c417 in ComputeWeightedGapLMMechanicalContact::post() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/modules/contact/lib/libcontact-opt.so.0
#7  0x00007f87f90897f6 in ComputeMortarFunctor::operator()(Moose::ComputeType) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#8  0x00007f87f92e85fd in NonlinearSystemBase::mortarConstraints(Moose::ComputeType) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#9  0x00007f87f93c5534 in NonlinearSystemBase::computeResidualInternal(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#10 0x00007f87f93c6468 in NonlinearSystemBase::computeResidualTags(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#11 0x00007f87f994b698 in FEProblemBase::computeResidualTags(std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#12 0x00007f87f989429a in FEProblemBase::computeResidualInternal(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#13 0x00007f87f987c6a5 in FEProblemBase::computeResidualSys(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#14 0x00007f87f93c0542 in ComputeResidualFunctor::residual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, libMesh::NonlinearImplicitSystem&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#15 0x00007f87f7ea467e in libmesh_petsc_snes_residual () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#16 0x00007f87f4652d2d in SNESComputeFunction () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#17 0x00007f87f46449d8 in SNESLineSearchApply_Basic () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#18 0x00007f87f464216c in SNESLineSearchApply () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#19 0x00007f87f46b3042 in SNESSolve_NEWTONLS () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#20 0x00007f87f46619b9 in SNESSolve () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#21 0x00007f87f7ea8ca0 in libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int) () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#22 0x00007f87f7f22c88 in libMesh::NonlinearImplicitSystem::solve() () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#23 0x00007f87f9d5b4ab in TimeIntegrator::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#24 0x00007f87f93c22d3 in NonlinearSystem::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#25 0x00007f87f98841d6 in FEProblemBase::solve(unsigned int) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#26 0x00007f87f9f31344 in FEProblemSolve::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#27 0x00007f87f9f319c5 in FixedPointSolve::solveStep(double&, double&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#28 0x00007f87f9f48044 in FixedPointSolve::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#29 0x00007f87f97074ce in TimeStepper::step() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#30 0x00007f87f9f3052e in Transient::takeStep(double) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#31 0x00007f87f9f2d3d0 in Transient::execute() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#32 0x00007f87fa29386b in MooseApp::executeExecutioner() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#33 0x00007f87fa29dfc9 in MooseApp::run() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#34 0x0000555b1603d136 in main ()

********************************************************************************
Count: 1

Host: dcc-core-02 PID: 3391779

Host: dcc-core-02 PID: 3391779
#0  0x00007f94939192a5 in MPIDI_CH3I_Progress () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#1  0x00007f94938a0e8b in MPIR_Waitall_state () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#2  0x00007f94938a0f19 in MPIR_Waitall_impl () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#3  0x00007f94938a11a6 in MPIR_Waitall () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#4  0x00007f94937c80ca in PMPI_Waitall () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libmpi.so.12
#5  0x00007f9495c35472 in PetscSFLinkWaitRequests_MPI () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#6  0x00007f9495b993e6 in PetscSFBcastEnd_Basic () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#7  0x00007f9495b8b86f in PetscSFBcastEnd () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#8  0x00007f9495b925f6 in VecScatterEnd_Internal () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#9  0x00007f9495b97df4 in VecScatterEnd () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#10 0x00007f9495b6227b in VecGhostUpdateEnd () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#11 0x00007f9499ca1c00 in libMesh::PetscVector<double>::operator=(libMesh::PetscVector<double> const&) () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#12 0x00007f9499ca1c8a in libMesh::PetscVector<double>::operator=(libMesh::NumericVector<double> const&) () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#13 0x00007f9499e57f87 in libmesh_petsc_snes_residual () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#14 0x00007f9496606d2d in SNESComputeFunction () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#15 0x00007f94965f89d8 in SNESLineSearchApply_Basic () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#16 0x00007f94965f616c in SNESLineSearchApply () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#17 0x00007f9496667042 in SNESSolve_NEWTONLS () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#18 0x00007f94966159b9 in SNESSolve () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/lib/libpetsc.so.3.16
#19 0x00007f9499e5cca0 in libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int) () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#20 0x00007f9499ed6c88 in libMesh::NonlinearImplicitSystem::solve() () from /hpc/group/dolbowlab/bz75/moose-compilers/mambaforge3/envs/moose/libmesh/lib/libmesh_opt.so.0
#21 0x00007f949bd0f4ab in TimeIntegrator::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#22 0x00007f949b3762d3 in NonlinearSystem::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#23 0x00007f949b8381d6 in FEProblemBase::solve(unsigned int) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#24 0x00007f949bee5344 in FEProblemSolve::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#25 0x00007f949bee59c5 in FixedPointSolve::solveStep(double&, double&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#26 0x00007f949befc044 in FixedPointSolve::solve() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#27 0x00007f949b6bb4ce in TimeStepper::step() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#28 0x00007f949bee452e in Transient::takeStep(double) () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#29 0x00007f949bee13d0 in Transient::execute() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#30 0x00007f949c24786b in MooseApp::executeExecutioner() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#31 0x00007f949c251fc9 in MooseApp::run() () from /hpc/group/dolbowlab/bz75/projects/raccoon/moose/framework/libmoose-opt.so.0
#32 0x000056402f39f136 in main ()
```
## Steps to Reproduce

Run the input file with the msh file in the link on multiple cpus (preferably multiple nodes). I had hard time renaming boundaries on two annular meshes generated from `AnnularMeshGenerator` so all I can offer is `msh`. I was not able to reproduce the bug on plane type gap. I guess moose generated mesh of cylinder type gap might also lead to this bug.
https://duke.box.com/s/ujb1pbjo7hpgx8lta9747w4nhk5pjpub
```
stress_free_temperature = 300
thermal_expansion_coeff = 6.66e-6

[Problem]
  type = FEProblem
[]

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
  temperature = T_K
[]

[Mesh]
  patch_update_strategy = iteration
  use_displaced_mesh = true
  patch_size = 40
  [ori]
    type = FileMeshGenerator
    file = 'pellets_transf_h0.2e-3.msh'
  []
[]

[Variables]
  [disp_x]
    block = 'pellet_inner pellet_outer '
  []
  [disp_y]
    block = 'pellet_inner pellet_outer '
  []
  [disp_z]
    block = 'pellet_inner pellet_outer '
  []
  [T_K]
    [InitialCondition]
      type = ConstantIC
      value = 300.0
    []
  []
  [lm_pellet]
    block = 'pellet_secondary_subdomain'
    use_dual = true
  []
[]

[Kernels]
  [solid_x]
    type = ADStressDivergenceTensors
    variable = disp_x
    component = 0
    block = 'pellet_inner pellet_outer'
    use_displaced_mesh = false
  []
  [solid_y]
    type = ADStressDivergenceTensors
    variable = disp_y
    component = 1
    block = 'pellet_inner pellet_outer '
    use_displaced_mesh = false
  []
  [solid_z]
    type = ADStressDivergenceTensors
    variable = disp_z
    component = 2
    block = 'pellet_inner pellet_outer '
    use_displaced_mesh = false
  []
  [timeder]
    type = ADHeatConductionTimeDerivative
    variable = 'T_K'
    density_name = density
    specific_heat = specific_heat
    block = 'pellet_inner pellet_outer '
    use_displaced_mesh = true
  []
  [diff]
    type = ADHeatConduction
    variable = 'T_K'
    thermal_conductivity = thermal_conductivity
    block = 'pellet_inner pellet_outer '
    use_displaced_mesh = true
  []
  [heatsource]
    type = ADMatHeatSource
    variable = 'T_K'
    material_property = radial_source
    block = 'pellet_inner pellet_outer '
    use_displaced_mesh = true
  []
[]


[Debug]
  show_var_residual_norms = TRUE
[]


[BCs]
  [mirror_z]
    type = ADDirichletBC
    variable = disp_z
    boundary = 'mirror_innerp mirror_outerp  '
    value = 0
  []
  [mirror_x]
    type = ADDirichletBC
    variable = disp_x
    boundary = 'mirror_innerp mirror_outerp  '
    value = 0
  []
  [mirror_y]
    type = ADDirichletBC
    variable = disp_y
    boundary = 'mirror_innerp mirror_outerp  '
    value = 0
  []
[]


[Materials]
  [pellet_properties]
    type = ADGenericConstantMaterial
    prop_names = 'density  thermal_conductivity specific_heat'
    prop_values = '3.3112e3  34 1.2217e3' 
    block = 'pellet_inner pellet_outer'
  []
  [pulse_shape_linear]
    type = ADGenericFunctionMaterial
    prop_values = '5e10*max(11455*(t)/7,1e-9)'
    prop_names = 'radial_source'
    output_properties = 'radial_source'
    block = 'pellet_inner pellet_outer'
    use_displaced_mesh = false
  []
  [strain]
    type = ADComputeSmallStrain
    displacements = 'disp_x disp_y disp_z'
    eigenstrain_names = eigenstrain #nameS!
    block = 'pellet_inner pellet_outer '
  []
  [thermal_strain]
    type = ADComputeThermalExpansionEigenstrain
    stress_free_temperature = ${stress_free_temperature} 
    thermal_expansion_coeff = ${thermal_expansion_coeff} 
    eigenstrain_name = eigenstrain
    block = 'pellet_inner pellet_outer '
  []
  [elasticity]
    type = ADComputeIsotropicElasticityTensor
    youngs_modulus = 3.306e11
    poissons_ratio = 0.329
  []
  [stress]
    type = ADComputeLinearElasticStress
    block = 'pellet_inner pellet_outer '
  []
[]



[Contact]
  [pellet]
    primary = void_pellet_0
    secondary = void_pellet_1
    model = frictionless
    penalty = 1e6
    formulation = mortar
    c_normal = 1e6 
    correct_edge_dropping = true
  []
[]


[UserObjects]
  [conduction]
    type = GapFluxModelConduction
    temperature = T_K
    boundary = 'void_pellet_0 void_pellet_1    '
    gap_conductivity = 0.4
    use_displaced_mesh = true
  []
  [rad_pellet]
    type = GapFluxModelRadiation
    temperature = T_K
    boundary = void_pellet_0
    primary_emissivity = 0.37
    secondary_emissivity = 0.37
    use_displaced_mesh = true
  []
[]

[Constraints]
  [gap_pellet]
    type = ModularGapConductanceConstraint
    variable = lm_pellet
    secondary_variable = T_K
    primary_boundary = 'void_pellet_0'
    primary_subdomain = pellet_primary_subdomain
    secondary_boundary = 'void_pellet_1'
    secondary_subdomain = pellet_secondary_subdomain
    gap_flux_models = 'conduction rad_pellet' #closed_pellet  
    gap_geometry_type = 'CYLINDER'
    cylinder_axis_point_1 = '0 0 0'
    cylinder_axis_point_2 = '0 0 1'
    use_displaced_mesh = true
    quadrature = SECOND
  []
[]


[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -pc_factor_shift_type -pc_factor_shift_amount '
  petsc_options_value = 'lu      superlu_dist NONZERO 1e-14' 
  automatic_scaling = true
  line_search = none
  ignore_variables_for_autoscaling = 'pellet_normal_lm  lm_pellet '
  compute_scaling_once = true 
  scaling_group_variables = 'disp_x disp_y disp_z; T_K' 
  nl_rel_tol = 1e-50
  nl_abs_tol = 1e-8
  nl_max_its = 20
  dtmin = 1e-3
  dt = 1e-3
  start_time = 0e-3
  end_time = 7e-3
[]

[Outputs]
  [exodus]
    type = Exodus
    file_base = constMat
  []
  print_linear_residuals = false
[]
```

### PR DESCRIPTION
**Pull request by roystgnr**
## Reason
Fixes #23796.  This fixes the hung parallel runs, and adds assertions to help make those runs a bit easier to debug in the future.

## Design
The first commit wraps `loopOverMortarSegments` in a `PARALLEL_CATCH`, to synchronize handling of any exceptions (like the quadrature point exception thrown in the test case) between ranks.

The second commit adds new assertions.

## Impact
The fix keeps asynchronous exceptions from hanging a whole job, at the cost of adding a `maxloc` that makes exceptionless runs infinitesimally slower.

The new assertions should give fewer hangs and more accurate error messages when any similar bugs are hit in the future, at the cost of adding `max`/`min` calls that make `devel` and `dbg` runs infinitesimally slower.

### CODE REVIEW

File: framework/src/loops/ComputeMortarFunctor.C [hunk 1]
```diff
@@ -129,18 +131,29 @@ ComputeMortarFunctor::operator()(const Moose::ComputeType compute_type)
...
+                                            0,
+                                            _secondary_ip_sub_to_mats,
+                                            _primary_ip_sub_to_mats,
+                                            _secondary_boundary_mats,
+                                            act_functor);
+    }
+    catch (MooseException & e)
+    {
+      _fe_problem.setException(e.what());
+    }
```
Comment (lindsayad) [inline framework/src/loops/ComputeMortarFunctor.C:154]: So in `ThreadedElementLoopBase` we have a nested `try-catch` that catches `libMesh::LogicError` and `MetaPhysicL::LogicError` and re-throws as a `MooseException` which is caught by the outer `try-catch`. I think we should add that here as well. Also before setting the exception we should assert that we are not running threads (`ThreadedElementLoopBase`, because it is threaded, alternatively locks a mutex)

**Review by lindsayad — CHANGES_REQUESTED** [review]
Thanks so much for ~begugging~ debugging this Roy

File: framework/src/loops/ComputeMortarFunctor.C (hunk 1 above)
Comment (roystgnr) [reply framework/src/loops/ComputeMortarFunctor.C:154]: That seems sane.  The double `catch(foo)` in `AuxilliarySystem::computeMortarNodalVars` has a cleaner look to it, though, for the same effect; I'll do that unless you object.

Actually ... is it sane *enough*?  Looking through our `PARALLEL_CATCH` usage elsewhere, I see `catch(MetaPhysicL::LogicError & e)` ... and for future-proofing there's no telling what we might have coming out of libraries some day.  I'd be tempted to `catch(...)` and get everything ... except that for *true* logic errors we really do want to just scream-and-die right away while there's a hope of debugging.  `parallel_object_only()` would be a perfect case in point.  It's just an artifact of past design mistakes that libMesh sees geometry errors and throws exceptions calling them logic errors, thus forcing app codes to treat `LogicError` as if it wasn't supposed to be just for bugs...

In my own code I'd used `libMesh::ConvergenceFailure` for "stuff you can catch and recover from", but that was in a world without tangled meshes, where it was just solver convergence issues forcing me to back off and retry.  I think the long run solution might be to create ... call it `libMesh::EvaluationFailure`, maybe? ... make it a subclass of `LogicError` at first for backwards compatibility, then switch the catch blocks to catch it directly, then break it out into just a subclass of `std::runtime_error`.  `ConvergenceFailure` would be a subclass of `EvaluationFailure`, too, to use for e.g. nested iterative solvers.

But that's long run.  Here I'll just make the suggested change, unless you think my immediate fears are right and we ought to be catching `MetaPhysicL::LogicError` too.

Comment (lindsayad) [reply framework/src/loops/ComputeMortarFunctor.C]: Yes the catches at the same level look good too. And yes if you could add a catch for `MetaPhysicL::LogicError` in `AuxilliarySystem::computeMortarNodalVars` that would be much appreciated

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: framework/src/loops/ComputeMortarFunctor.C (hunk 1 above)
Comment (roystgnr) [reply framework/src/loops/ComputeMortarFunctor.C]: Plain catch and `setException(e.what())`, or `translateMetaPhysicLError`?  The latter does rethrow under the hood so we do need nested catches if you'd prefer that.

File: framework/src/loops/ComputeMortarFunctor.C [hunk 2]
```diff
@@ -129,18 +131,33 @@ ComputeMortarFunctor::operator()(const Moose::ComputeType compute_type)
...
+                                            act_functor);
+    }
+    catch (libMesh::LogicError & e)
+    {
+      _fe_problem.setException("We caught a libMesh::LogicError: " + std::string(e.what()));
+    }
+    catch (MooseException & e)
+    {
+      _fe_problem.setException(e.what());
+    }
```
[the remark this answers is not in the document]
Comment (roystgnr) [reply framework/src/loops/ComputeMortarFunctor.C:158]: Wow.  I would not have considered exceeding an array size to be a recoverable error ... though yeah, now I see it in this case.  Definitely need some more thought before I go hog wild on a "figure out how to recover from precisely the set of exceptions that are recoverable" design...

**Comment by lindsayad** [comment]
Ok I have two threads talking about the same thing and I've contradicted myself between one conversation and what I've actually put into code. Looking at `translateMetaPhysicLError` ... I'm now undecided. @recuero do you have any sense of how often we have really oblique projections resulting in a really large AD container fill that can be saved by cutting the timestep and re-trying?

**Comment by recuero** [comment]
That's a tough question to answer. 

 - Situations in which we have really oblique projections resulting in large required AD container size happen when we have close to perpendicular surfaces that come into contact. That sounds like a contradiction but it can easily happen when there is contact between a cube and a plane (e.g. with wrap-around sidesets) or a sphere and a plane. So, it's a pretty common situation.
 - Since oblique projections can happen in many cases, we should be able to cut the time step if something is off. 
 
 Can the large, required container size be mitigated by cutting the time step? I think that, in general, no. It could be that if an intermediate very distorted configuration generated very oblique projections and cutting the time step would resolve that particular issue, but my guess is that this occurrence would be very rare.

File: modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C [hunk 3]
```diff
@@ -206,6 +206,8 @@ ComputeWeightedGapLMMechanicalContact::computeJacobian(const Moose::MortarType m
 void
 ComputeWeightedGapLMMechanicalContact::post()
 {
+  parallel_object_only();
```
Comment (recuero) [inline modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C:209]: We should also plan on extending this call to other mortar objects in the future, shouldn't we?

**Comment by lindsayad** [comment]
Based off your response, my inkling would be to regard any time we exceed the configured AD container size as a hard error, and not something we should try to recover from.

In that vein, @roystgnr I would suggest we regard `MetaPhysicL::LogicError` as `mooseError`, at least until we have some distinction between "exceeded AD container size" types of errors and "I tried to take the log of a negative number" type of error. So I think we should use `moose::translateMetaPhysicLError` uniformly

File: modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C (hunk 3 above)
Comment (lindsayad) [reply modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C:209]: yes

Comment (roystgnr) [reply modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C:209]: IMHO there's probably a thousand places in MOOSE that would benefit from this call.  I figured for now I'd just leave this reactively-added batch in and see if there was much interest or much pushback before I considered getting proactive about it.

**Comment by roystgnr** [comment]
```
tensor_mechanics/test:pressure.jacobian_RZ_quad8: /opt/moose/modules/tensor_mechanics/test/tests/pressure/ring.i:33: (Problem/coord_type):
tensor_mechanics/test:pressure.jacobian_RZ_quad8: The parameter 'coord_type' is deprecated.
tensor_mechanics/test:pressure.jacobian_RZ_quad8: Please use 'Mesh/coord_type' instead
tensor_mechanics/test:pressure.jacobian_RZ_quad8: 
tensor_mechanics/test:pressure.jacobian_RZ_quad8: 
tensor_mechanics/test:pressure.jacobian_RZ_quad8: ################################################################################
tensor_mechanics/test:pressure.jacobian_RZ_quad8: Tester failed, reason: EXPECTED OUTPUT NOT FOUND
```

In Docker/Test_modules?  I don't think that was me.

**Comment by roystgnr** [comment]
> So I think we should use moose::translateMetaPhysicLError uniformly

Added; assuming I've interpreted you correctly.

> Because performing abort in one thread (which is what mooseError does) and not others can lead to very bad simulation tear-down.

I'd have hoped that `MPI_THREAD_FUNNELED` would give implementations enough of a warning to let `MPI_Abort` clean up after itself.  Digging into `timpi_init.C` to look into things brings up a couple paragraphs' comment about how many stacks aren't handling `MPI_THREAD_FUNNELED` requests properly, though, so maybe not.

**Comment by lindsayad** [comment]
So you think conceptually `MPI_Abort` should be fine in a threaded region? I just recall working with @grmnptr on some problem where we were seeing use of a static mutex that had been destroyed already when we were aborting in a threaded region

**Review by lindsayad — APPROVED** [review]
