### PR TITLE
SimplePredictor console output fix

### LINKED ISSUE #14099: Moose::out precision reset in SimplePredictor
## Bug Description
`SimplePredictor` changes the std::setprecision, but fails to set it back to the normal values. This causes failures in norm outputs, notably when using `ReferenceResidualProblem`

## Steps to Reproduce
```
# The purpose of this test is to ensure the SimplePredictor resets the std::precision

[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 3
  ny = 3
[]

[Problem]
  type = ReferenceResidualProblem
  solution_variables = 'u'
  extra_tag_vectors = 'ref'
  reference_vector = 'ref'
[]

[Variables]
  [./u]
  [../]
[]

[Kernels]
  [./diff_u]
    type = Diffusion
    variable = u
    extra_vector_tags = 'ref'
  [../]
[]

[BCs]
  [./bot]
    type = PresetBC
    variable = u
    boundary = bottom
    value = 0.0
  [../]
  [./top]
    type = FunctionPresetBC
    variable = u
    boundary = top
    function = 't'
  [../]
[]

[Executioner]
  type = Transient

  start_time = 0.0
  dt = 0.5
  end_time = 1.0

  [./Predictor]
    type = SimplePredictor
    scale = 1.0
  [../]
[]

```

## Impact
This makes it hard to see the variable norms when running with `ReferenceResidualProblem`

### PR DESCRIPTION
**Pull request by tophmatthews**
Removed std::fixed and std::precision calls in SimplePredictor. They seem unnecessary, and limit the ability to see very small predictor numbers.

Closes #14099

### CODE REVIEW

File: framework/src/predictors/SimplePredictor.C [hunk 1]
```diff
@@ -41,14 +41,7 @@ SimplePredictor::shouldApply()
 void
 SimplePredictor::apply(NumericVector<Number> & sln)
 {
-  // Save the original stream flags
-  std::ios_base::fmtflags out_flags = Moose::out.flags();
-
-  _console << "  Applying predictor with scale factor = " << std::fixed << std::setprecision(2)
```
Comment (tophmatthews) [inline framework/src/predictors/SimplePredictor.C]: Another option is to use `Moose::out` here instead of _console. This stream gets reset by `Moose::out.flags(out_flags)` below. However, I wasn't sure i f there is a real reason to use `_console` instead of `Moose::out`?

Comment (permcody) [reply framework/src/predictors/SimplePredictor.C]: `_console` respects the options given by the user (say if they want to turn it off, or have it print less frequently). More importantly it gets indented when used in a Multiapp. `Moose::out` is just `std::cout`. You don't want to use `Moose::out` for anything but temporary debugging.

Comment (tophmatthews) [reply framework/src/predictors/SimplePredictor.C]: Good to know. Then the current implementation makes the most sense. There are probably ways to change the output format temporarily, but I don't think it's necessary and will hide values (i.e. it'll show 0 if predictor is less than 0.01)

Comment (permcody) [reply framework/src/predictors/SimplePredictor.C]: This "fix" may or may not be good permantely. As we refactor things around you might run into new problems where the precision or output type may not be what you want because another system is setting and not resetting flags properly. 

What probably should be done is we have a standard that we agree on (say scientific with some specific precision), and if you are ok with that you should have to worry about saving and resetting flags. If however somebody wants something different they should restore the flags to the default before that routine exits. Seems like a good intern project!

**Review by permcody — APPROVED** [review]
I guess your test will catch it if it changes!

File: framework/src/predictors/SimplePredictor.C (hunk 1 above)
Comment (tophmatthews) [reply framework/src/predictors/SimplePredictor.C]: Yeah, I agree. This fix was due to SimplePredictor screwing up the flags for reference residual norms.
