### PR TITLE
 PorousFlowDarcyVelocityComponentLowerDimensional added 

### LINKED ISSUE #10269: AuxKernel for computing Darcy velocity in fractures
## Rationale

Tagging @cpgr in case i've made an error in the stuff below.

PorousFlow is being used to simulate flow in mixed-dimensional meshes.  The 3D mesh contains 2D elements that represent thin, highly conductive fractures.   Because of MOOSE's dimensional independence, no extra code has been needed: the input file must just supply appropriately scaled permeability and porosity.  Specifically, the input-file-porosity = a * experimentally-measured-fracture-porosity and input-file-permeability = a * experimentally-measured-fracture-permeability.   Here "a" is the actual fracture thickness.  These input-file quantities are prescribed to Materials defined on the 2D elements.

Crazy results can be produced when calculating the Darcy velocity using the AuxKernel PorousFlowDarcyVelocityComponent, according to Philipp S.  I don't know exactly what results he's getting, but it's clear this AuxKernel doesn't work in this situation.

Here is the desired behaviour.

1. It will be assumed the user has an elemental AuxVariable (can either be constant or first order in the current PorousFlow setup) defined only on the 2D elements.  We want to calculate the DarcyVelocity in the 2D elements.

2. The fundamental assumption behind this 2D+3D approach is that the 2D elements are supposed to represent very thin 3D elements, inside which grad(P).n = 0, where n is the normal vector to the element.  Only then can the thin 3D element be replaced by a 2D one.   So, as far as the fracture is concerned, grad(P) should point in the tangential direction to the element.  I need to check that MOOSE actually does this.   The fracture does not care that outside (in the 3D elements) grad(P) is pointing somewhere else: **within the fracture grad(P).n = 0**.

3. The gravity vector will be projected to the element's tangential direction, and the vector (grad(P) - density*projected_gravity) will be formed.   This is appropriate because at steadystate this vector will be zero.

4. The result will be multiplied by the permeability.  The user should have chosen their permeability tensor so that the resultant vector is tangent to the element.   For instance, their permeability should not have components that mix tangential and normal directions.  I don't think this AuxKernel is the place to check this, however, because of the computational burden and because it would be extremely rare (I can't remember any experimental work that measures off-diagonal permeability components).  Better to state this in the ClassDescription.

5. The user extracts the components of this vector as usual.

## Description

Very little difference between this and PorousFlowDarcyVelocityComponent.  I have to quickly convince myself that MOOSE actually makes grad(P) lie along the element.  But all the code will include is a projection of gravity.  All the remaining stuff in PorousFlowDarcyVelocityComponent is the same.

## Impact

Ability to extract sensible Darcy velocity in simulations with mixed-dimensional elements.

### PR DESCRIPTION
**Pull request by WilkAndy**
This allows users to record Darcy velocity in a lower-dimensional block in their mesh, such as a block representing a fracture.

Fixes #10269

### CODE REVIEW

**Comment by WilkAndy** [comment]
This is finally done, @philippschaedle

File: modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+  const unsigned elem_dim = _current_elem->dim();
+  if (elem_dim == _mesh.dimension())
+    mooseError("The variable ",
+               _var.name(),
+               " must must be defined on lower-dimensional elements "
+               "only since it employs "
+               "PorousFlowDarcyVelocityComponentLowerDimensional\n");
+
+  const std::vector<RealGradient> & tang1 =
+      _subproblem.assembly(_tid).getFE(FEType(), elem_dim)->get_dxyzdxi();
```
Comment (permcody) [inline modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: @andrsd or @friedmud, before this gets merged in, do you have any opinions. This is pretty specialized so we don't have a better interface in MOOSE.

Comment (andrsd) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: I think there might be a problem calling this the very first time. This gets out FE from libMesh and requests an additional quantity (dxyzdxi/zeta). But reinit was already called, so my guess would be that you get some zero values back. The next time through it is probably fine.

Code-wise: you can do `_assembly.getFE(...)` instead of `_subproblem.assembly(_tid)`. That would be cleaner.

As far as user-friendly API goes, requesting values from FE happens deep in `Assembly::buildFE` and we do not provide users to pick what values they want. We pick `phi`, `dphi`, `d2phi` and `xyz` for them. Not sure if providing more flexibility would be useful.

Thinking more about this, may be a better approach is to get the references (actually pointers) as early as in the c-tor for all dimensions (0 - _mesh_dimension) and here just use something like `_tang1[elem_dim]`. That may fix the problem I described in paragraph 1 (is that was even a problem at all).

Comment (WilkAndy) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: OK, i'll try the things mentioned above, thank you.  By the way, i just copied that line from ```/tensor_mechanics/src/kernels/StressDivergenceTensorsTruss.C```.  The reason i didn't get the reference in the constructor was because i was considering deforming meshes, where the tangent vectors might change direction.  But perhaps that's just silly, and certainly silly if at some stage the above code gives tang1=0 !

Comment (WilkAndy) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: I get a seg-fault when the ctor contains:
```
 _tang1(_assembly.getFE(FEType(), _current_elem->dim())->get_dxyzdxi())
```
Any advice?

Comment (WilkAndy) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: It's the ```_current_elem->dim()``` that gives the seg-fault

Comment (andrsd) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Right, you cannot do `_current_elem->dim()` in the constructor, because `_current_elem` is set during the loop over the mesh. The `_tang1` need to become an array of pointers to the values, 0th index for 0D elements, 1st index for 1D, etc. up to LIBMESH_DIM. Then, do a loop to initialize each item. Then, in compute node use `_current_elem->dim()` to index into `_tang1`. Make more sense?

Comment (WilkAndy) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Thank @andrsd .   This "hassle" is exactly the feature i want to exploit in this AuxKernel !   I'll attempt to implement what you write above.

Comment (andrsd) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Yeah, I know. I was just trying to say, that it may seem like a hassle to get 4 references, when you really are going to use just one of them...

File: modules/porous_flow/test/tests/aux_kernels/darcy_velocity_lower_except.i [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+    type = TimeDerivative
+    variable = pp
+  [../]
+[]
+
+[AuxVariables]
+  [./fracture_vel_x]
+    order = CONSTANT
+    family = MONOMIAL
+    #block = 3
```
Comment (andrsd) [inline modules/porous_flow/test/tests/aux_kernels/darcy_velocity_lower_except.i]: remove this line, it looks like a left over from debugging

**Review by andrsd — CHANGES_REQUESTED** [review]

**Comment by WilkAndy** [comment]
Is this good to go now @andrsd ?

**Review by andrsd — APPROVED** [review]

**Comment by WilkAndy** [comment]
Thanks for the review and merge, @andrsd

**Comment by brianmoose** [comment]
Hmm, the Intel target for this seems to be reliably broken which has prevented this from getting onto the master branch: https://www.moosebuild.org/job/142739/
PR #10437 has the same errors which start after this was merged.
Maybe an integration issue with #9832?

**Comment by brianmoose** [comment]
Hmm, nevermind, looks like just a flaky test. It seems to be passing on the latest devel testing.
