### PR TITLE
Fixed AugmentSparsity for 1D contact problem

### LINKED ISSUE #8164: Constraint system for contact fails in 1D
### Description of the enhancement or error report
When you request the constraint system for mechanical contact with a 1D mesh, you get a PETSc error immediately:
[0]PETSC ERROR: nnz cannot be greater than row length: local row 4 value 6 rowlength 5

### Rationale for the enhancement or information for reproducing the error
This can be reproduced with the attached files and the combined module.
[one_d_contact.zip](https://github.com/idaholab/moose/files/627785/one_d_contact.zip)

### Identified impact
Having robust contact is needed for the 1D cases.

### PR DESCRIPTION
**Pull request by fdkong**
`dofMap().n_local_dofs() ` includes all dofs on local even for `scalar `variables,
and we hence do not need to do anything for `scalar` variables.

Closes #8164

### CODE REVIEW

**Review by permcody — APPROVED** [review]

File: framework/src/base/NonlinearSystemBase.C [hunk 1]
```diff
@@ -2145,15 +2144,9 @@ NonlinearSystemBase::augmentSparsity(SparsityPattern::Graph & sparsity,
...
-
-    // If we're _not_ on the last processor then all of the scalar dofs are off processor (n_oz)
-    const dof_id_type n_scalar_dofs_not_on_proc = processor_id() == n_processors()-1 ? 0 : dofMap().n_SCALAR_dofs();
-
-    // The total number of dofs on and off processor (including scalar dofs)
-    const dof_id_type n_dofs_on_proc = dofMap().n_local_dofs() + n_scalar_dofs_on_proc;
-    const dof_id_type n_dofs_not_on_proc = (dofMap().n_dofs() - dofMap().n_local_dofs()) + n_scalar_dofs_not_on_proc;
+    // The total number of dofs on and off processor
+    const dof_id_type n_dofs_on_proc = dofMap().n_local_dofs();
+    const dof_id_type n_dofs_not_on_proc = (dofMap().n_dofs() - dofMap().n_local_dofs());
```
Comment (jwpeterson) [inline framework/src/base/NonlinearSystemBase.C]: Extra parentheses aren't really necessary here, don't know if that's really part of the style guide though.

Comment (fdkong) [inline framework/src/base/NonlinearSystemBase.C]: will remove
