### PR TITLE
hit: speed up parsing hugely by fixing line-number calculation

### LINKED ISSUE #10091: hit: parser is slow for large files
## Rationale
Parsing large files is slow.  Users shouldn't have to wait or ever even be able to notice parsing speed.

## Description
Hit file parsing speed grows non-linearly as file size grows.

## Impact
Make users/developers happier with faster parsing speeds.

### PR DESCRIPTION
**Pull request by rwcarlsen**
This changes the naive N^2 algorithm during lexing where we read through the
entire file to calculate the line number for every token we emit.  Instead, we
now keep a running total line count and don't have to ready through the file
more than once.

Fixes #10091

### CODE REVIEW

File: framework/contrib/hit/lex.cc [hunk 1]
```diff
@@ -30,16 +30,16 @@ charIn(char c, const std::string & valid)
 #undef EOF
 
 int
-lineNum(size_t offset, const std::string & input)
+lineCount(const std::string & input)
 {
-  int line = 0;
+  int n = 0;
   size_t pos = input.find("\n", 0); // fist occurrence
```
Comment (andrsd) [inline framework/contrib/hit/lex.cc]: May be change the typo here as well: `fist` -> `first`

**Review by brianmoose — APPROVED** [review]
