### PR TITLE
XYMeshLineCutter bug fix

### LINKED ISSUE #31795: XYMeshCutter mentions quad-tri conversion in a warning even when it s not happening
### Bug Description

Observing it on this input
https://github.com/idaholab/open_pronghorn/blob/d297165e1716ad0e304c3a3a73220a4a25688c7b/validation/free_flow/isothermal/ercoftac_030_bfs/bfs_init_fully_developed_channel.i

### Steps to Reproduce

Run the input
See the warning
Look at the mesh, no Tris!

### Impact

Extra warning, caused a PR push to fail testing, I had to `allow_warnings`

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pbehne**
Added utility function to determine if point is on line

Given a cut line, the XYMeshCutter deletes elements on one side of the
line.
When the line cuts through quad elements, those elements are converted
to tris and refined to form a new mesh boundary coincident with the cut
line.
To determine whether the cut line cuts through a given element, each
vertex of the element is plugged into the line equation f(x, y) = ax + by + c.
An (x, y) point is on the line if f(x, y) = 0.
Vertices residing on one side of the line have positive f(x, y) and
vertices residing on the other side of the line have negative f(x, y).
If two vertices of an element have differently signed f values, the
element is deemed to be cut by the line and is marked for conversion to
tri elements and further refinement.

This PR patches a bug in the above logic.
Previously, the mesh generator did not check if a given vertex lies on
the cut line.
These vertices were assigned to one side of the line.
In the case of a quad that is not cut by the line, but has an edge
coincident with the line, this can cause those elements to be
incorrectly marked for tri conversion and refinement.
While the final cut mesh was correct, this results in an irrelevant, confusing
warning that quad elements are being converted to tri elements.
This PR adds checks to determine and ignore vertices that lie on the
cut line.
These vertices are no longer used when determining whether an element is cut
by the line.

Closes #31795.

### CODE REVIEW

File: framework/src/utils/MooseMeshXYCuttingUtils.C [hunk 1]
```diff
@@ -710,15 +721,17 @@ quadToTriOnLine(ReplicatedMesh & mesh,
...
+          node_side_rec.push_back(lineSideDeterminator(v_point(0),
+                                                       v_point(1),
+                                                       cut_line_params[0],
+                                                       cut_line_params[1],
+                                                       cut_line_params[2],
+                                                       true));
       }
-      if (std::accumulate(node_side_rec.begin(), node_side_rec.end(), 0) != 4 &&
-          std::accumulate(node_side_rec.begin(), node_side_rec.end(), 0) > 0)
+      const auto num_nodes = std::accumulate(node_side_rec.begin(), node_side_rec.end(), 0);
```
Comment (GiudGiud) [inline framework/src/utils/MooseMeshXYCuttingUtils.C:739]: add a comment please

this is counting the booleans in the node_side_rec, which does not include nodes that were exactly on the line (excluded from the decision)

File: framework/src/utils/MooseMeshXYCuttingUtils.C [hunk 2]
```diff
@@ -766,24 +779,33 @@ lineRemoverCutElemTri(ReplicatedMesh & mesh,
...
+      else
+        node_side_rec[i] = lineSideDeterminator(v_point(0),
+                                                v_point(1),
+                                                cut_line_params[0],
+                                                cut_line_params[1],
+                                                cut_line_params[2],
+                                                true);
     }
-    if (std::accumulate(node_side_rec.begin(), node_side_rec.end(), 0) == (int)node_side_rec.size())
+    const unsigned int num_nodes = std::accumulate(node_side_rec.begin(), node_side_rec.end(), 0);
```
Comment (GiudGiud) [inline framework/src/utils/MooseMeshXYCuttingUtils.C:815]: same add a comment please

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
nice fix. Thanks @pbehne !
