### PR TITLE
Remove boundary cell ghosting in MOOSE FVM

### LINKED ISSUE #22048: Remove boundary ghost cells from FVM
## Reason
Even though it simplifies certain things, using boundary ghosting is not a valid option for 3D unstructured meshes and would potentially lead to wrong results.

## Design
- Remove boundary ghost cells from MooseMesh and FaceInfo
- Forbid the usage of interpolate() functions on the boundary
- Switch the boundary treatment to the standard one (mirroring instead of 180 degree rotation)

## Impact
Will increase the reliability of 3D Moose FV simulations on unstructured meshes.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #22048

Other, related issues that will be fixed in this:
1. In the old approach (ghost cells and interpolating to the face on the boundary) with `FVAdvection`, and `FVMatAdvection`, if you use `FVDirichletBC` and `upwind` "interpolation", it extrapolated a ghost cell value and upwind-ed it to the inlet surface. In the new approach we evaluate the variable on the surface which means that the correct face value will be used for the residual. 
2. If there is a Dirichlet boundary condition for both velocity and advected quantity (rho) and derived material-objects (rho*u) used in `FVMatAdvection`, we now make sure that we strictly respect these boundary conditions instead of the interpolation of the product. (See the boundary values of `fvkernels/mms/mass-mom-mat-advection-diffusion.test`
3. Add an actual MMS test for `fvkernels/mms/mass-mom-mat-advection-diffusion.test` instead of the exodiff

### CODE REVIEW

File: framework/include/mesh/FaceInfo.h [hunk 1]
```diff
@@ -87,14 +87,23 @@ class FaceInfo
...
   ///@}
 
   ///@{
   /// Returns the elem and neighbor subdomain IDs. If no neighbor element exists, then
   /// an invalid ID is returned for the neighbor subdomain ID.
   SubdomainID elemSubdomainID() const { return _elem_info->subdomain_id(); }
-  SubdomainID neighborSubdomainID() const { return _neighbor_info->subdomain_id(); }
+  SubdomainID neighborSubdomainID() const
+  {
+    return _neighbor_info ? _neighbor_info->subdomain_id() : Moose::INVALID_BLOCK_ID;
```
Comment (lindsayad) [inline framework/include/mesh/FaceInfo.h:105]: I know that you are in the draft phase, but I wanted to check over this PR to see if it might affect my porosity jump development ...

Any reason to not do the assertion treatment here that you are doing in the other methods you've modified?

File: framework/include/utils/PiecewiseByBlockLambdaFunctor.h [hunk 2]
```diff
@@ -261,6 +261,14 @@ PiecewiseByBlockLambdaFunctor<T>::evaluate(const Moose::FaceArg & face,
...
   using namespace Moose::FV;
   mooseAssert(state == 0, "Only current time state supported.");
+
+  if (face.fi->boundaryIDs().size())
+  {
+    Moose::SingleSidedFaceArg ssfa = {
+        face.fi, face.limiter_type, face.elem_is_upwind, face.correct_skewness, face.elem_sub_id};
+    return this->evaluate(ssfa, 0);
+  }
+
```
Comment (lindsayad) [inline framework/include/utils/PiecewiseByBlockLambdaFunctor.h:271]: I'm not a fan of this. You can have internal sidesets that may be totally unrelated to the caller of this evaluation

File: framework/src/variables/MooseVariableFV.C [hunk 3]
```diff
@@ -532,12 +525,7 @@ MooseVariableFV<OutputType>::getNeighborValue(const Elem * const neighbor,
   if (neighbor && this->hasBlocks(neighbor->subdomain_id()))
     return getElemValue(neighbor);
   else
-    // If we don't have a neighbor, then we're along a boundary
-    // Linear interpolation: face_value = (elem_value + neighbor_value) / 2. Note that weights of
-    // 1/2 are perfectly appropriate here because we can arbitrarily put our ghost cell centroid
-    // anywhere and by convention we locate it such that a line drawn between the ghost cell
-    // centroid and the element centroid is perfectly bisected by the face centroid
-    return 2. * getBoundaryFaceValue(fi) - elem_value;
+    return getBoundaryFaceValue(fi);
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:528]: I feel like an error here would be better in the spirit of this PR?

File: framework/src/variables/MooseVariableFV.C [hunk 4]
```diff
@@ -632,7 +621,8 @@ MooseVariableFV<OutputType>::getExtrapolatedBoundaryFaceValue(const FaceInfo & f
   ADReal boundary_value;
   const auto & tup = Moose::FV::determineElemOneAndTwo(fi, *this);
   const Elem * const elem = std::get<0>(tup);
-  if (_two_term_boundary_expansion)
+
+  if (two_term_expansion)
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:625]: Maybe I'll find out later, but why this change?

File: framework/src/variables/MooseVariableFV.C [hunk 5]
```diff
@@ -825,7 +817,13 @@ MooseVariableFV<OutputType>::evaluate(const SingleSidedFaceArg & face,
   const FaceInfo * const fi = face.fi;
   mooseAssert(fi, "The face information must be non-null");
   if (isExtrapolatedBoundaryFace(*fi).first)
-    return getExtrapolatedBoundaryFaceValue(*fi);
+  {
+    bool linear_extrapolation = true;
+    if (face.limiter_type == Moose::FV::LimiterType::Upwind && face.elem_is_upwind)
+      linear_extrapolation = false;
+
+    return getExtrapolatedBoundaryFaceValue(*fi, linear_extrapolation);
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:825]: Ah I see. Nice!!

**Review by lindsayad — CHANGES_REQUESTED** [review]
I'm a fan of what I'm seeing!!

**Comment by grmnptr** [comment]
Got it, thanks for the initial review! 
I probably won't be able to push this through (wil ltry though) due to leaving end of next week. 
So feel free to venture forth with the porosity jump PR and I'll just rebase and resolve the conflicts if we have any.

**Comment by lindsayad** [comment]
Hmm, the thing is that there are some concepts in this PR that I will want to have when doing the porosity jump stuff. Would you want to hand this off sometime between now and when you leave? I can take off from wherever you leave off.

**Comment by grmnptr** [comment]
Sounds good to me! I'll try to push this to a nicer place till next Thursday. Then you can take it over! The issue is that with the ghost cells gone we have some freedom in the boundary treatments, and I am trying to pick a  good one (so I am exploring a few options at the moment).

File: framework/src/variables/MooseVariableFV.C [hunk 6]
```diff
@@ -734,28 +723,30 @@ MooseVariableFV<OutputType>::adGradSln(const FaceInfo & fi, const bool correct_s
...
+
+  // We only need nonorthogonal correctors in 2+ dimensions
+  if (_mesh.dimension() > 1)
+  {
+    const auto & interpolated_gradient = uncorrectedAdGradSln(fi, correct_skewness);
+    face_grad += interpolated_gradient * (fi.normal() - fi.dCN() / delta);
+  }
 
-  return face_grad;
+  return face_grad * fi.normal();
```
Comment (grmnptr) [inline framework/src/variables/MooseVariableFV.C:749]: This might need refinement to get the correct gradient. Now it focuses to get the surface normal gradient.

**Comment by grmnptr** [comment]
Hey @lindsayad , I am handing this off now. Feel free to grab anything from this PR to build yours. I'll come back to this in 3 weeks and resolve conflicts if we have any.

**Comment by lindsayad** [comment]
sounds good!

**Comment by grmnptr** [comment]
Okay, before the next push, I'll put some notes here about the tests which got regolded:

`markers/error_fraction_marker.fv`: Considering that an advection problem is at hand and a dirichlet BC is defined on the outflow boundary, I think the changes in the error distribution are reasonable donsidering the changing FVAdvection kernel. Not the dirichlet boundary condition is respected in the advection kernel as well instead of upwinding the cell value. 

`fvkernels/fv_adapt.adapt`: The non-orthogonal corrector changed which modified the gradients on the faces. This can cause 1e-4 errors on adaptively refined meshes.

**Comment by grmnptr** [comment]
Before the next push, just a note why the `test:finite_volume/fviks/convection.convection_correlation/channel` and 
 `test:finite_volume/fviks/convection.convection_correlation/cavity` got regolded. This is actually a bug fix. The issue was that the interface between solid and fluid was not treated properly. It enforced the dirichlet boundary condition for velocity with the -extrapolate then interpolate back- logic which was false considering that in this case it used an actual cell on the other side instead of a ghost cell. Now it is enforcing correct Dirichlet condition on the interface. Checked numerically the corresponding terms.

**Comment by grmnptr** [comment]
Before the next push, just noting that I regolded `test:finite_volume/pins/channel-flow/heated.solid-fluid-block` because it used linear extrapolation on the outflow boundary even with upwind for energy. Now it gives the upwind value as expected.

File: framework/src/variables/MooseVariableFV.C (hunk 3 above)
Comment (grmnptr) [reply framework/src/variables/MooseVariableFV.C]: I deleted this function in general, no need to wrap `elemValue` anymore.

File: framework/include/utils/PiecewiseByBlockLambdaFunctor.h (hunk 2 above)
Comment (grmnptr) [reply framework/include/utils/PiecewiseByBlockLambdaFunctor.h]: I added a different condition which is more robust. By the way it is amazing how every comment of this preliminary PR pointed to things that actually caused issues during the testing phase.

File: framework/include/mesh/FaceInfo.h (hunk 1 above)
Comment (grmnptr) [reply framework/include/mesh/FaceInfo.h:105]: We should allow this because I think (I might be wrong here) in certain cases the subdomain IDs are used to identify if we are on a functor boundary or not.

**Comment by grmnptr** [comment]
I'll profile this today to check changes in the memory/cpu footprint.

**Comment by grmnptr** [comment]
In terms of CPU footprint I just used `time` and ran the second longest non-mms test in the NS module three times in a row for an average (using one processor):
```
Devel: 9.208 s
With this PR: 8.463 s
```

**Comment by grmnptr** [comment]
Just to prove this the same problem with with `Mesh/uniform_refine=1` (40k dofs)  gives the following results (averaged over 3 runs):
```
Devel: 43.360 s
Current PR:  40.602 s
```
Old perf graph:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                Section                               | Calls |   Self(s)  |   Avg(s)   |    %   | Mem(MB) |  Total(s)  |   Avg(s)   |    %   | Mem(MB) |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| NavierStokesTestApp (main)                                           |     1 |      0.005 |      0.005 |   0.01 |       2 |     43.128 |     43.128 | 100.00 |     276 |
|   Action::SetupMeshAction::Mesh::SetupMeshAction::act::setup_mesh    |     1 |      0.001 |      0.001 |   0.00 |       0 |      0.001 |      0.001 |   0.00 |       0 |
|   Action::SetupMeshAction::Mesh::SetupMeshAction::act::set_mesh_base |     2 |      0.000 |      0.000 |   0.00 |       0 |      0.000 |      0.000 |   0.00 |       0 |
|   MooseApp::executeMeshGenerators                                    |     1 |      0.000 |      0.000 |   0.00 |       0 |      0.000 |      0.000 |   0.00 |       0 |
|   FEProblem::outputStep                                              |     3 |      0.019 |      0.006 |   0.04 |       0 |      0.109 |      0.036 |   0.25 |       5 |
|     Exodus::outputStep                                               |     3 |      0.076 |      0.025 |   0.18 |       5 |      0.076 |      0.025 |   0.18 |       5 |
|   Transient::PicardSolve                                             |     2 |      0.001 |      0.001 |   0.00 |       0 |     41.913 |     20.957 |  97.18 |     202 |
|     FEProblem::outputStep                                            |     2 |      0.013 |      0.007 |   0.03 |       0 |      0.013 |      0.007 |   0.03 |       0 |
|     FEProblem::solve                                                 |     2 |     12.149 |      6.075 |  28.17 |      10 |     41.714 |     20.857 |  96.72 |     202 |
|       FEProblem::computeResidualInternal                             |     2 |      0.000 |      0.000 |   0.00 |       0 |      2.921 |      1.461 |   6.77 |     146 |
|         PINSFVRhieChowInterpolator::execute                          |     2 |      0.929 |      0.465 |   2.16 |      83 |      0.929 |      0.465 |   2.16 |      83 |
|       FEProblem::computeResidualInternal                             |     9 |      0.000 |      0.000 |   0.00 |       0 |     12.859 |      1.429 |  29.82 |       1 |
|         PINSFVRhieChowInterpolator::execute                          |     9 |      4.020 |      0.447 |   9.32 |       1 |      4.020 |      0.447 |   9.32 |       1 |
|       FEProblem::computeJacobianInternal                             |     7 |      0.000 |      0.000 |   0.00 |       0 |     13.784 |      1.969 |  31.96 |      45 |
|         PINSFVRhieChowInterpolator::execute                          |     7 |      3.179 |      0.454 |   7.37 |       0 |      3.179 |      0.454 |   7.37 |       0 |
|     FEProblem::computeUserObjects                                    |     2 |      0.185 |      0.092 |   0.43 |       0 |      0.185 |      0.092 |   0.43 |       0 |
|   Transient::final                                                   |     1 |      0.000 |      0.000 |   0.00 |       0 |      0.006 |      0.006 |   0.02 |       0 |
|     FEProblem::outputStep                                            |     1 |      0.006 |      0.006 |   0.01 |       0 |      0.006 |      0.006 |   0.01 |       0 |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

New perf graph:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                Section                               | Calls |   Self(s)  |   Avg(s)   |    %   | Mem(MB) |  Total(s)  |   Avg(s)   |    %   | Mem(MB) |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| NavierStokesTestApp (main)                                           |     1 |      0.003 |      0.003 |   0.01 |       2 |     40.540 |     40.540 | 100.00 |     278 |
|   Action::SetupMeshAction::Mesh::SetupMeshAction::act::setup_mesh    |     1 |      0.001 |      0.001 |   0.00 |       0 |      0.001 |      0.001 |   0.00 |       0 |
|   Action::SetupMeshAction::Mesh::SetupMeshAction::act::set_mesh_base |     2 |      0.000 |      0.000 |   0.00 |       0 |      0.000 |      0.000 |   0.00 |       0 |
|   MooseApp::executeMeshGenerators                                    |     1 |      0.000 |      0.000 |   0.00 |       0 |      0.000 |      0.000 |   0.00 |       0 |
|   FEProblem::outputStep                                              |     3 |      0.019 |      0.006 |   0.05 |       0 |      0.107 |      0.036 |   0.26 |       1 |
|     Exodus::outputStep                                               |     3 |      0.073 |      0.024 |   0.18 |       1 |      0.073 |      0.024 |   0.18 |       1 |
|   Transient::PicardSolve                                             |     2 |      0.001 |      0.001 |   0.00 |       0 |     39.321 |     19.660 |  96.99 |     187 |
|     FEProblem::outputStep                                            |     2 |      0.013 |      0.006 |   0.03 |       0 |      0.013 |      0.006 |   0.03 |       0 |
|     FEProblem::solve                                                 |     2 |     12.224 |      6.112 |  30.15 |       8 |     39.123 |     19.562 |  96.50 |     187 |
|       FEProblem::computeResidualInternal                             |     2 |      0.000 |      0.000 |   0.00 |       0 |      2.610 |      1.305 |   6.44 |     133 |
|         PINSFVRhieChowInterpolator::execute                          |     2 |      0.868 |      0.434 |   2.14 |      70 |      0.868 |      0.434 |   2.14 |      70 |
|       FEProblem::computeResidualInternal                             |     9 |      0.000 |      0.000 |   0.00 |       0 |     11.517 |      1.280 |  28.41 |       1 |
|         PINSFVRhieChowInterpolator::execute                          |     9 |      3.760 |      0.418 |   9.28 |       1 |      3.760 |      0.418 |   9.28 |       1 |
|       FEProblem::computeJacobianInternal                             |     7 |      0.000 |      0.000 |   0.00 |       0 |     12.772 |      1.825 |  31.50 |      45 |
|         PINSFVRhieChowInterpolator::execute                          |     7 |      2.984 |      0.426 |   7.36 |       0 |      2.984 |      0.426 |   7.36 |       0 |
|     FEProblem::computeUserObjects                                    |     2 |      0.183 |      0.092 |   0.45 |       0 |      0.183 |      0.092 |   0.45 |       0 |
|   Transient::final                                                   |     1 |      0.000 |      0.000 |   0.00 |       0 |      0.007 |      0.007 |   0.02 |       0 |
|     FEProblem::outputStep                                            |     1 |      0.007 |      0.007 |   0.02 |       0 |      0.007 |      0.007 |   0.02 |       0 |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by grmnptr** [comment]
The heap profile:
```
Devel: 4816 MB
Current PR: 4039 MB
```
The main difference come from: 

New:
```
PetscMallocAlign
2435.37MB (60.29%)
```
Old:
```
PetscMallocAlign
3029.03MB (62.89%)
```
I am not so sure why we see such a big difference. The difference in the `MooseMesh::buildFiniteVolumeInfo` is minimal. Maybe the lack of ghost cells resulted in fewer entries in the Jacobian or tighter band? I'm attaching the heap profiles just in case.
[new_heap.pdf](https://github.com/idaholab/moose/files/9903882/new_heap.pdf)
[old_memory.pdf](https://github.com/idaholab/moose/files/9903885/old_memory.pdf)

File: framework/include/utils/PiecewiseByBlockLambdaFunctor.h [hunk 7]
```diff
@@ -261,7 +275,15 @@ PiecewiseByBlockLambdaFunctor<T>::evaluate(const Moose::FaceArg & face,
 {
   using namespace Moose::FV;
   mooseAssert(state == 0, "Only current time state supported.");
-  return interpolate(*this, face);
+
+  if (isInternalFace(*face.fi))
+  {
+    return interpolate(*this, face);
+  }
```
Comment (lindsayad) [inline framework/include/utils/PiecewiseByBlockLambdaFunctor.h:282]:
```suggestion
  if (isInternalFace(*face.fi))
    return interpolate(*this, face);
```

File: framework/include/utils/PiecewiseByBlockLambdaFunctor.h [hunk 8]
```diff
@@ -261,7 +275,15 @@ PiecewiseByBlockLambdaFunctor<T>::evaluate(const Moose::FaceArg & face,
...
+
+  Moose::SingleSidedFaceArg ssfa = {
+      face.fi, face.limiter_type, face.elem_is_upwind, face.correct_skewness, face.elem_sub_id};
```
Comment (lindsayad) [inline framework/include/utils/PiecewiseByBlockLambdaFunctor.h:285]: Instead of using `face.elem_sub_id` always, we should base this off of what side of the interface this functor is defined on. It may only be on the neighbor side instead of the elem side

File: framework/src/fvkernels/FVDiffusion.C [hunk 9]
```diff
@@ -48,15 +48,26 @@ FVDiffusion::FVDiffusion(const InputParameters & params)
...
+                _coeff(neighborFromFace()),
+                *_face_info,
+                true);
+  // Else we use linear inter/extrapolation using regular face args or single-sided
+  // face arguments
+  else
+  {
+    const auto face = singleSidedFaceArg();
+    coeff = _coeff(face);
+  }
```
Comment (lindsayad) [inline framework/src/fvkernels/FVDiffusion.C:70]: 👍 for now. In the future, as we talked about, we will make it so kernel developers don't have to do this `if-else` branching, but rather we will handle it in the functors themselves based on the blocks of the consumer

File: framework/src/variables/MooseVariableFV.C [hunk 10]
```diff
@@ -705,10 +690,9 @@ MooseVariableFV<OutputType>::uncorrectedAdGradSln(const FaceInfo & fi,
   mooseError("MooseVariableFV::uncorrectedAdGradSln only supported for global AD indexing");
 #endif
 
-  auto tup = Moose::FV::determineElemOneAndTwo(fi, *this);
-  const Elem * const elem_one = std::get<0>(tup);
-  const Elem * const elem_two = std::get<1>(tup);
-  const bool elem_one_is_fi_elem = std::get<2>(tup);
+  bool var_defined_on_elem = fi.varDefinedOnElem(this->name());
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:693]:
```suggestion
  const bool var_defined_on_elem = fi.varDefinedOnElem(this->name());
```

File: framework/src/variables/MooseVariableFV.C [hunk 11]
```diff
@@ -805,14 +793,13 @@ MooseVariableFV<OutputType>::evaluate(const FaceArg & face,
...
-    return getExtrapolatedBoundaryFaceValue(*fi);
-  else if (isInternalFace(*fi))
+  if (isInternalFace(*fi))
     return Moose::FV::interpolate(*this, face);
   else
   {
-    mooseAssert(isDirichletBoundaryFace(*fi), "We've run out of face types");
-    return getDirichletBoundaryFaceValue(*fi);
+    Moose::SingleSidedFaceArg ssfa = {
+        face.fi, face.limiter_type, face.elem_is_upwind, face.correct_skewness, face.elem_sub_id};
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:801]: As for the PBBLF, let's be sure that we are providing the correct subdomain ID to the SSF. E.g. let's make sure the variable is defined on the subdomain ID

File: modules/navier_stokes/include/utils/CellCenteredMapFunctor.h [hunk 12]
```diff
@@ -109,31 +109,7 @@ class CellCenteredMapFunctor : public Moose::FunctorBase<T>, public Map
...
-                                                   true,
-                                                   elem_from_face.correct_skewness,
-                                                   elem_from_face.sub_id});
-    const auto boundary_value = (*this)(boundary_face);
-    // Linear interpolation: face_value = (elem_value + neighbor_value) / 2. Note that weights of
-    // 1/2 are perfectly appropriate here because we can arbitrarily put our ghost cell centroid
-    // anywhere and by convention we locate it such that a line drawn between the ghost cell
-    // centroid and the element centroid is perfectly bisected by the face centroid
-    return 2. * boundary_value - elem_value;
+    return (*this)(ElemArg({elem_from_face.elem, elem_from_face.correct_skewness}));
```
Comment (lindsayad) [inline modules/navier_stokes/include/utils/CellCenteredMapFunctor.h:112]: This is nice!

**Review by lindsayad — CHANGES_REQUESTED** [review]

File: framework/include/mesh/FaceInfo.h [hunk 13]
```diff
@@ -87,14 +87,23 @@ class FaceInfo
...
+  }
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/include/mesh/FaceInfo.h:106]: this is a single line though

**Comment by GiudGiud** [comment]
There should be a way to get PETSc to give stats about the matrix for a large case too

File: framework/include/mesh/FaceInfo.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/mesh/FaceInfo.h:106]: I should be clear ... if the curly braces plus the statement lines exceed one line, let's move it out of the class definition. I'm not always the best at following this myself, but it helps with developers trying to peruse APIs to not have to wade through an excess of lines

[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/include/mesh/FaceInfo.h:106]: Got it, moved them!

File: framework/include/utils/GreenGaussGradient.h [hunk 14]
```diff
@@ -254,22 +254,30 @@ greenGaussGradient(const FaceArg & face_arg,
...
-    Moose::FV::interpolate(
-        Moose::FV::InterpMethod::Average, face_gradient, grad_elem, grad_neighbor, fi, true);
-
-    // Perform orthogonality correction
     const auto & value_elem = functor(elem_arg);
     const auto & value_neighbor = functor(neighbor_arg);
 
-    face_gradient += outer_product(
-        fi.eCN(), (value_neighbor - value_elem) / fi.dCNMag() - face_gradient * fi.eCN());
+    VectorValue<T> face_gradient = (value_neighbor - value_elem) / fi.dCNMag() * fi.eCN();
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply framework/include/utils/GreenGaussGradient.h:260]: Added comment!

File: framework/src/fvkernels/FVDiffusion.C (hunk 9 above)
Comment (grmnptr) [reply framework/src/fvkernels/FVDiffusion.C:70]: Roger that!

File: framework/include/utils/PiecewiseByBlockLambdaFunctor.h (hunk 8 above)
Comment (grmnptr) [reply framework/include/utils/PiecewiseByBlockLambdaFunctor.h:285]: Added a conditional subdomain ID based on the `hasBlock(elemID)`.

File: framework/src/variables/MooseVariableFV.C (hunk 11 above)
Comment (grmnptr) [reply framework/src/variables/MooseVariableFV.C:801]: Added a conditional subdomain ID based on if the variable is defined on the element!

**Comment by grmnptr** [comment]
I decreased the number of cells to have 50 DoFs in the system. I used the following petsc options:
```
petsc_options_iname = '-pc_type -pc_factor_shift_type'
petsc_options_value = 'lu NONZERO'
petsc_options = '-ksp_view_pmat'
```
and the matrices are exactly the same. I even added non-homogeneous initial conditions. Is it possible that petsc discards zero entries when it prints the matrices?

**Comment by lindsayad** [comment]
No it doesn't. It keeps whatever entries you allocate even if they are 0

**Comment by lindsayad** [comment]
Thanks for looking into it @grmnptr. It seems like it's a mystery for now, but it's not really that relevant to me as to whether this PR should go in, especially if we're luckily decreasing memory consumption. 

I don't know whether @jedbrown would have any ideas about why seemingly the exact same matrix leads to much more memory consumption by LU.

**Review by lindsayad — DISMISSED** [review]
This looks great to me. An excellent refactor. Thanks for your hard work @grmnptr. @GiudGiud do you want to review this?

**Comment by grmnptr** [comment]
Got it thanks! I have no idea then. The convergence history in terms of residual norms is the same, the solutions are the same. Just the memory/cpu usage is different. I was suspecting more zero entries in the old version but apparently we don't even have that. I compared matrices by `diff`ing the output of `-ksp_view_pmat`.

**Comment by GiudGiud** [comment]
I ll take a look

looks like there's some easy cleanups to do

**Comment by grmnptr** [comment]
Ok I modified the anisotropic diffusion kernel in the framework as well. I think I am ready for @GiudGiud 's review.

**Comment by grmnptr** [comment]
Hey @GiudGiud, could you give me a review on this?

File: framework/include/mesh/ElemInfo.h [hunk 15]
```diff
@@ -27,29 +27,14 @@ class ElemInfo
...
-
-  /// Construct an empty shell for a ghost element
-  ElemInfo();
-
-  /// Initialize the ghost element using a real ElemInfo and a FaceInfo
-  void initialize(const ElemInfo & ei, const FaceInfo & fi);
-
-  /// Check if the corresponding element is a ghost
-  bool isGhost() const { return _elem == nullptr; }
+  ElemInfo() : _elem(nullptr) {}
```
Comment (GiudGiud) [inline framework/include/mesh/ElemInfo.h:30]: docstring

File: framework/include/mesh/FaceInfo.h [hunk 16]
```diff
@@ -159,6 +159,18 @@ class FaceInfo
    */
   void computeCoefficients(const ElemInfo * const neighbor_info);
 
+  /**
+   * Computes the interpolation weights and similar quantities with the assumption
+   * that the face is on a boundary.
+   */
+  void computeCoefficients();
```
Comment (GiudGiud) [inline framework/include/mesh/FaceInfo.h:166]: can you call it computeBoundaryCoefficients ?
Otherwise it s easy to use the wrong one if you dont read the docstring

File: framework/src/fvkernels/FVAnisotropicDiffusion.C [hunk 17]
```diff
@@ -57,12 +57,21 @@ FVAnisotropicDiffusion::computeQpResidual()
...
-              true);
+  // If we are on internal faces, we interpolate the diffusivity as usual
+  if (_var.isInternalFace(*_face_info))
+    interpolate(_coeff_interp_method,
+                coeff,
+                _coeff(elemFromFace()),
+                _coeff(neighborFromFace()),
+                *_face_info,
+                true);
+  // Else we just use the boundary values (which can be various depending on how the diffusion
```
Comment (GiudGiud) [inline framework/src/fvkernels/FVAnisotropicDiffusion.C:68]:
```suggestion
  // Else we just use the boundary values (which depend on how the diffusion
```

File: framework/src/fvkernels/FVDiffusion.C [hunk 18]
```diff
@@ -48,15 +48,26 @@ FVDiffusion::FVDiffusion(const InputParameters & params)
...
+
+  // If we are on internal faces, we interpolate the diffusivity as usual
+  if (_var.isInternalFace(*_face_info))
+    interpolate(_coeff_interp_method,
+                coeff,
+                _coeff(elemFromFace()),
+                _coeff(neighborFromFace()),
+                *_face_info,
+                true);
+  // Else we just use the boundary values (which can be various depending on how the diffusion
```
Comment (GiudGiud) [inline framework/src/fvkernels/FVDiffusion.C:64]:
```suggestion
  // Else we just use the boundary values (which depend on how the diffusion
```

File: framework/src/fvkernels/FVFluxKernel.C [hunk 19]
```diff
@@ -327,8 +327,21 @@ FVFluxKernel::gradUDotNormal() const
...
 
+  const Elem * const elem = &_face_info->elem();
+  const Elem * const neighbor = _face_info->neighborPtr();
+
+  bool var_defined_on_elem = _face_info->varDefinedOnElem(_var.name());
+  bool is_internal_face = _var.isInternalFace(*_face_info);
+
+  const ADReal side_one_value = (!is_internal_face && !var_defined_on_elem)
+                                    ? _var.getBoundaryFaceValue(*_face_info)
+                                    : _var.getElemValue(elem);
```
Comment (GiudGiud) [inline framework/src/fvkernels/FVFluxKernel.C:338]: if internal face and variable not defined on element, can we take an element value?

File: framework/src/variables/MooseVariableFV.C [hunk 20]
```diff
@@ -501,6 +495,16 @@ MooseVariableFV<OutputType>::getElemValue(const Elem * const elem) const
...
   mooseError("MooseVariableFV::getElemValue only supported for global AD indexing");
 #endif
+  mooseAssert(elem,
+              "The elem shall exist! This typically occurs when the "
+              "user wants to evaluate nonexisting elements (nullptr) at physical boundaryies.");
+  mooseAssert(
+      this->hasBlocks(elem->subdomain_id()),
+      "The elem shall have the same subdomain as the variable! This typically occurs when the "
+      "user wants to evaluate the elements right next to the boundary of two variables (block "
+      "boundary). The subdomain which is quarried: " +
```
Comment (GiudGiud) [inline framework/src/variables/MooseVariableFV.C:505]:
```suggestion
      "boundary). The subdomain which is querried: " +
```

File: framework/src/variables/MooseVariableFV.C [hunk 21]
```diff
@@ -501,6 +495,16 @@ MooseVariableFV<OutputType>::getElemValue(const Elem * const elem) const
 #ifndef MOOSE_GLOBAL_AD_INDEXING
   mooseError("MooseVariableFV::getElemValue only supported for global AD indexing");
 #endif
+  mooseAssert(elem,
+              "The elem shall exist! This typically occurs when the "
+              "user wants to evaluate nonexisting elements (nullptr) at physical boundaryies.");
```
Comment (GiudGiud) [inline framework/src/variables/MooseVariableFV.C:500]:
```suggestion
              "user wants to evaluate non-existing elements (nullptr) at physical boundaries.");
```

File: framework/src/variables/MooseVariableFV.C [hunk 22]
```diff
@@ -501,6 +495,16 @@ MooseVariableFV<OutputType>::getElemValue(const Elem * const elem) const
...
+  mooseAssert(
+      this->hasBlocks(elem->subdomain_id()),
+      "The elem shall have the same subdomain as the variable! This typically occurs when the "
```
Comment (GiudGiud) [inline framework/src/variables/MooseVariableFV.C:503]:
```suggestion
      "The variable should be defined on the element's subdomain! This typically occurs when the "
```

File: framework/src/mesh/FaceInfo.C [hunk 23]
```diff
@@ -93,3 +103,15 @@ FaceInfo::skewnessCorrectionVector() const
 
   return _face_centroid - r_intersection;
 }
+
+bool
+FaceInfo::varDefinedOnElem(const std::string & var_name) const
+{
+  auto it = _face_types_by_var.find(var_name);
```
Comment (GiudGiud) [inline framework/src/mesh/FaceInfo.C:110]: with this indexing by name, calling variables vel_x vel_y vel_z will be (likely infinitesimally) slower than u, v, w

Comment (GiudGiud) [reply framework/src/mesh/FaceInfo.C:110]: I guess we ll have to check profiles to see if this lookup done everywhere matters

File: modules/navier_stokes/src/fvkernels/PINSFVMomentumDiffusion.C [hunk 24]
```diff
@@ -52,15 +52,24 @@ PINSFVMomentumDiffusion::computeStrongResidual()
...
   // Compute the diffusion driven by the velocity gradient
   // Interpolate viscosity divided by porosity on the face
   ADReal mu_face;
-  interpolate(Moose::FV::InterpMethod::Average, mu_face, mu_elem, mu_neighbor, *_face_info, true);
+
+  const auto mu_elem = has_elem ? _mu(elem_face) : _mu(neighbor_face);
+  const auto eps_elem = has_elem ? _eps(elem_face) : _eps(neighbor_face);
+
+  ADReal mu_neighbor;
+  ADReal eps_neighbor;
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PINSFVMomentumDiffusion.C:64]: remove and put it inside if?

File: test/tests/mesh/face_info/gold/face_info_two_region_quads_out_face_info_3_0001.csv [hunk 25]
```diff
@@ -1,13 +1,13 @@
...
-1,0.5,1.5,0,2,2,0.5,2,0,8,0.5,2.5,0,-1,0,0,1,-0,2
-1,0.5,1.5,0,2,3,0,1.5,0,9,-0.5,1.5,0,-1,0,-1,0,0,2
-1,1.5,1.5,0,3,1,2,1.5,0,10,2.5,1.5,0,-1,0,1,0,0,2
-1,1.5,1.5,0,3,2,1.5,2,0,11,1.5,2.5,0,-1,0,0,1,-0,2
+1,0.5,0.5,0,0,0,0.5,0,0,0,1.7976931348623e+308,1.7976931348623e+308,1.7976931348623e+308,-1,-1,-0,-1,0,2
+1,0.5,0.5,0,0,1,1,0.5,0,1,1.5,0.5,0,1,3,1,0,0,1
+1,0.5,0.5,0,0,2,0.5,1,0,2,0.5,1.5,0,2,0,-0,1,0,1
+1,0.5,0.5,0,0,3,0,0.5,0,3,1.7976931348623e+308,1.7976931348623e+308,1.7976931348623e+308,-1,-1,-1,0,0,2
+1,1.5,0.5,0,1,0,1.5,0,0,4,1.7976931348623e+308,1.7976931348623e+308,1.7976931348623e+308,-1,-1,-0,-1,0,2
+1,1.5,0.5,0,1,1,2,0.5,0,5,1.7976931348623e+308,1.7976931348623e+308,1.7976931348623e+308,-1,-1,1,0,0,2
```
Comment (GiudGiud) [inline test/tests/mesh/face_info/gold/face_info_two_region_quads_out_face_info_3_0001.csv:7]: these are huge, what is up

File: test/tests/fvkernels/mms/skewness-correction/diffusion/test.py [hunk 26]
```diff
@@ -32,6 +33,7 @@ def test(self):
         fig.save('skewness-corrected.png')
 
         for _,value in fig.label_to_slope.items():
+            print(value)
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/skewness-correction/diffusion/test.py:36]:
```suggestion
```

File: test/tests/fvkernels/mms/skewness-correction/diffusion/test.py [hunk 27]
```diff
@@ -16,6 +16,7 @@ def test(self):
         fig.save('average.png')
 
         for _,value in fig.label_to_slope.items():
+            print(value)
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/skewness-correction/diffusion/test.py:19]:
```suggestion
```

File: test/tests/fvkernels/mms/mat-advection.i [hunk 28]
```diff
@@ -1,91 +0,0 @@
...
-  [./v]
-    family = MONOMIAL
-    order = CONSTANT
-    fv = true
-  [../]
-[]
-
-[FVKernels]
-  [./advection]
-    type = FVMatAdvection
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/mat-advection.i:27]: FVMatAdvection is still here, why did you remove the test?

Can we no longer do MMS because we cant specify BCs?

File: test/tests/fvkernels/mms/mass-mom-mat-advection-diffusion/test.py [hunk 29]
```diff
@@ -0,0 +1,18 @@
...
+class TestMassMomdAvectionDiffusion(unittest.TestCase):
+    def test(self):
+        labels = ['l2_rho','l2_vel']
+        df1 = mms.run_spatial('input.i', 4, y_pp=labels, mpi=2)
+        fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        fig.plot(df1, label=labels, marker='o', markersize=8, num_fitted_points=3, slope_precision=2)
+        fig.save('mmm-advection-diffusion.png')
+
+        for _,value in fig.label_to_slope.items():
+            print(value)
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/mass-mom-mat-advection-diffusion/test.py:14]:
```suggestion
```

Comment (GiudGiud) [reply test/tests/fvkernels/mms/mass-mom-mat-advection-diffusion/test.py:14]: I m not against prints in python scripts when they are helpful for us to run them locally btw, but they need to have a message

File: test/tests/fvkernels/mms/harmonic_interpolation/test.py [hunk 30]
```diff
@@ -4,9 +4,10 @@
 
 class TestHarmonicTriangles(unittest.TestCase):
     def test(self):
-        df1 = mms.run_spatial('diffusion.i', 4, 'FVKernels/diff/coeff_interp_method=harmonic', mpi=1)
+        df1 = mms.run_spatial('diffusion.i', 5, 'FVKernels/diff/coeff_interp_method=harmonic', mpi=1)
 
         fig = mms.ConvergencePlot(xlabel='Element Size ($h$)', ylabel='$L_2$ Error')
+        print(df1)
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/harmonic_interpolation/test.py:10]:
```suggestion
```

File: test/tests/fvkernels/mms/harmonic_interpolation/test.py [hunk 31]
```diff
@@ -16,6 +17,7 @@ def test(self):
         fig.save('triangles-harmonic.png')
 
         for _,value in fig.label_to_slope.items():
+            print(value)
```
Comment (GiudGiud) [inline test/tests/fvkernels/mms/harmonic_interpolation/test.py:20]:
```suggestion
```

File: test/src/fvkernels/FVLimitedVectorAdvection.C [hunk 32]
```diff
@@ -49,7 +49,15 @@ FVLimitedVectorAdvection::computeQpResidual()
...
   const auto face = makeFace(*_face_info, _limiter_type, elem_is_upwind, faceArgSubdomains());
 
-  const auto phi_f = interpolate(_vector, face)(_index);
+  ADReal phi_f;
+
+  if (_var.isInternalFace(*_face_info))
+    phi_f = interpolate(_vector, face)(_index);
+  else
+  {
+    const auto face = makeFace(*_face_info, _limiter_type, elem_is_upwind, faceArgSubdomains());
```
Comment (GiudGiud) [inline test/src/fvkernels/FVLimitedVectorAdvection.C:58]: this is the same as above

File: modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C [hunk 33]
```diff
@@ -127,26 +127,23 @@ VolumetricFlowRate::computeFaceInfoIntegral([[maybe_unused]] const FaceInfo * fi
   const auto vel = MetaPhysicL::raw_value(_rc_uo->getVelocity(_velocity_interp_method, *fi, _tid));
   const bool correct_skewness =
       _advected_interp_method == Moose::FV::InterpMethod::SkewCorrectedAverage;
-
-  // External faces for the advected quantity
```
Comment (GiudGiud) [inline modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C:131]: why remove?

File: modules/navier_stokes/src/fvkernels/PINSFVMomentumFrictionCorrection.C [hunk 34]
```diff
@@ -70,39 +70,63 @@ PINSFVMomentumFrictionCorrection::gatherRCData(const FaceInfo & fi)
...
+    // Interpolate viscosity divided by porosity on the face
+    interpolate(Moose::FV::InterpMethod::Average,
+                diff_face,
+                friction_term_elem * geometric_factor,
+                friction_term_neighbor * geometric_factor,
+                *_face_info,
+                true);
   }
-  if (_use_Forchheimer_friction_model)
+  // If not, we use the extrapllated values of the functors on the face
```
Comment (GiudGiud) [inline modules/navier_stokes/src/fvkernels/PINSFVMomentumFrictionCorrection.C:112]:
```suggestion
  // If not, we use the extrapolated values of the functors on the face
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]
so what's the status with these MMS tests?
can we no longer impose these BCs?

**Comment by grmnptr** [comment]
Thanks @GiudGiud !!

File: framework/src/mesh/FaceInfo.C (hunk 23 above)
Comment (grmnptr) [reply framework/src/mesh/FaceInfo.C:110]: I like `u,v,w` and if we can include them in a vector variable for paraview I am open to changing them back. Also I am not a huge fan of this indexing. This might change when we introduce the consumer-dependent `isBoundary()` function to the variable and other functors.

File: test/src/vectorpostprocessors/TestFaceInfo.C [hunk 35]
```diff
@@ -63,11 +63,6 @@ TestFaceInfo::execute()
     _face_area.push_back(p->faceArea());
     _elem_element_id.push_back(p->elem().id());
     _elem_element_side.push_back(p->elemSideID());
-    // the neighbor element might be a nullptr
```
Comment (loganharbour) [inline test/src/vectorpostprocessors/TestFaceInfo.C:66]: You guys should really use a Reporter for this object

File: test/tests/fvkernels/mms/mat-advection.i (hunk 28 above)
Comment (grmnptr) [reply test/tests/fvkernels/mms/mat-advection.i:27]: I think my logic was that `FVMatAdvection` is tested at 3-4 other instances with Dirichlet Boundary conditions. The main difference is that this input had `FVMatAdvectionFunctionBC` which I removed since it entirely relied on boundary ghost cells by not exactly enforcing the DirichletBC.

File: test/src/vectorpostprocessors/TestFaceInfo.C (hunk 35 above)
Comment (grmnptr) [reply test/src/vectorpostprocessors/TestFaceInfo.C:66]: Good idea! For now, however I'd like to keep it as is. Isn't a VPP a Reporter underneath?

**Comment by grmnptr** [comment]
Yeah I deleted the `FVAdvectionFunctionBC` and `FVMatAdvectionFunctionBC` because they computed the exact solution on the ghost cell plus on the boundary cell and interpolated between the two to get the the boundary value. This was to prevent ill-defined systems for advection-only cases in 1D. Since we don't have ghost cells anymore and we have a nice DirichletBC which can enforce the BC direcly, I decided to delete the tests as well. The same kernels are tested in other `mms` cases. The coverage didn't seem to decrease.

File: test/src/vectorpostprocessors/TestFaceInfo.C (hunk 35 above)
Comment (loganharbour) [reply test/src/vectorpostprocessors/TestFaceInfo.C:66]: Yeah - but with more context/other information. Looking at these diffs is miserable... looking at a json diff is wonderful

**Comment by grmnptr** [comment]
These were `exodiff` tests...

**Comment by GiudGiud** [comment]
yeah looks like the mms tests that were removed are for framework FV and NavierStokes cns

File: framework/include/mesh/FaceInfo.h (hunk 16 above)
Comment (grmnptr) [reply framework/include/mesh/FaceInfo.h:166]: Sure, good idea! Will rename it in the next commit!

File: modules/navier_stokes/src/fvkernels/PINSFVMomentumDiffusion.C (hunk 24 above)
Comment (grmnptr) [reply modules/navier_stokes/src/fvkernels/PINSFVMomentumDiffusion.C:64]: We can't  do it. This part at the end of the function uses it too so it cannot be defined in an if-else statement:
```
ADReal coeff_face;
  const auto coeff_elem = mu_elem / eps_elem * _var(elem_face);
  if (onBoundary(*_face_info))
    coeff_face = coeff_elem;
  else
  {
    const auto coeff_neighbor = mu_neighbor / eps_neighbor * _var(neighbor_face);
    interpolate(Moose::FV::InterpMethod::Average,
                coeff_face,
                coeff_elem,
                coeff_neighbor,
                *_face_info,
                true);
  }
```

**Comment by jedbrown** [comment]
@lindsayad Factorization should be deterministic so I would not expect a discrepancy. Is there a qualitative difference between PETSc's default solver and an external solver (like `-pc_factor_mat_solver_type umfpack`)? (Umfpack will be more efficient, but do the two "identical" matrices factor to use the same amount of memory?) Can you reduce and share `-ksp_view` output (which reports fill in the factorization).

File: framework/src/variables/MooseVariableFV.C [hunk 36]
```diff
@@ -501,6 +495,16 @@ MooseVariableFV<OutputType>::getElemValue(const Elem * const elem) const
...
   mooseError("MooseVariableFV::getElemValue only supported for global AD indexing");
 #endif
+  mooseAssert(elem,
+              "The elem shall exist! This typically occurs when the "
+              "user wants to evaluate non-existing elements (nullptr) at physical boundaries.");
+  mooseAssert(
+      this->hasBlocks(elem->subdomain_id()),
+      "The variable should be defined on the element's subdomain! This typically occurs when the "
+      "user wants to evaluate the elements right next to the boundary of two variables (block "
+      "boundary). The subdomain which is querried: " +
```
Comment (lindsayad) [inline framework/src/variables/MooseVariableFV.C:505]:
```suggestion
      "boundary). The subdomain which is queried: " +
```

File: framework/src/mesh/FaceInfo.C (hunk 23 above)
Comment (lindsayad) [reply framework/src/mesh/FaceInfo.C:110]: Hmm I should have commented on this earlier. I just searched through the diff (without expanding every file admittedly), and the usage of this I found in `uncorrectedAdGradSln` could be replaced by `this->hasBlocks(&fi.elem())` which would remove the string comparisons. Does this new method give us something that we didn't have before in other locations of the diff?

**Review by lindsayad — CHANGES_REQUESTED** [review]

**Comment by lindsayad** [comment]
> The CNS test was removed because without ghost cells the HLLC kernels are only usable with HLLC boundary conditions. I added a diffusion term in one of them to still test the capability of having second order accuracy with some diffusion included.

@grmnptr and I talked about this one extensively. I am fully satisfied with what he did for the CNS MMS testing

File: framework/src/mesh/FaceInfo.C (hunk 23 above)
Comment (grmnptr) [reply framework/src/mesh/FaceInfo.C:110]: No, these are the only locations where this routine is used. I was not aware of this `hasBlocks` approach, I'll change this and get rid of this method.

**Review by GiudGiud — CHANGES_REQUESTED** [review]
There's two relatively large diffs:

- the convection fviks
- the heated channel in PINSFV with the solid phase

I tracked down the later to gradUDotNormal in FVDiffusion on T_solid but maybe you already know where it's from

File: modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/heated/tests [hunk 37]
```diff
@@ -85,7 +98,10 @@
     ad_indexing_type = 'global'
     valgrind = HEAVY
     design = 'PINSFVEnergyAmbientConvection.md'
-    cli_args = "Variables/inactive='' AuxVariables/inactive='T_solid' FVKernels/inactive='' FVKernels/energy_convection/block='2' FVKernels/solid_energy_convection/block='2' FVKernels/energy_advection/advected_interp_method='upwind' FVBCs/inactive='' Outputs/file_base='rc-heated-solid-fluid-block'"
+    cli_args = "Variables/inactive='' AuxVariables/inactive='T_solid' FVKernels/inactive='' "
+               "FVKernels/energy_convection/block='2' FVKernels/solid_energy_convection/block='2' "
+               "FVKernels/energy_advection/advected_interp_method='upwind' FVBCs/inactive='' "
+               "Outputs/file_base='rc-heated-solid-fluid-block'"
   []
   [solid-fluid-block-action]
```
[the remark this answers is not in the document]
Comment (grmnptr) [reply modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/heated/tests:106]: Nice catch! Will add the symlink!

**Comment by GiudGiud** [comment]
I d rather you rewrite history so this extra gold file never existed but otherwise this is good to go!

**Review by lindsayad — DISMISSED** [review]

**Comment by grmnptr** [comment]
I'll rewrite history and check what `-ksp_view` will give us to understand the change.

**Comment by grmnptr** [comment]
The results of the run with `-ksp_view` are:= the same for both `devel` and current `PR`:
```
KSP Object: 1 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=10000, initial guess is zero
  tolerances:  relative=1e-05, absolute=1e-50, divergence=1e+100
  right preconditioning
  using UNPRECONDITIONED norm type for convergence test
PC Object: 1 MPI processes
  type: lu
    out-of-place factorization
    tolerance for zero pivot 2.22045e-14
    using diagonal shift to prevent zero pivot [NONZERO]
    matrix ordering: nd
    factor fill ratio given 5., needed 8.43492
      Factored matrix follows:
        Mat Object: 1 MPI processes
          type: seqaij
          rows=10000, cols=10000, bs=5
          package used to perform factorization: petsc
          total: nonzeros=2962817, allocated nonzeros=2962817
            using I-node routines: found 5958 nodes, limit used is 5
  linear system matrix = precond matrix:
  Mat Object: () 1 MPI processes
    type: seqaij
    rows=10000, cols=10000, bs=5
    total: nonzeros=351256, allocated nonzeros=620100
    total number of mallocs used during MatSetValues calls=0
      using I-node routines: found 6000 nodes, limit used is 5
```
At this point I am a bit confused, I still see CPU/memory gains with the most commong NS settings. But I think I'll just let this go for now.

**Review by GiudGiud — APPROVED** [review]

**Comment by lindsayad** [comment]
Nice work @grmnptr !
