### PR TITLE
Fix FV loops to work with multiple NL systems

### LINKED ISSUE #23174: FVKernels don't work with multiple nonlinear systems.
## Bug Description
If we have two nonlinear systems and FV kernels on both, we end up querying every kernel (for all systems) in the threaded face loop evaluation. This leads to incorrect results.

## Steps to Reproduce
Try creating a 2-variable, 2-system FV diffusion problem and manually inspect the residuals. 

## Impact
Prevents the effective utilization of FV functionalities with multiple systems.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #23174

### CODE REVIEW

File: modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C [hunk 1]
```diff
@@ -79,6 +79,10 @@ INSFVRhieChowInterpolator::validParams()
       "supplied when the mesh dimension is greater than 2. It represents the on-diagonal "
       "coefficients for the 'z' component velocity, solved "
       "via the Navier-Stokes equations.");
+  params.addParam<NonlinearSystemName>("mass_momentum_system",
+                                       "0",
```
Comment (lindsayad) [inline modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:83]: Is this the default name that you want? The default nonlinear system name for our standard monolithic solves is `"nl0"`

Comment (lindsayad) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:83]: I just think it's a bit odd that the default name is a number

Comment (grmnptr) [reply modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C:83]: I think I think `_fe_problem.nlSysNum` tries to parse it to a number and if it can it will select the number. I'll switch to the default you mentioned! Commit incoming.

**Review by lindsayad — APPROVED** [review]
