### PR TITLE
Fixed indexing in ACBarrierFunction.C to prevent indexing outisde of …

### LINKED ISSUE #17541: ACBarrierFunction.C giving segmentation fault when coupling with TensorMechanics

### PR DESCRIPTION
**Pull request by lr272727**
Reason:
ACBarrierFunction.C gives segmentation fault when coupled with TensorMechanics. The addition of displacement variables causes computeQpOffDiagJacobian to index outside of _vals, which only contains order parameters. 

Design:
Only allow for indexing over length of _vals, otherwise return zero. Submitting patch under advisement  from @laagesen. 

Impact:
Allows for coupling of Allen-Cahn type formulations to mechanics using TensorMechanics. Closes #17541

### CODE REVIEW

File: modules/phase_field/src/kernels/ACBarrierFunction.C [hunk 1]
```diff
@@ -74,12 +76,16 @@ ACBarrierFunction::computeQpOffDiagJacobian(unsigned int jvar)
...
-                 2.0 * _gamma[_qp] * (_u[_qp] * _u[_qp] + sum_etai2);
-  df0deta = (*_vals[j])[_qp] * df0deta_base;
-
-  return ((*_d2mudvardeta[j])[_qp] * calculateF0() + _dmudvar[_qp] * df0deta) * _phi[_j][_qp] *
-         _test[_i][_qp] * _L[_qp];
+  // prevent index from exceeding # of variables
+  if (j < _vals.size())
+  {
+    df0deta_base = (*_vals[j])[_qp] * (*_vals[j])[_qp] - 1.0 +
+                   2.0 * _Lgamma[_qp] * (_u[_qp] * _u[_qp] + sum_etai2);
```
Comment (laagesen) [inline modules/phase_field/src/kernels/ACBarrierFunction.C:83]: Typo `_Lgamma`, should be `_gamma`

**Review by laagesen — CHANGES_REQUESTED** [review]

File: modules/phase_field/src/kernels/ACBarrierFunction.C [hunk 2]
```diff
@@ -9,6 +9,8 @@
 
 #include "ACBarrierFunction.h"
 #include "libmesh/utility.h"
+#include <stdio.h>
+#include <stdlib.h>
```
Comment (dschwen) [inline modules/phase_field/src/kernels/ACBarrierFunction.C:13]: remove this please

File: modules/phase_field/src/kernels/ACBarrierFunction.C [hunk 3]
```diff
@@ -74,12 +76,16 @@ ACBarrierFunction::computeQpOffDiagJacobian(unsigned int jvar)
...
       sum_etai2 += (*_vals[i])[_qp] * (*_vals[i])[_qp];
 
-  df0deta_base = (*_vals[j])[_qp] * (*_vals[j])[_qp] - 1.0 +
-                 2.0 * _gamma[_qp] * (_u[_qp] * _u[_qp] + sum_etai2);
-  df0deta = (*_vals[j])[_qp] * df0deta_base;
-
-  return ((*_d2mudvardeta[j])[_qp] * calculateF0() + _dmudvar[_qp] * df0deta) * _phi[_j][_qp] *
-         _test[_i][_qp] * _L[_qp];
+  // prevent index from exceeding # of variables
+  if (j < _vals.size())
```
Comment (dschwen) [inline modules/phase_field/src/kernels/ACBarrierFunction.C:80]: It seems to me the correct fix would be to use `getParameterJvarMap` from JVarMapKernelInterface instead.

File: modules/phase_field/src/kernels/ACBarrierFunction.C [hunk 4]
```diff
@@ -31,7 +31,8 @@ ACBarrierFunction::ACBarrierFunction(const InputParameters & parameters)
     _dmudvar(getMaterialPropertyDerivative<Real>("mu", _uname)),
     _d2mudvar2(getMaterialPropertyDerivative<Real>("mu", _uname, _uname)),
     _vname(getParam<std::vector<VariableName>>("v")),
-    _d2mudvardeta(_n_eta)
+    _d2mudvardeta(_n_eta),
+    _eta_map(getParameterJvarMap("v"))
```
Comment (dschwen) [inline modules/phase_field/src/kernels/ACBarrierFunction.C:35]: I'd rather call this `_vmap`. The multiple different names (`v`, `_vals`, eta) get a bit confusing. Otherwise this looks good (once you fix indentation)

**Review by dschwen — APPROVED** [review]
