### PR TITLE
Fix bug and test for BimodalInverseSuperellipsoidsIC

### LINKED ISSUE #7358: Fix bug and test for BimodalInverseSuperellipsoidsIC
### Description of the enhancement or error report
There is a bug in `BimodalInverseSuperellipsoidsIC` causing the randomly placed internal particles to be placed outside the larger superellipsoids instead of inside (and thus they are not visible). Also, although there is a test input file for this IC, it wasn't added to the tests.i file, so the test was never being run.

### Rationale for the enhancement or information for reproducing the error
The internal particles are placed outside the larger particles instead of inside and are indistinguishable from the surrounding matrix. So it looks like the incorrect number of randomly placed internal particles is being generated. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

### PR DESCRIPTION
**Pull request by laagesen**
Closes #7358

### CODE REVIEW

File: modules/phase_field/tests/initial_conditions/tests [hunk 1]
```diff
@@ -6,6 +6,14 @@
     exodiff = 'RampIC_out.e'
   [../]
 
+  [./BimodalInverseSuperellipsoidsIC]
+    type = Exodiff
+    input = 'BimodalInverseSuperellipsoidsIC.i'
+    exodiff = 'BimodalInverseSuperellipsoidsIC_out.e'
+    scale_refine = 1
+    valgrind = 'HEAVY'
+  [../]
```
Comment (dschwen) [inline modules/phase_field/tests/initial_conditions/tests]: Why does an IC test have to be `HEAVY`?

File: modules/phase_field/src/ics/BimodalInverseSuperellipsoidsIC.C [hunk 2]
```diff
@@ -112,7 +112,7 @@ BimodalInverseSuperellipsoidsIC::computeSuperellipsoidCenters()
 
         if (j < _x_positions.size())
         {
-          if (r1 - dist - r2 > _large_spac)
+          if (r1 - dist - r2 < _large_spac)
```
Comment (dschwen) [inline modules/phase_field/src/ics/BimodalInverseSuperellipsoidsIC.C]: 👍

**Comment by permcody** [comment]
👍
