### PR TITLE
Fix SolutionUserObjects attempting to import postprocessors with the same name as a field variable

### LINKED ISSUE #15992: SolutionUserObject fails when PostProcessors and Variables have same name
## Bug Description
In general, MOOSE allows `PostProcessors` to have the same names as the materials or variables. However, `SolutionUserObject` fails to read such data from an exodus file due to the name clash. It throws in the following error which is coming from libMesh and is not directly indicative of the issue. 
```
ERROR: incompatible variable 'var_name' has already been added for this system!
Stack frames: 13
0: 0   libmesh_dbg.0.dylib                 0x000000010b000c2c libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 460
1: 1   libmesh_dbg.0.dylib                 0x000000010aff7a2a libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 218
2: 2   libmesh_dbg.0.dylib                 0x000000010bcf9e9b libMesh::System::add_variable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, libMesh::FEType const&, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> > const*) + 939
3: 3   libmesh_dbg.0.dylib                 0x000000010bcfb3d3 libMesh::System::add_variable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, libMesh::Order, libMesh::FEFamily, std::__1::set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short> > const*) + 83
4: 4   libmoose-dbg.0.dylib                0x00000001058b07f9 SolutionUserObject::readExodusII() + 2809
5: 5   libmoose-dbg.0.dylib                0x00000001058b349a SolutionUserObject::initialSetup() + 330
6: 6   libmoose-dbg.0.dylib                0x000000010546f502 FEProblemBase::initialSetup() + 5618
7: 7   libmoose-dbg.0.dylib                0x0000000104f831cf Transient::init() + 2415
8: 8   libmoose-dbg.0.dylib                0x000000010612dc47 MooseApp::executeExecutioner() + 183
9: 9   libmoose-dbg.0.dylib                0x000000010612ebbf MooseApp::run() + 335

```
## Steps to Reproduce
`SolutionUserObject` to read an exodus file that has a `Postprocessor` with the same name as a `Variable`

## Impact
Affects only the `SolutionUserObject`

### PR DESCRIPTION
**Pull request by socratesgorilla**
Closes #15992

### CODE REVIEW

File: framework/src/userobject/SolutionUserObject.C [hunk 1]
```diff
@@ -288,8 +288,29 @@ SolutionUserObject::readExodusII()
...
+  std::vector<std::string> _system_scalars;
+  if (_scalar_variables.size() > 0)
+  {
+    // Iterate over the scalar variables. If we find one matching a nodal variable name, we change
+    // it. Then we add the var, changed or unchanged, to the system.
+    for (std::string var : _scalar_variables)
+    {
+      if (std::any_of(_nodal_variables.begin(),
+                      _nodal_variables.end(),
+                      [var](std::string y) { return var == y; }))
```
Comment (friedmud) [inline framework/src/userobject/SolutionUserObject.C:301]: Small nit: please use `std::find` here

File: framework/src/userobject/SolutionUserObject.C [hunk 2]
```diff
@@ -288,8 +288,18 @@ SolutionUserObject::readExodusII()
...
-  for (const auto & var_name : _scalar_variables)
-    _system->add_variable(var_name, FIRST, SCALAR);
+  // Handle scalars
+  if (_scalar_variables.size() > 0)
+  {
+    // Iterate over the scalar variables. If we find one matching a nodal variable name, we ignore
+    // it, as this value is a postprocessor outputted to the global variables, not a scalar
+    // variable.
+    for (const std::string & var : _scalar_variables)
+      if (!std::any_of(_nodal_variables.begin(),
```
Comment (permcody) [inline framework/src/userobject/SolutionUserObject.C:298]: Just a non-action comment: You might also consider `std::find` for comparing all values in a container. It's arguably simpler since it doesn't require a lambda.

File: framework/src/userobject/SolutionUserObject.C [hunk 3]
```diff
@@ -288,8 +288,18 @@ SolutionUserObject::readExodusII()
   for (const auto & var_name : _elemental_variables)
     _system->add_variable(var_name, CONSTANT, MONOMIAL);
 
-  for (const auto & var_name : _scalar_variables)
-    _system->add_variable(var_name, FIRST, SCALAR);
+  // Handle scalars
+  if (_scalar_variables.size() > 0)
```
Comment (permcody) [inline framework/src/userobject/SolutionUserObject.C:292]: Non-action comment: All the C++ containers have an `.empty()` method.

Comment (socratesgorilla) [reply framework/src/userobject/SolutionUserObject.C:292]: I copied this straight from the existing code around line 374, but I didn't know about this method, will use this from now on

**Comment by socratesgorilla** [comment]
This should still not be merged until the other one is also merged

File: framework/src/userobject/SolutionUserObject.C [hunk 4]
```diff
@@ -271,24 +271,34 @@ SolutionUserObject::readExodusII()
...
-  for (const auto & var_name : _nodal_variables)
+  for (const std::string & var_name : _nodal_variables)
     _system->add_variable(var_name, FIRST);
 
-  for (const auto & var_name : _elemental_variables)
+  for (const std::string & var_name : _elemental_variables)
     _system->add_variable(var_name, CONSTANT, MONOMIAL);
 
-  for (const auto & var_name : _scalar_variables)
+  for (const std::string & var_name : _scalar_variables)
```
Comment (GiudGiud) [inline framework/src/userobject/SolutionUserObject.C:301]: why the change?

File: framework/src/userobject/SolutionUserObject.C [hunk 5]
```diff
@@ -363,10 +373,9 @@ SolutionUserObject::readExodusII()
     for (const auto & var_name : _elemental_variables)
       _exodusII_io->copy_elemental_solution(*_system, var_name, var_name, _exodus_time_index);
 
-    if (_scalar_variables.size() > 0)
+    if (!_scalar_variables.empty())
       _exodusII_io->copy_scalar_solution(
           *_system, _scalar_variables, _scalar_variables, _exodus_time_index);
-
     // Update the equations systems
```
Comment (GiudGiud) [inline framework/src/userobject/SolutionUserObject.C:379]:
```suggestion

    // Update the equations systems
```

File: framework/src/userobject/SolutionUserObject.C [hunk 6]
```diff
@@ -271,24 +271,34 @@ SolutionUserObject::readExodusII()
       if (std::find(all_elemental.begin(), all_elemental.end(), var_name) != all_elemental.end())
         _elemental_variables.push_back(var_name);
       if (std::find(all_scalar.begin(), all_scalar.end(), var_name) != all_scalar.end())
-        _scalar_variables.push_back(var_name);
+        // Check if the scalar matches any field variables, and ignore the var if it does. This
+        // means its a Postprocessor.
+        if (std::find(begin(_nodal_variables), end(_nodal_variables), var_name) ==
```
Comment (GiudGiud) [inline framework/src/userobject/SolutionUserObject.C:276]: you need to check both nodal and elemental field variables before adding the scalar variable

File: framework/src/userobject/SolutionUserObject.C [hunk 7]
```diff
@@ -363,10 +373,9 @@ SolutionUserObject::readExodusII()
     for (const auto & var_name : _elemental_variables)
       _exodusII_io->copy_elemental_solution(*_system, var_name, var_name, _exodus_time_index);
 
-    if (_scalar_variables.size() > 0)
+    if (!_scalar_variables.empty())
```
Comment (GiudGiud) [inline framework/src/userobject/SolutionUserObject.C:376]: please revert that it s the same

File: test/tests/userobjects/solution_user_object/tests [hunk 8]
```diff
@@ -17,4 +17,11 @@
 
     requirement = 'The system shall be capable of reading in field information and producing gradient values from both continuous and discontinuous fields.'
   [../]
+  [test_scalar]
+    type = RunApp
+    cli_args = 'UserObjects/soln/mesh=gold/testscalarrename.e UserObjects/soln/system_variables=""'
+    input = 'discontinuous_value_solution_uo_p2.i'
+    requirement = 'The system shall ignore postprocessor names that match field variable names when importing an exodus file.'
```
Comment (GiudGiud) [inline test/tests/userobjects/solution_user_object/tests:24]:
```suggestion
    requirement = 'The system shall not create scalar variables from global variables that have a name that matches a field variable's name when importing a solution from an exodus file.'
```

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/userobject/SolutionUserObject.C (hunk 7 above)
Comment (socratesgorilla) [reply framework/src/userobject/SolutionUserObject.C:376]: This was suggested by cody and derek haha, look at the resolved comments

File: framework/src/userobject/SolutionUserObject.C (hunk 4 above)
Comment (socratesgorilla) [reply framework/src/userobject/SolutionUserObject.C:301]: i mean, auto is slower than specifying it directly, no?

Comment (GiudGiud) [reply framework/src/userobject/SolutionUserObject.C:301]: not really. It s decided at compile time, and if we ever change the type we wont need to change all the code if it s auto, but we will need to if it s std::string

File: framework/src/userobject/SolutionUserObject.C (hunk 7 above)
Comment (GiudGiud) [reply framework/src/userobject/SolutionUserObject.C:376]: lol

Comment (GiudGiud) [reply framework/src/userobject/SolutionUserObject.C:376]: ok I m fine with it and they are at fault

**Comment by permcody** [comment]
No, not slower at all. The type is determined at compile time during the
semantic analysis phase. It comes from the expression on the rhs.

**Comment by socratesgorilla** [comment]
> No, not slower at all. The type is determined at compile time during the semantic analysis phase. It comes from the expression on the rhs.

Ah, okay, I can change this on a push then.

File: framework/src/userobject/SolutionUserObject.C (hunk 6 above)
Comment (socratesgorilla) [reply framework/src/userobject/SolutionUserObject.C:276]: is it actually possible for the user to specify an elemental variable that could trigger this? Previously we were just checking _nl and _aux for this.

Comment (GiudGiud) [reply framework/src/userobject/SolutionUserObject.C:276]: elemental variables can be in _nl and _aux in the same way that nodal variables are. 
some docs here, indirectly applies
https://mooseframework.inl.gov/syntax/AuxKernels/#2040a820-b5ba-4d14-a585-589f6e4f38bc

**Comment by permcody** [comment]
To be clear, I don’t have a problem with one choice over the other. I
suggested this as a way to expose Nathaniel to more of the methods
available on the container. However, in rare cases (e.g. linked lists),
empty can be faster than checking size.

File: framework/src/userobject/SolutionUserObject.C (hunk 6 above)
Comment (GiudGiud) [reply framework/src/userobject/SolutionUserObject.C:276]: I think this still needs to change to consider elemental variables.

same change as below though

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/userobject/SolutionUserObject.C (hunk 6 above)
Comment (socratesgorilla) [reply framework/src/userobject/SolutionUserObject.C:276]: Ah, whoops -- I implemented it in one half of the if-else, below around line 289, but forgot to put it here. I'll push it up

**Review by GiudGiud — APPROVED** [review]
nice. good fix
