### PR TITLE
Eigensolver Performance Improvement

### LINKED ISSUE #12767: Eigenvalue executioner improvement for supporting Picard iteration
## Rationale

During refactoring Picard iteration to enable Picard iteration for steady-state calculations including eigenvalue calculations, I found few issues.

When `Eigenvalue` is master:
1. Possibly SLEPc options are not set properly during Picard iteration causing a SLEPc error;
2. `EigenSystem` does not support evaluating L2 norm of the entire residual of the eigen problem;
3. Initialization of eigen calculation in SLEPc solver is desired to be moved out so that we can perform some evaluations between initialization and eigen solve. It also make the solver able to use the solution of previous Picard iteration as the initial guess.

When `Eigenvalue` is sub-app:
1. An SLEPc error was observed when the eigenvalue calculation is called the third time during Picard iteration:
```
0]PETSC ERROR: Argument out of range
[0]PETSC ERROR: Too many EPS monitors set
```
2. Screen output is not prefixed properly. I was getting something like
```
   18 SNES Function norm 2.478709290258e-11 
```
instead of
```
sub0:   18 SNES Function norm 2.478709290258e-11 
```
3. The convergence history is not colored.

## Description

These issues need to be fixed. Actually our major motivation of switching to the new eigenvalue executioner is to make the Picard iteration for multiphysics calculations simpler and more efficient.

## Impact
Better usability of the new eigenvalue solver.

### LINKED ISSUE #14292: Postprocessor for specific eigenvalue
## Reason
With the new Eigenvalue executioner, the only way to output the converged eigenvalue is to use a vector processor, which outputs all the eigenvalues that SLEPc calculated. In reactor physics, the only eigenvalue that really matters is the smallest one, so looking through csv files to find a single eigenvalue is a bit of a hassle. I would be nice to add the eigenvalue to the screen output and within the csv file with all the other postprocessor values. 

## Design
Create a postprocessor where users can define which eigenvalue they want to output, with possible tags:
- Largest/smallest magnitude
- Largest/smallest real
- Largest/smallest imaginary

## Impact
New output capability for eigenvalue problems using SLEPc executioner.

### LINKED ISSUE #15513: Enhancement of new eigenvalue solver
## Reason

The new eigenvalue solver has delivered most of the capabilities required by Griffin. However, some features still need to be enhanced.

1) Better support of Picard iteration. `Eigenvalue`  should be able to work as either a mater app or a sub-app. See details https://github.com/idaholab/moose/issues/12767

2) The `Eigenvalue` should be able to start from a given initial solution. It is useful for depletion calculations.  See details https://github.com/idaholab/moose/issues/12767

Closes #12767

3) Output eigenvalue after solve. I want to output a regular eigenvalue in console, but I would also add one option to allow users to output the inverse of eigenvalue. Nuetroinic community always wants to see the inverse of eigenvalue. Closes #14292

4) It is better to make the residual monitors (Nonlinear |R| and Linear |R| ) consistent with those of the regular nonlinear solver. 

5) Add short cuts: `PJFNK`, `JFNK`.  Some users may like to use the new eigenvalue solver via old input file options.

6) Autoscaling in the new solvers. Closes #15048

## Design

Need to refactor SLEPc again, and add more interfaces to hook up monitors.

## Impact
Make griffin better

### PR DESCRIPTION
**Pull request by fdkong**
1. Use the initial guess from the previous simulation. Closes #12767 

2. Add colorful outputs support. Print out the eigenvalue at each power iteration and the end of Newton solver.  Closes #14292

3.  Separate power iteration and Newton. Newton does not start from Power during Picard iteration.

Closes #15513

### CODE REVIEW

**Comment by fdkong** [comment]
Require libmeh update https://github.com/libMesh/libmesh/pull/2697

**Comment by fdkong** [comment]
@YaqiWang Here is the draft.

With this PR, 

1) we are able to reuse initial guess from the previous simulation 

2) we have colorful outputs. 

We need to add docs and more regression tests.

File: framework/src/executioners/Eigenvalue.C [hunk 1]
```diff
@@ -51,6 +51,11 @@ Eigenvalue::validParams()
   params.addParam<Real>(
       "normal_factor", 1.0, "Normalize eigenvector to make a defined norm equal to this factor");
 
+  params.addParam<bool>("auto_initialization",
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:54]: This parameter is not like the one in the old eigenvalue executioner. The old eigenvalue executioner does not have slepc. The default value of this parameter is true. When this parameter is set to true, MOOSE will initialize the eigenvector to const 1. And this initialization is done in Executioner init. When `execute` is called again, initialization will not be done again.

File: framework/src/systems/NonlinearEigenSystem.C [hunk 2]
```diff
@@ -239,6 +239,13 @@ NonlinearEigenSystem::solve()
   if (_eigen_problem.isGeneralizedEigenvalueProblem() && sys().matrix_B)
     sys().matrix_B->close();
 #endif
+
+  if (_eigen_problem.needInitializeEigenVector())
+  {
+    _eigen_problem.initEigenvector(1.0);
+    _transient_sys.set_initial_space(solution());
```
Comment (YaqiWang) [inline framework/src/systems/NonlinearEigenSystem.C:257]: If we want to have the behavior in the old executioner, we should call this line always. and move the above line in `Eigenvalue::init`.

File: framework/src/problems/EigenProblem.C [hunk 3]
```diff
@@ -316,6 +316,26 @@ EigenProblem::scaleEigenvector(const Real scaling_factor)
...
+  for (auto & vn : var_names)
+  {
+    MooseVariableFEBase & var = getVariable(0, vn);
+    if (var.parameters().get<bool>("eigen"))
+      for (unsigned int vc = 0; vc < var.count(); ++vc)
+      {
+        std::set<dof_id_type> var_indices;
+        _nl_eigen->system().local_dof_indices(var.number() + vc, var_indices);
+        for (const auto & dof : var_indices)
+          _nl_eigen->solution().set(dof, initial_value);
```
Comment (YaqiWang) [inline framework/src/problems/EigenProblem.C:332]: I know this code is the same as the one in the old executioner, but I'd let you be aware that this is not very right. Setting all dofs to this initial value does not make the solution flat in cases of MONOMIAL. It is right for LAGRANGE, but not always right. I was sloppy during the old implementation because libMesh does not have a simple way for us to set dofs so that the solution is constant over the domain.

File: framework/src/executioners/Eigenvalue.C [hunk 4]
```diff
@@ -97,10 +97,23 @@ Eigenvalue::init()
...
+ #endif
 }
 
 void
 Eigenvalue::execute()
+{
+  Steady::execute();
+}
+
+void Eigenvalue::prepareSolverOptions()
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:177]: No one is calling this function?

File: framework/src/utils/SlepcSupport.C [hunk 5]
```diff
@@ -106,6 +106,8 @@ getSlepcEigenProblemValidParams()
 
   params.addParam<unsigned int>("free_power_iterations", 4, "The number of free power iterations");
 
+  params.addParam<unsigned int>("extra_power_iterations", 0, "The number of extra free power iterations");
```
Comment (YaqiWang) [inline framework/src/utils/SlepcSupport.C:112]: Where this parameter is used?

File: framework/src/executioners/Eigenvalue.C [hunk 6]
```diff
@@ -52,13 +52,12 @@ Eigenvalue::validParams()
...
   params.addParam<bool>("auto_initialization",
-                        false,
+                        true,
                         "If true, we will set an initial eigen vector in moose, otherwise EPS "
                         "solver will initial eigen vector");
 
-  params.addParam<bool>("newton_inverse_power",
-                        true,
-                        "If Newton and Inverse Power is combined in SLEPc side");
+  params.addParam<bool>(
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:59]: Why is this parameter?  I thought for the slepc solver inside Eigenvalue::execute, we always have the combined newton and inverse power. On the other hand, the solver in Eigenvalue::init, we only want to have fixed number of inverse power iterations.

File: framework/include/problems/EigenProblem.h [hunk 7]
```diff
@@ -143,6 +143,10 @@ class EigenProblem : public FEProblemBase
 
   virtual void initPetscOutput() override;
 
+  bool outputInverseEigenvalue() { return _output_inverse_eigenvalue; }
+
+  void outputInverseEigenvalue(bool inverse) { _output_inverse_eigenvalue = inverse; }
```
Comment (YaqiWang) [inline framework/include/problems/EigenProblem.h:148]: did we decide to have a static function that GriffinApp can call to change the behavior of printing eigenvalues at the end?

**Review by YaqiWang — CHANGES_REQUESTED** [review]
@fdkong seems you have some misunderstandings.

File: framework/include/problems/EigenProblem.h (hunk 7 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:148]: I knew that. But I realized it was not necessary to be static. This function does not need to be set earlier. 

But I could do that

File: framework/src/executioners/Eigenvalue.C (hunk 6 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:59]: This parameter is added when we want SLEPc to do everything instead of separating `power` and `newton`.

I believe  Grifin will not touch this parameter

File: framework/include/problems/EigenProblem.h (hunk 7 above)
Comment (YaqiWang) [reply framework/include/problems/EigenProblem.h:148]: Then how Griffin change the default behavior? We do not want to ask users to set that parameter in the input all the time though.

File: framework/src/executioners/Eigenvalue.C (hunk 4 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:177]: See line 117.

File: framework/src/problems/EigenProblem.C (hunk 3 above)
Comment (fdkong) [reply framework/src/problems/EigenProblem.C:332]: I will check `MONOMIAL`

File: framework/src/systems/NonlinearEigenSystem.C (hunk 2 above)
Comment (fdkong) [reply framework/src/systems/NonlinearEigenSystem.C:257]: It is always called. `if` is to check that it is indeed a nonlinear solver. We care about nonlinear solver at this point.

File: framework/src/utils/SlepcSupport.C (hunk 5 above)
Comment (fdkong) [reply framework/src/utils/SlepcSupport.C:112]: In Eigenvalue::excute

File: framework/src/executioners/Eigenvalue.C (hunk 1 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:54]: We do not want to do `initialization` in the second `execute` because you want to reuse the solution from the previous step in Picard iteration.

File: framework/include/problems/EigenProblem.h (hunk 7 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:148]: Suppress parameter or call this method in SNProblem.

File: framework/src/executioners/Eigenvalue.C [hunk 8]
```diff
@@ -89,10 +110,71 @@ Eigenvalue::init()
...
+      _eigen_problem.doInitialFreePowerIteration(false);
+    }
+ #endif
 }
 
 void
 Eigenvalue::execute()
+{
+  // Let us do extra power iterations here if necessary
+  auto extra_power_iterations = _pars.get<unsigned int>("extra_power_iterations");
```
Comment (fdkong) [inline framework/src/executioners/Eigenvalue.C:150]: getParams

File: framework/src/executioners/Eigenvalue.C (hunk 6 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:59]: addprivateparam

**Comment by YaqiWang** [comment]
Just had a discussion with Fande on phone. I was looking at some outdated codes... We looked the code together and Fande will tag me once our discussions are addressed.

**Comment by pbalest** [comment]
Quick question how this is going to work? it will be a flag to turn on or the eigenvalue will use the old solution as initial guess every iteration by default?

**Comment by fdkong** [comment]
> Quick question how this is going to work? it will be a flag to turn on or the eigenvalue will use the old solution as initial guess every iteration by default? can I start to try it or it need further work?

If `eigenvalue` is the master, it will take the previous solution by default. A good example is `/test/tests/problems/eigen_problem/eigensolvers/ne_coupled_picard.i`. 

If `eigenvalue` is the subapp, you need ` keep_solution_during_restore = true` in `MultiApps` block to have the subapp use the previous solution as the initial guess. The good example is `moose/test/tests/problems/eigen_problem/eigensolvers/ne_coupled_picard_subT.i`

**Comment by pbalest** [comment]
Do I need this PR in? Because I think I already tried with `keep_solution_during_restore = true`, let me double check!

**Comment by fdkong** [comment]
> Do I need this PR in? Because I think I already tried with `keep_solution_during_restore = true`, let me double check!

Yes, you need this PR.

**Comment by pbalest** [comment]
Nice! I'll give a try then! thanks @fdkong

**Comment by pbalest** [comment]
@fdkong is this branch compatible with the latest griffin version? Do I need a particular Libmesh version?
```
Compiling C++ (in opt mode) /Users/balep/projects/griffin-idaholab-new1/moose/framework/build/unity_src/outputs_formatters_Unity.C...
In file included from /Users/balep/projects/griffin-idaholab-new1/moose/framework/build/unity_src/systems_Unity.C:8:
/Users/balep/projects/griffin-idaholab-new1/moose/framework/src/systems/NonlinearEigenSystem.C:282:20: error: no member named 'set_initial_space' in 'libMesh::TransientSystem<libMesh::EigenSystem>'
    _transient_sys.set_initial_space(solution());
```

**Comment by fdkong** [comment]
> @fdkong is this branch compatible with the latest griffin version? Do I need a particular Libmesh version?
> 
> ```
> Compiling C++ (in opt mode) /Users/balep/projects/griffin-idaholab-new1/moose/framework/build/unity_src/outputs_formatters_Unity.C...
> In file included from /Users/balep/projects/griffin-idaholab-new1/moose/framework/build/unity_src/systems_Unity.C:8:
> /Users/balep/projects/griffin-idaholab-new1/moose/framework/src/systems/NonlinearEigenSystem.C:282:20: error: no member named 'set_initial_space' in 'libMesh::TransientSystem<libMesh::EigenSystem>'
>     _transient_sys.set_initial_space(solution());
> ```

We need

https://github.com/libMesh/libmesh/pull/2697

**Comment by fdkong** [comment]
You could check my submodule commit.

**Comment by pbalest** [comment]
Just saw it thanks! I was using the conda libmesh that's probably why got that error!

**Comment by pbalest** [comment]
I am trying an input file that was running before on HPC, with this version do not run anymore.. this is what I get:
```
*** ERROR ***
It is not eps power, and there is no snes

[cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by fdkong** [comment]
> I am trying an input file that was running before on HPC, with this version do not run anymore.. this is what I get:
> 
> ```
> *** ERROR ***
> It is not eps power, and there is no snes
> 
> [cli_0]: aborting job:
> application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
> ```
> 
> These are the loaded modules:
> 
> ```
> use.moose   2) CMake/3.9.4   3) python/3.7-anaconda   4) GCC/8.2.0   5) MVAPICH2/2.3.1-GCC   6) PETSc/3.11.4-GCC
> ```

What the executioner block looks like?

It is better to use petsc submodule (3.13). I did not check the code against the old PETSc yet.

**Comment by pbalest** [comment]
```
[Executioner]
  type = Eigenvalue
  matrix_free = true
  solve_type = Newton
  eigen_problem_type = GEN_NON_HERMITIAN
  free_power_iterations = 4
  nl_abs_tol = 1e-9
  auto_preconditioning = false
[]
```

**Comment by fdkong** [comment]
> [Executioner]
>   type = Eigenvalue
>   matrix_free = true
>   solve_type = Newton
>   eigen_problem_type = GEN_NON_HERMITIAN
>   free_power_iterations = 4
>   nl_abs_tol = 1e-9
>   auto_preconditioning = false
> []

Could you try petsc submodule?

**Comment by pbalest** [comment]
Trying but it will be easy because HPC is can't download the missing libraries... looking for an option to transfer them manually

**Comment by fdkong** [comment]
> Trying but it will not be easy because HPC is can't download the missing libraries... looking for an option to transfer them manually

Offline installation instructions at https://github.com/idaholab/moose/pull/15765 may help. It will instruct you to install moose on a machine that does not have internet access.

**Comment by pbalest** [comment]
Thanks  I was trying to access the website but, is still down.. I'll compile the documentation and follow istructions!

**Comment by fdkong** [comment]
@pbalest I start to working on the integration

**Comment by fdkong** [comment]
libMesh update is needed. @lindsayad Where is the latest libmesh update?

**Comment by lindsayad** [comment]
https://github.com/idaholab/moose/pull/15867

**Comment by lindsayad** [comment]
I think @loganharbour had a problem where draft-prs don't update conflicts?

**Comment by fdkong** [comment]
> #15867

` _transient_sys.set_initial_space(solution());` should be in, and I am puzzled why civet did not see the update

File: framework/include/problems/EigenProblem.h [hunk 9]
```diff
@@ -105,12 +116,77 @@ class EigenProblem : public FEProblemBase
...
+   * Should set initial values for only eigen variables.
+   */
+  void initEigenvector(const Real initial_value);
+
+  /**
+   * Whether or not we do free power iteration. It is used in convergence check.
+   * We need to mark the solver as "converged" when doing free power to retrieve
+   * the final solution from SLPEc
+   */
+  bool doFreePowerIteration() { return _do_free_power_iteration; }
```
Comment (YaqiWang) [inline framework/include/problems/EigenProblem.h:135]: `const`?

File: framework/include/problems/EigenProblem.h [hunk 10]
```diff
@@ -105,12 +116,77 @@ class EigenProblem : public FEProblemBase
...
+
   /**
    * Which eigenvalue is active
    */
   unsigned int activeEigenvalueIndex() { return _active_eigen_index; }
+
+  /**
+   * Return console handle, and we use that in EPSMonitor to print out eigenvalue
+   */
+  const ConsoleStream & console() { return _console; }
```
Comment (YaqiWang) [inline framework/include/problems/EigenProblem.h:150]: `const`?

File: framework/include/utils/MooseTypes.h [hunk 11]
```diff
@@ -677,7 +677,9 @@ enum EigenSolveType
   EST_KRYLOVSCHUR,     ///< Krylov-Schur
   EST_JACOBI_DAVIDSON, ///< Jacobi-Davidson
   EST_NONLINEAR_POWER, ///< Nonlinear inverse power
-  EST_NEWTON,          ///< Newton-based eigen solver
+  EST_NEWTON, ///< Newton-based eigensolver with an assembled Jacobian matrix (fully coupled by default)
```
Comment (YaqiWang) [inline framework/include/utils/MooseTypes.h:680]: What do you mean `fully coupled by default`? You mean the matrix coupling pattern is full?

Comment (fdkong) [reply framework/include/utils/MooseTypes.h:680]: Yes

Comment (fdkong) [reply framework/include/utils/MooseTypes.h:680]: You might never use it in griffin

Comment (YaqiWang) [reply framework/include/utils/MooseTypes.h:680]: hehe, I am actually going to use it.

File: framework/src/executioners/Eigenvalue.C [hunk 12]
```diff
@@ -61,40 +77,228 @@ Eigenvalue::validParams()
...
+    setFreeNonlinearPowerIterations(free_power_iterations);
+
+    // Provide vector of ones to solver
+    // "auto_initialization" is on by default and we init the vector values associated
+    // with eigen-variables as ones. If "auto_initialization" is turned off by users,
+    // it is up to users to provide an initial guess. If "auto_initialization" is off
+    // and users does not provide an initial guess, slepc will automatically generate
+    // a random vector as the initial guess. The motivation to offer this option is
+    // that we have to initialize  ONLY eigen variables in multiphysics simulation.
+    if (_eigen_problem.needInitializeEigenVector())
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:176]: Should this be outside the `if` on line 162? User may set zero free power iterations but still want to do the initialization.

File: framework/src/executioners/Eigenvalue.C [hunk 13]
```diff
@@ -61,40 +77,228 @@ Eigenvalue::validParams()
...
+      _eigen_problem.initEigenvector(1.0);
+
+    _console << " Free power iteration starts" << std::endl;
+
+    // Call solver
+    _eigen_problem.solve();
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:182]: I am getting `Nonlinear solve did not converge due to DIVERGED_MAX_IT iterations 1` in one of my test runs here. I suggest we clear the snes tolerances so that we do not get this.

File: framework/src/executioners/Eigenvalue.C [hunk 14]
```diff
@@ -61,40 +77,228 @@ Eigenvalue::validParams()
...
+
+  // Does not allow time kernels
+  checkIntegrity();
+  // Some setup
+  _eigen_problem.execute(EXEC_PRE_MULTIAPP_SETUP);
+  _eigen_problem.initialSetup();
+
+#ifdef LIBMESH_HAVE_SLEPC
+
+  // Make sure all PETSc options are setup correctly
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:155]: Can we move the code in `init` from here into `_eigen_problem.initialSetup()`?

File: framework/src/executioners/Eigenvalue.C [hunk 15]
```diff
@@ -61,40 +77,228 @@ Eigenvalue::validParams()
...
+  for (unsigned int r_step = 0; r_step <= steps; r_step++)
+  {
+#endif // LIBMESH_ENABLE_AMR
+    _eigen_problem.timestepSetup();
+
+    // This loop is for nonlinear multigrids (developed by Alex)
+    for (MooseIndex(_num_grid_steps) grid_step = 0; grid_step <= _num_grid_steps; ++grid_step)
+    {
+
+      // Let us do extra power iterations here if necessary
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:229]: From here to LIne 238, I think the code should be in `_eigen_problem.solve()`. We want the `PicardSolve` as the outermost iteration.

File: framework/src/utils/SlepcSupport.C [hunk 16]
```diff
@@ -920,6 +959,148 @@ PCSetUp_MoosePC(PC pc)
...
+
+  EigenProblem * eigen_problem = static_cast<EigenProblem *>(mctx);
+  auto & console = eigen_problem->console();
+
+  auto inverse = eigen_problem->outputInverseEigenvalue();
+
+  auto eigenvalue = inverse ? 1.0 / (*eigr) : (*eigr);
+
+  // The term "k-eigenvalue" is adopted from the neutronics community.
+  console << " Iteration " << its << std::setprecision(8)
```
Comment (YaqiWang) [inline framework/src/utils/SlepcSupport.C:1098]: Suggest to have precision 10 here. 8 is slightly on the margin i.e. nl_rel_tol may still not reached but eigenvalue is accurate in 8 precision.

File: framework/src/executioners/Eigenvalue.C [hunk 17]
```diff
@@ -24,7 +24,8 @@ Eigenvalue::validParams()
 {
   InputParameters params = Steady::validParams();
 
-  params.addClassDescription("Eigenvalue solves a standard/generalized eigenvaue problem");
+  params.addClassDescription(
+      "Eigenvalue solves a standard/generalized linear or nonlinear eigenvaue problem");
 
   params.addParam<bool>(
       "matrix_free",
```
Comment (YaqiWang) [inline framework/src/executioners/Eigenvalue.C:31]: Do we still need this parameter here?

Comment (YaqiWang) [reply framework/src/executioners/Eigenvalue.C:31]: Now I am thinking based on our discussion that we should remove `precond_matrix_includes_eigen`. Users use kernels to decide how to assemble `A` and `B`. The code should manipulate `A` and `B` with `x` and `lambda` to form the full preconditioning matrix. We possibly can detect if `B` is zero or not. If `B` is zero, the manipulation is not needed.

File: framework/src/utils/SlepcSupport.C [hunk 18]
```diff
@@ -106,6 +110,9 @@ getSlepcEigenProblemValidParams()
 
   params.addParam<unsigned int>("free_power_iterations", 4, "The number of free power iterations");
 
+  params.addParam<unsigned int>(
```
Comment (YaqiWang) [inline framework/src/utils/SlepcSupport.C:113]: We need a protection here: out PJFNK eigen solver only can find the smallest eigenvalue, so we should error out if users set the `which_eigen_pairs` to something like `LARGEST_MAGNITUDE`. In more general sense, we need to check if a specific eigen solver in SLEPc can deliver the desired eigen pairs.

**Comment by fdkong** [comment]
OK, I am finally back this PR again

File: framework/src/utils/SlepcSupport.C (hunk 16 above)
Comment (fdkong) [reply framework/src/utils/SlepcSupport.C:1098]: OK

File: framework/src/executioners/Eigenvalue.C (hunk 17 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:31]: matrix_free will be an invalid for griffin once the integration is done. In this PR, we can not change it.  It will still be a valid option when users  use non-Newton algorithms

File: framework/src/utils/SlepcSupport.C (hunk 18 above)
Comment (fdkong) [reply framework/src/utils/SlepcSupport.C:113]: In general, we should not protect this in MOOSE, instead, it should be handled by SLEPc/PETSc.  For example, right now, PJFNK only makes sense for SMALLEST_MAGNITUDE (that was chosen by default). SLEPc will be angry we choose wrong parameters. In addition, in the future, PJFNK can be enhanced  to find other spectrums.

Comment (YaqiWang) [reply framework/src/utils/SlepcSupport.C:113]: Is SLEPc erroring out on the wrong settings then?

Comment (fdkong) [reply framework/src/utils/SlepcSupport.C:113]: I think so, otherwise thing is really wrong

File: framework/include/problems/EigenProblem.h [hunk 19]
```diff
@@ -57,7 +58,56 @@ class EigenProblem : public FEProblemBase
...
+  /**
+   * If we need to initialize eigen vector. We initialize the eigen vector
+   * only when "auto_initialization" is on and nonlinear eigen solver is selected.
+   */
+  bool needInitializeEigenVector();
+
+  /*
+   * Specify whether or not to initialize eigenvector automatically
+   */
+  void needInitializeEigenVector(bool need) { _auto_initilize_eigen_vector = need; }
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:70]: `initilize` -> `initialize`

File: framework/include/problems/EigenProblem.h [hunk 20]
```diff
@@ -57,7 +58,56 @@ class EigenProblem : public FEProblemBase
...
+
+  /**
+   * Set postprocessor and normalization factor
+   * 'Postprocessor' is often used to compute an integral of physics variables
+   */
+  void setNormalization(const PostprocessorName pp,
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:76]: `const PostprocessName &`

File: framework/include/problems/EigenProblem.h [hunk 21]
```diff
@@ -57,7 +58,56 @@ class EigenProblem : public FEProblemBase
...
+                        const Real value = std::numeric_limits<Real>::max());
+
+  /**
+   * Whether or not we do free power iteration. It is used in convergence check.
+   * We need to mark the solver as "converged" when doing free power to retrieve
+   * the final solution from SLPEc
+   */
+  bool doFreePowerIteration() { return _do_free_power_iteration; }
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:84]: Make method `const`

File: framework/include/problems/EigenProblem.h [hunk 22]
```diff
@@ -105,12 +155,37 @@ class EigenProblem : public FEProblemBase
...
+  /**
+   * For nonlinear eigen solver, a good initial value can help convergence.
+   * Should set initial values for only eigen variables.
+   */
+  void initEigenvector(const Real initial_value);
 
   /**
    * Which eigenvalue is active
    */
   unsigned int activeEigenvalueIndex() { return _active_eigen_index; }
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:167]: Not in the diff, but let's make this a `const` method

File: framework/include/problems/EigenProblem.h (hunk 10 above)
Comment (lindsayad) [reply framework/include/problems/EigenProblem.h:172]: :+1: to that

File: framework/include/problems/EigenProblem.h [hunk 23]
```diff
@@ -121,11 +196,23 @@ class EigenProblem : public FEProblemBase
   bool _negative_sign_eigen_kernel;
 
   unsigned int _active_eigen_index;
+
+  bool _auto_initilize_eigen_vector;
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:200]: `initilize` -> `initialize`

File: framework/include/problems/EigenProblem.h [hunk 24]
```diff
@@ -121,11 +196,23 @@ class EigenProblem : public FEProblemBase
...
   PerfID _compute_jacobian_tag_timer;
   PerfID _compute_jacobian_ab_timer;
   PerfID _compute_residual_tag_timer;
   PerfID _compute_residual_ab_timer;
   PerfID _solve_timer;
   PerfID _compute_jacobian_blocks_timer;
+
+  bool _has_normalization;
+  PostprocessorName _normalization;
+  Real _normal_factor;
```
Comment (lindsayad) [inline framework/include/problems/EigenProblem.h:214]: What is the difference between these two? It might be helpful to add some doxygen explaining what these individual members do

File: framework/include/systems/NonlinearEigenSystem.h [hunk 25]
```diff
@@ -92,6 +99,12 @@ class NonlinearEigenSystem : public NonlinearSystemBase
 
   virtual NonlinearSolver<Number> * nonlinearSolver() override;
 
+  /**
+   * Retrieve snes from slepc eigen solver. It is valid for only nonlinear eigen solver.
+   * You should see a big error if you do this for linear solver.
```
Comment (lindsayad) [inline framework/include/systems/NonlinearEigenSystem.h:104]: Big error is better than small error :smile:

File: framework/include/systems/NonlinearEigenSystem.h [hunk 26]
```diff
@@ -125,7 +138,7 @@ class NonlinearEigenSystem : public NonlinearSystemBase
    *
    * @return all converged eigenvalues as complex numbers
    */
-  virtual const std::vector<std::pair<Real, Real>> & getAllConvergedEigenvalues()
+  virtual const std::vector<std::pair<Real, Real>> & getAllConvergedEigenvalues() const
```
Comment (lindsayad) [inline framework/include/systems/NonlinearEigenSystem.h:141]: Oh I love `const`. Are you actually going to override this method somewhere? Wondering if this needs to be `virtual`. I always thought that `NonlinearEigenSystem` was a leaf object, but maybe you derive from it in Griffin or something.

File: framework/include/utils/SlepcEigenSolverConfiguration.h [hunk 27]
```diff
@@ -0,0 +1,46 @@
...
+  /**
+   * Constructur: get a reference to the \p SlepcEigenSolver variable to be able to manipulate it
+   */
+  SlepcEigenSolverConfiguration(EigenProblem & eigen_problem,
+                                libMesh::SlepcEigenSolver<libMesh::Number> & slepc_eigen_solver);
+
+  /**
+   * empty destructor
+   */
+  ~SlepcEigenSolverConfiguration() {}
```
Comment (lindsayad) [inline framework/include/utils/SlepcEigenSolverConfiguration.h:33]: If it's empty, then we do not need

File: framework/include/utils/SlepcSupport.h [hunk 28]
```diff
@@ -53,6 +56,26 @@ PetscErrorCode mooseSlepcEigenFormJacobianB(SNES snes, Vec x, Mat jac, Mat pc, v
...
+                                    int nconv,
+                                    PetscScalar * eigr,
+                                    PetscScalar * eigi,
+                                    PetscReal * errest,
+                                    int nest,
+                                    void * mctx);
+
+PetscErrorCode mooseSlepcEPSSNESSetUpOptionPrefix(EPS eps);
+PetscErrorCode mooseSlepcEPSSNESSetCustomizePC(EPS eps);
+PetscErrorCode mooseSlepcEPSSNESKSPSetPCSide(FEProblemBase & problem, EPS eps);
```
Comment (lindsayad) [inline framework/include/utils/SlepcSupport.h:78]: It looks like have a history of not documenting these APIs, but I would love to see some doxygen here. Most of the method names are pretty self explanatory, but for instance I don't know just by looking at it what `mooseSlepcStoppingTest` does

File: framework/include/variables/MooseVariableBase.h [hunk 29]
```diff
@@ -144,6 +144,16 @@ class MooseVariableBase : public MooseObject,
...
 
+  /**
+   * Whether or not this variable operates on an eigen kernel
+   */
+  virtual bool eigen() const { return _is_eigen; }
+
+  /**
+   * Mark this variable as an eigen var or non-eigen var
+   */
+  virtual void eigen(bool eigen) { _is_eigen = eigen; }
```
Comment (lindsayad) [inline framework/include/variables/MooseVariableBase.h:155]: These are new methods with a base implementation that I don't see overridden anywhere. Can we remove `virtual`?

File: framework/src/auxkernels/NormalizationAux.C [hunk 30]
```diff
@@ -37,6 +37,7 @@ Real
 NormalizationAux::computeValue()
 {
   Real denominator = _pp_on_source ? *_pp_on_source : 1.0;
+  mooseAssert(denominator != 0., "postprocessor value is zero");
```
Comment (lindsayad) [inline framework/src/auxkernels/NormalizationAux.C:40]: Oh I love asserts

File: framework/src/executioners/Eigenvalue.C [hunk 31]
```diff
@@ -61,40 +78,133 @@ Eigenvalue::validParams()
...
     paramError("normal_factor",
                "Cannot set scaling factor without defining normalization postprocessor.");
+
+  // _feproblem_solve calls FEProblemBase
+  _picard_solve.setInnerSolve(_feproblem_solve);
+  _time = _system_time;
+
+  if (isParamValid("normalization"))
+  {
+    auto normpp = getParam<PostprocessorName>("normalization");
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:116]: Not important but could be `const auto &` to avoid copies. I know that string is not very expensive to copy :smile:

File: framework/src/executioners/Eigenvalue.C [hunk 32]
```diff
@@ -61,40 +78,133 @@ Eigenvalue::validParams()
...
+#endif
+  // SLEPc older than 3.13.0 can not take initial guess from moose
+  // It may generate converge issues
+#if PETSC_RELEASE_LESS_THAN(3, 13, 0)
+  mooseDeprecated(
+      "Please use SLEPc-3.13.0 or higher. Old versions of SLEPc likely produce bad convergence");
+#endif
 }
 
+#if LIBMESH_HAVE_SLEPC
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:134]: Not a huge deal but `#ifdef` convention. We either define it or we don't.

File: framework/src/executioners/Eigenvalue.C [hunk 33]
```diff
@@ -114,31 +224,160 @@ Eigenvalue::execute()
...
+{
+  _eigen_problem.outputInverseEigenvalue(inverse);
+}
+
+#endif
+
+void
+Eigenvalue::execute()
+{
+#if LIBMESH_HAVE_SLEPC
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:282]: `#ifdef`

File: framework/src/executioners/Eigenvalue.C [hunk 34]
```diff
@@ -61,40 +78,133 @@ Eigenvalue::validParams()
...
+
   // Set a flag to nonlinear eigen system
   _eigen_problem.getNonlinearEigenSystem().precondMatrixIncludesEigenKernels(
       getParam<bool>("precond_matrix_includes_eigen"));
-#endif
-  Steady::init();
+
+  if (isParamValid("normalization"))
+  {
+    auto normpp = getParam<PostprocessorName>("normalization");
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:150]: `const auto &`. You possibly will never ask me to review again :rofl:

File: framework/src/executioners/Eigenvalue.C [hunk 35]
```diff
@@ -114,31 +224,160 @@ Eigenvalue::execute()
     _eigen_problem.petscOptionsInserted() = true;
   }
 #endif
+}
+
+void
+Eigenvalue::setFreeNonlinearPowerIterations(unsigned int free_power_iterations)
+{
+#if !PETSC_RELEASE_LESS_THAN(3, 12, 0)
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:232]: This is a situation where `#if` is appropriate because we care about the value of the macro, not simply about whether it exists

File: framework/src/executioners/Eigenvalue.C [hunk 36]
```diff
@@ -114,31 +224,160 @@ Eigenvalue::execute()
...
+  // have the code compatible with the rest moose world.
+  _eigen_problem.advanceState();
+
+  // First step in any eigenvalue state solve is always 1 (preserving backwards compatibility)
+  _time_step = 1;
+
+#ifdef LIBMESH_ENABLE_AMR
+
+  // Define the refinement loop
+  unsigned int steps = _eigen_problem.adaptivity().getSteps();
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:301]: Could use `auto` here in case you ever wanted to change the return type of `getSteps`. But I guess you will probably never do more than 2^32 steps :laughing:

File: framework/src/executioners/Eigenvalue.C [hunk 37]
```diff
@@ -114,31 +224,160 @@ Eigenvalue::execute()
...
+  for (unsigned int r_step = 0; r_step <= steps; r_step++)
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:302]: You don't have to do this but I love using this relatively new libMesh utility function:
```c++
for (const auto r_step : make_range(steps))
```

File: framework/src/executioners/Eigenvalue.C [hunk 38]
```diff
@@ -114,31 +224,160 @@ Eigenvalue::execute()
...
-    Real val = getParam<Real>("normal_factor");
+#endif // LIBMESH_ENABLE_AMR
+    _eigen_problem.timestepSetup();
 
-    if (MooseUtils::absoluteFuzzyEqual(*_normalization, 0.0))
-      mooseError("Cannot normalize eigenvector by 0");
-    else
-      val /= *_normalization;
+    // This loop is for nonlinear multigrids (developed by Alex)
+    for (MooseIndex(_num_grid_steps) grid_step = 0; grid_step <= _num_grid_steps; ++grid_step)
```
Comment (lindsayad) [inline framework/src/executioners/Eigenvalue.C:308]: I feel honored that you put my code here

File: framework/src/problems/EigenProblem.C [hunk 39]
```diff
@@ -348,7 +357,123 @@ EigenProblem::scaleEigenvector(const Real scaling_factor)
...
+EigenProblem::initEigenvector(const Real initial_value)
+{
+  dof_id_type n_dofs = 0;
+
+  std::vector<VariableName> var_names = getVariableNames();
+
+  // Count how many dofs we have
+  for (auto & vn : var_names)
+  {
+    auto & var = getVariable(0, vn);
```
Comment (lindsayad) [inline framework/src/problems/EigenProblem.C:370]: You know that I love `const auto &`

File: framework/src/systems/NonlinearEigenSystem.C [hunk 40]
```diff
@@ -101,12 +102,25 @@ NonlinearEigenSystem::NonlinearEigenSystem(EigenProblem & eigen_problem, const s
...
     _eigen_problem(eigen_problem),
+    _solver_configuration(nullptr),
     _n_eigen_pairs_required(eigen_problem.getNEigenPairsRequired()),
     _work_rhs_vector_AX(addVector("work_rhs_vector_Ax", false, PARALLEL)),
     _work_rhs_vector_BX(addVector("work_rhs_vector_Bx", false, PARALLEL))
 {
   sys().attach_assemble_function(Moose::assemble_matrix);
 
+  SlepcEigenSolver<Number> * solver =
+      libmesh_cast_ptr<SlepcEigenSolver<Number> *>(&(*_transient_sys.eigen_solver));
```
Comment (lindsayad) [inline framework/src/systems/NonlinearEigenSystem.C:113]: No need to have back-to-back &*; they cancel each other. Unless `eigen_solver` is a smart ptr, then you can just call `.get()`

File: framework/src/systems/NonlinearEigenSystem.C [hunk 41]
```diff
@@ -155,6 +169,11 @@ NonlinearEigenSystem::initialSetup()
     // IntegratedBCs
     addPrecondTagToMooseObjects(_integrated_bcs);
   }
+
+  // Mark a variable an eigen variable if it operates on eigen kernels
+  markEigenVariables(_dg_kernels);
+  markEigenVariables(_kernels);
+  markEigenVariables(_scalar_kernels);
```
Comment (lindsayad) [inline framework/src/systems/NonlinearEigenSystem.C:176]: This looks tricky. IIRC we cannot do eigen with (integrated) bcs? In which case, I assume it wouldn't make sense either to do them with interface kernels? I think this probably doesn't make sense thinking about the strong form of the eigenvalue problem

File: framework/include/systems/NonlinearEigenSystem.h [hunk 42]
```diff
@@ -76,6 +77,12 @@ class NonlinearEigenSystem : public NonlinearSystemBase
   template <typename T>
   void addPrecondTagToMooseObjects(MooseObjectTagWarehouse<T> & warehouse);
 
+  /**
+   * Mark a variable an eigen variable if it operates on eigen kernels
+   */
+  template <typename T>
+  void markEigenVariables(MooseObjectTagWarehouse<T> & warehouse);
```
Comment (lindsayad) [inline framework/include/systems/NonlinearEigenSystem.h:84]: If you are only going to use this in the `NonlinearEigenSystem` class, then you should make this method private. You put the definition in the .C file so if someone else attempted to call this we would end up with undefined references

File: framework/src/utils/SlepcSupport.C [hunk 43]
```diff
@@ -122,29 +129,28 @@ setSlepcEigenSolverTolerances(EigenProblem & eigen_problem, const InputParameter
...
-    Moose::PetscSupport::setSinglePetscOption("-eps_power_ksp_max_it",
+    Moose::PetscSupport::setSinglePetscOption("-ksp_max_it",
                                               stringify(params.get<unsigned int>("l_max_its")));
 
-    Moose::PetscSupport::setSinglePetscOption("-eps_power_ksp_rtol",
-                                              stringify(params.get<Real>("l_tol")));
+    Moose::PetscSupport::setSinglePetscOption("-ksp_rtol", stringify(params.get<Real>("l_tol")));
 
-    Moose::PetscSupport::setSinglePetscOption("-eps_power_ksp_atol",
+    Moose::PetscSupport::setSinglePetscOption("-ksp_atol",
```
Comment (lindsayad) [inline framework/src/utils/SlepcSupport.C:153]: This looks like a really nice change

File: modules/navier_stokes/test/tests/ins/IdealAMG/2d_diffusion_amg.i [hunk 44]
```diff
@@ -0,0 +1,48 @@
+[Mesh]
```
Comment (lindsayad) [inline modules/navier_stokes/test/tests/ins/IdealAMG/2d_diffusion_amg.i:1]: I'm guessing you didn't mean for this file to get in here?

Comment (lindsayad) [reply modules/navier_stokes/test/tests/ins/IdealAMG/2d_diffusion_amg.i:1]: Beautiful cask branch?

**Review by lindsayad — CHANGES_REQUESTED** [review]
This looks like an awesome PR @fdkong. My only requested changes are small C++ ones

File: framework/include/outputs/OutputWarehouse.h [hunk 45]
```diff
@@ -194,6 +194,12 @@ class OutputWarehouse
   /// Reset the output system
   void reset();
 
+  /**
+   * Calls the timestepSetup function for each of the output objects
```
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/include/outputs/OutputWarehouse.h:198]: `timestepSetup` is too early for solver setup where I am trying to hook up monitor, change prefix, etc. SLEPc solver does not exist yet when we call `timestepSetup`.

I moved this method from the private region to the public region because I want to call this function from `EigenProblem`.

[the remark this answers is not in the document]
Comment (fdkong) [reply framework/include/outputs/OutputWarehouse.h:198]: At the same time, I do not want to declare `EigenProblem` as friend of `OutputWarehouse`

File: framework/include/problems/EigenProblem.h [hunk 46]
```diff
@@ -30,6 +30,7 @@ class EigenProblem : public FEProblemBase
 
   EigenProblem(const InputParameters & parameters);
 
+#if LIBMESH_HAVE_SLEPC
```
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:33]: Will change. Thanks

File: framework/include/problems/EigenProblem.h [hunk 47]
```diff
@@ -57,7 +58,56 @@ class EigenProblem : public FEProblemBase
    */
   bool negativeSignEigenKernel() { return _negative_sign_eigen_kernel; }
 
-#if LIBMESH_HAVE_SLEPC
+  /**
+   * If we need to initialize eigen vector. We initialize the eigen vector
+   * only when "auto_initialization" is on and nonlinear eigen solver is selected.
+   */
+  bool needInitializeEigenVector();
```
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:65]: Yes

File: framework/include/problems/EigenProblem.h (hunk 19 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:70]: Oh, my god!

File: framework/include/problems/EigenProblem.h (hunk 20 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:76]: Yes

File: framework/include/problems/EigenProblem.h (hunk 21 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:84]: Yes

File: framework/include/problems/EigenProblem.h (hunk 22 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:167]: Yes

File: framework/include/problems/EigenProblem.h (hunk 10 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:172]: Yes

File: framework/include/problems/EigenProblem.h (hunk 23 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:200]: Yes

File: framework/include/problems/EigenProblem.h (hunk 24 above)
Comment (fdkong) [reply framework/include/problems/EigenProblem.h:214]: Yes

File: framework/include/systems/NonlinearEigenSystem.h (hunk 42 above)
Comment (fdkong) [reply framework/include/systems/NonlinearEigenSystem.h:84]: Nice

File: framework/include/outputs/OutputWarehouse.h (hunk 45 above)
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/outputs/OutputWarehouse.h:198]: Adding some more doxygen for this reasoning would be appreciated, otherwise someone else like me might come along and be confused and think you made a typo and think that that method doesn't actually do what you say it does

File: framework/include/utils/SlepcSupport.h (hunk 28 above)
Comment (fdkong) [reply framework/include/utils/SlepcSupport.h:78]: Will do docs

File: framework/include/variables/MooseVariableBase.h (hunk 29 above)
Comment (fdkong) [reply framework/include/variables/MooseVariableBase.h:155]: will do

File: framework/src/auxkernels/NormalizationAux.C (hunk 30 above)
Comment (fdkong) [reply framework/src/auxkernels/NormalizationAux.C:40]: I will become another  Roy soon

File: framework/src/executioners/Eigenvalue.C (hunk 31 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:116]: Haha. There is a lesson for me, I should make everything constant. And then git rid of these that can not be made as constant

File: framework/src/executioners/Eigenvalue.C (hunk 32 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:134]: will do

File: framework/src/executioners/Eigenvalue.C (hunk 13 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:196]: Good suggestion

File: framework/src/executioners/Eigenvalue.C (hunk 35 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:232]: It is really hard for me to get something right, haha

File: framework/src/executioners/Eigenvalue.C (hunk 33 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:282]: will do

File: framework/src/executioners/Eigenvalue.C (hunk 37 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:302]: Python style .

File: framework/src/executioners/Eigenvalue.C (hunk 38 above)
Comment (fdkong) [reply framework/src/executioners/Eigenvalue.C:308]: haha

File: framework/src/systems/NonlinearEigenSystem.C (hunk 40 above)
Comment (fdkong) [reply framework/src/systems/NonlinearEigenSystem.C:113]: Will do

File: framework/src/systems/NonlinearEigenSystem.C (hunk 41 above)
Comment (fdkong) [reply framework/src/systems/NonlinearEigenSystem.C:176]: We support `integrated bcs` now.` interface kernels` should make sense, but there is no use case yet.

File: framework/src/utils/SlepcSupport.C (hunk 43 above)
Comment (fdkong) [reply framework/src/utils/SlepcSupport.C:153]: haha. Get rid of prefix because nobody like it

File: modules/navier_stokes/test/tests/ins/IdealAMG/2d_diffusion_amg.i (hunk 44 above)
Comment (fdkong) [reply modules/navier_stokes/test/tests/ins/IdealAMG/2d_diffusion_amg.i:1]: It is disaster!!

File: framework/include/outputs/OutputWarehouse.h (hunk 45 above)
[the remark this answers is not in the document]
Comment (fdkong) [reply framework/include/outputs/OutputWarehouse.h:198]: Will do

**Comment by fdkong** [comment]
@lindsayad It is ready for review/merge

**Review by lindsayad — APPROVED** [review]
Oh my gosh, such beautiful documented and `const` code I have hardly ever seen

**Comment by YaqiWang** [comment]
This is great! Thanks!
