### PR TITLE
Close vectors as necessary in CrankNicolson

### LINKED ISSUE #24146: CrankNicholson fails in parallel with PETSc 3.19
## Bug Description
When doing final residual assembly inside a Crank-Nicholson time integration, PETSc 3.19 dies with a warning about doing VecAXPY on a vector in the wrong state.

## Steps to Reproduce
Build MOOSE with PETSc 3.19, run test suite; `--re crank` catches a number of the failures.

## Impact
Prevents upgrading to 3.19, but the fix here will be easy.

### PR DESCRIPTION
**Pull request by roystgnr**
This fixes #24146 for me

## Reason
PETSc 3.19 compatibility

## Design
Test for unclosed vectors in final Crank-Nicholson residual assembly, close them if necessary.

## Impact
No side effects expected

### CODE REVIEW

**Review by lindsayad — DISMISSED** [review]

**Comment by roystgnr** [comment]
Kicking "Internal app tests", but that timeout was on a CrankNicolson run so I'm crossing my fingers...

**Comment by roystgnr** [comment]
I've got a theory here ... that test is only guaranteed to be synchronized across all processors if all processors have already (implicitly) set `_is_closed` to false.  If one processor didn't get a workload then it doesn't know that the others did.

I think the only way to fix this is with an allreduce.  Which is a bit disappointing.  It'll only make solves milliseconds slower, but if the fix here had worked it'd have been nanoseconds.

File: framework/src/timeintegrators/CrankNicolson.C [hunk 1]
```diff
@@ -76,14 +76,20 @@ CrankNicolson::postResidual(NumericVector<Number> & residual)
...
+  // we don't always get here with _Re_time closed.
+  std::vector<unsigned char> inputs_closed = {
+      _Re_time.closed(), _Re_non_time.closed(), _residual_old.closed()};
+
+  // We might have done work on one processor but not all processors,
+  // so we have to sync our closed() checks.  Congrats to the BISON
+  // folks for test coverage that caught that.
+  comm().min(inputs_closed);
+
+  if (!inputs_closed[0])
```
Comment (lindsayad) [inline framework/src/timeintegrators/CrankNicolson.C:88]: This is not a required change, but we would also support a `min` with a `std::tuple` right? (Then you could do an explicit structured binding). Mostly for confirmation/curiosity. As this spans about 10 lines, it's pretty clear what `inputs_closed[0]` refers to

Comment (roystgnr) [reply framework/src/timeintegrators/CrankNicolson.C:88]: > we would also support a min with a std::tuple right?

Of course we would!  It would be *super* embarrassing if I'd started by using a `std::array` here only to discover that `timpi/op_function.h` didn't support anything more complicated than `std::pair`, right?  And then I'd tried to slip a `std::vector` by everyone while I quietly worked on the TIMPI PR?

But anyway, we'll just stick with `vector` here for now, because ... reasons.

Comment (roystgnr) [reply framework/src/timeintegrators/CrankNicolson.C:88]: Hmmm... actually, I've rediscovered the reason I didn't go crazy with `OpFunction` overloads earlier.  There's a bit of an ambiguity to some of them that isn't there for `StandardType` and `Packing` overloads, an it goes down a rabbit hole.

If I've declared a `tuple <T, U, V> x;` and I take a `min()` of those across two processors - should I get the component-wise min, or the dictionary-order `min()`?  If I do the former, won't that be a nasty surprise to people who instantiate `tuple <Year, Day, Month> iso_8601_date;`?  If I do the latter, won't that be a nasty surprise to people who instantiate `tuple <bool, bool, bool> packing_three_mins_into_one;`?  With a particular class it's maybe sufficient to pick one or the other and document it (e.g. our `OpFunction<Point>` says `min() and max() are applied component-wise; this makes them useful for bounding box reduction operations`, even though that makes them inconsistent with our `operator<(const Point&,const Point&)`, but who knows what someone expects from an arbitrary `tuple`?

I could create both types of functions, partially specialize `OpFunction` around a `componentwise_tuple<Types...>` and `dictionary_tuple<Types...>`, and then require people to use one or the other container (subclass? shim class??) when doing reductions?  Or I could create a `Communicator::allreduce()` that would take (and MPI_Op_create if necessary, etc) an explicit function rather than inferring a function via data type and communicator method name?  I could do both?

I'm leaning toward the latter at this point, but damn.  This is the sort of question that would have been ideal to bring up in person last week.

Comment (lindsayad) [reply framework/src/timeintegrators/CrankNicolson.C:88]: Haha well you didn't make me think about this until this morning

**Review by lindsayad — APPROVED** [review]
