### PR TITLE
Guarded against NaN in LinearInterpolation

### LINKED ISSUE #30157: LinearInterpolation can access out of bounds with NaN input
### Bug Description

In `LinearInterpolation`, if you do `sample(x)` and `x` is a NaN, then it will try and access out of bounds in this:
```
  auto upper = std::upper_bound(_x.begin(), _x.end(), x);
  int i = std::distance(_x.begin(), upper) - 1;
  return _y[i] + (_y[i + 1] - _y[i]) * (x - _x[i]) / (_x[i + 1] - _x[i]);
```
If no upper bound exists for `x` (as in the case of nan), `upper = _x.end()` and then `i = _x.size() - 1`, which is a problem for `y[i + 1]`.

### Steps to Reproduce

See above.

### Impact

Garbage results if nan values are input to object.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by joshuahansel**
This was broken by https://github.com/idaholab/moose/pull/24256

Closes #30157

### CODE REVIEW

**Comment by joshuahansel** [comment]
@lindsayad Just marked as ready. I confirmed this will fix the valgrind target in Sockeye.

File: framework/src/utils/LinearInterpolation.C [hunk 1]
```diff
@@ -70,11 +70,14 @@ LinearInterpolation::sample(const T & x) const
   }
 
   auto upper = std::upper_bound(_x.begin(), _x.end(), x);
-  int i = std::distance(_x.begin(), upper) - 1;
-  return _y[i] + (_y[i + 1] - _y[i]) * (x - _x[i]) / (_x[i + 1] - _x[i]);
-
-  // If this point is reached, x must be a NaN.
-  mooseException("Sample point in LinearInterpolation is a NaN.");
+  const unsigned int i = std::distance(_x.begin(), upper) - 1;
```
Comment (lindsayad) [inline framework/src/utils/LinearInterpolation.C:73]:
```suggestion
  const auto i = cast_int<std::size_t>(std::distance(_x.begin(), upper) - 1);
```

File: framework/src/utils/LinearInterpolation.C [hunk 2]
```diff
@@ -70,11 +70,14 @@ LinearInterpolation::sample(const T & x) const
...
+  if (i == _x.size() - 1)
```
Comment (lindsayad) [inline framework/src/utils/LinearInterpolation.C:74]:
```suggestion
  if (i == cast_int<std::size_t>(_x.size() - 1))
```

File: framework/src/utils/LinearInterpolation.C [hunk 3]
```diff
@@ -102,11 +105,14 @@ LinearInterpolation::sampleDerivative(const T & x) const
   }
 
   auto upper = std::upper_bound(_x.begin(), _x.end(), x);
-  int i = std::distance(_x.begin(), upper) - 1;
-  return (_y[i + 1] - _y[i]) / (_x[i + 1] - _x[i]);
-
-  // If this point is reached, x must be a NaN.
-  mooseException("Sample point in LinearInterpolation is a NaN.");
+  const unsigned int i = std::distance(_x.begin(), upper) - 1;
```
Comment (lindsayad) [inline framework/src/utils/LinearInterpolation.C:108]:
```suggestion
  const auto i = cast_int<std::size_t>(std::distance(_x.begin(), upper) - 1);
```

File: framework/src/utils/LinearInterpolation.C [hunk 4]
```diff
@@ -102,11 +105,14 @@ LinearInterpolation::sampleDerivative(const T & x) const
...
+  if (i == _x.size() - 1)
```
Comment (lindsayad) [inline framework/src/utils/LinearInterpolation.C:109]:
```suggestion
  if (i == cast_int<std::size_t>(_x.size() - 1))
```

**Review by lindsayad — APPROVED** [review]
