### PR TITLE
Avoid changing dt in FiniteStrainUObasedCP

### LINKED ISSUE #17340: Make FiniteStrainUObasedCP not to modify _dt during substepping
## Reason

The current FiniteStrainUObasedCP substepping scheme is modifying dt during substepping. This would result in undesired behaviors when the global timestep is cut due to moose exception.  

## Design

- Add a separate _substep_dt variable and use it for updating state variables in the inner loop.
- Do not affect existing tests

## Impact

Resolve issues that are brought by modifying the time step in FiniteStrainUObasedCP.

### PR DESCRIPTION
**Pull request by dewenyushu**
Add a separate _substep_dt variable and use it for updating state variables in the inner loop.

Closes #17340

### CODE REVIEW

**Comment by jiangwen84** [comment]
Could you add a test for this code change? I remember there is a test for exception. You can modify it by adding a function Dirichlet BC. It will be nice to add the same test to the stress update version too.

**Comment by dewenyushu** [comment]
> Could you add a test for this code change? I remember there is a test for exception. You can modify it by adding a function Dirichlet BC. It will be nice to add the same test to the stress update version too.

Thanks @jiangwen84 ! Tests are added for both cases now!

File: modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C [hunk 1]
```diff
@@ -553,15 +561,13 @@ FiniteStrainUObasedCP::calcJacobian()
...
+    _uo_slip_rates[i]->calcSlipRateDerivative(_qp, _substep_dt, dslipdtau);
     for (unsigned int j = 0; j < nss; j++)
     {
       dtaudpk2[j] = (*_flow_direction[i])[_qp][j];
       dfpinvdslip[j] = -_fp_old_inv * (*_flow_direction[i])[_qp][j];
+      dfpinvdpk2 += (dfpinvdslip[j] * dslipdtau[j] * _substep_dt).outerProduct(dtaudpk2[j]);
     }
-
-    for (unsigned int j = 0; j < nss; j++)
-      dfpinvdpk2 += (dfpinvdslip[j] * dslipdtau[j] * _dt).outerProduct(dtaudpk2[j]);
```
Comment (sapitts) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:564]: Is this change just to remove the extra loop over the `nss` variable, since each product is computed on the individual `j` entries of the vectors?

File: modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/use_substep_dt.i [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+[]
+
+# [Variables]
+#   [./ux]
+#   [../]
+#   [./uy]
+#   [../]
+#   [./uz]
+#   [../]
+# []
```
Comment (sapitts) [inline modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/use_substep_dt.i:22]: Might as well remove these commented out variables to clean up the input file a bit

File: modules/tensor_mechanics/test/tests/crystal_plasticity/user_object_based/tests [hunk 3]
```diff
@@ -100,4 +100,12 @@
     requirement = 'The system shall provide an object to read values from a file and map them onto a mesh besed on mesh block IDs'
     design = 'ElementPropertyReadFile.md'
   [../]
+  [./use_substep_dt]
+    type = 'CSVDiff'
+    input = 'use_substep_dt.i'
+    csvdiff = 'use_substep_dt_out.csv'
+    issues = '#17340'
+    requirement = 'The system shall apply correct boundary condition after timestep being cut'
```
Comment (sapitts) [inline modules/tensor_mechanics/test/tests/crystal_plasticity/user_object_based/tests:108]: perhaps add in something about the timestep being cut after substepping?

**Review by sapitts — CHANGES_REQUESTED** [review]
A few minor things, and I like the code changes you've made here

File: modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C (hunk 1 above)
Comment (dewenyushu) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:564]: Exactly :)

Comment (sapitts) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:564]: Does the material based version also need this optimization? :-)

Comment (sapitts) [reply modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:564]: Oh nice!

**Review by sapitts — APPROVED** [review]
This PR looks good to me; @dschwen would you review and merge if you approve of the changes please?

File: modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C [hunk 4]
```diff
@@ -159,6 +159,8 @@ FiniteStrainUObasedCP::FiniteStrainUObasedCP(const InputParameters & parameters)
     _mat_prop_state_var_evol_rate_comps[i] = &declareProperty<std::vector<Real>>(
         parameters.get<std::vector<UserObjectName>>("uo_state_var_evol_rate_comps")[i]);
   }
+
+  _substep_dt = 0.0;
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:163]: any reason this is not in the initializer list?

File: modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C [hunk 5]
```diff
@@ -447,7 +445,16 @@ FiniteStrainUObasedCP::solveStress()
   if (iter >= _maxiter)
   {
 #ifdef DEBUG
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainUObasedCP.C:447]: this should be `#ifndef NDEBUG` ... yeah, I know. But that's how we enable assertions for example. Otherwise it won't show up in `devel` mode

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
The minor comments could be addressed later
