### PR TITLE
Fix water97 around two phase region

### LINKED ISSUE #32048: Extend range of Water 97 fluid properties in FP module
### Motivation

Water97FluidProperties::T_from_p_h_ad()
Region 5 is not implemented

the code assumes that the (p, h) plot is continuous across h_from_p_T(pressure, vaporTemperature(pressure)), which is not. Region 4 should be a two phase region

### Design

@lingzou suggested the following pseudo code for h_from_pT
```
if (h > h_from_p_T(p, 273.15) && h < h_l_sat_from_p(p))
  return 1;
else if (h < h_g_sat_from(p))
  return 4;
else if (h < h_from_p_T(p, 1073.15)
  return 2;
else if (h < h_from_p_T(p, 2273.15)
  return 5:
```

and a bisection method for region 5

### Impact

More capable fluid properties
More capabilities for studying water cooled systems

### PR DESCRIPTION
**Pull request by GiudGiud**
based on feedback from @lingzou-anl 

Added more testing and some made it more efficient too, the comparisons were calling h_from_p_T twice more than now

Closes #32048

### CODE REVIEW

**Comment by GiudGiud** [comment]
Test failures are not related

**Comment by GiudGiud** [comment]
We could do an optimization/cleanup PR on this fluid property later on. The treatment of AD (well actually non-AD calls) is not optimal, should be templated so non-AD does not go through AD calls

File: modules/fluid_properties/include/fluidproperties/Water97FluidProperties.h [hunk 1]
```diff
@@ -275,6 +275,16 @@ class Water97FluidProperties : public SinglePhaseFluidProperties
    */
   unsigned int inRegion(Real pressure, Real temperature) const;
 
+  /**
+   * Determines the phase region that the given pressure and enthaply values
```
Comment (joshuahansel) [inline modules/fluid_properties/include/fluidproperties/Water97FluidProperties.h:279]:
```suggestion
   * Determines the phase region that the given pressure and enthalpy values
```

**Review by joshuahansel — CHANGES_REQUESTED** [review]

**Comment by GiudGiud** [comment]
coverage failure is fake news, I expanded coverage

**Review by joshuahansel — CHANGES_REQUESTED** [review]
Please add some basic doc delineating the regions.

**Comment by GiudGiud** [comment]
Added a figure. I can't really make the bounds explicit in the doco without copying a good chunk of the code

**Comment by joshuahansel** [comment]
@GiudGiud Sorry for the delay. I'm good with this, looks like it just needs some conflict resolution.

**Comment by GiudGiud** [comment]
Rebased and repushed

**Review by joshuahansel — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thanks for the review!
