### PR TITLE
One based indexing in UMAT

### LINKED ISSUE #19590: One based indexing in UMAT
## Reason
Element and integration point numbers use 1-based indexing rather than the 0-based indexing seen in MOOSE.

## Design
Add `+1` to the element and integration point  and add a new parameter (`use_one_based_indexing`) that _must_ be provided in the input file, and will give a verbose explanation if it is not set to `true`. This should prevent users from unknowingly getting the indexing changed, leading possibly to unexpected results.

Also, for better compatibility, our multi-file build system should support `.mod` files.

## Impact
Better compatibility.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #19590

### CODE REVIEW

File: modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C [hunk 1]
```diff
@@ -27,6 +27,11 @@ AbaqusUMATStress::validParams()
   params.addClassDescription("Coupling material to use Abaqus UMAT models in MOOSE");
   params.addRequiredParam<FileName>(
       "plugin", "The path to the compiled dynamic library for the plugin you want to use");
+  params.addRequiredParam<bool>(
+      "use_one_based_indexing",
+      "MOOSE is transitioning to supporting 1-based indexing to ensure maximum "
+      "compatibility with UMAT plugins. During the transition period we require "
+      "users to specify this parameter to acknowledge the change.");
```
Comment (recuero) [inline modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C:34]: Since it looks like that "one_based" is the way to go here, one option is to not require it and default to the _right_ way. Also "MOOSE is transitioning" -> "MOOSE has transitioned": Is there anything that remains?

**Review by recuero — DISMISSED** [review]

**Review by recuero — DISMISSED** [review]

File: modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C (hunk 1 above)
Comment (bwspenc) [reply modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C:34]: The statement about MOOSE transitioning to one-based numbering isn't really true, is it?  That makes it sound like we're switching all of MOOSE's internal node numbering to start at 1 across the board, which I doubt is the case. Also, this parameter description doesn't actually say what setting the parameter to true or false actually does. Suggested re-wording:

Parameter to control whether indexing for element and integration points as presented to UMAT models is based on 1 (true) or 0 (false).  This does not affect internal MOOSE numbering. The option to use 0-based numbering is deprecated and will be removed soon.

**Review by bwspenc — CHANGES_REQUESTED** [review]
Minor suggested adjusted to a parameter description.

Also, it seems like some mention of this should be made in AbaqusUMATStress.md. In that document, we should explain the interactions between this and the numbering in .e and .in mesh files.

File: modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C (hunk 1 above)
Comment (dschwen) [reply modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C]: Made the change

**Review by bwspenc — APPROVED** [review]
