### PR TITLE
Fix edge case in IsotropicTempDepHardening

### LINKED ISSUE #7722: Fix edge case in temperature dependent hardening models
The models for temperature dependent hardening in solid_mechanics and tensor_mechanics fail with a segfault if the temperature is higher than the max temperature of the hardening curves provided. I will fix this.

### PR DESCRIPTION
**Pull request by backmari**
and RecomputeRadialReturnTempDepHardening closes #7722

@bwspenc 

(The style changes in IsotropicTempDepHardening are just to make the solid_mechanics version more similar to the same model in tensor_mechanics (RecomputeRadialReturnTempDepHardening).)

### CODE REVIEW

File: modules/solid_mechanics/src/materials/IsotropicTempDepHardening.C [hunk 1]
```diff
@@ -104,13 +104,15 @@ IsotropicTempDepHardening::initializeHardeningFunctions(unsigned qp)
 
   else if (temp <= _hf_temperatures[0])
   {
-    _hf_index = 0;
+    _hf_index_lo = 0;
+    _hf_index_hi = 1;
```
Comment (bwspenc) [inline modules/solid_mechanics/src/materials/IsotropicTempDepHardening.C]: Wouldn't it be better for _hf_index_hi to be 0 in this case?  That would avoid issues if there's just a single hardening function supplied.

File: modules/tensor_mechanics/src/materials/RecomputeRadialReturnTempDepHardening.C [hunk 2]
```diff
@@ -95,13 +96,15 @@ RecomputeRadialReturnTempDepHardening::initializeHardeningFunctions()
 
   else if (temp <= _hf_temperatures[0])
   {
-    _hf_index = 0;
+    _hf_index_lo = 0;
+    _hf_index_hi = 1;
```
Comment (bwspenc) [inline modules/tensor_mechanics/src/materials/RecomputeRadialReturnTempDepHardening.C]: Again, I'd make this 0.

**Comment by bwspenc** [comment]
Aside from my comments, this looks good. Could you please test this and make sure it works with a just a single hardening curve provided?

File: modules/solid_mechanics/src/materials/IsotropicTempDepHardening.C (hunk 1 above)
Comment (backmari) [inline modules/solid_mechanics/src/materials/IsotropicTempDepHardening.C]: That makes sense.

**Comment by backmari** [comment]
@bwspenc Thanks for looking through this. There is a test in the constructor to check that the user provided more than one hardening curve, i.e. it does NOT work with just a single hardening curve...

**Comment by bwspenc** [comment]
@backmari Thanks, I was wondering about that. With the changes you just made, I think it might actually work for that case (except for the error check), but it's fine to only have it work for 2+ curves.

This looks good to me, and as far as I'm concerned, it's ready to be merged.

**Comment by permcody** [comment]
👍
