### PR TITLE
parser: make suggestions for misspelled parameters

### LINKED ISSUE #980: Better Error For Unused Parameter
Currently if you are treating unused parameters as errors you get output that looks like this:

```
*** ERROR: The following parameters were unused in your input file:
Executioner/n_steps
*** ERROR
```

It would be awesome if it would also print out what the valid options actually are for the parent block!

### PR DESCRIPTION
**Pull request by rwcarlsen**
```
$ moose_test-opt -i foo.i --warn-unused Mesh/dispalcments='bla'
...
*** Warning ***
CLI_ARG:1: unused parameter 'Mesh/dispalcments'
    Did you mean 'displacements'?
```

I don't think we want to print out the entire parameter list - that list could be super long and then the user would have to sift through it all visually.

fixes #980

### CODE REVIEW

**Comment by permcody** [comment]
@lindsayad - Moltres failed, it's not clear if this PR broke something. Does that look like a new failure to you?

**Comment by lindsayad** [comment]
This is a real failure. Backtrace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000010166d376 libmoose-dbg.0.dylib`MooseUtils::levenshteinDist(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long(this="") const at string:1735
    frame #1: 0x000000010166d35a libmoose-dbg.0.dylib`MooseUtils::levenshteinDist(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [inlined] std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size(this="") const at string:1489
    frame #2: 0x000000010166d34c libmoose-dbg.0.dylib`MooseUtils::levenshteinDist(s1="", s2="nt_scale") at MooseUtils.C:44
    frame #3: 0x0000000101288eb6 libmoose-dbg.0.dylib`findSimilar(param="nt_scale", options=size=0, dist_cutoff=3) at Parser.C:142
    frame #4: 0x00000001012ed517 libmoose-dbg.0.dylib`UnusedWalker::walk(this=0x00007fff5fbfd4c0, fullpath="nt_scale", nodename="nt_scale", n=0x0000000110d02660) at Parser.C:194
    frame #5: 0x000000010299f213 libhit-dbg.0.dylib`hit::Node::walk(this=0x0000000110d02660, w=0x00007fff5fbfd4c0, t=Field) at parse.cc:298
    frame #6: 0x000000010299f42a libhit-dbg.0.dylib`hit::Node::walk(this=0x0000000110d01a60, w=0x00007fff5fbfd4c0, t=Field) at parse.cc:300
    frame #7: 0x000000010129ffc9 libmoose-dbg.0.dylib`Parser::errorCheck(this=0x000000011100b930, comm=0x0000000110d09bc8, warn_unused=true, err_unused=false) at Parser.C:578
    frame #8: 0x0000000100ba8ed1 libmoose-dbg.0.dylib`MooseApp::executeExecutioner(this=0x000000011100b200) at MooseApp.C:559
    frame #9: 0x0000000100bab65a libmoose-dbg.0.dylib`MooseApp::run(this=0x000000011100b200) at MooseApp.C:717
    frame #10: 0x00000001000029f4 moltres-dbg`main(argc=3, argv=0x00007fff5fbfe980) at main.C:24
    frame #11: 0x00007fffc5084235 libdyld.dylib`start + 1
```
What's happening is that the parser is trying to `listValidParams` for a section when we're not in a section. E.g. I have a variable (or a `nodename` as its called in `UnusedWalker::walk`) that is defined at the top of the input file, not in any MOOSE sections.

So yea I can delete that variable because as the parser has detected, this is an unused variable. But maybe the parser shouldn't try to make suggestions in this case?

**Comment by permcody** [comment]
Yeah, the parser probably shouldn't make that recommendation.

**Comment by rwcarlsen** [comment]
Well - actually the code was broken and the parser wasn't trying to make a suggestion there.  The list of valid params for the root/top-level section is ``{}`` and my code assumed there was at least one valid param in that list.  If there are no valid params, then the code doesn't make any suggestions.  It also doesn't make suggestions unless the edit distance is 3 or less between a candidate and the unused param name.

File: framework/src/utils/MooseUtils.C [hunk 1]
```diff
@@ -31,10 +31,42 @@
...
+levenshteinDist(const std::string & s1, const std::string & s2)
+{
+  // To change the type this function manipulates and returns, change
+  // the return type and the types of the two variables below.
+  auto s1len = s1.size();
+  auto s2len = s2.size();
+
+  auto column_start = (decltype(s1len))1;
+
+  auto column = new decltype(s1len)[s1len + 1];
```
Comment (permcody) [inline framework/src/utils/MooseUtils.C]: Raw c-style array memory allocation? What's wrong with std::vector? I like the autos and decltypes though!

File: framework/src/utils/MooseUtils.C [hunk 2]
```diff
@@ -31,10 +31,42 @@
...
+    {
+      auto old_diagonal = column[y];
+      auto possibilities = {
+          column[y] + 1, column[y - 1] + 1, last_diagonal + (s1[y - 1] == s2[x - 1] ? 0 : 1)};
+      column[y] = std::min(possibilities);
+      last_diagonal = old_diagonal;
+    }
+  }
+  auto result = column[s1len];
+  delete[] column;
```
Comment (permcody) [inline framework/src/utils/MooseUtils.C]: Yeah, this shouldn't be necessary. Even if you used an array, you could allocate into a unique pointer.

File: framework/src/utils/MooseUtils.C [hunk 3]
```diff
@@ -31,10 +31,42 @@
 
 // System includes
 #include <sys/stat.h>
+#include <numeric>
 
 namespace MooseUtils
 {
 
+int
```
Comment (permcody) [inline framework/src/utils/MooseUtils.C]: Levenshtein distance is always positive. Why `int`?

File: framework/src/utils/MooseUtils.C [hunk 4]
```diff
@@ -31,10 +31,42 @@
...
+levenshteinDist(const std::string & s1, const std::string & s2)
+{
+  // To change the type this function manipulates and returns, change
+  // the return type and the types of the two variables below.
+  auto s1len = s1.size();
+  auto s2len = s2.size();
+
+  auto column_start = (decltype(s1len))1;
```
Comment (permcody) [inline framework/src/utils/MooseUtils.C]: You should be able to right this line of code with decltype on the LHS:
`decltype(silen) column_start = 1;` 

The only time it needs to be on the RHS is when you are trying to drop the const. However in this case it looks like `column_start` is constant.

**Review by permcody — CHANGES_REQUESTED** [review]
Algorithm is fine. I'm just trying to get you to create code like the rest of us.  A constant battle I know. I see another new raw memory allocation which I really think we should avoid. Yes I know it's in the same basic block but later you might through a warning or refactor and then leak that memory. It happens. Also, we really like `unsigned` in MOOSE. `int` feels very C-like to us not C++.

File: framework/src/utils/MooseUtils.C (hunk 3 above)
Comment (rwcarlsen) [reply framework/src/utils/MooseUtils.C]: I pushed a commit with the source where I copied the code from.  Since I didn't write the code, I'd err on the side of not changing it, but I don't feel strongly either way.  int makes it easier to test that this function never returns negative values though :-P

Comment (dschwen) [reply framework/src/utils/MooseUtils.C]: To test that it _never_ returns negative values, you'd have to have it calculate _every_ possible distance. Good luck with that...

File: framework/src/utils/MooseUtils.C [hunk 5]
```diff
@@ -31,10 +31,44 @@
 
 // System includes
 #include <sys/stat.h>
+#include <numeric>
 
 namespace MooseUtils
 {
 
+// this implementation is copied from
+// https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#C.2B.2B
```
Comment (permcody) [inline framework/src/utils/MooseUtils.C]: Ok for the record, this is terrible C++11. It's cross between old C and C++11:
https://xkcd.com/1513/

**Review by permcody — APPROVED** [review]
