### PR TITLE
Catch error thrown by LinearInterpolation object

### LINKED ISSUE #9498: OpenMPI error in FunctionDT
### Description of the enhancement or error report
Creating a FunctionDT TimeStepper with time_t and time_dt inputs of different sizes causes an unexpected MPI communication error such as

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

There should be a test in the constructor to check that time_t and time_dt have the same size (or where-ever that bugs occurs, I am not sure)

### Rationale for the enhancement or information for reproducing the error
This would provide the user a clearer (and less scary) explanation of why his/her input file causes an error, and what to modify in its input file.

### Identified impact
Changes to FunctionDT TimeStepper or one of its attributes (I am not sure where it happens).

### PR DESCRIPTION
**Pull request by permcody**
close #9498

### CODE REVIEW

File: framework/src/timesteppers/FunctionDT.C [hunk 1]
```diff
@@ -41,12 +41,20 @@ FunctionDT::FunctionDT(const InputParameters & parameters)
...
     _growth_factor(getParam<Real>("growth_factor")),
     _cutback_occurred(false),
     _min_dt(getParam<Real>("min_dt")),
     _interpolate(getParam<bool>("interpolate"))
 {
+  try
+  {
+    _time_ipol = libmesh_make_unique<LinearInterpolation>(_time_t, _time_dt);
+  }
+  catch (std::domain_error & e)
```
Comment (jwpeterson) [inline framework/src/timesteppers/FunctionDT.C]: Side issue, I found it interesting that we throw two different types of std::exceptions (std::out_of_range and std::domain_error) from the `LinearInterpolation` but based on the [docs](http://en.cppreference.com/w/cpp/error/domain_error) it would seem that they are all actually domain errors.

**Review by jwpeterson — APPROVED** [review]
