### PR TITLE
Fix parallel communication issues in DiscreteNucleation

### LINKED ISSUE #5512: Parallelization issue in Discrete Nucleation
Parallel domain boundaries should be transparent (by design)  to inserted nuclei in the map. This is not the case currently. I need to fix this bug.

### PR DESCRIPTION
**Pull request by dschwen**
The discrete nucleation system updates a nucleus map on demand, iff changes were made to either nucleus list or mesh. The changes flag for the nucleus list was not gathered across MPI tasks (and threads) so the update was only triggered in the domain where the change occurred. However, changes in neighboring domains can affect a local domain (if the nuclei have large radii).

The Map user object was also missing a zeroing of a vector which is has to be performed for each element.

Closes #5512

### CODE REVIEW

File: modules/phase_field/src/userobjects/DiscreteNucleationInserter.C [hunk 1]
```diff
@@ -79,6 +79,7 @@ DiscreteNucleationInserter::threadJoin(const UserObject &y)
   // combine _local_nucleus_list entries from all threads on the current process
   const DiscreteNucleationInserter & uo = static_cast<const DiscreteNucleationInserter &>(y);
   _local_nucleus_list.insert(_local_nucleus_list.end(), uo._local_nucleus_list.begin(), uo._local_nucleus_list.end());
+  _changes_made += uo._changes_made;
```
Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: I've seen this pattern in framework. I wasn't sure if that works (i.e. If all threads sum this up and hand out the already summed up value won't this overcount and have a race condition?!)

Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: Ok, got it, this is only called on thread 0 with the UOs for thread 1..N passed in!

**Comment by dschwen** [comment]
I had to loosen the CSV diff tolerance quite a bit. It is unclear to me how it could vary so much between architectures.

**Comment by dschwen** [comment]
Hmm, the tests pass on my machine and on rod...

File: modules/phase_field/src/userobjects/DiscreteNucleationInserter.C [hunk 2]
```diff
@@ -78,13 +81,18 @@ DiscreteNucleationInserter::threadJoin(const UserObject &y)
...
 
 void
 DiscreteNucleationInserter::finalize()
 {
-  // here we need to combine all _local_nucleus_list into a the _global_nucleus_list
-  _global_nucleus_list = _local_nucleus_list;
+  // add the _local_nucleus_list of thread zero
+  _global_nucleus_list.insert(_global_nucleus_list.end(), _local_nucleus_list.begin(), _local_nucleus_list.end());
+  // combine _global_nucleus_lists from all MPI ranks
   _communicator.allgather(_global_nucleus_list);
```
Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: The error is right here @jwpeterson, allgather should turn ```_global_nucleus_list``` into a vector that is a concatenation of all local ```_global_nucleus_list``` vectors. This works on my machine, but on the build box, I get only the entries from processor 0 and the rest filled with zeroes or undefined values. I output the local copies of ```_global_nucleus_list``` before the allgather and they contain the correct values. What could cause allgather to fail?!

Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: Ok, this might be a genuine libMesh issue! I'm not getting just zeroes, but I'm getting values scrambled form other positions in my compound type that my std::vector is templated on (it is an ```std::pair<Real, Point>```).

Comment (jwpeterson) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: `_global_nucleus_list` is a `std::vector` of `std::pair<Real, Point>`?  Yeah, there's a good chance one compiler is deducing the wrong template function for this or something.  Are you using different MPI implementations (openMPI vs. mpich) on the two machines?

Comment (dschwen) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: Idk what is installed on hpcbuild? On the Mac I'm using the redistributable.

Comment (jwpeterson) [inline modules/phase_field/src/userobjects/DiscreteNucleationInserter.C]: > Idk what is installed on hpcbuild?

It depends on the module you had loaded.

> On the Mac I'm using the redistributable.

Again, it depends on the module, the redistributable contains both MPIs.

**Comment by permcody** [comment]
Did you figure this out @jwpeterson? Just curious

**Comment by jwpeterson** [comment]
It kind of fell off my radar since @dschwen got the workaround working.  I didn't replicate the issue with a test code yet, but will put it on my TODO list.
