### PR TITLE
LaRomance substepping

### LINKED ISSUE #14757: Substepping in radial return models
## Reason
This design request is motivated by attempts to use the constitutive LAROMANCE models with a large eigenstrain: even small timesteps fail to run through the ROM class when the eigenstrain is sufficiently large. A substepping capability to incrementally add the eigenstrain may be helpful in this use case.

## Design
Add a capability to increment the trial strain guess, thus mitigating the difference between the trial stress guess and the yield surface. This capability should also include the ability to increment additively decomposed state variables local to the individual constitutive model classes.

## Impact
Larger ranges of applied strains (e.g. eigenstrain, larger strain rate) can be used when running simulations with radial return type constitutive models.

### PR DESCRIPTION
**Pull request by recuero**
## Reason
Allow robust and error based simulation of reduced-order creep models (i.e. LaRomance)

## Design
Follow the substepping design by @dewenyushu. In general, the creep model will be responsible for managing stateful materials when substepping is used.

## Impact
More robust practical simulations including advanced creep models.

This PR aspires to close #14757.

### CODE REVIEW

File: modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C [hunk 1]
```diff
@@ -390,6 +390,9 @@ ADComputeMultipleInelasticStress::computeAdmissibleState(
     ADRankTwoTensor & elastic_strain_increment,
     ADRankTwoTensor & inelastic_strain_increment)
 {
+  // Properly update material properties (necessary if substepping is employed).
+  _models[model_number]->zeroOutIncrementalMaterialProperties();
```
Comment (dewenyushu) [inline modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:394]: Do we have the mechanism to prevent calling this if sub-stepping is not enabled for one of the models? 

The users may get into cases when one/several of the multiple inelastic models do not support sub-stepping.

File: modules/tensor_mechanics/include/materials/StressUpdateBase.h [hunk 2]
```diff
@@ -157,6 +157,11 @@ class StressUpdateBaseTempl : public Material
    */
   virtual void storeIncrementalMaterialProperties(){};
 
+  /**
+   * Zero out material properties. Useful for substepping with inelastic models.
+   */
+  virtual void zeroOutIncrementalMaterialProperties(){};
```
Comment (dewenyushu) [inline modules/tensor_mechanics/include/materials/StressUpdateBase.h:163]: If this is called, does it mean the user is trying to do sub-stepping but the model does not support it? If so, maybe we should throw an error or something?

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C [hunk 3]
```diff
@@ -90,13 +97,24 @@ RadialReturnStressUpdateTempl<is_ad>::calculateNumberSubsteps(
...
+
+      if (ratio > _substep_tolerance)
+        number_of_substeps = std::ceil(ratio / _substep_tolerance);
+    }
+    else
+    {
+      const Real accurate_time_step = _dt * _substep_tolerance / effective_elastic_strain;
+
+      if (_dt > accurate_time_step)
+        number_of_substeps = std::ceil(_dt / accurate_time_step);
```
Comment (dewenyushu) [inline modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:113]: It seems like this can be refactored so that we do not need `_dt` here:

```
      const Real ratio = _substep_tolerance / effective_elastic_strain;

      if (_ratio<1.0)
        number_of_substeps = std::ceil(1.0 / ratio);
```

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C [hunk 4]
```diff
@@ -277,6 +296,9 @@ RadialReturnStressUpdateTempl<false>::updateStateSubstep(RankTwoTensor & strain_
                                                          RankFourTensor & tangent_operator)
 {
   const unsigned int total_substeps = calculateNumberSubsteps(strain_increment);
+  _number_of_substeps[_qp] = total_substeps;
+
+  Moose::out << "Number of substeps: " << total_substeps << "\n";
```
Comment (dewenyushu) [inline modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:301]: This info will be printed our for all `_qp`, right? Maybe this is too much info? Are we going to store this in an additional material property?

**Review by dewenyushu — COMMENTED** [review]
Really glad that you get this to work. Just a few comments.

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C (hunk 4 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:301]: Definitely too much information! That must go!

Comment (recuero) [reply modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:301]: Yeah, the one test should be outputting the number of steps to the exodus file.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 5]
```diff
@@ -856,30 +895,34 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::computeStressFinalize(
...
     const Real negative_cell_dislocations = MetaPhysicL::raw_value(_cell_dislocations[_qp]);
     const Real negative_wall_dislocations = MetaPhysicL::raw_value(_wall_dislocations[_qp]);
     _cell_dislocations[_qp] = _old_input_values[_cell_output_index];
     _wall_dislocations[_qp] = _old_input_values[_wall_output_index];
-    mooseException("The negative values of the cell dislocation density, ",
-                   negative_cell_dislocations,
-                   ", and/or wall dislocation density, ",
-                   negative_wall_dislocations,
-                   ". Cutting timestep.");
+    mooseError("The negative values of the cell dislocation density, ",
```
Comment (lynnmunday) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:912]: This will no longer cut the timestep so you can get rid of that part of that part of the error.

Comment (lynnmunday) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:912]: Maybe this error should be after the verbose output.

Comment (recuero) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:912]: This was a local change I made to make sure I didn't run into these undesirable situations while testing or creating tests (I pushed this as a draft to trigger CIVET testing). I will revert this back to being an exception to avoid any regression in behavior.

File: modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C (hunk 1 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:394]: This would become an empty call up in the hierarchy if the model doesn't support substepping. Calling it should be safe for any model.

File: modules/tensor_mechanics/include/materials/StressUpdateBase.h (hunk 2 above)
Comment (recuero) [reply modules/tensor_mechanics/include/materials/StressUpdateBase.h:163]: No, you can always call this method. It may or may not be implemented downstream, but that's responsibility of the model. I do think we are not handling an error when the user selects `use_substep = true` and the model doesn't support it (it does not inherit that flag). I'll look into creating that paramError.

**Comment by recuero** [comment]
@sapitts do we have an example of those numerically challenging reduced order models with large eigenstrains (#14757 - to be used with the existing SS316H model)? It may be good to analyze/include one test with a more meaningful practical setup.

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C [hunk 6]
```diff
@@ -179,6 +179,15 @@ ComputeMultipleInelasticStress::initialSetup()
...
                    " is not compatible with ComputeMultipleInelasticStress");
+
+  // This check prevents the hierarchy from silently skipping substepping without informing the user
+  for (unsigned int model_number = 0; model_number < _num_models; ++model_number)
+  {
+    const bool use_substep = _models[model_number]->substeppingCapabilityRequested();
+    if (use_substep && _models[model_number]->substeppingCapabilityEnabled() == false)
+      mooseError("Usage of substepping has been requested, but this inelastic model does not "
+                 "implement substepping yet.");
+  }
```
Comment (dewenyushu) [inline modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:190]: This is great. Thanks @recuero for catching this design defect and making correspondence change.

Comment (recuero) [reply modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:190]: Thank you for putting the substepping framework together! I think it's going to see good use in many applied cases.

File: modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C (hunk 1 above)
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:394]: if it is only necessary when substepping is employed, maybe you could add 
```
if (_use_substep)
```

File: modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C [hunk 7]
```diff
@@ -92,6 +92,18 @@ ADPowerLawCreepStressUpdate::computeStrainEnergyRateDensity(
...
+void
+ADPowerLawCreepStressUpdate::computeStressFinalize(const ADRankTwoTensor & plastic_strain_increment)
+{
+  _creep_strain[_qp] += plastic_strain_increment;
+}
+
+void
+ADPowerLawCreepStressUpdate::zeroOutIncrementalMaterialProperties()
+{
+  _creep_strain[_qp] = _creep_strain_old[_qp];
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C:104]: same here.

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C [hunk 8]
```diff
@@ -466,6 +475,9 @@ ComputeMultipleInelasticStress::computeAdmissibleState(unsigned model_number,
                                                        RankTwoTensor & inelastic_strain_increment,
                                                        RankFourTensor & consistent_tangent_operator)
 {
+  // Properly update material properties (necessary if substepping is employed).
+  _models[model_number]->zeroOutIncrementalMaterialProperties();
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:479]: same here.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 9]
```diff
@@ -156,8 +156,17 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::LAROMANCEStressUpdateBaseTempl(
     _extrapolation(this->template declareProperty<Real>("ROM_extrapolation")),
 
     _derivative(0.0),
-    _old_input_values(3)
+    _old_input_values(3),
+    _wall_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "wall_dislocations_step")),
+    _cell_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "cell_dislocations_step")),
+    _plastic_strain_increment(RankTwoTensor::Identity()),
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:164]: why is it initialized as Identify instead of zero?

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h [hunk 10]
```diff
@@ -526,6 +530,17 @@ class LAROMANCEStressUpdateBaseTempl : public RadialReturnCreepStressUpdateBaseT
...
+  ///@{Material properties accumulated at substeps
+  GenericMaterialProperty<Real, is_ad> & _wall_dislocations_step;
+  GenericMaterialProperty<Real, is_ad> & _cell_dislocations_step;
+  ///@}
+
+  /// Total plastic strain increment in step (summing substep contributions)
+  RankTwoTensor _plastic_strain_increment;
+
+  /// Material capturing number of substeps. If substepping isn't used will default to one.
+  MaterialProperty<Real> & _number_of_substeps;
```
Comment (jiangwen84) [inline modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:543]: why is it `Real` type? not `unsigned int`

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C [hunk 11]
```diff
@@ -276,10 +294,10 @@ RadialReturnStressUpdateTempl<false>::updateStateSubstep(RankTwoTensor & strain_
                                                          bool compute_full_tangent_operator,
                                                          RankFourTensor & tangent_operator)
 {
-  const unsigned int total_substeps = calculateNumberSubsteps(strain_increment);
+  const unsigned int total_number_steps = calculateNumberSubsteps(strain_increment);
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:297]: to be consistent, `total_number_substeps` would be better?

File: modules/tensor_mechanics/src/materials/StressUpdateBase.C [hunk 12]
```diff
@@ -109,7 +109,7 @@ TangentCalculationMethod
 StressUpdateBaseTempl<true>::getTangentCalculationMethod()
 {
   mooseError(
-      "getTangentCalculationMethod called: no tangent calculationg is needed while using AD");
+      "getTangentCalculationMethod called: no tangent matrix calculation is needed while using AD");
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/StressUpdateBase.C:112]: suggestion: no tangent **moduli** calculation

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C [hunk 13]
```diff
@@ -90,13 +97,24 @@ RadialReturnStressUpdateTempl<is_ad>::calculateNumberSubsteps(
...
-    const Real ratio = effective_elastic_strain / _max_inelastic_increment;
 
-    if (ratio > _substep_tolerance)
-      substep_number = std::ceil(ratio / _substep_tolerance);
+    if (!_use_substep_integration_error)
+    {
+      const Real ratio = effective_elastic_strain / _max_inelastic_increment;
+
+      if (ratio > _substep_tolerance)
+        number_of_substeps = std::ceil(ratio / _substep_tolerance);
```
Comment (jiangwen84) [inline modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:106]: We probably need to set up an upper limit for the number_of_substeps too. According to my experience with crystal plasticity, when number of sub stepping is greater than 10, it no longer helps the convergence and would slow down the calculation. I do know what is a best number to use here though. :-)

**Review by jiangwen84 — DISMISSED** [review]
Looks great. Several minor comments.

File: modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C [hunk 14]
```diff
@@ -94,6 +94,18 @@ PowerLawCreepStressUpdate::computeStrainEnergyRateDensity(
...
+void
+PowerLawCreepStressUpdate::computeStressFinalize(const RankTwoTensor & plastic_strain_increment)
+{
+  _creep_strain[_qp] += plastic_strain_increment;
+}
+
+void
+PowerLawCreepStressUpdate::zeroOutIncrementalMaterialProperties()
+{
+  _creep_strain[_qp] = _creep_strain_old[_qp];
```
[the remark this answers is not in the document]
Comment (recuero) [reply modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C:106]: This method can do different things in different material models. The idea is to provide the creep model the ability of including substepping in its logic. LaRomance sets incremental properties to zero, whereas this method resets `creep_strain`, thereby zeroing out the existing incremental values. I will replace the name of this method with `resetIncrementalMaterialProperties`.

File: modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C (hunk 1 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C:394]: This method will provide the value of material properties (which will be zero or "reset") if substepping is not selected. Creep models that include substepping will make use of this method, even if the user has not selected it.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 9 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:164]: Because I was confused about the RankTwoTensor initialization options. I assume `::initNone` is the right option here.

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h (hunk 10 above)
Comment (recuero) [reply modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:543]: Should be `unsigned int` but the materialOutputAction somehow can't handle it. It gives me an error: 

``` *** ERROR ***
test:rom_stress_update.ADrom/lower_limit_extrapolated: The types for total 1 material properties:
test:rom_stress_update.ADrom/lower_limit_extrapolated:   number_of_substeps
test:rom_stress_update.ADrom/lower_limit_extrapolated: are not supported for automatic output by MaterialOutputAction. *** ERROR ***
```
There are very few instances of `MaterialProperty<unsigned int>` in MOOSE.

File: modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C (hunk 13 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:106]: This is a great point. @dewenyushu and I discussed this. It'd be good to know the reason why increased number of substeps doesn't help in some of these cases. I'd think that BCs and other loading may play a role in this, i.e. it may depend on the simulation setup. We can create a parameter that the user can override and throw an exception if it turns out the number is larger? I will include this change and see if there are any failures.

Comment (recuero) [reply modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C:106]: A user may want to achieve a particular numerical creep integration error at the expense of more substeps... We should probably be generous with the default number of substeps. I can try 25 initially.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 15]
```diff
@@ -489,7 +528,7 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::checkInputWindow(const GenericReal<is_ad>
     switch (behavior)
     {
       case WindowFailure::WARN:
-        mooseWarning(msg.str());
+        mooseDoOnce(mooseWarning(msg.str()));
```
Comment (recuero) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:531]: @tophmatthews are you okay with this change? We were thinking the warning output can become too invasive when we evaluate the model outside the range and that, hopefully, printing it out once would be enough to alert the user. Let me know if you think otherwise and I'll revert it.

**Comment by recuero** [comment]
@jiangwen84 thanks for the review. @lynnmunday volunteered to give this a try on some cool models he prepared for a project. So, whenever you are okay with the PR, it can be merged.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 16]
```diff
@@ -156,8 +156,17 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::LAROMANCEStressUpdateBaseTempl(
...
     _derivative(0.0),
-    _old_input_values(3)
+    _old_input_values(3),
+    _wall_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "wall_dislocations_step")),
+    _cell_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "cell_dislocations_step")),
+    _plastic_strain_increment(RankTwoTensor::Identity()),
+    _number_of_substeps(
+        this->template declareProperty<Real>(this->_base_name + "number_of_substeps"))
```
[the remark this answers is not in the document]
Comment (recuero) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:166]: See https://github.com/idaholab/moose/pull/19414#discussion_r754470870.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 15 above)
Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:531]: Isn't mooseWarning already wrapped in a DoOnce?

**Comment by tophmatthews** [comment]
Just for my own curiosity, the initial capability was setup by @dewenyushu a year or so ago, and this is the implementation of that capability for creep models?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 15 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:531]: `mooseDeprecatedStream` and `mooseInfoStream` are, but not `mooseWarning`.

Comment (tophmatthews) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:531]: Yeah, this is probably fine. We're working hard on removing the need for this, so seems good to me.

**Comment by tophmatthews** [comment]
Super stoked to see the implementation here! Certainly for metallic fuel problems, the max inelastic timestep really kills our wall time by requiring many small timesteps.

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h (hunk 10 above)
Comment (jiangwen84) [reply modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:543]: That is wired. My suggestion is either to make `unsigned int` work with `materialOutputAction` or disable material output for the number of substeps using `materialOutputAction`. You can manually output substeps using an auxkernel.

**Comment by recuero** [comment]
There are a number of design decisions to be made, for auxiliary kernels. The existing ones are already templated with AD types, which are not compatible with `Int`. A hierarchy parallel to `MaterialAuxBase` appears necessary (not just creating `MaterialUnsignedIntAux`)

**Comment by dschwen** [comment]
My suggestion would be to create a universal `MaterialIntegerAux` AuxKernel that tries all integer flavors (using `haveMaterialProperty<>()` (e.g. `int`, `unsigned int`, `char`, `short`, `long`, `long long`, `unsigned short`, etc.)

**Comment by recuero** [comment]
Anyway, this is all quite of an excursion from the purpose of this PR. I'll open a separate one when I get to it.

**Comment by lynnmunday** [comment]
Can you merge this without fixing the unsigned int material output and then fix it later?

**Comment by jiangwen84** [comment]
> Can you merge this without fixing the unsigned int material output and then fix it later?

I think @recuero can use `unsigned int` without outputting them. Another PR to add the material output capability for `unsigned int`. Any thoughts?

**Comment by recuero** [comment]
>can use `unsigned int` without outputting them

Changes are required to the MaterialsOutputAction to use `unsigned int` in the material property. Even tests that were not explicitly outputting the variable were failing with the same message. As this PR stands right now we are casting an integer into a real for output purposes. AFAICS this should not cause problems other than a pesky "x.00" in the output maybe.

I agree with @lynnmunday that the use and testing of the capability in practical problems should have priority in this case.

**Comment by jiangwen84** [comment]
> > can use `unsigned int` without outputting them
> 
> Changes are required to the MaterialsOutputAction to use `unsigned int` in the material property. Even tests that were not explicitly outputting the variable were failing with the same message. As this PR stands right now we are casting an integer into a real for output purposes. AFAICS this should not cause problems other than a pesky "x.00" in the output maybe.
> 
> I agree with @lynnmunday that the use and testing of the capability in practical problems should have priority in this case.

Ok. I am fine with using `Real`. I will leave @dschwen for the final merge. 

BTW, @lynnmunday can pull down your PR and test it locally without waiting this being merged.

File: modules/tensor_mechanics/doc/content/source/materials/RadialReturnStressUpdate.md [hunk 17]
```diff
@@ -75,6 +75,41 @@ Users can print out any of these strains and stresses using the `RankTwoAux` as
 described on the [Visualizing Tensors](/tensor_mechanics/VisualizingTensors.md)
 page.
 
+## Substepping capability
+
+Regular use of the radial return mapping triggers one instance of the return to the yield surface that spans
+the entire system wide time step. While the material time step limiter discussed in [ComputeMultipleInelasticStress](ComputeMultipleInelasticStress.md) can
+effectively limits the time step size to achieve the desired convergence or integration error properties, it does so at
```
Comment (dschwen) [inline modules/tensor_mechanics/doc/content/source/materials/RadialReturnStressUpdate.md:82]:
```suggestion
effectively limit the time step size to achieve the desired convergence or integration error properties, it does so at
```

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h [hunk 18]
```diff
@@ -526,6 +530,17 @@ class LAROMANCEStressUpdateBaseTempl : public RadialReturnCreepStressUpdateBaseT
...
+
+  ///@{Material properties accumulated at substeps
+  GenericMaterialProperty<Real, is_ad> & _wall_dislocations_step;
+  GenericMaterialProperty<Real, is_ad> & _cell_dislocations_step;
+  ///@}
+
+  /// Total plastic strain increment in step (summing substep contributions)
+  RankTwoTensor _plastic_strain_increment;
+
+  /// Material capturing number of substeps. If substepping isn't used will default to one.
```
Comment (dschwen) [inline modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:542]:
```suggestion
  /// Material property capturing number of substeps for output purposes (defaults to one if substepping isn't used) ```

File: modules/tensor_mechanics/include/materials/StressUpdateBase.h [hunk 19]
```diff
@@ -141,6 +141,13 @@ class StressUpdateBaseTempl : public Material
    */
   virtual bool substeppingCapabilityEnabled() { return false; }
 
+  /**
+   * Has the user requested usage of (possibly) implemented substepping capability for inelastic
+   * models.
+   *
```
Comment (dschwen) [inline modules/tensor_mechanics/include/materials/StressUpdateBase.h:147]:
```suggestion
```

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C [hunk 20]
```diff
@@ -179,6 +179,15 @@ ComputeMultipleInelasticStress::initialSetup()
     paramError("damage_model",
                "Damage Model " + _damage_model->name() +
                    " is not compatible with ComputeMultipleInelasticStress");
+
+  // This check prevents the hierarchy from silently skipping substepping without informing the user
+  for (unsigned int model_number = 0; model_number < _num_models; ++model_number)
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:184]: Just a _suggestion_ (automatically uses the correct type for the counter - requires `#include "libmesh/int_range.h"`).

```suggestion
  for (auto model_number: index_range(_models))
```

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C [hunk 21]
```diff
@@ -179,6 +179,15 @@ ComputeMultipleInelasticStress::initialSetup()
...
+  {
+    const bool use_substep = _models[model_number]->substeppingCapabilityRequested();
+    if (use_substep && _models[model_number]->substeppingCapabilityEnabled() == false)
+      mooseError("Usage of substepping has been requested, but this inelastic model does not "
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:188]: How will the user know what "this inelastic model" is if multiple models are used?

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C [hunk 22]
```diff
@@ -466,6 +475,9 @@ ComputeMultipleInelasticStress::computeAdmissibleState(unsigned model_number,
                                                        RankTwoTensor & inelastic_strain_increment,
                                                        RankFourTensor & consistent_tangent_operator)
 {
+  // Properly update material properties (necessary if substepping is employed).
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:478]: "properly update" is not very descriptive. Is it maybe "reset deformation state to the beginning of the increment" or something along those lines?

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 23]
```diff
@@ -156,8 +156,17 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::LAROMANCEStressUpdateBaseTempl(
     _extrapolation(this->template declareProperty<Real>("ROM_extrapolation")),
 
     _derivative(0.0),
-    _old_input_values(3)
+    _old_input_values(3),
+    _wall_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "wall_dislocations_step")),
+    _cell_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
+        this->_base_name + "cell_dislocations_step")),
+    _plastic_strain_increment(RankTwoTensor::initNone),
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:164]: Why `initNone` if you zero it out below? You could just do 
```suggestion
    _plastic_strain_increment(),
```

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 24]
```diff
@@ -349,6 +358,30 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::maximumPermissibleValue(
   return effective_trial_stress / this->_three_shear_modulus * 0.999999;
 }
 
+template <bool is_ad>
+void
+LAROMANCEStressUpdateBaseTempl<is_ad>::resetIncrementalMaterialProperties()
+{
+
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:365]:
```suggestion
```

File: modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h (hunk 18 above)
Comment (recuero) [reply modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h:542]: Check

File: modules/tensor_mechanics/include/materials/StressUpdateBase.h (hunk 19 above)
Comment (recuero) [reply modules/tensor_mechanics/include/materials/StressUpdateBase.h:147]: Done

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C (hunk 20 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:184]: I just _made_ that change.

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C (hunk 21 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:188]: Should be addressed now.

File: modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C (hunk 22 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C:478]: Yeah, it's resetting material properties.

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C (hunk 23 above)
Comment (recuero) [reply modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:164]: Ok

File: modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C [hunk 25]
```diff
@@ -161,7 +161,7 @@ LAROMANCEStressUpdateBaseTempl<is_ad>::LAROMANCEStressUpdateBaseTempl(
         this->_base_name + "wall_dislocations_step")),
     _cell_dislocations_step(this->template declareGenericProperty<Real, is_ad>(
         this->_base_name + "cell_dislocations_step")),
-    _plastic_strain_increment(RankTwoTensor::initNone),
+    _plastic_strain_increment(),
```
Comment (dschwen) [inline modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C:164]: You don't need to zero below

**Review by dschwen — APPROVED** [review]
