### PR TITLE
ReferenceResidualProblem behavior when solution_variables isn't provided

### LINKED ISSUE #14334: ReferenceResidualProblem crashes if grouping is used without specifying solution variables
## Bug Description
In the transition to the tagging system, and issue was introduced in ReferenceResidual problem in which the code will crash if the user specifies `group_variables` but not `solution_variables`.

Also, the output of the individual variables' residuals and corresponding reference quantities was inadvertently removed except for when grouping is used.

## Steps to Reproduce
See above. One simply needs to use ReferenceResidualProblem with `group_variables` specified but without specifying `solution_variables`. The code hangs for a while, and then dies with signal 9.

## Impact
This is mostly an annoyance. It does not result in any incorrect calculations.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #14334

Fix a crash when group_variables was specified without solution_variables

Make use of solution_variables with tagging system deprecated, and
remove from it from all tests.

### CODE REVIEW

File: framework/include/problems/ReferenceResidualProblem.h [hunk 1]
```diff
@@ -43,13 +43,25 @@ class ReferenceResidualProblem : public FEProblem
                             const PetscInt nfuncs,
                             const PetscInt max_funcs,
                             const PetscBool force_iteration,
-                            const Real ref_resid,
+                            const Real initial_residual_before_preset_bcs,
```
Comment (lindsayad) [inline framework/include/problems/ReferenceResidualProblem.h]: Was this just poorly named before?

**Review by lindsayad — APPROVED** [review]

File: framework/include/problems/ReferenceResidualProblem.h (hunk 1 above)
Comment (bwspenc) [reply framework/include/problems/ReferenceResidualProblem.h]: Yes.  I changed the name to match the names of parameters in FEProblemBase to make it more clear what it is.  I'm probably the one responsible for the original `ref_resid` name. When I was going through the code, I couldn't remember what that was exactly, so I think this makes it more clear.
