### PR TITLE
Fix 1D contact search issue

### LINKED ISSUE #8404: 1D contact failures when y != 0
### Description of the enhancement or error report
We are running 1D problems with a series of 1D element strips that are aligned in the x direction, but may have nonzero y coordinate.  We are seeing failures in the inverse mapping when the DiracKernel used for thermal contact is trying to call `addPoint()`.  The point that it gets from the contact search always has zero for the y coordinate even if the element it is associated with has a nonzero y coordinate.

### Rationale for the enhancement or information for reproducing the error
This is reproducible by creating a long 1.5D BISON model.

### Identified impact
There is a problem with the contact search for these 1D cases.  The contact points that it is providing are wrong.

### PR DESCRIPTION
**Pull request by bwspenc**
closes #8404

### CODE REVIEW

**Comment by bwspenc** [comment]
@jwpeterson @novasr

**Comment by bwspenc** [comment]
Not sure why, but the tests don't seem to be getting run on this.  They ran initially, and then I did a push -f, and they didn't get re-run.

**Comment by permcody** [comment]
I just had the same problem. @brianmoose is looking at it.

**Comment by brianmoose** [comment]
It looks like tests got run. Is b3670f not your current commit? It looks like it is but there seems to be some GitHub problems...

**Comment by bwspenc** [comment]
@brianmoose They did eventually run, but they fired off about a half hour after I pushed an update.

File: framework/src/geomsearch/FindContactPoint.C [hunk 1]
```diff
@@ -54,70 +55,49 @@ findContactPoint(PenetrationInfo & p_info,
...
-    p_info._normal = Point(left == nearestNode ? -1 : 1, 0, 0);
+    const Node * nearest_node = side->node_ptr(0);
+    p_info._closest_point = *nearest_node;
+    p_info._closest_point_ref = master_elem->master_point(master_elem->get_node_index(nearest_node));
+    std::vector<Point> elem_points = {p_info._closest_point_ref};
+    fe_elem->reinit(master_elem, &elem_points);
+
+    const std::vector<RealGradient> & elem_dxyz_dxi = fe_elem->get_dxyzdxi();
+    p_info._normal = elem_dxyz_dxi[0];
+    if (nearest_node->id() == master_elem->node(0))
```
Comment (jwpeterson) [inline framework/src/geomsearch/FindContactPoint.C]: `Elem::node()` is deprecated, please use the better-named `Elem::node_id()` instead.

File: framework/include/geomsearch/FindContactPoint.h [hunk 2]
```diff
@@ -26,8 +26,9 @@ namespace Moose
 
 void
 findContactPoint(PenetrationInfo & p_info,
-                 FEBase * _fe,
-                 FEType & _fe_type,
+                 FEBase * fe_elem,
+                 FEBase * fe_side,
+                 FEType & fe_side_type,
```
Comment (jwpeterson) [inline framework/include/geomsearch/FindContactPoint.h]: Renaming refactoring like this should ideally go in a separate commit, so it doesn't get mixed up with the actual fix you're making...  That being said, it's not too confusing in this case so I won't hold up the merge based on this comment ;0)

**Review by jwpeterson — CHANGES_REQUESTED** [review]

File: framework/include/geomsearch/FindContactPoint.h (hunk 2 above)
Comment (bwspenc) [inline framework/include/geomsearch/FindContactPoint.h]: I see your point.  In this case, though, the name change kind of goes hand in hand with the fix. I'm passing in another FEBase object into this function, and I needed to make the distinction between the one associated with the element and the one associated with the side.  Since there was previously only one such object, it wasn't named in a way that indicated that it was associated with the side.

**Comment by bwspenc** [comment]
@jwpeterson I addressed the one issue you pointed out, so I think this is ready to go, unless you'd really like me to go back and break the renaming stuff out into a separate commit.

**Review by jwpeterson — APPROVED** [review]
