### PR TITLE
Reinit interface materials for boundary aux kernel computation

### LINKED ISSUE #14387: RealMaterialAux does not trigger the evaluation of interfacematerial
## Bug Description
If one uses an interfacematerial and ask to pull out interfacematerial properties via `MaterialRealAux` the interface material will never be evaluated.
Most likely there is something missing in the loops
@lindsayad  

## Steps to Reproduce
just go into `test/tests/materials/interface_materials/interface_value_material.i` comment the interface kernel block and the InterfaceValuaMaterial::computeQpProperties will not be executed. Check the exodus and all the interface material property will be 0

## Impact
Prevents user to compute interface material properties if the `interfacematerial` is not associated to an InterfaceKernel

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #14387

### CODE REVIEW

File: framework/src/loops/ComputeElemAuxBcsThread.C [hunk 1]
```diff
@@ -91,6 +93,13 @@ ComputeElemAuxBcsThread<AuxKernelType>::operator()(const ConstBndElemRange & ran
           _problem.reinitMaterialsFace(elem->subdomain_id(), _tid);
 
           _problem.reinitMaterialsBoundary(boundary_id, _tid);
+
+          if (neighbor && neighbor->active())
```
Comment (arovinelli) [inline framework/src/loops/ComputeElemAuxBcsThread.C]: shouldn't these two cehcks be nested?,
like 

```
if (neighbor != nullptr )
  if(neighbor->active())
```

File: framework/src/loops/ComputeElemAuxBcsThread.C [hunk 2]
```diff
@@ -99,6 +108,8 @@ ComputeElemAuxBcsThread<AuxKernelType>::operator()(const ConstBndElemRange & ran
         if (_need_materials)
         {
           _problem.swapBackMaterialsFace(_tid);
+          if (neighbor && neighbor->active())
```
Comment (arovinelli) [inline framework/src/loops/ComputeElemAuxBcsThread.C]: see above

File: test/tests/materials/interface_material/tests [hunk 3]
```diff
@@ -29,4 +29,12 @@
     recover = false
     method = '!dbg' # issue 12033
   []
+  [boundary_elem_aux]
+    type = Exodiff
+    input = interface_value_material_noIK.i
+    exodiff = interface_value_material_noIK_out.e
+    requirement = 'The system shall evaluate interface materials such that they can be used in boundary restricted elemental auxiliary kernels'
+    issues = '#14387'
+    design = 'Materials/index.md'
```
Comment (arovinelli) [inline test/tests/materials/interface_material/tests]: you need to add 

```
    mesh_mode = 'REPLICATED'
    recover = false
    recover = false
    method = '!dbg' # issue 12033
    method = '!dbg' # issue 12033
```

File: framework/src/loops/ComputeElemAuxBcsThread.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/loops/ComputeElemAuxBcsThread.C]: No because if `neighbor == nullptr`, then the second boolean expression is not evaluated

**Review by arovinelli — CHANGES_REQUESTED** [review]

File: framework/src/loops/ComputeElemAuxBcsThread.C (hunk 1 above)
Comment (arovinelli) [reply framework/src/loops/ComputeElemAuxBcsThread.C]: > No because if `neighbor == nullptr`, then the second boolean expression is not evaluated

Then ok, just fix the test.

File: test/tests/materials/interface_material/tests (hunk 3 above)
Comment (lindsayad) [reply test/tests/materials/interface_material/tests]: I hope not since this isn't using `BreakMeshByBlockGenerator`. This passed testing both in debug and with recover. The parallel failures should be fixed by 9ac82fe

**Review by arovinelli — APPROVED** [review]
For me it's ready to go.
I triple checked results in exodus everything seems correct to me

**Review by arovinelli — APPROVED** [review]

**Review by arovinelli — APPROVED** [review]

**Comment by arovinelli** [comment]
@lindsayad I approved this, maybe someone admin need to approve it (@permcody ?)

**Comment by permcody** [comment]
@arovinelli - External approvals are appreciated, but since you don't have merge rights it doesn't actually satisfy the "independent review" criteria which is good from and SQA standpoint. Still, it does provide the final reviewer some assurance that a technical review has been performed. Thanks!

**Review by permcody — APPROVED** [review]
