### PR TITLE
PorousFlowDarcyVelocityComponentLowerDimensional fixed for 1D+2D meshes

### LINKED ISSUE #10684: PorousFlowLowerDimensionalAux DarcyVelocity appears to segfault in 2D/1D
## Rationale

Philipp Schaedle reports a segfault when using a mesh with 2D+1D elements.  The current PorousFlow tests only use 3D+2D elements.

### PR DESCRIPTION
**Pull request by WilkAndy**
Also: an aperture parameter added so people do not keep having to divide by it to get useful answers.

Fixes #10684

### CODE REVIEW

File: modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C [hunk 1]
```diff
@@ -51,14 +46,22 @@ PorousFlowDarcyVelocityComponentLowerDimensional::computeValue()
                "only since it employs "
                "PorousFlowDarcyVelocityComponentLowerDimensional\n");
 
+  // MOOSE will automatically make grad(P) lie along the element's tangent direction
+  // but we need to project gravity in that direction too
+
+  // tang_xi is the element's tangent vector in xi direction
+  const std::vector<RealGradient> tang_xi = _assembly.getFE(FEType(), elem_dim)->get_dxyzdxi();
```
Comment (permcody) [inline modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Oops, Big error! You need to save this off as a reference!

File: modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C [hunk 2]
```diff
@@ -51,14 +46,22 @@ PorousFlowDarcyVelocityComponentLowerDimensional::computeValue()
...
-      (_gravity * (*_tang_xi[elem_dim])[_qp] / (*_tang_xi[elem_dim])[_qp].norm_sq()) *
-      (*_tang_xi[elem_dim])[_qp];
+      (_gravity * tang_xi[_qp] / tang_xi[_qp].norm_sq()) * tang_xi[_qp];
   if (elem_dim == 2)
-    tangential_gravity +=
-        (_gravity * (*_tang_eta[elem_dim])[_qp] / (*_tang_eta[elem_dim])[_qp].norm_sq()) *
-        (*_tang_eta[elem_dim])[_qp];
+  {
+    // tang_eta is the element's tangent vector in eta direction
+    const std::vector<RealGradient> tang_eta = _assembly.getFE(FEType(), elem_dim)->get_dxyzdeta();
```
Comment (permcody) [inline modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Reference here too

**Review by permcody — CHANGES_REQUESTED** [review]

File: modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C (hunk 2 above)
Comment (WilkAndy) [reply modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C]: Holy Dooley you've got a good eye, @permcody .  Thanks.

**Review by permcody — APPROVED** [review]
