### PR TITLE
Fix nonunity errors with conda stacks

### LINKED ISSUE #21873: Nonuity build results in VPP errors using conda stacs on Macs
## Bug Description
If moose is compiled using non-unity build and the conda stacks on Macs (both ARM and Intel), we get the following errors:

```
vectorpostprocessors/parallel_consistency.test ................................... [min_cpus=2] FAILED (CRASH)
vectorpostprocessors/parallel_consistency.broadcast .............................. [min_cpus=2] FAILED (CRASH)
auxkernels/vector_postprocessor_visualization.test ............................... [min_cpus=3] FAILED (CRASH)
```

## Steps to Reproduce

```
conda activate moose (latest moose environment with libmesh)
git clone https://www.github.com/idaholab/moose
cd moose/test
MOOSE_UNITY=false make -j8
./run_tests -j8
```

## Impact
Will enable libtorch-related merges due to the fact that it disables unity build in certain folders.

### PR DESCRIPTION
**Pull request by grmnptr**
Closes #21873

### CODE REVIEW

File: framework/include/vectorpostprocessors/VectorPostprocessor.h [hunk 1]
```diff
@@ -123,3 +123,56 @@ class VectorPostprocessorContext : public ReporterGeneralContext<T>
   ScatterVectorPostprocessorValue _scatter_value;
   ScatterVectorPostprocessorValue _scatter_value_old;
 };
+
```
Comment (loganharbour) [inline framework/include/vectorpostprocessors/VectorPostprocessor.h:126]: Did you try just moving it above the explicit instantiation?

Comment (grmnptr) [reply framework/include/vectorpostprocessors/VectorPostprocessor.h]: Tried and works, going with that approach.

**Review by GiudGiud — APPROVED** [review]
