### PR TITLE
Warn if material properties are retrieved after construction time

### LINKED ISSUE #5859: getMaterialProperty does not fail gracefully if requesting a non-existing property
Demonstrated in 9aa75d598. This is quite a doozey!

### PR DESCRIPTION
**Pull request by dschwen**
Getting material properties after the constructors have run (e.g. in `initialSetup`) bypasses the system consistency check. This PR warns the user about those cases.

Closes #5859

### CODE REVIEW

**Comment by permcody** [comment]
:+1:

**Comment by YaqiWang** [comment]
I have some opinions on c1fb9d7 because it will affect current Yak.

**Comment by permcody** [comment]
Well, let's hear them, or if they are causing diffs I guess we'll see them soon on the test status.

**Comment by YaqiWang** [comment]
Working on it, just to make sure you do not merge it without considering it, hehe

**Comment by dschwen** [comment]
All tests passed.Does that mean keep your opinions to yourself @YaqiWang ? ;-)

**Comment by YaqiWang** [comment]
Sure, I think this overall is good. ;-) But I will try to justify what I did and hopefully they are justified...

File: framework/src/materials/MaterialPropertyInterface.C [hunk 1]
```diff
@@ -182,3 +182,10 @@ MaterialPropertyInterface::statefulPropertiesAllowed(bool stateful_allowed)
 {
   _stateful_allowed = stateful_allowed;
 }
+
+void
+MaterialPropertyInterface::checkExecutionStage()
+{
+  if (_mi_feproblem.startedInitialSetup())
+    mooseWarning("Material properties should be gotten at construction time.");
```
Comment (friedmud) [inline framework/src/materials/MaterialPropertyInterface.C]: Overall I like these changes... but can we change the message so that it doesn't use "gotten"?  How about:

`Material properties should be retrieved during object construction.`

:smile:

**Comment by YaqiWang** [comment]
I think I am done on my comments now.

**Comment by YaqiWang** [comment]
Oh BTW, we can change that mooseWarning to mooseError to detect all violating calls. And we can make it permanent if all of them are fixed.

File: framework/src/materials/MaterialPropertyInterface.C (hunk 1 above)
Comment (dschwen) [inline framework/src/materials/MaterialPropertyInterface.C]: Ha! Yes, _retrieved_ was the word I was looking for. Will fix this.

**Comment by dschwen** [comment]
So what are the opinions on error vs. warning before I push the fixes for this?

**Comment by YaqiWang** [comment]
I'd see error. But then we will need a patch for yak, which requires a separate interface to get material properties in initial setup.

**Comment by friedmud** [comment]
I would vote for error. It would help a lot with the initial setup stuff if
we just completely disallow getting material properties at a later time.

**Comment by dschwen** [comment]
Ok, let's see what the fallout is from erroring out...

**Comment by YaqiWang** [comment]
Yes, these are expectable. I will need a new interface function for fixing them in Yak. Should not take me too long. I am surprised that only Yak is calling the functions in initial setup...

**Comment by dschwen** [comment]
What is the way forward here? Should I make this a warning again? I just do not see it happening that we add a while new set of all `getMaterialProperty` functions.

@aeslaughter had a great suggestion, which was to move the consistency check to _after_ teh initial setup phase. Is this a viable option? Would we break anything with that change?

**Comment by permcody** [comment]
That's a fair question. I don't know, it may be worth a shot.

**Comment by YaqiWang** [comment]
I'd rather have a separate interface function. I am afraid we cannot make the check after initial setup work plus we do want error be issued as soon as possible.

**Comment by dschwen** [comment]
Why is that @YaqiWang ? InitialSetup is finished immediately after construction, right? What do you lose by postponing the error check? Does it matter if the system integrity is checked a few miliseconds late? Of course the dependency resolver needs to (re-)run at that point. Do we rely on dependencies to be accurate in initialSetup @permcody ?

**Comment by permcody** [comment]
Theoretically no, in practice maybe or perhaps even probably. We have to do
some amount of execution in initial setup. We execute Materials, UOs,
AuxKernels and other objects so it's not a pure setup method. I don't think
we could make it pure either since there are just some inherit dependencies
among the initialization of the various systems. There may be some
compromises that could be made to support some checks late. This is tricky
to get right.

**Comment by YaqiWang** [comment]
@dschwen There could be quite amount of computing in initial setup, for example, a full solve multiapp on initial will be executed. There are others as mentioned by Cody. The error message comes late is not user friendly. I think we should make as a rule: issuing error asap.

In my use case, my element user object is on the entire domain but trying to get a material property only valid on part of the domain. The user object maintains a marker for protecting the material property access because it can get the list of blocks where the property is valid. It calls `getMaterialProperty` so I am not sure if the code can know it has the protection.

**Comment by YaqiWang** [comment]
@dschwen We can finish this together quickly. It has been sitting here for a little long.

**Comment by dschwen** [comment]
Yaqi, How about you call `getDefaultMaterialProperty` instead? Materials gotten through this call are exempt from the consistency check, as they return zero for properties that end up not existing. This is fine for calls made from classes that are **not** Materials.

The issue to think about is dependency resolution. Late calls to `getMaterialProperty` from **Materials** should still error out, as they bypass the dependency resolution, resulting in uninitialized/lagging material property values. This is a subtle bug that can be hard to detect.

**Comment by YaqiWang** [comment]
Right, late calls from Materials should be error out. Will `getDefaultMaterialProperty` obtain the correct reference if the property is provided somewhere? If so, I will grab your branch and make the changes in Yak.

**Comment by YaqiWang** [comment]
Also we will need a rebase before continuing.

**Comment by dschwen** [comment]
Yes, `getDefaultMaterialProperty` will do late binding to the correct property if it gets provided later on. The latest version that fixes a construction order dependence (and implements a better design) is in #6567). I will work on this branch as soon at that other PR gets merged (so that I can incorporate potential changes requests).

**Comment by YaqiWang** [comment]
OK, I see. Just let me know. It should not take me long for fixing Yak.

**Comment by dschwen** [comment]
Ok, these last two commits should implement the idea outlined above:

1. In materials never allow getting material properties after the construction stage (allowing this breaks _dependency resolution_)
2. In all other object types **only** allow `getZeroMaterialProperty`. Allowing any of the `getMaterialProperty*` routines would break _problem integrity checking_ which makes sure all requested material properties are provided. The properties gotten via `getZeroMaterialProperty` do not have to be provided as they default to a constant value of zero.

This will require YAK application patches.

**Comment by YaqiWang** [comment]
Do we have a reason we have to name this function as `getZeroMaterialProperty`? Even `getDefaultMaterialProperty` is better than it to me. How about call it `getRawMaterialPropertyReference`?

**Comment by dschwen** [comment]
No, it is not a raw reference at all. It is a material property that is zero by default, unless it is declared. I think this name is fine as it is. `getDefaultMaterialProperty` is actually confusing and may actually be removed now (it is in the `DerivativeMaterialPropertyInterface`).

**Comment by YaqiWang** [comment]
@dschwen do we have a check when calling `getZeroMaterialProperty` now if the material property is ever declared or available?

**Comment by dschwen** [comment]
No, of course not. That's the whole point. If the property is not declared
the reference points to a property that is zeroed out!

**Comment by YaqiWang** [comment]
OK, these could be better than what in my mind. With this I may not need to set the marker at all in my user object! I will start fixing Yak now.

**Comment by YaqiWang** [comment]
@dschwen You will need to let BISON team know this because I saw some BISON tests are failing with this PR too.

**Comment by dschwen** [comment]
I'll put in a Bison PR myself

**Comment by dschwen** [comment]
I'm removing the check for the _old_ and _older_ materials, since dependencies seem irrelevant for those!

**Comment by dschwen** [comment]
This takes care of Bison. Yak is still failing. Any plans @YaqiWang ?

**Comment by permcody** [comment]
Ping @YaqiWang 
It would be nice to get this into the framework. Otherwise I'll probably close this PR and let it grow moldy and stale in poor @dschwen's fork. That would probably make him sad.

**Comment by YaqiWang** [comment]
Sorry, I did not notice @dschwen 's message on Apr 20. We can create a function as `std::pair<MaterialProperty<T>*, std::set<SubdomainID> MaterialInterface::getMaterialPropertyByName()`, which can be called anywhere and bypass the check. Then we can patch Yak. How this sounds?

**Comment by dschwen** [comment]
It would need to have a different name. You cannot overload based on return value.

**Comment by YaqiWang** [comment]
Yeah, something along this line will work. Basically an interface function returns the property pointer and on what blocks it is defined. It will be completely up to user how to use these information. It is basically just an inquiring function but rather a function telling moose I (an object on blocks) want a property (defined over the blocks I am on).

**Comment by YaqiWang** [comment]
@dschwen Are you going to create this `getBlockMaterialProperty()`?

**Comment by dschwen** [comment]
What, who, me?! Are you trying to make me an accomplice for your hacks? ;-)

**Comment by YaqiWang** [comment]
So you want me add a commit on top of yours in this PR?

**Comment by dschwen** [comment]
If you make the commit I can cherry pick it in. This preserved authorship.

**Comment by YaqiWang** [comment]
@dschwen My patch is available at `git@github.com:YaqiWang/moose.git:warnconsistency_5859`. You will need to rebase this PR with the current moose devel. I have a patch for yak. What is the current procedure to patch applications when a PR breaks them?

**Comment by dschwen** [comment]
Ok, @YaqiWang , thanks! I picked it onto my branch and pushed it. If you have a patch for yak ready this will be merged in. Then the change to yak will be merged.

**Comment by YaqiWang** [comment]
So this will be merged first and then the yak patch? Will this temporarily break yak?

**Comment by dschwen** [comment]
Yak will not be broken, because it will have the old moose hash in its
submodule.

**Comment by YaqiWang** [comment]
Ok! @permcody I think this is ready for review.

**Comment by YaqiWang** [comment]
Ping @permcody , I have the patch sitting in my brunch and want to get rid of it...

**Comment by friedmud** [comment]
>brunch

You'd better get that patch out of your food!  😜

**Comment by permcody** [comment]
@YaqiWang I was gone on Friday. You said in your branch, I assume you mean on the gitlab said, Can you send me a link?

**Comment by YaqiWang** [comment]
@permcody It is in `yak_patch_material` branch of my yak repo. Thanks.

**Comment by permcody** [comment]
Thanks, that code looks fine. @dschwen - please rebase this branch and we'll get this merged. @YaqiWang after this is merged you need to add another commit to your branch to update the MOOSE submodule to the hash in `devel`. It'll pass the tests and get merged in, then the `devel` branch can be retested and merged into `master`

**Comment by dschwen** [comment]
@permcody it is rebased

**Comment by YaqiWang** [comment]
@permcody Do you have more comments or thoughts?

**Comment by permcody** [comment]
No, this is ready to go. I'm at training. If you are ready, I can merge this in. If you run into problems with getting the submodule updated after I merge this, you can talk to Daniel. With that in mind are you ready to go?

**Comment by YaqiWang** [comment]
Yes.
