### PR TITLE
close adjoint rhs

### LINKED ISSUE #32714: adjoint solve needs to close petsc vector
### Motivation

When I run a simulation with a forward and adjoint solve from the optimization module, I hit the below error which is telling me I need to close the rhs vector before I apply scaling to it in AdjointSolve.C

[5]PETSC ERROR: #1 VecScaleAsync_Private() at /opt/civet0/build_0/_env/conda-bld/moose-petsc_1773975423171/work/src/vec/vec/interface/rvector.c:453
[5]PETSC ERROR: #2 VecScale() at /opt/civet0/build_0/_env/conda-bld/moose-petsc_1773975423171/work/src/vec/vec/interface/rvector.c:493
libc++abi: terminating due to uncaught exception of type libMesh::PetscSolverException: Not for unassembled vector, did you call VecAssemblyBegin()/VecAssemblyEnd()?
libc++abi: terminating due to uncaught exception of type libMesh::PetscSolverException: Not for unassembled vector, did you call VecAssemblyBegin()/VecAssemblyEnd()?
libMesh terminating:
Not for unassembled vector, did you call VecAssemblyBegin()/VecAssemblyEnd()?
Abort(1) on node 5 (rank 5 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
libc++abi: terminating due to uncaught exception of type libMesh::PetscSolverException: Not for unassembled vector, did you call VecAssemblyBegin()/VecAssemblyEnd()?

### Design

Add rhs.close before rhs.scale

### Impact

This will fix a petsc error I am hitting.

### PR DESCRIPTION
**Pull request by lynnmunday**
closes #32714

### CODE REVIEW

File: modules/optimization/src/executioners/AdjointSolve.C [hunk 1]
```diff
@@ -151,7 +151,7 @@ AdjointSolve::assembleAdjointSystem(SparseMatrix<Number> & matrix,
 
   _problem.setCurrentNonlinearSystem(_adjoint_sys_num);
   _problem.computeResidualTag(*_nl_adjoint.currentSolution(), rhs, _nl_adjoint.nonTimeVectorTag());
-
+  rhs.close();
   rhs.scale(-1.0);
```
Comment (GiudGiud) [inline modules/optimization/src/executioners/AdjointSolve.C:155]: so close does this
```
  /**
   * Calls the NumericVector's internal assembly routines, ensuring
   * that the values are consistent across processors.
   */
  virtual void close () = 0;
```

so I think we would want to switch these two lines so the scaling is consistent across processors

File: modules/optimization/test/tests/executioners/steady_and_adjoint/tests [hunk 2]
```diff
@@ -34,5 +34,12 @@
       exodiff = nonlinear_diffusion_out.e
       detail = 'have non-linear material properties.'
     []
+    [adjoint_rhs]
+      type = RunApp
+      input = adjoint_rhs.i
+      min_parallel = 2
+      recover = false
+      detail = 'contains two reporter point sources where one reporter point source applies 440 dirac sources and runs in parallel.'
```
Comment (GiudGiud) [inline modules/optimization/test/tests/executioners/steady_and_adjoint/tests]: this is too details. why 440? would it not work with 439? 

try to make it about what this test is ensuring is working

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: modules/optimization/src/executioners/AdjointSolve.C (hunk 1 above)
Comment (GiudGiud) [reply modules/optimization/src/executioners/AdjointSolve.C:155]: though if all processes are scaling it may not matter

Comment (lynnmunday) [reply modules/optimization/src/executioners/AdjointSolve.C:155]: It does have to go before the scaling, otherwise I hit the petsc error that I pasted into the issue.  I think this is sort of caused by another error that is addressed in the reporter point source PR I have open.   But with this close, I hit an error that I can fix in the reporterPointSource PR.  Putting close after the scale causes the petsc vector scaling error from the issue.

**Review by GiudGiud — APPROVED** [review]
test performance (1.4s) is reasonable even with 400 sources

**Comment by GiudGiud** [comment]
test failures
```
[5.074s] [ 801MB]    ERROR stochastic_tools/test:samplers/ParallelActiveLearning.Bayesian_active_learning/b_al FAILED (KILLED: OVER MEMORY) [stochastic_tools-opt]
[15.36s] [ 689MB]    ERROR hdgkernels/ip-advection-diffusion.mms/hierarchic_quad FAILED (KILLED: OVER MEMORY) [max_cpus=1]
```
unrelated
