### PR TITLE
Avoid exceptions during projection of primary nodes when nodes are aligned

### LINKED ISSUE #31308: Aligned node exceptions with mortar
### Bug Description

Sometimes it happens that we fail to detect aligned nodes when projecting the secondary nodes and then we throw an exception when we detect alignment during the projection of the primary nodes. We should prevent users from experiencing this

### Steps to Reproduce

Run the inputs provided in #30433 

### Impact

Non-optimal experience for users of mortar

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by lindsayad**
@recuero added a great comment about loosening the tolerance when
projecting the secondary nodes relative to the primary nodes in
order to avoid our exception about "we should have already registered
this primary node as mapped" during primary node projection for aligned
nodes. However, we appear to have only applied it to the inner if
conditional and missed applying it to the outer one which leads to
exceptions in the input provided in https://github.com/idaholab/moose/discussions/30433

Closes #31308

### CODE REVIEW

File: framework/src/problems/FEProblemBase.C [hunk 1]
```diff
@@ -1136,7 +1136,14 @@ FEProblemBase::initialSetup()
 
       if (_material_props.hasStatefulProperties() || _bnd_material_props.hasStatefulProperties() ||
           _neighbor_material_props.hasStatefulProperties())
+      {
         _has_initialized_stateful = true;
+        if (_ics.hasObjects() && _app.isRestarting())
```
Comment (GiudGiud) [inline framework/src/problems/FEProblemBase.C]: what if I m restarting my mechanics simulation with stateful material properties but now I m also solving some non-stateful diffusion problem on the side as well (and need an IC for it, like most things)
seems like we need something more targetted or just some option to allow it

Comment (GiudGiud) [reply framework/src/problems/FEProblemBase.C]: or does restart ban having a new variable? not sure

Comment (lindsayad) [reply framework/src/problems/FEProblemBase.C]: I reverted that change

File: framework/include/constraints/MortarData.h [hunk 2]
```diff
@@ -136,11 +138,12 @@ class MortarData : public libMesh::ParallelObject
 
   /// Map from primary-secondary (in that order) boundary ID pair to the corresponding
   /// undisplaced AutomaticMortarGeneration object
-  std::unordered_map<MortarKey, AutomaticMortarGeneration> _mortar_interfaces;
+  std::unordered_map<MortarKey, std::unique_ptr<AutomaticMortarGeneration>> _mortar_interfaces;
```
Comment (GiudGiud) [inline framework/include/constraints/MortarData.h]: so is MortarData basically a warehouse for mortar interfaces?

File: modules/contact/include/userobjects/LMWeightedGapUserObject.h [hunk 3]
```diff
@@ -18,20 +18,35 @@ class MooseVariableFE;
...
 
+  /**
+   * Check user input validity for provided variable
+   */
+  void checkInput(const MooseVariable * const var, const std::string & var_name) const;
+
+  /**
+   * Verify that the provided variables have degrees of freedom at nodes
+   */
+  void verifyNodal(const MooseVariable & var, const std::string & var_name) const;
```
Comment (GiudGiud) [inline modules/contact/include/userobjects/LMWeightedGapUserObject.h]:
```suggestion
  void verifyHasNodalDofs(const MooseVariable & var, const std::string & var_name) const;
```
or verifyIsNodalDefined if that s what it is

File: modules/contact/src/auxkernels/MortarUserObjectAux.C [hunk 4]
```diff
@@ -7,24 +7,28 @@
...
 #include "WeightedGapUserObject.h"
 #include "PenaltyWeightedGapUserObject.h"
 #include "WeightedVelocitiesUserObject.h"
 #include "PenaltyFrictionUserObject.h"
 
-registerMooseObject("ContactApp", PenaltyMortarUserObjectAux);
+registerMooseObject("ContactApp", MortarUserObjectAux);
+registerMooseObjectRenamed("ContactApp",
+                           PenaltyMortarUserObjectAux,
+                           "01/01/2026 00:00",
```
Comment (GiudGiud) [inline modules/contact/src/auxkernels/MortarUserObjectAux.C]:
```suggestion
                           "04/01/2026 00:00",
```

File: modules/contact/test/tests/mortar_restart/frictional_bouncing_block_action_restart_1.i [hunk 5]
```diff
@@ -33,11 +33,15 @@ offset = 1e-2
...
 
-[Physics/SolidMechanics/QuasiStatic]
-  [all]
-    strain = FINITE
-    generate_output = 'stress_xx stress_yy'
-    block = '1 2'
+[Physics]
+  [SolidMechanics]
+    [QuasiStatic]
+      [all]
```
Comment (GiudGiud) [inline modules/contact/test/tests/mortar_restart/frictional_bouncing_block_action_restart_1.i:39]: this came from formatting the file you have been caught!

File: modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp [hunk 6]
```diff
@@ -0,0 +1,13 @@
+COORDINATES absolute 1.e-6    # min separation not calculated
+
+TIME STEPS relative 1.e-6 floor 0.0     # min:               0 @ t1 max:              18 @ t10
+
+NODAL VARIABLES relative 1.0e-5 floor 1.0e-8
+	disp_x                 # min:               0 @ t1,n1	max:      0.23836948 @ t10,n38
```
Comment (GiudGiud) [inline modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp:6]: is this a max error? Dont they seem quite high?

File: modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.i [hunk 7]
```diff
@@ -12,12 +12,18 @@ offset = 1e-2
...
-[Physics/SolidMechanics/QuasiStatic]
-  [all]
-    add_variables = true
-    strain = FINITE
-    generate_output = 'stress_xx'
-    block = '1 2 3'
+[Physics]
+
+  [SolidMechanics]
+
```
Comment (GiudGiud) [inline modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.i]:
```suggestion
  [SolidMechanics]
```

File: modules/contact/src/userobjects/LMWeightedGapUserObject.C [hunk 8]
```diff
@@ -58,6 +57,27 @@ LMWeightedGapUserObject::LMWeightedGapUserObject(const InputParameters & paramet
...
+               "The Lagrange multiplier variable must be an actual variable and not a constant.");
+  else if (!var)
+    paramError(var_name,
+               "The Lagrange multiplier variables must be provided and be actual variables.");
+}
+
+void
+LMWeightedGapUserObject::verifyNodal(const MooseVariable & var, const std::string & var_name) const
+{
+  if (!var.isNodal())
```
Comment (GiudGiud) [inline modules/contact/src/userobjects/LMWeightedGapUserObject.C]:
```suggestion
  if (!var.isNodalDefined())
```
I think thisis the one you want
100% nodal nothing elsewhere

Comment (GiudGiud) [reply modules/contact/src/userobjects/LMWeightedGapUserObject.C]: or at least that s how I understand that one

File: modules/contact/src/userobjects/LMWeightedGapUserObject.C [hunk 9]
```diff
@@ -69,3 +89,17 @@ LMWeightedGapUserObject::contactPressure() const
...
+LMWeightedGapUserObject::getNormalContactPressure(const Node * const node) const
+{
+  const auto sys_num = _lm_var->sys().number();
+  const auto var_num = _lm_var->number();
+  if (!node->n_dofs(sys_num, var_num))
+    mooseError("No degrees of freedom for the Lagrange multiplier at the node. If this is being "
+               "called from an aux kernel make sure that your aux variable has the same order as "
+               "your Lagrange multiplier");
+
+  const auto dof_number = node->dof_number(sys_num, var_num, 0);
```
Comment (GiudGiud) [inline modules/contact/src/userobjects/LMWeightedGapUserObject.C]:
```suggestion
  const auto dof_number = node->dof_number(sys_num, var_num, /*component*/ 0);
```

File: modules/contact/include/actions/ContactAction.h [hunk 10]
```diff
@@ -111,6 +111,16 @@ class ContactAction : public Action
...
 
+  struct MortarInfo
+  {
+    BoundaryID primary_id;
+    BoundaryID secondary_id;
+    std::string uo_name;
+  };
+
+  /// Map from boundary pair to mortar user object name
+  std::map<std::pair<BoundaryName, BoundaryName>, const MortarInfo> _bnd_pair_to_mortar_info;
```
Comment (GiudGiud) [inline modules/contact/include/actions/ContactAction.h:122]: kind of weird to index by name no? as long as this is only used to set up it s fine

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 11]
```diff
@@ -230,7 +230,8 @@ AutomaticMortarGeneration::AutomaticMortarGeneration(
     _debug(debug),
     _on_displaced(on_displaced),
     _periodic(periodic),
-    _distributed(!_mesh.is_replicated()),
+    // We always ghost the entire mortar interface when it is allowed to displace
+    _distributed(_on_displaced ? false : !_mesh.is_replicated()),
```
Comment (GiudGiud) [inline framework/src/constraints/AutomaticMortarGeneration.C:234]: let s document that somehwere? seems like something that would be an issue for scalability and displaced is very common for mortar users

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 12]
```diff
@@ -1858,6 +1861,105 @@ AutomaticMortarGeneration::projectSecondaryNodes()
...
+    primary_node_neighbors = &libmesh_map_find(_nodes_to_primary_elem_map, primary_node.id());
+
+  std::vector<bool> primary_elems_mapped(primary_node_neighbors->size(), false);
+
+  // Add entries to secondary_node_and_elem_to_xi2_primary_elem container.
+  //
+  // First, determine "on left" vs. "on right" orientation of the nodal neighbors.
+  // There can be a max of 2 nodal neighbors, and we want to make sure that the
+  // secondary nodal neighbor on the "left" is associated with the primary nodal
+  // neighbor on the "left" and similarly for the "right".
```
Comment (GiudGiud) [inline framework/src/constraints/AutomaticMortarGeneration.C]: can copilot draw something to represent this?

File: modules/contact/src/actions/ContactAction.C [hunk 13]
```diff
@@ -506,6 +520,23 @@ ContactAction::act()
 
         _problem->addAuxKernel("PenetrationAux", name, params);
       }
+      else
+      {
+        const auto type = "MortarUserObjectAux";
+        InputParameters params = _factory.getValidParams(type);
+        params.set<std::vector<BoundaryName>>("boundary") = {secondary_name};
+        params.set<AuxVariableName>("variable") = "gap";
+        params.set<bool>("use_displaced_mesh") = true; // Unecessary as this object only operates on
```
Comment (GiudGiud) [inline modules/contact/src/actions/ContactAction.C]:
```suggestion
        params.set<bool>("use_displaced_mesh") = true; // Unnecessary as this object only operates on
```

File: modules/contact/src/actions/ContactAction.C [hunk 14]
```diff
@@ -828,139 +892,148 @@ ContactAction::addMortarContact()
...
       if (ndisp > 2)
-        var_params.set<std::vector<VariableName>>("disp_z") = {displacements[2]};
+        uo_params.set<std::vector<VariableName>>("disp_z") = {displacements[2]};
 
-      var_params.set<VariableName>("secondary_variable") = displacements[0];
-      var_params.set<bool>("use_displaced_mesh") = true;
-      var_params.set<Real>("friction_coefficient") = getParam<Real>("friction_coefficient");
-      var_params.set<Real>("penalty") = getParam<Real>("penalty");
-      var_params.set<Real>("penalty_friction") = getParam<Real>("penalty_friction");
+      uo_params.set<VariableName>("secondary_variable") = displacements[0];
```
Comment (GiudGiud) [inline modules/contact/src/actions/ContactAction.C:1001]: ? why disp_x ?

File: modules/contact/src/actions/ContactAction.C [hunk 15]
```diff
@@ -634,47 +664,71 @@ ContactAction::act()
...
+      params.set<std::vector<VariableName>>("nodal_area") = {"nodal_area"};
+      params.set<bool>("use_displaced_mesh") = true;
 
-    std::string name = _name + "_contact_pressure";
-    params.set<ExecFlagEnum>("execute_on",
-                             true) = {EXEC_NONLINEAR, EXEC_TIMESTEP_END, EXEC_TIMESTEP_BEGIN};
-    _problem->addAuxKernel("ContactPressureAux", name, params);
+      std::string name = _name + "_contact_pressure";
+      params.set<ExecFlagEnum>("execute_on",
+                               true) = {EXEC_NONLINEAR, EXEC_TIMESTEP_END, EXEC_TIMESTEP_BEGIN};
```
Comment (GiudGiud) [inline modules/contact/src/actions/ContactAction.C:709]: it s a lot of execution when you did not set a schedule for MortarUserObjectAux

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 12 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C]: I don't know. Do you have copilot installed in vs code?

File: framework/include/constraints/MortarData.h (hunk 2 above)
Comment (lindsayad) [reply framework/include/constraints/MortarData.h]: yes

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 12 above)
Comment (GiudGiud) [reply framework/src/constraints/AutomaticMortarGeneration.C]: nope but it s installed in the teams client

File: modules/contact/test/tests/mortar_restart/frictional_bouncing_block_action_restart_1.i (hunk 5 above)
Comment (lindsayad) [reply modules/contact/test/tests/mortar_restart/frictional_bouncing_block_action_restart_1.i:39]: image

File: modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp (hunk 6 above)
Comment (lindsayad) [reply modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp:6]: No, those are the min and max values of the field

Comment (GiudGiud) [reply modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp:6]: this isnt used for anything right? Like it does not impose a criterion on the new min/max

Comment (lindsayad) [reply modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.cmp:6]: no it's not used for anything. It's automatically generated by `exodiff -summary`. For someone reading the custom comparison file I think it's helpful for deciding whether the tolerances (which are used for things) are reasonable

File: modules/contact/src/userobjects/LMWeightedGapUserObject.C (hunk 8 above)
Comment (lindsayad) [reply modules/contact/src/userobjects/LMWeightedGapUserObject.C]: that uses on-the-fly information, e.g. `_has_dof_indices`. Whereas this method will only be called from constructors. I'm going to change this to just directly check that the FEFamily is `Lagrange`

File: modules/contact/src/actions/ContactAction.C (hunk 14 above)
Comment (lindsayad) [reply modules/contact/src/actions/ContactAction.C:1001]: you could pick any of the displacements

File: modules/contact/src/actions/ContactAction.C (hunk 15 above)
Comment (lindsayad) [reply modules/contact/src/actions/ContactAction.C:709]: I agree it's a lot, but the choice pre-dates me. @bwspenc do you know what you'd want to execute this on `EXEC_TIMESTEP_BEGIN` or why `EXEC_NONLINEAR` instead of the aux kernel default `EXEC_LINEAR`?

File: framework/include/constraints/MortarData.h (hunk 2 above)
Comment (GiudGiud) [reply framework/include/constraints/MortarData.h]: MortarInterfacesStorage/Warehouse would probably be a better name.
MortarData feels like something I d send between processes when performing mortar setup work

as you want though for changing the name

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 16]
```diff
@@ -1858,6 +1861,122 @@ AutomaticMortarGeneration::projectSecondaryNodes()
...
+  //           x
+  //
+  //  Looking at the aligned nodes, the secondary node first, if we pick the top secondary lower
+  //  dimensional element, then the cross product as written a few lines below points out of the
+  //  screen towards you. (Point in the direction of the secondary nodal normal, and then curl your
+  //  hand towards the secondary element's opposite node, then the thumb points in the direction of
+  //  the cross product). Doing the same with the aligned primary node, if we pick the top primary
+  //  element, then the cross product also points out of the screen. Because the cross products
+  //  point in the same direction (positive dot product), then we know to associate the
+  //  secondary-primary pair. If we had picked the bottom primary element whose cross product points
```
Comment (GiudGiud) [inline framework/src/constraints/AutomaticMortarGeneration.C]:
```suggestion
  //  secondary-primary element pair. If we had picked the bottom primary element whose cross product points
```

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 17]
```diff
@@ -1858,6 +1861,122 @@ AutomaticMortarGeneration::projectSecondaryNodes()
...
+  //  into the screen, then clearly the cross products point in the opposite direction and we don't
+  //  have a match
+  std::array<Real, 2> secondary_node_neighbor_cps, primary_node_neighbor_cps;
+
+  for (const auto nn : index_range(*secondary_node_neighbors))
+  {
+    const Elem * const secondary_neigh = (*secondary_node_neighbors)[nn];
```
Comment (GiudGiud) [inline framework/src/constraints/AutomaticMortarGeneration.C:1911]: so all this work is in 2D, is there an equivalent need for 3D?

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 18]
```diff
@@ -1858,6 +1861,122 @@ AutomaticMortarGeneration::projectSecondaryNodes()
...
+  if (!found_match)
+  {
+    // There could be coincident nodes and this might be a bad primary candidate (see
+    // issue #21680). Instead of giving up, let's try continuing
+    rejected_elem_candidates.insert(&candidate_element);
+    return false;
+  }
+
+  // We need to handle the case where we've exactly projected a secondary node onto a
+  // primary node, but our secondary node is at one of the secondary face endpoints and
```
Comment (GiudGiud) [inline framework/src/constraints/AutomaticMortarGeneration.C]:
```suggestion
  // primary node, but our secondary node is at one of the secondary boundary face endpoints and
```

File: modules/contact/src/userobjects/LMWeightedGapUserObject.C [hunk 19]
```diff
@@ -58,6 +57,26 @@ LMWeightedGapUserObject::LMWeightedGapUserObject(const InputParameters & paramet
                "false`.");
 }
 
+void
+LMWeightedGapUserObject::checkInput(const MooseVariable * const var,
+                                    const std::string & var_name) const
```
Comment (GiudGiud) [inline modules/contact/src/userobjects/LMWeightedGapUserObject.C]:
```suggestion
                                    const std::string & var_param_name) const
```

File: modules/contact/src/userobjects/LMWeightedGapUserObject.C [hunk 20]
```diff
@@ -58,6 +57,26 @@ LMWeightedGapUserObject::LMWeightedGapUserObject(const InputParameters & paramet
...
+    paramError(var_name,
+               "The Lagrange multiplier variable must be an actual variable and not a constant.");
+  else if (!var)
+    paramError(var_name,
+               "The Lagrange multiplier variables must be provided and be actual variables.");
+}
+
+void
+LMWeightedGapUserObject::verifyLagrange(const MooseVariable & var,
+                                        const std::string & var_name) const
```
Comment (GiudGiud) [inline modules/contact/src/userobjects/LMWeightedGapUserObject.C]:
```suggestion
                                        const std::string & var_param_name) const
```

Comment (GiudGiud) [reply modules/contact/src/userobjects/LMWeightedGapUserObject.C]: or coupled_var_name

**Review by GiudGiud — APPROVED** [review]

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 17 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C:1911]: There's a decent chance yea but it's pretty hard to manufacture tests that challenge the mortaring as much as the one that @mpai60 provided. To be honest I have spent a much smaller fraction of time in the 3D mortar code than in the 2D, both because @jbadger95 was the one who provided the 3D implementation and because many more users use 2D so that's the bug reports we see
