### PR TITLE
PatternedMeshGenerator boundary stitching patch

### LINKED ISSUE #23312: PatternedMeshGenerator boundary stitching
## Bug Description

The [PatternedMeshGenerator](https://mooseframework.inl.gov/moose/source/meshgenerators/PatternedMeshGenerator.html) creates a 2D mesh from a specified set of unique 'tiles' meshes (parameter _inputs_) and a two-dimensional pattern (parameter _pattern_). This is accomplished by stitching the tiles in the pattern together using the [libMesh::UnstructuredMesh::stitch_meshes](https://mooseframework.inl.gov/docs/doxygen/libmesh/classlibMesh_1_1UnstructuredMesh.html#ac3619b0da85824ef8e79dd31f7e7d6ef) function. Two of the parameters in the stitch_meshes method are the boundary ids of the mesh boundaries to be stitched together. PatternedMeshGenerator has input parameters that specify the text names of the left, right, top and bottom boundaries of the mesh tiles in _inputs_. These names are used to extract the corresponding boundary ids used to stitch the tiles together. 

The bug is that these boundary ids are only extracted from the first mesh tile in _inputs_ and that the remaining tiles are not checked to ensure that they have the same boundary ids for the left, right, top and bottom boundaries. When tiles in _inputs_ do not share identical boundary id configurations, tile stitching is performed incorrectly, resulting in an incorrect patterned mesh.

The proposed patch is to add logic to check whether all mesh tiles in _inputs_ share the same boundary id configurations. If they do not, boundary ids will be modified to be the same across all tiles.

## Steps to Reproduce

The attached input file _input.txt_ provides an example of this bug. The incorrect boundaries resulting from the incorrect stitching may be visualized using Peacock (attached screenshots).

## Impact

This bug causes PatternedMeshGenerator to stitch meshes together incorrectly, resulting in unusable meshes with incorrect boundaries.

[input.txt](https://github.com/idaholab/moose/files/10561133/input.txt)
image
image
image
image

### PR DESCRIPTION
**Pull request by pbehne**
This commit patches the bug described in #23312 which results in incorrect mesh stitching in the PatternedMeshGenerator when the mesh tiles provided in the 'inputs' parameter do not have the same boundary ids. A check is added to detect this issue, and if present, the boundary ids of all tile meshes are changed to be common, previously unused boundary ids. This allows for the tiles to be stitched together correctly. Additionally, the class was cleaned up to incorporate recommended code standards.

closes #23312

### CODE REVIEW

**Comment by pbehne** [comment]
@loganharbour

**Review by loganharbour — CHANGES_REQUESTED** [review]
Lots of cleanup changes that I think are straight forward

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 1]
```diff
@@ -88,36 +101,36 @@ PatternedMeshGenerator::generate()
...
+
+    // Check if all the boundaries have been initialized
+    if (left_id == -123)
+      mooseError("The left boundary has not been initialized properly.");
+    if (right_id == -123)
+      mooseError("The right boundary has not been initialized properly.");
+    if (top_id == -123)
+      mooseError("The top boundary has not been initialized properly.");
+    if (bottom_id == -123)
+      mooseError("The bottom boundary has not been initialized properly.");
```
[the remark this answers is not in the document]
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C]: Incorporated.

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 2]
```diff
@@ -88,35 +104,36 @@ PatternedMeshGenerator::generate()
...
+    {
+      if (ids[side] == Moose::INVALID_BOUNDARY_ID)
+        paramError("inputs",
+                   "The '",
+                   boundary_param_names[side],
+                   "' parameter with value '",
+                   boundary_names[side],
+                   "' does not exist in input mesh '",
+                   _input_names[i],
+                   "'");
```
Comment (pbehne) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:127]: @loganharbour, let me know if you want any additional changes to this one. It's a bit tricky because an error results from a combination of TWO input parameters (i..e, when one of left_boundary, right_boundary, top_boundary, or bottom_boundary does not match up with a boundary name of any of the meshes in inputs).

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 3]
```diff
@@ -88,35 +104,36 @@ PatternedMeshGenerator::generate()
...
-  // Getting the boundaries provided by the user
-  std::vector<BoundaryName> boundary_names = {getParam<BoundaryName>("left_boundary"),
-                                              getParam<BoundaryName>("right_boundary"),
-                                              getParam<BoundaryName>("top_boundary"),
-                                              getParam<BoundaryName>("bottom_boundary")};
+    _meshes[i] = dynamic_pointer_cast<ReplicatedMesh>(mesh->clone());
 
-  std::vector<boundary_id_type> ids =
-      MooseMeshUtils::getBoundaryIDs(*_meshes[0], boundary_names, true);
+    const auto ids = MooseMeshUtils::getBoundaryIDs(*_meshes[i], boundary_names, false);
```
Comment (pbehne) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:109]: In order to properly trigger the paramError for "inputs", I changed the "generate_unknown" parameter in getBoundaryIDs from true to false. When true, a new boundary_id is generated if no match to the requested boundary name is found. When false, invalid_id is returned, which is what triggers the paramError below.

By changing generate_unknown to False, so of the tests in the reactor module are failing because the paramError is being triggered. My hypothesis is that these tests rely on new boundary ids being generated in a way that we are not taking into account.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 2 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:127]: See comment above about generate_unknown parameter in getBoundaryIDs function.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 3 above)
Comment (loganharbour) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:109]: FYI @miaoyinb and @yjung-anl, looks like we've got a pattern stitch that relies on some undefined behavior that we cleaned up (see https://civet.inl.gov/job/1331932/)

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 2 above)
Comment (loganharbour) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:127]: Talk to me about this in person, I'm a bit confused at what you're trying to say in the first comment. Also - we might want to check to make sure that all of the options in [left, right, top, bottom] are unique.

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 4]
```diff
@@ -128,6 +145,26 @@ PatternedMeshGenerator::generate()
...
+      {
+        stitch_bids.push_back(id);
+        if (stitch_bids.size() == 4)
+          break;
+      }
+
+  for (const auto i : index_range(_meshes))
+    for (const auto side : make_range(4))
+      MeshTools::Modification::change_boundary_id(
+          *_meshes[i], input_bids[i][side], stitch_bids[side]);
```
Comment (loganharbour) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:163]:
```suggestion
  if (!have_common_ids)
    for (const auto i : index_range(_meshes))
      for (const auto side : make_range(4))
        MeshTools::Modification::change_boundary_id(
            *_meshes[i], input_bids[i][side], stitch_bids[side]);
```

This makes sense right?

**Review by loganharbour — CHANGES_REQUESTED** [review]
We'll chat in a bit. I think the last thing we need is to fix the failures and add some error testing

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 4 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:163]: Yup, will incorporate.

**Comment by loganharbour** [comment]
@miaoyinb or @yjung-anl can you please verify the changes in a0c894eb01286b052c043841b358436b7250e32c

**Comment by miaoyinb** [comment]
> @miaoyinb or @yjung-anl can you please verify the changes in [a0c894e](https://github.com/idaholab/moose/commit/a0c894eb01286b052c043841b358436b7250e32c)

I think this is for @yjung-anl.

**Comment by yjung-anl** [comment]
@pbehne 
The changes look good to me!
Thank you for identifying and fixing this issue!

File: modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/assembly_only.i [hunk 5]
```diff
@@ -20,17 +20,37 @@
     duct_halfpitch = '0.68'
     mesh_intervals = '1 1 1'
     quad_center_elements = false
-    region_ids='1 2 5; 11 12 15'
+    region_ids = '1 2 5; 11 12 15'
+  []
+  [pin1]
```
Comment (pbehne) [inline modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/assembly_only.i:25]: @yjung-anl
I am trying to fix all the remaining tests in the reactor module that are failing. See https://civet.inl.gov/job/1338882/ for failure details. With the new error checks in PatternedMeshGenerator, we need to make sure that any MeshGenerators in AssemblyMeshGenerator/inputs have boundary sidesets named 'left', 'right', 'top', and 'bottom'. To do this, I renamed pin1 to pin1_a and ran it through a SideSetsFromNormalsGenerator to get the desired boundaries. However, the AssemblyMeshGenerator does not like this and gives the following error:

```
The reactor_params input must be a ReactorMeshParams type MeshGenerator
Please check that a valid definition and name of ReactorMeshParams has been provided.
```

Could you please look into a fix for this?

Comment (miaoyinb) [reply modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/assembly_only.i:25]: This is because the mesh metadata generated by `PinMeshGenerator` are lost when you modify the mesh using SideSetsFromNormalsGenerator. @loganharbour @GiudGiud  and I are working on the mesh metadata forwarding capability development that will eventually solve this issue. I will help fix this once #23353 is merged.

Comment (pbehne) [reply modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/assembly_only.i]: We were able to implement a fix in the source code that does not requires modification of the test input files.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 3 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:122]: The failing tests have been updated to work correctly.

**Comment by pbehne** [comment]
Note that a Griffin test in the controlled app tests fails. PR 1055 in the Griffin repo corrects this issue.

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 6]
```diff
@@ -128,6 +158,29 @@ PatternedMeshGenerator::generate()
...
+    stitch_bids = input_bids[0];
+  else
+  {
+    for (boundary_id_type id = 0; id != Moose::INVALID_BOUNDARY_ID; ++id)
+      if (!used_boundary_ids.count(id))
+      {
+        stitch_bids.push_back(id);
+        if (stitch_bids.size() == 4)
+          break;
+      }
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:172]: I think there's a util to get the next free boundary id. and if there is not we should add one

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 7]
```diff
@@ -88,35 +117,36 @@ PatternedMeshGenerator::generate()
...
-  // Check if all the boundaries have been initialized
-  if (left == -123)
-    mooseError("The left boundary has not been initialized properly.");
-  if (right == -123)
-    mooseError("The right boundary has not been initialized properly.");
-  if (top == -123)
-    mooseError("The top boundary has not been initialized properly.");
-  if (bottom == -123)
-    mooseError("The bottom boundary has not been initialized properly.");
+    for (const auto j : index_range(boundary_names))
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:147]: add comments

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 8]
```diff
@@ -128,6 +158,29 @@ PatternedMeshGenerator::generate()
...
+        stitch_bids.push_back(id);
+        if (stitch_bids.size() == 4)
+          break;
+      }
+
+    // Make all inputs have common boundary ids
+    for (const auto i : index_range(_meshes))
+      for (const auto side : make_range(4))
+        MeshTools::Modification::change_boundary_id(
+            *_meshes[i], input_bids[i][side], stitch_bids[side]);
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:178]: this could be problematic if input_bids[i] is the same on all sides.

Then you end up with a no sideset with stitch_bids[0, 1 or 2]

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md [hunk 9]
```diff
@@ -7,6 +7,10 @@
 The `PatternedMeshGenerator` object is similar to [TiledMeshGenerator](/TiledMeshGenerator.md). However, it is restricted to two dimensions and
 adds the ability to create a tile pattern from an arbitrary number of input meshes.
 
+!alert note
+The MeshGenerators provided in inputs are no longer required to have the same boundary ids for a given boundary.
```
[the remark this answers is not in the document]
Comment (pbehne) [reply framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:11]: Correct. I will update for clarity.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 8 above)
Comment (loganharbour) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:178]: Not possible by default: https://github.com/idaholab/moose/blob/470e4353ecbd7163dd55ed236bcd81eb3cc485ba/framework/src/meshgenerators/PatternedMeshGenerator.C#L91

We even discussed this (this error is what caused problems with reactor)

why must you hijack my PR

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md [hunk 10]
```diff
@@ -7,6 +7,10 @@
...
+Boundary ids for all input MeshGenerators are temporarily renamed to a common unused set of ids. The resulting PatternedMeshGenerator has boundary ids that are the same as the first entry of the inputs parameter.
```
[the remark this answers is not in the document]
Comment (loganharbour) [reply framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:12]: The inputs aren't modified, re: temporarily

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 6 above)
Comment (loganharbour) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:172]: We use it in a few places but it's used in different ways, for example in RenameBoundaryGenerator we have to also check again an extra set of bids

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 8 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:181]: no I think it breaks as I say
```
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 5
    ny = 5
    subdomain_ids = '1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     '
  []

  [gmg2]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 5
    ny = 5
    subdomain_ids = '2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     '
    # The following triggers generation of new common boundary ids in
    # PatternedMeshGenerator
    boundary_id_offset = 1
  []

  [2_sides_same]
    type = RenameBoundaryGenerator
    input = gmg2
    old_boundary = 'left top'
    new_boundary = 'left left'
  []
  [2_sides_same2]
    type = RenameBoundaryGenerator
    input = gmg
    old_boundary = 'left top'
    new_boundary = 'left left'
  []

  [pmg]
    type = PatternedMeshGenerator
    inputs = '2_sides_same2 2_sides_same'
    pattern = '1 0 ;
               0 1'
    top_boundary = 'left'
    require_unique_boundaries = false
  []
[]
```

```
In UnstructuredMesh::stitch_meshes:
This mesh has 11 nodes on boundary 8.
Other mesh has 0 nodes on boundary 7.
Minimum edge length on both surfaces is 0.2.
In UnstructuredMesh::stitch_meshes:
Found 0 matching nodes.
```

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md [hunk 11]
```diff
@@ -7,6 +7,10 @@
 The `PatternedMeshGenerator` object is similar to [TiledMeshGenerator](/TiledMeshGenerator.md). However, it is restricted to two dimensions and
 adds the ability to create a tile pattern from an arbitrary number of input meshes.
 
+!alert note
+The MeshGenerators provided in inputs are no longer required to have the same boundary ids for a given boundary name.
+In this case, boundary ids for all (cloned) input MeshGenerators are renamed to a common unused set of ids. The resulting PatternedMeshGenerator has boundary ids that are the same as the first entry of the passed inputs parameter.
```
[the remark this answers is not in the document]
Comment (pbehne) [reply framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:12]: I know what you are trying to say, but I do not think this wording is correct from all interpretations. Each of the meshes in the grid is technically a clone inside PatterendMeshGenerator::generate (see [here](https://github.com/idaholab/moose/blob/2509317e71abacfdea1b50465f28a7ca62170326/framework/src/meshgenerators/PatternedMeshGenerator.C#L120)). In the case that these meshes do not have common boundary ids, the boundary ids of these clones are renamed once to common, previously unused boundary ids, not to the boundary ids of the top left mesh (see [here](https://github.com/idaholab/moose/blob/2509317e71abacfdea1b50465f28a7ca62170326/framework/src/meshgenerators/PatternedMeshGenerator.C#L162-L182)).  It is only the stitched-together mesh (that is returned) that has the boundary ids of the original, top left mesh (see [here)](https://github.com/idaholab/moose/blob/2509317e71abacfdea1b50465f28a7ca62170326/framework/src/meshgenerators/PatternedMeshGenerator.C#L245-L251). If you still do not like my use of "The resulting PatternedMeshGenerator has boundary ids..." above, I think "The resulting stitched mesh has boundary ids" would work.

[the remark this answers is not in the document]
Comment (pbehne) [reply framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:12]: Also, your use of "top left" is fine.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 8 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:181]: Setting 'require_unique_boundaries' to true (the default value) fixes this issue ;)

Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:181]: unless you forbid users from setting it to false then there's an issue.

It fails silently too which is more problematic

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md (hunk 11 above)
Comment (pbehne) [inline framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:12]:
```suggestion
In this case, boundary ids for all (cloned) input MeshGenerators are renamed to a common unused set of ids. The resulting stitched patterned mesh has boundary ids that are the same as the first entry of the passed inputs parameter (top left mesh in the grid).
```

**Comment by pbehne** [comment]
@GiudGiud I had some nice debug print statements in PatternedMeshGenerator.C, but removed them to make CIVET happy. If it will help your review, feel free to check out 17c0dd7.

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 12]
```diff
@@ -88,35 +116,74 @@ PatternedMeshGenerator::generate()
...
-  if (left == -123)
-    mooseError("The left boundary has not been initialized properly.");
-  if (right == -123)
-    mooseError("The right boundary has not been initialized properly.");
-  if (top == -123)
-    mooseError("The top boundary has not been initialized properly.");
-  if (bottom == -123)
-    mooseError("The bottom boundary has not been initialized properly.");
+  // Error check on lengths of input_bids_unique
+  if (lengths_set.size() != 1)
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:182]: you could check the content to be 1 or 4 just below

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 13]
```diff
@@ -128,6 +195,43 @@ PatternedMeshGenerator::generate()
...
+        // It is okay to only use the 0th index here, since we ensure all entries in
+        // input_bids_unique have the same size through the above error check.
+        if (stitch_bids.size() == input_bids_unique[0].size())
+          break;
+      }
+
+    // Make all inputs have common boundary ids
+    for (const auto i : index_range(_meshes))
+      for (const auto side : index_range(stitch_bids))
+      {
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:220]:
```suggestion
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 14]
```diff
@@ -128,6 +195,43 @@ PatternedMeshGenerator::generate()
...
+        MeshTools::Modification::change_boundary_id(
+            *_meshes[i], input_bids_unique[i][side], stitch_bids[side]);
+      }
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:223]:
```suggestion
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 15]
```diff
@@ -88,35 +116,74 @@ PatternedMeshGenerator::generate()
...
+                   "'");
+
+      input_bids[i][side] = ids[side];
+
+      // We only do this when i == 0 because all input meshes should have the
+      // same index map. Allowing different index maps for different input
+      // meshes results in undefined behaviour when stitching
+      if (i == 0)
+      {
+        if (!id_set.count(ids[side]))
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:154]: you dont need id_set.
You're storing this information of "I have seen this before" in another vector (input_bids_unique) and a map seen_bid_to_index_map

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 16]
```diff
@@ -88,35 +116,74 @@ PatternedMeshGenerator::generate()
...
+        {
+          input_bids_unique[i].push_back(ids[side]);
+          id_set.insert(ids[side]);
+        }
+      }
+    }
 
-  boundary_id_type left = ids[0], right = ids[1], top = ids[2], bottom = ids[3];
+    lengths_set.insert(input_bids_unique.size());
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:178]: I wouldnt keep track of length_sets like this.
If you make it a single integer, you can error as soon as you hit the inconsistent size, and you can return the name of the problematic inputs

File: test/tests/meshgenerators/patterned_mesh_generator/tests [hunk 17]
```diff
@@ -1,13 +1,36 @@
...
-  [../]
+    [non_existent_boundary]
+      type = 'RunException'
+      input = 'patterned_mesh_generator.i'
+      cli_args = 'Mesh/pmg/right_boundary="fake_boundary"'
+      expect_err = 'does not exist in input mesh'
+      detail = 'the boundary name does not exist'
+      mesh_mode = 'REPLICATED'
+    []
+  []
```
Comment (GiudGiud) [inline test/tests/meshgenerators/patterned_mesh_generator/tests:35]: add an error test for the inconsistent size of boundary_ids

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 15 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:154]: How do you recommend I replace the
`if (!id_set.count(ids[side]))`
statements? Use std::find on input_bids_unique and query that result instead?

Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:154]: yeah there's a count on vectors and probably just find on the map

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 16 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:178]: I will modify to use a single integer. However, I don't think there is a quick way to point to a single input mesh as the problematic input without adding additional checks. For example: if there are two input meshes with a different length of input_bids_unique, which one is considered the problematic input?

Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:178]: the first one you hit in the loop? Or the first one that is not 1 or 4

Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:178]: I guess it s why it s easier to check for 1/4 than to check for "all the same"

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 18]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
   // Reserve spaces for all the meshes
   _meshes.reserve(_input_names.size());
 
+  // Getting the boundaries provided by the user
```
[the remark this answers is not in the document]
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:79]: Remember that even with that check in place, I still found a way to break the mesh generator without triggering the check. Because we don't have a way to catch these cases (without normals checking), I don't see a reason to leave the check in place since there are valid cases 1 > num_boundaries > 4 that produce correct meshes. Still want me to add the check back in?

[the remark this answers is not in the document]
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:79]: Also, I did update the manual page for PatternedMeshGenerator to inform the user specifically what to look for when the mess up their inputs.

[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:79]: As you want. I think it s a fine limitation

File: test/tests/meshgenerators/patterned_mesh_generator/tests (hunk 17 above)
Comment (pbehne) [reply test/tests/meshgenerators/patterned_mesh_generator/tests:35]: I am actually having a difficult time coming up with an input that triggers this error without hitting the error (here)[https://github.com/idaholab/moose/blob/74817397957818d058304850d3fca6d7ceecd352/framework/src/meshgenerators/PatternedMeshGenerator.C#L136-L145] first. Do you have any ideas? If not, I think the inconsistent size test can be removed.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 12 above)
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:182]: See our above conversation. I am leaving this check out for more user flexibility.

File: framework/src/meshgenerators/PatternedMeshGenerator.C (hunk 18 above)
[the remark this answers is not in the document]
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:79]: Will leave the check out.

File: test/tests/meshgenerators/patterned_mesh_generator/tests (hunk 17 above)
Comment (GiudGiud) [reply test/tests/meshgenerators/patterned_mesh_generator/tests:35]: just use one with 4 sides and one with 1 side all around?

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 19]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
...
+  bool have_common_ids = true;
+
+  // Keep track of used boundary ids to generate new, unused ones later (if needed)
+  std::set<boundary_id_type> used_boundary_ids;
+
+  // Using a vector of vectors instead of vector of sets to preserve insertion order
+  std::vector<std::vector<boundary_id_type>> input_bids_unique(_input_names.size());
+
+  // For an error check on input_bids_unique later
+  size_t set_length;
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:100]:
```suggestion
  size_t set_length = 0;
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 20]
```diff
@@ -88,35 +116,70 @@ PatternedMeshGenerator::generate()
...
-  if (left == -123)
-    mooseError("The left boundary has not been initialized properly.");
-  if (right == -123)
-    mooseError("The right boundary has not been initialized properly.");
-  if (top == -123)
-    mooseError("The top boundary has not been initialized properly.");
-  if (bottom == -123)
-    mooseError("The bottom boundary has not been initialized properly.");
+        if (std::count(input_bids_unique[i].begin(), input_bids_unique[i].end(), ids[side]) > 0)
+        {
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:168]:
```suggestion
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 21]
```diff
@@ -88,35 +116,70 @@ PatternedMeshGenerator::generate()
...
+          input_bids_unique[i].push_back(ids[side]);
+        }
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:170]:
```suggestion
```

**Review by GiudGiud — COMMENTED** [review]
good to go after this and the extra test

**Comment by GiudGiud** [comment]
Once you're done with the seg fault and the other test, we should look at condensing this commit history a little (squashing)

File: test/tests/meshgenerators/patterned_mesh_generator/tests (hunk 17 above)
Comment (pbehne) [reply test/tests/meshgenerators/patterned_mesh_generator/tests:35]: In such a case, there is no correct way to set left/right/top/bottom_boundary. See below:

`[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 5
    ny = 5
    subdomain_ids = '1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     1 1 1 1 1
                     '
  []

  [gmg2]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 5
    ny = 5
    subdomain_ids = '2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     2 2 2 2 2
                     '
  []

  [all_sides_same]
    type = RenameBoundaryGenerator
    input = 'gmg2'
    old_boundary = 'left right top bottom'
    new_boundary = 'left left left left'
  []

  [pmg]
    type = PatternedMeshGenerator
    inputs = 'gmg all_sides_same'
    pattern = '1 0 ;
               0 1'
  []
[]`

The error:

`*** ERROR ***
(Mesh/pmg/inputs):
    The 'right_boundary' parameter with value 'right' does not exist in input mesh 'all_sides_same'`

Now if I set left/right/top/bottom_boundary all to 'left':

`  [pmg]
    type = PatternedMeshGenerator
    inputs = 'gmg all_sides_same'
    pattern = '1 0 ;
               0 1'
    left_boundary = left
    right_boundary = left
    top_boundary = left
    bottom_boundary = left
  []`

This runs because the boundary id for the 'left' mesh in each input mesh is a single number, thus the error is not triggered.

**Comment by pbehne** [comment]
@GiudGiud, hold off on merging until I give you the go ahead. I had to make a change that I shouldn't have, so I want to look through all changes one more time to make sure I haven't missed anything.

**Comment by pbehne** [comment]
@GiudGiud, I am ready for merging if you are.

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md [hunk 22]
```diff
@@ -7,6 +7,13 @@
 The `PatternedMeshGenerator` object is similar to [TiledMeshGenerator](/TiledMeshGenerator.md). However, it is restricted to two dimensions and
 adds the ability to create a tile pattern from an arbitrary number of input meshes.
 
+!alert note
+The MeshGenerators provided in inputs are no longer required to have the same boundary ids for a given boundary name.
+In this case, boundary ids for all (cloned) input MeshGenerators are renamed to a common unused set of ids. The resulting stitched patterned mesh has boundary ids that are the same as the first entry of the passed inputs parameter (top left mesh in the grid).
```
Comment (GiudGiud) [inline framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:12]:
```suggestion
In this case, boundary ids for all (cloned) input MeshGenerators are first renamed to a common unused set of ids. Them the resulting stitched patterned mesh will be changed again to boundary ids that are the same as the first entry of the passed inputs parameter (top left mesh in the grid).
```
Last sentence does not work
See our input
```
    inputs = 'fmg fmg2'
    pattern = '1 0 0 0 0 0 0 0 0 0 0 0 0 0 ;
               0 1 1 0 0 0 0 0 0 0 0 1 1 0 ;
               0 1 1 1 0 0 0 0 0 0 1 1 1 0 ;
               0 1 0 1 1 0 0 0 0 1 1 0 1 0 ;
               0 1 0 0 1 1 0 0 1 1 0 0 1 0 ;
               0 1 0 0 0 1 1 1 1 0 0 0 1 0 ;
               0 1 0 0 0 0 1 1 0 0 0 0 1 0 ;
               0 1 0 0 0 0 0 0 0 0 0 0 1 0 ;
               0 1 0 0 0 0 0 0 0 0 0 0 1 0 ;
               0 1 0 0 0 0 0 0 0 0 0 0 1 0 ;
               0 1 0 0 0 0 0 0 0 0 0 0 1 0 ;
               0 0 0 0 0 0 0 0 0 0 0 0 0 0'
```

first input and top-left pattern could be not the same

File: framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md [hunk 23]
```diff
@@ -7,6 +7,13 @@
...
+
+!alert note
+Although best efforts have been made to ensure that the PatternedMeshGenerator fails with a descriptive error message when provided with invalid or ambiguous input, there are some expections that will result in silent failure (the input meshes are stitched together incorrectly and the program continues to run). If this occurs, this issue is likely that one of the left/right/top/bottom_boundary input parameters is set to an incorrect value (i.e., left_boundary = 'right', when the 'right' boundary does not have outward normal (-1, 0, 0)). Check for mistakes like these when troubleshooting errors. Additionally, it should be confirmed that the values of the left/right/top/bottom_boundary parameters are correct for EVERY mesh provided in the 'inputs' parameter (i.e., each mesh in 'inputs' should have the same boundary labels and locations).
```
Comment (GiudGiud) [inline framework/doc/content/source/meshgenerators/PatternedMeshGenerator.md:15]:
```suggestion
Although best efforts have been made to ensure that the PatternedMeshGenerator fails with a descriptive error message when provided with invalid or ambiguous input, there are some expections that will result in silent failure (the input meshes are stitched together incorrectly and the program continues to run). If this occurs, this issue is likely that one of the left/right/top/bottom_boundary input parameters is set to an incorrect value (i.e., left_boundary = 'right', when the 'right' boundary does not have outward normal (-1, 0, 0)). Check for mistakes like these when troubleshooting errors. Additionally, it should be confirmed that the values of the left/right/top/bottom_boundary parameters are correct for EVERY mesh provided in the 'inputs' parameter (i.e., each mesh in 'inputs' should have the same boundary name, ids may differ, and locations).
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 24]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
...
+      _input_names.size(), std::vector<boundary_id_type>(4, Moose::INVALID_BOUNDARY_ID));
+  bool have_common_ids = true;
+
+  // Keep track of used boundary ids to generate new, unused ones later (if needed)
+  std::set<boundary_id_type> used_boundary_ids;
+
+  // Using a vector of vectors instead of vector of sets to preserve insertion order
+  std::vector<std::vector<boundary_id_type>> input_bids_unique(_input_names.size());
+
+  // For an error check on input_bids_unique later
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:99]:
```suggestion
  // For an error check on the number of uniquely named boundaries to stitch
```

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 25]
```diff
@@ -88,35 +116,68 @@ PatternedMeshGenerator::generate()
...
+    mooseAssert(ids.size() == boundary_names.size(),
+                "Unexpected number of ids returned for MooseMeshUtils::getBoundaryIDs");
 
-  // Getting the boundaries provided by the user
-  std::vector<BoundaryName> boundary_names = {getParam<BoundaryName>("left_boundary"),
-                                              getParam<BoundaryName>("right_boundary"),
-                                              getParam<BoundaryName>("top_boundary"),
-                                              getParam<BoundaryName>("bottom_boundary")};
+    // Keep track of used IDs so we can later find IDs that are unused across all meshes
+    used_boundary_ids.insert(ids.begin(), ids.end());
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:126]: this isnt a full list of used ids. It's only ids used for the the names op top/left/...

In ids, you need to get ALL ids in those meshes to find ones that are never used. 

Otherwise when you change ids you ll hit existing ids that are not part of top/left/...

Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:126]: but then your use of ids below is different. 

I reckon you should create a new all_ids set here, then use all_ids for used_boundary_ids

**Review by GiudGiud — CHANGES_REQUESTED** [review]

**Comment by pbehne** [comment]
@GiudGiud, please check changes in latest commit. If all looks good, I will squash into the previous commit.

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 26]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
...
+      "left_boundary", "right_boundary", "top_boundary", "bottom_boundary"};
+  const std::set<std::string> boundary_names_set(boundary_names.begin(), boundary_names.end());
+
+  // IDs for each input (indexed by input mesh and then left/right/top/bottom)
+  std::vector<std::vector<boundary_id_type>> input_bids(
+      _input_names.size(), std::vector<boundary_id_type>(4, Moose::INVALID_BOUNDARY_ID));
+  bool have_common_ids = true;
+
+  // Keep track of used boundary ids to generate new, unused ones later (if needed)
+  std::set<boundary_id_type> all_boundary_ids;
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:94]: move this down too

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 27]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
...
+
+  // Using a vector of vectors instead of vector of sets to preserve insertion order
+  std::vector<std::vector<boundary_id_type>> input_bids_unique(_input_names.size());
+
+  // For an error check on the number of uniquely named boundaries to stitch
+  size_t set_length = 0;
+
+  // Given a boundary name (i.e., 'left_boundary'), this will give the correct
+  // index to get the correct boundary id to later use for boundary stitching
+  std::map<std::string, size_t> boundary_name_to_index_map;
```
Comment (GiudGiud) [inline framework/src/meshgenerators/PatternedMeshGenerator.C:104]: move it down next to where it s filled too

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/src/meshgenerators/PatternedMeshGenerator.C [hunk 28]
```diff
@@ -76,8 +76,36 @@ PatternedMeshGenerator::generate()
...
   _meshes.reserve(_input_names.size());
 
+  // Getting the boundaries provided by the user
+  const std::vector<BoundaryName> boundary_names = {getParam<BoundaryName>("left_boundary"),
+                                                    getParam<BoundaryName>("right_boundary"),
+                                                    getParam<BoundaryName>("top_boundary"),
+                                                    getParam<BoundaryName>("bottom_boundary")};
+  const std::vector<std::string> boundary_param_names = {
+      "left_boundary", "right_boundary", "top_boundary", "bottom_boundary"};
+  const std::set<std::string> boundary_names_set(boundary_names.begin(), boundary_names.end());
```
[the remark this answers is not in the document]
Comment (GiudGiud) [reply framework/src/meshgenerators/PatternedMeshGenerator.C:86]: ugh was left as a pending 2 hours ago

[the remark this answers is not in the document]
Comment (pbehne) [reply framework/src/meshgenerators/PatternedMeshGenerator.C]: Not anymore. I have removed it.

**Review by GiudGiud — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]

**Comment by pbehne** [comment]
@loganharbour, @GiudGiud, Any idea what's going on with the Griffin failures? I don't see how they are related to my PR.

**Comment by GiudGiud** [comment]
Unrelated

**Comment by GiudGiud** [comment]
Logan is assigned so he'll merge your PR when appropriate. You can move on to something else at this point

**Comment by loganharbour** [comment]
Will go in today when it's all green.
