### PR TITLE
Distributed-displaced mesh generation plus mortar convergence studies

### LINKED ISSUE #15785: cannot simultaneously use mesh adaptivity and automatic scaling at each step
I came across this when trying to apply some mesh adaptivity to a phase field problem with automatic scaling. If trying to do BOTH mesh adaptivity AND recompute scaling at each step, I hit an assert at the beginning of the second time step. If I remove either the mesh adaptivity or set `compute_scaling_once = true`, then problem runs fine. I'm running with the latest moose master (34fb8fad) and I believe my conda environment is up-to-date.

## Bug Description
Cannot run a problem with both adaptivity and automatic scaling computed every step.

## Steps to Reproduce
Add the following lines to the Executioner block of [both_split_2vars.i](https://github.com/idaholab/moose/blob/next/modules/phase_field/test/tests/actions/both_split_2vars.i)
```
  automatic_scaling = true
  compute_scaling_once = false

  [./Adaptivity]
    initial_adaptivity = 0
    cycles_per_step = 1
    refine_fraction = 0.95
    coarsen_fraction = 0.1
    max_h_level = 2
  [../]
```
## Impact
Would expect to use both these features simultaneously.

---
Here's the output when I run in debug mode:
```
Time Step 2, time = 0.1, dt = 0.05
Assertion `i < size()' failed.
i = 1827
size() = 1827


Stack frames: 30
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::PetscVector<double>::add(unsigned int, double)
3: libMesh::DiagonalMatrix<double>::add(unsigned int, unsigned int, double)
4: Assembly::addCachedJacobian()
5: FEProblemBase::addCachedJacobian(unsigned int)
6: ComputeJacobianThread::postElement(libMesh::Elem const*)
7: ComputeJacobianForScalingThread::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool)
8: /home/jesse/projects/moose/framework/.libs/libmoose-dbg.so.0(+0x356e768) [0x7fd95bdb2768]
9: NonlinearSystemBase::computeJacobianInternal(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
10: NonlinearSystemBase::computeJacobianTags(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
11: FEProblemBase::computeJacobianTags(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
12: FEProblemBase::computeJacobianInternal(libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
13: FEProblemBase::computeJacobian(libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&)
14: FEProblemBase::computeJacobianSys(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&)
15: NonlinearSystem::computeScalingJacobian()
16: NonlinearSystemBase::computeScaling()
17: NonlinearSystem::solve()
18: FEProblemBase::solve()
19: FEProblemSolve::solve()
20: PicardSolve::solveStep(double, double&, double, double&, bool, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
21: PicardSolve::solve()
22: TimeStepper::step()
23: Transient::takeStep(double)
24: Transient::execute()
25: MooseApp::executeExecutioner()
26: MooseApp::run()
27: /home/jesse/projects/moose/modules/phase_field/.libs/phase_field-dbg(+0x1338c) [0x55a9a18e838c]
28: __libc_start_main
29: /home/jesse/projects/moose/modules/phase_field/.libs/phase_field-dbg(+0x12169) [0x55a9a18e7169]
[0] ../src/numerics/petsc_vector.C, line 190, compiled Aug 11 2020 at 09:54:30
Assertion `i < size()' failed.
i = 1827
size() = 1827


Stack frames: 27
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::PetscVector<double>::add(unsigned int, double)
3: libMesh::DiagonalMatrix<double>::add(unsigned int, unsigned int, double)
4: Assembly::addCachedJacobian()
5: FEProblemBase::addCachedJacobian(unsigned int)
6: NonlinearSystemBase::computeJacobianInternal(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
7: NonlinearSystemBase::computeJacobianTags(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
8: FEProblemBase::computeJacobianTags(std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
9: FEProblemBase::computeJacobianInternal(libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
10: FEProblemBase::computeJacobian(libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&)
11: FEProblemBase::computeJacobianSys(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::SparseMatrix<double>&)
12: NonlinearSystem::computeScalingJacobian()
13: NonlinearSystemBase::computeScaling()
14: NonlinearSystem::solve()
15: FEProblemBase::solve()
16: FEProblemSolve::solve()
17: PicardSolve::solveStep(double, double&, double, double&, bool, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&)
18: PicardSolve::solve()
19: TimeStepper::step()
20: Transient::takeStep(double)
21: Transient::execute()
22: MooseApp::executeExecutioner()
23: MooseApp::run()
24: /home/jesse/projects/moose/modules/phase_field/.libs/phase_field-dbg(+0x1338c) [0x55a9a18e838c]
25: __libc_start_main
26: /home/jesse/projects/moose/modules/phase_field/.libs/phase_field-dbg(+0x12169) [0x55a9a18e7169]
[0] ../src/numerics/petsc_vector.C, line 190, compiled Aug 11 2020 at 09:54:30
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

### PR DESCRIPTION
**Pull request by lindsayad**
Looks at:
- approximately matching size discretizations on slave/master
- approximately 2:1 slave:master mismatch
- approximately 1:2 slave:master mismatch

I'm observing first order convergence for the LM no matter which I use,
when I expect super-convergence especially in the case of matching
mesh sizes.

master-coarser
slave-coarser
same

I saw super-convergence in results shared in #13080 so I'm going to have to spend some more time with this

### CODE REVIEW

**Comment by lindsayad** [comment]
This is if I have *exact* 2:1 mismatches. It seems like there is almost certainly a bug in here...
master-coarser
slave-coarser

@dewenyushu just so you're aware that I'm doing some convergences studies with a standard LM. Some results I'm not pleased with...

**Comment by lindsayad** [comment]
Ok the results from a38f842 look like what they did in #13080, so that's a relief. Maybe there's a bug in how I'm using the mesh generators in 59e67ab 

p1p0

**Comment by lindsayad** [comment]
3aff05f with p2p1
p2p1

**Comment by lindsayad** [comment]
@jwpeterson it looks like the mortar implementation isn't totally broken

**Comment by jwpeterson** [comment]
@lindsayad I started with your case of a 5x11 mesh next to a 5x5 mesh (so approximately 2:1 mismatch) and did a uniform refinement study of the stabilized P1-P0 formulation, varying which side of the interface was treated as the slave side. What I found was that both formulations converged at O(h) in the asymptotic limit, so no super-convergence, but the error for the "coarser slave" case was *much* (like 100x) lower. I'd be curious to see if you get a similar result in the existing and dual formulations in MOOSE.

compare_2to1

**Comment by lindsayad** [comment]
> so no super-convergence

Does the technical report outline conditions under which super-convergence may be observed?

> but the error for the "coarser slave" case was _much_ (like 100x) lower.

Very interesting. Here's a new result with my "gmsh" mesh case:
p1p0-multiple-lines

I do indeed see that the coarser slave yields lower errors for the mesh sizes examined; however, in this case it appears that the asymptotic convergence rate is better for the coarse master case.

**Comment by lindsayad** [comment]
> stabilized P1-P0 formulation

Is stabilization technically required even when using a mixed order discretization?

**Comment by lindsayad** [comment]
Ok, yea with the "MOOSE" mesh, I see basically the exact same thing as you did @jwpeterson :
multiple-lines

**Comment by jwpeterson** [comment]
Do your Gmsh meshes not have the 2:1 element size mismatch or something? I'm curious why they are so "good" compared to the MOOSE mesh. Any other difference between the Gmsh and MOOSE meshes?

> Is stabilization technically required even when using a mixed order discretization?

The unequal-order discretizations are still technically LBB-unstable, as far as I understand things. There's more info on this in the Barbosa & Hughes paper cited in the report. That doesn't mean that you can't get an answer, though, so "required" is a strong word. 

I always observed much lower error for the stabilized formulations, e.g. by about a factor of 10 in the 2:1 mismatch case. You can see this especially in the line plots comparing the flux solutions in the report... also when using unstabilized P^1 - P^0, I sometimes observed a large increase in the number of GMRES iterations required by the linear solver. I wasn't sure exactly what caused this, but generally speaking the stabilized formulation gave much more predictable results so I always preferred to use it.

**Comment by jwpeterson** [comment]
> Does the technical report outline conditions under which super-convergence may be observed?

No, the most useful a-priori error estimate that I found was in the Barbosa & Hughes paper, which is Eqn. (67) in the report. Technically it only applies to the stabilized formulation and the mesh-dependent norm shown, but it is qualitatively similar to other a-priori estimates in that only the "combined" primal H1-error + flux L2-error is predicted. So super-convergence of the flux error is never precluded by these estimates, but also they don't allow you to predict when it will/will not happen. 

So far in your results I have always seen at least O(h^2) for the flux in the P2-P1 formulation and at least O(h) for the flux in the P1-P0 formulation, which is in agreement with the theory. The theory also doesn't preclude (but doesn't explain) the difference we see in the coarse slave vs. coarse master formulations, this must somehow be accounted for by the constant "C" in the estimate being quite different for the two cases...

**Comment by jwpeterson** [comment]
Anyway, I think we can conclude from your results that choosing the slave side to be the coarser of the two almost always results in lower overall error, except for possibly in the P2-P1 case on "sufficiently-refined" grids but in that case the error is very close for almost the entire range of h, so this may be something to worry about only in the P1-P0 case.

**Comment by lindsayad** [comment]
> Do your Gmsh meshes not have the 2:1 element size mismatch or something? I'm curious why they are so "good" compared to the MOOSE mesh. Any other difference between the Gmsh and MOOSE meshes?

They do not have the 2:1 mismatch; it's probably more like 6:5, or maybe even closer than that to a unity ratio (but definitely not perfectly 1). In terms of element size mismatch the gmsh mesh is probably closest to the "same" case for the MOOSE mesh, where there is still a slight mismatch with the master begin slightly finer. I guess then that the MOOSE and gmsh mesh results are not too discrepant, since gmsh "slightly coarser slave" case has a flux converging at ~1.1 while the MOOSE "slightly coarser slave" (e.g. the poorly named "same") converges at 1.0

**Comment by jwpeterson** [comment]
> They do not have the 2:1 mismatch; it's probably more like 6:5, or maybe even closer than that to a unity ratio (but definitely not perfectly 1).

OK, that's good, I think it explains why we see superconvergent flux behavior for the Gmsh meshes. This is also consistent with what I've seen in the past for nearly-equal-h-but-mismatched meshes. 

It would be great if you could also run the P2-P1 solve on the 2:1 mismatched "MOOSE" meshes and see if you observe the same big accuracy difference between the coarse and fine slave in that case. Based on your other results, I would expect the difference to be much less pronounced than in the P1-P0 case, but it would be good to confirm that. Unfortunately, I did not implement P2-P1 in my libmesh code, so I don't have a point of comparison for this one.

**Comment by lindsayad** [comment]
This is P2P1 with the MOOSE generated mesh with slave-to-master size ratio 11:5
multiple-lines

Wowzers trousers. You could say that the difference is still quite pronounced haha. Even worse here...

**Comment by jwpeterson** [comment]
> You could say that the difference is still quite pronounced haha.

To me this looks like a definite bug in the "coarse slave" case since the rates are wrong... no idea what would cause that though given that coarse master seems to work fine!

**Comment by lindsayad** [comment]
Oh yea, stabilization is the key!!! Thanks @jwpeterson for getting me to see the light. Below is P1P0 exact 2:1 mismatch. Stabilized has delta = 0.4:
4-to-2

**Comment by lindsayad** [comment]
> To me this looks like a definite bug in the "coarse slave" case since the rates are wrong... no idea what would cause that though given that coarse master seems to work fine!

This definitely still seems to be the case for P2P1. Stabilization did not make the bad P2P1 coarse slave behavior go away. I actually didn't catch that it was the coarse slave case that was buggy in P2P1; I had been thinking that it was the coarse master case that was buggy as it was for P1P0 (whose "bug" was fixed by just adding stabilization (see https://github.com/idaholab/moose/pull/15338#issuecomment-635646775)).

Here's an updated P2P1 plot, with stabilization cases also included:
multiple-lines

Although the error is still significantly higher than for a roughly matched interface, adding stabilization the the coarse master case drops the error substantially from the unstabilized case (and actually makes it slightly super-convergent with slope 2.3).

But stabilization had no effect on the coarse slave case for P2P1, the flux is still non-convergent and the primal variable has sub-optimal convergence.

**Comment by lindsayad** [comment]
Ok heretofore summary. The below figures have a base mesh of left-nx=2, right-nx=2, coarse-ny=2. In the plots ny denotes the fine side ny:

p2p1-ny-4
p2p1-ny-5
p1p0-ny-4
p1p0-ny-5

P1P0 looks good. Don't quite know what to make of P2P1. The 5:2 mismatch looks pretty wonky but the 4:2 looks a lot better. Maybe for mortar validation I shouldn't be doing solution continuity at all, and maybe I could figure out an MMS for something like gap conductance...

**Comment by jwpeterson** [comment]
@lindsayad I agree the P1-P0 results are a big improvement, nice work! I will check whether the Barbosa & Hughes paper says anything special about P2 elements, but I don't seem to recall anything. It is a bit surprising that P2-P1 converges for a little while but then the line turns back up... is it possible there is some tolerance issue in the nodal projections that is only showing up once the mesh is sufficiently refined?

**Comment by lindsayad** [comment]
Ok got some weekend free time to return to this. I setup a gap conductance MMS case, which nicely doesn't require stabilization, and I'm seeing the same behavior that I did with the solution continuity test case. P1P0 looks great. P2P1 looks good for a 4:2 mismatch but like trash for 5:2. Something I find interesting here is that the coarse master case has lower error for the flux in all cases.

p1p0-ny-4
p1p0-ny-5
p2p1-ny-4
p2p1-ny-5

**Comment by lindsayad** [comment]
Let's see, the coarse slave cases work out like this:

- optimal convergence: 2:2, 3:2, 4:2
- poor convergence: 5:2, 6:2, 8:2

**Comment by jwpeterson** [comment]
This sounds like good progress, especially the fact that we can rule out issues with stabilization since you used a gap heat conduction MMS. The fact that *all* coarse master cases and *some* coarse slave cases are working suggests to me that the code is essentially working, but there is some bug which seems to only be triggered by P2 elements with a coarser slave discretization. 

I'd suspect either the projection of slave nodes onto the master surface or the inverse projection of master nodes from the slave surface. If there is a bug there, the general formulas for the projections are most likely correct and there are just some "edge" cases which don't work correctly. What do you think? Any ideas what the issue might be?

**Comment by jwpeterson** [comment]
OK, one more comment: after drawing some pictures, it looks like all of your sub-optimal cases occur when at least 3 master elements touch a *single* element on the slave side, the simplest example of this being the 3:1 case. In all the optimal cases a maximum of 2 master side elements touch any given slave element. Maybe this is a clue to what the issue is...

**Comment by lindsayad** [comment]
Oh wow such beautiful code

p2p1-7-to-3
p2p1-6-to-3
p2p1-5-to-3
p2p1-4-to-3
p2p1-3-to-3
p2p1-2-to-3
p2p1-1-to-3

**Comment by jwpeterson** [comment]
Looks good, we expect O(h^2) convergence rate for the flux in this case and it looks like we get exactly that now! I'm glad you did the extensive MMS testing... otherwise this bug would probably have gone undetected for even longer than it did.

**Comment by lindsayad** [comment]
Yea I'm glad @dewenyushu's work inspired me to do it. It's been fun to work on mortar again!

**Comment by jwpeterson** [comment]
Maybe the only case you haven't explicitly confirmed is P2-P0, for which I would expect to see O(h^1.5) rate of convergence for the flux. 

The more I think about it, in the P2-P0 case you get the biggest bang for your buck since you get the full O(h^{r + 3/2}) (where r is the polynomial degree of the flux var) whereas with P2-P1 you get P1-P0 you get O(h^{r+1}) only. IMO that makes P2-P0 an interesting case.

**Comment by lindsayad** [comment]
I'll try that out after I figure out a sparsity allocation problem that
makes this annoyingly slow to run for large problems...

**Comment by lindsayad** [comment]
It looks to me that with P2P0 you actually lose optimal convergence in the primal variable
p2p0-2-to-2
p2p0-3-to-2
p2p0-4-to-2
p2p0-6-to-2

Taking the 5:2 coarse master case through a couple more refinements:
p2p0-5-to-2

**Comment by lindsayad** [comment]
Convergence summary:
| discretization | L2 primal | L2 lambda |
| --- | --- | --- |
| p2p2 | 3 | 3|
|p2p1 |3|2|
|p2p0|2|1|
|p1p1|2|2|
|p1p0|2|1|

**Comment by jwpeterson** [comment]
Hmm... I'm not quite sure what to make of the P2-P0 results. Not what I was expecting but it's definitely possible I (still) don't completely understand the a-priori estimates for this case. Note that  you are computing the L2-norm of the primal solution in all of these plots, but the estimates are actually for (something proportional to) the H1-norm of the primal solution, for what it's worth. 

1. For the stabilized solution continuity case, the relevant norm and estimate are given by (66), (67), respectively, in the Tech Report.
1. For the unstabilized equal-order case, the norm and estimate are given by (58), (65).

I think neither of these estimates are directly applicable to the P2-P0 gap heat conduction problem, unfortunately, since it uses non-equal order approximations *and* doesn't use stabilization.  

The latter estimate *should* be applicable to the P2-P2 discretization case, and it predicts that you should see O(h^2) convergence in the combined norm. Therefore I was a bit surprised that you saw O(h^3) for lambda in that case, but then I remembered that you are using that quartic exact solution? I believe the true flux is quadratic in that case, so it is in the space of the P2-P2 approximation. Therefore it's possible you are seeing some kind of "superconvergent" effect in P2-P2 which is just due to the choice of exact solution.

**Comment by dewenyushu** [comment]
@lindsayad great fix! I tried two weeks ago to check by hand the projected nodes for a 5:3 case but did not find anything suspicious. So I am really impressed by this fix and excited to see how this will change the dual mortar convergence!

Nice to see stabilization been added, too! Has stabilization been enabled for mortar contact or is it an ongoing process?

**Comment by jwpeterson** [comment]
@dewenyushu I don't think (this particular form of) stabilization is needed for the contact problem, at least in the formulation discussed in Popp's paper, since the constraint equation involves the Lagrange multiplier variable itself. This is in contrast to the solution continuity formulation which otherwise has a zero block on the diagonal for the constraint equations. It would be good to know for sure whether this is the case, though. I guess there are somehow no issues of LBB-stability for the dual mortar formulation?

**Comment by dewenyushu** [comment]
> @dewenyushu I don't think (this particular form of) stabilization is needed for the contact problem, at least in the formulation discussed in Popp's paper, since the constraint equation involves the Lagrange multiplier variable itself. This is in contrast to the solution continuity formulation which otherwise has a zero block on the diagonal for the constraint equations. It would be good to know for sure whether this is the case, though. I guess there are somehow no issues of LBB-stability for the dual mortar formulation?

Thanks for the reply! Good question about the stability condition. I think the dual basis satisfies the inf-sup condition by construction. I read statements like this in this paper: 

https://www.cambridge.org/core/journals/acta-numerica/article/variationally-consistent-discretization-schemes-and-numerical-algorithms-for-contact-problems/7B66B8B7573361A299206BE15E1B325D

There should be mathematical proofs somewhere else, but I have not dig deep enough for that.

**Comment by lindsayad** [comment]
> The latter estimate _should_ be applicable to the P2-P2 discretization case, and it predicts that you should see O(h^2) convergence in the combined norm. Therefore I was a bit surprised that you saw O(h^3) for lambda in that case, but then I remembered that you are using that quartic exact solution? I believe the true flux is quadratic in that case, so it is in the space of the P2-P2 approximation. Therefore it's possible you are seeing some kind of "superconvergent" effect in P2-P2 which is just due to the choice of exact solution.

I actually saw fourth order in lambda when using the previous MMS solution and was very puzzled before remembering exactly what you're saying. So I adjusted the MMS such that the true value of lambda is cubic on the interface. Then convergence reduced to third order.

I wonder at those a priori estimates...it seems like those estimates are always given in the context of solution continuity. I guess it's unclear to me whether they are generally applicable. 3 and 3 for the P2P2 is consistent with the 2 and 2 for P1P1.

**Comment by jwpeterson** [comment]
> I guess it's unclear to me whether they are generally applicable.

That's a really good point actually... the gap heat conduction formulation is almost "artificial" in the sense that you introduce an extra variable to discretize the flux, but in theory you could solve the problem "directly" using only primal variables. The same isn't true for solution continuity or, in the context of some of the papers on this subject, the imposition of essential BCs using Lagrange multipliers. It is probably wrong to try and apply the same estimates in both cases. Thinking of it as a standard coupled problem, we would optimally expect O(h^{p+1}) for both variables in L2-norm, which is exactly what you observe.

**Comment by jwpeterson** [comment]
> which is exactly what you observe.

Except for the P2-P0 case, of course. I suspect that the primal variable error is "polluted" by the error from the two-orders-lower flux discretization in that case, so that formulation is definitely suboptimal in comparison to the others for gap heat conduction.

**Comment by lindsayad** [comment]
> Thinking of it as a standard coupled problem, we would optimally expect O(h^{p+1}) for both variables in L2-norm, which is exactly what you observe.

Yes and I also think if

> Except for the P2-P0 case, of course. I suspect that the primal variable error is "polluted" by the error from the two-orders-lower flux discretization in that case, so that formulation is definitely suboptimal in comparison to the others for gap heat conduction.

Right. If we're thinking about it as a standard coupled problem, I would intuitively expect that if we're equating the flux (proportional to the primal first derivative) to a variable representation that is not one, but two orders less than the primal, that we would be unable to capture optimal convergence.

**Comment by jwpeterson** [comment]
BTW, you may be aware of this already, but I thought I'd just add that if you were to solve the primal-only problem and then simply differentiate the FE solution (i.e. post-process it) to obtain the boundary flux, this is known to converge as O(h^p) in L2, where p is the polynomial degree used to approximate the primal variable. Therefore, the benefit we get from the extra "work" of discretizing/solving for the flux as an extra variable is the higher-order accurate, O(h^{p+1}), approximation we get.

**Comment by jwpeterson** [comment]
... all of which leads me to conclude that, for the gap heat conduction application, it makes the most sense to use equal-order approximations (P2-P2 or P1-P1) for the primal and flux variables. If you use e.g. P2-P1 you'll get an O(h^2) approximation to the flux... but that's the same as what you would expect to get by just differentiating/post-processing the FE solution... so there's no point in doing the extra work of defining/solving for a separate flux variable just to end up with the same accuracy. 

This argument only applies to gap heat conduction of course. I think for continuity enforcement it makes sense to use mixed-order because the error estimates are different.

**Comment by lindsayad** [comment]
@jwpeterson do you have any thoughts on why solution continuity stabilization might be weird for second order elements? I see these weird spikes in the convergence plots for some of the stabilized cases. First order elements always look good. Moreover, second order elements without stabilization never show any spikes

p1p0-3-to-2
p1p1-3-to-2
p2p0-3-to-2
p2p1-3-to-2
p2p2-3-to-2

**Comment by lindsayad** [comment]
This is my favorite:
p2p0-5-to-2

**Comment by lindsayad** [comment]
Need to update this branch with #15473

**Comment by jwpeterson** [comment]
Yeah @lindsayad I don't know what would cause these jumps in the convergence plot *only* for the stabilized scheme... if it was some other issue with the creation of the mortar segments on P2 elements, you'd definitely expect it to show up in the unstabilized case as well. 

P2-P0 definitely seems to be the most erratic of the bunch, especially in your last image where the error jumps the most on the finest mesh! Maybe best to just avoid P2-P0 if we don't really understand what's going on with it, and stick to equal-order or flux-one-order-less formulations in general? Even in the P2-P0 cases that "work", the flux is only converging at 1st-order ($\ell + 1$), we see the same basic pattern in the P2-P1 case and the results are a lot smoother.

**Comment by lindsayad** [comment]
@jwpeterson the erraticism is gone with delta = 0.1:

p2p0-5-to-2
p2p1-5-to-2
p2p2-5-to-2

**Comment by jwpeterson** [comment]
> the erraticism is gone with delta = 0.1:

:+1: It's so beautiful.

**Comment by jwpeterson** [comment]
So if I look at for example the orange and brown lines in the P2P2-5-to-2 figure, it seems they both have the same slope but the stabilized one has lower error. Similarly for the red and grey lines, although not quite as large of a gap. It seems that using stabilization is therefore both more robust (avoid occasional convergence failures) and more accurate, so win-win.

**Comment by jwpeterson** [comment]
Oh, also worth noting is that we lose a half-power of h for the primal variable L2-norm in the P2-P0 case, i.e. we get O(h^2.5), so IMO this is similar to the gap heat conduction case where we concluded that this formulation is sub-optimal/the LM variable error pollutes the primal variable error. That's also good to know.

**Comment by lindsayad** [comment]
Both good points. I'm satisfied that the code is beautiful now

**Comment by jwpeterson** [comment]
OK, one last thing that seems important and I totally forgot to mention: you are actually seeing different convergence rates for the P2-P0 and P2-P2 cases depending on coarse primary/secondary. P2-P1 seems to not be affected by this choice. I will try to summarize in the tables below:

| **Coarse Primary**           |  u | LM |
|----------| --------- | -- |
| P2-P0 |      3       |  1  |
| P2-P1 |      3      |  2  |
| P2-P2 |      3       |  2  |


| **Coarse Secondary**           |  u | LM |
|----------| --------- | -- |
| P2-P0 |      *2.5* &#x1F53B;      |  1  |
| P2-P1 |      3      |  2  |
| P2-P2 |      3       |  *2.5* &#x1F53A;  |

I'm not sure whether these results are general, etc. but IMO since you generally can't guarantee whether primary or secondary will be "coarser" in real problems, P2-P1 seems like the most robust discretization since it doesn't care, P2-P0 should probably be avoided, and the extra cost of P2-P2 vs. P2-P1 isn't worth the chance of possibly getting O(h^2.5) convergence for the LM.

**Comment by lindsayad** [comment]
Well put!

**Comment by lindsayad** [comment]
Ok, resuming work on this PR. I'm going to make the correct interaction of mesh generators with distributed mesh a prereq for getting this merged, e.g. the tests in this PR must be able to to run with distributed mesh.

**Comment by lindsayad** [comment]
Some good discussion of distributed mesh and relationship managers in #15655

**Comment by lindsayad** [comment]
@fdkong do you want to merge #15655 into this? I currently have all your commits from there on here. At this point I don't see much of a reason to divorce the mortar stuff from other code in this PR because the mortar convergence study portion of the PR should be relatively small in terms of % line-count. I could try though to split out the commits that are meant to help #15655 but I'm not sure if I would be able to.

If we do decide to combine, I know this PR needs gold nemesis files for your new test(s)

**Comment by fdkong** [comment]
> If we do decide to combine, I know this PR needs gold nemesis files for your new test(s)

Yes, we could roll together

**Comment by jessecarterMOOSE** [comment]
Hey @lindsayad @fdkong - I checked out this PR in order to do mesh adaptivity and automatic scaling, which does work, but when I add a few simple materials and then try to do a LineMaterialRealSampler VectorPostprocessor, I get a segfault, even if I don't use scaling. For example, adding the following to [cycles_per_step.i](https://github.com/idaholab/moose/blob/next/test/tests/adaptivity/cycles_per_step/cycles_per_step.i) is enough to cause the segfault.

```
[Materials]
  [./const]
    type = GenericConstantMaterial
    prop_names = 'A B'
    prop_values = '1.0 2.0'
  [../]
[]

[VectorPostprocessors]
  [./mats]
    type = LineMaterialRealSampler
    start = '0 0 0'
    end = '10 10 0'
    property = 'A B'
    sort_by = 'x'
  [../]
[]
```

After a few timesteps it spits out this:
```

No index 18446744073709551615 in ghosted vector.
Vector contains [0,2960)
And empty ghost array.
```

And then a bunch of debugging information that you would probably find useful but I want to clog up the chat.

**Comment by lindsayad** [comment]
> when I add a few simple materials and then try to do a LineMaterialRealSampler VectorPostprocessor, I get a segfault, even if I don't use scaling.

Fun! This still has some failing framework tests to resolve. Once I resolve those, I will look test your input and see what's going on. Appreciate the bug report!

**Comment by lindsayad** [comment]
This periodic simulation is really pissing me off

**Comment by fdkong** [comment]
> This periodic simulation is really pissing me off

Sorry, buddy

IIRC, the source is discontinuous, and there is only a small region with nonzero values.  That somehow makes the solution in the transition zone different in different runs. The original loose tolerances I added do not work? You do not need to tighten the tolerances.

If it  is only the test that blocks you, you could skip it (or you use ridiculous tols as well) for a moment. I will investigate into it once I have a chance. As you know, I have to work on another project at this point.

**Comment by lindsayad** [comment]
Oh wow such beautiful green. Just dying to be reviewed

**Comment by jwpeterson** [comment]
This PR has been quite a journey!

**Comment by fdkong** [comment]
> Oh wow such beautiful green. Just dying to be reviewed

So beautiful, I should merge it instead of review it

File: framework/src/actions/AddRelationshipManager.C [hunk 1]
```diff
@@ -14,6 +14,9 @@
 registerMooseAction("MooseApp", AddRelationshipManager, "attach_geometric_rm");
 registerMooseAction("MooseApp", AddRelationshipManager, "attach_algebraic_rm");
 registerMooseAction("MooseApp", AddRelationshipManager, "attach_coupling_rm");
+registerMooseAction("MooseApp", AddRelationshipManager, "add_geometric_rm");
+registerMooseAction("MooseApp", AddRelationshipManager, "add_algebraic_rm");
+registerMooseAction("MooseApp", AddRelationshipManager, "add_coupling_rm");
```
Comment (fdkong) [inline framework/src/actions/AddRelationshipManager.C:19]: What are differences between "attach" and "add"?

File: framework/src/base/Assembly.C [hunk 2]
```diff
@@ -2654,25 +2681,25 @@ Assembly::prepareLowerD()
...
                   jvar.dofIndices().size() * jvar.count());
 
-      jacobianBlockLower(Moose::LowerPrimary, vi, vj, tag)
+      jacobianBlockMortar(Moose::LowerPrimary, vi, vj, tag)
           .resize(ivar.dofIndicesLower().size() * ivar.count(),
                   jvar.dofIndicesNeighbor().size() * jvar.count());
 
       // derivatives w.r.t. interior secondary residuals
-      jacobianBlockLower(Moose::SecondaryLower, vi, vj, tag)
+      jacobianBlockMortar(Moose::SecondaryLower, vi, vj, tag)
```
Comment (fdkong) [inline framework/src/base/Assembly.C:2697]: Motivation that you changed "Lower" to "Mortar"?

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 3]
```diff
@@ -44,24 +46,29 @@ AutomaticMortarGeneration::AutomaticMortarGeneration(
...
   primary_requested_boundary_ids.insert(boundary_key.first);
   secondary_requested_boundary_ids.insert(boundary_key.second);
   primary_secondary_subdomain_id_pairs.push_back(subdomain_key);
   primary_boundary_subdomain_ids.insert(subdomain_key.first);
   secondary_boundary_subdomain_ids.insert(subdomain_key.second);
+
+  if (_distributed)
+    mortar_segment_mesh = libmesh_make_unique<DistributedMesh>(mesh.comm());
+  else
+    mortar_segment_mesh = libmesh_make_unique<ReplicatedMesh>(mesh.comm());
```
Comment (fdkong) [inline framework/src/constraints/AutomaticMortarGeneration.C:65]: `_distributed` should simply derive from the parent  mesh. For example, if I am using 3D distributed mesh, I would expect 2D mortar mesh is distributed as well.

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 4]
```diff
@@ -119,6 +126,25 @@ AutomaticMortarGeneration::buildMortarSegmentMesh()
...
+  for (const auto & pr : primary_secondary_boundary_id_pairs)
+  {
+    const auto primary_bnd_id = pr.first;
+    const auto secondary_bnd_id = pr.second;
+    const auto num_primary_nodes =
+        std::distance(mesh.bid_nodes_begin(primary_bnd_id), mesh.bid_nodes_end(primary_bnd_id));
+    const auto num_secondary_nodes =
+        std::distance(mesh.bid_nodes_begin(secondary_bnd_id), mesh.bid_nodes_end(secondary_bnd_id));
+
+    node_unique_id_offset += num_primary_nodes + 2 * num_secondary_nodes;
```
Comment (fdkong) [inline framework/src/constraints/AutomaticMortarGeneration.C:145]: It would be great if you could have documents how you come up these magic offsets.

File: framework/src/constraints/AutomaticMortarGeneration.C [hunk 5]
```diff
@@ -133,22 +159,30 @@ AutomaticMortarGeneration::buildMortarSegmentMesh()
...
+      new_node->set_unique_id(new_node->id() + node_unique_id_offset);
+    }
 
     Elem * new_elem;
     if (secondary_elem->default_order() == SECOND)
-      new_elem = mortar_segment_mesh.add_elem(new Edge3);
+      new_elem = new Edge3;
     else
-      new_elem = mortar_segment_mesh.add_elem(new Edge2);
+      new_elem = new Edge2;
```
Comment (fdkong) [inline framework/src/constraints/AutomaticMortarGeneration.C:173]: Mortar mesh is always 1D?

File: framework/src/relationshipmanagers/AugmentSparsityOnInterface.C [hunk 6]
```diff
@@ -78,79 +91,132 @@ AugmentSparsityOnInterface::operator()(const MeshBase::const_element_iterator &
...
+        mooseAssert(secondary_boundary_id != Moose::INVALID_BOUNDARY_ID,
+                    "Secondary boundary id should exist by now. If you're using a MeshModifier "
+                    "please use the corresponding MeshGenerator instead");
+        mooseAssert(primary_subdomain_id != Moose::INVALID_BLOCK_ID,
+                    "Primary subdomain id should exist by now. If you're using a MeshModifier "
+                    "please use the corresponding MeshGenerator instead");
+        mooseAssert(secondary_subdomain_id != Moose::INVALID_BLOCK_ID,
+                    "Secondary subdomain id should exist by now. If you're using a MeshModifier "
+                    "please use the corresponding MeshGenerator instead");
+
```
Comment (fdkong) [inline framework/src/relationshipmanagers/AugmentSparsityOnInterface.C:166]: Roy styles, Assert everywhere , haha

File: test/tests/bcs/dmg_periodic/tests [hunk 7]
```diff
@@ -12,12 +12,9 @@
   [../]
 
   [./check_one_step]
-    type = 'Exodiff'
+    type = 'RunApp'
```
Comment (fdkong) [inline test/tests/bcs/dmg_periodic/tests:15]: Still have diff issues?

File: test/tests/mesh/periodic_node_map/tests [hunk 8]
```diff
@@ -8,6 +8,7 @@
 
     requirement = "The system shall produce a valid periodic node map with only one periodic constraint direction."
     recover = false  # Steady Test (Needs to be here since we don't want the checkpoints clobbering each other)
+    mesh_mode = 'replicated' # We no longer ghost all periodic boundaries for all procs
```
Comment (fdkong) [inline test/tests/mesh/periodic_node_map/tests:11]: mesh_mode = 'replicated distributed'? I want to test both

**Review by fdkong — CHANGES_REQUESTED** [review]
It looks great for me.

Should we ask for one more judge  because I have a few commits in this PR?

File: framework/include/base/Assembly.h [hunk 9]
```diff
@@ -389,6 +395,22 @@ class Assembly
...
+  /**
+   * Return the neighboring lower dimensional element
+   * @return A _reference_.  Make sure to store this as a reference!
+   */
+  const Elem * const & neighborLowerDElem() const { return _current_neighbor_lower_d_elem; }
+
+  /*
+   * @return The current lower-dimensional element volume
+   */
+  const Real & lowerDElemVolume() const { return _current_lower_d_elem_volume; }
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/base/Assembly.h:407]: This is for mortar calculations. The lower dimensional elements have to be explicitly added by the user during mesh generation.

File: framework/include/base/Assembly.h [hunk 10]
```diff
@@ -834,11 +861,11 @@ class Assembly
                                 const std::vector<dof_id_type> & jdof_indices);
 
   /**
-   * Add LowerLower, LowerSecondary (LowerElement), LowerPrimary (LowerNeighbor), SecondaryLower
-   * (ElementLower), and PrimaryLower (NeighborLower) portions of the Jacobian for compute objects
-   * like MortarConstraints
+   * Add *all* portions of the Jacobian, e.g. LowerLower, LowerSecondary, LowerPrimary,
+   * SecondaryLower, SecondarySecondary, SecondaryPrimary, PrimaryLower, PrimarySecondary,
+   * PrimaryPrimary for mortar-like objects
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/base/Assembly.h:866]: Correct, this is for mortar generally. We came up with primary-secondary terminology as a replacement for master-slave. I'll see about adding a bit more to this doxygen comment

File: framework/include/constraints/AutomaticMortarGeneration.h [hunk 11]
```diff
@@ -267,4 +265,7 @@ class AutomaticMortarGeneration : public ConsoleStreamInterface
 
   /// Whether this object will be generating a mortar segment mesh for periodic constraints
   const bool _periodic;
+
+  /// Whether the mortar segment mesh is distributed
+  const bool _distributed;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/constraints/AutomaticMortarGeneration.h:270]: I do.
```c++
AutomaticMortarGeneration::AutomaticMortarGeneration(
    MooseApp & app,
    MeshBase & mesh_in,
    const std::pair<BoundaryID, BoundaryID> & boundary_key,
    const std::pair<SubdomainID, SubdomainID> & subdomain_key,
    bool on_displaced,
    bool periodic)
  : ConsoleStreamInterface(app),
    mesh(mesh_in),
    h_max(0.),
    _debug(false),
    _on_displaced(on_displaced),
    _periodic(periodic),
    _distributed(!mesh.is_replicated())
{
```

File: framework/include/constraints/MortarConstraintBase.h [hunk 12]
```diff
@@ -152,20 +151,16 @@ class MortarConstraintBase : public Constraint,
...
-  using ADMortarConstraint::_grad_test_primary;                                                    \
-  using ADMortarConstraint::_normals;                                                              \
-  using ADMortarConstraint::_tangents;                                                             \
-  using ADMortarConstraint::_secondary_var;                                                        \
-  using ADMortarConstraint::_primary_var
+  /// The secondary face lower dimensional element (not the mortar element!)
+  Elem const * const & _lower_secondary_elem;
+
+  /// The primary face lower dimensional element
+  Elem const * const & _lower_primary_elem;
```
[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/constraints/MortarConstraintBase.h:159]: It is not the mortar segment element. There are the lower-dimensional secondary and primary elements that correspond to faces of higher dimensional elements on the mortar boundary. The  mortar segment elements are formed starting with the lower-dimensional secondary element, and the projecting nodes from the lower-dimensional primary element and splitting those elements where the nodes project

[the remark this answers is not in the document]
Comment (lindsayad) [reply framework/include/constraints/MortarConstraintBase.h:159]: I will add more doxygen for this

File: framework/src/actions/AddRelationshipManager.C (hunk 1 above)
Comment (lindsayad) [reply framework/src/actions/AddRelationshipManager.C:19]: If you have mesh generators then RMs are "attached" to the `MeshBase`  object(s) at the same time that they are added, so no difference. When we do not have mesh generators, then attaching happens during a different phase than adding. During adding, we store the RMs in a container on `MooseApp`, and then during attaching we actually attach them to the mesh or dof-map. I *think* this was done because sometimes you cannot attach geometric relationship managers early in the simulation...like a geometric rm associated with periodic boundaries or something

File: framework/src/base/Assembly.C (hunk 2 above)
Comment (lindsayad) [reply framework/src/base/Assembly.C:2697]: I think I had a good reason at the time, but I've forgotten it now :cry:

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 3 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C:65]: That's why I'm doing...right?

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 4 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C:145]: I have this comment ten lines earlier:
```
  // Create an offset by the maximum number of mortar segment elements that can be created *plus*
  // the number of lower-dimensional secondary subdomain elements. Recall that the number of mortar
  // segments created is a function of node projection, *and* that if we split elems we will delete
  // that elem which has already taken a unique id
```

File: framework/src/constraints/AutomaticMortarGeneration.C (hunk 5 above)
Comment (lindsayad) [reply framework/src/constraints/AutomaticMortarGeneration.C:173]: Yea we do not do mortar with 3D (e.g. 2D mortar segment mesh elements) yet

File: framework/src/relationshipmanagers/AugmentSparsityOnInterface.C (hunk 6 above)
Comment (lindsayad) [reply framework/src/relationshipmanagers/AugmentSparsityOnInterface.C:166]: It helps me keep track of what I'm doing and I grow more and more paranoid over the years :smile:

File: test/tests/bcs/dmg_periodic/tests (hunk 7 above)
Comment (lindsayad) [reply test/tests/bcs/dmg_periodic/tests:15]: I don't think so but maybe I didn't change it back to `Exodiff` because it seems like the purpose of this test (based on the requirement) is just to make sure that the boundaries are actually distributed? And there are a lot of other `Exodiff` tests in this directory

File: test/tests/mesh/periodic_node_map/tests (hunk 8 above)
Comment (lindsayad) [reply test/tests/mesh/periodic_node_map/tests:11]: These tests use a custom object that expects there to be a certain number of entries in their periodic node map. We no longer ghost all boundaries just for grins, so we no longer have all the boundary nodes when we are running distributed

File: framework/src/base/Assembly.C (hunk 2 above)
Comment (lindsayad) [reply framework/src/base/Assembly.C:2697]: Ah it's because you can retrieve Jacobian blocks from this method that are totally unrelated to the lower-dimensional element degrees of freedom, e.g you can retrieve `Moose::PrimaryPrimary, Moose::PrimarySecondary` etc. So I thought that `jacobianBlockLower` was a bad name

**Comment by lindsayad** [comment]
@fdkong I added a little bit more doxygen. I suppose we can ask @aeslaughter , @loganharbour , or @rwcarlsen for an additional review?

File: test/tests/bcs/dmg_periodic/tests (hunk 7 above)
Comment (fdkong) [reply test/tests/bcs/dmg_periodic/tests:15]: Yes

File: test/tests/mesh/periodic_node_map/tests (hunk 8 above)
Comment (fdkong) [reply test/tests/mesh/periodic_node_map/tests:11]: Nice!

**Review by fdkong — APPROVED** [review]

**Comment by lindsayad** [comment]
If we don't get another review, I'll merge this at the end of Monday.

**Comment by lindsayad** [comment]
Ruh roh, looks like periodic distributed recover without all ghosted boundaries has some problems https://civet.inl.gov/job/603572/

**Comment by lindsayad** [comment]
@roystgnr I should know this but does checkpoint write out ghost elements? I would assume so

**Comment by fdkong** [comment]
> @roystgnr I should know this but does checkpoint write out ghost elements? I would assume so. Yea I see some `query_ghosting_functors` in Checkpoint IO.

Data is "distributed" in the file. When we read it back, we may not connect the whole story together.  So we need communicate data around ... to figure out the whole  story

**Comment by roystgnr** [comment]
> I should know this but does checkpoint write out ghost elements? I would assume so. Yea I see some query_ghosting_functors in Checkpoint IO.

It does, but I'm afraid there's a bit of a trick to it: we write out ghost elements but *not* ghosting functors, much less the data that particular functors depend on.  I guess we could make that possible, albeit at great difficulty, if we added a factory pattern and also required a serialize routine in the base class to be overridden?  But at the moment the way it works is we expect you to have the same ghosting requirements set up for the read() that you did for the write() ... so if you haven't yet set up all your periodic BCs, for example, then we'll happily read the periodic ghosted elements, discover you haven't said they're still necessary, and discard them.

In the future, this could be one of the use cases of that post-prepare_for_use idiom we're brainstorming.  A CheckpointIO::read() would leave need_remote_elem_removal() (or whatever we call the status accessor for that particular substep) set to false, so subsequent preparation work would skip remote element deletion and you'd have more time to get your ghosting functors and PBCs and algebraic coupling functors (this bit @arovinelli just last week!) and everything into place first.  But unlike allow_remote_element_removal(false), the new setting wouldn't be *permanent*, so if you do AMR or load balancing or reduce ghosting extent or anything like that later in the simulation, those operations would naturally set need_remote_elem_removal(true) and you wouldn't have to worry about whether you might still have no-longer-necessary ghosted elements floating about afterward.  But the whole process would be more robust to different user idioms: instead of having to get your ghosting functors set up before the restart's first prepare_for_use() you'd merely have to get them set up before they're first truly needed.
