### PR TITLE
Fix issues with CompositionDT use the overridden member functions

### LINKED ISSUE #24476: IterationAdaptiveDT doesn't work correctly when composing time step
## Bug Description

CompositionDT doesn't use the overridden member functions in derived time stepper classes. This causes issues when IterationAdaptiveDT/functionDT(maybe more) is used to compose the final time step. 

## Steps to Reproduce

An input example as below. The solver will always use the min_dt(1e-12).
```
  [TimeSteppers]
    [dt_adapt]
      type = IterationAdaptiveDT
      dt = 1
      # optimal_iterations = 10
    []
    [dt_func_dt]
      type = FunctionDT
      function = dt_func
      # min_dt = 0.1
    []
  []
```
## Impact

Allow users use all available time steppers in `[TimeSteppers]`

### PR DESCRIPTION
**Pull request by MengnanLi91**
close #24476

### CODE REVIEW

File: framework/src/timesteppers/CompositionDT.C [hunk 1]
```diff
@@ -60,6 +64,79 @@ CompositionDT::CompositionDT(const InputParameters & parameters)
...
 }
 
+void
+CompositionDT::init()
+{
+  const auto time_steppers = getTimeSteppers();
+  for (auto & ts : time_steppers)
+    if (ts != this)
+      ts->init();
+}
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:74]: Make a private templated method:

```
template <typename Lambda>
void CompositionDT::actOnTimeSteppers(Lambda & act)
{
  for (auto & ts : getTimeSteppers())
    if (ts != this)
      act(*ts);
}
```

You can then replace all of these calls with something like:

```
void
CompositionDT::preExecute()
{
  actOnTimeSteppers([](auto & ts) { ts.preExecute(); });
}
```

File: framework/include/timesteppers/CompositionDT.h [hunk 2]
```diff
@@ -57,7 +107,7 @@ class CompositionDT : public TimeStepper
   /**
    * Internal method for querying TheWarehouse for the currently active timesteppers.
    */
-  std::vector<TimeStepper *> getTimeSteppers();
+  std::vector<TimeStepper *> getTimeSteppers() const;
```
Comment (loganharbour) [inline framework/include/timesteppers/CompositionDT.h:110]: You should very rarely make a const method that returns non const objects.

Where are you calling this that requires it to be const? If you really need this, you should have:

```
std::vector<TimeStepper *> getTimeSteppers();
std::vector<const TimeStepper *> getTimeSteppers() const;
```

File: framework/src/timesteppers/CompositionDT.C [hunk 3]
```diff
@@ -114,38 +199,53 @@ CompositionDT::getSequenceSteppersNextTime()
...
+    return std::min((ts - _time), dt);
+  }
   else
-    return std::max(minDT, lower_bound);
+    return dt;
 }
 
 std::vector<TimeStepper *>
-CompositionDT::getTimeSteppers()
+CompositionDT::getTimeSteppers() const
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:248]: We should filter out this timestepper here, in order to remove that logic everywhere else

File: framework/src/timesteppers/CompositionDT.C [hunk 4]
```diff
@@ -87,10 +163,19 @@ CompositionDT::computeDT()
     {
       ts->computeStep();
       const auto dt = ts->getCurrentDT();
+
       if (_lower_bound.count(ts->name()))
+      {
         bound_dt.emplace(dt);
+        if (bound_dt.find(dt) == (--bound_dt.end()))
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:170]: I'm not a big fan of running find on floating point values

File: framework/src/timesteppers/CompositionDT.C [hunk 5]
```diff
@@ -154,3 +254,56 @@ CompositionDT::getTimeSteppers()
...
   return time_steppers;
 }
+
+void
+CompositionDT::step()
+{
+  if (_last_time_stepper)
+    _last_time_stepper->step();
+  else
+    TimeStepper::step();
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:264]: Talk me through this logic when you get in

**Review by loganharbour — CHANGES_REQUESTED** [review]

File: framework/src/timesteppers/CompositionDT.C [hunk 6]
```diff
@@ -154,3 +254,56 @@ CompositionDT::getTimeSteppers()
...
+    if (ts != this)
+      ts->rejectStep();
+}
+
+bool
+CompositionDT::converged() const
+{
+  if (_last_time_stepper)
+    return _last_time_stepper->converged();
+  return TimeStepper::converged();
```
[the remark this answers is not in the document]
Comment (MengnanLi91) [reply framework/src/timesteppers/CompositionDT.C]: Can I mark this as resolved?

File: test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+    [AB2]
+      type = AB2PredictorCorrector
+      dt = .01
+      e_max = 10
+      e_tol = 1
+    []
+    [IterationAdapDT]
+      type = IterationAdaptiveDT
+      dt = 0.5
+    []
```
Comment (GiudGiud) [inline test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i:78]: I would replace that one with a big big time step. Then it should not intervene in the simulation

and you can use the gold file for the AB2PredictorCorrector regular test

File: framework/src/timesteppers/CompositionDT.C [hunk 8]
```diff
@@ -60,40 +64,100 @@ CompositionDT::CompositionDT(const InputParameters & parameters)
...
+}
+
+bool
+CompositionDT::constrainStep(Real & dt)
+{
+  bool at_sync_point = TimeStepper::constrainStep(dt);
+  const auto time_steppers = getTimeSteppers();
+  for (auto & ts : time_steppers)
+    if (!ts->constrainStep(dt))
+      return false;
```
Comment (GiudGiud) [inline framework/src/timesteppers/CompositionDT.C:124]: so if all time steppers do not constrain, then we dont.

shouldnt it be "if any TS constrains, we constrain" ?

File: test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i (hunk 7 above)
Comment (MengnanLi91) [reply test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i:78]: I need to have two time steppers to trigger the use of CompositionDT. It won't construct a CompositionDT if only one time stepper is found in [TimeSteppers] block

File: test/tests/time_steppers/time_stepper_system/timesequence.csv
[the remark this answers is not in the document]
Comment (MengnanLi91) [reply test/tests/time_steppers/time_stepper_system/timesequence.csv:1]: This is the input for CSVTimesequenceStepper

File: test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i (hunk 7 above)
Comment (MengnanLi91) [reply test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i:78]: AB2PredictorCorrector regular test use exodus file instead of csv.  I'll check the time step size to make sure they are the same, but keep the gold file for this case as csv to be consistent with other tests.

Comment (GiudGiud) [reply test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i:78]: It s better to be consistent with the old test, prove that we have the same behavior

the storage cost of a symlink is even lower than a CSV

Comment (MengnanLi91) [reply test/tests/time_steppers/time_stepper_system/AB2PredictorCorrector.i:78]: Okay, will do that instead.

File: framework/include/timesteppers/CompositionDT.h [hunk 9]
```diff
@@ -70,4 +120,13 @@ class CompositionDT : public TimeStepper
 
   // The time stepper(s) input as lower bound of the time stepper size
   const std::set<std::string> _lower_bound;
+
+  // The time stepper selected to use based on minimum time step size
+  TimeStepper * _last_time_stepper;
+
+  // The time stepper selected as the lower bound
+  TimeStepper * _bound_last_time_stepper;
```
Comment (GiudGiud) [inline framework/include/timesteppers/CompositionDT.h:128]: _largest_bound_time_stepper ?

File: framework/include/timesteppers/CompositionDT.h [hunk 10]
```diff
@@ -70,4 +120,13 @@ class CompositionDT : public TimeStepper
...
+
+  // The time stepper selected as the time sequence stepper
+  TimeSequenceStepperBase * _last_time_sequence_stepper;
```
Comment (GiudGiud) [inline framework/include/timesteppers/CompositionDT.h:131]: same it s not really the last, more like the first

_closest_time_sequence_stepper?

**Review by GiudGiud — CHANGES_REQUESTED** [review]

**Review by GiudGiud — DISMISSED** [review]

**Comment by GiudGiud** [comment]
@loganharbour

File: framework/include/timesteppers/CompositionDT.h [hunk 11]
```diff
@@ -38,17 +38,66 @@ class CompositionDT : public TimeStepper
...
    */
-  Real produceCompositionDT(const std::set<Real> & dts, const std::set<Real> & bound_dts);
+  Real produceCompositionDT(std::set<std::pair<Real, TimeStepper *>, CompareFirst> & dts,
+                            std::set<std::pair<Real, TimeStepper *>, CompareFirst> & bound_dts);
 
   // Find the time point to hit at current time step
   Real getSequenceSteppersNextTime();
 
+  template <typename Lambda>
+  void actOnTimeSteppers(Lambda && act);
```
Comment (loganharbour) [inline framework/include/timesteppers/CompositionDT.h:62]: Make this private

File: framework/include/timesteppers/CompositionDT.h [hunk 12]
```diff
@@ -38,17 +38,66 @@ class CompositionDT : public TimeStepper
...
+
+  /**
+   * Initialize all the input time stepper(s). Called at the very beginning of
+   * Executioner::execute()
+   */
+  virtual void init() override;
```
Comment (loganharbour) [inline framework/include/timesteppers/CompositionDT.h:68]: Everything that follows should be override final to denote that nothing should override these later

File: framework/src/timesteppers/CompositionDT.C [hunk 13]
```diff
@@ -60,40 +64,100 @@ CompositionDT::CompositionDT(const InputParameters & parameters)
...
-
   // Note : compositionDT requires other active time steppers as input so no active time steppers
   // or only compositionDT is active is not allowed
-  if (time_steppers.size() < 2 && time_steppers[0] == this)
+  if (time_steppers.size() < 1)
     mooseError("No TimeStepper(s) are currently active to compute a timestep");
 
-  std::set<Real> dts;
-  std::set<Real> bound_dt;
+  std::set<std::pair<Real, TimeStepper *>, CompareFirst> dts, bound_dt;
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:143]: Can you add a comment as to why we have the custom comparator, and what these are used for

File: framework/src/timesteppers/CompositionDT.C [hunk 14]
```diff
@@ -152,5 +232,35 @@ CompositionDT::getTimeSteppers()
       .query()
       .condition<AttribSystem>("TimeStepper")
       .queryInto(time_steppers);
+
+  time_steppers.erase(std::remove(time_steppers.begin(), time_steppers.end(), this),
```
Comment (loganharbour) [inline framework/src/timesteppers/CompositionDT.C:236]: Add comment about removing this one

**Review by loganharbour — CHANGES_REQUESTED** [review]
Minor changes

**Review by GiudGiud — APPROVED** [review]

**Review by loganharbour — APPROVED** [review]
