### PR TITLE
Patch for MultiAppVectorPostprocessorTransfer for distributed subapps.

### LINKED ISSUE #27047: `MultiAppVectorPostprocessorTransfer` incorrect results when procs per app > 1
### Bug Description

When the number of sub apps per proc > 1 the `MultiAppVectorPostprocessorTransfer` will give results that are N * correct result where N is the number of procs that the sub app uses.

### Steps to Reproduce

Replace `max_procs_per_app = 1 ` with `min_procs_per_app = 2` and run in parallel. The results will be different.
``` 
[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 1
  ymax = 2
[]

[Problem]
  kernel_coverage_check = false
[]

[Variables]
  [./u]
  [../]
[]

[AuxVariables]
  [./v]
    [./InitialCondition]
      type = FunctionIC
      function = set_v
    [../]
  [../]
[]

[Functions]
  [./set_v]
    type = ParsedFunction
    expression = 'x + 2 * y'
  [../]
[]

[VectorPostprocessors]
  [./sample_points]
    type = PointValueSampler
    variable = v
    points = '0.25 1.25 0 0.5 1.5 0'
    sort_by = x
    execute_on = 'initial timestep_end'
  [../]

  [./receive_values]
    type = PointValueSampler
    variable = v
    points = '0.25 1.25 0 0.5 1.5 0'
    sort_by = x
    execute_on = initial
  [../]
[]

[MultiApps]
  [./sub]
    type = TransientMultiApp
    input_files = 'sub.i'
    positions = '0.25 1.25 0 0.5 1.5 0'
    max_procs_per_app = 1 # changing this to anything but 1 would cause problems in parallel.
  [../]
[]

[Transfers]
  [./send]
    type = MultiAppVectorPostprocessorTransfer
    vector_postprocessor = sample_points
    postprocessor = receive
    vector_name = v
    to_multi_app = sub
  [../]

  [./receive]
    type = MultiAppVectorPostprocessorTransfer
    vector_postprocessor = receive_values
    postprocessor = send
    vector_name = v
    from_multi_app = sub
  [../]
[]

[Executioner]
  type = Transient
  nl_abs_tol = 1e-10
  num_steps = 1
[]

[Outputs]
  csv = true
[]
```

### Impact

Incorrect results with no errors. 

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pbehne**
This PR patches the bug reported in #27047, where the MultiAppVectorPostprocessorTransfer gives incorrect results when pp values are transfered from subapps distributed over more than 1 proc to the parent app. The transfer is executed by defining on each proc a vector of zeros with length equal to the number of subapps. The intention is that each subapp will put its pp value into the corresponding entry of this vector, leaving the other entries as zero. In order to fill the remaining zeros on each proc with the pp values from subapps not on the given proc, the vector values are summed element-wise accross all processors. The old implementation of this approach uses hasLocalApp(i) to check if subapp i belongs to the current processor. If so, the corresponding vector value is changed from 0 to the pp value. When a subapp is distributed accross more than one processor, this approach does not work because hasLocalApp(i) returns true on multiple processors, thus the vector that holds pp values gets the value for the distributed subapp on all processors that it lives on. These values are added together, resulting in an overall incorrect pp value transfered to the vpp. The solution to this issue is, in addition to checking hasLocalApp(i) to see if subapp i lives on the current processors, also check isFirstLocalRank() to determine if the current processor is the first proc that subapp i is distributed on. This avoids the erroneous duplication and summation of the same subapp's pp value.

Additionally, the test for the MultiAppVectorPostprocessorTransfer was updated to distribute each subapp over at least 2 processors so issues like these are not overlooked in the future.

Closes #27047.

### CODE REVIEW

File: framework/src/transfers/MultiAppVectorPostprocessorTransfer.C [hunk 1]
```diff
@@ -88,8 +88,13 @@ MultiAppVectorPostprocessorTransfer::executeFromMultiapp()
...
-    if (getFromMultiApp()->hasLocalApp(i))
+  {
+    // To avoid duplication and thus a wrong pp value after summing value accross procs, we should
+    // ensure that value[i] is only set by one procs. To do this, we check isFirstLocalRank to see
+    // if the current proc is the first rank that subapp i lives on.
+    if (getFromMultiApp()->hasLocalApp(i) && getFromMultiApp()->isFirstLocalRank())
       value[i] = getFromMultiApp()->appProblemBase(i).getPostprocessorValueByName(_sub_pp_name);
+  }
 
   for (auto & v : value)
```
Comment (GiudGiud) [inline framework/src/transfers/MultiAppVectorPostprocessorTransfer.C:99]: add a comment

I think we are summing here to distribute the value?

File: test/tests/transfers/multiapp_vector_pp_transfer/parent.i [hunk 2]
```diff
@@ -55,7 +55,7 @@
     type = TransientMultiApp
     input_files = 'sub.i'
     positions = '0.25 1.25 0 0.5 1.5 0'
-    max_procs_per_app = 1
+    min_procs_per_app = 2
```
Comment (GiudGiud) [inline test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: shouldnt it work with 1? You could just delete the line

**Review by GiudGiud — CHANGES_REQUESTED** [review]
very nice work

File: test/tests/transfers/multiapp_vector_pp_transfer/parent.i (hunk 2 above)
Comment (pbehne) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: The purpose of forcefully requiring the sub app to be distributed over 2 procs is to make sure the bug this PR fixes doesn't show up again. Do you think I should leave it at 1 proc and add a new test? Or just not test for this?

Comment (GiudGiud) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: if you dont specify anything, the sweep tests will check this from 1 to 16 processors naturally

Comment (GiudGiud) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: achieving what you want and keeping testing for 1 proc

Comment (pbehne) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: If that's the case, how come this bug wasn't caught earlier due to a test failure?

Comment (GiudGiud) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: because of this line
```
max_procs_per_app = 1
```
which I suggest you remove and do not replace

Comment (pbehne) [reply test/tests/transfers/multiapp_vector_pp_transfer/parent.i:58]: Thanks for the explanation!

**Review by GiudGiud — APPROVED** [review]

**Comment by pbehne** [comment]
@lindsayad NEAMS MP project
