### PR TITLE
make declareProperty[Old/Older] optional and other material property housekeeping

### LINKED ISSUE #8031: getMaterialPropertyOld() does not fail if the requested material property isn't stateful
### Description of the enhancement or error report
If I call `getMaterialPropertyOld()` to get a material for which `declarePropertyOld()` hasn't been declared, it doesn't fail.

### Rationale for the enhancement or information for reproducing the error
If the test in modules/tensor_mechanics/tests/plane_stress/weak_plane_strain_incremental.i is modified so use the ComputePlaneSmallStrain model instead of the ComputePlaneIncrementalStrain model, it runs to completion.  It should error out because `mechanical_strain` does not have its old property declared in the ComputePlaneSmallStrain model.

### Identified impact
TensorMechanics has a mix of incremental and total strain models. Some of them declare the old properties and some don't.  The whole system is very error-prone because of this issue. If a user neglects to use the option that makes a property stateful, and then tries to use a model that uses property, no error is generated and models run with undefined data.

### PR DESCRIPTION
**Pull request by rwcarlsen**
This makes ``getMaterialProperty[Old/Older]`` implicitly cause a property to become stateful.  Other tweaks include:

* improve doc comments in MaterialData and other material classes
* have MaterialData::size function do its own check for change in n_qpoints - eliminating need for paired checks in several places.
* Eliminate redundancy in MaterialData::[get/declare]Property functions.
* Eliminate redundancy in MaterialPropertyStorage functions w.r.t. initializing hashmaps.
* remove always false error checking for retrieving non-existing material types.

fixes #8031, #7867, #7881, #7625

Because of ``initStatefulQpProperties``, I haven't been able to come up with a satisfactory way to deprecate ``declareProperty[Old/Older]``.  If a material doesn't retrieve the (writable) references using the declare functions (get functions return const refs), then it can't initialize the values in initStatefulQpProperties.  I looked into creating a new ``Material::initQpStatefulProperty(std::string& prop_name, T& old, T& older)`` function called by MaterialData whenever a property *becomes* stateful via a getMaterialProperty[Old/Older] call, but this doesn't work because the property initialization that happens later in MaterialPropertyStorage would clobber that.  And calling such a templated function would not work from MaterialPropertyStorage because it doesn't know the templated types of each property.  There may be a good solution lurking, but I haven't found it yet.

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hi @rwcarlsen ,

I've been mucking around with Material stuff lately, and vaguely feel that some things aren't working properly.  I haven't any definitive examples, but since Materials are at the forefront of your mind, I wonder whether you could please think briefly about the following scenarios.

 - DiracKernels requesting Material properties, especially in the case when there are many Dirac points inside a single element.

 - Kernels/DiracKernels/BCs/Materials requesting Properties, but via a pointer, eg:
_mat_prop(some_condition ? &getMaterialProperty<T>("name") : nullptr).  Including the case when these are stateful (DiracKernels don't fully work for stateful Properties, but should be able to obtain the current (not old) value of the stateful Property).

 - porous_flow/src/materials/PorousFlowMaterial.C resizing Properties to the number of nodes in an element, during initStatefulProperties, and computeProperties, and this having effects on Kernels/DiracKernels/BCs/Materials.

File: framework/include/materials/MaterialData.h [hunk 1]
```diff
@@ -155,8 +158,13 @@ class MaterialData
...
 
   /**
-   * Resizes the properties to the specified size
-   * @param size The size of the properties to set
+   * Resizes the number of properties to the specified size (including
+   * stateful old and older properties.
+   *
+   * Warning:
+   * If size is greater than the current size, the new properties are set
+   * to NULL except * for the last element - which is set to a blank material
```
Comment (friedmud) [inline framework/include/materials/MaterialData.h]: Can you explain this a little bit more?  It doesn't make sense to me.  The new properties shouldn't be `NULL`... they aren't even pointers.  And the behavior with the "last element" doesn't make sense to me.

File: framework/include/materials/MaterialPropertyStorage.h [hunk 2]
```diff
@@ -119,8 +119,12 @@ class MaterialPropertyStorage
   void shift();
 
   /**
-   * Copy material properties from elem_from to elem_to
-   * Thread safe
+   * Copy material properties from elem_from to elem_to. Thread safe.
+   *
+   * WARNING: This is not capable of copying material data to/from elements on other processors.
+   *          It only works if both elem_to and elem_from are both on the local processor.
+   *          We can't currently check to ensure that they're on processor here because this isn't a ParallelObject.
```
Comment (friedmud) [inline framework/include/materials/MaterialPropertyStorage.h]: This also isn't the right interface for copying to other processors... that interface would need lists of element pairs and properties so that efficient buffers could be built and communicated at once.

This is really a pretty specialized function that's only really used for XFEM.  I kind of don't even like that it's here... :-)

None of that has anything to do with this PR.  You were just moving this comment from the `.C` which is fine... it's good to have it here.

File: framework/include/materials/MaterialData.h [hunk 3]
```diff
@@ -42,53 +42,56 @@ class MaterialData
   void release();
 
   /**
-   * Size the properties
+   * Resize the data to hold properties for n_qpoints quadrature points.
    */
   void size(unsigned int n_qpoints);
```
Comment (friedmud) [inline framework/include/materials/MaterialData.h]: I'd really like to rename this to `resize()`.  I know you didn't name it... but it's a good time to do it.

File: framework/src/materials/MaterialData.C [hunk 4]
```diff
@@ -38,6 +38,9 @@ MaterialData::release()
 void
 MaterialData::size(unsigned int n_qpoints)
 {
+  if (n_qpoints == _n_qpoints)
```
Comment (friedmud) [inline framework/src/materials/MaterialData.C]: This is good.

File: framework/src/base/ComputeMaterialsObjectThread.C [hunk 5]
```diff
@@ -94,8 +94,7 @@ ComputeMaterialsObjectThread::onElement(const Elem *elem)
     _fe_problem.reinitElem(elem, _tid);
 
     unsigned int n_points = _assembly[_tid]->qRule()->n_points();
-    if (_material_data[_tid]->nQPoints() != n_points)
```
Comment (friedmud) [inline framework/src/base/ComputeMaterialsObjectThread.C]: Doing this check internally is better: good spot.

File: framework/include/materials/Material.h [hunk 6]
```diff
@@ -320,23 +321,22 @@ template<typename T>
 const MaterialProperty<T> &
 Material::getMaterialPropertyOldByName(const std::string & prop_name)
 {
-  _requested_props.insert(prop_name);
+  //_requested_props.insert(prop_name);
```
Comment (friedmud) [inline framework/include/materials/Material.h]: Why disable this stuff?

File: framework/include/materials/MaterialData.h [hunk 7]
```diff
@@ -270,47 +278,25 @@ MaterialData::declarePropertyOlder(const std::string & prop_name)
...
 MaterialData::getProperty(const std::string & name)
 {
-  unsigned int prop_id = _storage.getPropertyId(name);
-  resizeProps<T>(prop_id);
-
-  MaterialProperty<T> * prop = dynamic_cast<MaterialProperty<T> *>(_props[prop_id]);
-  if (prop != NULL)
-    return *prop;
-  else
-    mooseError("Material has no property named: " + name);
```
Comment (friedmud) [inline framework/include/materials/MaterialData.h]: So - how does error checking work now?

**Review by friedmud — CHANGES_REQUESTED** [review]
Overall this is good.  I'm mainly asking for clarification about error checking.  I want to make sure that we can still detect when properties that don't exist are requested.

File: framework/include/materials/Material.h (hunk 6 above)
Comment (rwcarlsen) [inline framework/include/materials/Material.h]: Oops - forgot to uncomment after debugging.

File: framework/include/materials/MaterialData.h (hunk 7 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialData.h]: I am still looking into/thinking about error checking.  If you look at the rest of the logic in MaterialData.h - this if clause was always true (i.e. this error was never thrown).

File: framework/include/materials/MaterialData.h (hunk 1 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialData.h]: The issue is with the ``MaterialData::resizeProps`` function.  ``_props`` member and friends are basically vectors of ``PropertyValue*``  and the resize function calls resize on the vector, (inserting NULLs to any new elements), and then proceeds to reset/fix the last element only as a blank material property value using new.

File: framework/include/materials/MaterialData.h (hunk 3 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialData.h]: Yeah - I noticed that too.  Done.

File: framework/include/materials/MaterialData.h (hunk 1 above)
Comment (friedmud) [inline framework/include/materials/MaterialData.h]: Can you point me to where it does this?  That behavior doesn't make any sense!  If it does that... then we should create an Issue to fix it!

Comment (rwcarlsen) [inline framework/include/materials/MaterialData.h]: I've fixed in in updates to the PR.  Relevant section is here: https://github.com/idaholab/moose/pull/8278/files#diff-a7d1c85c03658594a218c1dc277310efL217

**Comment by WilkAndy** [comment]
Hi @rwcarlsen ,

Here's another thing related to Materials.  I can't use mesh adaptivity in PorousFlow, as explained in #7625.  This is due to a stateful material non-initialization problem.  If you'd like to explore the problem then an example input file is:

porous_flow/tests/heat_advection/heat_advection_1d.i

remove the active = '' line in that file and you'll get a nice seg fault.

**Comment by rwcarlsen** [comment]
@WilkAndy - I've been seeing some similar issues while working on this PR - I wouldn't be surprised if, when this is finished, it fixes #7625 as well.

**Comment by WilkAndy** [comment]
Oh wow, it'd be great if #7625 was fixed by this PR, thanks @rwcarlsen ,

a

**Comment by rwcarlsen** [comment]
This does indeed seem to fix #7625.  And consequentlly #4602 also (they actually seem to be the same issue).

**Comment by WilkAndy** [comment]
Oh wow, thank you @rwcarlsen .   very good news!

**Comment by rwcarlsen** [comment]
This should be ready for another look.  There are 3 failed bison tests (exodiff), but I'm pretty sure those are due to uses of stateful properties that were never declared stateful - so hopefully the exodiffs are actually showing improved results on those bison tests that were previously relying on undefined moose behavior. @sapitts verbally volunteered to take a look maybe?

**Comment by sapitts** [comment]
@rwcarlsen I'm looking at the three failing tests, and none use the same combination of strain calculator and eigenstrain material; however, I suspect that the _eigenstrain_old is the unset material property.  Would you help me figure out if this is the case?

Still not volunteering to redo the analytical calculations though!

**Comment by rwcarlsen** [comment]
On vanilla devel moose+bison, the following moose tensor mechanics patch causes the same bison failures (i.e. demonstrates that if this PR actually breaks bison, then so does a supposedly benign one that shouldn't break bison):

```diff
diff --git a/modules/tensor_mechanics/src/materials/ComputeIncrementalStrainBase.C b/modules/tensor_mechanics/src/materials/ComputeIncrementalStrainBase.C
index c59dc7c..4cb3083 100644
--- a/modules/tensor_mechanics/src/materials/ComputeIncrementalStrainBase.C
+++ b/modules/tensor_mechanics/src/materials/ComputeIncrementalStrainBase.C
@@ -33,6 +33,19 @@ ComputeIncrementalStrainBase::ComputeIncrementalStrainBase(const InputParameters
   for (unsigned int i = 0; i < _eigenstrains_old.size(); ++i)
     _eigenstrains_old[i] = &getMaterialPropertyOld<RankTwoTensor>(_eigenstrain_names[i]);

+    declarePropertyOld<RankTwoTensor>(_base_name + "strain_rate");
+    declarePropertyOld<RankTwoTensor>(_base_name + "strain_increment");
+    declarePropertyOld<RankTwoTensor>(_base_name + "deformation_gradient");
+    declarePropertyOld<RankTwoTensor>(_base_name + "rotation_increment");
+    declarePropertyOld<RankTwoTensor>(_base_name + "mechanical_strain");
+    declarePropertyOld<RankTwoTensor>(_base_name + "total_strain");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "strain_rate");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "strain_increment");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "deformation_gradient");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "rotation_increment");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "mechanical_strain");
+    declarePropertyOlder<RankTwoTensor>(_base_name + "total_strain");
+
   // fetch coupled variables and gradients (as stateful properties if necessary)
   for (unsigned int i = 0; i < _ndisp; ++i)
```

which causes bison oneD densification only test to fail with this exodiff:

```
oneD.densification_only:   --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:   --------- Time step 2, 1.0000000e-01 ~ 1.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:   --------- Time step 3, 2.0000000e-01 ~ 2.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -4.3168445e-04 ~ -4.3173099e-04 = 1.07806e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -1.2944944e-03 ~ -1.2946339e-03 = 1.07759e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 4, 3.0000000e-01 ~ 3.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -6.2621741e-04 ~ -6.2634798e-04 = 2.08455e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -1.8774760e-03 ~ -1.8778672e-03 = 2.08324e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 5, 4.0000000e-01 ~ 4.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -8.0779141e-04 ~ -8.0803577e-04 = 3.02419e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -2.4214172e-03 ~ -2.4221491e-03 = 3.02174e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 6, 5.0000000e-01 ~ 5.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -9.7726547e-04 ~ -9.7764688e-04 = 3.90138e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -2.9289322e-03 ~ -2.9300742e-03 = 3.89756e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 7, 6.0000000e-01 ~ 6.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -1.1354422e-03 ~ -1.1359784e-03 = 4.72024e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -3.4024604e-03 ~ -3.4040654e-03 = 4.71488e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 8, 7.0000000e-01 ~ 7.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -1.2830715e-03 ~ -1.2837756e-03 = 5.48463e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -3.8442779e-03 ~ -3.8463848e-03 = 5.47759e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 9, 8.0000000e-01 ~ 8.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -1.4208539e-03 ~ -1.4217352e-03 = 6.19815e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -4.2565082e-03 ~ -4.2591444e-03 = 6.18934e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 10, 9.0000000e-01 ~ 9.0000000e-01, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -1.5494438e-03 ~ -1.5505081e-03 = 6.86416e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -4.6411327e-03 ~ -4.6443157e-03 = 6.85352e-04 (block 3001, elmt 1)
oneD.densification_only:   --------- Time step 11, 1.0000000e+00 ~ 1.0000000e+00, rel diff:  0.00000e+00 ---------
oneD.densification_only: Global variables:
oneD.densification_only:    scalar_strain_yy  rel diff: -1.6694522e-03 ~ -1.6707028e-03 = 7.48581e-04 (FAILED)
oneD.densification_only: Nodal variables:
oneD.densification_only: Element variables:
oneD.densification_only:    volumetric_strain  rel diff: -5.0000000e-03 ~ -5.0037394e-03 = 7.47331e-04 (block 3001, elmt 1)
oneD.densification_only:
oneD.densification_only: exodiff: Files are different
oneD.densification_only:
```

which is exactly the exodiff caused by this PR.

**Comment by sapitts** [comment]
Thanks @rwcarlsen.  One of those failing Bison tests maps with a soft link back to a solid mechanics test, so I will switch the strain calculator in a Bison patch tonight (tensor_mechanics/uo2_eigenstrain/uo2_vswelling.solid_test_small_strain.

The other two should be regold, as the solutions are incorrect.  The only analytical solution in the oneD is for the volume change, which doesn't exodiff, although @jasondhales may want to double check since this is his test.  The relocation test is mine; I'll take care of updating the analytical solution, since if my analytical calculations were correct in the first place we would have this problem now.  Thanks for catching these errors for us.

If there's a way that I can patch Bison (maybe by declaring the old strains in the eigenstrains directly as a stop gap measure?) so that you don't have to go through the pain of the submodule updates, I'd be happy to do so but will need some direction on the best method.

**Comment by rwcarlsen** [comment]
I just pushed up a rebased cleaned up sequence of commits - the last commit has the behavioral changes to MOOSE - everything else is comments, refactoring, etc.

**Comment by rwcarlsen** [comment]
@sapitts - I'm heading out for the day - we can talk tomorrow.

File: test/src/materials/ImplicitStateful.C [hunk 8]
```diff
@@ -0,0 +1,53 @@
...
+{
+}
+
+void
+ImplicitStateful::computeQpProperties()
+{
+  if (_fe_problem.timeStep() <= 1)
+    _prop[_qp] = 0;
+
+  if (_fe_problem.timeStep() > 0)
```
Comment (permcody) [inline test/src/materials/ImplicitStateful.C]: We should be able to access the old and older properties even for the first computation. Is that still the case? 
e.g. We always wanted users to be able to put in the compute statement without worrying about the timestep number.

File: test/src/materials/ImplicitStateful.C [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+#include "ImplicitStateful.h"
+
+template<>
+InputParameters validParams<ImplicitStateful>()
+{
+  InputParameters params = validParams<Material>();
+  params.addRequiredParam<std::string>("prop_name", "bla");
+  params.addRequiredParam<std::string>("coupled_prop_name", "bla");
+  params.addRequiredParam<bool>("add_time", "bla");
+  params.addRequiredParam<bool>("older", "bla");
```
Comment (permcody) [inline test/src/materials/ImplicitStateful.C]: Make sure you put in meaningful documentation comments here.

File: framework/src/materials/MaterialPropertyStorage.C [hunk 10]
```diff
@@ -380,47 +340,57 @@ MaterialPropertyStorage::addPropertyOld (const std::string & prop_name)
...
-    return id;
+    auto prop_id = _stateful_prop_id_to_prop_id[i];
+    // duplicate the stateful property in property storage (all three states - we will reuse the allocated memory there)
+    // also allocating the right amount of memory, so we do not have to resize, etc.
+    if (props(&elem, side)[i] == NULL)
+      props(&elem, side)[i] = material_data.props()[prop_id]->init(n_qpoints);
+    if (propsOld(&elem, side)[i] == NULL)
+      propsOld(&elem, side)[i] = material_data.propsOld()[prop_id]->init(n_qpoints);
+    if (hasOlderProperties() && propsOlder(&elem, side)[i] == NULL)
+      propsOlder(&elem, side)[i] = material_data.propsOlder()[prop_id]->init(n_qpoints);
```
Comment (permcody) [inline framework/src/materials/MaterialPropertyStorage.C]: `NULL` -> `nullptr`

File: framework/include/materials/MaterialData.h [hunk 11]
```diff
@@ -235,82 +204,57 @@ template<typename T>
...
 {
-  unsigned int prop_id = _storage.addPropertyOlder(prop_name);
-  resizeProps<T>(prop_id);
+  return declareProp<T>(_props_older, prop_name, _storage.addPropertyOlder(prop_name));
+}
 
-  MaterialProperty<T> *prop = dynamic_cast<MaterialProperty<T>*>(_props_older[prop_id]);
+template<typename T>
+MaterialProperty<T> &
+MaterialData::declareProp(MaterialProperties& props, const std::string & prop_name, unsigned int prop_id)
```
Comment (permcody) [inline framework/include/materials/MaterialData.h]: My two cents, I'm not sure I like seeing both `declareProp()` and `declareProperty()`. I know that the former is private but it's not clear which is which when you are looking through the code. I'd prefer something like `declarePropertyHelper`, or `declarePropertyInternal`

File: framework/include/materials/MaterialProperty.h [hunk 12]
```diff
@@ -45,28 +45,22 @@ PropertyValue *_init_helper(int size, PropertyValue *prop, const std::vector<P>*
 class PropertyValue
 {
 public:
-  /**
-   * Destructor.
-   */
-  virtual ~PropertyValue() {};
+  virtual ~PropertyValue() { };
```
Comment (permcody) [inline framework/include/materials/MaterialProperty.h]: I think I like the braces closed better :)

**Review by permcody — CHANGES_REQUESTED** [review]
This is looking pretty good!

I made several style comments which are easily fixable. What is the status with the issues with initQpStatefulProperties? Do we still have problems with defining how to initialize stateful properties? We may want feedback from developers who actually use stateful properties on this part of the design (@YaqiWang, @bwspenc, @dschwen)

File: test/src/materials/ImplicitStateful.C [hunk 13]
```diff
@@ -0,0 +1,53 @@
...
+  return params;
+}
+
+ImplicitStateful::ImplicitStateful(const InputParameters & pars) :
```
Comment (rwcarlsen) [inline test/src/materials/ImplicitStateful.C]: I thought we were favoring the newer get member function - especially since getParam doesn't necessarily return the same value.

Comment (permcody) [inline test/src/materials/ImplicitStateful.C]: Actually the get member function is older (pre-dates the getParam wrapper). The wrapper just called `_pars.get` which is a reference to the `InputParameters` object that's passed in. This is one of those "that ship has sailed" arguments. I always preferred using the local parameter objects better but I was overruled in a vote long ago so the wrapper is the preferred mechanism. Please use the wrapper here.

**Review by permcody — APPROVED** [review]

File: test/src/materials/ImplicitStateful.C (hunk 8 above)
Comment (rwcarlsen) [inline test/src/materials/ImplicitStateful.C]: Yes - I just fixed this - these checks are not necessary now.

File: framework/include/materials/MaterialProperty.h (hunk 12 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialProperty.h]: done

File: test/src/materials/ImplicitStateful.C (hunk 13 above)
Comment (rwcarlsen) [inline test/src/materials/ImplicitStateful.C]: done.

File: test/src/materials/ImplicitStateful.C (hunk 9 above)
Comment (rwcarlsen) [inline test/src/materials/ImplicitStateful.C]: done

**Comment by permcody** [comment]
@friedmud - do you have any further comments? 
Also, the rest of the guys I tagged (@YaqiWang, @bwspenc, @dschwen). We really should talk about the fate of `initQpStatefulProperties`. It's unclear exactly who is responsible for initializing stateful properties if it's not going to be done by the declaring Material. That's the one big thing holding this whole change from being merged.

**Comment by rwcarlsen** [comment]
Right now - it works exactly as before - except for implicitly stateful properties which are just zero initialized initially.  This PR just punts on creating a mechanism for stateful property users (that aren't the declarers) to initialize the stateful props.

**Comment by friedmud** [comment]
Hmmm... that IS problematic.

`initQpStateful` must still be done by the Material declaring the property.  Nothing else makes sense.

Let's brainstorm some ideas on this.  My current thought is that `initQpStateful` could have an argument for an identifier for the Property that needs initing. This would be similar to `computeQpOffDiagJacobian`.

Inside the function you would check to see which property it is and init it.

Other options are to register a callback when you declare a Property.  That callback would get used to init it in the case that it's stateful.

Anyone else got something?

Why didn't we think of this _before_ doing this work?  Could be a showstopper...

**Comment by rwcarlsen** [comment]
@friedmud - we did think of this before - it isn't a surprise.  Callbacks are problematic because one of the main purposes of implicit stateful promotion is that users can use stateful versions of properties defined by materials they didn't necessarily write.  Callbacks would require materials to have a-priori supported the callbacks - and support the initialization to occur to values desired by the user to boot.

It would be a good idea to find out from @YaqiWang, @bwspenc, @dschwen - to what degree the zero-initialization would be insufficient for their use cases.  If zero-initialization turns out to be not good enough in a significant number of cases, then we can work on a convenient way for the initialization to occur outside of the material object that defines the property.

**Comment by friedmud** [comment]
Let's break this down into cases:

1.  A Material declares a Property and its old value and initializes it.  This is essentially the old model (but it still possible).
2.  A Material declares a Property but doesn't directly need to use that property so it doesn't declare an old state.  However, the Material DOES know how to initialize the value if someone else were to ask for an old state.  This is what I was thinking of above above.
3.  A Material declares a Property but never anticipates anyone wanting an old state so it has no code for initialization.  Instead... one of the _retrieving_ objects could somehow inject initialization?  A callback?  What do you do if there are multiple competing "retrievers"?
4.  A Material declares a Property but doesn't initialize it.  All retrievers are fine with the initial state being zero (or just uninitialized).  This is essentially what the current PR does.

(1) and (4) seem to be handled ok in the current PR (although, it may be ice to be able to query whether or not a Property has been initialized).

What about (2) and (3)?

**Comment by rwcarlsen** [comment]
That is a good summary.  The problem with callbacks to address 2 is that during initialization, we do not know the c++ type of the object being initialized - so we can't pass it in - and the material object that knows how to initialize it didn't collect its own reference to it through a declare.  I'm not sure we can find a way to make 2 work - we brainstormed in our cube here about it for a bit earlier this week and couldn't come up with anything.  There is still potential to make 3 work though.

**Comment by rwcarlsen** [comment]
...unless the callbacks take something like ``void*`` and do casting - then we can solve 2.

**Comment by friedmud** [comment]
No casting required.

One option is that in `initQpStateful()` the Material uses a unique
identifier to grab the Property values from the MaterialPropertyData (we
would add this to the Material interface of course) and then set it.

**Comment by rwcarlsen** [comment]
That could work - we would have to tweak MaterialData class to make sure those entries aren't NULL despite the property becoming stateful via a different MaterialData instance.

**Comment by friedmud** [comment]
Going that direction with property initialization would also allow Materials to have "optionally stateful" properties within themselves.  That would enable a Material to choose (based on input parameter or whatever) to declare an old state or not based on what it needs.

**Comment by friedmud** [comment]
That said: I would want to see what the code looks like first: and understand what the performance impacts would be.  Initialization is only done once... but we still don't want it to take forever.

**Comment by rwcarlsen** [comment]
@sapitts - any ideas on this new BISON fail:

```
tensor_mechanics/u3si2_eigenstrains/u3si2_vswelling.U3Si2_test.............................. FAILED (EXODIFF) [0.715s]
```

**Comment by sapitts** [comment]
@gambka already has a fix into BISON devel for this test (the test using incremental small strain was merged in yesterday), and the fix for the oneD test is in a MR for Bison now too

**Comment by rwcarlsen** [comment]
@sapitts - Great! - thanks.

**Comment by rwcarlsen** [comment]
@friedmud - for case 3, couldn't we just have them call ``declareProperty[Old/Older]`` in their material and then do the usual thing in their ``intiQpStateful`` but for the extra-material owned property?  Then we would probably want to add a check to prevent duplicate calls to declareProperty[Old/Older] on the same property.

**Comment by YaqiWang** [comment]
Just noticed this thread. If a material declares an old property, it needs to provide `initQpStateful`. If a material does not declare an old property, it needs NOT to provide `initQpStateful`. In the second case, the property is not stateful because it does not depend on its old state directly. If someone try to get old property of a non-stateful property, the best approach I can think of is `yaqi-hickry` Andy referred as, i.e. simply call `computeProperty` to initialize it assuming all depending stuff has been property initialized. No need to over-design the system.

**Comment by bwspenc** [comment]
I have a few thoughts on this:
- Only the material that is computing the property should initialize itself.
- I haven't looked through the code to confirm this, but my guess is that the vast majority of the time, the only thing that is done in `initQpStatefulProperties()` is setting things to zero.  Having that default to zeroing plain old data out or calling the default constructor for the data type seems like a great idea, and it seems like it would be fine to not error out if that method isn't defined in a Material that has stateful properties.
- About the case where another Material other than the one that computes a property promotes a property to be stateful, and then `initQpStatefulProperties()` doesn't get called: If the material that computes that property didn't make it stateful, then it would have had no reason to override `initQpStatefulProperties()` to begin with, and that Material couldn't be depending on the old state of that property to compute the new state, so this shouldn't matter.

**Comment by friedmud** [comment]
Zero is not a good default. While that will sometimes work (plastic strain
can often start out zero and grow) for most Material properties they are
going to start at some value and _change_.

These are physical properties; like density, specific heat, Young's
modulus, etc. Zero doesn't usually make any sense. That's why we require
initQpStatefulProperties(): leaving it out is usually an egregious error
and you wouldn't want someone to make that mistake and have it just
silently use zero...

As for your last bullet... let's say that Material A is computing density
and doesn't declare it as stateful. Kernel B asks for the old value of
density (for whatever reason). Someone MUST set the initial value of
density!! It can't just be zero!

It doesn't matter that Material A isn't using the old value of density...
it needs to somehow set the initial value of it.

I'm really starting to feel like this whole thing might be the wrong
direction. The code is the way it is on purpose. Only a Material can know
if it's valid to get an old state of its properties... so only it should
get to declare that.

**Comment by permcody** [comment]
@dschwen, you need to chime in here before this whole thing gets dumped. I believe you wanted this capability the most for your templated derivative materials. We need to come up with a plan for initialization of stateful properties or this PR is dead in the water. As Derek stated, zero just isn't going to cut it in all cases.

**Comment by bwspenc** [comment]
@friedmud Those are good points.  This seems to be leading to requiring every material to define `initQpStatefulProperties()` (or something like it) regardless of whether the old state is actually used by anything.

**Comment by permcody** [comment]
A less Draconian approach would be to leave it optional like `computeQpJacobian` but throw an error when a developer attempts to actually use it and that definition is missing. We already have a mooseWarning() in the BASE CLASS implementation.

**Comment by bwspenc** [comment]
@permcody I agree that would be good, but from my discussion with @rwcarlsen yesterday, it sounded like that wouldn't work because if another Material promoted a property to be stateful, there was no way to force `initQpStatefulProperties()` on the Material that computes that property to get called.

**Comment by rwcarlsen** [comment]
I just added a commit that seems to correctly identified stateful-promoted properties inside material objects to call their initQpStateful functions.  I also restored the original warning for not overriding initQpStatefulProperties when it gets called.  This should resolve most remaining concerns I think.

**Comment by bwspenc** [comment]
@rwcarlsen It sounds like you've resolved any concerns I had.

**Comment by rwcarlsen** [comment]
Except that breaks module tests that promote properties to stateful that are owned by material classes that don't override ``initQpStatefulProperties`` and these tests promote warnings to errors :(

**Comment by bwspenc** [comment]
@rwcarlsen That make sense.  To make any property usable as a stateful property by another material that promotes it to be stateful, I guess we would have to require every material to provide `initQpStatefulProperties()`.  However, I think that as long as the code errors out if it tries to call that, that would alert us that we would need to implement that for a particular non-stateful material, which would be a reasonable solution in my opinion.

**Comment by friedmud** [comment]
Right - the next problem is that a Material needs to know _which_ properties need to be initialized.

This goes back to [what I said a few days ago](https://github.com/idaholab/moose/pull/8278#issuecomment-272553463)

Consider this scenario:

Material A declares two properties: `density` and `thermal_conductivity`.

Kernel B requests the old state of `density`... but NOTHING (anywhere) ass for the old state of `thermal_conductivity`.

If Material A were to implement `initQpStatefulProperties()` to initialize both `density` and `thermal_conductivity` then there would be a problem... because the memory for `thermal_conductivity` never got set aside.

Instead: we should change the function to `initQpStatefulProperties(unsigned int prop)`... which asks a material to initialize exactly _one_ property.  That way each property can be individually initialized.

But this opens up a HUGE FREAKING can of worms.  What if two properties initial values depend on eachother?  How do we set the dependency ordering for `initQpStatefulProperties()`?

Ok - scrap that.  That's a bad idea.

Maybe in `initQpStatefulProperties()` you have the ability to call `isStateful(prop_name)` (or we could use an identifier if using a name is too slow).  That way you would check `isStateful()` for each property before attempting to initialize it.

Not the best... but it could get it done.

**Comment by bwspenc** [comment]
@friedmud I see your point, although is it really a problem for a Material to set the value of a non-stateful property in `initQpStatefulProperties()`?  It's my understanding that we should only be setting the current properties in that method, and not the old properties (I don't think we should ever be setting those anywhere, right?  If that's the case, they should probably be const.)  The new state that just got set gets copied to the old state after that call behind the scenes.  If that's the case, it doesn't seem like there should be any issue with setting memory aside for a non-stateful property (although that depends on how it is implemented -- I don't really know this code that well).

**Comment by friedmud** [comment]
lol @YaqiWang I'm not ignoring them.  I had similar thoughts... but there are still problems.  The "initial" value might still not be computable based on the initial condition.

There are also issues with Materials that _do_ declare some properties as stateful and others _not_... but then something else promotes one of the "not stateful" properties to stateful.

Now: do you still just compute the properties on initial?  No... because generally the computation of stateful properties doesn't work right during initial (that's the reason why `initQpStatefulProperties()` exists in the first place).

Anyway: I think it's a good thought... but the reality is a bit more complicated than that.

**Comment by friedmud** [comment]
@bwspenc that's an astute observation!  You are absolutely right.

Ok.  So now I think we're good to go (probably with something like where the current PR is).  There are three cases:

1.  A Material does not declare anything as stateful and does _NOT_ provide `initQpStatefulProperties()`.  This means that no one can request properties from that Material be promoted to stateful.
2.  A Material declares stateful properties and in `initQpStatefulProperties()` it is responsible for setting the initial value of _all_ properties (even the non-stateful ones) just in case someone promoted them.
3.  A Material doesn't declare any stateful properties but can implement `initQpStatefulProperties()` to set the initial value of all of its properties in case anyone happens to ask for an old value of them.

In light of (2) we may consider renaming `initQpStatefulProperties()` to `initQpProperties()`... you should set the initial value of ALL Material properties... not just "known" stateful ones.

**Comment by friedmud** [comment]
BTW: Not providing `initQpStatefulProperties()` when one of your properties _is_ stateful or has been promoted to stateful should be a `mooseError()` (not a warning)

**Comment by YaqiWang** [comment]
Like initial condition and aux kernel on initial can coexist for an aux variable, `initQpStatefulProperties()` and
```
void computeProperties()
{
  if (in FEProblem::initialSetup())
  {
     // some initialization here up to users
  }
}
can coexist. If the material does not have stateful properties, neither should be implemented. It could be a good idea to have another function `computeQpStatefulProperties()`.

It is really user's job to make this right. MOOSE just need to follow the following rules:
1. call `initQpStatefulProperties()` when material contains stateful properties;
2. do not call `initQpStatefulProperties()` when material does contain stateful properties;
3. apply normal rule on calling `computeProperties()` when evaluating https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L609.

The only extra thing moose might need to do is to make sure  `computeProperties()` of the material, which has not stateful properties but somewhere its old properties are required, being called.

I think we also need to check if problem is transient when `declarePropertyOld` or `declarePropertyOlder` is called. I know currently `isTransient` is abused, but it should be fixed when the eigen executioner refactoring is done.

**Comment by YaqiWang** [comment]
BTW, https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L646 is really hacky and should be removed! It is rather individual materials being fixed but not this hack.

**Comment by friedmud** [comment]
Ok @YaqiWang ... we accept Pull Requests.

That huge comment there is from me... after many hours of trying to get the tests to pass that code ended up where it is and the way it is.  The world is complicated my friend... there are lots of apps using stateful materials and restart and many of them require very particular ordering of things.

**Comment by YaqiWang** [comment]
I am not blaming you @friedmud . Like we add the legacy flags, we need to push app developers to remove the legacy seriously. I am making comments because we are living in a multiphysics world and those wrong things will affect me.

**Comment by bwspenc** [comment]
@friedmud I like your plan.  I also like the proposed rename of `initQpStatefulProperties()`, although we can save that for later.

What happens if one property got initialized in `initQpStatefulProperties()` but another one did not?  We have a lot of models that probably only initialize the stateful properties, but they may have other non-stateful properties that don't get initialized there.  I assume you don't really have a way of checking for that case.  I would hope that they would just get initialized to zero if they weren't set to something else.

**Comment by rwcarlsen** [comment]
@bwspenc - If they didn't otherwise set them in initQpStatefulProps then they would still be zero-initialized.

**Comment by friedmud** [comment]
Yeah - it will need to be a thing we change over time.  We'll also need to
change the documentation.

I think renaming the function makes things a lot clearer.

BTW: If we do the rename we really need to do a _deprecation_.  This
function is used a TON throughout all of the apps.

**Comment by rwcarlsen** [comment]
created #8339

**Comment by friedmud** [comment]
Over in #8339 @YaqiWang said:

>This abuse stateful material properties. It causes a consequence of more memory consumption. Stateful is not obtained free, we will need to store the properties on all quadrature points! Stateful material property should by definition be a property depending on its old states. On the other hand, I do know why this issue comes up. Automatic promotion should be done in my proposed way and whenever it happens, moose should issue a warning. In summary, stateful should be by design but not by consumer. initQpStatefulProperties is called twice in FEProblemBase::initialSetup currently, which should be marked as one of legacies.

Let me say that I'm not 100% convinced about this automatic promotion thing either.  Seems to "solve" a couple of fringe issues... but impacts essentially every Material ever made.  That doesn't make me very happy.

That said, I'm not sure that you're criticisms are on target either.  Let's take them one at a time:

### It causes a consequence of more memory consumption. 

Actually: it may lead to _less_ memory consumption.  Why?  Because now, instead of a Material having _guess_ about which properties _may_ needed to be stateful... only _exactly_ those that need to be stateful will be.

### Stateful material property should by definition be a property depending on its old states.

No: they are properties which _provide_ old states.  Those old states could be used in the production of new values of the property, or they may not.  But the old state is _available_ for whatever use.

### moose should issue a warning

Nonsense.  Maybe we could provide a diagnostic printout of the properties that have old states in case you want to inspect it.  But there's no reason to issue a warning.

### stateful should be by design but not by consumer.

Consider this.  For heat conduction time derivative we generally write `rho*cp*dT/dt`... but master Martineau will tell you that it should _actually_ be `d(rho*cp*T)/dt` ... which would first order finite difference into: `(rho*cp*T - rho_old*cp_old*T_old)/dt`

Now: Any old material producing density and specific heat won't declare them as being stateful... because the old states are not needed in the Material.... BUT!  The old states _are_ needed in the calculation!

No: It actually makes a ton of sense to automatically promote Material properties to being stateful based on whether or not their old states are _used_.

**Comment by YaqiWang** [comment]
You have to admit that he old state of a non-stateful property can be reevaluated based on the other old states, like the old solutions, old other properties, etc. So you really do not have to promote the property to stateful. That is what I mean more memory consumption. I am not completely against auto promotion here. It is just the way how we approach this. Lazy creating the old state is convenience but with price.

**Comment by bwspenc** [comment]
I agree with what @friedmud is saying above.  @YaqiWang -- We're not asking for this because we want to be lazy. In the tensor_mechanics module, we are developing a set of materials that are intended to be very modular.  Each one of these performs a small part of the calculation, and we want them to be interchangeable.

We have materials A, B, C, and D, where B depends on A, C depends on B, and D depends on C.  There are multiple options for which specific materials you can use for materials A, B, C, or D.  Material B may or may not need the old state of material A, but there's no way for material A to know that.  Depending on the formulation, material A may or may not need its old state to compute its new state.  Right now, we are relying on user input to force material A to be stateful when material B needs that old state.  Currently, if the user uses a version of material B that requires the old state of material A, the system will silently return a pointer to garbage. That's very bad!

This automatic state promotion will prevent this error when the old state of a non-stateful material is requested, and make the system much more user friendly because we will be able to eliminate the parameters the user now must specify to make a material stateful.  I can't see how this would use any more memory than the current system unless someone went out of their way to ask for the old state of a bunch of materials that they didn't actually need.

I need to look at the implementation here, but what I would like to see is that the old state is only created when something requests it, whether that is the material that computes that property or some other material. That would be a shift from the current model where the old state is created by declaring it, even though it may not actually be used. Furthermore, we should only be able to get a const reference to the old state, since we shouldn't ever need to modify the old state (at least I can't think of a good reason to do that).  If anything, I would expect this to result in less memory usage because it would eliminate the creation of stateful data when it isn't needed.

**Comment by bwspenc** [comment]
OK, I just looked at the code, and this is a step toward the model where the stateful properties are created by getting them rather than declaring them.  I'd strongly advocate that we then take the next step and deprecate `declarePropertyOld()` et. al.  My reasons for this are:
- We won't need them anymore.
- They can be used carelessly to allocate storage for stateful data that isn't needed.
- They return writeable references to the old state, which gives a lot of opportunities for bugs.

**Comment by YaqiWang** [comment]
People can use auto promotion carelessly too.
We can make `declarePropertyOld()` return const reference because they never needs to be writable if the code is properly designed. `declarePropertyOld()` will just mark a property to be stateful and give users the readable access to the old property. Old property should be always updated by MOOSE.
And again, I am not against the auto promotion. It can be a nice feature and make lots of things easy, although it may result into abuse by users.

**Comment by YaqiWang** [comment]
Now after further thinking, `declarePropertyOld()` and `getPropertyOld()` really have no difference, it is just where we call them in the material. If we call them in the material where the property is declared, it is explicit promotion, otherwise it is implicit promotion. Explicit promotion requires users to implement `initQpStatefulProperties()` or `computeQpStatefulProperties` or both. MOOSE will just call `computeQpProperties` for the Implicit promotion.

**Comment by rwcarlsen** [comment]
@YaqiWang declare and get are indeed basically the same - which is the reasoning behind deprecating the declares.  But we don't ever want to users to "compute" stateful properties - that is the framework's job.  Explicit promotion is like premature anti-optimization though.  Why not just provide the ability to initialize stateful properties only if they are needed?

**Comment by permcody** [comment]
@YaqiWang - I feel like Ben and Derek are onboard with the changes but you still have several concerns about these changes. Please feel free to stop by the cube to talk with Robert and I about them. Let's make sure you are comfortable with these changes and your concerns are addressed before we make these changes.

**Comment by YaqiWang** [comment]
@rwcarlsen It is because there are properties who depend on its own old state, which I call them "truly" stateful. For them, you must provide initial condition. You probably want explicit promotion for them.

**Comment by friedmud** [comment]
@YaqiWang even properties that don't depend on their old state need a value set for their initial condition: and that value might differ from what you would get by just evaluating the property at time zero.

There is no reason to treat any property as "special".  There are now only two options:

1.  A property has an old state and needs an initial value.
2.  It doesn't.

What the actual computation is for computing that property simply doesn't matter.

**Comment by rwcarlsen** [comment]
@YaqiWang just finished a lengthy discussion with us here.  He agreed that this PR is a good step forward.  His remaining concerns relate to how we deal with stateful property initialization vs initial conditions - which are not so directly affected by this PR.  He basically has initial conditions for stateful material properties that depend on initialization of stateful material properties.  So it is a dependency resolution issue which he said would be nice if it could be solved in Yak by putting code a new initialization function that runs after initQpStatefulProperties.  We should probably move this discussion to its own issue - perhaps #5804.

**Comment by YaqiWang** [comment]
Why do you want to have a different evaluation on initial for a normal property? That sounds to me a bug.

**Comment by bwspenc** [comment]
@YaqiWang If I understand your question correctly, I think the answer is that we need to do a special calculation at initialization because at that point, we can't use the old properties.  Otherwise, there really shouldn't be any difference. If there were some way to detect that you were in the initialization phase in `computeQpProperties()` it seems like we wouldn't need a special init function, which would be nice.

**Comment by YaqiWang** [comment]
Yes I am using `if (_t == _app.getStartTime())`, but it a little ugly and I rather MOOSE handle it. In `initQpStatefulProperties`, other normal properties are not available, which the evaluation depends on. BTW, this evaluation cannot have dependency on its own old property (unitialized value) and is better to not have dependency on other old properties (initial state should be 'initial', why having an old initial!).

**Comment by friedmud** [comment]
Ok - well... I'm certainly willing to try a path where we get rid of `initQpStatefulProperties()` all together and just switch to something where we check a boolean in `computeQpProperties()`.  I can definitely understand the appeal of it... it would certainly make automatic promotion work more smoothly for all Materials.

**Comment by friedmud** [comment]
We could just call that boolean `_initial` so you can just do a quick:

```
if (_initial)
  do_initial_stuff
else
  do_normal_stuff
```

Any Material that doesn't need to do anything special on initial will then just do The Right Thing (TM) hopefully...

**Comment by friedmud** [comment]
I do swear that there were _reasons_ why we added `initQpStatefulProperties()` though.

I'm sure we'll find out... 😉

**Comment by permcody** [comment]
I don't think there were any real reasons other than we wanted to avoid branching in the normal compute area. There's also an assumption that you do do things like access post processing values but there's nothing stopping you from doing that.

**Comment by rwcarlsen** [comment]
I don't think this design discussion about initialization and any
corresponding changes really belong in this PR - which doesn't really
change anything about the existing initQpStatefulProperties.

**Comment by rwcarlsen** [comment]
@bwspenc, @sapitts - the three failing BISON tests fail with this error:

```
Material "fuel_thermal_meso" provides one or more stateful properties but initQpStatefulProperties() was not overridden in the derived class.
```

A few now-auto-stateful props just need initQpStateful's added to their classes - a trivial (i.e. empty) implementation would fix the error here - although you may want a slightly *smarter* implementation.  It should be a simple/quick fix.  I could take a stab at the fix or someone more familiar with BISON can.

**Comment by rwcarlsen** [comment]
Bison materials ``ThermalU3Si5UN`` and ``ThermalUO2FissionGas`` need initQpStatefulProperties implementations to fix the failures.

**Comment by bwspenc** [comment]
@rwcarlsen Have you started the BISON fix already?  If not, I can do it.

**Comment by rwcarlsen** [comment]
I haven't started anything.

**Comment by bwspenc** [comment]
@rwcarlsen I just submitted a BISON MR that fixes the issue with those tests.  I believe it also fixes the other issue with multiple declaration of materials.  It's along the same lines as your MR that's sitting out there, so we won't need your version.

**Comment by rwcarlsen** [comment]
@bwspenc sounds good.

**Comment by bwspenc** [comment]
@rwcarlsen The BISON fixes just got merged.  They should also fix the other issue with duplicate material registration.  Your code changes should prevent code like that from making it the codebase in the future.

**Comment by rwcarlsen** [comment]
@friedmud - All green.

**Comment by friedmud** [comment]
Ok - so we're going to put off the discussion about @YaqiWang 's suggestion of removing `initQpStatefulProperties` all together?

I would really rather deal with that now.  I don't want to have to email our user base telling them that things have changed because of this PR... and then jerk them around by changing it again soon.

Or, are you thinking that this PR can be a "silent" update (shouldn't effect anyone) so we don't need to tell anyone about the change?

File: framework/src/materials/GenericConstantMaterial.C [hunk 14]
```diff
@@ -46,6 +46,12 @@ GenericConstantMaterial::GenericConstantMaterial(const InputParameters & paramet
 }
 
 void
+GenericConstantMaterial::initQpStatefulProperties()
```
Comment (YaqiWang) [inline framework/src/materials/GenericConstantMaterial.C]: I do not think this is right!

File: modules/solid_mechanics/src/materials/total_strain/SolidMechanicsMaterial.C [hunk 15]
```diff
@@ -24,6 +24,11 @@ InputParameters validParams<SolidMechanicsMaterial>()
   return params;
 }
 
+void
```
Comment (YaqiWang) [inline modules/solid_mechanics/src/materials/total_strain/SolidMechanicsMaterial.C]: This looks to me not right.

File: framework/src/materials/Material.C [hunk 16]
```diff
@@ -100,15 +102,25 @@ Material::Material(const InputParameters & parameters) :
...
+      return;
+    }
+  }
 }
 
 void
 Material::initQpStatefulProperties()
 {
-  mooseDoOnce(mooseWarning(std::string("Material \"") + name() + "\" declares one or more stateful properties but initQpStatefulProperties() was not overridden in the derived class."));
+  mooseDoOnce(mooseError(std::string("Material \"") + name() + "\" provides one or more stateful properties but initQpStatefulProperties() was not overridden in the derived class."));
```
Comment (YaqiWang) [inline framework/src/materials/Material.C]: This function should not be called after properties before all non-stateful auto promoted of a material.

File: framework/src/materials/Material.C [hunk 17]
```diff
@@ -100,15 +102,25 @@ Material::Material(const InputParameters & parameters) :
...
 Material::initStatefulProperties(unsigned int n_points)
 {
-  if (_has_stateful_property)
-    for (_qp = 0; _qp < n_points; ++_qp)
-      initQpStatefulProperties();
+  // checking for statefulness of properties via this loop is necessary
+  // because owned props might have been promoted to stateful by calls to
+  // getMaterialProperty[Old/Older] from other objects.  In these cases, this
+  // object won't otherwise know that it owns stateful properties.
+  for (auto& prop : _supplied_props)
```
Comment (YaqiWang) [inline framework/src/materials/Material.C]: space between `auto` and `&``.

**Comment by rwcarlsen** [comment]
This should more or less be a silent update.  The only difference for users is now they won't be unknowingly using uninitialized garbage when they use stateful properties that weren't declared.

File: framework/src/materials/Material.C (hunk 17 above)
Comment (YaqiWang) [inline framework/src/materials/Material.C]: I do not think we want to change this function as we discussed. Normal materials does not need this and it could create the conflict between 'initial condition' and 'initial evaluation'.

File: framework/src/materials/Material.C (hunk 16 above)
Comment (rwcarlsen) [inline framework/src/materials/Material.C]: Could you be more specific - I'm not sure what you are suggesting here.

**Comment by YaqiWang** [comment]
But you changed the design!

File: framework/src/materials/GenericConstantMaterial.C (hunk 14 above)
Comment (rwcarlsen) [inline framework/src/materials/GenericConstantMaterial.C]: What would you suggest as a better solution?  This material declares properties that are used as stateful in various tests - so as per original MOOSE behavior (which is not changed in this PR) - the material class needs to implement/override stateful prop initialization function.

**Comment by rwcarlsen** [comment]
@YaqiWang - the only thing different from the user perspective is it will be harder for them to write broken code that uses properties as stateful that aren't actually being initialized/updated/tracked as stateful by MOOSE.  They can still do things exactly as before with get/declare's for properties.  There are no new methods/functions, no renamed functions, etc.  If they use get/declare property functions as the were suppose to before, they will get the same behavior as before.

File: framework/src/materials/Material.C (hunk 16 above)
Comment (YaqiWang) [inline framework/src/materials/Material.C]: If the only place this function is called is in `ComputeMaterialsObjectThread`, which should be, this should be fine.

File: framework/src/materials/GenericConstantMaterial.C (hunk 14 above)
Comment (YaqiWang) [inline framework/src/materials/GenericConstantMaterial.C]: The suggestion is that this function should be never called because this material does not `getPropertyOld`.

**Comment by friedmud** [comment]
I think I'm with @rwcarlsen on this currently: let's get this in because it's a good change toward where we want to go... and then work on the _next_ PR which will remove `initQpStatefulProperties()` and replace it with conditional evaluation within `computeQpProperties()` and an initial evaluation.

Can we get a consensus that that's a good idea?

File: examples/ex09_stateful_materials/src/materials/ExampleMaterial.C [hunk 18]
```diff
@@ -32,10 +32,10 @@ ExampleMaterial::ExampleMaterial(const InputParameters & parameters) :
     // valued property named "diffusivity" that Kernels can use.
     _diffusivity(declareProperty<Real>("diffusivity")),
 
-    // Declare that we are going to have an old value of diffusivity
+    // Retrieve/use an old value of diffusivity.
```
Comment (YaqiWang) [inline examples/ex09_stateful_materials/src/materials/ExampleMaterial.C]: I do want to request changes in the PR.

**Review by YaqiWang — CHANGES_REQUESTED** [review]

File: framework/src/materials/Material.C (hunk 17 above)
Comment (rwcarlsen) [inline framework/src/materials/Material.C]: This is the *only* way for promoted-stateful properties to be initialized to anything other than zero.

File: framework/src/materials/Material.C (hunk 16 above)
Comment (rwcarlsen) [inline framework/src/materials/Material.C]: That is correct as far as I know - it is only called from there.

File: framework/src/materials/Material.C [hunk 19]
```diff
@@ -100,15 +102,25 @@ Material::Material(const InputParameters & parameters) :
...
+  {
+    if (_material_data->getMaterialPropertyStorage().isStatefulProp(prop))
+    {
+      for (_qp = 0; _qp < n_points; ++_qp)
+        initQpStatefulProperties();
```
Comment (YaqiWang) [inline framework/src/materials/Material.C]: My suggestion is:
```
unsigned int num_stateful_properties = 0;
for (auto& prop : _supplied_props)
  if (_material_data->getMaterialPropertyStorage().isStatefulProp(prop))
    ++num_stateful_properties;

if (_has_stateful_propperties) // strictly speaking, we should check num_stateful_properties == number of stateful properties declared by this material.
  initQpStatefulProperties();
else if (num_stateful_properties > 0)
  mooseError();
```

File: framework/src/materials/GenericConstantMaterial.C (hunk 14 above)
Comment (YaqiWang) [inline framework/src/materials/GenericConstantMaterial.C]: Then it should be an error. We are not supporting auto promotion in this PR, arenot we?

File: framework/src/materials/Material.C (hunk 16 above)
Comment (YaqiWang) [inline framework/src/materials/Material.C]: Sorry I ignored the direct caller is `initStatefulProperties()`.

**Comment by bwspenc** [comment]
I think this code is good to go as-is.  Let's get this in and then look at doing something different with initQpStatefulProperties() next.  This will only impact code that currently improperly gets the old state for a non-stateful property.

File: framework/src/materials/Material.C (hunk 19 above)
Comment (rwcarlsen) [inline framework/src/materials/Material.C]: This prevents promoted properties to be initialized to anything other than zero - which is unacceptable IMO.

Comment (YaqiWang) [inline framework/src/materials/Material.C]: Another thing, `initQpStatefulProperties` can be called multiple times if number of stateful props is greater than 1.

**Comment by YaqiWang** [comment]
This PR is great! And now I can see `GenericConstantMaterial::initQpStatefulProperties()` is a bandage of the current mess. It should be removed in the future. Now I guess I only have a minor comment in `Material::initStatefulProperties()`.

File: framework/src/materials/Material.C (hunk 19 above)
Comment (friedmud) [inline framework/src/materials/Material.C]: @YaqiWang is right - this loop isn't right.  You need to find out if there are any stateful properties and then call `initQpStatefulProperties()` once....

File: framework/src/materials/Material.C (hunk 17 above)
Comment (YaqiWang) [inline framework/src/materials/Material.C]: I am not sure but this could be not exactly. If the material `computQpProperties` is called in `FEProblemBase::initialSetup`, the old property should be properly initialized. However the material will not be evaluated on initial if there is no other objects depending on it. This investigation can leave to another PR, which hopefully will be in soon.

File: framework/src/materials/Material.C (hunk 19 above)
Comment (rwcarlsen) [inline framework/src/materials/Material.C]: Nope - see the early return just after the quadrature point loop?

Comment (YaqiWang) [inline framework/src/materials/Material.C]: Oh, missed it. It is better to make this PR closer to our final version though. A request could be from user to know which property is promoted. But I guess it can be addressed in the future. I am good now.

**Comment by YaqiWang** [comment]
@rwcarlsen I apologize for my ignorance. This is good to me now. I do want `GenericConstantMaterial::initQpStatefulProperties()` gets removed very soon. @friedmud You suggestion of removing `initStatefulProperties` is too risky at this point and can be considered at the end of the follow-on PR of this one.

**Comment by rwcarlsen** [comment]
ping reviewers - this should be ready to go.

**Comment by friedmud** [comment]
Looking...

File: framework/include/materials/MaterialProperty.h [hunk 20]
```diff
@@ -330,7 +324,7 @@ template<typename P>
 PropertyValue *_init_helper(int size, PropertyValue * /*prop*/, const P*)
 {
   MaterialProperty<P> *copy = new MaterialProperty<P>;
-  copy->_value.resize(size);
+  copy->_value.resize(size, P{});
```
Comment (friedmud) [inline framework/include/materials/MaterialProperty.h]: Is the default constructor required here?  Shouldn't it do that by default?

(Honest question)

File: framework/include/materials/MaterialProperty.h [hunk 21]
```diff
@@ -340,7 +334,7 @@ PropertyValue *_init_helper(int size, PropertyValue * /*prop*/, const std::vecto
 {
   typedef MaterialProperty<std::vector<P> > PropType;
   PropType *copy = new PropType;
-  copy->_value.resize(size);
+  copy->_value.resize(size, std::vector<P>{});
```
Comment (friedmud) [inline framework/include/materials/MaterialProperty.h]: This one too - I don't think there's a reason to do this.

File: framework/include/materials/MaterialPropertyInterface.h [hunk 22]
```diff
@@ -186,7 +186,7 @@ class MaterialPropertyInterface
   Moose::MaterialDataType _material_data_type;
 
   /// Pointer to the material data class that stores properties
-  MooseSharedPointer<MaterialData> _material_data;
+  std::shared_ptr<MaterialData> _material_data;
```
Comment (friedmud) [inline framework/include/materials/MaterialPropertyInterface.h]: Are we getting rid of `MooseSharedPointer` now?

File: framework/src/materials/GenericConstantMaterial.C (hunk 14 above)
Comment (friedmud) [inline framework/src/materials/GenericConstantMaterial.C]: I'm ok with this for now... but let's quickly add another ticket to fix this.

File: framework/src/materials/Material.C (hunk 16 above)
Comment (friedmud) [inline framework/src/materials/Material.C]: Why the `mooseDoOnce()`?  If this errors... the whole simulation stops... regardless of "once" or not.

**Review by friedmud — CHANGES_REQUESTED** [review]
Just a few more small things to either fix or respond to.  It's getting close

File: framework/include/materials/MaterialProperty.h (hunk 20 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialProperty.h]: This is necessary.  Without it, if ``P`` is a POD type then you can get uninitialized garbage.

File: framework/include/materials/MaterialProperty.h (hunk 21 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialProperty.h]: The implicit_stateful test fails non-deterministically without this.

Comment (friedmud) [inline framework/include/materials/MaterialProperty.h]: Just weird - ok ;-)

File: framework/include/materials/MaterialPropertyInterface.h (hunk 22 above)
Comment (rwcarlsen) [inline framework/include/materials/MaterialPropertyInterface.h]: Cody suggested just switching MooseShared -> std::shared whenever I run into it reworking code.

**Review by friedmud — APPROVED** [review]
This looks good - when the testing is complete it can be merged.

I'm getting ready to land... so I may not merge it until later tonight.  If you guys are itchy then someone else can feel free.

**Comment by WilkAndy** [comment]
Thanks for apparently fixing the mesh adaptivity problem, @rwcarlsen .   i'll report back if there are any problems, but i doubt there will be.

a
