### PR TITLE
Make variable check in transfers more picky

### LINKED ISSUE #29961: Variable integrity check on variable names in transfers will accept a variable from the "other" app when the variable is missing from the correct app
### Bug Description

The logic for checkIntegrity of a variable will check both apps for having the variable name in the problem

it should only check the relevant app

### Steps to Reproduce

use a shape evaluation transfer for example
misspell a variable in the source variable
have the correct spelling for an unrelated variable in the target

### Impact

You will still get an error later, but it is confusing to have it so late
Better user experience

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by GiudGiud**
closes #29961

### CODE REVIEW

**Comment by roystgnr** [comment]
No comment on the from-multiapp changes, but ... surely this can't be the right answer for the error output?  I had imagined some sort of special case error throw here, but we're just using `mooseError()` to emit the error message?  There's no way that should be giving us a race condition that's *just here*, out of a zillion other library uses.  And I don't see how it should be giving us a race condition at all, when we're careful in `mooseErrorRaw()` to emit `std::flush` before we abort.

**Comment by GiudGiud** [comment]
well I dont have another theory

**Comment by GiudGiud** [comment]
I think this change is fine regardless of whether it solves the issue. Getting one error message to look at is better than many

**Review by roystgnr — APPROVED** [review]
Agreed that this is probably a change for the better even if it's a red herring for our immediate problem.

**Comment by GiudGiud** [comment]
Test failures related to an unrelated next breakage.

File: framework/include/transfers/MultiAppTransfer.h [hunk 1]
```diff
@@ -38,7 +38,7 @@ class MultiAppTransfer : public Transfer
   /**
    * Utility to verify that the variable in the destination system exists.
    */
-  void variableIntegrityCheck(const AuxVariableName & var_name) const;
+  void variableIntegrityCheck(const AuxVariableName & var_name, bool is_from_multiapp) const;
```
Comment (roystgnr) [inline framework/include/transfers/MultiAppTransfer.h:41]: This appears to have broken SAM: https://civet.inl.gov/job/2718600/

Comment (GiudGiud) [reply framework/include/transfers/MultiAppTransfer.h:41]: the failure I observed, SAM not building, was not related
https://civet.inl.gov/job/2715195/

Comment (GiudGiud) [reply framework/include/transfers/MultiAppTransfer.h:41]: This is a simple fix. I ll make a patch now

Comment (GiudGiud) [reply framework/include/transfers/MultiAppTransfer.h:41]: Patch there
https://git-nse.egs.anl.gov/SAM/SAM/-/merge_requests/1023

**Comment by loganharbour** [comment]
Please be more mindful of unrelated failures and request breakages like this.

We hit an odd break here where a package is stuck due to an app, and the app is stuck due to a package being stuck.
