### PR TITLE
Fix Sideset Retaining Bug in Element Conversion

### LINKED ISSUE #30158: Incorrect Sideset Retaining in MooseMeshElementConversionUtils
### Bug Description

In some cases, the sidesets in the input mesh have extra or missing sides after conversion.

### Steps to Reproduce

This input lead to extra sides in the "outer" sideset

```
[Mesh]
  [ccg]
    type = ConcentricCircleMeshGenerator
    radii = '1'
    rings = '5'
    num_sectors = 8
    has_outer_square = false
    portion = left_half
    preserve_volumes = true
  []
  [biddel]
    type = BoundaryDeletionGenerator
    input = ccg
    boundary_names = 'right'
  []
  [rg]
    type = RevolveGenerator
    input = biddel
    axis_point = '0.0 0.0 0.0'
    axis_direction = '0.0 1.0 0.0'
    nums_azimuthal_intervals = 8
  []
  [tet]
    type = ElementsToTetrahedronsConverter
    input = rg
  []
[]
```

### Impact

Sideset information is compromised during element type conversion.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #30158

### CODE REVIEW

**Review by GiudGiud — COMMENTED** [review]
can we turn on the pedantic exodiff option to get a test to cover this?

**Comment by miaoyinb** [comment]
I added a series of tests to cover all the cases.
I maybe able to merge some elements to reduce numbers of tests.

**Comment by miaoyinb** [comment]
Reduced to three tests

**Comment by miaoyinb** [comment]
ready for review.

File: framework/src/meshgenerators/ElementGenerator.C [hunk 1]
```diff
@@ -37,6 +37,8 @@ ElementGenerator::validParams()
   // Subdomain
   params.addParam<SubdomainName>("subdomain_name", "Subdomain name");
   params.addParam<SubdomainID>("subdomain_id", 0, "Subdomain id");
+  // Sidesets
+  params.addParam<bool>("create_sidesets", false, "Create separate sidesets for each side");
```
Comment (GiudGiud) [inline framework/src/meshgenerators/ElementGenerator.C:41]:
```suggestion
  params.addParam<bool>("create_sidesets", false, "Create separate sidesets for each side. The side index is used as the boundary ID for each sideset.");
```

File: test/tests/meshgenerators/elements_to_tetrahedrons_convertor/gold/pyramid_elem_0_in.e
Comment (GiudGiud) [inline test/tests/meshgenerators/elements_to_tetrahedrons_convertor/gold/pyramid_elem_0_in.e:1]: where do you use this file? I dont see it in the tests

**Review by GiudGiud — COMMENTED** [review]
love the tests. very thorough!

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
test failures are unrelated
