### PR TITLE
Rbg surface num

### LINKED ISSUE #27175: No error thrown if RenameBoundaryGenerator and surface number over 2^15
### Bug Description

The surface id are limited to 2^15. It would be nice to have an error thrown when we rename with higher values instead of the code randomly ceiling our input values. That took me 1 hour to debug my geometry because of that.

### Steps to Reproduce

run that :

`[Mesh]`
`  [refl0]`
`    type = CartesianMeshGenerator`
`    dim = 2`
`    dx = ' 4.0 3.0 2.0'`
`    dy = ' 2.0 3.0 4.0'`
`    ix = ' 4 3 2'`
`    iy = ' 2 3 4'`
`    subdomain_id = '102 101 100 102 101 101 102 102 102 '`
`  []`
`  [refl0_pre]`
`    type = RenameBoundaryGenerator`
`    input = refl0`
`    old_boundary = '0 1 2 3'`
`    new_boundary = '40000 40001 40002 40003'`
`  []`

### Impact

User can debug more quickly.

### [Optional] Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pbehne**
This PR addresses #27175, which reports an issue with the
RenameBoundaryGenerator. When the 'new_boundary' parameter value is given as
boundary id values instead of boundary names, and the new ids are greater than
2^15, type overflow occurs and the boundary is renamed to the largest possible
value for type BoundaryID instead of what the user requested. This PR adds
bounds checking to user-requested boundary and subdomain ids and emits a descriptive error
if the user requests to use id values outside the range of the
respective BoundaryID and SubdomainID types.

Closes #27175

### CODE REVIEW

File: framework/src/meshgenerators/RenameBoundaryGenerator.C [hunk 1]
```diff
@@ -24,33 +24,12 @@ RenameBoundaryGenerator::validParams()
...
-      "'old_boundary_id' or 'old_boundary_name'.",
-      "Use 'new_boundary' instead of 'new_boundary_id'.");
-  params.addDeprecatedParam<std::vector<BoundaryName>>(
-      "new_boundary_name",
-      "The new boundary name(s) for the elements defined by "
-      "'old_boundary_id' or 'old_boundary_name'. If 'new_boundary_id' is not provided and a "
-      "boundary with the given name does not exist, a new boundary ID will be created.",
-      "Use 'new_boundary' instead of 'new_boundary_name'.");
-
-  params.addParam<std::vector<BoundaryName>>(
```
Comment (GiudGiud) [inline framework/src/meshgenerators/RenameBoundaryGenerator.C:49]: These options while deprecated are very useful. 

I have a mesh which uses them, and we should check the VTBin case there are others

Comment (pbehne) [reply framework/src/meshgenerators/RenameBoundaryGenerator.C:49]: VTB is good, see draft PR below.

File: framework/include/utils/MooseMeshUtils.h [hunk 2]
```diff
@@ -289,4 +289,21 @@ void makeOrderedNodeList(std::vector<std::pair<dof_id_type, dof_id_type>> & node
...
+ * Converts a given name (BoundaryName or SubdomainName) into a corresponding ID (BoundaryID or
+ * SubdomainID) and performs bounds checking to ensure that overflow doesn't happen.
+ * @param name Name that is to be converted into an ID.
+ * @return ID type corresponding to the type of name.
+ */
+template <typename T, typename Q>
+Q
+getIDFromName(const T & name)
+{
+  const auto id = stoi(name);
```
Comment (GiudGiud) [inline framework/include/utils/MooseMeshUtils.h:303]: this will always be an int, so if Q is unsigned int we have a problem

maybe stoll ? but we could just use convert in mooseUtils with a big long int type?

File: framework/src/meshgenerators/RenameBoundaryGenerator.C (hunk 1 above)
Comment (GiudGiud) [reply framework/src/meshgenerators/RenameBoundaryGenerator.C:49]: yeah my bad. It was the RenameBlockGenerator that I use the deprecated options for

Comment (GiudGiud) [reply framework/src/meshgenerators/RenameBoundaryGenerator.C:49]: but good idea to check

File: framework/include/utils/MooseMeshUtils.h (hunk 2 above)
Comment (GiudGiud) [reply framework/include/utils/MooseMeshUtils.h:303]: or maybe just use >> like we used to?

File: framework/include/utils/MooseMeshUtils.h [hunk 3]
```diff
@@ -289,4 +289,21 @@ void makeOrderedNodeList(std::vector<std::pair<dof_id_type, dof_id_type>> & node
...
+  if (id < std::numeric_limits<Q>::min() || id > std::numeric_limits<Q>::max())
+    mooseError(name, " is not within the numeric limits of the expected ID type.");
```
Comment (GiudGiud) [inline framework/include/utils/MooseMeshUtils.h:305]: specify the type in the error message with prettyCppName<Q>()

**Review by GiudGiud — CHANGES_REQUESTED** [review]

File: framework/include/utils/MooseMeshUtils.h (hunk 3 above)
Comment (pbehne) [reply framework/include/utils/MooseMeshUtils.h:305]: Where is prettyCppName defined? I don't see it in MOOSE or libmesh, and google gives me nothing.

Comment (loganharbour) [reply framework/include/utils/MooseMeshUtils.h:305]: he means prettyCppType

File: framework/include/utils/MooseMeshUtils.h (hunk 2 above)
Comment (pbehne) [reply framework/include/utils/MooseMeshUtils.h]: See current implementation, which uses stoll.

File: framework/include/utils/MooseMeshUtils.h (hunk 3 above)
Comment (pbehne) [reply framework/include/utils/MooseMeshUtils.h]: prettyCppType demangles `BoundaryName` correctly, but demangles `BoundaryID` as `short`, which is not desirable.

Comment (GiudGiud) [reply framework/include/utils/MooseMeshUtils.h]: Well 'short' is googlable for its size unlike BoundaryID so it may not be so bad?

Comment (pbehne) [reply framework/include/utils/MooseMeshUtils.h]: Yeah, I still think it's better than not putting the type.

File: framework/include/utils/MooseMeshUtils.h [hunk 4]
```diff
@@ -289,4 +289,28 @@ void makeOrderedNodeList(std::vector<std::pair<dof_id_type, dof_id_type>> & node
                          std::vector<dof_id_type> & elem_id_list,
                          std::vector<dof_id_type> & ordered_node_list,
                          std::vector<dof_id_type> & ordered_elem_id_list);
+
+/**
+ * Converts a given name (BoundaryName or SubdomainName) into a corresponding ID (BoundaryID or
+ * SubdomainID) and performs bounds checking to ensure that overflow doesn't happen.
+ * @param name Name that is to be converted into an ID.
```
Comment (GiudGiud) [inline framework/include/utils/MooseMeshUtils.h:296]: Add a note that this should only be used on names that are already known to be digits (use Moose::isDigits)

**Review by GiudGiud — COMMENTED** [review]
good after that one

**Review by GiudGiud — APPROVED** [review]

**Comment by dschwen** [comment]
Are you sure this is the right fix? My approach would be to convert the I'd back to a string and compare it to the original parameter value. At least for integers this would reliably detect any overflow.

**Comment by pbehne** [comment]
> Are you sure this is the right fix? My approach would be to convert the I'd back to a string and compare it to the original parameter value. At least for integers this would reliably detect any overflow.

Good idea. I do wish that you would have posted this before the PR was merged, though.

**Comment by GiudGiud** [comment]
What we have works for all intents and purposes.
long long are really big.
