### PR TITLE
AzimuthalBlockSplitGenerator with quad center elements

### LINKED ISSUE #22422: Seg Fault When Using AzimuthalBlockSplitGenerator with Mesh with Quad Center Elements
## Bug Description
When the input of `AzimuthalBlockSplitGenerator` is a mesh generated by `PolygonConcentricCircleMeshGenerator` with `quad_center_elements` set as `true`.

## Steps to Reproduce
Use `AzimuthalBlockSplitGenerator` with `PolygonConcentricCircleMeshGenerator` and set `quad_center_elements`  as true.

## Impact
`AzimuthalBlockSplitGenerator` should work with blocks that do not contain these quad center elements. Meanwhile, `AzimuthalBlockSplitGenerator` need to throw an error if the users want to split the block that involves the quad center elements. Otherwise the user would be confused.

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #22422

### CODE REVIEW

**Comment by miaoyinb** [comment]
@shikhar413 FYI

**Comment by miaoyinb** [comment]
@GiudGiud This enables use of `AzimuthalBlockSplitGenerator` for meshes with center quad elements.

File: modules/reactor/test/tests/meshgenerators/azimuthal_block_split_generator/tests [hunk 1]
```diff
@@ -64,6 +79,21 @@
...
+      cli_args = 'Mesh/cd/quad_center_elements="true"
+                  Mesh/cd/num_sectors_per_side="4 4 4 4 4 4"
+                  Mesh/cd/ring_block_ids="10 10 20"
+                  Mesh/cd/ring_block_names="center center cd_ring"
+                  Mesh/cd_azi_define/old_blocks="10 20"
+                  Mesh/cd_azi_define/new_block_ids="100 200"
+                  Mesh/cd_azi_define/new_block_names="center_new cd_ring_new"
+                  --mesh-only "azi_block_id_mod_err.e"'
+      expect_err = 'This parameter contains a block that involves center quad elements, the nodes of which should not be moved to match the given angles.'
+      detail = "if old_blocks contains center quad elements."
```
Comment (GiudGiud) [inline modules/reactor/test/tests/meshgenerators/azimuthal_block_split_generator/tests:94]:
```suggestion
      detail = "if the list of blocks whose nodes should be moved contains a block with center quad elements."
```

Comment (GiudGiud) [reply modules/reactor/test/tests/meshgenerators/azimuthal_block_split_generator/tests:94]: we try to avoid naming parameters in the requirements. Parameters could change names and we could forget to update requirements. It s also less readable by someone who would be auditing only

File: modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C [hunk 2]
```diff
@@ -90,6 +90,13 @@ AzimuthalBlockSplitGenerator::generate()
       paramError("old_blocks",
                  "This parameter contains blocks that do not exist in the input mesh.");
 
+  if (std::find(_old_block_ids.begin(), _old_block_ids.end(), mesh.elem_ref(0).subdomain_id()) !=
+          _old_block_ids.end() &&
+      mesh.elem_ref(0).n_vertices() == 4)
```
Comment (GiudGiud) [inline modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C:95]: checking the number of vertices of element 0 might not be an accurate way of checking for center quad elements?

I think I d rather use the meta data here

**Review by GiudGiud — CHANGES_REQUESTED** [review]
first I apologize for the delay on this review.

I dont think I understand this PR.

We dont allow moving the nodes of quad elems because that would likely create some degenerate quads.

But:
- then the sectors arent well cut? The center of the pin wont be cut, it will keep its old shape, possibly remain a circle, while the other rings will be cut nicely in sectors?
- we are skipping all the quads in the pin. If you look at the exodus, block 10 is completely ignored (it s all quads), and block 100 isnt created at all.

**Comment by miaoyinb** [comment]
> first I apologize for the delay on this review.
> 
> I dont think I understand this PR.
> 
> We dont allow moving the nodes of quad elems because that would likely create some degenerate quads.
> 
> But:
> 
> * then the sectors arent well cut? The center of the pin wont be cut, it will keep its old shape, possibly remain a circle, while the other rings will be cut nicely in sectors?
> * we are skipping all the quads in the pin. If you look at the exodus, block 10 is completely ignored (it s all quads), and block 100 isnt created at all.

`AzimuthalBlockSplitGenerator` moves nodes of interest to the specified azimuthal locations and then splits the blocks. It only works with the mesh generated by `PolygonConcentricCircleMeshGeneratorBase`'s derived classes with triangular central elements. If the central elements are set to be quad, the nodes in the central region should not be moved as they are not defined based on azimuthal angles. However, the outer regions can still be split as usually.

In this PR, I am allowing splitting of these outer regions if the central quad elements region is not set to be modified, otherwise an error message is thrown.

File: modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C (hunk 2 above)
Comment (miaoyinb) [reply modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C:95]: Sure

File: modules/reactor/doc/content/source/meshgenerators/AzimuthalBlockSplitGenerator.md [hunk 3]
```diff
@@ -15,6 +15,8 @@ Multiple radial blocks, which are defined by [!param](/Mesh/AzimuthalBlockSplitG
 
 As moving nodes in the azimuthal direction changes the volumes of the circular blocks, the volume preservation radius correction is made if [!param](/Mesh/AzimuthalBlockSplitGenerator/preserve_volumes) is set as true.
 
+If the [!param](/Mesh/AzimuthalBlockSplitGenerator/input) mesh is generated by [`PolygonConcentricCircleMeshGenerator`](/PolygonConcentricCircleMeshGenerator.md) with [!param](/Mesh/PolygonConcentricCircleMeshGenerator/quad_center_elements) set as true, and if the block that contains these quadrilateral central elements is selected in [!param](/Mesh/AzimuthalBlockSplitGenerator/old_blocks), an error message is issued because no nodes in that block should be moved.
```
Comment (GiudGiud) [inline modules/reactor/doc/content/source/meshgenerators/AzimuthalBlockSplitGenerator.md:18]:
```suggestion
If the [!param](/Mesh/AzimuthalBlockSplitGenerator/input) mesh is generated by [`PolygonConcentricCircleMeshGenerator`](/PolygonConcentricCircleMeshGenerator.md) with [!param](/Mesh/PolygonConcentricCircleMeshGenerator/quad_center_elements) set as true, and if the block that contains these quadrilateral central elements is selected in [!param](/Mesh/AzimuthalBlockSplitGenerator/old_blocks), an error message is issued because we currently do not support centered azimuthal splitting of a single quad element.
```

File: modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C [hunk 4]
```diff
@@ -90,6 +90,13 @@ AzimuthalBlockSplitGenerator::generate()
       paramError("old_blocks",
                  "This parameter contains blocks that do not exist in the input mesh.");
 
+  if (std::find(_old_block_ids.begin(),
+                _old_block_ids.end(),
+                getMeshProperty<bool>("quad_center_block_id", _input_name)) != _old_block_ids.end())
+    paramError("old_blocks",
+               "This parameter contains a block that involves center quad elements, the nodes of "
+               "which should not be moved to match the given angles.");
```
Comment (GiudGiud) [inline modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C:98]:
```suggestion
               "This parameter contains a block that involves center quad elements, azimuthal splitting "
               "is currently not supported in this case.");
```

**Comment by GiudGiud** [comment]
so this is to treat the inner ring as a single region, and the outer ring with azimuthal sectors?

is splitting an inner quad region supported?

File: modules/reactor/doc/content/source/meshgenerators/AzimuthalBlockSplitGenerator.md (hunk 3 above)
Comment (GiudGiud) [inline modules/reactor/doc/content/source/meshgenerators/AzimuthalBlockSplitGenerator.md:18]:
```suggestion
If the [!param](/Mesh/AzimuthalBlockSplitGenerator/input) mesh is generated by [`PolygonConcentricCircleMeshGenerator`](/PolygonConcentricCircleMeshGenerator.md) with [!param](/Mesh/PolygonConcentricCircleMeshGenerator/quad_center_elements) set as true, and if the block that contains these quadrilateral central elements is selected in [!param](/Mesh/AzimuthalBlockSplitGenerator/old_blocks), an error message is issued because no nodes in that block should be moved. The central pattern of quad elements is not designed to be arbitrarily modified to align its nodes with azimuthal sectors.
```

**Comment by miaoyinb** [comment]
> so this is to treat the inner ring as a single region, and the outer ring with azimuthal sectors?

Yes. If the central elements are quad, they are not constructed based on azimuthal intervals and thus cannot be moved according to azimuthal angles. For all the outer regions, they can be split if needed.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Thanks for the PR!
