### PR TITLE
Get submodule hashes with git ls-files

### LINKED ISSUE #18616: Git Submodule Status Still Returns Negative Hashes After Init
## Bug Description
I'm guessing this is just a new Git thing we'll have to account for.  We started having issues with KP-SAM, because `git submodule init moose` was kicking back a negative "commit hash" like it would before `git submodule init moose`.  As you can see below, this also occurs for us with MOOSE and its submodules.

```
[ec2-user@ip-172-31-13-201 moose]$ git submodule status
-def87c9916e53ad08034f93db8fd82fb42578a85 large_media
-ffab5c914090ad625645faa1bb4251d6b46f1c26 libmesh
-880d209961346e912b7f043c3872310738b1a095 moosetools
-09da24df01e50defd94bc4f7396f866a808ecea5 petsc
[ec2-user@ip-172-31-13-201 moose]$ git submodule init
Submodule 'large_media' (https://github.com/idaholab/large_media) registered for path 'large_media'
Submodule 'libmesh' (https://github.com/libMesh/libmesh) registered for path 'libmesh'
Submodule 'moosetools' (https://github.com/idaholab/moosetools) registered for path 'moosetools'
Submodule 'petsc' (https://gitlab.com/petsc/petsc.git) registered for path 'petsc'
[ec2-user@ip-172-31-13-201 moose]$ git submodule status
-def87c9916e53ad08034f93db8fd82fb42578a85 large_media
-ffab5c914090ad625645faa1bb4251d6b46f1c26 libmesh
-880d209961346e912b7f043c3872310738b1a095 moosetools
-09da24df01e50defd94bc4f7396f866a808ecea5 petsc
```

## Steps to Reproduce
Currently testing on Amazon Linux 2 (`yum` package manager) with Git 2.32.0.  
1. Start with a fresh clone of MOOSE
1. Run `git submodule status` to see the negative "hashes"
1. Run `git submodule init` to init submodules
1. Run `git submodule status` to see that commit "hashes" remain negative

## Impact
We recently updated our Jenkins nodes to have the setup given in the last section, so without this in place, our build will start breaking.  I will furnish a PR ASAP.

### PR DESCRIPTION
**Pull request by herter4171**
## Reason
For some reason `git submodule status` doesn't show commit hashes after `git submodule init` anymore, so we have to get those with `git ls-files`.

## Design
Changed `docker_ci/Jenkinsfile` to use `git ls-files`.  Also added package manager installs for `sudo` for downstream use.

## Impact
No change to the framework.  Fixes #18616.

### CODE REVIEW

File: docker_ci/apt_installs.sh [hunk 1]
```diff
@@ -30,7 +30,8 @@ apt-get install -y \
   flex \
   libboost-all-dev \
   emacs \
-  libgtest-dev
+  libgtest-dev \
+  sudo
```
Comment (loganharbour) [inline docker_ci/apt_installs.sh:34]: Why is this needed now?

Comment (herter4171) [reply docker_ci/apt_installs.sh:34]: Mostly convenience, and it seemed too petty for its own issue/PR.  When I test images, I want to be able to switch seamlessly between `root` to install packages and the user `dev` to make sure that environment works without involving another shell by just doing `sudo -u dev /bin/bash`.  Basically, we need `dev` so that people can't do non-standard things, and it's also much easier to enable SSH for a non-root user for multi-container MPI runs.

Comment (loganharbour) [reply docker_ci/apt_installs.sh:34]: 👍🏼

**Review by loganharbour — APPROVED** [review]
