### PR TITLE
Consider non-readable paths as unavailable directories

### LINKED ISSUE #27198: Patch `MooseUtils::pathIsDirectory` for protected paths
### Motivation

`MooseUtils::pathIsDirectory` will currently throw an exception from `std::filesystem` if it is called with a path that is not readable due to permissions.

### Design

Implement `MooseUtils::pathIsDirectory` such that it will return false if the path is not readable.

### Impact

Minor. Fixes issues pertaining to `Registry::addDataFilePath()` for absolute paths that are not readable.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #27198

### CODE REVIEW

File: framework/src/utils/MooseUtils.C [hunk 1]
```diff
@@ -246,7 +246,10 @@ pathExists(const std::string & path)
 bool
 pathIsDirectory(const std::string & path)
 {
-  return std::filesystem::is_directory(path);
+  // We use the error_code implementation of this so that we suppress any issues with
```
Comment (dschwen) [inline framework/src/utils/MooseUtils.C:249]:
```suggestion
  // We use the non-throwing overload of this so that we suppress any issues with
```

**Review by dschwen — APPROVED** [review]
